    - oidc:
        client-id: "client-id-of-this-service"
        # See [EncryptionFilter](https://helidon.io/docs/latest/apidocs/io.helidon.config.encryption/io/helidon/config/encryption/EncryptionFilter.html) for details about encrypting passwords in configuration files.
        client-secret: "client-secret-of-this-service"
        identity-uri: "http://your-tenant.identity-server.com"
        frontend-uri: "http://my-service:8080"
        audience: "http://my-service"
        cors:
          allow-origins: ["http://foo.com", "http://there.com"]
          allow-methods: ["PUT", "DELETE"]
        outbound:
          - name: "internal-services"
            hosts: ["*.example.org"]
            outbound-token:
              header: "X-Internal-Auth"
