
# 1st stage, build the app
FROM container-registry.oracle.com/java/jdk-no-fee-term:17 as build

WORKDIR /usr/share

# Install maven
RUN set -x && \
    curl -O https://archive.apache.org/dist/maven/maven-3/3.8.4/binaries/apache-maven-3.8.4-bin.tar.gz && \
    tar -xvf apache-maven-*-bin.tar.gz  && \
    rm apache-maven-*-bin.tar.gz && \
    mv apache-maven-* maven && \
    ln -s /usr/share/maven/bin/mvn /bin/

WORKDIR /helidon

# Create a first layer to cache the "Maven World" in the local repository.
# Incremental docker builds will always resume after that, unless you update
# the pom
ADD pom.xml .
RUN mvn package -Dmaven.test.skip -Declipselink.weave.skip

# Do the Maven build to create the custom Java Runtime Image
# Incremental docker builds will resume here when you change sources
ADD src src
# Don't generate CDS archive to work around JVM bug https://bugs.openjdk.org/browse/JDK-8274944
RUN mvn package -Pjlink-image -DskipTests -Djlink.image.addClassDataSharingArchive=false
RUN echo "done!"

# 2nd stage, build the final image with the JRI built in the 1st stage

FROM container-registry.oracle.com/os/oraclelinux:9-slim
WORKDIR /helidon
COPY --from=build /helidon/target/{{artifactId}}-jri ./
ENTRYPOINT ["/bin/bash", "/helidon/bin/start"]
EXPOSE 8080
