
# 1st stage, build the app
FROM maven:3.8.4-openjdk-17-slim as build

WORKDIR /helidon

# Create a first layer to cache the "Maven World" in the local repository.
# Incremental docker builds will always resume after that, unless you update
# the pom
{{#poms}}
ADD {{.}} {{.}}
{{/poms}}
RUN mvn package -Dmaven.test.skip {{#docker-phase1-options}}{{.}}{{^last}} {{/last}}{{/docker-phase1-options}}

# Do the Maven build!
# Incremental docker builds will resume here when you change sources
{{#src-dirs}}
ADD {{.}} {{.}}
{{/src-dirs}}
RUN mvn package -DskipTests

RUN echo "done!"

# 2nd stage, build the runtime image
FROM openjdk:17-jdk-slim
WORKDIR /helidon

# Copy the binary built in the 1st stage
COPY --from=build /helidon/{{#module-dir}}{{.}}/{{/module-dir}}target/{{artifactId}}.jar ./
COPY --from=build /helidon/{{#module-dir}}{{.}}/{{/module-dir}}target/libs ./libs

CMD ["java", "-jar", "{{artifactId}}.jar"]

EXPOSE 8080
