///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Metrics
:toc:
:toc-placement: preamble
:description: MicroProfile Metrics support in Helidon MP
:keywords: helidon, mp, microprofile, metrics
:feature-name: MicroProfile Metrics
:microprofile-bundle: true
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.metrics</groupId>
    <artifactId>helidon-microprofile-metrics</artifactId>
</dependency>
----

== Overview

Helidon provides three types of metrics: base, vendor, and application.  Helidon automatically provides built-in base and vendor metrics.
Applications can use these metrics without additional configuration or code changes.

== Next Steps

Learn more about link:{microprofile-metrics-spec-url}[MicroProfile Metrics specification].

Create a sample MicroProfile (MP) project that can be used to run some basic examples using both built-in and custom metrics with Helidon MP. xref:../guides/metrics.adoc[Helidon MP Metrics Guide].