///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Metrics-Capable Modules
:h1-prefix: MP
:description: Helidon MP metrics-capable modules
:keywords: helidon, metrics, metrics-capable, microprofile, guide
:intro-project-name: {h1-prefix}
:chk: icon:check[]
:x: icon:times[]
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

// Overview and usage
include::{rootdir}/includes/metrics/metrics-capable-components.adoc[tags=preamble;all-beginning-text]

include::{rootdir}/includes/metrics/metrics-capable-components.adoc[tags=writing-code-intro]

==== Writing a Helidon MP Application

When your MP application code uses `@Inject` for either a `RegistryFactory` or a `MetricRegistry`, Helidon injects either the full-featured instance or the minimal instance according to whether the runtime path includes the full implementation and, if so, whether metrics is enabled.

By choosing and injecting the appropriate implementation, Helidon allows you to write your code without concern for which implementation is available at runtime.

==== Packaging a Metrics-capable Helidon MP _Application_

The Helidon MP metrics implementation depends on the metrics and metrics service APIs as well as `helidon-metrics` which contains the full implementation of each.
Therefore, by default, Helidon MP applications have full-featured metrics and endpoint support.

Application code can `@Inject` the `RegistryFactory` and `MetricRegistry` instances.
Helidon MP itself uses metrics settings in the configuration to make the correct `RegistryFactory` and `MetricRegistry` instances available at injection sites.

Helidon's MicroProfile metrics component `helidon-microprofile-metrics` has its own runtime dependency on the minimal implementation,
so that implementation, at least, is available at runtime.

By default, Helidon MP applications use the full implementation, because Helidon's MP metrics depends also on the full metrics implementation.
That said, a developer of a Helidon MP app _can_ explicitly exclude the dependency on the full implementation:
[source,xml]
.Explicit exclusion of `helidon-metrics`
----
<dependency>
    <groupId>io.helidon.microprofile.bundles</groupId>
    <artifactId>helidon-microprofile</artifactId>
    <exclusions>
        <exclusion>
            <groupId>io.helidon.metrics</groupId>
            <artifactId>helidon-metrics</artifactId>
        </exclusion>
    </exclusions>
</dependency>
----

In the resulting Helidon MP application, Helidon will use the minimal metrics and metrics support implementations.

include::{rootdir}/includes/metrics/metrics-capable-components.adoc[tag=writing-component]

include::{rootdir}/includes/metrics/metrics-capable-components.adoc[tags=writing-code-ending]

include::{rootdir}/includes/metrics/metrics-capable-components.adoc[tags=wrap-up]