///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Metrics in Helidon MP
:description: Helidon MP Metrics Support
:keywords: helidon, java, metrics, mp, configuration, services
:feature-name: metrics
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
** <<Other Packaging Options, Other Packaging Options>>
- <<Usage, Usage>>
** <<Instrumenting Your Service, Instrumenting Your Service>>
** <<Categorizing the Types of Metrics, Categorizing the Types of Metrics>>
** <<Metric Registries, Metric Registries>>
** <<Retrieving Metrics Reports From Your Service, Retrieving Metrics Reports From Your Service>>
- <<API, API>>
** <<Metrics Annotations, Metrics Annotations>>
** <<The MetricRegistry API, The MetricRegistry API>>
** <<Working with Metrics in CDI Extensions, Working with Metrics in CDI Extensions>>
- <<Configuration, Configuration>>
** <<Configuration Options, Configuration Options>>
- <<Examples, Examples>>
** <<Example Application Code, Example Application Code>>
** <<Example Configuration, Example Configuration>>
- <<Additional Information, Additional Information>>
** <<Integration with Kubernetes and Prometheus, Integration with Kubernetes and Prometheus>>
** <<References, References>>

== Overview
Helidon MP metrics implements the MicroProfile Metrics specification, providing:

include::{rootdir}/includes/metrics/metrics-shared.adoc[tag=overview]

include::{rootdir}/includes/dependencies.adoc[]

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>io.helidon.microprofile.metrics</groupId>
    <artifactId>helidon-microprofile-metrics</artifactId>
</dependency>
----

Adding this dependency packages the full-featured metrics implementation with your service.

=== Other Packaging Options
Helidon gives you flexibility in how you make metrics available to your service. xref:{rootdir}/mp/metrics/metrics-capable-components.adoc[This document] explains your options.

== Usage

include::{rootdir}/includes/metrics/metrics-shared.adoc[tag=usage-body]


== API

The link:{microprofile-metrics-javadoc-url}/org/eclipse/microprofile/metrics/package-summary.html[MicroProfile Metrics API] prescribes all the standard interfaces related to metrics. This section summarizes a few key points about using that API and explains some Helidon-specific interfaces.

=== Metrics Annotations
** <<Metric-Defining Annotations, Metric-Defining Annotations>>
** <<Metric-Referencing Annotations, Metric-Referencing Annotations>>

You can very easily instrument your service and refer to registered metrics by annotating methods to be measured and injecting metrics which your code needs to observe.

==== Metric-Defining Annotations
The MicroProfile Metrics specification describes several metric types you can create using annotations, summarized in the following table:

.Metrics Annotations
[%autowidth]
|====
| Annotation | Usage

| link:{microprofile-metrics-javadoc-annotation-url}/Counted.html[`@Counted`]
| Monotonically increasing count of events.

| link:{microprofile-metrics-javadoc-annotation-url}ConcurrentGauge.html[`@ConcurrentGauge`]
| Increasing and decreasing measurement of currently-executing blocks of code.

| link:{microprofile-metrics-javadoc-annotation-url}/Gauge.html[`@Gauge`]
| Access to a value managed by other code in the service.

| link:{microprofile-metrics-javadoc-annotation-url}/Metered.html[`@Metered`]
| Count of invocations and how frequently invocations have occurred.

| link:{microprofile-metrics-javadoc-annotation-url}/SimplyTimed.html[`@SimplyTimed`]
| Count of invocations and the total duration consumed by those invocations.

| link:{microprofile-metrics-javadoc-annotation-url}/Timed.html[`@Timed`]
| Frequency of invocations and the distribution of how long the invocations take.

|====

Place annotations on constructors or methods to measure those specific executables. If you annotate the class instead, Helidon applies that annotation to all constructors and methods which the class declares.

==== Metric-Referencing Annotations
To get a reference to a specific metric, use a metric-referencing annotation in any bean, including your REST resource classes.

You can `@Inject` a field of the correct type. Helidon uses the MicroProfile Metrics naming conventions to select which specific metric to inject. Use the link:{microprofile-metrics-javadoc-url}/org/eclipse/microprofile/metrics/annotation/Metric.html[`@Metric`] annotation to control that selection.

You can also add `@Metric` on a constructor or method parameter to trigger injection there.

Helidon automatically looks up the metric referenced from any injection site and provides a reference to the metric. Your code then simply invokes methods on the injected metric.

include::{rootdir}/includes/metrics/metrics-shared.adoc[tag=metric-registry-api]

=== Working with Metrics in CDI Extensions
You can work with metrics inside your own CDI extensions, but be careful to do so at the correct point in the CDI lifecycle.

Configuration can influence how the metrics system behaves, as the <<Configuration, configuration>> section below explains.
Your code should work with metrics only after the Helidon metrics system has initialized itself using configuration.
One way to accomplish this is to deal with metrics in a method that observes the Helidon `RuntimeStart` CDI event, which the xref:extension_example[extension example below] illustrates.

// Here's Configuration.
include::{rootdir}/includes/metrics/metrics-config.adoc[tag=config-intro]

== Examples

Helidon MP includes a prewritten example application illustrating
link:{helidon-github-tree-url}/examples/metrics/filtering/mp[enabling/disabling metrics] using configuration.

The rest of this section contains other examples of working with metrics:

[#example-application-code]
=== Example Application Code
- <<Adding Method-Level Annotations, Adding Method-Level Annotations>>
- <<Additional Method-Level Metrics, Additional Method-Level Metrics>>
- <<Class-Level Metrics, Class-Level Metrics>>
- <<Field-Level Metrics, Field-Level Metrics>>
- <<Gauge Metric, Gauge Metric>>
- <<Working with Metrics in CDI Extensions, Working with Metrics in CDI Extensions>>

==== Adding Method-Level Annotations
The following example adds a new resource class, `GreetingCards`, to the Helidon MP QuickStart example. It shows how to use the `@Counted` annotation to track the number of times
the `/cards` endpoint is called.

[source,java]
.Create a new class `GreetingCards` with the following code:
----
package io.helidon.examples.quickstart.mp;

import java.util.Collections;
import jakarta.enterprise.context.RequestScoped;
import jakarta.json.Json;
import jakarta.json.JsonBuilderFactory;
import jakarta.json.JsonObject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.metrics.annotation.Counted;

@Path("/cards") //<1>
@RequestScoped // <2>
public class GreetingCards {

  private static final JsonBuilderFactory JSON = Json.createBuilderFactory(Collections.emptyMap());

  @GET
  @Produces(MediaType.APPLICATION_JSON)
  @Counted(name = "any-card")  // <3>
  public JsonObject anyCard() throws InterruptedException {
    return createResponse("Here are some random cards ...");
  }

  private JsonObject createResponse(String msg) {
    return JSON.createObjectBuilder().add("message", msg).build();
  }
}
----
<1> This class is annotated with `Path` which sets the path for this resource
as `/cards`.
<2> The `@RequestScoped` annotation defines that this bean is
request scoped.  The request scope is active only for the duration of
one web service invocation and it is destroyed at the end of that
invocation.
<3> The annotation `@Counted` will register a `Counter` metric for this method, creating it if needed.
The counter is incremented each time the anyCards method is called.  The `name` attribute is optional.

// tag::build-and-access-cards-example[]

// tag::build-cards-example[]
.Build and run the application
[source,bash]
----
mvn package
java -jar target/helidon-quickstart-mp.jar
----
// end::build-cards-example[]

// tag::access-cards-example[]
.Access the application endpoints
[source,base]
----
curl http://localhost:8080/cards
curl http://localhost:8080/cards
curl -H "Accept: application/json"  http://localhost:8080/metrics/application
----
// end::access-cards-example[]

// end::build-and-access-cards-example[]

[source,json]
.JSON response:
----
{
  "io.helidon.examples.quickstart.mp.GreetingCards.any-card":2 // <1>
}
----
<1> The any-card count is two, since you invoked the endpoint twice.

NOTE: Notice the counter name is fully qualified with the class and method names.  You can remove the prefix by using the `absolute=true` field in the `@Counted` annotation.
You must use  `absolute=false` (the default) for class-level annotations.

==== Additional Method-Level Metrics

The `@ConcurrentGauge`, @Timed`, `@Metered`, and `@SimplyTimed` annotations can also be used with a method.  For the following example.
you can just annotate the same method with `@Metered` and `@Timed`. These metrics collect significant
information about the measured methods, but at a cost of some overhead and more complicated output.
Use `@SimplyTimed` in cases where capturing the invocation count and the total elapsed time
spent in a block of code is sufficient.

Note that when using multiple annotations on a method, you *must* give the metrics different names as shown below (although they do not have to be absolute).

[source,java]
.Update the `GreetingCards` class with the following code:
----
package io.helidon.examples.quickstart.mp;

import java.util.Collections;
import jakarta.enterprise.context.RequestScoped;
import jakarta.json.Json;
import jakarta.json.JsonBuilderFactory;
import jakarta.json.JsonObject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.metrics.MetricUnits;
import org.eclipse.microprofile.metrics.annotation.Counted;
import org.eclipse.microprofile.metrics.annotation.Metered;
import org.eclipse.microprofile.metrics.annotation.Timed;

@Path("/cards")
@RequestScoped
public class GreetingCards {

  private static final JsonBuilderFactory JSON = Json.createBuilderFactory(Collections.emptyMap());

  @GET
  @Produces(MediaType.APPLICATION_JSON)
  @Counted(name = "cardCount", absolute = true) //<1>
  @Metered(name = "cardMeter", absolute = true, unit = MetricUnits.MILLISECONDS) //<2>
  @Timed(name = "cardTimer", absolute = true, unit = MetricUnits.MILLISECONDS) //<3>
  public JsonObject anyCard() {
    return createResponse("Here are some random cards ...");
  }

  private JsonObject createResponse(String msg) {
    return JSON.createObjectBuilder().add("message", msg).build();
  }
}

----
<1> Specify a custom name for the `Counter` metric and set `absolute=true` to remove the path prefix from the name.
<2> Add the `@Metered` annotation to get a `Meter` metric.
<3> Add the `@Timed` annotation to get a `Timer` metric.

include::metrics.adoc[tag=build-and-access-cards-example]

[source,json]
.JSON response:
----
{
  "cardCount": 2,
  "cardMeter": { // <1>
    "count": 2,
    "meanRate": 0.15653506570241812,
    "oneMinRate": 0,
    "fiveMinRate": 0,
    "fifteenMinRate": 0
  },
  "cardTimer": { // <2>
    "count": 2,
    "elapsedTime": 2,
    "meanRate": 0.15651866263362785,
    "oneMinRate": 0,
    "fiveMinRate": 0,
    "fifteenMinRate": 0,
    "min": 0,
    "max": 2,
    "mean": 1.0506565,
    "stddev": 1.0405735,
    "p50": 2.09123,
    "p75": 2.09123,
    "p95": 2.09123,
    "p98": 2.09123,
    "p99": 2.09123,
    "p999": 2.09123
  }
}
----
<1> The `Meter` metric includes the count field (it is a superset of `Counter`).
<2> The `Timer` metric includes the `Meter` fields (it is a superset of `Meter`).


==== Class-Level Metrics

You can collect metrics at the class-level to aggregate data from all methods in that class using the same metric.
The following example introduces a metric to count all card queries.  In the following example, the method-level metrics are not
needed to aggregate the counts, but they are left in the example to demonstrate the combined output of all three metrics.

[source,java]
.Update the `GreetingCards` class with the following code:
----
package io.helidon.examples.quickstart.mp;

import java.util.Collections;
import jakarta.enterprise.context.RequestScoped;
import jakarta.json.Json;
import jakarta.json.JsonBuilderFactory;
import jakarta.json.JsonObject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.metrics.annotation.Counted;

@Path("/cards")
@RequestScoped
@Counted(name = "totalCards") // <1>
public class GreetingCards {

  private static final JsonBuilderFactory JSON = Json.createBuilderFactory(Collections.emptyMap());

  @GET
  @Produces(MediaType.APPLICATION_JSON)
  @Counted(absolute = true) // <2>
  public JsonObject anyCard() throws InterruptedException {
    return createResponse("Here are some random cards ...");
  }

  @Path("/birthday")
  @GET
  @Produces(MediaType.APPLICATION_JSON)
  @Counted(absolute = true) // <3>
  public JsonObject birthdayCard() throws InterruptedException {
    return createResponse("Here are some birthday cards ...");
  }

  private JsonObject createResponse(String msg) {
    return JSON.createObjectBuilder().add("message", msg).build();
  }
}
----
<1> This class is annotated with `@Counted`, which aggregates count data from all the method that have a `Count` annotation.
<2> Use `absolute=true` to remove path prefix for method-level annotations.
<3> Add a method with a `Counter` metric to get birthday cards.

include::metrics.adoc[tag=build-cards-example]
[source,bash]
.Access the application endpoints
----
curl http://localhost:8080/cards
curl http://localhost:8080/cards/birthday
curl -H "Accept: application/json"  http://localhost:8080/metrics/application
----

[source,json]
.JSON response from `/metrics/application`:
----
{
  "anyCard": 1,
  "birthdayCard": 1,
  "io.helidon.examples.quickstart.mp.totalCards.GreetingCards": 2  // <1>
}
----
<1> The `totalCards` count is a total of all the method-level `Counter` metrics.  Class level metric names are always
fully qualified.


==== Field-Level Metrics

Field level metrics can be injected into managed objects, but they need to be updated by the application code.
This annotation can be used on fields of type `Meter`, `Timer`, `Counter`, and `Histogram`.

The following example shows how to use a field-level `Counter` metric to track cache hits.

[source,java]
.Update the `GreetingCards` class with the following code:
----
package io.helidon.examples.quickstart.mp;

import java.util.Collections;
import java.util.Random;
import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Inject;
import jakarta.json.Json;
import jakarta.json.JsonBuilderFactory;
import jakarta.json.JsonObject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.metrics.Counter;
import org.eclipse.microprofile.metrics.annotation.Counted;
import org.eclipse.microprofile.metrics.annotation.Metric;

@Path("/cards")
@RequestScoped
@Counted(name = "totalCards")
public class GreetingCards {

  private static final JsonBuilderFactory JSON = Json.createBuilderFactory(Collections.emptyMap());

  @Inject
  @Metric(name = "cacheHits", absolute = true) // <1>
  private Counter cacheHits;

  @GET
  @Produces(MediaType.APPLICATION_JSON)
  @Counted(absolute = true)
  public JsonObject anyCard() throws InterruptedException {
    updateStats(); // <2>
    return createResponse("Here are some random cards ...");
  }

  @Path("/birthday")
  @GET
  @Produces(MediaType.APPLICATION_JSON)
  @Counted(absolute = true)
  public JsonObject birthdayCard() throws InterruptedException {
    updateStats();  // <3>
    return createResponse("Here are some birthday cards ...");
  }

  private JsonObject createResponse(String msg) {
    return JSON.createObjectBuilder().add("message", msg).build();
  }

  private void updateStats() {
    if (new Random().nextInt(3) == 1) {
      cacheHits.inc(); // <4>
    }
  }
}
----
<1> A `Counter` metric field, `cacheHits`, is automatically injected by Helidon.
<2> Call `updateStats()` to update the cache hits.
<3> Call `updateStats()` to update the cache hits.
<4> Randomly increment the `cacheHits` counter.

[source,bash]
.Build and run the application, then invoke the following endpoints:
----
curl http://localhost:8080/cards
curl http://localhost:8080/cards
curl http://localhost:8080/cards/birthday
curl http://localhost:8080/cards/birthday
curl http://localhost:8080/cards/birthday
curl -H "Accept: application/json"  http://localhost:8080/metrics/application
----

[source,json]
.JSON response from `/metrics/application`:
----
{
  "anyCard": 2,
  "birthdayCard": 3,
  "cacheHits": 2, // <1>
  "io.helidon.examples.quickstart.mp.totalCards.GreetingCards": 5
}
----
<1> The cache was hit two times out of five queries.

==== Gauge Metric

The metrics you have tested so far are updated in response to an application REST request, i.e GET `/cards`.  These
metrics can be declared in a request scoped class and Helidon will store the metric in the `MetricRegistry`, so the value persists
across requests. When GET `/metrics/application` is invoked, Helidon will return the current value of the metric stored in the `MetricRegistry`.
The `Gauge` metric is different from all the other metrics. The application must provide a getter to return the gauge value in an
application scoped class. When GET `/metrics/application` is invoked, Helidon will call the `Gauge` getter, store that value
in the `MetricsRegistry`, and return it as part of the metrics response payload.  So, the `Gauge` metric value is updated real-time, in response to the
get metrics request.

The following example demonstrates how to use a `Gauge` to track application up-time.

[source,java]
.Create a new `GreetingCardsAppMetrics` class with the following code:
----
package io.helidon.examples.quickstart.mp;

import java.time.Duration;
import java.util.concurrent.atomic.AtomicLong;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.context.Initialized;
import jakarta.enterprise.event.Observes;
import org.eclipse.microprofile.metrics.annotation.Gauge;

@ApplicationScoped // <1>
public class GreetingCardsAppMetrics {

  private AtomicLong startTime = new AtomicLong(0); // <2>

  public void onStartUp(@Observes @Initialized(ApplicationScoped.class) Object init) {
    startTime = new AtomicLong(System.currentTimeMillis()); // <3>
  }

  @Gauge(unit = "TimeSeconds")
  public long appUpTimeSeconds() {
    return Duration.ofMillis(System.currentTimeMillis() - startTime.get()).getSeconds();  // <4>
  }
}
----
<1> This managed object must be application scoped to properly register and use the `Gauge` metric.
<2> Declare an `AtomicLong` field to hold the start time of the application.
<3> Initialize the application start time.
<4> Return the application `appUpTimeSeconds` metric, which will be included in the application metrics.


[source,java]
.Update the `GreetingCards` class with the following code to simplify the metrics output:
----
package io.helidon.examples.quickstart.mp;

import java.util.Collections;
import jakarta.enterprise.context.RequestScoped;
import jakarta.json.Json;
import jakarta.json.JsonBuilderFactory;
import jakarta.json.JsonObject;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.metrics.annotation.Counted;

@Path("/cards")
@RequestScoped
public class GreetingCards {

  private static final JsonBuilderFactory JSON = Json.createBuilderFactory(Collections.emptyMap());

  @GET
  @Produces(MediaType.APPLICATION_JSON)
  @Counted(name = "cardCount", absolute = true)
  public JsonObject anyCard() throws InterruptedException {
    return createResponse("Here are some random cards ...");
  }

  private JsonObject createResponse(String msg) {
    return JSON.createObjectBuilder().add("message", msg).build();
  }
}
----

[source,bash]
.Build and run the application, then invoke the application metrics endpoint:
----
curl -H "Accept: application/json"  http://localhost:8080/metrics/application
----

[source,json]
.JSON response from `/metrics/application`:
----
{
  "cardCount": 0,
  "io.helidon.examples.quickstart.mp.GreetingCardsAppMetrics.appUpTimeSeconds": 6 // <1>
}
----
<1> The application has been running for 6 seconds.

[[extension_example]]
==== Working with Metrics in CDI Extensions

You can work with metrics from your own CDI extension by observing the `RuntimeStart` event.

[source,java]
.CDI Extension that works correctly with metrics
----
import io.helidon.microprofile.cdi.RuntimeStart;

import jakarta.enterprise.event.Observes;
import jakarta.enterprise.inject.spi.Extension;
import org.eclipse.microprofile.metrics.Counter;
import org.eclipse.microprofile.metrics.MetricRegistry;

public class MyExtension implements Extension {

    void startup(@Observes @RuntimeStart Object event,  // <1>
                 MetricRegistry metricRegistry) {       // <2>
        metricRegistry.counter("myCounter");         // <3>
        }
}
----
<1> Declares that your observer method responds to the `RuntimeStart` event. By this time, Helidon has initialized the metrics system.
<2> Injects a `MetricRegistry` (the application registry by default).
<3> Uses the injected registry to register a metric (a counter in this case).

[NOTE]
====
Helidon does not prevent you from working with metrics earlier than the `RuntimeStart` event, but, if you do so, then Helidon might ignore certain configuration settings that would otherwise control how metrics behaves.

Your extension might use earlier lifecycle events (such as `ProcessAnnotatedType`) to gather and store information about metrics that you want to register.
Then your `RuntimeStart` observer method would use that stored information to register the metrics you need.
====


// Config examples
include::{rootdir}/includes/metrics/metrics-config.adoc[tag=config-examples]

== Additional Information

include::{rootdir}/includes/guides/metrics.adoc[tag=k8s-and-prometheus-integration]

=== References
link:{microprofile-metrics-spec-url}[MicroProfile Metrics specification]

link:{microprofile-metrics-javadoc-url}/org/eclipse/microprofile/metrics/package-info.html[MicroProfile Metrics API]
