/*
 * Copyright (c) 2025, 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.config;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

import io.helidon.common.Api;
import io.helidon.service.registry.Service;

/**
 * Container class for annotations related to Helidon Configuration when using declarative programming model.
 * <p>
 * NOTE: this API is part of preview features of Helidon. This API may still change between minor releases,
 *               but it is intended for supported external use.
 */
@Api.Preview
public final class Configuration {
    private Configuration() {
    }

    /**
     * A qualifier for injection of a single value from the configuration tree.
     */
    @Target(ElementType.PARAMETER)
    @Retention(RetentionPolicy.CLASS)
    @Documented
    @Service.Qualifier
    public @interface Value {
        /**
         * Configuration key (from the config root) or configuration expression to find the value.
         * <p>
         * Default configuration key is {@code <class_name>.<field_name>} for field injection (if supported),
         * and {@code <className>.<constructor_param_name>} for constructor injection. The {@code <class_name>}
         * is the fully qualified class name of the type that uses this annotation.
         * <p>
         * In addition to plain keys such as {@code app.greeting}, this annotation supports the standard
         * configuration-expression syntax {@code ${key:default}}. Expressions may be the whole value, such as
         * {@code ${app.greeting:Hello}}, or part of a composite string, such as
         * {@code Hello ${app.name:World}}.
         * <p>
         * Note that parameter names are not retained at runtime, so the parameter name when not using
         * build time processing would be generated by the JVM.
         * <p>
         * If a whole expression does not resolve and does not define an inline default, one of the
         * {@link io.helidon.common.Default} annotations can still be used as a fallback.
         *
         * @return configuration key or expression
         */
        String value() default "";
    }
}
