///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Helidon SE Guides
:keywords: helidon, java, microservices, microprofile, guides
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

== Getting Started

[PILLARS]
====
[CARD]
.Quickstart SE
[link=quickstart.adoc]
--
Create your first Helidon SE application in under 5 minutes.
--

====

== Helidon SE Guides

[PILLARS]
====
[CARD]
.Config Guide
[link=config.adoc]
--
Learn how to configure a Helidon SE application.
--

[CARD]
.Health Check Guide
[link=health.adoc]
--
Learn how to use Helidon SE built-in and custom health checks.
--

[CARD]
.Metrics Guide
[link=metrics.adoc]
--
Learn how to use Helidon SE built-in and application metrics.
--

[CARD]
.Tracing Guide
[link=tracing.adoc]
--
Learn how to trace a Helidon SE application.
--

[CARD]
.OIDC Guide
[link=security-oidc.adoc]
--
Learn how to set up an OIDC Helidon SE application
--

[CARD]
.Helidon SE Upgrade Guide
[link=upgrade.adoc]
--
Learn how to Upgrade your Helidon SE application
--

[CARD]
.Helidon SE WebClient Guide
[link=webclient.adoc]
--
Learn how to use the Helidon SE WebClient
--

[CARD]
.Helidon SE DB Client Guide
[link=dbclient.adoc]
--
Learn how to use the Helidon SE DB Client
--

[CARD]
.Helidon SE Performance Tuning Guide
[link=performance-tuning.adoc]
--
Learn how to tune your Helidon SE application
--
====

== Build and Deploy

[PILLARS]
====
[CARD]
.Maven Guide
[link=maven-build.adoc]
--
Using Helidon in your Maven project.
--

[CARD]
.Gradle Guide
[link=gradle-build.adoc]
--
Using Helidon in your Gradle project.
--

[CARD]
.GraalVM Native Images
[link=graalnative.adoc]
--
Learn how to build a GraalVM native image for your Helidon application both
on your desktop and as part of a Docker image.
--

[CARD]
.Custom Runtime Images using jlink
[link=jlink-image.adoc]
--
Learn how to build a custom runtime Java image for your Helidon application both
on your desktop and as part of a Docker image.
--

[CARD]
.Building Container Images with Jib
[link=../../guides/jib.adoc]
--
Learn how to use Jib to create a container image without Docker.
--

[CARD]
.Deploying to OKE
[link=../../guides/oke.adoc]
--
Learn how to deploy your application to Oracle Cloud Infrastructure Container
 Engine for Kubernetes (OKE).
--

====
