///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Performance Tuning
:description: Helidon SE Performance Tuning
:feature-name: Performance Tuning
:microprofile-bundle: false
:keywords: helidon, se, performance, tuning
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

== Introduction

In this guide you fill find basic advice for performance tuning of your Helidon application.
Most of this concerns tuning Helidon WebServer, but you should also consider configuring/tuning
Java heap size as per any Java application.

include::{rootdir}/includes/guides/performance-tuning.adoc[]

