///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon SE 4.x Upgrade Guide
:description: Helidon SE 4.x Upgrade Guide
:keywords: helidon, porting, migration, upgrade, incompatibilities
:rootdir: {docdir}/../..

include::{rootdir}/includes/attributes.adoc[]

Helidon 4.x introduces significant changes to APIs and runtime behavior. Use this guide to help you understand the changes required to transition a Helidon SE 3.x application to Helidon 4.x.

== Significant Changes

The following sections describe the changes between Helidon 3.x and Helidon 4.x that can significantly impact your development process. Review them carefully.

You can also review the https://github.com/helidon-io/helidon/blob/main/CHANGELOG.md[Helidon repository CHANGELOG] to see a detailed history of changes made to the project.

NOTE: Helidon adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning]. As such, Helidon 4.x includes changes that are not backward compatible with Helidon 3.x.

TIP: The link:{helidon-github-examples-url}/[Helidon Examples repository] is a good resource for understanding how things work in Helidon 4.x.

=== Java SE Support

Helidon 4.x removes support for Java SE 17. You must use Java SE 21 or later. If you are using Helidon 4.3.0 or later, using Java SE 25 or later is recommended.

=== Programming Paradigm Shift

In Helidon 4.x, Helidon SE moves from an asynchronous-style API to a blocking-style API that is optimized for use with virtual threads. Currently, there is no compatibility API available.

=== New Web Server Implementation

Helidon 4.x introduces Helidon WebServer, a virtual threads-based web server implementation based on the JDK Project Loom. Helidon WebServer replaces Netty, the server implementation used in previous versions of Helidon.

You will need to update your existing Helidon SE 3.x code to use the new APIs but it is generally simpler to write and maintain code in Helidon SE 4.x than it was in previous versions.

Here is an example of the differences between Helidon SE 3.x and Helidon SE 4.x:

.Use Helidon 3.x to extract a JSON body from an HTTP request and do something
[source,java]
----
include::{sourcedir}/about/IntroSnippets.java[tag=snippet_1, indent=0]
----

.Use Helidon 4.x to extract a JSON body from an HTTP request and do something
[source,java]
----
include::{sourcedir}/about/IntroSnippets.java[tag=snippet_2, indent=0]
----

Learn more at xref:../webserver/webserver.adoc[WebServer].

=== Server Startup

Starting a server in Helidon 4.x is much simpler than in previous versions because it no longer requires asynchronous programming.

In previous versions of Helidon, the server was started asynchronously and further server operations had to wait. For example:

[source,java]
.Start Helidon SE 3.x server
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_1, indent=0]
----
<1> Server is started in an asynchronous way. A `Single` object is returned.
<2> Wait for the server to start and print the message in an asynchronous way.
<3> Gracefully handle exceptions if they occur during the initialization process.

In Helidon 4.x, you can create and configure a server and then wait for it to start. If any exceptions happen, they are handled the traditional way using available language constructions. For example:

[source,java]
.Start Helidon SE 4.x server
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_2, indent=0]
----
<1> Configure the server.
<2> Start the server. No reactive objects returned.
<3> Print a message when the server is started.

=== Additional Server Lifecycle Tasks

In Helidon 3.x, if you provided code to run after WebServer startup and after WebServer shutdown, you needed to use asynchronous constructs, like so:

[source,java]
.Helidon 3.x server lifecycle
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_9, indent=0]
----

In Helidon 4.x, no special API is needed for post-server startup tasks since the server starts synchronously. Your `HttpService` can interpose on the server lifecycle by overriding the `beforeStart` and `afterStop` methods, like so:

[source,java]
.Helidon 4.x server lifecycle
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_10, indent=0]
----

=== Server Features and Media Support Discovery

In previous versions of Helidon, you had to explicitly register WebServer features (`register(MetricsSupport.create())`) and explicitly add media support (`addMediaSupport(JsonpSupport.create())`).

Helidon 4.x automatically discovers these components from the class path. You only need to add the dependencies to your `pom.xml` file and, optionally, add configuration to customize them.

If you want full control using the API, you still have that option.

For more information, see:

* xref:../observability.adoc[Observability Feature Support]
* xref:../webserver/webserver.adoc#_media_types_support[Media Types Support]

=== Routing Configuration

In previous Helidon versions, the routing was configured as follows: services were created and assigned to the desired path. Observability and other features were created as usual Helidon `services`, available as part of the framework. User-defined services were also registered the same way. For example:

[source,java]
.Routing in Helidon SE 3.x server
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_3, indent=0]
----
<1> Create and configure `Metrics` and `Health` support.
<2> Create a regular Helidon Service.
<3> Register `Metrics` and `Health` support as Helidon Services.
<4> Register the regular Greeting service.

In Helidon 4.x, the Metrics and Health features are automatically discovered and, assuming you added the dependencies to your project, the routing is configured in the following way:

[source,java]
.Routing in Helidon SE 4.x server
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_4, indent=0]
----
<1> Register Greeting service as in previous versions of Helidon.

If you want to add these features to the server programmatically, you would use `WebServer.builder().addFeature()` method instead.

`Feature` encapsulates a set of endpoints, services and/or filters. It is similar to `HttpService` but gives more freedom in setup. The main difference is that a feature can add `Filters` and it cannot be registered on a path. Features are not registered immediately; each feature can order features according to their weight by defining a `Weight` or implementing `Weighted` . Higher-weighted features are registered first. This allows you to order features in a meaningful way, for example Context, then Tracing, then Security, and so on.

==== Adding Additional Routing Criteria

Helidon 4.x removes the `RequestPredicate` class, which in previous versions, was used to specify more routing criteria.

So, for example, if you used the following in Helidon 3.x:

[source,java]
.Helidon 3.x using `RequestPredicate`
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_11, indent=0]
----

Then, you would now use the following in Helidon 4.x:

[source,java]
.Routing without RequestPredicate in Helidon 4.x
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_12, indent=0]
----

=== Services

Helidon 4.x introduces `HttpService` which you implement to process HTTP requests. To set up routing, you should now use the `routing(HttpRules rules)` method. It receives an `HttpRules` object with routes description.

Additionally, `ServerRequest` and `ServerResponse` are now in the `io.helidon.webserver.http` package and `Http.Status` is now `io.helidon.http.Status`.

WARNING: These changes make Helidon 4.x incompatible with previous versions.

In previous versions, a service looked like this:

[source,java]
.Helidon SE 3.x Service
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_5, indent=0]
----
<1> Use the `update()` method to set up routing.
<2> Handle a `Request` and return a `Response`.

In Helidon 4.x, the same service looks like this:

[source,java]
.Helidon SE 4.x Service
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_6, indent=0]
----
<1> Implement `HttpService` for the `GreetingService`.
<2> Use `routing(HttpRules rules)` to set up routing.
<3> Handle a `Request` and return a `Response`.

Learn more about `HttpService` and `Routing` at xref:../webserver/webserver.adoc[Helidon SE WebServer].

== Other Changes

The following sections describe changes between Helidon 3.x and Helidon 4.x that may impact your development process.

=== Media Support

Media support moved from the `io.helidon.media` Java package to `io.helidon.http.media` and has the following new dependency coordinates:

[source,xml]
----
<dependency>
    <groupId>io.helidon.http.media</groupId>
    <artifactId>helidon-http-media-jsonp</artifactId>
</dependency>

<dependency>
    <groupId>io.helidon.http.media</groupId>
    <artifactId>helidon-http-media-jsonb</artifactId>
</dependency>
----

In Helidon 4.x, media support is discovered by default, so you only need to add the dependency rather than explicitly adding media support using the `WebServer` builder.

However, media support no longer transitively brings the Jakarta EE API dependencies, so you will need to add those dependencies explicitly. For example:

[source,xml]
----
<dependency>
    <groupId>jakarta.json</groupId>
    <artifactId>jakarta.json-api</artifactId>
</dependency>
----

=== Testing

Helidon 4.x adds a new testing framework for Helidon SE.

[source,xml]
----
<dependency>
     <groupId>io.helidon.webserver.testing.junit5</groupId>
     <artifactId>helidon-webserver-testing-junit5</artifactId>
     <scope>test</scope>
</dependency>
----

For more information, see xref:../testing.adoc[Helidon SE Testing].

=== Observability

Observability features moved to different packages. For `Health` and `Metrics`, you should now use:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>io.helidon.webserver.observe</groupId>
        <artifactId>helidon-webserver-observe-health</artifactId>
    </dependency>
    <dependency>
        <groupId>io.helidon.webserver.observe</groupId>
        <artifactId>helidon-webserver-observe-metrics</artifactId>
    </dependency>
</dependencies>
----

Observability has new endpoints. See them at xref:../observability.adoc[hObservability].

For System Metrics, you should now use:

[source,xml]
----
<dependency>
    <groupId>io.helidon.metrics</groupId>
    <artifactId>helidon-metrics-system-meters</artifactId>
</dependency>
----

By default, Observability features are discovered automatically if you add the above dependencies.
If you choose to add them programmatically (using `addFeature`), you must add the following dependency:

[source,xml]
----
<dependency>
    <groupId>io.helidon.webserver.observe</groupId>
    <artifactId>helidon-webserver-observe</artifactId>
</dependency>
----

Metrics has changed significantly in Helidon 4.x. For more information, see xref:../metrics/metrics.adoc[Helidon SE Metrics].

=== Security

* Changed modules:
- `helidon-security-integration-grpc` was removed
- `helidon-security-integration-jersey` moved to the module `helidon-microprofile-security`
- `helidon-security-integration-jersey-client` moved to the module `helidon-microprofile-security`
- `helidon-security-integration-webserver` moved to the module `helidon-webserver-security`

* Significant class name changes:
- `OidcSupport` was renamed to `OidcFeature`
- `WebSecurity` was renamed to `SecurityFeature`

* Other:
- `SynchronousProvider removed` - `SynchronousProvider` usage is no longer needed, since all security providers are synchronous.

=== Global Configuration

Helidon 4.x adds global configuration, a singleton instance of the `Config` class, which is implicitly employed by certain Helidon components. Furthermore, it offers a handy approach for your application to access configuration information from any part of your code.

[source,java]
----
include::{sourcedir}/se/guides/Upgrade4xSnippets.java[tag=snippet_8, indent=0]
----

For more information, see xref:../config/introduction.adoc[Helidon SE Config].

=== Logging

The class `LogConfig` moved to the `io.helidon.logging.common` Java package.

The Helidon console handler changed from `io.helidon.common.HelidonConsoleHandler` to `io.helidon.logging.jul.HelidonConsoleHandler`.

If you use this handler in your `logging.properties` file, you will need to update it and add the following dependency:

[source,xml]
----
<dependency>
    <groupId>io.helidon.logging</groupId>
    <artifactId>helidon-logging-jul</artifactId>
    <scope>runtime</scope>
</dependency>
----
