///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Health Checks
:description: Helidon health checks
:keywords: helidon, health-checks, health, check

== Overview
Helidon SE provides the following to support health checks:

1. The endpoint `/health`: A configurable endpoint that exposes health checks in JSON
    format as described by the MicroProfile Health specification
2. A base set of health checks (a separate library `io.helidon.health:helidon-health-checks`)

The Health Check component in Helidon SE is the core for the Helidon MP implementation of the MicroProfile Health specification.


=== Prerequisites

Declare the following dependency in your project:

[source,xml,subs="verbatim,attributes"]
----
    <dependency>
        <groupId>io.helidon.health</groupId>
        <artifactId>helidon-health</artifactId>
    </dependency>
----

To enable the built-in health checks, add the following dependency:

[source,xml,subs="verbatim,attributes"]
----
    <dependency>
        <groupId>io.helidon.health</groupId>
        <artifactId>helidon-health-checks</artifactId>
    </dependency>
----


=== Adding health checks to your application
To enable health checks, register them with the web server.

[source,java]
----
import io.helidon.metrics.MetricsSupport;
//...
HealthSupport health = HealthSuport.builder()
    .add(HealthChecks.healthChecks())               // <1>
    .add(() -> HealthCheckResponse.named("exampleHealthCheck")
                 .up()
                 .withData("time", System.currentTimeMillis())
                 .build())                          // <2>
    .build();

Routing.builder()
        .register(health)                           // <3>
        .register("/hello", (req, res) -> res.send("HelloWorld"))
        .build();
----
<1> Add built-in health checks (requires the `helidon-health-checks` dependency)
<2> Add a custom health check. This example returns `UP` and current time
<3> Register health support with web server routing (adds the `/health` endpoint)

=== Accessing the health check endpoint

You can get health-check data through the `/health` endpoint.

The following is an example of the response (in JSON format) to a health-check request, based on the built-in and custom
    health checks implemented in the example provided earlier:

[source,json]
----
{
    "outcome": "UP",
    "checks": [
        {
            "name": "deadlock",
            "state": "UP"
        },
        {
            "name": "diskSpace",
            "state": "UP",
            "data": {
                "free": "211.00 GB",
                "freeBytes": 226563444736,
                "percentFree": "45.31%",
                "total": "465.72 GB",
                "totalBytes": 500068036608
            }
        },
        {
            "name": "exampleHealthCheck",
            "state": "UP",
            "data": {
                "time": 1546958376613
            }
        },
        {
            "name": "heapMemory",
            "state": "UP",
            "data": {
                "free": "215.15 MB",
                "freeBytes": 225600496,
                "max": "3.56 GB",
                "maxBytes": 3817865216,
                "percentFree": "99.17%",
                "total": "245.50 MB",
                "totalBytes": 257425408
            }
        }
    ]
}
----
