///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Community
:description: Helidon community
:keywords: helidon, community, slack, github, twitter, blog

== Open Source

Helidon is a Java open source project under the
https://www.apache.org/licenses/LICENSE-2.0[Apache License version 2.0].
We encourage community contributions whether it's participating in discussions,
creating issues, or submitting pull requests.

== Get Answers

Have a question?

* Ask them in in Slack at http://slack.helidon.io[#helidon-user]
* Or on https://stackoverflow.com/questions/tagged/helidon[Stack Overflow] using the `helidon` tag
* Read the https://github.com/oracle/helidon/wiki/FAQ[Helidon FAQ]

== Code and Issues

* Helidon source is hosted on https://github.com/oracle/helidon[GitHub].
* If you'd like to report a bug, enhancement request, or check if an
issue is on our list, visit the https://github.com/oracle/helidon/issues[Helidon GitHub issue tracker].


== Stay Informed

* Follow us on Twitter https://twitter.com/helidon_project[@helidon_project]
* Read the https://medium.com/helidon[Helidon blog].
