///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Bean Validation Introduction
:h1Prefix: MP
:pagename: bean-validation
:description: Bean Validation
:keywords: helidon, webserver, bean validation, validation
:bean-validation-spec-url: https://projects.eclipse.org/projects/ee4j.bean-validation
:feature-name: Bean Validation
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc

== ToC

- Overview
- Maven
- Usage
- API
- Configuration
- Reference
- Examples
- Additional Information

== Overview

Helidon supports Bean Validation via its integration with JAX-RS/Jersey. The
{bean-validation-spec-url}[Jakarta Bean
Validation specification] defines an API to validate Java beans.
Bean Validation is supported in REST resource classes as well as in
regular application beans.

If bean validation is required outside JAX-RS/Jersey use cases, it is also available in Helidon.
It follows the standard {bean-validation-spec-url}[Jakarta Bean
Validation specification] which defines an API to validate Java beans.

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source, xml]
----
<dependency>
  <groupId>org.glassfish.jersey.ext</groupId>
  <artifactId>jersey-bean-validation</artifactId>
</dependency>
----

For general validation, please add to your `pom.xml`:

[source, xml]
----
<dependency>
  <groupId>io.helidon.microprofile.bean-validation</groupId>
  <artifactId>helidon-microprofile-bean-validation</artifactId>
</dependency>
----

== API

TODO Add API tables with description

== Reference

TODO

== Examples

1. The following example shows a simple resource method annotated with `@POST` whose
parameter must be _not null_ and _valid_. Validating a parameter in this case implies
making sure that any constraint annotations in the `Greeting` class are satisfied.
The resource method shall never be called if the validation fails, with a 400
(Bad Request) status code returned instead.
+
[source,java]
----
@Path("helloworld")
public class HelloWorld {

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    public void post(@NotNull @Valid Greeting greeting) {
        // ...
    }
}
----

2. The following example shows a simple application with one field declared as _not null_ using `@NotNull` annotation:
+
[source,java]
----
public class GreetingHolder {
    @NotNull
    private String greeting;
    //...
}
----
+
If the bean contains a method parameter annotated with @Valid, and GreetingHolder with _null_greeting is passed, then a _ValidationException_ will be thrown:
+
[source,java]
----
@ApplicationScoped
public class GreetingProvider {
    private GreetingHolder greetingHolder;
    //..
    void setGreeting(@Valid GreetingHolder greetingHolder) {
        this.greetingHolder = greetingHolder;
    }
}
----
+
NOTE: `beans.xml` is required to identify beans and for bean validation to work properly.


== Additional Information

TODO