
///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= MicroProfile Config
:toc:
:toc-placement: preamble
:spec-name: MicroProfile Config
:description: {spec-name} support in Helidon MP
:keywords: helidon, mp, microprofile, config, encryption, reference
:javadoc-base-url-api: {javadoc-base-url}/io.helidon.config/io/helidon/config/
:h1Prefix: MP
:feature-name: MicroProfile Config
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc
:microprofile-bundle: true

Helidon's MicroProfile Config, an implementation of Eclipse MicroProfile Config, enables you to configure your applications using MicroProfile’s config configuration sources and APIs.

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source,xml]
----
        <dependency>
            <groupId>io.helidon.microprofile.config</groupId>
            <artifactId>helidon-microprofile-config</artifactId>
        </dependency>
----

== About {spec-name}

Helidon MicroProfile Config is an implementation of https://github.com/eclipse/microprofile-config/[Eclipse MicroProfile Config].
You can configure your applications using MicroProfile's config configuration sources and APIs. You can also extend the
configuration using MicroProfile SPI to add custom `ConfigSource` and `Converter`.

=== {spec-name} Features

{spec-name} uses `ConfigSource` SPI to load configuration data, either from default configuration sources such
file `META-INF/microprofile-config.properties`, environment variables, and system properties; or from custom `ConfigSource`
located by Java Service Loader.

The data is then available through {spec-name} APIs to be injected into CDI Beans, or to be obtained using a `Config`
instance programmatically.

{spec-name} provides typed access to configuration values, using built-in converters, and `Converter` implementations located
by Java Service Loader.

==== Using {spec-name} API

You can use MicroProfile Config API to get configuration properties by using `ConfigProvider.getConfig()`
or injecting configuration values with `@ConfigProperty`.

[source,java]
.Using ConfigProvider.getConfig()
----
org.eclipse.microprofile.config.Config config = ConfigProvider.getConfig();
config.getOptionalValue("app.greeting", String.class).orElse("Hello");
----

[source,java]
.Injecting configured properties into a constructor
----
@Inject
public GreetingProvider(@ConfigProperty(name = "app.greeting", defaultValue = "Hello") String message) {
    this.message = message
}
----

==== {spec-name} Config Sources

The example below shows how the MicroProfile configuration file `microprofile-config.properties` can be used to modify the server listen port property.

[source,properties]
----
// Application properties. This is the default greeting
app.greeting=Hello

// Microprofile server properties
server.port=8080
server.host=0.0.0.0
----

==== {spec-name} Profiles

{spec-name} supports a concept of configuration profiles. You can define a profile using the configuration property `mp.config.profile`
(when using default configuration, this can be defined as a system property, environment variable or as a property in `microprofile-config.properties`).
When a profile is defined, additional config source is loaded (`microprofile-config-profile.properties`) and properties from profile have precedence over
default properties. Profile properties can be defined using `%profile` prefix, such as `%dev.server.port`.

=== Helidon {spec-name} Features

Helidon MicroProfile Config offers the following features on top of the specification:

* *References* +
You can use `${reference}` to reference another configuration key in a key value. This
allows to configure a single key to be reused in multiple other keys.

[source,yaml]
.Example
----
uri: "http://localhost:8080"
service-1: "${uri}/service1"
service-2: "${uri}/service2"
----


* *Encryption* +
You can encrypt secrets using a master password and store them in a configuration file.
The config encryption filter in MicroProfile Config is enabled by default.
For more information, see <<mp/security/03_configuration-secrets.adoc,Configuration Secrets>>.

[source,properties]
.Example of encrypted secrets
----
# Password encrypted using a master password
client_secret=${GCM=mYRkg+4Q4hua1kvpCCI2hg==}
# Password encrypted using public key (there are length limits when using RSA)
client_secret=${RSA=mYRkg+4Q4hua1kvpCCI2hg==}
# Password in clear text, can be used in development
# The system needs to be configured to accept clear text
client_secret=${CLEAR=known_password}
----

* *Meta Configuration* +
You can configure the Config using Helidon MP Config meta configuration feature. The meta-config allows configuration of config sources and other
configuration options, including addition of discovered sources and converters.

This is a Helidon specific feature available since version 2.3.0. See <<mp/config/02_MP_config_sources.adoc,Microprofile Config Sources>> for detailed information.

NOTE: For backward compatibility, we will support usage of Helidon SE meta-configuration until version 3.0.0. Using this approach causes behavior that is not compatible with {spec-name} specification.

== Guides

[PILLARS]
====
[CARD]
.MP Config Guide
[link=mp/guides/03_config.adoc]
--
Step-by-step guide about using {spec-name} in your Helidon MP application.
--
====

== Additional Information

- link:{javadoc-base-url-api}spi/package-summary.html[Helidon Config SPI]
- link:{javadoc-base-url-api}package-summary.html[Helidon Config API]
- link:https://download.eclipse.org/microprofile/microprofile-config-1.3/apidocs/[Eclispe MicroProfile API]
