///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= MicroProfile Config
:toc:
:toc-placement: preamble
:spec-name: MicroProfile Config
:description: {spec-name} support in Helidon MP
:keywords: helidon, mp, microprofile, config



== About {spec-name}
Helidon MP Config is an implementation of https://github.com/eclipse/microprofile-config/[Eclipse MicroProfile Config] that now includes Helidon-specific meta-configuration and APIs. You can configure your applications using MicroProfile's config properties file and APIs and extend the configuration system with Helidon-specific meta-configuration and APIs. You can also write and register custom ConfigSources.



== Guides

[PILLARS]
====
[CARD]
.MP Config Guide
[link=mp/guides/03_config.adoc]
--
Step-by-step guide about using {spec-name} in your Helidon MP application.
--
====


=== Using MicroProfile Config Sources and META-INF

Default configuration values can be retrieved from system properties, environment variables, files, directories, URLs or configuration files of the form ${CLASSPATH}/META-INF/microprofile-config.properties. 

The example below shows how the MicroProfile configuration file `microprofile-config.properties` can be used to modify properties such as server port or host IP. 

----
# Application properties. This is the default greeting
app.greeting=Hello

# Microprofile server properties
server.port=8080
server.host=0.0.0.0
----

=== Using MicroProfile Config APIs 

The MicroProfile Config API can be used by applications as a single API that can retrieve configuration information from different sources.

The example below shows how the MicroProfile API  `ConfigProviderResolver.getBuilder())` can be used to access String values of configured properties and register user-provided ConfigSources (with `ConfigBuilder`).


----
// MP API to obtain provider resolver
ConfigProviderResolver resolver = ConfigProviderResolver.instance();
Config config = resolver
        // get a new MP config builder
        .getBuilder()
        // add the defaults - environment variables, system properties and META-INF/microprofile-config.properties
        .addDefaultSources()
        // custom MP source
        .withSources(new MyConfigSource())
        // custom MP converter
        .withConverters(new MyConverter())
        // build a new MP config
        .build();
// register the new config with the resolver to be the "current" configuration
resolver.registerConfig(config, Thread.currentThread().getContextClassLoader());
----



=== Using Helidon Meta-Configuration

Instead of directly specifying the configuration sources in your code, you can use meta-configuration in a file that declares the configuration sources and their attributes. This requires using the `Config.loadSourcesFrom` method rather than a `Config.Buider` object. The contents of the meta-configuration file need to be in JSON, YAML, or HOCON format. The meta-config allows configuration of config sources and other configuration options, including retry policies and polling strategies.

The example below shows 

//get description from Tomas//

----
sources:
  - type: "system-properties"
  - type: "environment-variables"
  - type: "file"
    properties:
      optional: true
      path: "mp-config.yaml"
  - type: "classpath"
    multi-source: true
    properties:
      resource: "META-INF/microprofile-config.properties"
----



=== Using Helidon Config APIs

You can use Helidon's APIs such as `Config.builder())` to create a configuration and then register the configuration either through the Helidon MP server builder (`io.helidon.microprofile.server.Server.builder())`, or through MicroProfile APIs. 

 
----
// create a custom instance of Helidon Config
io.helidon.config.Config helidonConfig = io.helidon.config.Config.create();
// register it with MP Config
ConfigProviderResolver.instance()
        .registerConfig((org.eclipse.microprofile.config.Config) helidonConfig, Thread.currentThread().getContextClassLoader());
----

For more information on using Helidon Config APIs, see the Helidon SE Configuration documentation.

== Additional Information

- https://helidon.io/docs/latest/apidocs/io/helidon/config/spi/package-summary.html[Helidon Config SPI]
- https://helidon.io/docs/latest/apidocs/io/helidon/config/package-summary.html[Helidon Config API]
- https://download.eclipse.org/microprofile/microprofile-config-1.3/apidocs/[Eclispe MicroProfile API]
