
///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= MicroProfile Config
:toc:
:toc-placement: preamble
:spec-name: MicroProfile Config
:description: {spec-name} support in Helidon MP
:keywords: helidon, mp, microprofile, config



== About {spec-name}
Helidon MP Config is an implementation of https://github.com/eclipse/microprofile-config/[Eclipse MicroProfile Config] that now includes Helidon-specific meta-configuration and APIs. You can configure your applications using MicroProfile's config properties file and APIs and extend the configuration system with Helidon-specific meta-configuration and APIs. You can also write and register custom ConfigSources.



== Guides

[PILLARS]
====
[CARD]
.MP Config Guide
[link=mp/guides/03_config.adoc]
--
Step-by-step guide about using {spec-name} in your Helidon MP application.
--
====


=== Using MicroProfile Config Sources and META-INF

Default configuration values can be retrieved from system properties, environment variables, files, directories, URLs or configuration files of the form `${CLASSPATH}/META-INF/microprofile-config.properties`. 

The example below shows how the MicroProfile configuration file `microprofile-config.properties` can be used to modify properties such as server port or host IP. 

----
# Application properties. This is the default greeting
app.greeting=Hello

# Microprofile server properties
server.port=8080
server.host=0.0.0.0
----

=== Using MicroProfile Config APIs 

The MicroProfile Config API can be used by applications as a single API that can retrieve configuration information from different sources.

The example below shows how the MicroProfile API  `ConfigProviderResolver.getBuilder())` can be used to access String values of configured properties and register user-provided ConfigSources (with `ConfigBuilder`).


----
// MP API to obtain provider resolver
ConfigProviderResolver configProvider = ConfigProviderResolver.instance();
configProvider.registerConfig(configProvider.getBuilder() <1>
                                    .addDefaultSources() <2>
                                    .withSources(new MyConfigSource()) <3>
                                    .withConverters(new MyConverter()) <4>
                                    .build(), <5>            
Thread.currentThread().getContextClassLoader()) <6>
----

<1> Creates a new MP config builder.
<2> Adds the defaults config sources: environment variables, system properties and META-INF/microprofile-config.properties.
<3> Adds a custom MP source
<4> Adds a custom MP converter
<5> Builds a new MP config
<6> Returns the context ClassLoader for this thread.


=== Using Helidon MicroProfile

You can use Helidon MicroProfile to create a configuration from a classpath Config Source. You undertake a class and get a configuration key from it.

[source, java]
----
Config config = Config.create(classpath(resource:  "application.conf"));
----

=== Using Helidon Meta-Configuration

Instead of directly specifying the configuration sources in your code, you can use meta-configuration in a file that declares the configuration sources and their attributes. This requires using the `Config.loadSourcesFrom` method rather than a `Config.Builder` object. The contents of the meta-configuration file need to be in JSON, YAML, or HOCON format. The meta-config allows configuration of config sources and other configuration options, including retry policies and polling strategies.

Example of a YAML meta configuration file: 

//get description from Tomas//

----
sources:
  - type: "system-properties" <1>
  - type: "environment-variables" <2>
  - type: "file"
    properties:
      optional: true
      path: "mp-config.yaml" <3>
  - type: "classpath"
    properties:
      optional: true
      resource: application:yaml <4> 
    type: "classpath"
    properties:
      resource: "META-INF/microprofile-config.properties" <5>
----

<1> Loads the environment variables config source.
<2> Loads the system variables config source.
<3> Loads the file config source from `mp-config.yaml` that is optional.
<4> Loads the file config source from `application.yaml` that is optional.
<5> Loads the classpath resource config source for  `microprofile-config.properties` that is the default configuration source of Microprofile application and is mandatory.


=== Using Helidon Config APIs

You can use Helidon's APIs such as `Config.builder())` to create a configuration and then register the configuration either through the Helidon MP server builder (`io.helidon.microprofile.server.Server.builder())`, or through MicroProfile APIs. 

 
----

io.helidon.config.Config helidonConfig = io.helidon.config.Config.create(); <1>

ConfigProviderResolver.instance()
        .registerConfig((org.eclipse.microprofile.config.Config) helidonConfig, <2>
        Thread.currentThread().getContextClassLoader());
----

<1> Creates a custom instance of Helidon Config.
<2> Registers the instance with MP Config.

For more information on using Helidon Config APIs, see the Helidon SE Configuration documentation.

== Additional Information

- https://helidon.io/docs/latest/apidocs/io/helidon/config/spi/package-summary.html[Helidon Config SPI]
- https://helidon.io/docs/latest/apidocs/io/helidon/config/package-summary.html[Helidon Config API]
- https://download.eclipse.org/microprofile/microprofile-config-1.3/apidocs/[Eclispe MicroProfile API]
