
///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= MicroProfile Config
:toc:
:toc-placement: preamble
:spec-name: MicroProfile Config
:description: {spec-name} support in Helidon MP
:keywords: helidon, mp, microprofile, config, encryption, reference



== About {spec-name}
Helidon MP Config is an implementation of https://github.com/eclipse/microprofile-config/[Eclipse MicroProfile Config] that now includes Helidon-specific meta-configuration and APIs. You can configure your applications using MicroProfile's config properties file and APIs and extend the configuration system with Helidon-specific meta-configuration and APIs. You can also write and register custom ConfigSources.

=== Helidon MicroProfile Config Features

Helidon MicroProfile Config offers the following features:

* *References* +
You can use dollar, curly brackets, and reference to another key in a value to provide references and contruct the value when you use meta-configuration file for MP configuration. You can either reference the whole value or reference the value and add prefix or suffix, and the referenced value is replaced with the property.

[source=java]
.Example
----

providers:
    - abac:
      # Adds ABAC Provider - it does not require any configuration
    - oidc:
        client-id: "${ALIAS=security.properties.idcs-client-id}"
        client-secret: "${ALIAS=security.properties.idcs-client-secret}"
        identity-uri: "${ALIAS=security.properties.idcs-uri}"
        # A prefix used for custom scopes
        scope-audience: "http://localhost:7987/test-application"
        proxy-host: "${ALIAS=security.properties.proxy-host}"
        frontend-uri: "${ALIAS=security.properties.frontend-uri}"
    - idcs-role-mapper:
        multitenant: false
        oidc-config:
          # Repeat the IDCS configuration, as in this case. IDCS serves both as open ID connect authenticator and as a role mapper. Use of minimal configuration here.
          client-id: "${ALIAS=security.properties.idcs-client-id}"
          client-secret: "${ALIAS=security.properties.idcs-client-secret}"
          identity-uri: "${ALIAS=security.properties.idcs-uri}"
----


* *Encryption* +
You can encrypt configuration values in MicroProfile Config. The config encryption filter is enabled by default. For more information, see <<about/02_configuration-secrets.adoc,Configuration Secrets>>.

//Please provide an example of configuration
[source=java]
.Example


== Guides

[PILLARS]
====
[CARD]
.MP Config Guide
[link=mp/guides/03_config.adoc]
--
Step-by-step guide about using {spec-name} in your Helidon MP application.
--
====


=== Using MicroProfile Config Sources and META-INF

Default configuration values can be retrieved from system properties, environment variables, files, directories, URLs or configuration files of the form `${CLASSPATH}/META-INF/microprofile-config.properties`. 

The example below shows how the MicroProfile configuration file `microprofile-config.properties` can be used to modify properties such as server port or host IP. 

----
# Application properties. This is the default greeting
app.greeting=Hello

# Microprofile server properties
server.port=8080
server.host=0.0.0.0
----

=== Using MicroProfile Config API

You can use the default MicroProfile configuration by injecting configuration properties or use `ConfigProvider.getConfig()`.

----
   org.eclipse.microprofile.config.Config config = ConfigProvider.getConfig();
----

=== Using Helidon Meta Configuration

The meta configuration uses underlying implementation of Helidon config. In this case, you can either inject configuration properties or use `ConfigProvider.getConfig()`.
Instead of directly specifying the configuration sources in your code, you can use meta configuration in a file that declares the configuration sources and their attributes. The contents of the meta-configuration file need to be in JSON, YAML, or HOCON format.
The meta-config allows configuration of config sources and other configuration options, including retry policies and polling strategies.

Example of a YAML meta configuration file: 

----
sources:
  - type: "system-properties" <1>
  - type: "environment-variables" <2>
  - type: "file"
    properties:
      optional: true
      path: "mp-config.yaml" <3>
  - type: "classpath"
    properties:
      optional: true
      resource: application.yaml <4> 
    type: "classpath"
    properties:
      resource: "META-INF/microprofile-config.properties" <5>
----

<1> Loads the environment variables config source.
<2> Loads the system variables config source.
<3> Loads the file config source from `mp-config.yaml` that is optional.
<4> Loads the file config source from `application.yaml` that is optional.
<5> Loads the classpath resource config source for  `microprofile-config.properties` that is the default configuration source of Microprofile application and is mandatory.


=== Using Helidon Config APIs

You can use the `MpConfigSources.create(helidonConfig)` to create a config source from Helidon config and then use it to create a MicroProfile instance.

----
ConfigBuilder metaConfig(io.helidon.config.Config metaConfig) {
        io.helidon.config.Config helidonConfig = io.helidon.config.Config.builder()
                .config(metaConfig)
                .build();
        this.sources.add(new OrdinalSource(MpConfigSources.create(helidonConfig))); <1>
        return this;
    }

ConfigProviderResolver.instance()
                    .getBuilder()
                    .withSources(MpConfigSources.create(config)) <2>
                    .build();
----

<1> Creates a config source from Helidon config.
<5> Creates a MicroProfile config instance.

For more information on using Helidon Config APIs, see the Helidon SE Configuration documentation.

== Additional Information

- https://helidon.io/docs/latest/apidocs/io/helidon/config/spi/package-summary.html[Helidon Config SPI]
- https://helidon.io/docs/latest/apidocs/io/helidon/config/package-summary.html[Helidon Config API]
- https://download.eclipse.org/microprofile/microprofile-config-1.3/apidocs/[Eclispe MicroProfile API]
