///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= MicroProfile Config
:toc:
:toc-placement: preamble
:spec-name: MicroProfile Config
:description: {spec-name} support in Helidon MP
:keywords: helidon, mp, microprofile, config


== About {spec-name}

- About {spec-name} specification. It's goals and what problems it helps solving. 
- Links to the spec and sources.
- What version of the spec is supported in Helidon MP. 
- {spec-name} high level features list.

== Guides

[PILLARS]
====
[CARD]
.MP Config Guide
[link=mp/guides/03_config.adoc]
--
Step-by-step guide about using {spec-name} in your Helidon MP application.
--
====

== Using {spec-name} in Helidon MP applications

=== Configuration

- How to configure your Helidon MP application to support {spec-name} using CLI.
- How to configure your Helidon MP application to support {spec-name} manually.

=== Use case 1

- Description
- Small code snippet

=== Use case 2

- Description
- Small code snippet

=== Use case 3

- Description
- Small code snippet

== Additional Information

- Additional references
- Link to javadocs