///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Microprofile Config Sources
:pagename: MicroProfileSources
:description: MicroProfile Config Sources
:keywords: helidon, mp, ordinal, mpconfig, yamlmpconfig


A Config Source provides configuration values from different sources such as property files and user classes that are registered by the application.

== Understanding the Ordering of Default Config Sources

The default MicroProfile Config Sources are:

* System properties (ordinal=400)
* Environment variables (ordinal=300)
* /META-INF/microprofile-config.properties (ordinal=100)

Each Config Source has a ordinal that determines the priority of the Config Source. A Config Source with higher ordinal has high priority as compared to the Config Source with lower ordinal. The values taken from the high-priority Configsource overrides the values from low-priority Config Source. This helps to customize the configuration of Config Sources using external Config Source if an external Config Source has higher ordinal values than the built-in Config Sources of the application.


== Creating Custom Config Sources

Custom Config Sources are loaded using the Java ServiceLoader pattern and can be registered by providing a file named `org.eclipse.microprofile.config.spi.ConfigSource` in the `/META-INF/services/` folder.

You need to use the following methods and implement the interface `org.eclipse.microprofile.config.spi.ConfigSource` to create a custom Config Source:

* `String getName()`
* `Map<String, String> getProperties()`
* `String getValue(String key)`
* `getOrdinal()`

=== Example of a Custom Config Source

[source,java]
----
public class CustomConfigSource implements ConfigSource {
			String NAME = "MyConfigSource";
			PRIORITY = 200; // Default for MP is 100
			Map<String, String> PROPERTIES = mapOf("app.greeting", "Hi");


	@Override
	public String getName() { 
		return NAME; <1>
	}

	@Override
	public Map<String, String> getProperties() { 
		return PROPERTIES; <2>
	}

	@Override
	public String getValue(String key) {
		return PROPERTIES.get(key); <3>
	}

	@Override
	public int getOrdinal() {
		return PRIORITY; <4>
	}

}
----

<1> Returns the name of the Config Source to use for logging or analysis of configured values.
<2> Returns the properties in this Config Source as a map.
<3> Returns the value stored in the propertyName of this Config Source.
<4> Returns the ordinal based on the set order for this Config Source.


== Creating MicroProfile Config Sources for Manual Setup of Config

You can use the following methods to create MicroProfile Config Sources to manually set up the Config from `org.eclipse.microprofile.config.spi.ConfigProviderResolver#getBuilder()` on `io.helidon.config.mp.MpConfigSources` class:

|===
|Method |Description

|`systemProperties()}`   |System properties config source.

|`environmentVariables()}`   |Environment variables config source.

|`create(java.nio.file.Path)}`   |Loads a properties file from file system. +
To load the properties file from file system with custom name, use `create(String, java.nio.file.Path)}`.

|`create(java.util.Map)}`   |Creates an in-memory source from map. +
To create an in-memory source from map with custom name, use `create(String, java.util.Map)}`.

|`create(java.util.Properties)}`   |Creates an in-memory source from properties. +
To create an in-memory source from properties with custom name, use `create(String, java.util.Properties)}`.

|===

=== Example

[source,java]
.Create MicroProfile Config Source based on Environment Variables and Custom Map
----
org.eclipse.microprofile.config.Config mpConfig = ConfigProviderResolver.instance()
        .getBuilder() <1>
        .withSources(MpConfigSources.environmentVariables()) <2>
        .withSources(MpConfigSources.create(Map.of("key","value"))) <3>
        .build(); <4>
----
<1> Creates MicroProfile Config Source builder.
<2> Adds environment variables.
<3> Adds custom map.
<4> Builds the MicroProfile Config Source.


== Creating MicroProfile Config Source from Helidon SE Config Source

You can create MicroProfile Config Source from Helidon SE Config Source to use Helidon SE features in Helidon MP. The Config Source is immutable regardless of configured polling strategy or change watchers.


// Please provide example


== Creating MicroProfile Config Source from Helidon SE Config Instance

You can create MicroProfile Config Source from Helidon SE Config to use advanced Helidon SE features in Helidon MP. The Config Source is mutable if the config uses either polling strategy and change watchers or polling strategy or change watchers.
The latest config version is queried each time  `org.eclipse.microprofile.config.spi.ConfigSource#getValue(String)` is called.

//Please provide example

== Create Yaml MicroProfile Config Source Programatically

You can create Yaml Microprofile Config Source from a path or a URL. When you create a MicroProfile instance from the builder, the `YamlMPConfigSource` allows you to edit the list of config sources and creates a custom YAML.


=== Example

[source,java]
.Create YamlMPConfigSource from a path 
----
public static ConfigSource create(Path path)
        return create(path.toUri.toURL()); 
----

