///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////
= MicroProfile Config Sources

Configuration properties can be sourced from a number of locations, including property files, and user classes that are either registered by the application or loaded by using the Java ServiceLoader pattern. 

== Understanding the Ordering of Default Config Sources

The default MicroProfile Config Sources are:

* System properties (ordinal=400)
* Environment variables (ordinal=300)
* /META-INF/microprofile-config.properties (ordinal=100)

Each Config Source has a ordinal that determines the priority of the Config Source. A Config Source with higher ordinal has high priority as compared to the Config Source with lower ordinal. The values taken from the high-priority Configsource overrides the values from low-priority Config Source. This helps to customize the configuration of Config Sources using external Config Source if an external Config Source has higher ordinal values than the built-in Config Sources of the application.


=== Config Sources Categorization

The Config Sources are categorized based on how their functionality can be implemented on the config system.

. Eagerness of loading data:

.. Eager Config Sources - The Config Source either loads all data or loads each key separately from the Config Source. The eager Config sources are:

* ParsableSource - An eager source that can read all data from the underlying origin as a stream, which can be parsed based on its content type.

* NodeConfigSource - An eager source that can read all data from the underlying origin as a configuration node.

.. LazyConfigSource - A source that provides value for a single node.

[start=2]
. Mutability of data:

.. Immutable - The default Config Sources that do not support changes.

.. Mutable - The Config Sources that provide capability to change. The mutable Config Sources are:
 
* PollableSource - A source that generates a "stamp" of data that is used to check any changes in the underlying data.

* Watchablesource - A source based on data that has a specific change watcher which notifies the config framework of changes without the need for regular polling.

* EventConfigSource - A source that can directly notify the changes.


== Creating Custom Config Sources

Custom Config Sources are loaded using the Java ServiceLoader pattern and can be registered by providing a file named `org.eclipse.microprofile.config.spi.ConfigSource` in the `/META-INF/services/` folder.

You need to use the following methods and implement the interface `org.eclipse.microprofile.config.spi.ConfigSource` to create a custom Config Source:

* `String getName()`
* `Map<String, String> getProperties()`
* `String getValue(String key)`
* `getOrdinal()`

=== Example of a Custom Config Source

[source,java]
----
public class CustomConfigSource implements ConfigSource {
			String NAME = "Gh1468ConfigSource";
			PRIORITY = 200; // Default for MP is 100
			Map<String, String> PROPERTIES = mapOf("app.greeting", "Hi");


	@Override
	public String getName() { 
		return NAME; <1>
	}

	@Override
	public Map<String, String> getProperties() { 
		return PROPERTIES; <2>
	}

	@Override
	public String getValue(String key) {
		return PROPERTIES.get(key); <3>
	}

	@Override
	public int getOrdinal() {
		return PRIORITY; <4>
	}

}
----

<1> Returns the name of the Config Source to use for logging or analysis of configured values.
<2> Returns the properties in this Config Source as a map.
<3> Returns the value stored in the propertyName of this Config Source.
<4> Returns the ordinal based on the set order for this Config Source.


== Creating MicroProfile Config Sources for Manual Setup of Config

You can use the following methods to create MicroProfile Config Sources to manually set up the Config from `org.eclipse.microprofile.config.spi.ConfigProviderResolver#getBuilder()`:

|===
|Method |Description

|`systemProperties()}`   |System properties config source.

|`environmentVariables()}`   |Environment variables config source.

|`create(java.nio.file.Path)}`   |Loads a properties file from file system. +
To load the properties file from file system with custom name, use `create(String, java.nio.file.Path)}`.

|`create(java.util.Map)}`   |Creates an in-memory source from map. +
To create an in-memory source from map with custom name, use `create(String, java.util.Map)}`.

|`create(java.util.Properties)}`   |Creates an in-memory source from properties. +
To create an in-memory source from properties with custom name, use `create(String, java.util.Properties)}`.


|===

===  Config Source Creation based on System Properties

The Config Source queries the properties each time `org.eclipse.microprofile.config.spi.ConfigSource#getValue(String)` is called.

[source,java]
----
ConfigSource systemProperties() {
        return new MpSystemPropertiesSource();
----

=== Config Source Creation based on Environment Variables

The Config Source replaces the properties with environment variables as defined in MicroProfile Config specification.

[source,java]
----
ConfigSource environmentVariables() { <1>
        return new MpEnvironmentVariablesSource();
----

=== Config Source Creation based on a File on the File System

The Config Source reads the file just once when the source is created and any other changes to the file are ignored.

[source,java]
----
ConfigSource create(Path path) { <1>
        return create(path.toString(), path);
----

<1> Creates path of the properties file on the file system.

=== Config Source Creation based on a URL

The Config Source reads the URL just once when the source is created and any other changes to the resource are ignored.

[source,java]
----
ConfigSource create(URL url) { <1>
        String name = url.toString();
----

<1> Creates URL of the properties file.

=== In-Memory Config Source Creation From Map

The config source queries the map each time `org.eclipse.microprofile.config.spi.ConfigSource#getValue(String)` is called.

[source,java]
----

ConfigSource create(Map<String, String> theMap) { <1>
        return create("Map", theMap); 
----

<1> Creates map that serves as configuration data.

=== In-Memory Config Source Creation From Properties

The Config Source queries the properties each time `org.eclipse.microprofile.config.spi.ConfigSource#getValue(String)` is called.

[source,java]
----
ConfigSource create(Properties properties) { <1>
        return create("Properties", properties);
----

<1> Creates properties that serves as configuration data.


== Creating MicroProfile Config Sources from Helidon SE Config

This method supports Helidon SE features in Helidon MP. The Config Source is immutable regardless of configured polling strategy or change watchers.

[source,java]
----
ConfigSource create(io.helidon.config.spi.ConfigSource helidonConfigSource) {
        return MpHelidonSource.create(helidonConfigSource);
----

== Creating MicroProfile Config Sources from Helidon SE Config Instance

This method supports advanced Helidon SE features in Helidon MP. The Config Source is mutable if the config uses either polling strategy and change watchers or polling strategy or change watchers.
The latest config version is queried each time  `org.eclipse.microprofile.config.spi.ConfigSource#getValue(String)` is called.

[source,java]
----
ConfigSource create(Config config) {
        return new MpHelidonConfigSource(config);
----












