///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Micrometer Metrics
:description: Helidon Micrometer integration
:keywords: micrometer, helidon, metrics, integration
:javadoc-base-url-api: {javadoc-base-url}io.helidon.integrations.micrometer/io/helidon/integrations/micrometer
:h1Prefix: SE
:common-page-prefix-inc: ../../shared/micrometer/common_shared.adoc
:isSE: true

include::{common-page-prefix-inc}[tags=intro;!intro-mp-specific]

include::{common-page-prefix-inc}[tags=prereq]

== Using Micrometer in Your Application
You need to make two types of changes to your application to use Helidon SE integration with Micrometer:

. Register an instance of link:{javadoc-base-url-api}/MicrometerSupport.html[`MicrometerSupport`] with the web server.
. Create  meters using the meter registry which `MicrometerSupport` manages and update those meters.

=== Register an Instance of `MicrometerSupport` with the Web Server

[source,java]
.Initialize Micrometer support
----
import io.helidon.integrations.micrometer.MicrometerSupport;
//...
MicrometerSupport micrometerSupport = MicrometerSupport.create(); // <1>

Routing.builder()
                .register(micrometerSupport) // <2>
                .register("/myapp", new MyService(micrometerSupport.registry())) // <3>
                .build();
----
<1> Create the `MicrometerSupport` instance, using the default built-in Prometheus meter registry.
<2> Register the support instance as a service; by default, `MicrometerSupport` exposes the endpoint as `/micrometer`.
<3> Pass the `MicrometerSupport` object's meter registry to your service for use in creating and updating meters.

=== Create and Update Meters in your Application Service

[source,java]
.Define and use a `Counter`
----
import io.micrometer.core.instrument.Counter;

public class MyService implements Service {

    private final Counter requestCounter;

    public MyService(MicrometerMeterRegistry registry) {
        requestCounter = registry.counter("allRequests"); // <1>
        // ...
    }

    @Override
    public void update(Routing.Rules rules) {
        rules
            .any(this::countRequests) // <2>
            .get("/", this::myGet);
    }

    private void countRequests(ServerRequest request, ServerResponse response) {
        requestCounter.increment(); // <3>
        request.next();
    }
}
----
<1> Use the Micrometer meter registry to create the request counter.
<2> Add routing for any request to invoke the method which counts requests by updating the counter.
<3> Update the counter and delegate the rest of the request processing to the next handler in the chain.

The example above enrolls the built-in Prometheus meter registry with the default Prometheus registry configuration.
You can change the default setup for built-in registries, and you can enroll other meter registries your application
creates itself.

include::{common-page-prefix-inc}[tag=overriding-intro]

You can override these defaults in either of two ways:

* Using the link:{javadoc-base-url-api}/MicrometerSupport.Builder.html[`MicrometerSupport.Builder`] class
* Using configuration

==== Using `MicrometerSupport.Builder`
Use the `MicrometerSupport.Builder` class to set up Micrometer support however your application needs.

The builder lets you:

* Provide your own Micrometer meter registry configuration that `MicrometerSupport` uses to create a built-in meter
registry, or
* Instantiate a Micrometer meter registry yourself, configured however you want, and add it to the `MicrometerSupport`
object's collection of meter registries

[source,java]
.Overriding defaults for built-in meter registries using `MicrometerSupport.Builder`
----
PrometheusConfig myPrometheusConfig = ...; // <1>
MicrometerSupport support = MicrometerSupport.builder()
                .enrollBuiltInRegistry( // <2>
                        MicrometerSupport.BuiltInRegistryType.PROMETHEUS,
                        myPrometheusConfig)
                .build();
----
<1> Create the meter registry configuration however you need.
<2> Enroll the `PROMETHEUS` built-in registry type with your custom configuration.


==== Using Configuration
include::{common-page-prefix-inc}[tag=overriding-using-config]


=== Enrolling other Micrometer meter registries
To create additional types of registries and enroll them with `MicrometerSupport`, you need to:

. Write a `Handler` +
+
Each meter registry has its own way of producing output.
Write your handler so that it has a reference to the meter registry it should use and so that
its `accept` method sets the payload in the HTTP response using the registry's mechanism for creating output.

. Write a `Function` which accepts a `ServerRequest` and returns an `Optional<Handler>` +
+
In general, your function looks at the request--the `Content-Type`, query parameters, etc.--to
decide whether your handler should respond to the request.
If so, your function should instantiate your `Handler` and return an `Optional.of(theHandlerInstance)`;
otherwise, your function should return `Optional.empty()`. +
+
When `MicrometerSupport` receives a request, it invokes the functions of all the enrolled registries,
stopping as soon as one function provides a handler.
`MicrometerSupport` then delegates to that handler to create and send the response.

. Pass the `Handler` and `Function` to the `MicrometerSupport.enrollRegistry` method to enroll them +
+
[source,java]
.Creating and enrolling your own Micrometer meter registry
----
MeterRegistry myRegistry = new PrometheusMeterRegistry(myPrometheusConfig); // <1>
MicrometerSupport support = MicrometerSupport.builder()
                .enrollRegistry(myRegistry,
                               request -> request // <2>
                                    .headers()
                                    .bestAccepted(MediaType.TEXT_PLAIN).isPresent()
                                    ? Optional.of((req, resp) ->
                                            resp.send(myRegistry.scrape())) // <3>
                                    : Optional.empty())
                .build();
----
<1> Create the meter registry. This example uses a Prometheus registry but it can be any extension of `MeterRegistry`.
<2> Provide the function that checks if the link:{javadoc-base-url-webserver}/ServerRequest.html[`ServerRequest`]
accepts content that your meter registry can produce (e.g., either `text/plain` or unspecified is normally an indication for Prometheus-style output)
and returns the appropriate `Optional<link:{:javadoc-base-url-webserver}/Handler.html[``Handler``]>`.
<3> A very simple in-line `Handler` that sets the response entity from the Prometheus registry's `scrape()` method.

include::{common-page-prefix-inc}[tag=accessing-endpoint-intro]

When `MicrometerSupport` receives a request at the endpoint, it looks for the first enrolled meter registry for which
the corresponding `Function<ServerRequest, Optional<Handler>>` returns a non-empty `Handler`.
Helidon invokes that `Handler` which must retrieve the metrics output from its meter registry and set
and send the response.
Note that the `Handler` which your function returns typically has a reference to the meter registry it will use
in preparing the response.


