///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Micrometer Metrics
:description: Helidon Micrometer metrics
:keywords: micrometer, helidon, metrics
:javadoc-base-url-api: {javadoc-base-url}io.helidon.metrics.micrometer/io/helidon/metrics/micrometer
:h1Prefix: SE

Helidon {h1Prefix} simplifies how you can use Micrometer for application-specific metrics:

* The endpoint `/micrometer`: A configurable endpoint that exposes metrics according to which Micrometer meter registry
responds to the HTTP request.
* The `MicrometerSupport` class: A convenience class for enrolling Micrometer meter registries your application
creates explicitly or for selecting which built-in Micrometer meter registries to
to use.

In Helidon {helidon-version}, Micrometer support is separate from the Helidon SE metrics API and the built-in Helidon metrics.

== Prerequisites

Declare the following dependency in your project:

[source,xml,subs="verbatim,attributes"]
----
    <dependency>
        <groupId>io.helidon.metrics</groupId>
        <artifactId>helidon-metrics-micrometer</artifactId>
    </dependency>
----

Micrometer supports different meter registries for different output styles and formats.
Helidon provides built-in support for the Prometheus meter registry.
To use other meter registry types, you will need to add dependencies for them to your `pom.xml`.

== Using Micrometer in Your Application
You need to make two types of changes to your application to use Helidon's Micrometer support:

1. Register an instance of link:{javadoc-base-url-api}/MicrometerSupport.html[`MicrometerSupport`] with the web server.
2. Modify your application service code to use the meter registry which `MicrometerSupport` manages to create
and update meters.

=== Register an Instance of `MicrometerSupport` with the Web Server

[source,java]
.Initialize Micrometer support
----
import io.helidon.metrics.MicrometerSupport;
//...
MicrometerSupport micrometerSupport = MicrometerSupport.create(); // 1

Routing.builder()
                .register(micrometerSupport) // 2
                .register("/myapp", new MyService(micrometerSupport.registry())) // 3
                .build();
----
<1> Create the `MicrometerSupport` instance, using the default built-in Prometheus meter registry.
<2> Register the support instance as a service; by default, `MicrometerSupport` exposes the endpoint as `/micrometer`.
<3> Pass the `MicrometerSupport` object's meter registry to your service for use in creating and updating meters.

=== Create and Update Micrometer Meters in your Application Service

[source,java]
.Define and use a `Counter`
----
import io.micrometer.core.instrument.Counter;

public class MyService implements Service {

    private final Counter requestCounter;

    public MyService(MicrometerMeterRegistry registry) {
        requestCounter = registry.counter("allRequests"); // 1
        // ...
    }

    @Override
    public void update(Routing.Rules rules) {
        rules
            .any(this::countRequests) // 2
            .get("/", this::myGet);
    }

    private void countRequests(ServerRequest request, ServerResponse response) {
        requestCounter.increment(); // 3
        request.next();
    }
}
----
<1> Use the Micrometer meter registry to create the request counter.
<2> Add routing for any request to invoke the method which counts requests by updating the counter.
<3> Update the counter and delegate the rest of the request processing to the next handler in the chain.

The example above enrolls the built-in Prometheus meter registry with the default Prometheus registry configuration.
You can change the default setup for built-in registries, and you can enroll other meter registries your application
creates itself.

=== Overriding Defaults for Built-in Meter Registry Types
Unless otherwise instructed, Helidon uses defaults for any built-in Micrometer meter registry. For example, Helidon configures the built-in
Prometheus registry using `PrometheusConfig.DEFAULT`.

You can override these defaults in either of two ways:

* Using the link:{javadoc-base-url-api}/MicrometerSupport.Builder.html[`MicrometerSupport.Builder`] class
* Using configuration

==== Using `MicrometerSupport.Builder`
Use the `MicrometerSupport.Builder` class to set up Micrometer support however your application needs.

The builder lets you:

* Provide your own Micrometer meter registry configuration that `MicrometerSupport` uses to create a built-in meter
registry, or
* Instantiate a Micrometer meter registry yourself, configured however you want, and add it to the `MicrometerSupport`
object's collection of meter registries

[source,java]
.Overriding defaults for built-in meter registries using `MicrometerSupport.Builder`
----
PrometheusConfig myPrometheusConfig = ...; // 1
MicrometerSupport support = MicrometerSupport.builder()
                .enrollBuiltInRegistry( // 2
                        MicrometerSupport.BuiltInRegistryType.PROMETHEUS,
                        myPrometheusConfig)
                .build();
----
<1> Create the meter registry configuration however you need.
<2> Enroll the `PROMETHEUS` built-in registry type with your custom configuration.


==== Using Configuration
To use configuration to control the selection and behavior of Helidon's built-in Micrometer meter registries,
include in your configuration a `metrics.micrometer.builtin-registries` section.

[source,yaml]
.Enroll Prometheus built-in meter registry using default configuration
----
metrics:
  micrometer:
    builtin-registries:
      - type: prometheus
----

[source,yaml]
.Enroll Prometheus built-in meter registry with non-default configuration
----
metrics:
  micrometer:
    builtin-registries:
      - type: prometheus
        prefix: myPrefix
----

The configuration keys that are valid for the 'builtin-registries' entry depend on the type of Micrometer meter
registry.
Refer to the documentation for the meter registry you want to configure to find out what items apply to that registry
type.

Helidon does not validate the configuration keys you specify against the items defined by the corresponding
meter registry configuration class.

=== Enrolling other Micrometer meter registries
To create your own registries and enroll them with `MicrometerSupport`, you need to:

1. Write a `Handler` +
+
Each meter registry has its own way of producing output.
Write your handler so that it has a reference to the meter registry it should use and so
its `accept` method sets the payload in the HTTP response using the registry's mechanism for creating output.

1. Write a `Function` which accepts a `ServerRequest` and returns an `Optional<Handler>` +
+
In general, your function looks at the request--the `Content-Type`, query parameters, etc.--to
decide whether your handler should respond to the request.
If so, your function should instantiate your `Handler` and return an `Optional.of(theInstance)`;
otherwise, your function should return `Optional.empty()`. +
+
When `MicrometerSupport` receives a request, it invokes the functions of all the enrolled registries,
stopping as soon as one function provides a handler.
`MicrometerSupport` then delegates to that handler to create and send the response.

* Pass the `Handler` and `Function` to the `MicrometerSupport.enrollRegistry` method to enroll them

[source,java]
.Creating and enrolling your own Micrometer meter registry
----
MeterRegistry myRegistry = new PrometheusMeterRegistry(myPrometheusConfig); // 1
MicrometerSupport support = MicrometerSupport.builder()
                .enrollRegistry(myRegistry,
                               request -> request // 2
                                    .headers()
                                    .bestAccepted(MediaType.TEXT_PLAIN).isPresent()
                                    ? Optional.of((req, resp) ->
                                            resp.send(myRegistry.scrape())) // 3
                                    : Optional.empty())
                .build();
----
<1> Create the meter registry. This example uses a Prometheus registry but it can be any extension of `MeterRegistry`.
<2> Provide the function that checks if the link:{javadoc-base-url-webserver}/ServerRequest.html[`ServerRequest`]
accepts `text/plain` (or unspecified) content (either is normally an indication for Prometheus-style output)
and returns the appropriate `Optional<link:{:javadoc-base-url-webserver}/Handler.html[``Handler``]>`.
<3> A very simple in-line `Handler` that sets the response entity from the Prometheus registry's `scrape()` method.

== Accessing the Helidon Micrometer Endpoint
By default, Helidon Micrometer support exposes the `/micrometer` endpoint. You can override this
using the `Builder` or the `metrics.micrometer.web-context` configuration key.

When `MicrometerSupport` receives a request at the endpoint, it looks for the first enrolled meter registry for which
the corresponding `Function<ServerRequest, Optional<Handler>>` returns a non-empty `Handler`.
Helidon invokes that `Handler` which must retrieve the metrics output from the corresponding meter registry and set
and send the response.
Note that the `Handler` which your function returns must have a reference to the meter registry it will use
in preparing the response.
