///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Metrics Support for Exemplars
:h1Prefix: SE
:description: Helidon metrics
:keywords: helidon, metrics, exemplar, prometheus, OpenMetrics
:zipkin-page: ../../shared/tracing/tracer-zipkin.adoc
:jaeger-page: ../../shared/tracing/tracer-jaeger.adoc
:open-metrics-spec-exemplars: https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars

Add Helidon SE and MP support for  link:{open-metrics-spec-exemplars}[OpenMetrics (Prometheus) exemplars] for histograms, counters, and simple timers to your application simply by adding dependencies to your project's `pom.xml`.

== Prerequisites

Declare the following dependency in your project:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>io.helidon.metrics</groupId>
    <artifactId>helidon-metrics-trace-exemplar</artifactId>
    <scope>runtime</scope>
</dependency>
----

Also, include either link:{zipkin-page}[Helidon Zipkin] or link:{jaeger-page}[Helidon Jaeger] support:
include::{zipkin-page}[tag=zipkin-dependency]
or
include::{jaeger-page}[tag=jaeger-dependency]

Be sure Zipkin or Jaeger, whichever you chose, is running and accessible to your server.

== Interpreting Exemplars footnote:[link:https://www.merriam-webster.com/dictionary/exemplar[exemplar (Mirriam-Webster)] - one that serves as a model or example.]

When you add the `helidon-metrics-trace-exemplar` dependency--and one for either Zipkin or Jaeger--to your application, Helidon automatically records a label and timestamp with each histogram and simple timer sample and with each counter update. Helidon adds the label, sample value, and timestamp to the OpenMetrics output returned from the Helidon metrics endpoint (`/metrics` unless you set it up otherwise).

.Exemplar output - `Timer`
[listing]
----
# TYPE application_getTimer_mean_seconds gauge
application_getTimer_mean_seconds 8.303030623354298E-4 # {trace_id="067632454fe4e8d1"} 1.14701E-4 1617723032.570000 <1>
# TYPE application_getTimer_max_seconds gauge
application_getTimer_max_seconds 0.003952636 # {trace_id="fce183094e471633"} 0.003952636 1617723030.108000 <2>
# TYPE application_getTimer_min_seconds gauge
application_getTimer_min_seconds 5.5254E-5 # {trace_id="0b1a4bf22b4e47fd"} 5.5254E-5 1617723033.311000
----
<1> This exemplar is a sample with value at least as close to the mean as any other sample.
<2> This exemplar is for an exact sample with value the same as the maximum value the timer has observed.

.Exemplar output - `SimpleTimer`
[listing]
----
# TYPE application_globalRequestTracker_total counter
# HELP application_globalRequestTracker_total
application_globalRequestTracker_total 4 # {trace_id="daf26fe35fee9917"} 0.001183992 1617725180.234000 <1>
# TYPE application_globalRequestTracker_elapsedTime_seconds gauge
application_globalRequestTracker_elapsedTime_seconds 0.030309068 # {trace_id="daf26fe35fee9917"} 0.001183992 1617725180.234000 <1>
----
<1> The exemplar for a `SimpleTimer` is the same for the `total` and the `elapsedTime` submetrics: always the most recent sample which updated the `SimpleTimer`.

Helidon adds an exemplar to the output for each statistical value--such as minimum, maximum, mean, and quantiles--for histograms, timers, simple times, and for counters. The exemplar information describes a single, actual sample that is representative of the statistical value.
Helidon chooses the representative examplar for each value using information that is already recorded for each type of metric:

. If a metric necessarily corresponds to a specific sample--for example a minimum or maximum--Helidon associates a sample that has that exact value as the exemmplar for the metric.
. If a metric collects samples into bins (quantiles), Helidon associates a sample from that bin with the bin's output.
. If a metric maintains running statistics (counts, totals), Helidon associates the most recent sample for that metric.
. If Helidon computes a metric's value from a number of samples--for example, mean--Helidon associates a sample for which its value is at least as close as other samples to the statistical calculation.

In cases with multiple representative samples (for example, two samples' values are equally close to the mean), Helidon chooses one of them arbitrarily.


