--
-- Copyright (c) 2026 Oracle and/or its affiliates.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE CONTACT (
    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(80) NOT NULL,
    EMAIL VARCHAR2(160) UNIQUE
);
INSERT INTO CONTACT (NAME, EMAIL) VALUES ('alpha', 'alpha@example.test');
INSERT INTO CONTACT (NAME, EMAIL) VALUES ('beta', NULL);

CREATE TABLE SCALAR_VALUE (
    ID NUMBER(10) PRIMARY KEY,
    BOOLEAN_VALUE NUMBER(1),
    BYTE_VALUE NUMBER(3),
    SHORT_VALUE NUMBER(5),
    INTEGER_VALUE NUMBER(10),
    LONG_VALUE NUMBER(19),
    FLOAT_VALUE BINARY_FLOAT,
    DOUBLE_VALUE BINARY_DOUBLE,
    DECIMAL_VALUE NUMBER(20, 2),
    STRING_VALUE VARCHAR2(160),
    SECOND_STRING_VALUE VARCHAR2(160),
    BYTES_VALUE RAW(160),
    LOCAL_DATE_VALUE DATE,
    LOCAL_TIME_VALUE TIMESTAMP,
    LOCAL_DATE_TIME_VALUE TIMESTAMP,
    OFFSET_TIME_VALUE TIMESTAMP WITH TIME ZONE,
    OFFSET_DATE_TIME_VALUE TIMESTAMP WITH TIME ZONE,
    DATE_VALUE DATE,
    TIME_VALUE TIMESTAMP,
    TIMESTAMP_VALUE TIMESTAMP
);
INSERT INTO SCALAR_VALUE (ID) VALUES (1);

CREATE TABLE TX_MATRIX (
    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DATA_VALUE VARCHAR2(40) NOT NULL
);
INSERT INTO TX_MATRIX (DATA_VALUE) VALUES ('baseline');
