///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Long Running Actions (LRA)
:description: Long Running Actions
:keywords: helidon, mp, lra
:h1Prefix: MP
:feature-name: Long Running Actions
:spec-version: 1.0-RC3
:spec-name: MicroProfile {feature-name} specification
:javadoc-link: https://download.eclipse.org/microprofile/microprofile-lra-{spec-version}/apidocs/org/eclipse/microprofile/lra/annotation/
:microtx-link: https://docs.oracle.com/en/database/oracle/transaction-manager-for-microservices/index.html
:rootdir: {docdir}/..

include::{rootdir}/includes/mp.adoc[]

== Contents

* <<Overview, Overview>>
* <<Maven Coordinates, Maven Coordinates>>
* <<Usage, Usage>>
* <<API, API>>
* <<Configuration, Configuration>>
* <<Examples, Examples>>
* <<Testing, Testing>>
* <<Additional Information, Additional Information>>
** <<Coordinator, Coordinator>>
** <<MicroTx LRA Coordinator, MicroTx LRA Coordinator>>
** <<Helidon LRA Coordinator, Helidon LRA Coordinator>>
** <<Narayana, Narayana>>
* <<Reference, Reference>>

== Overview

Distributed transactions for microservices are known as SAGA design patterns and are defined by the {microprofile-lra-spec-url}[{spec-name}].
Unlike well known XA protocol, LRA is asynchronous and therefore much more scalable. Every LRA JAX-RS resource (<<Participant, participant>>) defines endpoints to be invoked when transaction needs to be _completed_ or _compensated_.


include::{rootdir}/includes/dependencies.adoc[]
[source,xml]
----
<dependencies>
    <dependency>
      <groupId>io.helidon.microprofile.lra</groupId>
      <artifactId>helidon-microprofile-lra</artifactId>
    </dependency>
    <!-- Support for Narayana coordinator -->
    <dependency>
      <groupId>io.helidon.lra</groupId>
      <artifactId>helidon-lra-coordinator-narayana-client</artifactId>
    </dependency>
</dependencies>
----

== Usage

The LRA transactions need to be coordinated over REST API by the LRA coordinator. <<Coordinator, Coordinator>>
keeps track of all transactions and calls the `@Compensate` or `@Complete` endpoints for all participants involved in the particular
transaction. LRA transaction is first started, then joined by <<Participant, participant>>.
The participant reports the successful finish of the transaction by calling it complete. The coordinator then calls the JAX-RS
_complete_ endpoint that was registered during the join of each
<<Participant, participant>>. As the completed or compensated participants don't have to be on same instance,
the whole architecture is highly scalable.

image::lra/lra-complete-lb.svg[Complete]

If an error occurs during the LRA transaction, the participant reports a cancellation of LRA to the coordinator. <<Coordinator, Coordinator>> calls compensate on all the joined participants.

image::lra/lra-compensate-lb-error.svg[Cancel]

When a participant joins the LRA with timeout defined `@LRA(value = LRA.Type.REQUIRES_NEW, timeLimit = 5, timeUnit = ChronoUnit.MINUTES)`, the coordinator compensates if the timeout occurred before the close is reported by the participants.

image::lra/lra-compensate-lb-timeout.svg[Timeout]

== API

=== Participant

The Participant, or Compensator, is an LRA resource with at least one of the JAX-RS(or non-JAX-RS) methods annotated with
{javadoc-link}Compensate.html[@Compensate] or {javadoc-link}AfterLRA.html[@AfterLRA].


=== @LRA [[lra-method]]

{javadoc-link}ws/rs/LRA.html[~javadoc~]

Marks JAX-RS method which should run in LRA context and needs to be accompanied by at least minimal set of mandatory
participant methods(<<compensate-participant-method,Compensate>> or <<after-participant-method,AfterLRA>>).

LRA options:

* {javadoc-link}ws/rs/LRA.html#value--[value]
** {javadoc-link}ws/rs/LRA.Type.html#REQUIRED[REQUIRED] join incoming LRA or create and join new
** {javadoc-link}ws/rs/LRA.Type.html#REQUIRES_NEW[REQUIRES_NEW] create and join new LRA
** {javadoc-link}ws/rs/LRA.Type.html#MANDATORY[MANDATORY] join incoming LRA or fail
** {javadoc-link}ws/rs/LRA.Type.html#SUPPORTS[SUPPORTS] join incoming LRA or continue outside LRA context
** {javadoc-link}ws/rs/LRA.Type.html#NOT_SUPPORTED[NOT_SUPPORTED] always continue outside LRA context
** {javadoc-link}ws/rs/LRA.Type.html#NEVER[NEVER] Fail with 412 if executed in LRA context
** {javadoc-link}ws/rs/LRA.Type.html#NESTED[NESTED] create and join new LRA nested in the incoming LRA context
* {javadoc-link}ws/rs/LRA.html#timeLimit--[timeLimit] max time limit before LRA gets cancelled automatically by <<Coordinator, coordinator>>
* {javadoc-link}ws/rs/LRA.html#timeUnit--[timeUnit] time unit if the timeLimit value
* {javadoc-link}ws/rs/LRA.html#end--[end] when false LRA is not closed after successful method execution
* {javadoc-link}ws/rs/LRA.html#cancelOn--[cancelOn] which HTTP response codes of the method causes LRA to cancel
* {javadoc-link}ws/rs/LRA.html#cancelOnFamily--[cancelOnFamily] which family of HTTP response codes causes LRA to cancel


Method parameters:

* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - ID of the LRA transaction

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_1, indent=0]
----

=== @Compensate [[compensate-participant-method]]

{javadoc-link}Compensate.html[~javadoc~]

CAUTION: Expected to be called by LRA <<Coordinator, coordinator>> only!

Compensate method is called by a <<Coordinator, coordinator>> when LRA is cancelled,
usually by error during execution of method body of <<lra-method,@LRA annotated method>>.
If the method responds with 500 or 202, coordinator will eventually try the call again.
If participant has <<status-participant-method,@Status annotated method>>, <<Coordinator, coordinator>>
retrieves the status to find out if retry should be done.


==== JAX-RS variant with supported LRA context values:

* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - ID of the LRA transaction
* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_PARENT_CONTEXT_HEADER[LRA_HTTP_PARENT_CONTEXT_HEADER] - parent LRA ID in case of nested LRA

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_2, indent=0]
----

==== Non JAX-RS variant with supported LRA context values:

* URI with LRA ID

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_3, indent=0]
----

=== @Complete [[complete-participant-method]]

{javadoc-link}Complete.html[~javadoc~]

CAUTION: Expected to be called by LRA <<Coordinator, coordinator>> only!

Complete method is called by <<Coordinator, coordinator>> when LRA is successfully closed.
If the method responds with 500 or 202, coordinator will eventually try the call again.
If participant has <<status-participant-method,@Status annotated method>>, <<Coordinator, coordinator>> retrieves the status to find out if retry should be done.

==== JAX-RS variant with supported LRA context values:

* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - ID of the LRA transaction
* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_PARENT_CONTEXT_HEADER[LRA_HTTP_PARENT_CONTEXT_HEADER] - parent LRA ID in case of nested LRA

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_4, indent=0]
----

==== Non JAX-RS variant with supported LRA context values:

* URI with LRA ID

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_5, indent=0]
----

=== @Forget

{javadoc-link}Forget.html[~javadoc~]

CAUTION: Expected to be called by LRA <<Coordinator, coordinator>> only!

<<complete-participant-method,Complete>> and <<complete-participant-method,compensate>>
methods can fail(500) or report that compensation/completion is in progress(202).
In such case participant needs to be prepared to report its status over <<status-participant-method,@Status annotated method>>
to <<Coordinator, coordinator>>.
When <<Coordinator, coordinator>> decides all the participants have finished, method annotated with @Forget is called.

==== JAX-RS variant with supported LRA context values:

* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - ID of the LRA transaction
* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_PARENT_CONTEXT_HEADER[LRA_HTTP_PARENT_CONTEXT_HEADER] - parent LRA ID in case of nested LRA

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_6, indent=0]
----

==== Non JAX-RS variant with supported LRA context values:

* URI with LRA ID

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_7, indent=0]
----

=== @Leave

{javadoc-link}ws/rs/Leave.html[~javadoc~]

Method annotated with @Leave called with LRA context(with header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER]) informs <<Coordinator, coordinator>> that current participant is leaving the LRA.
Method body is executed after leave signal is sent.
As a result, participant methods complete and compensate won't be called when the particular LRA ends.

* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - ID of the LRA transaction

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_8, indent=0]
----

=== @Status [[status-participant-method]]

{javadoc-link}Status.html[~javadoc~]

CAUTION: Expected to be called by LRA <<Coordinator, coordinator>> only!

If the coordinator's call to the participant's method fails, then it will retry the call.
If the participant is not idempotent, then it may need to report its state to coordinator by declaring method
annotated with @Status for reporting if previous call did change participant status.
<<Coordinator, Coordinator>> can call it and decide if compensate or complete retry is needed.

==== JAX-RS variant with supported LRA context values:

* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - ID of the LRA transaction
* {javadoc-link}ParticipantStatus.html[ParticipantStatus] - Status of the participant reported to <<Coordinator, coordinator>>

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_9, indent=0]
----

==== Non JAX-RS variant with supported LRA context values:

* URI with LRA ID
* {javadoc-link}ParticipantStatus.html[ParticipantStatus] - Status of the participant reported to <<Coordinator, coordinator>>

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_10, indent=0]
----

=== @AfterLRA [[after-participant-method]]

{javadoc-link}AfterLRA.html[~javadoc~]

CAUTION: Expected to be called by LRA <<Coordinator, coordinator>> only!

Method annotated with {javadoc-link}AfterLRA.html[@AfterLRA] in the same class as the one with @LRA annotation gets invoked after particular LRA finishes.

==== JAX-RS variant with supported LRA context values:

* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_ENDED_CONTEXT_HEADER[LRA_HTTP_ENDED_CONTEXT_HEADER] - ID of the finished LRA transaction
* Header {javadoc-link}ws/rs/LRA.html#LRA_HTTP_PARENT_CONTEXT_HEADER[LRA_HTTP_PARENT_CONTEXT_HEADER] - parent LRA ID in case of nested LRA
* {javadoc-link}LRAStatus.html[LRAStatus] - Final status of the LRA ({javadoc-link}LRAStatus.html#Cancelled[Cancelled], {javadoc-link}LRAStatus.html#Closed[Closed], {javadoc-link}LRAStatus.html#FailedToCancel[FailedToCancel], {javadoc-link}LRAStatus.html#FailedToClose[FailedToClose])

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_11, indent=0]
----

==== Non JAX-RS variant with supported LRA context values:

* URI with finished LRA ID
* {javadoc-link}LRAStatus.html[LRAStatus] - Final status of the LRA ({javadoc-link}LRAStatus.html#Cancelled[Cancelled], {javadoc-link}LRAStatus.html#Closed[Closed], {javadoc-link}LRAStatus.html#FailedToCancel[FailedToCancel], {javadoc-link}LRAStatus.html#FailedToClose[FailedToClose])

[source,java]
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_12, indent=0]
----

== Configuration

[source,text]
.Type
----
io.helidon.microprofile.lra
----

.Optional configuration options
[cols="3,3,2,5a"]

|===
|Key |Type |Default value |Description

|`mp.lra.coordinator.url` |string |`\http://localhost:8070/lra-coordinator` |Url of coordinator.
|`mp.lra.coordinator.propagation.active` |boolean |{nbsp} |Propagate LRA headers `LRA_HTTP_CONTEXT_HEADER` and `LRA_HTTP_PARENT_CONTEXT_HEADER` through non-LRA endpoints.
|`mp.lara.participant.url` |string |{nbsp} |Url of the LRA enabled service overrides standard base uri, so coordinator can call load-balancer instead of the service.
|`mp.lra.coordinator.timeout` |string |{nbsp} |Timeout for synchronous communication with coordinator.
|`mp.lra.coordinator.timeout-unit` |string |{nbsp} |Timeout unit for synchronous communication with coordinator.

|===


[source,yaml]
.Example of LRA configuration
----
mp.lra:
  coordinator.url: http://localhost:8070/lra-coordinator <1>
  propagation.active: true <2>
  participant.url: https://coordinator.visible.host:443/awesomeapp <3>
----
<1> Url of coordinator
<2> Propagate LRA headers LRA_HTTP_CONTEXT_HEADER and LRA_HTTP_PARENT_CONTEXT_HEADER through non-LRA endpoints
<3> Url of the LRA enabled service overrides standard base uri,
so coordinator can call load-balancer instead of the service

For more information continue to {microprofile-lra-spec-url}[{spec-name}].

== Examples

The following example shows how a simple LRA participant starts and joins a transaction after calling the '/start-example' resource.
When startExample method finishes successfully, close is reported to <<Coordinator, coordinator>>
and `/complete-example` endpoint is called by coordinator to confirm successful closure of the LRA.

If an exception occurs during startExample method execution, coordinator receives cancel call and `/compensate-example`
is called by coordinator to compensate for cancelled LRA transaction.

[source,java]
.Example of simple LRA participant
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_13, indent=0]
----
<1> This JAX-RS PUT method will start new LRA transactions and join it before method body gets executed
<2> LRA ID assigned by coordinator to this LRA transaction
<3> When method execution finishes exceptionally, cancel signal for this particular LRA is sent to coordinator
<4> When method execution finishes successfully, complete signal for this particular LRA is sent to coordinator
<5> Method which will be called by coordinator when LRA is completed
<6> Method which will be called by coordinator when LRA is canceled

== Testing
Testing of JAX-RS resources with LRA can be challenging as LRA participant running in parallel with the test is needed.

Helidon provides test coordinator which can be started automatically with additional socket on a random port within your
own Helidon application. You only need one extra test dependency to enable test coordinator in your xref:testing/testing.adoc[@HelidonTest].

[source, xml]
.Dependency
----
<dependency>
    <groupId>io.helidon.microprofile.lra</groupId>
    <artifactId>helidon-microprofile-lra-testing</artifactId>
    <scope>test</scope>
</dependency>
----

Considering that you have LRA enabled JAX-RS resource you want to test.

[source, java]
.Example JAX-RS resource with LRA.
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_14, indent=0]
----

Helidon test with enabled CDI discovery can look like this.

[source, java]
.HelidonTest with LRA test support.
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_15, indent=0]
----
<1> Resource is discovered automatically
<2> Test coordinator needs to be added manually
<3> Injecting test coordinator to access state of LRA managed by coordinator mid-test
<4> Retrieving LRA managed by coordinator by LraId
<5> Asserting LRA state in coordinator

LRA testing feature has the following default configuration:

* port: `0` - coordinator is started on random port(Helidon LRA participant is capable to discover test coordinator automatically)
* bind-address: `localhost` - bind address of the coordinator
* helidon.lra.coordinator.persistence: `false` - LRAs managed by test coordinator are not persisted
* helidon.lra.participant.use-build-time-index: `false` - Participant annotation inspection ignores Jandex index files created in build time, it helps to avoid issues with additional test resources

Testing LRA coordinator is started on additional named socket `test-lra-coordinator` configured with default index `500`.
Default index can be changed with system property `helidon.lra.coordinator.test-socket.index`.

Example: `-Dhelidon.lra.coordinator.test-socket.index=20`.

[source, java]
.HelidonTest override LRA test feature default settings.
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_16, indent=0]
----
<1> Start test LRA coordinator always on the same port 8070(default is random port)
<2> Test LRA coordinator socket bind address (default is localhost)
<3> Persist LRA managed by coordinator(default is false)
<4> Use build time Jandex index(default is false)

When CDI bean auto-discovery is not desired, LRA and Config CDI extensions needs to be added manually.

[source, java]
.HelidonTest setup with disabled discovery.
----
include::{sourcedir}/mp/LraSnippets.java[tag=snippet_17, indent=0]
----

== Additional Information

=== Coordinator
Coordinator is a service that tracks all LRA transactions and calls the compensate REST endpoints of
the participants when the LRA transaction gets cancelled or completes (in case it gets closed).
In addition, participant also keeps track of timeouts, retries participant calls, and assigns LRA ids.

.Helidon LRA supports following coordinators
* {microtx-link}[MicroTx LRA coordinator]
* Helidon LRA coordinator
* https://narayana.io/lra[Narayana coordinator].

=== MicroTx LRA Coordinator
Oracle Transaction Manager for Microservices - {microtx-link}[MicroTx] is an enterprise grade transaction manager for microservices,
among other it manages LRA transactions and is compatible with Narayana LRA clients.

MicroTx LRA coordinator is compatible with Narayana clients when `narayanaLraCompatibilityMode` is on,
you need to add another dependency to enable Narayana client:
[source,xml]
.Dependency needed for using Helidon LRA with Narayana compatible coordinator
----
<dependency>
    <groupId>io.helidon.lra</groupId>
    <artifactId>helidon-lra-coordinator-narayana-client</artifactId>
</dependency>
----

[source, bash]
.Run MicroTx in Docker
----
docker container run --name otmm -v "$(pwd)":/app/config \
-w /app/config -p 8080:8080/tcp --env CONFIG_FILE=tcs.yaml \
--add-host host.docker.internal:host-gateway -d tmm:<version>
----

To use MicroTx with Helidon LRA participant, `narayanaLraCompatibilityMode` needs to be enabled.

[source, yaml]
.Configure MicroTx for development
----
tmmAppName: tcs
tmmConfiguration:
  listenAddr: 0.0.0.0:8080
  internalAddr: http://host.docker.internal:8080
  externalUrl: http://lra-coordinator.acme.com:8080
  xaCoordinator:
    enabled: false
  lraCoordinator:
    enabled: true
  tccCoordinator:
    enabled: false
  storage:
    type: memory
  authentication:
    enabled: false
  authorization:
    enabled: false
  serveTLS:
    enabled: false
  narayanaLraCompatibilityMode:
    enabled: true #<1>
----
<1> Enable Narayana compatibility mode

=== Helidon LRA Coordinator

CAUTION: Test tool, usage in production is not advised.

[source,bash]
.Build and run Helidon LRA coordinator
----
docker build -t helidon/lra-coordinator https://github.com/oracle/helidon.git#:lra/coordinator/server
docker run --name lra-coordinator --network="host" helidon/lra-coordinator
----

Helidon LRA coordinator is compatible with Narayana clients, you need to add a dependency for Narayana client:
[source,xml]
.Dependency needed for using Helidon LRA with Narayana compatible coordinator
----
<dependency>
    <groupId>io.helidon.lra</groupId>
    <artifactId>helidon-lra-coordinator-narayana-client</artifactId>
</dependency>
----

=== Narayana
https://narayana.io[Narayana] is a transaction manager supporting LRA.
To use Narayana LRA coordinator with Helidon LRA client you need to add a dependency for Narayana client:

[source,xml]
.Dependency needed for using Helidon LRA with Narayana coordinator
----
<dependency>
    <groupId>io.helidon.lra</groupId>
    <artifactId>helidon-lra-coordinator-narayana-client</artifactId>
</dependency>
----

The simplest way to run Narayana LRA coordinator locally:

[source,bash]
.Downloading and running Narayana LRA coordinator
----
curl https://repo1.maven.org/maven2/org/jboss/narayana/rts/lra-coordinator-quarkus/5.11.1.Final/lra-coordinator-quarkus-5.11.1.Final-runner.jar \
-o narayana-coordinator.jar
java -Dquarkus.http.port=8070 -jar narayana-coordinator.jar
----

Narayana LRA coordinator is running by default under `lra-coordinator` context,
with port `8070` defined in the snippet above you need to configure your Helidon LRA app as follows:
`mp.lra.coordinator.url=http://localhost:8070/lra-coordinator`


== Reference

* https://github.com/eclipse/microprofile-lra[MicroProfile LRA GitHub Repository]
* {microprofile-lra-spec-url}[{spec-name}]
* https://download.eclipse.org/microprofile/microprofile-lra-{spec-version}/apidocs/org/eclipse/microprofile/lra/[Microprofile LRA JavaDoc]
* https://helidon.io/docs/v4/apidocs/io.helidon.lra.coordinator.client/module-summary.html[Helidon LRA Client JavaDoc]
* {microtx-link}[MicroTx - Oracle Transaction Manager for Microservices]
