///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Scheduling
:description: Scheduling in Helidon MP
:keywords: helidon, mp, scheduling
:feature-name: Scheduling
:rootdir: {docdir}/..

include::{rootdir}/includes/mp.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
- <<Configuration, Configuration>>
- <<Examples, Examples>>
- <<Reference, Reference>>

== Overview

Scheduling is an essential feature for the Enterprise. Helidon has its own implementation of Scheduling functionality
based on https://github.com/jmrozanec/cron-utils[Cron-utils].

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.scheduling</groupId>
    <artifactId>helidon-microprofile-scheduling</artifactId>
</dependency>
----

== Usage

For scheduling tasks in Helidon you can choose from `@Scheduling.Cron` or `@Scheduling.FixedRate` annotations by required
complexity of invocation interval. All you need is to define a method with one of the annotations in an application scoped bean.

=== Fixed rate

For simple fixed rate invocation interval, the `@Scheduling.FixedRate` is the easiest way to schedule task invocation.

[source,java]
----
include::{sourcedir}/mp/SchedulingSnippets.java[tag=snippet_1, indent=0]
----

Metadata like human-readable interval description or configured values are available through
_FixedRateInvocation_ injected as method parameter.

=== Cron expression

For more complicated interval definition, cron expression can be leveraged with `@Scheduling.Cron` annotation.

[source,java]
----
include::{sourcedir}/mp/SchedulingSnippets.java[tag=snippet_3, indent=0]
----

include::{rootdir}/includes/cron.adoc[lines=19..]

Metadata like human-readable interval description or configured values are available through _CronInvocation_ injected
 as method parameter.

[source,java]
----
include::{sourcedir}/mp/SchedulingSnippets.java[tag=snippet_4, indent=0]
----

== Configuration

`Scheduling` annotation properties can be overridden using `application.yaml` properties, if configured in the source code.

The following annotation options can use configuration "expression":

- `Scheduling.Fixed#delayBy()`
- `Scheduling.FixedRate#value()`
- `Scheduling.Cron#value()`


Configuration expressions is a reference to a configuration key, with optional default value:

`${config.key:default-value}`

=== Fixed Rate
The Fixed rate annotation can have the delay by and value overridden using config.

.Annotation that allows config overrides
[source,java]
----
include::{sourcedir}/mp/SchedulingSnippets.java[tag=snippet_2, indent=0]
----

The default values are 5 minutes for delay-by, and 10 minutes for interval, and could be overridden:

[source,yaml]
.Overriding annotated values from config
----
app:
  schedule:
    cache:
      delay-by: "PT10M"
      interval: "PT1H"
----

The configured values would be a 10-minute delay, with 1-hour interval.

=== Cron
The Cron annotation can have the value overridden using config.

.Annotation that allows config overrides
[source,java]
----
include::{sourcedir}/mp/SchedulingSnippets.java[tag=snippet_9, indent=0]
----

The default value is an expression of `0 15 8 ? * *`.

[source,yaml]
.Overriding annotated values from config
----
app:
  schedule:
    cache:
      cron: "* * * * * ? "
----

The configured values would be executing every 1 second.

== Examples

=== Fixed rate

[source,java]
.Example of scheduling with fixed rate
----
include::{sourcedir}/mp/SchedulingSnippets.java[tag=snippet_5, indent=0]
----

=== FixedRate Metadata Injection

[source,java]
.Example with invocation metadata
----
include::{sourcedir}/mp/SchedulingSnippets.java[tag=snippet_6, indent=0]
----

=== Cron expression

[source,java]
.Example of scheduling with cron expression
----
include::{sourcedir}/mp/SchedulingSnippets.java[tag=snippet_7, indent=0]
----

=== Scheduled Metadata Injection.

[source,java]
.Example with invocation metadata
----
include::{sourcedir}/mp/SchedulingSnippets.java[tag=snippet_8, indent=0]
----

== Reference

* https://github.com/jmrozanec/cron-utils[Cron-utils GitHub page]
* link:{scheduling-javadoc-base-url}/io/helidon/microprofile/scheduling/package-summary.html[Helidon Scheduling JavaDoc]
