///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Using CORS in Helidon MP Built-in Services
:toc:
:toc-placement: preamble
:h1Prefix: MP
:description: Helidon MP CORS Support in Built-in Services
:keywords: helidon, java, cors, mp, services
:cors-config-table-exclude-methods:
:flavor-uc: MP
:flavor-lc: se
:rootdir: {docdir}/../..

include::{rootdir}/includes/attributes.adoc[]

Several built-in Helidon services -- health, metrics, and OpenAPI -- have integrated CORS support.
You can include these services in your application and control their CORS behavior.

include::{rootdir}/includes/cors/cors-common.adoc[tag=understanding-cors-support-in-services]
include::{rootdir}/includes/cors/cors-common.adoc[tag=builtin-getting-started]
include::{rootdir}/includes/cors/cors-common.adoc[tags=configuring-cors-for-builtin-services;!se-config-example;!se-code-changes-for-builtin-services-config]

The following example restricts sharing of

* the `/health` resource, provided by the health built-in service, to only the origin `\http://there.com`, and
* the `/metrics` resource, provided by the metrics built-in service, to only the origin `\http://foo.com`.

[source,hocon]
----
...
health:
  cors:
    allow-origins: [http://there.com]
metrics:
  cors:
    allow-origins: [http://foo.com]
...
----

include::{rootdir}/includes/cors/cors-common.adoc[tag=accessing-shared-resources-intro]
[source,bash]
----
mvn package
java -jar target/helidon-quickstart-mp.jar
...
2020.05.12 05:44:08 INFO io.helidon.microprofile.server.ServerCdiExtension Thread[main,5,main]: Server started on http://localhost:8080 (and all other host addresses) in 5280 milliseconds (since JVM startup).
...
----

include::{rootdir}/includes/cors/cors-common.adoc[tag=accessing-shared-resources-main]
