/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.codegen.test.codegen.use;

import org.junit.jupiter.api.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class EnumTest {
    @Test
    public void testEnum() {
        /*
        The following enum constants and methods are generated by `TestCodegenExtension`
        Do not change the assertions unless the code generator is changed as well
         */
        assertThat(TriggerType__Enum.FIRST
                           .someBoolean(), is(true));
        assertThat(TriggerType__Enum.second
                           .someBoolean(), is(false));
        assertThat(TriggerType__Enum.FIRST.constant(),
                   is("Hello World!"));
    }
}
