///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:toc:
:toc-placement: preamble
= Adding Security
:description: Helidon MicroProfile security
:keywords: helidon, microprofile, micro-profile
:feature-name: Security
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
- <<Protecting Helidon Endpoints, Protecting Helidon Endpoints>>
- <<Configuring Endpoint Protection, Configuring Endpoint Protection>>

== Overview
To add security, such as protecting
resource methods with authentication, to a MicroProfile application, add the Helidon
 security integration dependency to your project.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
  <groupId>io.helidon.microprofile</groupId>
  <artifactId>helidon-microprofile-security</artifactId>
</dependency>
----

== Usage

For JAX-RS resources, declare security by adding annotations to a resource class or
 method.

[source,java]
.Protected resource method
----
@GET
@io.helidon.security.annotations.Authenticated
@io.helidon.security.annotations.Authorized
// you can also use io.helidon.security.abac.role.RoleValidator.Roles
@RolesAllowed("admin")
public String adminResource(@Context io.helidon.security.SecurityContext securityContext) {
  return "you are " + securityContext.userName();
}
----

Security in Helidon MicroProfile is built on top of Jersey's and can be enabled/disabled
using the `security.jersey.enabled=[true|false]`property.

include::{rootdir}/includes/security/helidon-endpoints.adoc[]