///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= gRPC Server
:description: Helidon gRPC Server
:keywords: helidon, grpc, java, se
:feature-name: gRPC Server
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
** <<gRPC Server Routing, gRPC Server Routing>>
** <<Service Implementation, Service Implementation>>
** <<Server Interceptors, Server Interceptors>>
** <<Metrics, Metrics>>
- <<Configuration, Configuration>>
** <<Configuring the gRPC Server, Configuring the gRPC Server>>
** <<Configuring the gRPC Reflection Service, Configuring the gRPC Reflection Service>>
- <<Examples, Examples>>

== Overview

The Helidon gRPC server provides a framework for creating link:http://grpc.io/[gRPC] applications.
While it allows you to deploy any standard gRPC service that
implements `io.grpc.BindableService` interface, including services generated
from the Protobuf IDL files (and even allows you to customize them to a certain
extent), using Helidon gRPC framework to implement your services has a number of
benefits:

* It allows you to define both HTTP and gRPC services using a similar programming
model, simplifying the learning curve for developers

* It provides a number of helper methods that make service implementation
significantly simpler

* It allows you to run gRPC and HTTP endpoints on the same WebServer, and even on the same port.


include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver-grpc</artifactId>
</dependency>
----

== Usage
=== gRPC Server Routing
- <<Customizing Service Definitions, Customizing Service Definitions>>

Unlike the HTTP server, which allows you to route requests based on path expression
and an HTTP verb, the gRPC server always routes requests based on the service and
method names. This makes routing configuration somewhat simpler -- all you need
to do is register your services:

[source,java]
----
include::{sourcedir}/se/grpc/ServerSnippets.java[tag=snippet_1, indent=0]
----

<1> Register `GreetFeature` instance.
<2> Register `EchoService` instance.
<3> Register `MathService` instance.
<4> Register a custom unary gRPC route

Both "standard" gRPC services that implement `io.grpc.BindableService` interface
(typically implemented by extending generated server-side stubs and overriding
their methods), and Helidon gRPC services that implement
`io.helidon.grpc.server.GrpcService` interface can be registered.
The difference is that Helidon gRPC services allow you to customize behavior
down to the method level, and provide a number of useful helper methods that
make service implementation easier, as we'll see in a moment.

==== Customizing Service Definitions

When registering a service, regardless of its type, you can customize its
descriptor by providing an instance of `ServerServiceDefinition` as an
argument to the `service` method.

=== Service Implementation

==== Implementing Protobuf Services

In order to implement Protobuf-based service, you would follow the official
link:https://grpc.io/docs/quickstart/java.html[instructions] on the gRPC
website, which boil down to the following:

===== Define the Service IDL

For this example, we will re-implement the `EchoService` above as a Protobuf
service in `echo.proto` file.

[source, proto]
----
syntax = "proto3";
option java_package = "org.example.services.echo";

service EchoService {
  rpc Echo (EchoRequest) returns (EchoResponse) {}
}

message EchoRequest {
  string message = 1;
}

message EchoResponse {
  string message = 1;
}
----

Based on this IDL, the gRPC compiler will generate message classes (`EchoRequest`
and `EchoResponse`), client stubs that can be used to make RPC calls to the server,
as well as the base class for the server-side service implementation.

We can ignore the last one, and implement the service using Helidon gRPC framework
instead.

===== Implement the Service

The service implementation will be very similar to our original implementation:

[source,java]
----
include::{sourcedir}/se/grpc/ServerSnippets.java[tag=snippet_2, indent=0]
----

<1> Specify the proto descriptor in order to provide the necessary type information and
enable Protobuf marshalling.
<2> Define the unary method `Echo` and map it to the `this::echo` handler.
<3> Create a handler for the `Echo` method, using Protobuf message types for request and response.
<4> Extract the message string from the request.
<5> Create the response containing the extracted message.
<6> Send the response back to the client by completing the response observer.

NOTE: The `complete` method shown in the example above is just one of many helper
methods available in the `ResponseHelper` class. See the full list
link:{grpc-server-javadoc-base-url}/io/helidon/webserver/grpc/ResponseHelper.html[here].

=== Server Interceptors

gRPC supports the notion of _server interceptors_ which are useful to implement
common tasks (cross-cutting concerns) on any subset of methods and services.
Interceptors implement the `io.grpc.ServerInterceptor` interface which defines
a single `interceptCall` method. Server interceptors are arranged in a _chain_ that
wraps the actual gRPC method invocation and that can be ordered by weight.

Server interceptors are registered while creating routes, and will intercept any
gRPC method calls that follow: that is, registration ordering is important to
make sure interceptor chains are properly constructed to accomplish a
certain task. For example, consider the following routing definition:

[source,java]
----
include::{sourcedir}/se/grpc/ServerSnippets.java[tag=snippet_4, indent=0]
----

This routing includes two server interceptor instances of types `Interceptor1` and
`Interceptor2`. As stated above, the order in which these interceptors are
registered is important. In this example, `Interceptor1` will be called for
any method in `EchoService` and `MathService`, but not for `GreetService`.
Similarly, `Interceptor2` will be called only for methods in `MathService`.
The default weight of a server interceptor is `InterceptorWeights.USER`;
it follows that for `MathService`, `Interceptor2` will be called _before_
`Interceptor1` given its _higher_ weight of `Interceptor.USER + 100`.

NOTE: Even though the gRPC API supports interception of methods via
alternative mechanisms, it is recommended to use the `intercept` method
on a `GrpcRouting` builder, as shown above, to ensure correct ordering
based on weights.

=== Metrics

Helidon supports a few metrics that are specific to gRPC and are based
on those defined in https://grpc.io/docs/guides/opentelemetry-metrics/[gRPC OpenTelemetry Metrics].
Metrics are disabled by default, but can be easily enabled via configuration
as we shall discuss shortly.

Here is the list of gRPC server metrics available in Helidon:

|===
|Metric |Type |Labels| Description

|grpc.server.call.started
|Counter
|grpc.method
|The total number of calls started, including not completed ones,
for a certain method.

|grpc.server.call.duration
|Timer
|grpc.method, grpc.status
|Timer that tracks call durations for a certain method.

|grpc.server.call.sent_total_compressed_message_size
|Distribution Summary
|grpc.method, grpc.status
|Summary of message sizes sent to clients for a certain method.

|grpc.server.call.rcvd_total_compressed_message_size
|Distribution Summary
|grpc.method, grpc.status
|Summary of message sizes received from clients for a certain method.
|===

At the time of writing, Helidon only tracks successful method calls, so the value of the
`grpc.status` label must always be set to the string "OK". Support for metrics of unsuccessful calls
may be supported in the future, hence the need to include the label at this time.

As stated above, gRPC metrics are disabled by default but can be enabled
by configuring the gRPC protocol in the Webserver. This can be accomplished
either programmatically or directly in your server config file as follows:

[source,yaml]
----
server:
  port: 8080
  host: 0.0.0.0
  protocols:
    grpc:
      enable-metrics: true
----

The configuration above shall enable metrics on the Webserver's default port 8080. For
more information see xref:{rootdir}/se/metrics/metrics.adoc[Helidon Metrics].

== Configuration
Configure the gRPC server using the Helidon configuration framework, either programmatically
or via a configuration file.

=== Configuring the gRPC Server

Currently, we do not have any custom configuration options for the gRPC protocol.

To register a routing with Helidon WebServer, simply add the routing to the listener
(WebServer configuration is itself the default listener configuration)

[source,java]
----
include::{sourcedir}/se/grpc/ServerSnippets.java[tag=snippet_3, indent=0]
----

<1> Configure HTTP routing of the server
<2> Configure gRPC routing of the server

=== Configuring the gRPC Reflection Service

When a gRPC client interacts with a server, it needs to have access to the
proto file in order to learn about the available services, methods and
message types in use. For many applications this information is simply
_common knowledge_ between the two parties. However, in some cases, especially
while developing a new service, it is convenient to use tools such as `grpcurl`
to test the service. One way to do that is to specify the proto file as
an argument as follows:

[source,bash]
----
>> grpcurl -proto strings.proto -d '{ "text": "hello world" }' localhost:8080 StringService.Split
----

The parameter `-proto` is used by `grpcurl` to learn about the methods and
messages types available in the proto file, and ultimately execute the
requested gRPC call.

Helidon includes a gRPC reflection service that can be queried by tools
such as `grpcurl` to learn about the available services &mdash;similar to
OpenAPI for REST services. The reflection service is implemented as a
_feature_ and can be enabled programmatically when adding the feature, or
via config as follows:

[source,yaml]
----
  features:
    grpc-reflection:
      enabled: true
----

The feature accepts a list of sockets, or if omitted as seen above,
it would enable the feature on all sockets.
For security reasons, the gRPC reflection service is
_disabled by default_; if enabled, it is recommended to disable
the feature for production to avoid any unwanted requests. For more information about
gRPC reflection, see https://grpc.io/docs/guides/reflection/[gRPC Reflection].

== Examples

The following gRPC examples for Helidon SE are available:

* link:{helidon-github-examples-url}/webserver/protocols[Multiple protocols on a single WebServer]
