///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:toc:
:toc-placement: preamble
:description: Scheduling in Helidon SE
:keywords: helidon, se, scheduling
:h1Prefix: SE
:feature-name: Scheduling
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source,xml]
----
<dependency>
    <groupId>io.helidon.scheduling</groupId>
    <artifactId>helidon-scheduling</artifactId>
</dependency>
----

== Scheduling
For scheduling periodic tasks it is possible to choose fixed rate setup or Cron expression.

=== Fixed rate
For simple fixed rate invocation use .

[source,java]
.Example of scheduling with fixed rate use `Scheduling.fixedRateBuilder()` builder.
----
Scheduling.fixedRateBuilder()
        .delay(10)
        .initialDelay(5)
        .timeUnit(TimeUnit.MINUTES)
        .task(inv -> System.out.println("Every 10 minutes, first invocation 5 minutes after start"))
        .build();
----

Metadata like human-readable interval description or configured values are available through
FixedRateInvocation provided as task parameter.

[source,java]
.Example with ivocation metadata
----
Scheduling.fixedRateBuilder()
        .delay(10)
        .task(inv -> System.out.println("Method invoked " + inv.description()))
        .build();
----

=== Cron expression

For more complicated interval definition, cron expression can be leveraged with
`Scheduling.cronBuilder()` builder.

[source,java]
.Example of scheduling with cron expression
----
Scheduling.cronBuilder()
    .expression("0 15 8 ? * *")
    .task(inv -> System.out.println("Executer every day at 8:15"))
    .build();
----

include::../../shared/scheduling/01_cron.adoc[lines=19..]

Metadata like human-readable interval description or configured values are available through
CronInvocation provided as task parameter.

[source,java]
.Example with ivocation metadata
----
Scheduling.cronBuilder()
    .expression("0 15 8 ? * *")
    .task(inv -> System.out.println("Method invoked " + inv.description()))
    .build();
----