///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= JMS Connector
:description: Reactive Messaging support for JMS in Helidon MP
:keywords: helidon, mp, messaging, jms
:feature-name: JMS Connector
:microprofile-bundle: false
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Configuration, Configuration>>
- <<Usage, Usage>>


== Overview

Connecting streams to JMS with Reactive Messaging couldn't be easier.


include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.messaging.jms</groupId>
    <artifactId>helidon-messaging-jms</artifactId>
</dependency>
----

== Configuration

Connector name: `helidon-jms`

include::{rootdir}/config/io_helidon_messaging_connectors_jms_JmsConfigBuilder.adoc[tag=config,leveloffset=+1]

TIP: Besides the configuration options above, custom attributes can be passed over configuration.

.Custom Attributes Examples
|===
|`jndi.destination` | JNDI destination identifier.
|`jndi.env-properties` | Environment properties used for creating initial context `java.naming.factory.initial`, `java.naming.provider.url` ...
|`producer.someproperty` | property with producer prefix is set to producer instance (for example WLS Unit-of-Order `WLMessageProducer.setUnitOfOrder("unit-1")` can be configured as `producer.unit-of-order=unit-1`)
|===

=== Configured JMS factory

The simplest possible usage is looking up JMS ConnectionFactory in the naming context.

[source,yaml]
.Example of connector config:
----
mp.messaging:

  incoming.from-jms:
    connector: helidon-jms
    destination: messaging-test-queue-1
    type: queue

  outgoing.to-jms:
    connector: helidon-jms
    destination: messaging-test-queue-1
    type: queue

  connector:
    helidon-jms:
      user: Gandalf
      password: mellon
      jndi:
        jms-factory: ConnectionFactory
        env-properties:
          java.naming:
            factory.initial: org.apache.activemq.jndi.ActiveMQInitialContextFactory
            provider.url: tcp://localhost:61616
----

=== Injected JMS factory

In case you need more advanced setup, connector can work with injected factory instance.

[source,java]
.Inject:
----
include::{sourcedir}/mp/reactivemessaging/JmsSnippets.java[tag=snippet_1, indent=0]
----

[source,yaml]
.Config:
----
jms:
  url: tcp://127.0.0.1:61616

mp:
  messaging:
    connector:
      helidon-jms:
        named-factory: active-mq-factory

    outgoing.to-jms:
      connector: helidon-jms
      session-group-id: order-connection-1
      destination: TESTQUEUE
      type: queue

    incoming.from-jms:
      connector: helidon-jms
      session-group-id: order-connection-1
      destination: TESTQUEUE
      type: queue
----

== Usage

=== Consuming

[source,java]
.Consuming one by one unwrapped value:
----
include::{sourcedir}/mp/reactivemessaging/JmsSnippets.java[tag=snippet_2, indent=0]
----

[source,java]
.Consuming one by one, manual ack:
----
include::{sourcedir}/mp/reactivemessaging/JmsSnippets.java[tag=snippet_3, indent=0]
----

=== Producing

[source,java]
.Example of producing to JMS:
----
include::{sourcedir}/mp/reactivemessaging/JmsSnippets.java[tag=snippet_4, indent=0]
----

[source,java]
.Example of more advanced producing to JMS:
----
include::{sourcedir}/mp/reactivemessaging/JmsSnippets.java[tag=snippet_5, indent=0]
----
[source,java]
.Example of even more advanced producing to JMS with custom mapper:
----
include::{sourcedir}/mp/reactivemessaging/JmsSnippets.java[tag=snippet_6, indent=0]
----
