///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= GraphQL Server Introduction
:h1Prefix: SE
:pagename: graphql-server-introduction
:description: Helidon GraphQL Server Introduction
:keywords: helidon, graphql, java
:feature-name: GraphQL
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc

Helidon GraphQL Server provides a framework for creating link:https://github.com/graphql-java/graphql-java[GraphQL] applications.

== Experimental

WARNING: The Helidon GraphQL feature is currently experimental and the APIs are
 subject to changes until GraphQL support is stabilized.

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source,xml]
----
<dependency>
    <groupId>io.helidon.graphql</groupId>
    <artifactId>helidon-graphql-server</artifactId>
</dependency>
----

== Quick Start

Here is the code for a minimalist GraphQL application that exposes 2 queries.

[source,java]
----
    public static void main(String[] args) {
        WebServer server = WebServer.builder()
                .routing(Routing.builder()
                                 .register(GraphQlSupport.create(buildSchema()))  <1>
                                 .build())
                .build();

        server.start()  <2>
               .thenApply(webServer -> {
                   String endpoint = "http://localhost:" + webServer.port();
                   System.out.println("GraphQL started on " + endpoint + "/graphql");
                   System.out.println("GraphQL schema availanle on " + endpoint + "/graphql/schema.graphql");
                   return null;
               });
    }

    private static GraphQLSchema buildSchema() {
        String schema = "type Query{\n"    <3>
                + "hello: String \n"
                + "helloInDifferentLanguages: [String] \n"
                + "\n}";

        SchemaParser schemaParser = new SchemaParser();
        TypeDefinitionRegistry typeDefinitionRegistry = schemaParser.parse(schema);

        // DataFetcher to return various hello's in difference languages  <4>
        DataFetcher<List<String>> hellosDataFetcher = (DataFetcher<List<String>>) environment ->
                List.of("Bonjour", "Hola", "Zdravstvuyte", "Nǐn hǎo", "Salve", "Gudday", "Konnichiwa", "Guten Tag");

        RuntimeWiring runtimeWiring = RuntimeWiring.newRuntimeWiring()  <5>
                .type("Query", builder -> builder.dataFetcher("hello", new StaticDataFetcher("world")))
                .type("Query", builder -> builder.dataFetcher("helloInDifferentLanguages", hellosDataFetcher))
                .build();

        SchemaGenerator schemaGenerator = new SchemaGenerator();
        return schemaGenerator.makeExecutableSchema(typeDefinitionRegistry, runtimeWiring);  <6>
    }
----

<1> Register GraphQL support.
<2> Start the server.
<3> Define the GraphQL schema.
<4> Create a DataFetcher to return a List of Hellos in different languages.
<5> Wire up the DataFetchers.
<6> Generate the GraphQL schema.

The example above deploys a very simple service exposing the `/graphql` endpoint.

You can then probe the endpoints:

1. Hello word endpoint
+
[source,bash]
----
curl -X POST http://127.0.0.1:PORT/graphql -d '{"query":"query { hello }"}'

"data":{"hello":"world"}}
----

2. Hello in different languages
+
[source,bash]
----
curl -X POST http://127.0.0.1:PORT/graphql -d '{"query":"query { helloInDifferentLanguages }"}'

{"data":{"helloInDifferentLanguages":["Bonjour","Hola","Zdravstvuyte","Nǐn hǎo","Salve","Gudday","Konnichiwa","Guten Tag"]}}
----

