///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Extensions Overview
:h1Prefix: MP
:description: Helidon extensions
:keywords: helidon, java, microservices, microprofile, extensions
:cdi-extension-api-url: https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#spi

== CDI extensions

Helidon provides link:{cdi-extension-api-url}[CDI portable extensions] that you
 can use to inject the following objects into your Helidon MicroProfile
 applications:

[PILLARS]
====

[CARD]
.HikariCP data sources
[link=extensions/02_cdi_datasource-hikaricp.adoc]
--
Create and inject a HikariCP data source in your application code.
--

[CARD]
.Oracle UCP data sources
[link=extensions/02_cdi_datasource-ucp.adoc]
--
Create and inject an Oracle Universal Connection Pool data source in
your application code.
--

[CARD]
.Jedis clients
[link=extensions/03_cdi_jedis.adoc]
--
Create and inject a Jedis pool in your application code.
--

[CARD]
.OCI Object Storage clients
[link=extensions/04_cdi_oci-objectstorage.adoc]
--
Create and inject an Oracle Cloud Infrastructure Object Storage client in your
 application code.
--

[CARD]
.Java Transaction API objects
[link=extensions/05_cdi_jta.adoc]
--
Use the Java Transaction API in your application code.
--
====
