///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= CDI extension for Oracle UCP
:h1Prefix: MP
:description: Helidon CDI extension for Oracle Universal Connection Pool
:keywords: helidon, java, microservices, microprofile, extensions, cdi, ucp
:hikaricp-props-url: https://github.com/brettwooldridge/HikariCP/blob/dev/README.md#configuration-knobs-baby
:feature-name: Oracle UCP Support
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc

This https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#spi[CDI portable extension] provides
support for injecting
https://docs.oracle.com/en/database/oracle/oracle-database/19/jjucp/index.html[Oracle
Universal Connection Pool data sources] in your Helidon MicroProfile
applications.

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source,xml]
----
<dependency>
    <groupId>io.helidon.integrations.cdi</groupId>
    <artifactId>helidon-integrations-cdi-datasource-ucp</artifactId>
</dependency>
----

== Injecting an Oracle Universal Connection Pool data source

The following examples show how to create a `DataSource` named `orders` in your
application.

[source,java]
.Field-injection example
----
 @Inject
 @Named("orders")
 private DataSource ordersDataSource;
----

[source,java]
.Constructor-injection example
----
 private final DataSource ds;
 @Inject
 public YourConstructor(@Named("orders") DataSource ds) {
   super();
   this.ds = ds;
 }
----

The extension implements this injection point by creating a
https://docs.oracle.com/en/database/oracle/oracle-database/19/jjuar/oracle/ucp/jdbc/PoolDataSource.html[`PoolDataSource`]
object in the
http://docs.jboss.org/cdi/api/2.0/javax/enterprise/context/ApplicationScoped.html[application
scope].

You can configure the object using
<<microprofile/02_server-configuration.adoc, MicroProfile
config>>. For example, the data source created above can be configured
as follows:

[source, properties]
.META-INF/microprofile-config.properties
----
javax.sql.DataSource.orders.connectionFactoryClassName = oracle.jdbc.pool.OracleDataSource
javax.sql.DataSource.orders.URL = jdbc:oracle:thin:@localhost:1521:ORCL
javax.sql.DataSource.orders.user = sys as sysoper
javax.sql.DataSource.orders.password = Oracle
----

Property names that start with `javax.sql.DataSource.dataSourceName.`
are parsed, and the remaining portion of each name is treated as a
https://docs.oracle.com/javase/tutorial/javabeans/writing/properties.html[Java
Bean property] of the
https://docs.oracle.com/en/database/oracle/oracle-database/19/jjuar/oracle/ucp/jdbc/PoolDataSource.html[`oracle.ucp.jdbc.PoolDataSource`]
class.
