///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= CDI extension for OCI
:description: Helidon CDI extension for Oracle Cloud Infrastructure Object Storage
:keywords: helidon, java, microservices, microprofile, extensions, cdi, oci, object storage
:feature-name: OCI Object Storage Support
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

This link:{jakarta-cdi-spec-url}#spi[CDI portable extension] provides support for injecting an
 link:{oci-objstore-url}[Oracle Cloud Infrastructure Object Storage client] in your Helidon MicroProfile applications.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
     <groupId>io.helidon.integrations.oci.sdk</groupId>
     <artifactId>helidon-integrations-oci-sdk-cdi</artifactId>
</dependency>
----

== Using The Helidon OCI SDK Extension

Please see xref:../oci/oci.adoc[Helidon's OCI Integration] for information on how to use Helidon's OCI SDK Extension.
