///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= CDI extension for HikariCP
:description: Helidon CDI extension for HikariCP
:keywords: helidon, java, microservices, microprofile, extensions, cdi, hikaricp
:feature-name: HikariCP Support
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

This link:{jakarta-cdi-spec-url}#spi[CDI portable extension] provides support for
injecting link:http://brettwooldridge.github.io/HikariCP[HikariCP data sources] in your Helidon
MicroProfile applications.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.integrations.cdi</groupId>
    <artifactId>helidon-integrations-cdi-datasource-hikaricp</artifactId>
</dependency>
----

== Injecting a HikariCP data source

The following examples show how to create a `DataSource` named `orders` in your
application.

[source,java]
.Field-injection example
----
 @Inject
 @Named("orders")
 private DataSource ordersDataSource;
----

[source,java]
.Constructor-injection example
----
 private final DataSource ds;
 @Inject
 public YourConstructor(@Named("orders") DataSource ds) {
   super();
   this.ds = ds;
 }
----

The extension implements this injection point by creating a
link:{hikaricp-javadoc-url}/com/zaxxer/hikari/HikariDataSource.html[HikariDataSource] object in the
link:{jakarta-cdi-javadoc-url}/javax/enterprise/context/ApplicationScoped.html[application scope].

You can configure the object using
xref:../jaxrs/server-configuration.adoc[MicroProfile config]. For example,
the data source created above can be configured as follows:

[source, properties]
.META-INF/microprofile-config.properties
----
javax.sql.DataSource.orders.dataSourceClassName=oracle.jdbc.pool.OracleDataSource
javax.sql.DataSource.orders.dataSource.url = jdbc:oracle:thin:@localhost:1521:ORCL
javax.sql.DataSource.orders.dataSource.user = sys as sysoper
javax.sql.DataSource.orders.dataSource.password = Oracle
----

Property names that start with `javax.sql.DataSource.dataSourceName.` are parsed,
and the remaining portion of each name is treated as a
link:{hikaricp-base-url}/README.md#configuration-knobs-baby[Hikari connection pool property].
