///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Extensions Overview
:description: Helidon extensions
:keywords: helidon, java, microservices, microprofile, extensions
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

== CDI Extensions

Helidon provides link:{jakarta-cdi-spec-url}#spi[CDI portable extensions] that you can use to inject the following objects into your Helidon MicroProfile
 applications:

[PILLARS]
====

[CARD]
.Jedis clients
[link=cdi-jedis.adoc]
--
Create and inject a Jedis pool in your application code.
--

====
