///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

// tag::setup[]
ifndef::rootdir[:rootdir: {docdir}/../..]
ifndef::flavor-lc[:flavor-lc: se]
:feature-name: OpenTelemetry Tracing
// end::setup[]

Helidon is integrated with OpenTelemetry and OpenTelemetry tracing.

include::{rootdir}/includes/dependencies.adoc[]

// tag::otel-dependency[]


[source,xml]
.Dependency for OpenTelemetry support
----
<dependency>
<groupId>io.helidon.tracing.providers</groupId>
<artifactId>helidon-tracing-providers-opentelemetry</artifactId>
<scope>runtime</scope>
</dependency>
----
To control OpenTelemetry tracing using Helidon configuration, also add the following dependency.
[source,xml]
.Dependency for configuring OpenTelemetry using Helidon config
----
<dependency>
    <groupId>io.helidon.telemetry</groupId>
    <artifactId>helidon-telemetry-opentelemetry-config</artifactId>
    <scope>runtime</scope>
</dependency>
----
You must also add at least one dependency on an OpenTelemetry exporter so your service sends its span data to a back-end system such as Jaeger or Grafana.

The following example dependency uses the OpenTelemetry `otlp` exporter.

[source,xml]
.Example dependency for an OpenTelemetry exporter
----
<dependency>
    <groupId>io.opentelemetry</groupId>
    <artifactId>opentelemetry-exporter-otlp</artifactId>
    <scope>runtime</scope>
</dependency>
----

// end::otel-dependency[]

// tag::otel-configuration[]

== Configuring OpenTelemetry Tracing
Because OpenTelemetry comprises several signals, of which tracing is only one, you configure OpenTelemetry tracing differently from other implementations of tracing.

For complete information on configuring OpenTelemetry using Helidon {flavor-uc}, see xref:{rootdir}/{flavor-lc}/open-telemetry.adoc[the Helidon {flavor-uc} OpenTelemetry documentation].

The following example shows only some of the settings you can use to control OpenTelemetry tracing.

ifdef::se-flavor[]
[source,yaml]
.Example Helidon configuration for OpenTelemetry tracing
----
telemetry:
  service: helidon-otel-tracing-example # <1>
  signals:
    tracing:
      processors:
        - type: simple # <2>
      exporters:
        - type: otlp   # <3>
----
endif::se-flavor[]
ifdef::mp-flavor[]
[source.properties]
.Example Helidon configuration for OpenTelemetry tracing
----
telemetry.service=helidon-otel-tracing-example # <1>
telemetry.signals.tracing.processors.0.type=simple <2>
telemetry.signals.tracing.exporters.0.type=otlp <3>
----
endif::mp-flavor[]
<1> Specifies the OpenTelemetry service name.
<2> Selects the `simple` span processor.
<3> Selects which span exporter to use.

The `simple` processor type sends each span to the backend as soon as it ends, rather than grouping multiple spans into batches, and so is appropriate for testing and demos but not for production deployments.

The `otlp` exporter type matches the exporter dependency example shown above. If you try to configure a particular exporter type without added the corresponding dependency to your project, the server fails during startup.

// end::otel-configuration[]
