///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/../..]
ifndef::flavor-lc[:flavor-lc: se]
:feature-name: Jaeger Tracing

Helidon is integrated with the Jaeger tracer.

The Jaeger builder is loaded through `ServiceLoader` and configured. You could
also use the Jaeger builder directly, though this would create a source-code dependency
on the Jaeger tracer.

We use Jaeger OpenTelemetry Tracing client to
integrate with Jaeger tracer.

include::{rootdir}/includes/dependencies.adoc[]

// tag::jaeger-dependency[]
[source,xml]
----
<dependency>
    <groupId>io.helidon.tracing</groupId>
    <artifactId>helidon-tracing-providers-jaeger</artifactId>
</dependency>
----
// end::jaeger-dependency[]

// tag::jaeger-configuration[]

== Configuring Jaeger

include::{rootdir}/config/io_helidon_tracing_providers_jaeger_JaegerTracerBuilder.adoc[tag=config,levelOffset=1]

The following is an example of a Jaeger configuration, specified in the YAML format.
[source,yaml]
----
tracing:
    service: "helidon-full-http"
    protocol: "https"
    host: "jaeger"
    port: 14240
----

// end::jaeger-configuration[]
