///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= CDI extension for Jedis
:description: Helidon CDI extension for Jedis
:keywords: helidon, java, microservices, microprofile, extensions, cdi, jedis, redis
:cdi-extension-api-url: https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#spi
:cdi-applicationscoped-api-url: http://docs.jboss.org/cdi/api/2.0/javax/enterprise/context/ApplicationScoped.html
:jedis-jedispool-api-url: https://static.javadoc.io/redis.clients/jedis/2.9.0/redis/clients/jedis/JedisPool.html
:jedis-project-url: https://github.com/xetorthio/jedis

This link:{cdi-extension-api-url}[CDI portable extension] provides support for
 injecting link:{jedis-project-url}[Jedis clients] in your Helidon
 MicroProfile applications.

== Prerequisites

Declare the following dependency in your project:

[source,xml]
----
    <dependency>
        <groupId>io.helidon.integrations.cdi</groupId>
        <artifactId>helidon-integrations-cdi-jedis</artifactId>
    </dependency>
----

== Injecting a Jedis client

The following examples show how to create and inject a Jedis pool named `orders`
 in your application code.

[source,java]
.Field-injection example
----
 @Inject
 @Named("orders")
 private JedisPool ordersPool;
----

[source,java]
.Constructor-injection example
----
 private final JedisPool ordersPool;
 @Inject
 public YourConstructor(@Named("orders") JedisPool pool) {
   super();
   this.ordersPool = pool;
 }
----

The extension implements this injection point by creating a
 link:{jedis-jedispool-api-url}[JedisPool] object in the
 link:{cdi-applicationscoped-api-url}[application scope].

You can configure the object using
 <<microprofile/02_server-configuration.adoc, MicroProfile config>>. For example,
 the Jedis pool created above can be configured as follows:

[source, properties]
.META-INF/microprofile-config.properties
----
redis.clients.jedis.JedisPool.orders.port=6379
----

Property names that start with `redis.clients.jedis.JedisPool.dataSourceName.` are
 parsed, and the remaining portion of each name is treated as a Java Bean property
 of `JedisPool`.
