///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Fault Tolerance Introduction
:h1Prefix: MP
:pagename: faulttolerance-introduction
:description: Fault Tolerance Introduction
:keywords: helidon, webserver, faulttolerance, mp
:fault-tolerance-spec-url: https://github.com/eclipse/microprofile-fault-tolerance
:scheduled-executor-config: {javadoc-base-url}io.helidon.common.configurable/io/helidon/common/configurable/ScheduledThreadPoolSupplier.Builder.html#config(io.helidon.config.Config)
:executor-config: {javadoc-base-url}io.helidon.common.configurable/io/helidon/common/configurable/ThreadPoolSupplier.Builder.html#config(io.helidon.config.Config)

Fault Tolerance is part of the MicroProfile set of {fault-tolerance-spec-url}[specifications]. This API defines mostly
annotations that improve application robustness by providing support to conveniently handle
error conditions (faults) that may occur in real-world applications. Examples include
service restarts, network delays, temporal infrastructure instabilities, etc.

== Fault Tolerance in Helidon

The latest implementation of MP Fault Tolerance is built on top of Helidon's SE
Fault Tolerance. Thus, some configuration for Helidon SE Fault
Tolerance also applies to MP. The next section describes some
configuration properties that are of particular interest to MP applications.

=== Configuration

Helidon's implementation uses two types of thread pools: normal and scheduled. The default
core size of these executors is 16; however, that can be configured using an `application.yaml`
file as follows:

[source,yaml]
----
executor:
  core-pool-size: 8

scheduled-executor:
  core-pool-size: 8
----

NOTE: There is currently _no support_ to configure these executor properties via a
`microprofile-config.properties` file.

The complete set of properties available to configure these executors is in
{executor-config}[ServerThreadPoolSupplier] and
{scheduled-executor-config}[ScheduledThreadPoolSupplier].

