///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webclient.http1.Http1ClientProtocolConfig
:keywords: helidon, config, io.helidon.webclient.http1.Http1ClientProtocolConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webclient.http1.Http1ClientProtocolConfig
include::{rootdir}/includes/attributes.adoc[]

= Http1ClientProtocolConfig (webclient.http1) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webclient.http1/io/helidon/webclient/http1/Http1ClientProtocolConfig.html[io.helidon.webclient.http1.Http1ClientProtocolConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`default-keep-alive` |boolean |`true` |Whether to use keep alive by default.

 `true` for keeping connections alive and re-using them for multiple requests (default), `false`
  to create a new connection for each request
|`max-header-size` |int |`16384` |Configure the maximum allowed header size of the response.

  maximum header size
|`max-status-line-length` |int |`256` |Configure the maximum allowed length of the status line from the response.

 Maximum status line length
|`name` |string |`http_1_1` |
|`validate-request-headers` |boolean |`false` |Sets whether the request header format is validated or not.

     Defaults to `false` as user has control on the header creation.
 

 Whether request header validation should be enabled
|`validate-response-headers` |boolean |`true` |Sets whether the response header format is validated or not.

     Defaults to `true`.
 

 Whether response header validation should be enabled

|===

// end::config[]