///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.oci.OciConfig
:keywords: helidon, config, io.helidon.integrations.oci.OciConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.oci.OciConfig
include::{rootdir}/includes/attributes.adoc[]

= OciConfig (integrations.oci) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.oci/io/helidon/integrations/oci/OciConfig.html[io.helidon.integrations.oci.OciConfig]


This is a standalone configuration type, prefix from configuration root: `helidon.oci`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`allowed-atn-strategies` |string[&#93; |{nbsp} |List of attempted authentication strategies in case atnStrategy() is set to STRATEGY_AUTO.

 In case the list is empty, all available strategies will be tried, ordered by their io.helidon.common.Weight

 List of authentication strategies to be tried
 @see #atnStrategy()
|`atn-strategy` |string |`auto` |Authentication strategy to use. If the configured strategy is not available, an exception
 would be thrown for OCI related services.

 Known and supported authentication strategies for public OCI:

- STRATEGY_AUTO - use the list of allowedAtnStrategies() (in the provided order), and choose
     the first one
     capable of providing data
- AtnStrategyConfig.STRATEGY -
     use configuration of the application to obtain values needed to set up connectivity, uses
     com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider
- AtnStrategyConfigFile.STRATEGY - use configuration file of OCI (`home/.oci/config`), uses
     com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider
- AtnStrategyResourcePrincipal.STRATEGY  - use identity of the OCI resource the service is executed on
     (fn), uses
     com.oracle.bmc.auth.ResourcePrincipalAuthenticationDetailsProvider
- AtnStrategyInstancePrincipal.STRATEGY - use identity of the OCI instance the service is running on, uses
     com.oracle.bmc.auth.InstancePrincipalsAuthenticationDetailsProvider

The authentication strategy to apply
|`atn-timeout` |Duration |`PT10S` |Timeout of authentication operations, where applicable.
 This is a timeout for each operation (if there are retries, each timeout will be this duration).
 Defaults to 10 seconds.

 Authentication operation timeout
|`config-file-strategy` |xref:{rootdir}/config/io_helidon_integrations_oci_ConfigFileStrategyConfig.adoc[ConfigFileStrategyConfig] |{nbsp} |Config file strategy configuration (if provided and used).

 Information to customize config for atnStrategy()
|`config-strategy` |xref:{rootdir}/config/io_helidon_integrations_oci_ConfigStrategyConfig.adoc[ConfigStrategyConfig] |{nbsp} |Config strategy configuration (if provided and used).

 Information needed for config atnStrategy()
|`imds-base-uri` |URI |{nbsp} |The OCI IMDS URI (http URL pointing to the metadata service, if customization needed.

 The OCI IMDS URI
|`imds-timeout` |Duration |`PT0.1S` |The OCI IMDS connection timeout. This is used to auto-detect availability.

 This configuration property is used when attempting to connect to the metadata service.

 The OCI IMDS connection timeout
|`region` |Region |{nbsp} |Explicit region. The configured region will be used by region provider.
 This may be ignored by authentication detail providers, as in most cases region is provided by them.

 Explicit region

|===

// end::config[]