///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.observe.log.LogObserver
:keywords: helidon, config, io.helidon.webserver.observe.log.LogObserver
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.observe.log.LogObserver
include::{rootdir}/includes/attributes.adoc[]

= LogObserver (webserver.observe.log) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.observe.log/io/helidon/webserver/observe/log/LogObserver.html[io.helidon.webserver.observe.log.LogObserver]


[source,text]
.Config key
----
log
----


This type provides the following service implementations:

- `io.helidon.webserver.observe.spi.ObserveProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`endpoint` |string |`log` |
|`permit-all` |boolean |{nbsp} |Permit all access, even when not authorized.

Whether to permit access for anybody
|`stream` |xref:{rootdir}/config/io_helidon_webserver_observe_log_LogStreamConfig.adoc[LogStreamConfig] |`@io.helidon.webserver.observe.log.LogStreamConfig@.create()` |Configuration of log stream.

Log stream configuration

|===

// end::config[]