///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.http.RequestedUriDiscoveryContext
:keywords: helidon, config, io.helidon.http.RequestedUriDiscoveryContext
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.http.RequestedUriDiscoveryContext
include::{rootdir}/includes/attributes.adoc[]

= RequestedUriDiscoveryContext (http) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.http/io/helidon/http/RequestedUriDiscoveryContext.html[io.helidon.http.RequestedUriDiscoveryContext]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`enabled` |boolean |`true if &#x27;types&#x27; or &#x27;trusted-proxies&#x27; is set; false otherwise` |Sets whether requested URI discovery is enabled for requestes arriving on the socket.
|`trusted-proxies` |xref:{rootdir}/config/io_helidon_common_configurable_AllowList.adoc[AllowList] |{nbsp} |Sets the trusted proxies for requested URI discovery for requests arriving on the socket.
|`types` |RequestedUriDiscoveryType[&#93; (FORWARDED, X_FORWARDED, HOST) |{nbsp} |Sets the discovery types for requested URI discovery for requests arriving on the socket.

Allowed values:

- `FORWARDED`: The `io.helidon.http.Header#FORWARDED` header is used to discover the original requested URI.
- `X_FORWARDED`: The
`io.helidon.http.Header#X_FORWARDED_PROTO`,
`io.helidon.http.Header#X_FORWARDED_HOST`,
`io.helidon.http.Header#X_FORWARDED_PORT`,
`io.helidon.http.Header#X_FORWARDED_PREFIX`
headers are used to discover the original requested URI.
- `HOST`: This is the default, only the `io.helidon.http.Header#HOST` header is used to discover
requested URI.


|===

// end::config[]