///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.security.providers.common.EvictableCache
:keywords: helidon, config, io.helidon.security.providers.common.EvictableCache
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.security.providers.common.EvictableCache
include::{rootdir}/includes/attributes.adoc[]

= EvictableCache (security.providers.common) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.security.providers.common/io/helidon/security/providers/common/EvictableCache.html[io.helidon.security.providers.common.EvictableCache]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cache-enabled` |boolean |`true` |If the cacheEnabled is set to false, no caching will be done.
 Otherwise (default behavior) evictable caching will be used.
|`cache-evict-delay-millis` |long |`60000` |Delay from the creation of the cache to first eviction
|`cache-evict-period-millis` |long |`300000` |How often to evict records
|`cache-overall-timeout-millis` |long |`3600000` |Configure record timeout since its creation.
|`cache-timeout-millis` |long |`3600000` |Configure record timeout since last access.
|`evictor-class` |Class |{nbsp} |Configure evictor to check if a record is still valid.
 This should be a fast way to check, as it is happening in a ConcurrentHashMap#forEachKey(long, Consumer).
 This is also called during all get and remove operations to only return valid records.
|`max-size` |long |`100000` |Configure maximal cache size.
|`parallelism-threshold` |long |`10000` |Configure parallelism threshold.

|===

// end::config[]