///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.openapi.ui.OpenApiUi
:keywords: helidon, config, io.helidon.integrations.openapi.ui.OpenApiUi
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.openapi.ui.OpenApiUi
include::{rootdir}/includes/attributes.adoc[]

= OpenApiUi (integrations.openapi.ui) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.openapi.ui/io/helidon/integrations/openapi/ui/OpenApiUi.html[io.helidon.integrations.openapi.ui.OpenApiUi]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`enabled` |boolean |`true` |Sets whether the service should be enabled.

 @return `true` if enabled, `false` otherwise
|`options` |Map&lt;string, string&gt; |{nbsp} |Merges implementation-specific UI options.

 @return options for the UI to merge
|`web-context` |string |{nbsp} |Full web context (not just the suffix).

 @return full web context path

|===

// end::config[]