///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.metrics.api.ScopeConfig
:keywords: helidon, config, io.helidon.metrics.api.ScopeConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.metrics.api.ScopeConfig
include::{rootdir}/includes/attributes.adoc[]

= ScopeConfig (metrics.api) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.metrics.api/io/helidon/metrics/api/ScopeConfig.html[io.helidon.metrics.api.ScopeConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`enabled` |boolean |`true` |Whether the scope is enabled.

 @return if the scope is enabled
|`filter.exclude` |Pattern |{nbsp} |Regular expression for meter names to exclude.

 @return exclude expression
|`filter.include` |Pattern |{nbsp} |Regular expression for meter names to include.

 @return include expression
|`name` |string |{nbsp} |Name of the scope to which the configuration applies.

 @return scope name

|===

// end::config[]