///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.websocket.WsConfig
:keywords: helidon, config, io.helidon.webserver.websocket.WsConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.websocket.WsConfig
include::{rootdir}/includes/attributes.adoc[]

= WsConfig (webserver.websocket) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.websocket/io/helidon/webserver/websocket/WsConfig.html[io.helidon.webserver.websocket.WsConfig]



This type provides the following service implementations:

- `io.helidon.webserver.spi.ProtocolConfig`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`max-frame-length` |int |`1048576` |Max WebSocket frame size supported by the server on a read operation.
 Default is 1 MB.

 Max frame size to read
|`name` |string |`websocket` |Name of this configuration.

 Configuration name
|`origins` |string[&#93; |{nbsp} |WebSocket origins.

 Origins

|===

// end::config[]