///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.oci.tls.certificates.OciCertificatesTlsManager
:keywords: helidon, config, io.helidon.integrations.oci.tls.certificates.OciCertificatesTlsManager
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.oci.tls.certificates.OciCertificatesTlsManager
include::{rootdir}/includes/attributes.adoc[]

= OciCertificatesTlsManager (integrations.oci.tls.certificates) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.oci.tls.certificates/io/helidon/integrations/oci/tls/certificates/OciCertificatesTlsManager.html[io.helidon.integrations.oci.tls.certificates.OciCertificatesTlsManager]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`ca-ocid` |string |{nbsp} |The Certificate Authority OCID.

 Certificate authority OCID
|`cert-ocid` |string |{nbsp} |The Certificate OCID.

 Certificate OCID
|`compartment-ocid` |string |{nbsp} |The OCID of the compartment the services are in.

 The compartment OCID
|`key-ocid` |string |{nbsp} |The Key OCID.

 Key OCID
|`key-password` |Supplier |{nbsp} |The Key password.

 Key password
|`schedule` |string |{nbsp} |The schedule for trigger a reload check, testing whether there is a new io.helidon.common.tls.Tls instance
 available.

 The schedule for reload
|`vault-crypto-endpoint` |URI |{nbsp} |The address to use for the OCI Key Management Service / Vault crypto usage.
 Each OCI Vault has public crypto and management endpoints. We need to specify the crypto endpoint of the vault we are
 rotating the private keys in. The implementation expects both client and server to store the private key in the same vault.

 The address for the key management service / vault crypto usage
|`vault-management-endpoint` |URI |{nbsp} |The address to use for the OCI Key Management Service / Vault management usage.
 The crypto endpoint of the vault we are rotating the private keys in.

 The address for the key management service / vault management usage

|===

// end::config[]