///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.security.util.TokenHandler
:keywords: helidon, config, io.helidon.security.util.TokenHandler
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.security.util.TokenHandler
include::{rootdir}/includes/attributes.adoc[]

= TokenHandler (security.util) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.security.util/io/helidon/security/util/TokenHandler.html[io.helidon.security.util.TokenHandler]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`format` |string |{nbsp} |Token format for creating outbound tokens.
|`header` |string |{nbsp} |Set the name of header to look into to extract the token.
|`prefix` |string |{nbsp} |Set the prefix of header value to extract the token.
|`regexp` |string |{nbsp} |Set the token pattern (Regular expression) to extract the token.

|===

// end::config[]