///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.faulttolerance.Async
:keywords: helidon, config, io.helidon.faulttolerance.Async
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.faulttolerance.Async
include::{rootdir}/includes/attributes.adoc[]

= Async (faulttolerance) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.faulttolerance/io/helidon/faulttolerance/Async.html[io.helidon.faulttolerance.Async]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`executor-name` |string |{nbsp} |Name of an executor service. This is only honored when service registry is used.

 Name fo the java.util.concurrent.ExecutorService to lookup
 See executor()

|===

// end::config[]