///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.common.pki.KeystoreKeys
:keywords: helidon, config, io.helidon.common.pki.KeystoreKeys
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.common.pki.KeystoreKeys
include::{rootdir}/includes/attributes.adoc[]

= KeystoreKeys (common.pki) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.common.pki/io/helidon/common/pki/KeystoreKeys.html[io.helidon.common.pki.KeystoreKeys]




== Configuration options

.Required configuration options
[cols="3,3a,2,5a"]
|===
|key |type |default value |description

|`resource` |xref:{rootdir}/config/io_helidon_common_configurable_Resource.adoc[Resource] |{nbsp} |Keystore resource definition.

Keystore resource, from file path, classpath, URL etc.

|===



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cert-chain.alias` |string |{nbsp} |Alias of an X.509 chain.

Alias of certificate chain in the keystore
|`cert.alias` |string |{nbsp} |Alias of X.509 certificate of public key.
Used to load both the certificate and public key.

Alias under which the certificate is stored in the keystore
|`key.alias` |string |{nbsp} |Alias of the private key in the keystore.

Alias of the key in the keystore
|`key.passphrase` |char[] |{nbsp} |Pass-phrase of the key in the keystore (used for private keys).
This is (by default) the same as keystore passphrase - only configure
if it differs from keystore passphrase.

Pass-phrase of the key
|`passphrase` |char[] |{nbsp} |Pass-phrase of the keystore (supported with JKS and PKCS12 keystores).

Keystore password to use
|`trust-store` |boolean |`false` |If you want to build a trust store, call this method to add all
certificates present in the keystore to certificate list.

Whether this is a trust store
|`type` |string |`PKCS12` |Set type of keystore.
Defaults to DEFAULT_KEYSTORE_TYPE,
expected are other keystore types supported by java then can store keys under aliases.

Keystore type to load the key

|===

// end::config[]