///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.http1.Http1Config
:keywords: helidon, config, io.helidon.webserver.http1.Http1Config
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.http1.Http1Config
include::{rootdir}/includes/attributes.adoc[]

= Http1Config (webserver.http1) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.http1/io/helidon/webserver/http1/Http1Config.html[io.helidon.webserver.http1.Http1Config]


[source,text]
.Config key
----
http_1_1
----


This type provides the following service implementations:

- `io.helidon.webserver.spi.ProtocolConfigProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`continue-immediately` |boolean |`false` |When true WebServer answers to expect continue with 100 continue immediately,
not waiting for user to actually request the data.

If `true` answer with 100 continue immediately after expect continue
|`max-headers-size` |int |`16384` |Maximal size of received headers in bytes.

Maximal header size
|`max-prologue-length` |int |`4096` |Maximal size of received HTTP prologue (GET /path HTTP/1.1).

Maximal size in bytes
|`recv-log` |boolean |`true` |Logging of received packets. Uses trace and debug levels on logger of
Http1LoggingConnectionListener with suffix of `.recv``.

`true` if logging should be enabled for received packets, `false` if no logging should be done
|`requested-uri-discovery` |xref:{rootdir}/config/io_helidon_http_RequestedUriDiscoveryContext.adoc[RequestedUriDiscoveryContext] |{nbsp} |Requested URI discovery settings.

Settings for computing the requested URI
|`send-log` |boolean |`true` |Logging of sent packets. Uses trace and debug levels on logger of
Http1LoggingConnectionListener with suffix of `.send``.

`true` if logging should be enabled for sent packets, `false` if no logging should be done
|`validate-path` |boolean |`true` |If set to false, any path is accepted (even containing illegal characters).

Whether to validate path
|`validate-request-headers` |boolean |`true` |Whether to validate headers.
If set to false, any value is accepted, otherwise validates headers + known headers
are validated by format
(content length is always validated as it is part of protocol processing (other headers may be validated if
features use them)).

    Defaults to `true`.


Whether to validate headers
|`validate-response-headers` |boolean |`false` |Whether to validate headers.
If set to false, any value is accepted, otherwise validates headers + known headers
are validated by format
(content length is always validated as it is part of protocol processing (other headers may be validated if
features use them)).

    Defaults to `false` as user has control on the header creation.


Whether to validate headers

|===

// end::config[]