///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.common.socket.SocketOptions
:keywords: helidon, config, io.helidon.common.socket.SocketOptions
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.common.socket.SocketOptions
include::{rootdir}/includes/attributes.adoc[]

= SocketOptions (common.socket) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.common.socket/io/helidon/common/socket/SocketOptions.html[io.helidon.common.socket.SocketOptions]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`connect-timeout` |Duration |`PT10S` |Socket connect timeout. Default is 10 seconds.

 @return connect timeout duration
|`read-timeout` |Duration |`PT30S` |Socket read timeout. Default is 30 seconds.

 @return read timeout duration
|`socket-keep-alive` |boolean |`true` |Configure socket keep alive.
 Default is `true`.

 @return keep alive
 @see java.net.StandardSocketOptions#SO_KEEPALIVE
|`socket-receive-buffer-size` |int |`32768` |Socket receive buffer size.

 @return buffer size, in bytes
 @see java.net.StandardSocketOptions#SO_RCVBUF
|`socket-reuse-address` |boolean |`true` |Socket reuse address.
 Default is `true`.

 @return whether to reuse address
 @see java.net.StandardSocketOptions#SO_REUSEADDR
|`socket-send-buffer-size` |int |`32768` |Socket send buffer size.

 @return buffer size, in bytes
 @see java.net.StandardSocketOptions#SO_SNDBUF
|`tcp-no-delay` |boolean |`false` |This option may improve performance on some systems.
 Default is `false`.

 @return whether to use TCP_NODELAY, defaults to `false`
 @see java.net.StandardSocketOptions#TCP_NODELAY

|===

// end::config[]