///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.scheduling.Cron
:keywords: helidon, config, io.helidon.scheduling.Cron
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.scheduling.Cron
include::{rootdir}/includes/attributes.adoc[]

= Cron (scheduling) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.scheduling/io/helidon/scheduling/Cron.html[io.helidon.scheduling.Cron]




== Configuration options

.Required configuration options
[cols="3,3a,2,5a"]
|===
|key |type |default value |description

|`expression` |string |{nbsp} |Cron expression for specifying period of execution.

*Examples:*

- `0/2 * * * * ? *` - Every 2 seconds
- `0 45 9 ? * *` - Every day at 9:45
- `0 15 8 ? * MON-FRI` - Every workday at 8:15

Cron expression

|===



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`concurrent` |boolean |`true` |Allow concurrent execution if previous task didn't finish before next execution.
Default value is `true`.

True for allow concurrent execution.

|===

// end::config[]