///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.security.providers.abac.AbacProvider
:keywords: helidon, config, io.helidon.security.providers.abac.AbacProvider
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.security.providers.abac.AbacProvider
include::{rootdir}/includes/attributes.adoc[]

= AbacProvider (security.providers.abac) Configuration

// tag::config[]

Attribute Based Access Control provider


Type: link:{javadoc-base-url}/io.helidon.security.providers.abac/io/helidon/security/providers/abac/AbacProvider.html[io.helidon.security.providers.abac.AbacProvider]


[source,text]
.Config key
----
abac
----


This type provides the following service implementations:

- `io.helidon.security.spi.SecurityProvider`
- `io.helidon.security.spi.AuthorizationProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`fail-if-none-validated` |boolean |`true` |Whether to fail if NONE of the attributes is validated.
|`fail-on-unvalidated` |boolean |`true` |Whether to fail if any attribute is left unvalidated.

|===

// end::config[]