///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.common.pki.Keys
:keywords: helidon, config, io.helidon.common.pki.Keys
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.common.pki.Keys
include::{rootdir}/includes/attributes.adoc[]

= Keys (common.pki) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.common.pki/io/helidon/common/pki/Keys.html[io.helidon.common.pki.Keys]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`keystore` |xref:{rootdir}/config/io_helidon_common_pki_KeystoreKeys.adoc[KeystoreKeys] |{nbsp} |Configure keys from a keystore.
 Once the config object is built, this option will ALWAYS be empty. All keys from the keystore will be
 populated to #privateKey(), #publicKey(), #publicCert() etc.

 @return keystore configuration
|`pem` |xref:{rootdir}/config/io_helidon_common_pki_PemKeys.adoc[PemKeys] |{nbsp} |Configure keys from pem file(s).
 Once the config object is built, this option will ALWAYS be empty. All keys from the keystore will be
 populated to #privateKey(), #publicKey(), #publicCert() etc.

 @return pem based definition

|===

// end::config[]