///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.metrics.api.ScopingConfig
:keywords: helidon, config, io.helidon.metrics.api.ScopingConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.metrics.api.ScopingConfig
include::{rootdir}/includes/attributes.adoc[]

= ScopingConfig (metrics.api) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.metrics.api/io/helidon/metrics/api/ScopingConfig.html[io.helidon.metrics.api.ScopingConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`default` |string |`application` |Default scope value to associate with meters that are registered without an explicit setting; no setting means meters
are assigned scope io.helidon.metrics.api.Meter.Scope.DEFAULT.

Default scope value
|`scopes` |xref:{rootdir}/config/io_helidon_metrics_api_ScopeConfig.adoc[Map&lt;string, ScopeConfig&gt;] |{nbsp} |Settings for individual scopes.

Scope settings
|`tag-name` |string |`scope` |Tag name for storing meter scope values in the underlying implementation meter registry.

Tag name for storing scope values

|===

// end::config[]