///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.faulttolerance.Bulkhead
:keywords: helidon, config, io.helidon.faulttolerance.Bulkhead
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.faulttolerance.Bulkhead
include::{rootdir}/includes/attributes.adoc[]

= Bulkhead (faulttolerance) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.faulttolerance/io/helidon/faulttolerance/Bulkhead.html[io.helidon.faulttolerance.Bulkhead]


This is a standalone configuration type, prefix from configuration root: `fault-tolerance.bulkheads`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`limit` |int |`10` |Maximal number of parallel requests going through this bulkhead.
When the limit is reached, additional requests are enqueued.

Maximal number of parallel calls, defaults is DEFAULT_LIMIT
|`queue-length` |int |`10` |Maximal number of enqueued requests waiting for processing.
When the limit is reached, additional attempts to invoke
a request will receive a BulkheadException.

Length of the queue

|===

// end::config[]