///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webclient.grpc.GrpcClientProtocolConfig
:keywords: helidon, config, io.helidon.webclient.grpc.GrpcClientProtocolConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webclient.grpc.GrpcClientProtocolConfig
include::{rootdir}/includes/attributes.adoc[]

= GrpcClientProtocolConfig (webclient.grpc) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webclient.grpc/io/helidon/webclient/grpc/GrpcClientProtocolConfig.html[io.helidon.webclient.grpc.GrpcClientProtocolConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`abort-poll-time-expired` |boolean |`false` |Whether to continue retrying after a poll wait timeout expired or not. If a read
 operation timeouts out and this flag is set to `false`, the event is logged
 and the client will retry. Otherwise, an exception is thrown.

 Abort timeout flag
|`heartbeat-period` |Duration |`PT0S` |How often to send a heartbeat (HTTP/2 ping) to check if the connection is still
 alive. This is useful for long-running, streaming gRPC calls. It is turned off by
 default but can be enabled by setting the period to a value greater than 0.

 Heartbeat period
|`init-buffer-size` |int |`2048` |Initial buffer size used to serialize gRPC request payloads. Buffers shall grow
 according to the payload size, but setting this initial buffer size to a larger value
 may improve performance for certain applications.

 Initial buffer size
|`name` |string |`grpc` |Name identifying this client protocol. Defaults to type.

 Name of client protocol
|`poll-wait-time` |Duration |`PT10S` |How long to wait for the next HTTP/2 data frame to arrive in underlying stream.
 Whether this is a fatal error or not is controlled by abortPollTimeExpired().

 Poll time as a duration
 @see io.helidon.common.socket.SocketOptions#readTimeout()

|===

// end::config[]