///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.oci.ConfigFileMethodConfig
:keywords: helidon, config, io.helidon.integrations.oci.ConfigFileMethodConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.oci.ConfigFileMethodConfig
include::{rootdir}/includes/attributes.adoc[]

= ConfigFileMethodConfig (integrations.oci) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.oci/io/helidon/integrations/oci/ConfigFileMethodConfig.html[io.helidon.integrations.oci.ConfigFileMethodConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`path` |string |{nbsp} |The OCI configuration profile path.

 The OCI configuration profile path
|`profile` |string |`DEFAULT` |The OCI configuration/auth profile name.

 The optional OCI configuration/auth profile name

|===

// end::config[]