///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.observe.health.HealthObserver
:keywords: helidon, config, io.helidon.webserver.observe.health.HealthObserver
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.observe.health.HealthObserver
include::{rootdir}/includes/attributes.adoc[]

= HealthObserver (webserver.observe.health) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.observe.health/io/helidon/webserver/observe/health/HealthObserver.html[io.helidon.webserver.observe.health.HealthObserver]


This is a standalone configuration type, prefix from configuration root: `health`


This type provides the following service implementations:

- `io.helidon.webserver.observe.spi.ObserveProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`details` |boolean |`false` |Whether details should be printed.
By default, health only returns a io.helidon.http.Status.NO_CONTENT_204 for success,
io.helidon.http.Status.SERVICE_UNAVAILABLE_503 for health down,
and io.helidon.http.Status.INTERNAL_SERVER_ERROR_500 in case of error with no entity.
When details are enabled, health returns io.helidon.http.Status.OK_200 for success, same codes
otherwise
and a JSON entity with detailed information about each health check executed.

Set to `true` to enable details
|`endpoint` |string |`health` |
|`use-system-services` |boolean |`true` |Whether to use services discovered by java.util.ServiceLoader.
By default, all io.helidon.health.spi.HealthCheckProvider based health checks are added.

Set to `false` to disable discovery

|===

// end::config[]