///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.faulttolerance.Retry
:keywords: helidon, config, io.helidon.faulttolerance.Retry
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.faulttolerance.Retry
include::{rootdir}/includes/attributes.adoc[]

= Retry (faulttolerance) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.faulttolerance/io/helidon/faulttolerance/Retry.html[io.helidon.faulttolerance.Retry]


This is a standalone configuration type, prefix from configuration root: `fault-tolerance.retries`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`calls` |int |`3` |Number of calls (first try + retries).

Number of desired calls, must be 1 (means no retries) or higher.
|`delay` |Duration |`PT0.2S` |Base delay between try and retry.
Defaults to `200 ms`.

Delay between retries (combines with retry policy)
|`delay-factor` |double |`-1.0` |Delay retry policy factor. If unspecified (value of `-1`), Jitter retry policy would be used, unless
jitter is also unspecified.

Default when Retry.DelayingRetryPolicy is used is `2`.

Delay factor for delaying retry policy
|`jitter` |Duration |`PT-1S` |Jitter for Retry.JitterRetryPolicy. If unspecified (value of `-1`),
delaying retry policy is used. If both this value, and delayFactor() are specified, delaying retry policy
would be used.

Jitter
|`overall-timeout` |Duration |`PT1S` |Overall timeout of all retries combined.

Overall timeout

|===

// end::config[]