///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.scheduling.FixedRate
:keywords: helidon, config, io.helidon.scheduling.FixedRate
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.scheduling.FixedRate
include::{rootdir}/includes/attributes.adoc[]

= FixedRate (scheduling) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.scheduling/io/helidon/scheduling/FixedRate.html[io.helidon.scheduling.FixedRate]




== Configuration options

.Required configuration options
[cols="3,3a,2,5a"]
|===
|key |type |default value |description

|`delay` |long |{nbsp} |Fixed rate delay between each invocation. Time unit is by default java.util.concurrent.TimeUnit#SECONDS,
 can be specified with io.helidon.scheduling.Scheduling.FixedRateBuilder#timeUnit(java.util.concurrent.TimeUnit).

 @return delay between each invocation

|===



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`delay-type` |DelayType (SINCE_PREVIOUS_START, SINCE_PREVIOUS_END) |`@io.helidon.scheduling.FixedRate.DelayType@.SINCE_PREVIOUS_START` |Configure whether the delay between the invocations should be calculated from the time when previous task started or ended.
 Delay type is by default FixedRate.DelayType#SINCE_PREVIOUS_START.

 @return delay type
|`initial-delay` |long |`0` |Initial delay of the first invocation. Time unit is by default java.util.concurrent.TimeUnit#SECONDS,
 can be specified with
 io.helidon.scheduling.Scheduling.FixedRateBuilder#timeUnit(java.util.concurrent.TimeUnit) timeUnit().

 @return initial delay value
|`time-unit` |TimeUnit (NANOSECONDS, MICROSECONDS, MILLISECONDS, SECONDS, MINUTES, HOURS, DAYS) |`TimeUnit.SECONDS` |java.util.concurrent.TimeUnit TimeUnit used for interpretation of values provided with
 io.helidon.scheduling.Scheduling.FixedRateBuilder#delay(long)
 and io.helidon.scheduling.Scheduling.FixedRateBuilder#initialDelay(long).

 @return time unit for interpreting values
         in io.helidon.scheduling.Scheduling.FixedRateBuilder#delay(long)
         and io.helidon.scheduling.Scheduling.FixedRateBuilder#initialDelay(long)

|===

// end::config[]