///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.http.media.MediaContext
:keywords: helidon, config, io.helidon.http.media.MediaContext
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.http.media.MediaContext
include::{rootdir}/includes/attributes.adoc[]

= MediaContext (http.media) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.http.media/io/helidon/http/media/MediaContext.html[io.helidon.http.media.MediaContext]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`fallback` |xref:{rootdir}/config/io_helidon_http_media_MediaContext.adoc[MediaContext] |{nbsp} |Existing context to be used as a fallback for this context.

 Media context to use if supports configured on this request cannot provide a good result
|`media-supports` |io.helidon.http.media.MediaSupport[&#93; (service provider interface) |{nbsp} |Media supports to use.
 This instance has priority over provider(s) discovered by service loader.
 The providers are used in order of calling this method, where the first support added is the
 first one to be queried for readers and writers.

 Media supports
|`register-defaults` |boolean |`true` |Should we register defaults of Helidon, such as String media support.

 Whether to register default media supports

|===

// end::config[]