///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.oci.sdk.runtime.OciConfig
:keywords: helidon, config, io.helidon.integrations.oci.sdk.runtime.OciConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.oci.sdk.runtime.OciConfig
include::{rootdir}/includes/attributes.adoc[]

= OciConfig (integrations.oci.sdk.runtime) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.oci.sdk.runtime/io/helidon/integrations/oci/sdk/runtime/OciConfig.html[io.helidon.integrations.oci.sdk.runtime.OciConfig]


This is a standalone configuration type, prefix from configuration root: `oci`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`auth-strategies` |string[&#93; (auto, config, config-file, instance-principals, resource-principal) |{nbsp} |The list of authentication strategies that will be attempted by
 com.oracle.bmc.auth.BasicAuthenticationDetailsProvider when one is
 called for. This is only used if authStrategy() is not present.

- `auto` - if present in the list, or if no value
          for this property exists.
- `config` - the
          com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider
          will be used, customized with other configuration
          properties described here.
- `config-file` - the
          com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider
          will be used, customized with other configuration
          properties described here.
- `instance-principals` - the
          com.oracle.bmc.auth.InstancePrincipalsAuthenticationDetailsProvider
          will be used.
- `resource-principal` - the
          com.oracle.bmc.auth.ResourcePrincipalAuthenticationDetailsProvider
          will be used.

If there are more than one strategy descriptors defined, the
 first one that is deemed to be available/suitable will be used and all others will be ignored.

 The list of authentication strategies that will be applied, defaulting to `auto`
 See io.helidon.integrations.oci.sdk.runtime.OciAuthenticationDetailsProvider.AuthStrategy
|`auth-strategy` |string (auto, config, config-file, instance-principals, resource-principal) |{nbsp} |The singular authentication strategy to apply. This will be preferred over authStrategies() if both are
 present.

 The singular authentication strategy to be applied
|`auth.fingerprint` |string |{nbsp} |The OCI authentication fingerprint.

 This configuration property has an effect only when `config` is, explicitly or implicitly,
 present in the value for the authStrategies(). This is also known as simpleConfigIsPresent().
 When it is present, this property must be provided in order to set the <a
 href="https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm">API signing key's fingerprint</a>.
 See com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getFingerprint() for more details.

 The OCI authentication fingerprint
|`auth.keyFile` |string |`oci_api_key.pem` |The OCI authentication key file.

 This configuration property has an effect only when `config` is, explicitly or implicitly,
 present in the value for the authStrategies(). This is also known as simpleConfigIsPresent().
 When it is present, this property must be provided in order to set the
 com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getPrivateKey(). This file must exist in the
 `user.home` directory. Alternatively, this property can be set using either authPrivateKey() or
 using authPrivateKeyPath().

 The OCI authentication key file
|`auth.passphrase` |char[] |{nbsp} |The OCI authentication passphrase.

 This configuration property has an effect only when `config` is, explicitly or implicitly,
 present in the value for the authStrategies(). This is also known as simpleConfigIsPresent().
 When it is present, this property must be provided in order to set the
 com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getPassphraseCharacters().

 The OCI authentication passphrase
|`auth.private-key` |char[] |{nbsp} |The OCI authentication private key.

 This configuration property has an effect only when `config` is, explicitly or implicitly,
 present in the value for the authStrategies(). This is also known as simpleConfigIsPresent().
 When it is present, this property must be provided in order to set the
 com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getPrivateKey(). Alternatively, this property
 can be set using either authKeyFile() residing in the `user.home` directory, or using
 authPrivateKeyPath().

 The OCI authentication private key
|`auth.private-key-path` |string |{nbsp} |The OCI authentication key file path.

 This configuration property has an effect only when `config` is, explicitly or implicitly,
 present in the value for the authStrategies(). This is also known as simpleConfigIsPresent().
 When it is present, this property must be provided in order to set the
 com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getPrivateKey(). This file path is
 an alternative for using authKeyFile() where the file must exist in the `user.home` directory.
 Alternatively, this property can be set using authPrivateKey().

 The OCI authentication key file path
|`auth.region` |string |{nbsp} |The OCI region.

 This configuration property has an effect only when `config` is, explicitly or implicitly,
 present in the value for the authStrategies(). This is also known as simpleConfigIsPresent().
 When it is present, either this property or com.oracle.bmc.auth.RegionProvider must be provide a value in order
 to set the com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider.getRegion().

 The OCI region
|`auth.tenant-id` |string |{nbsp} |The OCI tenant id.

 This configuration property has an effect only when `config` is, explicitly or implicitly,
 present in the value for the authStrategies(). This is also known as simpleConfigIsPresent().
 When it is present, this property must be provided in order to set the
 com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider.getTenantId().

 The OCI tenant id
|`auth.user-id` |string |{nbsp} |The OCI user id.

 This configuration property has an effect only when `config` is, explicitly or implicitly,
 present in the value for the authStrategies().
 When it is present, this property must be provided in order to set the
 com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider.getUserId().

 The OCI user id
|`config.path` |string |{nbsp} |The OCI configuration profile path.

 This configuration property has an effect only when `config-file` is, explicitly or implicitly,
 present in the value for the authStrategies(). This is also known as fileConfigIsPresent().
 When it is present, this property must also be present and then the
 com.oracle.bmc.ConfigFileReader.parse(String)
 method will be passed this value. It is expected to be passed with a
 valid OCI configuration file path.

 The OCI configuration profile path
|`config.profile` |string |`DEFAULT` |The OCI configuration/auth profile name.

 This configuration property has an effect only when `config-file` is, explicitly or implicitly,
 present in the value for the authStrategies(). This is also known as fileConfigIsPresent().
 When it is present, this property may also be optionally provided in order to override the default
 DEFAULT_PROFILE_NAME.

 The optional OCI configuration/auth profile name
|`imds.hostname` |string |`169.254.169.254` |The OCI IMDS hostname.

 This configuration property is used to identify the metadata service url.

 The OCI IMDS hostname
|`imds.timeout.milliseconds` |Duration |`PT0.1S` |The OCI IMDS connection timeout. This is used to auto-detect availability.

 This configuration property is used when attempting to connect to the metadata service.

 The OCI IMDS connection timeout
 See OciAvailability

|===

// end::config[]