///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.oci.ConfigMethodConfig
:keywords: helidon, config, io.helidon.integrations.oci.ConfigMethodConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.oci.ConfigMethodConfig
include::{rootdir}/includes/attributes.adoc[]

= ConfigMethodConfig (integrations.oci) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.oci/io/helidon/integrations/oci/ConfigMethodConfig.html[io.helidon.integrations.oci.ConfigMethodConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`fingerprint` |string |{nbsp} |The OCI authentication fingerprint.

This configuration property must be provided in order to set the https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm[API signing key's fingerprint].
See com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getFingerprint() for more details.

The OCI authentication fingerprint
|`passphrase` |char[] |{nbsp} |The OCI authentication passphrase.

This property must be provided in order to set the
com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getPassphraseCharacters().

The OCI authentication passphrase
|`private-key` |xref:{rootdir}/config/io_helidon_common_configurable_Resource.adoc[Resource] |{nbsp} |The OCI authentication private key resource.
A resource can be defined as a resource on classpath, file on the file system,
base64 encoded text value in config, or plain-text value in config.

If not defined, we will use `.oci/oic_api_key.pem` file in user home directory.

The OCI authentication key file
|`region` |string |{nbsp} |The OCI region.

The OCI region
|`tenant-id` |string |{nbsp} |The OCI tenant id.

This property must be provided in order to set the
com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getTenantId().

The OCI tenant id
|`user-id` |string |{nbsp} |The OCI user id.

This property must be provided in order to set the
com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getUserId().

The OCI user id

|===

// end::config[]