///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.openapi.OpenApiFeature
:keywords: helidon, config, io.helidon.openapi.OpenApiFeature
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.openapi.OpenApiFeature
include::{rootdir}/includes/attributes.adoc[]

= OpenApiFeature (openapi) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.openapi/io/helidon/openapi/OpenApiFeature.html[io.helidon.openapi.OpenApiFeature]


This is a standalone configuration type, prefix from configuration root: `openapi`


This type provides the following service implementations:

- `io.helidon.webserver.spi.ServerFeatureProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cors` |xref:{rootdir}/config/io_helidon_cors_CrossOriginConfig.adoc[CrossOriginConfig] |{nbsp} |CORS config.

 CORS config
|`enabled` |boolean |`true` |Sets whether the feature should be enabled.

 `true` if enabled, `false` otherwise
|`manager` |io.helidon.openapi.OpenApiManager (service provider interface) |{nbsp} |OpenAPI manager.

 The OpenAPI manager
|`permit-all` |boolean |`true` |Whether to allow anybody to access the endpoint.

 Whether to permit access to metrics endpoint to anybody, defaults to `true`
 @see #roles()
|`roles` |string[&#93; |`openapi` |Hints for role names the user is expected to be in.

 List of hints
|`services` |io.helidon.openapi.OpenApiService[&#93; (service provider interface) |{nbsp} |OpenAPI services.

 The OpenAPI services
|`sockets` |string[&#93; |{nbsp} |List of sockets to register this feature on. If empty, it would get registered on all sockets.

 Socket names to register on, defaults to empty (all available sockets)
|`static-file` |string |{nbsp} |Path of the static OpenAPI document file. Default types are `json`, `yaml`, and `yml`.

 Location of the static OpenAPI document file
|`web-context` |string |`/openapi` |Web context path for the OpenAPI endpoint.

 WebContext to use
|`weight` |double |`90.0` |Weight of the OpenAPI feature. This is quite low, to be registered after routing.
 io.helidon.openapi.OpenApiFeature.WEIGHT.

 Weight of the feature

|===

// end::config[]