///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.observe.config.ConfigObserver
:keywords: helidon, config, io.helidon.webserver.observe.config.ConfigObserver
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.observe.config.ConfigObserver
include::{rootdir}/includes/attributes.adoc[]

= ConfigObserver (webserver.observe.config) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.observe.config/io/helidon/webserver/observe/config/ConfigObserver.html[io.helidon.webserver.observe.config.ConfigObserver]


[source,text]
.Config key
----
config
----


This type provides the following service implementations:

- `io.helidon.webserver.observe.spi.ObserveProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`endpoint` |string |`config` |
|`permit-all` |boolean |{nbsp} |Permit all access, even when not authorized.

Whether to permit access for anybody
|`secrets` |string[&#93; |`.*password, .*passphrase, .*secret` |Secret patterns (regular expressions) to exclude from output.
Any pattern that matches a key will cause the output to be obfuscated and not contain the value.

Patterns always added:

- `.*password`
- `.*passphrase`
- `.*secret`

Set of regular expression patterns for keys, where values should be excluded from output

|===

// end::config[]