///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.openapi.OpenApiFeature
:keywords: helidon, config, io.helidon.openapi.OpenApiFeature
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.openapi.OpenApiFeature
include::{rootdir}/includes/attributes.adoc[]

= OpenApiFeature (openapi) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.openapi/io/helidon/openapi/OpenApiFeature.html[io.helidon.openapi.OpenApiFeature]


This is a standalone configuration type, prefix from configuration root: `openapi`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cors` |xref:{rootdir}/config/io_helidon_cors_CrossOriginConfig.adoc[CrossOriginConfig] |{nbsp} |CORS config.

 @return CORS config
|`enabled` |boolean |`true` |Sets whether the feature should be enabled.

 @return `true` if enabled, `false` otherwise
|`manager` |io.helidon.openapi.OpenApiManager (service provider interface) |{nbsp} |OpenAPI manager.

 @return the OpenAPI manager
|`permit-all` |boolean |{nbsp} |Whether to allow anybody to access the endpoint.

 @return whether to permit access to metrics endpoint to anybody, defaults to `true`
 @see #roles()
|`roles` |string[&#93; |{nbsp} |Hints for role names the user is expected to be in.

 @return list of hints
|`services` |io.helidon.openapi.OpenApiService[&#93; (service provider interface) |{nbsp} |OpenAPI services.

 @return the OpenAPI services
|`static-file` |string |{nbsp} |Path of the static OpenAPI document file. Default types are `json`, `yaml`, and `yml`.

 @return location of the static OpenAPI document file
|`web-context` |string |`/openapi` |Web context path for the OpenAPI endpoint.

 @return webContext to use

|===

// end::config[]