///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webclient.api.WebClientCookieManager
:keywords: helidon, config, io.helidon.webclient.api.WebClientCookieManager
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webclient.api.WebClientCookieManager
include::{rootdir}/includes/attributes.adoc[]

= WebClientCookieManager (webclient.api) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webclient.api/io/helidon/webclient/api/WebClientCookieManager.html[io.helidon.webclient.api.WebClientCookieManager]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`automatic-store-enabled` |boolean |`false` |Whether automatic cookie store is enabled or not.

 Status of cookie store
|`cookie-policy` |CookiePolicy |`java.net.CookiePolicy.ACCEPT_ORIGINAL_SERVER` |Current cookie policy for this client.

 The cookie policy
|`default-cookies` |Map&lt;string, string&gt; |{nbsp} |Map of default cookies to include in all requests if cookies enabled.

 Map of default cookies

|===

// end::config[]