///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.cors.CorsFeature
:keywords: helidon, config, io.helidon.webserver.cors.CorsFeature
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.cors.CorsFeature
include::{rootdir}/includes/attributes.adoc[]

= CorsFeature (webserver.cors) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.cors/io/helidon/webserver/cors/CorsFeature.html[io.helidon.webserver.cors.CorsFeature]


[source,text]
.Config key
----
cors
----


This type provides the following service implementations:

- `io.helidon.webserver.spi.ServerFeatureProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`enabled` |boolean |`true` |This feature can be disabled.

 @return whether the feature is enabled
|`sockets` |string[&#93; |{nbsp} |List of sockets to register this feature on. If empty, it would get registered on all sockets.

 @return socket names to register on, defaults to empty (all available sockets)
|`weight` |double |`950.0` |Weight of the CORS feature. As it is used by other features, the default is quite high:
 `CorsFeature#WEIGHT`.

 @return weight of the feature

|===

// end::config[]