///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.http.encoding.ContentEncodingContext
:keywords: helidon, config, io.helidon.http.encoding.ContentEncodingContext
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.http.encoding.ContentEncodingContext
include::{rootdir}/includes/attributes.adoc[]

= ContentEncodingContext (http.encoding) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.http.encoding/io/helidon/http/encoding/ContentEncodingContext.html[io.helidon.http.encoding.ContentEncodingContext]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`content-encodings` |io.helidon.http.encoding.ContentEncoding[&#93; (service provider interface) |{nbsp} |List of content encodings that should be used.
Encodings configured here have priority over encodings discovered through service loader.

List of content encodings to be used (such as `gzip,deflate`)

|===

// end::config[]