///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.metrics.api.KeyPerformanceIndicatorMetricsConfig
:keywords: helidon, config, io.helidon.metrics.api.KeyPerformanceIndicatorMetricsConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.metrics.api.KeyPerformanceIndicatorMetricsConfig
include::{rootdir}/includes/attributes.adoc[]

= KeyPerformanceIndicatorMetricsConfig (metrics.api) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.metrics.api/io/helidon/metrics/api/KeyPerformanceIndicatorMetricsConfig.html[io.helidon.metrics.api.KeyPerformanceIndicatorMetricsConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`extended` |boolean |`false` |Whether KPI extended metrics are enabled.

 @return true if KPI extended metrics are enabled; false otherwise
|`long-running-requests.threshold` |Duration |`PT10S` |Threshold in ms that characterizes whether a request is long running.

 @return threshold in ms indicating a long-running request

|===

// end::config[]