///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.common.tls.Tls
:keywords: helidon, config, io.helidon.common.tls.Tls
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.common.tls.Tls
include::{rootdir}/includes/attributes.adoc[]

= Tls (common.tls) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.common.tls/io/helidon/common/tls/Tls.html[io.helidon.common.tls.Tls]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cipher-suite` |string[&#93; |{nbsp} |Enabled cipher suites for TLS communication.

 Cipher suits to enable, by default (or if list is empty), all available cipher suites
         are enabled
|`client-auth` |TlsClientAuth |`TlsClientAuth.NONE` |Configure requirement for mutual TLS.

 What type of mutual TLS to use, defaults to TlsClientAuth.NONE
|`enabled` |boolean |`true` |Flag indicating whether Tls is enabled.

 Enabled flag
|`endpoint-identification-algorithm` |string |`HTTPS` |Identification algorithm for SSL endpoints.

 Configure endpoint identification algorithm, or set to `NONE`
         to disable endpoint identification (equivalent to hostname verification).
         Defaults to Tls.ENDPOINT_IDENTIFICATION_HTTPS
|`internal-keystore-provider` |string |{nbsp} |Provider of the key stores used internally to create a key and trust manager factories.

 Keystore provider, if not defined, provider is not specified
|`internal-keystore-type` |string |{nbsp} |Type of the key stores used internally to create a key and trust manager factories.

 Keystore type, defaults to java.security.KeyStore.getDefaultType()
|`key-manager-factory-algorithm` |string |{nbsp} |Algorithm of the key manager factory used when private key is defined.
 Defaults to javax.net.ssl.KeyManagerFactory.getDefaultAlgorithm().

 Algorithm to use
|`manager` |io.helidon.common.tls.TlsManager (service provider interface) |{nbsp} |The Tls manager. If one is not explicitly defined in the config then a default manager will be created.

 The tls manager of the tls instance
 See ConfiguredTlsManager
|`private-key` |PrivateKey |{nbsp} |Private key to use. For server side TLS, this is required.
 For client side TLS, this is optional (used when mutual TLS is enabled).

 Private key to use
|`protocol` |string |`TLS` |Configure the protocol used to obtain an instance of javax.net.ssl.SSLContext.

 Protocol to use, defaults to DEFAULT_PROTOCOL
|`protocols` |string[&#93; |{nbsp} |Enabled protocols for TLS communication.
 Example of valid values for `TLS` protocol: `TLSv1.3`, `TLSv1.2`

 Protocols to enable, by default (or if list is empty), all available protocols are enabled
|`provider` |string |{nbsp} |Use explicit provider to obtain an instance of javax.net.ssl.SSLContext.

 Provider to use, defaults to none (only protocol() is used by default)
|`revocation` |xref:{rootdir}/config/io_helidon_common_tls_RevocationConfig.adoc[RevocationConfig] |{nbsp} |Certificate revocation check configuration.

 Certificate revocation configuration
|`secure-random-algorithm` |string |{nbsp} |Algorithm to use when creating a new secure random.

 Algorithm to use, by default uses java.security.SecureRandom constructor
|`secure-random-provider` |string |{nbsp} |Provider to use when creating a new secure random.
 When defined, secureRandomAlgorithm() must be defined as well.

 Provider to use, by default no provider is specified
|`session-cache-size` |int |`20480` |SSL session cache size.

 Session cache size, defaults to DEFAULT_SESSION_CACHE_SIZE.
|`session-timeout` |Duration |`PT24H` |SSL session timeout.

 Session timeout, defaults to DEFAULT_SESSION_TIMEOUT.
|`trust` |X509Certificate[&#93; |{nbsp} |List of certificates that form the trust manager.

 Certificates to be trusted
|`trust-all` |boolean |`false` |Trust any certificate provided by the other side of communication.

 <b>This is a dangerous setting: </b> if set to `true`, any certificate will be accepted, throwing away
 most of the security advantages of TLS. <b>NEVER</b> do this in production.

 Whether to trust all certificates, do not use in production
|`trust-manager-factory-algorithm` |string |{nbsp} |Trust manager factory algorithm.

 Algorithm to use

|===

// end::config[]