///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.oci.SessionTokenMethodConfig
:keywords: helidon, config, io.helidon.integrations.oci.SessionTokenMethodConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.oci.SessionTokenMethodConfig
include::{rootdir}/includes/attributes.adoc[]

= SessionTokenMethodConfig (integrations.oci) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.oci/io/helidon/integrations/oci/SessionTokenMethodConfig.html[io.helidon.integrations.oci.SessionTokenMethodConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`fingerprint` |string |{nbsp} |The OCI authentication fingerprint.

This configuration property must be provided in order to set the https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm[API signing key's fingerprint].
See com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getFingerprint() for more details.

The OCI authentication fingerprint
|`initial-refresh-delay` |Duration |{nbsp} |Delay of the first refresh.
Defaults to 0, to refresh immediately (implemented in the authentication details provider).

Initial refresh delay
See com.oracle.bmc.auth.SessionTokenAuthenticationDetailsProvider.SessionTokenAuthenticationDetailsProviderBuilder.initialRefreshDelay(long)
|`passphrase` |char[] |{nbsp} |The OCI authentication passphrase.

This property must be provided in order to set the
com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getPassphraseCharacters().

The OCI authentication passphrase
|`private-key-path` |Path |{nbsp} |The OCI authentication private key resource.
A resource can be defined as a resource on classpath, file on the file system,
base64 encoded text value in config, or plain-text value in config.

If not defined, we will use `".oci/sessions/DEFAULT/oci_api_key.pem` file in user home directory.

The OCI authentication key file
|`refresh-period` |Duration |{nbsp} |Refresh period, i.e. how often refresh occurs.
Defaults to 55 minutes (implemented in the authentication details provider).

Refresh period
See com.oracle.bmc.auth.SessionTokenAuthenticationDetailsProvider.SessionTokenAuthenticationDetailsProviderBuilder.refreshPeriod(long)
|`region` |string |{nbsp} |The OCI region.

The OCI region
|`session-lifetime-hours` |long |{nbsp} |Maximal lifetime of a session.
Defaults to (and maximum is) 24 hours.
Can only be set to a lower value.

Lifetime of a session in hours
|`session-token` |string |{nbsp} |Session token value.
If both this value, and sessionTokenPath() is defined, this value is used.

Session token
|`session-token-path` |Path |{nbsp} |Session token path.
If both this value, and sessionToken() is defined, the value of sessionToken() is used.

Session token path
|`tenant-id` |string |{nbsp} |The OCI tenant id.

This property must be provided in order to set the
com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getTenantId().

The OCI tenant id
|`user-id` |string |{nbsp} |The OCI user id.

This property must be provided in order to set the
com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider.getUserId().

The OCI user id

|===

// end::config[]