///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.faulttolerance.Timeout
:keywords: helidon, config, io.helidon.faulttolerance.Timeout
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.faulttolerance.Timeout
include::{rootdir}/includes/attributes.adoc[]

= Timeout (faulttolerance) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.faulttolerance/io/helidon/faulttolerance/Timeout.html[io.helidon.faulttolerance.Timeout]


This is a standalone configuration type, prefix from configuration root: `fault-tolerance.timeouts`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`current-thread` |boolean |`false` |Flag to indicate that code must be executed in current thread instead
 of in an executor's thread. This flag is `false` by default.

  whether to execute on current thread (`true`), or in an executor service (`false`})
|`timeout` |Duration |`PT10S` |Duration to wait before timing out.
 Defaults to `10 seconds`.

 Timeout

|===

// end::config[]