///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.integrations.oci.OciConfig
:keywords: helidon, config, io.helidon.integrations.oci.OciConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.integrations.oci.OciConfig
include::{rootdir}/includes/attributes.adoc[]

= OciConfig (integrations.oci) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.integrations.oci/io/helidon/integrations/oci/OciConfig.html[io.helidon.integrations.oci.OciConfig]


This is a standalone configuration type, prefix from configuration root: `helidon.oci`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`allowed-authentication-methods` |string[&#93; |{nbsp} |List of attempted authentication strategies in case io.helidon.integrations.oci.OciConfig.authenticationMethod() is
set to AUTHENTICATION_METHOD_AUTO.

In case the list is empty, all available strategies will be tried, ordered by their io.helidon.common.Weight

List of authentication strategies to be tried
See io.helidon.integrations.oci.OciConfig.authenticationMethod()
|`authentication-method` |string |`auto` |Authentication method to use. If the configured method is not available, an exception
would be thrown for OCI related services.

Known and supported authentication strategies for public OCI:

- AUTHENTICATION_METHOD_AUTO - use the list of
    io.helidon.integrations.oci.OciConfig.allowedAuthenticationMethods()
         (in the provided order), and choose the first one capable of providing data
- AuthenticationMethodConfig.METHOD -
    use configuration of the application to obtain values needed to set up connectivity, uses
    com.oracle.bmc.auth.SimpleAuthenticationDetailsProvider
- AuthenticationMethodConfigFile.METHOD - use configuration file of OCI (`home/.oci/config`), uses
    com.oracle.bmc.auth.ConfigFileAuthenticationDetailsProvider
- `resource-principal`  - use identity of the OCI resource the service is executed on
    (fn), uses
    com.oracle.bmc.auth.ResourcePrincipalAuthenticationDetailsProvider, and is available in a
    separate module `helidon-integrations-oci-authentication-resource`
- `instance-principal` - use identity of the OCI instance the service is running on, uses
    com.oracle.bmc.auth.InstancePrincipalsAuthenticationDetailsProvider, and is available in a
    separate module `helidon-integrations-oci-authentication-resource`
- `workload` - use workload identity of the OCI Kubernetes workload, available in a
    separate module `helidon-integrations-oci-authentication-workload`

The authentication method to apply
|`authentication-timeout` |Duration |`PT10S` |Timeout of authentication operations, where applicable.
This is a timeout for each operation (if there are retries, each timeout will be this duration).
Defaults to 10 seconds.

Authentication operation timeout
|`authentication.config` |xref:{rootdir}/config/io_helidon_integrations_oci_ConfigMethodConfig.adoc[ConfigMethodConfig] |{nbsp} |Config method configuration (if provided and used).

Information needed for config io.helidon.integrations.oci.OciConfig.authenticationMethod()
|`authentication.config-file` |xref:{rootdir}/config/io_helidon_integrations_oci_ConfigFileMethodConfig.adoc[ConfigFileMethodConfig] |{nbsp} |Config file method configuration (if provided and used).

Information to customize config for io.helidon.integrations.oci.OciConfig.authenticationMethod()
|`authentication.session-token` |xref:{rootdir}/config/io_helidon_integrations_oci_SessionTokenMethodConfig.adoc[SessionTokenMethodConfig] |{nbsp} |Session token method configuration (if provided and used).

Information to customize config for io.helidon.integrations.oci.OciConfig.authenticationMethod()
|`imds-base-uri` |URI |{nbsp} |The OCI IMDS URI (http URL pointing to the metadata service, if customization needed).

The OCI IMDS URI
|`imds-detect-retries` |int |{nbsp} |Customize the number of retries to contact IMDS service.

Number of retries, each provider has its own defaults
|`imds-timeout` |Duration |`PT1S` |The OCI IMDS connection timeout. This is used to auto-detect availability.

This configuration property is used when attempting to connect to the metadata service.

The OCI IMDS connection timeout
|`region` |Region |{nbsp} |Explicit region. The configured region will be used by region provider.
This may be ignored by authentication detail providers, as in most cases region is provided by them.

Explicit region

|===

// end::config[]