///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.security.providers.httpsign.SignedHeadersConfig.HeadersConfig
:keywords: helidon, config, io.helidon.security.providers.httpsign.SignedHeadersConfig.HeadersConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.security.providers.httpsign.SignedHeadersConfig.HeadersConfig
include::{rootdir}/includes/attributes.adoc[]

= HeadersConfig (security.providers.httpsign.SignedHeadersConfig) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.security.providers.httpsign.SignedHeadersConfig/io/helidon/security/providers/httpsign/SignedHeadersConfig/HeadersConfig.html[io.helidon.security.providers.httpsign.SignedHeadersConfig.HeadersConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`always` |string[&#93; |{nbsp} |Headers that must be signed (and signature validation or creation should fail if not signed or present)
|`if-present` |string[&#93; |{nbsp} |Headers that must be signed if present in request.
|`method` |string |{nbsp} |HTTP method this header configuration is bound to. If not present, it is considered default header configuration.

|===

// end::config[]