///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2025, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////
= OpenTelemetry Support in Helidon SE
:h1Prefix: SE
:description: Helidon SE Telemetry Support
:keywords: helidon, telemetry, tracing, observability
:feature-name: OpenTelemetry Support
:rootdir: {docdir}/../..
include::{rootdir}/includes/se.adoc[]
:version-doc-opentelemetry: v{version-lib-opentelemetry}
:semconv-link: https://github.com/open-telemetry/semantic-conventions/blob/{version-doc-opentelemetry}/docs/http/http-spans.md#http-server
:metrics-semconv-link: https://github.com/open-telemetry/semantic-conventions/blob/{version-doc-opentelemetry}/docs/http/http-metrics.md#http-server

:helidon-otelcfg-javadoc: {otel-config-javadoc-base-url}/io/helidon/telemetry/otelconfig/

== Contents

- <<Overview, Overview>>
- <<API, API>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Configuration, Configuration>>
* <<common-config, Common Settings>>
* <<tracing-config, Tracing>>
* <<metrics-config, Metrics>>
* <<logger-config, Logging>>
- <<Additional Information, Additional Information>>

== Overview
NOTE: Helidon SE support for OpenTelemetry configuration and semantic conventions as described below is currently a link:{javadoc-base-url}/io.helidon.common.features.api/io/helidon/common/features/api/Features.Preview.html[`@Features.Preview`] feature. We intend to support it going forward, but we might change its external API and behavior in backward-incompatible ways across dot releases.

Helidon SE supports OpenTelemetry in several important ways:

* Implements the xref:{rootdir}/se/tracing.adoc[neutral Helidon tracing API] using OpenTelemetry
* Allows users to assign OpenTelemetry settings as follows:
** Declaratively, using Helidon config under the top-level `telemetry` config key
** Programmatically, using the OpenTelemetry SDK API and the Helidon OpenTelemetry API

* Conforms to the link:{semconv-link}[OpenTelemetry semantic conventions] for automatically-created spans and metrics for HTTP requests
* Allows xref:{rootdir}/se/metrics/metrics.adoc#usage-publishing[publishing Helidon metrics] to backend systems using OTLP.

OpenTelemetry models observability as a set of link:https://opentelemetry.io/docs/concepts/signals/[_signals_]. Each signal--for example metrics, tracing, and logging--is an origin of monitoring data, and each has configurable settings which control its behavior.

Helidon's config support for OpenTelemetry has certain config attributes which apply to OpenTelemetry as a whole, others which pertain to individual signals, and still more which describe lower-level elements within a signal.

The Helidon OpenTelemetry configuration format, the Helidon OpenTelemetry API, and this documentation all follow this hierarchy:

* <<top-level-config, Top-level telemetry>>
** Signals
*** <<tracing-config, Tracing>>
*** <<metrics-config, Metrics>>
*** <<logger-config, Logging>>


This document describes how to configure each level in the hierarchy and covers general topics related to Helidon's support of OpenTelemetry.

== API
There are _two_ APIs that might be useful to developers working with OpenTelemetry:

* The Helidon OpenTelemetry API - useful for mapping configuration sources to Helidon builders and, ultimately, OpenTelemetry objects.
* The OpenTelemetry API - useful for creating OpenTelemetry objects apart from Helidon configuration sources.

The types in the Helidon OpenTelemetry API correspond closely to the configuration structures described in later sections of this document. Application code can use Helidon OpenTelemetry builders to prepare and construct each of the configurable entities to ultimately prepare an `OpenTelemetry` instance set up according to the application's needs.

That said, application code can equally well use the OpenTelemetry API and its builders to prepare the `OpenTelemetry` instance.

Applications could even use both APIs together, reading configuration to construct a Helidon builder and then adding to that builder OpenTelemetry objects created separately using the OpenTelemetry API.

The link:{helidon-otelcfg-javadoc}package-summary.html[Helidon OpenTelemetry API Javadoc] page lists the various types developers can use to prepare OpenTelemetry objects programmatically. As a starting point, the link:{helidon-otelcfg-javadoc}OpenTelemetryConfig.html[`OpenTelemetryConfig`] interface and its link:{helidon-otelcfg-javadoc}OpenTelemetryConfig.BuilderBase.html[`Builder`] represents the top-level configuration for OpenTelemetry. Their Javadoc contains links to other types that compose the top-level object, and so on.

Later sections in this document also describe the configuration settings available.

The link:https://opentelemetry.io/docs/languages/java/sdk/#sdk-components[OpenTelemetry SDK documentation] explains its API.

[NOTE]
Many applications do not need to use either the Helidon OpenTelemetry API or the OpenTelemetry API directly. They can instead rely completely on declarative Helidon configuration of OpenTelemetry.

=== Managing the Global `OpenTelemetry` Instance
Typically, an application uses the same `OpenTelemetry` instance throughout its execution. OpenTelemetry offers a global `OpenTelemetry` instance to make it easy for application code to set and obtain the global instance.

Similarly, the Helidon tracing API has a global `Tracer`.

In most cases, an application that prepares OpenTelemetry programmatically should initialize both of those by including code as shown in the following example.

[source,java]
.Setting the global `OpenTelemetry` and `Tracer` instances in Helidon
----
include::{sourcedir}/se/TelemetrySnippets.java[tags=snippet_1_imports;snippet_1, indent=0]
----

[[effects-of-setting-global]]
==== Assigning the Global Instance
Using Helidon to set the global `OpenTelemetry` instance has these effects:

* Assigns the instance as the OpenTelemetry global instance.
* Creates a Helidon `Tracer` using the OpenTelemetry instance and makes that the Helidon global `Tracer`.

NOTE: Helidon is deprecating its use of "global" Helidon objects in favor of retrieving the correct instance from the Helidon service registry. Applications should migrate toward using, for example, `Services.get(Tracer.class)` instead of `Tracer.global()`.


// Dependencies
== Maven Coordinates [[maven-coordinates]]

To enable various aspects of {feature-name}
add one or more of the following dependencies to your project's `pom.xml` (see
xref:{rootdir}/about/managing-dependencies.adoc[Managing Dependencies]).

=== Using the OpenTelemetry implementation of the Helidon Tracing API
Helidon offers an implementation of its xref:{rootdir}/se/tracing.adoc[ neutral tracing API] that uses OpenTelemetry. Add the following dependency to use OpenTelemetry for tracing.
[source,xml]
.Dependency to use the Helidon OpenTelemetry implementation of Helidon tracing
----
<dependency>
    <groupId>io.helidon.tracing.providers</groupId>
    <artifactId>helidon-tracing-providers-opentelemetry</artifactId>
    <scope>runtime</scope>
</dependency>

----

=== Adding OpenTelemetry Configuration and Builder Support
To allow deployers and end users to set up Helidon configuration to control OpenTelemetry behavior, add the following dependency.

[source,xml]
.Dependency to add Helidon OpenTelemetry config and programmatic builder support
----
<dependency>
    <groupId>io.helidon.telemetry</groupId>
    <artifactId>helidon-telemetry-opentelemetry-config</artifactId>
    <scope>runtime</scope> <!--1-->
</dependency>
----
<1> To use the Helidon OpenTelemetry API in your application code, remove this line or change it to `<scope>compile</scope>`.

=== Enabling Automatic Spans for HTTP Requests
Helidon's tracing observability support automatically creates a new tracing span for each HTTP request if your project includes the following dependency.

[source,xml]
.Dependency for automatic HTTP request tracing
----
<dependency>
    <groupId>io.helidon.webserver.observe</groupId>
    <artifactId>helidon-webserver-observe-tracing</artifactId>
    <scope>runtime</scope>
</dependency>
----

By default, when Helidon {flavor-uc} creates spans automatically for HTTP requests, it uses a set of rules--semantic conventions--for choosing the span name and adding tags to each span.

OpenTelemetry prescribes its own link:{semconv-link}[semantic conventions]. If you add the following dependency, Helidon follows the OpenTelemetry semantic conventions for spans instead of its own.

[source,xml]
.Dependency for Helidon support of the OpenTelemetry tracing semantic conventions
----
<dependency>
    <groupId>io.helidon.webserver.observe</groupId>
    <artifactId>helidon-webserver-observe-telemetry-tracing</artifactId>
    <scope>runtime</scope>
</dependency>
----

[[enabling-automatic-metrics-for-inbound-http]]
=== Enabling Automatic Metrics for Incoming HTTP Requests
Helidon's metrics observability support automatically registers and updates one or more meters (depending on configuration) and updates them accordingly as HTTP requests arrive.

[source,xml]
.Dependency for automatic HTTP request measurements
----
<dependency>
    <groupId>io.helidon.webserver.observe</groupId>
    <artifactId>helidon-webserver-observe-metrics</artifactId>
    <scope>runtime</scope>
</dependency>
----

OpenTelemetry prescribes its own link:{metrics-semconv-link}[semantic conventions] for metrics--their names and tha attributes (tags) they have. If you add the following dependency, Helidon registers and updates meters according to the OpenTelemetry metrics semantic conventions.

[source,xml]
.Dependency for Helidon support of the OpenTelemetry metrics semantic conventions for incoming HTTP requests
----
<dependency>
  <groupId>io.helidon.webserver.observe</groupId>
  <artifactId>helidon-webserver-observe-telemetry-metrics</artifactId>
  <scope>runtime</scope>
</dependency>
----

=== Enabling OpenTelemetry for Outgoing Helidon Webclient Traffic
Helidon supports the OpenTelemetry semantic conventions for outgoing traffic which uses the Helidon WebClient. See the xref:{rootdir}/se/webclient.adoc#_configuring_telemetry[Helidon WebClient documentation].

=== Specifying Additional OpenTelemetry Dependencies
Most applications need to declare other runtime dependencies on OpenTelemetry artifacts because the configuration specifies--or the application code uses--particular OpenTelemetry types packaged in other artifacts. For example, OpenTelemetry exporters are packaged individually or as related groups. See <<note-about-exporter-dependencies, this section below>> for some specific dependencies to consider adding for particular exporters.

These exporters transmit telemetry data using a different protocol. (See https://github.com/open-telemetry/opentelemetry-java/tree/{version-doc-opentelemetry}/exporters[this OpenTelemetry page].)


== Configuration
You can control almost all of OpenTelemetry's overall, tracing, metrics, and logger runtime behavior using Helidon configuration settings. Helidon constructs an `OpenTelemetry` object using the configuration. The resulting `OpenTelemetry` instance reflects these settings from the Helidon configuration:

* Settings that pertain to <<top-level-config,overall OpenTelemetry behavior>>, apart from a particular signal.
* An OpenTelemetry tracer provider based on <<tracing-config,tracing configuration>> in  `signals.tracing`.
* An OpenTelemetry meter provider based on <<metrics-config,metrics configuration>> in `signals.metrics`.
* An OpenTelemetry logger provider based on <<logger-config,logger configuration>> in `signals.logging`.

[[top-level-config]]
=== Controlling Overall OpenTelemetry Behavior
Several settings control the operation of OpenTelemetry as a whole, as shown in the next table.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_HelidonOpenTelemetry.adoc[tag=config,leveloffset=+2]

Notes:

* OpenTelemetry uses default propagators of `tracecontext` and `baggage`. (See the `otel.propagators` property in link:https://opentelemetry.io/docs/languages/java/configuration/#properties-general[this OpenTelemetry guide].)
* Setting `global` to `true` has the effect described in the <<effects-of-setting-global, section>> about global instances.

[[common-config]]
=== Common Configuration Across Signals
This section describes settings that apply to multiple signal types.

[[attributes-config]]
==== Assigning Attributes
Configured attributes are key/value pairs that OpenTelemetry attaches to each transmission of a signal. OpenTelemetry supports attributes of type `String`, `long`, `double`, and `boolean`. The Helidon configuration structure groups attributes by type so Helidon can indicate precisely to OpenTelemetry what type you intend for each attribute.

You can add attributes to the configuration for any of the signals under the signal's `attributes` section.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_TypedAttributes.adoc[tag=config,leveloffset=+3]

The following example shows attribute settings for the tracing signal.

[source,yaml]
.Example attribute settings
----
telemetry:
  service: my-helidon-service
  tracing:
    attributes:
      strings:
        attr1: 12
        attr5: "any old thing"
        attr7: something
      longs:
        attr2: 12
      doubles:
        attr3: 24.5
        attr6: 12
      booleans:
        attr4: true
----

[[exporters-and-processors]]
==== Configuring Exporters and Processors/Readers
OpenTelemetry transmits the telemetry data it gathers to a backend system--such as Grafana, Signoz, Prometheus, Jaeger, or others--where you can view and query the data. OpenTelemetry goes through these distinct steps to gather and send data:

. OpenTelemetry tracing and log record _processors_ and metrics _readers_ gather and process data observations.
. OpenTelemetry _exporters_ associated with each processor or reader then transmit_ the data to one or more targets. Targets are typically backend systems but can be local ones for debugging. Each processor or reader uses one or more exporters to transmit telemetry data.

The processor settings determine when and how often each uses its exporters to deliver data. Each exporter's settings prescribe where it should send the data, how to connect to a backend, etc.

===== Configuring Processors (and readers)
An OpenTelemetry span or log record processor or metric reader is one of the following types:

* simple - The processor sends each telemetry observation to its exporters for transmission as soon as it receives the observation.
* batch - The processor groups observations into batches and sends a batch at a time to its exporters for transmission.

In the table below only the `type` and `exporters` setting apply to `simple`  processors; the other settings are for batch processors.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_BatchProcessorConfig.adoc[tag=config,leveloffset=+3]

===== Configuring Exporters
Exporter objects in OpenTelemetry are specific to both _how_ they transmit telemetry data and _what_ signal they work with. Even so, many exporter settings are very similar across different signals. This section describes the behavior and configuration that is common among exporters. Refer to the sections below that describe each signal to see what additional exporter settings, if any, each signal adds.

Helidon configuration supports several of the most popular exporters, discussed below.

[[otlp-exporter-config]]
====== Setting Up OTLP Exporters

Most users choose an `Otlp` exporter which has two variations--one using gRPC and one using HTTP with protocol buffers--as indicated by the `protocol` setting.

.Common Configuration for OTLP exporters
include::{rootdir}/config/io_helidon_telemetry_otelconfig_OtlpExporterConfig.adoc[tag=config,leveloffset=+3]

.OpenTelemetry OTLP exporter defaults
[cols="1,4"]
|====
| Setting | OpenTelemetry default

| `compression` | `none`

| `endpoint`
| `grpc` protocol: http://localhost:4317

`http/proto` protocol: http://localhost:4318
| `protocol` | `grpc`
| `retry-policy` | none
| `timeout` | 10 seconds
|====


====== OTLP Retry Policy
You can control how each exporter retries if a transmission to a backend fails.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_RetryPolicyConfig.adoc[tag=config, leveloffset=+4]

OpenTelemetry also supports a Zipkin exporter which it has recently deprecated.

====== Zipkin Exporter
.Configuration for Zipkin exporters
include::{rootdir}/config/io_helidon_telemetry_otelconfig_ZipkinExporterConfig.adoc[tag=config,leveloffset=+3]

The link:https://opentelemetry.io/docs/languages/java/configuration/#properties-exporters[OpenTelemetry documentation] describes the defaults; see the "Properties for Zipkin span exporters" section there.

.OpenTelemetry defaults for Zipkin exporters
[cols="1,4"]
|====
| Setting | OpenTelemetry default value

| `compression` | `none`
| `encoder` | `JSON_V2`
| `endpoint` | http://localhost:9411/api/v2/spans
| `timeout` | 10 seconds
|====

OpenTelemetry provides other exporters, often used for debugging:

* `console`
+
Writes telemetry data at the `INFO` level using the  `java.util.logging.Logger` for `io.opentelemetry.exporter.logging.Logging\{signal}Expoerter`
* `logging-otlp`
+
Writes telemetry data in JSON format to the logger for the particular OpenTelemetry implementation class (e.g., `OtlpJsonLoggingMetricExporter`).

The `console` and `logging-otlp` have no configuration that is common across all signals.

[[note-about-exporter-dependencies]]
[NOTE]
You need to add dependencies to your project for the exporters your application uses, even ones supported by Helidon config.

The table below describes the exporter types that Helidon configuration supports and what dependency your project needs to support them.

If you need to use an exporter that is _not_ in the table:

* Add a dependency on the OpenTelemetry artifact that contains that exporter type.
* Add application code that prepares the exporter instance.
* Prepare the Helidon OpenTelemetry builders programmatically and add your exporter instance to the builder.

In the table below, the Maven artifacts are all in the `io.opentelemetry` group.

[cols="1,2,5a"]
|===
| Exporter type | OpenTelemetry Java Type | Artifact ID to add - ``see ``also the link:https://opentelemetry.io/docs/languages/java/sdk/#spanexporter[OpenTelemetry documentation]

.2+| <<otlp-exporter-config,`otlp`>> +
(see `protocol` setting below)
| `OtlpGrpc\{signal}Exporter`
.2+|
`opentelemetry-exporter-otlp`
|`OtlpHttp\{signal}Exporter`
|xref:{rootdir}/config/io_helidon_telemetry_otelconfig_ZipkinExporterConfig.adoc[`zipkin`] | `ZipkinSpanExporter` a|
`opentelemetry-exporter-zipkin`
| `console` | `Logging\{signal}Exporter`
.3+|
`opentelemetry-exporter-logging`
| `logging_otlp` | `OtlpJsonLogging\{signal}Exporter`

`SystemOutLogRecordExporeter`
|===


// ====
===== Associating Each Processor and Reader with its Exporters
In configuration, you link processors and readers with the exporters you want each to use as follows:

* For clarity, name each exporter if you have more than one.
* Optionally specify for each processor or reader the names of the exporters it should use.
+
If you omit the exporter names for a processor or reader, Helidon associates it with all configured exporters. If you configure no exporters explicitly, Helidon associates the OpenTelemetry default exporter with the processor or reader.

The following examples show increasingly-complicated scenarios using tracing as the signal:

* Default
* Minimal configuration
* Maximum flexibility

For many applications the default and minimal scenarios work well.

===== Default
This scenario includes no configuration at all for either processors or exporters.

OpenTelemetry uses its default processor (`batch`) with its default exporter (`otlp` using `grpc`). |
[source,yaml]
----
telemetry:
  service: "inventory"
  tracing:
    sampler: "always_off"
----

===== Minimal configuration
The user configures at most one processor and at most one exporter.

The single processor uses the single exporter.

No exporter name is declared or referenced.

[source,yaml]
----
telemetry:
  service: "inventory"
  tracing:
    sampler: "always_off"
    exporters:
      - type: zipkin
        compression: gzip
    processors:
      - type: batch
        max-queue-size: 50

----

===== Maximum flexibility
The user configures possibly multiple processors and possibly multiple named exporters. Each processor's configuration lists the names of the exporters it should use; no names means all exporters.

The first processor (type `batch`) uses both exporters because it does not specify any exporter names. The second processor uses only the `alternate-otlp` exporter.|

[source,yaml]
----
telemetry:
  service: "inventory"
  tracing:
    sampler: "always_off"
    exporters:
      - type: zipkin
        compression: gzip
        name: "compressed-zipkin"
      - endpoint: "http://collect.com:4317"
        name: "alternate-otlp""
    processors:
      - type: batch
        max-queue-size: 50
      - type: simple
        exporters: ["alternate-otlp"]
----

// Following horizontal line separates the nested "common config" section from the upcoming major section about configuring tracing. Otherwise it's a little hard to tell on our rendered page that we're starting a new major topic.
'''

[[tracing-config]]
=== Controlling OpenTelemetry Tracing Behavior
The settings under `signals.tracing` prepare an OpenTelemetry `TracerProvider`. When your application uses the Helidon tracing API to obtain a `Tracer`, Helidon uses the `TracerProvider` prepared from this config to create the tracer.

The next table describes the OpenTelemetry tracing settings.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_OpenTelemetryTracingConfig.adoc[tag=config,leveloffset=+2]

OpenTelemetry applies the defaults described in the next table.

.Default tracing settings applied by OpenTelemetry
[cols="1,4"]
|===
| Setting | OpenTelemetry default (and OpenTelemetry doc link)

| `exporters` | link:https://opentelemetry.io/docs/languages/java/configuration/#properties-exporters[`otlp` with `grpc` protocol] - see "Properties: exporters, `otel.traces.exporter` property"
| `processors` | link:https://opentelemetry.io/docs/languages/java/configuration/#properties-traces[`batch` with defaults] - see "Properties for batch span processor(s)"
| `sampler` | link:https://opentelemetry.io/docs/languages/java/configuration/#properties-traces[`parentbased_always_on`] - see "Properties for sampler"

| `span-limits`
| See link:https://opentelemetry.io/docs/languages/java/configuration/#properties-traces[tracing] "Properties for span limits"
|===

Refer to the earlier sections about <<attributes-config,configuring attributes>> and <<exporters-and-processors,configuring processors and exporters>>.

Sections below describe how to set up the tracing signal configuration:

- <<span-sampler-config, Configuring the Span Sampler>>
- <<span-limits-config, Configuring the Span Limits>>

[[span-sampler-config]]
==== Configuring the Span Sampler
OpenTelemetry offers different ways of sampling data--deciding which tracing spans tp capture and send to the backend. The link:https://opentelemetry.io/docs/languages/java/sdk/#sampler[OpenTelemetry documentation] describes sampling in more detail.

Helidon configuration supports the sampler implementations that reside in the `opentelemetry-sdk` as listed in the table below. Other samplers are in other components. If you need to use one of those:

* Add the relevant OpenTelemetry dependency to your project.
* Instantiate the span sample you need.
* Prepare the sampler and the  OpenTelemetry-related builders programmatically and use your sampler to assign the sampler the `OpenTelemetryTracer.Builder` should use.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_SamplerConfig.adoc[tag=config,leveloffset=+2]

[[span-limits-config]]
==== Configuring Span Limits
OpenTelemetry allows you to constrain certain aspects of the data it gathers in tracing spans. By assigning the settings in the table below, you can apply the span limits you want.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_SpanLimitsConfig.adoc[tag=config,leveloffset=+2]

The link:https://opentelemetry.io/docs/languages/java/sdk/#sampler[OpenTelemetry documentation] describes the defaults; see the "Properties for span limits" section there.

.OpenTelemetry defaults for span limits
[cols="1,4"]
|====
| Setting | OpenTelemetry Default

| `max-attribute-value-length` | no limit
| `max-attributes` | 128
| `max-attributes-per-event` | 128
| `max-events` | 128
| `max-links` | 128
|====


[[metrics-config]]
=== Controlling OpenTelemetry Metrics Behavior
The settings under `signals.metrics` prepare an OpenTelemetry `MeterProvider`. If your code uses the OpenTelemetry API to obtain an OpenTelemetry meter, meter provider, or meter builder, OpenTelemetry uses the `MeterProvider` prepared from this configuration.

The sections below describe Helidon config settings that correspond very directly to OpenTelemetry builders for the relevant OpenTelemetry type. Refer to the relevant OpenTelemetry documentation or Javadoc to understand the effect each setting has.

See the earlier sections about <<attributes-config,configuring attributes>> and <<exporters-and-processors,configuring processors and exporters>>. A <<metric-exporters-config,later section below>> describes some additional attributes on metrics exporters.

The next table describes the OpenTelemetry metrics settings.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_OpenTelemetryMetricsConfig.adoc[tag=config,leveloffset=+2]

OpenTelemetry applies the defaults described in the next table.

.Default metric settings applied by OpenTelemetry
[cols="1,4"]
|===
| Setting | OpenTelemetry default (and OpenTelemetry doc link)

| `exporters` | link:https://opentelemetry.io/docs/languages/java/configuration/#properties-exporters[`otlp` with `grpc` protocol] - see that web page's "Properties: exporters, `otel.metrics.exporter` property"] section.
| `readers` | link:https://opentelemetry.io/docs/languages/java/configuration/#properties-metrics[`PeriodicMetricReader`] with an interval of one minute
|===

Sections below describe how to set up the configuration that is specific to the metrics signal:

- <<metric-exporters-config, Configuring Metric Exporters>>
- <<metric-readers-config, Configuring Metric Readers>>
- <<metric-views-config, Configuring Metric Views>>

The following example illustrates some of the ways you can configure OpenTelemetry metrics behavior. It is neither complete nor typical.

.Example OpenTelemetry Metrics Configuration
[source,yaml]
----
telemetry:
  service: "test-telemetry"
  signals:
    metrics:                                          # <1>
      exporters:
        - name: exp-1                                 # <2>
          type: otlp
          endpoint: "http://host:1234"
          temporality-preference: cumulative          # <3>
          default-histogram-aggregation:              # <4>
            type: base2-exponential-bucket-histogram
            max-buckets: 152
            max-scale: 19
        - name: exp-2                                 # <5>
          type: otlp
          protocol: grpc
          temporality-preference: delta               # <6>
          default-histogram-aggregation:              # <7>
            type: explicit-bucket-histogram
            bucket-boundaries: [3,5,7]
      readers:
        - type: periodic                              # <8>
          exporter: exp-1
          interval: PT6S
      views:
        - name: sum-view                              # <9>
          aggregation:
            type: sum
          description: "Sum view"
          instrument-selector:
            name: counter-selector
            type: counter
            meter-name: my-counter

----
<1> Introduces the metrics configuration.
<2> Introduces the first metric exporter (with name `exp-1`).
<3> Indicates to accumulate measurement values since the previous transmission.
<4> Prescribes to aggregate histograms for transmission using the OpenTelemetry `BASE2_EXPONENTIAL_BUCKET_HISTOGRAM` technique with the specified maximum number of buckets and maximum scale.
<5> Introduces the second metric exporter (with name `exp-2`).
<6> Indicates to transmit deltas since the last transmission.
<7> Prescribes to aggregate histograms using a histogram with the given explicit bucket boundary values.
<8> Declares a single metric reader of the OpenTelemetry `PERIODIC` types gathering data each 6 seconds.
<9> Declares a single view to influence influence the transmission of the `my-counter` counter data.


[[metric-exporters-config]]
==== Metric Exporters
The configuration for metrics exporters has several additional settings beyond those described earlier for exporters in general.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_MetricExporterConfig.adoc[tag=config,leveloffset=+2]

===== Metric Aggregation
OpenTelemetry allows control over how each exporter aggregates histogram data prior to transmission to a backend.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_MetricDefaultHistogramAggregationConfig.adoc[tag=config, leveloffset=+2]

You can configure the explicit bucket boundaries for `EXPLICIT_BUCKET_HISTOGRAM` aggregation.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_ExplicitBucketHistogramAggregationConfig.adoc[tag=config, leveloffset=+2]

You can configure the exponential histogram aggregation behavior.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_Base2ExponentialHistogramAggregationConfig.adoc[tag=config, leveloffset=+2]


[[metric-readers-config]]
==== Metric Readers
An OpenTelemetry metric reader collects metric data in the server and then uses the associated metric exporter to send that data to the endpoint configured.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_MetricReaderConfig.adoc[tag=config,leveloffset=+2]

The periodic reader supports the following settings.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_PeriodicMetricReaderConfig.adoc[tag=config,leveloffset=+2]

[[metric-views-config]]
==== Metric Views
OpenTelemetry metric views allow you to influence how meters are aggregated for reporting to backend systems.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_ViewRegistrationConfig.adoc[tag=config,leveloffset=+2]

The instrument selector controls which meters this view reflects.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_InstrumentSelectorConfig.adoc[tag=config, leveloffset=+2]

[[logger-config]]
=== Controlling OpenTelemetry Logger Behavior
The settings under `signal.logging` prepare an OpenTelemetry `LoggerProvider.

The sections below describe Helidon config settings that correspond directly to OpenTelemetry builders for the relevant OpenTelemetry type. Refer to the relevant OpenTelemetry documentation or Javadoc to understand the effect each setting has.

The next table describes the OpenTelemetry logging settings.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_OpenTelemetryLoggingConfig.adoc[tag=config,leveloffset=+2]

OpenTelemetry uses the following defaults:

.Default logging settings applied by OpenTelemetry
[cols="1,4"]
|===
| Setting | OpenTelemetry default

| `exporters` | none
| `minimum-severity` | undefined severity number
| `processors` | no-op processor
| `trace-based` | `false`
|===


Refer to the earlier sections about <<attributes-config,configuring attributes>> and <<exporters-and-processors,configuring processors and exporters>>.

Sections below explain how to set up the configuration that is specific to the logging signal:

- <<configuring-log-limits, Configuring Log Limits>>



[[configuring-log-limits]]
==== Configuring Log Limits

For defaults, Helidon defers to the OpenTelemetry defaults, listed below.

include::{rootdir}/config/io_helidon_telemetry_otelconfig_LogLimitsConfig.adoc[tag=config,leveloffset=+3]

OpenTelemetry applies the following defaults:

.Default log limit settings applied by OpenTelemetry
[cols="1,4"]
|===
| Setting | OpenTelemetry default

| `max-attribute-value-length` | `Integer.MAX_VALUE`
| `max-number-of-attributes` | 128
| `exporters` | link:https://opentelemetry.io/docs/languages/java/configuration/#properties-exporters[`otlp` with `grpc` protocol] - see that web page's "Properties: exporters, `otel.logger.exporter` property" section.
| `log-limits` | `max-
| `processors` | https://opentelemetry.io/docs/languages/java/configuration/#properties-logs[`otlp`] - see that web page's "Properties: logs" section.
|===

The following example illustrates some of the ways you can configure OpenTelemetry logger behavior. It is neither complete nor typical.

.Example OpenTelemetry Logger Configuration
[source,yaml]
----
telemetry:
  service: test-tel-logging
  global: false
  signals:
    logging:                              # <1>
      minimum-severity: TRACE             # <2>
      log-limits:                         # <3>
        max-attribute-value-length: 20
        max-number-of-attributes: 14
      processors:                         # <4>
        - type: batch
          schedule-delay: PT10S
          max-queue-size: 15
          max-export-batch-size: 5
          timeout: PT30S
        - type: simple
      exporters:                          # <5>
        - name: exp-1
          endpoint: "http://host:1234"
----
<1> Introduces the logger configuration.
<2> Sets the minimum log level severity to of log messages to send to the backend system.
<3> Configures limits related to attributes that accompany log messages.
<4> Prescribes the logger processors.
<5> Prescribes the logger exporters.

[[logger-exporters-and-readers]]
==== Logger Exporters and Processors
You associate each logger processor with a logger exporter using the exporter's name.
See the <<exporters-and-processors,earlier section>> for more information.


== Additional Information

=== Helidon Documentation

* xref:{rootdir}/se/tracing.adoc[Helidon Tracing]

=== OpenTelemetry Documentation

* link:https://opentelemetry.io/docs/languages/java/configuration/#properties-exporters[Settings and defaults]
* link:https://opentelemetry.io/docs/languages/java/sdk[OpenTelemetry Java SDK reference]
* link:{semconv-link}[HTTP semantic conventions]
* link:https://opentelemetry.io/docs/languages/java/intro/[Intro to OpenTelemetry Java]
