///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/../..]
:description: Helidon Security Java Serialization (JEP-290)
:keywords: helidon, security, serialization, java, JEP-290
:metainf: META-INF/helidon/serial-config.properties

= JEP-290

== Contents

- <<Overview, Overview>>
- <<Deserialization Setup, Deserialization Setup>>
- <<System Property Configuration, System Property Configuration>>
- <<Programmatic Configuration, Programmatic Configuration>>
- <<JEP-290 Pattern Syntax, JEP-290 Pattern Syntax>>
- <<Troubleshooting, Troubleshooting>>

== Overview

link:https://openjdk.org/jeps/290[JEP-290] brought support for deserialization filters to Java programming language. Such filtering allows you to control the classes that need to be deserialized using Java serialization.

== Deserialization Setup

Helidon default settings forbid any deserialization except for patterns defined in a `pattern`
property of any `{metainf}` on classpath. The patterns are semicolon delimited strings such as `io.myapp.&#42;&#42;;java.util.HashMap` (any subpackage of `io.myapp` and class `java.util.HashMap`).
Helidon will *always* add a deny-all filter pattern to the end of the pattern string (to ensure we exclude any unspecified class - we only operate on whitelists)

These defaults can be modified either through system properties or programmatically.

== System Property Configuration
The following system properties can be used to control deserialization in Helidon:

.System Properties
[cols="3,3,5a"]

|===
|property |default value |description

|`helidon.serialFilter.pattern` |`!&#42;` |Filter pattern to use, deny all is always added
|`helidon.serialFilter.ignoreFiles` |`false` |Whether to ignore files `{metainf}` in libraries on the classpath
|`helidon.serialFilter.failure.action` |`FAIL` |Action to do when the configuration of global filter exists and is not consistent with security expectations (for example, contains a pattern to include all)

Options:

- `FAIL` - Throw an exception to terminate startup.
- `WARN` - Log a warning.
- `IGNORE` - Ignore this and continue silently.

|`helidon.serialFilter.missing.action` |`CONFIGURE` |Action to do when there is no global configuration.

Options:

- `CONFIGURE` - Configure the Helidon defaults.
- `FAIL` - Throw an exception to terminate startup.
- `WARN` - Log a warning.
- `IGNORE` - Ignore this and continue silently.

|`helidon.serialFilter.trace` |`NONE` |Tracing configuration for deserialization. Controls what information (if any) will be logged to a logger `io.helidon.common.SerializationConfig.TracingObjectInputFilter` in `INFO` log level.

Options:

- `NONE` - Do not trace.
- `BASIC` - Trace only classes, and only once per class.
- `FULL` - Trace all deserialization filter requests.

|===

== Programmatic Configuration

Custom `SerializationConfig` may be registered, but it *must* be done before Helidon server is started.

[source,java]
.Configure Custom Helidon Serialization Config
----
SerializationConfig.builder()
  .traceSerialization(SerializationConfig.TraceOption.BASIC) <1>
  .filterPattern(MyType.class.getName())                     <2>
  .ignoreFiles(true)                                         <3>
  .onWrongConfig(SerializationConfig.Action.IGNORE)          <4>
  .build()
  .configure();                                              <5>
----
<1> Trace first instance of each class that is deserialized.
<2> Configure a single class filter pattern (allows only deserialization of class `MyType`).
<3> Ignore files defined in {metainf}.
<4> In case there is an existing global serialization configuration on JDK, ignore it and continue (global filter cannot be reconfigured).
<5> Configure this serialization config as the default for this JVM.

== JEP-290 Pattern Syntax
Serialization patterns are fully qualified class names or package names with wildcards delimited with semicolon`;`

.Pattern Syntax
- Package name ending with `.*` - All classes in the package.
- Package name ending with `.**` - All classes in the package and subpackages.
- FQDN ending with `*` - Standard wildcard, matches all classes with the prefix.
- FQDN matches exact class
- Patterns starting with `!` - NOT, rejects pattern if matched.
- `<MODULE_NAME>/<FQDN>` - When pattern contains `/`, name before it marks the module name.


[source, shell]
.Example of `META-INF/helidon/serial-config.properties` Content
----
pattern=java.util.**;!java.util.ArrayList;my.package.*
----

[source, shell]
.Example of Pattern Supplied as a System Property
----
java -Dhelidon.serialFilter.pattern="java.util.**;!java.util.ArrayList;my.package.*" -jar my-app.jar
----

== Troubleshooting
The Helidon serialization config filter doesn't trace the actual rejected classes by default.
The logs will show only `InvalidClassException` with the message `filter status: REJECTED`.

[code, java]
.Default Reject Message
----
java.io.InvalidClassException: filter status: REJECTED
----

To find out which class has been actually rejected, set the `helidon.serialFilter.trace` system property to either `basic` or `full`.

[code, shell]
.Running Helidon Application in Basic Trace Mode
----
java -Dhelidon.serialFilter.trace=basic -jar ./target/custom-mp.jar
----

Each accepted or rejected class is logged only once with the `basic` trace filter setting.

[code, shell]
.Logs With Basic Filter Trace
----
...
ALLOWED class: class java.util.LinkedList, arrayLength: -1, depth: 2, references: 3, streamBytes: 84
REJECTED class: class java.util.ArrayList, arrayLength: -1, depth: 2, references: 3, streamBytes: 90
----

You can compose proper serialization filter pattern with the list of REJECTED classes.
