///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]

// tag::overview[]
The link:{openapi-spec-url}[OpenAPI specification] defines a standard way to express the interface exposed by a REST service.

OpenAPI support in Helidon {flavor-uc} focuses on serving a static OpenAPI document and exposing it via the `/openapi` endpoint.

The OpenAPI support in Helidon {flavor-uc} performs
two main tasks:

* Build an in-memory model of the REST API your service implements.
* Expose the model in text format (YAML or JSON) via the `/openapi` endpoint.

:static-source-info: a static OpenAPI document file packaged as part of your service

To construct the model, Helidon gathers information about the service API from
{static-source-info}.


// end::overview[]

// tag::furnish-openapi-info[]

==== Furnish OpenAPI information about your endpoints
// It's a bit odd to intermix the SE and MP content in this common file this way.
// But I tried having a level 3 section in the SE file include a sequence of
// level 4 sections from here, and that led to errors with headers being out of sequence.
// With the entire level 3 section here and conditional text for SE and MP, AsciiDoctor is happy.
ifdef::se-flavor[]
Your application supplies data for the OpenAPI model using a static OpenAPI file.
endif::[]

ifdef::se-flavor[]
===== Provide a static OpenAPI file
Add a static file at `META-INF/openapi.yml`, `META-INF/openapi.yaml`,
or `META-INF/openapi.json`. Tools such as Swagger let you describe your app's API
and they then generate an OpenAPI document file which you can include in your application
so OpenAPI can use it.

endif::se-flavor[]
// end::furnish-openapi-info[]

// tag::usage-access-endpoint[]
=== Accessing the REST Endpoint
Once you have added the {flavor-uc} OpenAPI dependency to your
ifdef::se-flavor[project, if you are using auto-discovery--or if you are not using auto-discovery and you have added code to register the `OpenApiFeature` object with your routing--then ]
your application responds to the built-in endpoint --
`/openapi` -- and returns the OpenAPI document describing the endpoints
in your application.

The
default format of the OpenAPI document is YAML.
There is not yet an adopted IANA YAML media type, but a proposed one specifically
for OpenAPI documents that has some support is `application/vnd.oai.openapi`.
That is what Helidon returns by default.

In addition, a client can specify the HTTP header `Accept` as either `application/vnd.oai.openapi+json` or
`application/json` to request JSON. Alternatively, the client can pass the query parameter `format` as either `JSON`
or `YAML` to receive `application/json` or `application/vnd.oai.openapi` (YAML) output, respectively.
// end::usage-access-endpoint[]
