///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:toc:
:toc-placement: preamble
:description: Reactive Streams support in Helidon
:keywords: helidon, se, microprofile, reactivestreams
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

== Reactive Streams

[PILLARS]
====
[CARD]
.Helidon Reactive Engine
[icon=fa-cogs,link=engine.adoc]
--
A set of reactive operators.
--

[CARD]
.MicroProfile Reactive Streams Operators
[icon=fa-book,link=rsoperators.adoc]
--
Microprofile implementation.
--
====

There are two handy apis for working with reactive streams available in Helidon,
one for working with `java.util.concurrent.Flow`
and second for `org.reactivestreams` based reactive components.