///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= LangChain4J
:description:  LangChain4J Integration
:keywords: Helidon, AI, LangChain4J, LC4J
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

== LangChain4J Support

Helidon SE includes native xref:{rootdir}/se/integrations/langchain4j/langchain4j.adoc[LangChain4J integration], which can also be used in Helidon MP thanks to *Helidon Inject to CDI bridge*. Refer to its xref:{rootdir}/se/integrations/langchain4j/langchain4j.adoc[documentation] for more details.