///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////


= Oracle Cloud Infrastructure
:description: Helidon OCI Integration
:keywords: oci, cdi, Oracle Cloud Infrastructure
:feature-name: OCI Integration
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

== Contents

- <<Overview, Overview>>
- <<maven-coordinates, Maven Coordinates>>
- <<_accessing_oci_services, Accessing OCI Services>>
- <<References, References>>

== Overview

You can quickly and easily deploy Helidon applications on Oracle Cloud Infrastructure (OCI) and integrate them with OCI services using the OCI Java SDK and the Helidon OCI SDK Extension.

link:{oci-javasdk-url}[The Oracle Cloud Infrastructure SDK for Java] enables you to write code to manage Oracle Cloud Infrastructure resources. The Helidon OCI SDK link:{jakarta-cdi-spec-url}#spi[CDI portable extension] provides support for
injecting link:{oci-javasdk-url}[Oracle Cloud Infrastructure SDK Clients] into your Helidon applications.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
.Adding the Helidon OCI SDK Extension dependency
----
<dependency>
     <groupId>io.helidon.integrations.oci.sdk</groupId>
     <artifactId>helidon-integrations-oci-sdk-cdi</artifactId>
</dependency>
----

NOTE: If your Helidon application is based on the xref:../guides/oci-guide.adoc[Helidon MP OCI project starter], many of the following dependencies are already included and you do not need to add them.

== Authentication

You must configure authentication between your local environment and the OCI environment. It is recommended that you configure authentication first and then verify your configuration by using the link:{oci-javasdk-url}[OCI CLI] to access the service.

The Helidon OCI SDK extension authenticates with OCI by picking up OCI credentials from your environment.

To configure authentication, add the ``oci.auth-strategies`` property to ``/server/src/main/resources/META-INF/microprofile-config.properties``

The ``oci.auth-strategies`` property specifies the OCI client authentication mechanism that should be used. It can be a single value or a list of authentication types, separated by commas. If you specify a list, it cycles through each type until the authentication is successful.

[source,properties]
.oci.auth-strategies example
----
oci.auth-strategies=config-file,instance_principals,resource_principal
----

OCI supports the following client authentication methods:

* ``auto`` (default value): Cycles through all of the authentication types until one succeeds. By default, this value is set to ``config_file,instance_principals,resource_principal``.
* ``config_file``: Uses the user authentication specified in `~/.oci/config`.
* ``config``: Uses the user authentication specified in the Helidon `microprofile-config.properties` file.
* ``instance_principals``: Uses the OCI Compute instance as the authentication and authorization principal. See link:{oci-doc-url}/Content/Identity/Tasks/callingservicesfrominstances.htm[Calling Services from an Instance].
* ``resource_principal``: Uses OCI resources and services as the authentication and authorization principal, such as serverless functions. This option is similar to the `instance_principals` authentication type. See https://docs.oracle.com/en/cloud/paas/autonomous-database/serverless/adbsb/resource-principal.html[About Using Resource Principal to Access Oracle Cloud Infrastructure Resources].

If your environment is already set up to work with the OCI SDK or
the OCI CLI, then it is likely you do not need to perform any additional configuration of the extension. When the extension is added as a dependency, it will self-configure.

When you inject an OCI SDK Client object, the Helidon OCI SDK extension
configures and constructs the object for you. The configuration primarily
consists of initializing an OCI `AuthenticationDetailsProvider`. By default, the extension examines your environment and selects the best
`AuthenticationDetailsProvider` and configures it for you.

If you require greater control over the OCI configuration, see 
link:{integration-oci-sdk-cdi-javadoc-base-url}/io/helidon/integrations/oci/sdk/cdi/OciExtension.html[OciExtension]
in the Helidon Javadocs for more information concerning the extension and its configuration
and authentication options. In particular, the `oci.auth-strategies` property lets you control which
`AuthenticationDetailsProvider` will be used.

== Accessing OCI Services

The Helidon OCI SDK extension supports injecting the client for any link:{oci-javasdk-url}#Services_Supported[OCI service supported by the OCI SDK for Java].

After adding the Helidon OCI SDK Extension dependency (as described above), you must add dependencies for each of the specific OCI SDK clients that you plan to use.

NOTE: Each time that you update your application to integrate to an OCI service, you must build and redeploy the application to enable the OCI service's features.

Here are some common OCI services and how to use them with your Helidon application.

- <<Monitoring, Monitoring>>
- <<Logging, Logging>>
- <<Tracing, Tracing>>
- <<Streaming, Streaming>>
- <<_object_storage, Object Storage>>

=== Monitoring

The OCI Monitoring services allows you to actively and passively monitor cloud resources using the Metrics and Alarms features.

Use OCI Monitoring with your Helidon application to amass an abundance of valuable server and application insight and place it directly into OCI Monitoring where it can be analyzed as needed. For an overview of OCI Monitoring features, see link:{oci-doc-url}/Content/Monitoring/Concepts/monitoringoverview.htm[Monitoring] in OCI documentation.

To enable OCI Monitoring integration, add the following dependency to your project's ``pom.xml``:

[source,xml]
.Adding the dependency for OCI Monitoring
----
<dependency>
  <groupId>io.helidon.oci.integrations</groupId>
  <artifactId>helidon-oci-integrations-metrics</artifactId>
</dependency>
----

Next, update ``/server/src/main/resources/application.yaml`` so the application sends Helidon generated metrics to the OCI monitoring services:

[source,yaml]
.Adding OCI metrics configuration details
----
ocimetrics:
  compartmentId: compartmentocid1234 # <1>
  namespace: helidon_pegasus # <2>
----
<1> The OCI compartment ID where the metrics will be sent.
<2> The OCI metrics namespace.

You can also update these optional values:

[source,yaml]
----
ocimetrics:
  initialDelay: 30 # <1>
  delay: 180 # <2>
  scopes: [base, vendor, application] # <3>
  enabled: true # <4>
----
<1> The delay (in seconds) before the first metrics transmission to OCI takes place. Default is 1 second.
<2> The interval (in seconds) between metrics transmission to OCI. Default is 60 seconds.
<3> Filter only the scopes that will be sent to OCI. This is optional. Default is all scopes.
<4> Enable or disable metrics transmission to OCI. Default is true.

Then, add the following configuration to ``/server/src/main/resources/META-INF/microprofile-config.properties``, modifying its values for your specific project:

[source,properties]
.Defining properties for OCI metrics
----
oci.monitoring.compartmentId=cmpt-ocid <1>
oci.monitoring.namespace=helidon_pegasus <2>
----
<1> The OCI compartment ID where the metrics will be sent.
<2> The OCI metrics namespace.

The next time that you launch the application, it will report metrics to OCI monitoring. Let the application run for short while to generate data, then go to the Metrics Explorer in the OCI console to view the monitoring data.

=== Logging

The OCI Logging service is a highly scalable and fully managed single pane of glass for all of the logs in your tenancy. For an overview of the OCI Logging feature, see link:{oci-doc-url}/Content/Logging/Concepts/loggingoverview.htm[Logging Overview] in OCI documentation.

Helidon uses the link:{oci-doc-url}/Content/Logging/Concepts/custom_logs.htm[custom logs] feature of OCI Logging for integration. The ability to add custom logs from any OCI Compute instance makes it more flexible to use this feature with other components such as Oracle Kubernetes Engine (OKE).

To enable OCI Logging integration, start by creating a log _group_. Log groups are logical containers for organizing logs. Logs must always be inside log groups. See
link:{oci-doc-url}/Content/Logging/Task/create-logging-log-group.htm[Create a Log Group] in OCI documentation.

Next, create a custom log object and its associated agent configuration. See link:{oci-doc-url}/Content/Logging/Task/create-logging-log.htm[Creating a Log] in OCI documentation.

Then, in ``/server/src/main/resources/META-INF/microprofile-config.properties``, add the following property:

[source,properties]
.Defining MP properties for OCI logging
----
oci.logging.id=oci-custom-log-id # <1>
----
<1> The OCID of the custom log for the Logging service.

Finally, configure Helidon logging to persist its log data to a file that the link:{oci-doc-url}/Content/Logging/Concepts/agent_management.htm[Unified Monitoring Agent] can access and process. For example, in the ``/server/src/main/resources/logging.properties`` file, add:

[source,properties]
.Defining properties for OCI logging
----
handlers=io.helidon.logging.ConsoleHandler,
java.util.logging.FileHandler
java.util.logging.FileHandler.pattern=%h/helidon_log/helidon.log
java.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter
----

After you configure OCI logging and launch the application, it will start reporting logs to OCI Logging. Logs are indexed in the system, and searchable through the OCI Console, API, and CLI. You can filter, aggregate, and visualize your logs. For more information, see https://docs.oracle.com/en-us/iaas/Content/Logging/Concepts/searchinglogs.htm[Logging Search] in OCI documentation.

You can also manually push logs to the custom log configuration. First, add the following dependency to the project's ``pom.xml`` file:

[source,xml]
.Adding the dependency for Logging Ingestion API (to manually push logs)
----
<dependency>
  <groupId>com.oracle.oci.sdk</groupId>
  <artifactId>oci-java-sdk-loggingingestion</artifactId>
</dependency>
----

Then, find the https://docs.oracle.com/en-us/iaas/Content/GSG/Tasks/contactingsupport_topic-Locating_Oracle_Cloud_Infrastructure_IDs.htm#resource-ocid[Oracle Cloud Identifier (OCID)] of the custom log configuration and use that OCID with the https://docs.oracle.com/en-us/iaas/api/#/en/logging-dataplane/20200831/[Logging Ingestion API] from the OCI SDK. See https://docs.oracle.com/en-us/iaas/Content/Logging/Concepts/using_the_api_customlogs.htm#using_the_api_customlogs[Ingesting Custom Logs] in OCI documentation.

=== Tracing

The OCI Application Performance Monitoring (APM) service provides deep visibility into the performance of applications and provides the ability to diagnose issues quickly in order to deliver a consistent level of service. See link:{oci-doc-url}/application-performance-monitoring/doc/application-performance-monitoring.html[About APM] in OCI documentation.

Use OCI APM with Helidon to trace requests from start to finish, allowing you to analyze requests across your distributed services and thereby obtain a complete picture to identify bottlenecks and issues early on.

To enable OCI Tracing integration, start by creating an APM Domain, an OCI resource that contains the systems being monitored by APM. See link:{oci-doc-url}/application-performance-monitoring/doc/create-apm-domain.html#GUID-ABC79A90-3940-4360-9E21-57D25B86F92B[Create an APM Domain] in OCI documentation.

Make sure that you record the *Data Upload Endpoint* and *Data Keys* for the APM domain - you will need them to configure the APM Java Tracer on the application. If you need to find them again, follow the steps at link:{oci-doc-url}/application-performance-monitoring/doc/obtain-data-upload-endpoint-and-data-keys.html[Obtain Data Upload Endpoint and Data Keys] in OCI documentation.

Next, configure the APM Java Tracer to use with Helidon. The APM Java Tracer (or just APM Tracer) is an APM data source that gathers and uploads data such as metrics and spans for monitoring. See link:{oci-doc-url}/application-performance-monitoring/doc/use-apm-tracer-helidon.html[Use APM Tracer in Helidon] in OCI documentation.

After you configure OCI APM with Helidon, you can use OCI Trace Explorer to view traces and spans and identify performance issues in your monitored application. See link:{oci-doc-url}/application-performance-monitoring/doc/monitor-traces-trace-explorer.html#GUID-D23BCE18-F42F-44A1-B583-47DF9F9817D8[Monitor Traces in Trace Explorer] in OCI documentation.

TIP: You can use OpenTelemetry for tracing and then ship the traces to OCI APM. Read the https://medium.com/oracledevs/distributed-tracing-in-helidon-coherence-and-oracle-autonomous-database-with-opentelemetry-and-c60fe965f902[Distributed Tracing in Helidon, Coherence and Oracle Autonomous Database with OpenTelemetry and OCI APM] article on Medium.

=== Streaming

The OCI Streaming service provides a fully managed, scalable, and durable solution for ingesting and consuming high-volume data streams in real time. See link:{oci-doc-url}/Content/Streaming/Concepts/streamingoverview.htm[Streaming] in OCI documentation.

The OCI Streaming service is compatible with Apache Kafka clients which means that when your Helidon applications are deployed in OCI environments, you can use either the OCI Streaming service or Apache Kafka. See link:{oci-doc-url}/Content/Streaming/Tasks/kafkacompatibility.htm[Using Streaming with Apache Kafka] in OCI documentation.

Streams are organized into logical groups called Stream Pools. When you connect to OCI Streaming with a Kafka client, streams are handled as Kafka topics and stream pools as virtual Kafka clusters.

To enable OCI Streaming integration, first you need to create a new stream in OCI. For instructions, see link:{oci-doc-url}/Content/Streaming/Tasks/creatingstreamsandstreampools_create-stream.htm[Creating a Stream] in OCI documentation. 

After you have finished creating the stream, make a note of the following values:

* Stream name (on the Stream Details page)
* Messages endpoint (on the Stream Details page)
* OCID of the stream _pool_ (on the Stream Pool Details page)

You can also click Kafka Connection Settings (on the Stream Pool Details page) to see an example of Kafka connection settings.

Next, add the following dependency to your project's ``pom.xml``:

[source,xml]
.Adding the dependency for OCI Streaming
----
<dependency>
  <groupId>io.helidon.microprofile.messaging</groupId>
  <artifactId>helidon-microprofile-messaging</artifactId>
</dependency>
<dependency>
  <groupId>io.helidon.messaging.kafka</groupId>
  <artifactId>helidon-messaging-kafka</artifactId>
</dependency>
----

Next, update ``/server/src/main/resources/application.yaml`` with streaming connection properties:

[source,yaml]
.Example of an application.yaml configured for OCI Streaming
----
oci:
 tenant: helidon-app-example # <1>
 user: email@domain.com # <2>
 token: oci-auth-token # <3>
 test-stream: # <4>
   name: TestStream
   endpoint: cell-1.streaming.us-phoenix-1.oci.oraclecloud.com
   port: 9092
   streampool-ocid: ocid1.streampool.oci1.phoenix.amaaaaaamevwycaap72ouurhfjrakuccakjpse5kenpkm5oikbgaadtq6byq
----
<1> The name of the OCI tenancy.
<2> The OCI account user name.
<3> The OCI authentication token. See link:{oci-doc-url}/Content/Registry/Tasks/registrygettingauthtoken.htm[Getting an Auth Token] in OCI documentation.
<4> The details of the stream which you saved earlier. The ``port`` should be the standard Kafka port number ``9092``.

Then, still in ``/server/src/main/resources/application.yaml``, configure messaging channels to use Helidon's Kafka connector.

[source,yaml]
.Example of a configuration for the helidon-kafka connector
----
mp.messaging:

  incoming.from-stream:
    connector: helidon-kafka
    topic: TestStream # <1>
    auto.offset.reset: latest
    enable.auto.commit: true
    group.id: example-group-id # <2>
 
  outgoing.to-stream:
    connector: helidon-kafka
    topic: TestStream # <1>

  connector:
     helidon-kafka:
       bootstrap.servers: ocid1.streampool.oci1.phoenix.amaaaaaamevwycaap72ouurhfjrakuccakjpse5kenpkm5oikbgaadtq6byq:9092 # <3>
       sasl.mechanism: PLAIN
       security.protocol: SASL_SSL
       sasl.jaas.config:  >-
         org.apache.kafka.common.security.plain.PlainLoginModule
         required
         username="helidon-app-example/person@domain.com/ocid1.streampool.oci1.phoenix.amaaaaaamevwycaap72ouurhfjrakuccakjpse5kenpkm5oikbgaadtq6byq" # <4>
         password="oci-auth-token"; # <5>
  
       key.serializer: org.apache.kafka.common.serialization.StringSerializer
       value.serializer: org.apache.kafka.common.serialization.StringSerializer
       key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
       value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
----
<1> The OCI stream name (which should match the value that you defined earlier in application.yaml).
<2> The ID for the stream group
<3> Kafka client's property link:{kafka-client-base-url}#consumerconfigs_bootstrap.servers[bootstrap.servers] configuration for all channels using the connector, using the following structure ``_<oci.test-stream.endpoint>:<oci.test-stream.port>_``.
<4> A username in this structure: ``_<oci.tenant>_/_<oci.user>_/_<oci.test-stream.streampool-ocid>_``.
<5> The OCI authentication token.

After you configure the ``helidon-kafka`` connector, you can use it on messaging channels to integrate with the OCI Streaming service.


=== Object Storage

The OCI Object Storage service is an internet-scale, high-performance storage platform that offers reliable and cost-efficient data durability. See link:{oci-objstore-url}[OCI Object Storage Overview] in OCI documentation.

To enable OCI Object Storage integration, add the following dependency to your project's ``pom.xml``:

[source,xml]
.Adding the dependency for OCI Object Storage
----
<dependency>
    <groupId>com.oracle.oci.sdk</groupId>
    <artifactId>oci-java-sdk-objectstorage</artifactId>
</dependency>
----

==== Injecting an Object Storage Client

Now you can inject OCI SDK Clients for Object Storage.

[source,java]
.Field-injection example
----
include::{sourcedir}/mp/integrations/OciSnippets.java[tag=snippet_1, indent=0]
----

[source,java]
.Constructor-injection example
----
include::{sourcedir}/mp/integrations/OciSnippets.java[tag=snippet_2, indent=0]
----

The extension implements this injection point by creating an Object Storage client
object in the link:{jakarta-inject-javadoc-url}/jakarta/inject/Singleton.html[singleton scope].

After you have injected an ObjectStorage client, you can use it as described in link:{oci-javasdk-objstore-javadoc-base-url}/package-summary.html[OCI SDK Object Storage Javadocs].

=== Vault

The OCI Vault service lets you store and manage encryption keys and secrets to securely access resources. See link:{oci-doc-url}/Content/KeyManagement/home.htm[Vault] in OCI documentation.

To enable OCI Vault integration, add the following dependencies to your project's ``pom.xml``:

[source,xml]
.Adding the dependency for OCI Vault
----
<dependency>
    <groupId>com.oracle.oci.sdk</groupId>
    <artifactId>oci-java-sdk-keymanagement</artifactId>
</dependency>
<dependency>
    <groupId>com.oracle.oci.sdk</groupId>
    <artifactId>oci-java-sdk-secrets</artifactId>
</dependency>
<dependency>
    <groupId>com.oracle.oci.sdk</groupId>
    <artifactId>oci-java-sdk-vault</artifactId>
</dependency>
----

==== Injecting a Vault Client

Now you can inject OCI SDK Clients for OCI Vault.

[source,java]
----
import com.oracle.bmc.keymanagement.KmsCrypto;
import com.oracle.bmc.secrets.Secrets;
import com.oracle.bmc.vault.Vaults;
@Inject
VaultResource(Secrets secrets,
    KmsCrypto crypto,
    Vaults vaults) {
    this.secrets = secrets;
    this.crypto = crypto;
    this.vaults = vaults;
}
----

== References

* link:{integration-oci-sdk-cdi-javadoc-base-url}/io/helidon/integrations/oci/sdk/cdi/OciExtension.html[OciExtension] in the Helidon Javadocs
* link:{helidon-github-examples-url}/integrations/oci[OCI SDK Usage Examples] in the Helidon Examples GitHub repository
