///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:description: Helidon metrics
:keywords: helidon, metrics, exemplar, prometheus, OpenMetrics
:zipkinSharedPage: ../../shared/tracing/tracer-zipkin.adoc
:jaegerSharedPage: ../../shared/tracing/tracer-jaeger.adoc
:open-metrics-spec-exemplars: https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#exemplars

Add Helidon {h1Prefix} support for  link:{open-metrics-spec-exemplars}[OpenMetrics (Prometheus) exemplars] to your application simply by adding dependencies to your project's `pom.xml`.

== Prerequisites

Declare the following dependency in your project:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>io.helidon.metrics</groupId>
    <artifactId>helidon-metrics-trace-exemplar</artifactId>
    <scope>runtime</scope>
</dependency>
----

Also, include either xref:{zipkinPageRef}[Helidon Zipkin] or xref:{jaegerPageRef}[Helidon Jaeger] support:
include::{zipkinSharedPage}[tag=zipkin-dependency]
or
include::{jaegerSharedPage}[tag=jaeger-dependency]

Be sure Zipkin or Jaeger, whichever you chose, is running and accessible to your server.

== Interpreting Exemplars

//[quote,Mirriam-Webster Dictionary,'link:https://www.merriam-webster.com/dictionary/exemplar[exemplar]'']
//____
//exemplar - one that serves as a model or example
//____
[NOTE]
--
link:https://www.merriam-webster.com/dictionary/exemplar[_exemplar_] - one that serves as a model or example
[.text-right]
-- Merriam-Webster Dictionary
--

When you add the `helidon-metrics-trace-exemplar` dependency--and one for either Zipkin or Jaeger--to your application, Helidon automatically records a sample (label, value, and timestamp) with each update to a histogram, simple timer, or counter. Helidon adds the label, value, and timestamp to the OpenMetrics output returned from the Helidon metrics endpoint (`/metrics` unless you set it up otherwise).

By default, Helidon adds exemplars only to counters and the counter portion of simple timers. The OpenMetrics specification allows exemplars only on counters and buckets. (Helidon's histogram output, consistent with the MicroProfile Metrics spec, includes the quantiles but not the buckets.)

[NOTE]
Earlier releases of Helidon included exemplars on other metric types as well. If you must keep the prior behavior for compatibility reasons, see the xref:controlling-exemplar-output[Controlling Exemplar Output] section below.


.Exemplar output - `Counter`
[listing]
----
# TYPE application_myCounter_total counter
application_myCounter_total 14 # {trace_id="067632454fe4e8d1"} 1.14701E-4 1617723032.570000 <1>

----
<1> This exemplar is the most recent sample.

.Exemplar output - `SimpleTimer`
[listing]
----
# TYPE application_globalRequestTracker_total counter
# HELP application_globalRequestTracker_total
application_globalRequestTracker_total 4 # {trace_id="daf26fe35fee9917"} 0.001183992 1617725180.234000 <1>

----
<1> The exemplar for a `SimpleTimer` is the most recent sample which updated the `SimpleTimer`.

The exemplar information describes a single, actual sample that is representative of the statistical value.
Helidon chooses the representative examplar for each value using information that is already recorded for each type of metric.


[[controlling-exemplar-output]]
== Controlling Exemplar Output
Once you add dependencies on `helidon-metrics-trace-exemplar` and one of the Helidon tracing integration libraries to your project, Helidon automatically adds exemplars to those metrics which the OpenMetrics specification permits to have exemplars.

Earlier releases of Helidon added exemplars to other, non-standard metric types. If you require the former behavior for compatibility reasons,  you can enable exemplars on non-standard metric types.
In this context, with _strict_ exemplar behavior Helidon adds exemplars only to those metrics allowed by the OpenMetrics spec.  With _lax_ behavior Helidon also adds exemplars to simple timer and meter output.

[NOTE]
The lax exemplar behavior is non-standard. Some downstream consumers of the resulting OpenMetrics output might reject it because it contains non-standard content.

ifdef::se-flavor[]
=== Using Configuration
endif::[]
ifdef::se-flavor[]
[source,yaml]
.Enabling non-standard exemplar behavior in `application.yaml`
----
metrics:
  strict-exemplars: false
----
endif::[]
ifdef::mp-flavor[]
[source,properties]
.Enabling non-standard exemplar behavior in `META-INF/microprofile-config.properties`
----
metrics.strict-exemplars = false
----
endif::[]
The `strict-exemplars` setting defaults to `true`.

ifdef::se-flavor[]
=== Using `MetricsSettings` Programmatically
The `MetricsSettings.Builder` interface accepts `strictExemplars(boolean)` with which you can programmatically choose the .
endif::[]
