///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Requested URI Discovery
:h1Prefix: MP
:description: Helidon Reactive WebServer requested URI discovery
:keywords: helidon, reactive, reactive streams, reactive java, reactive webserver, requested URI discovery
:rootdir: {docdir}/../..
:incdir: {rootdir}/shared/server
:requested-uri-discovery-inc: {incdir}/requested-uri-discovery.adoc
:mp-flavor: true
:flavor-uc: MP
:flavor-lc: mp

include::{requested-uri-discovery-inc}[tag=preamble]

== Requested URI Discovery
include::{requested-uri-discovery-inc}[tag=intro]

=== Setting Up Requested URI Discovery
include::{requested-uri-discovery-inc}[tag=config-example-intro]

[source,properties]
.Configuring Request URI Discovery (properties format)
----
server.port=8080
server.requested-uri-discovery.types=FORWARDED,X_FORWARDED
server.requested-uri-discovery.trusted-proxies.allow.pattern=lb.*\\.mycorp\\.com
server.requested-uri-discovery.trusted-proxies.deny.exact=lbtest.mycorp.com
----
This example might apply if `mycorp.com` had trusted load balancers named `lbxxx.mycorp.com` except for an untrusted test load balancer `lbtest.mycorp.com`.

=== Obtaining the Requested URI Information
Helidon makes the requested URI information available as a property in the request context:

[source,java]
.Retrieving Requested URI Information
----
import io.helidon.common.http.UriInfo;

public class MyFilter implements ContainerRequestFilter {

    @Override
    public void filter(ContainerRequestContext requestContext) {
        UriInfo uriInfo = (UriInfo) requestContext.getProperty("io.helidon.jaxrs.requested-uri");
        // ...
    }
}
----
See the link:{common-http-javadoc-base-url}/io/helidon/common/http/UriInfo.html[`UriInfo`] JavaDoc for more information.

NOTE: The `requestContext.getUriInfo()` method returns the Jakarta RESTful web services `UriInfo` object, _not_ the Helidon-provided requested URI information `UriInfo` object.
