///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon CDI extensions
:description: Helidon CDI extensions guide
:keywords: helidon, guide, CDI

* <<Overview>>
* <<Installing a CDI extension>>
* <<Injecting an object using a CDI extension>>

== Overview

Helidon provides https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#spi[portable extensions] that you can use to inject the following objects into your Helidon MicroProfile applications:

* HikariCP data sources
* Jedis clients
* Oracle Cloud Infrastructure Object Storage clients

== Installing a CDI extension

The Helidon CDI extensions are available as https://mvnrepository.com/artifact/io.helidon.integrations.cdi[Maven artifacts].

To install an extension, ensure that the extension and its runtime dependencies are specified on your application's runtime classpath.

The following examples show how to specify the required dependencies for the Helidon CDI extensions in your Maven POM (`pom.xml`).
 
* To install the extension for HikariCP data sources, specify the following dependency:

[source,xml]
----
<dependency>
  <groupId>io.helidon.integrations.cdi</groupId>
  <artifactId>helidon-integrations-cdi-datasource-hikaricp</artifactId>
  <version>1.0.0</version>
  <scope>runtime</scope>
</dependency>
----
  
* To install the extension for Jedis clients, specify the following dependency:
 
[source,xml]
----
<dependency>
  <groupId>io.helidon.integrations.cdi</groupId>
  <artifactId>helidon-integrations-cdi-jedis</artifactId>
  <version>1.0.0</version>
  <scope>runtime</scope>
</dependency>
----
  
* To install the extension for Oracle Cloud Infrastructure Object Storage clients:

   1. Clone the Oracle Cloud Infrastructure Java SDK artifacts. This step is necessary because, currently, the Oracle Cloud Infrastructure Java SDK is not available in the Maven repository.
   
      [source,bash]
      ----
      git clone --depth 1 --branch v1.2.44 https://github.com/oracle/oci-java-sdk.git
      ----
      
   2. Install the Oracle Cloud Infrastructure Java SDK artifacts in your local Maven repository.
   
      [source,bash]
      ----
      mvn -B -U -f oci-java-sdk.git/pom.xml \
          -Dmaven.test.skip=true \
          -Dmaven.source.skip=true \
          -Dmaven.javadoc.skip=true \
          -Dlombok.delombok.skip=true \
          -pl bmc-objectstorage \
          -am \
          install
      ----  
   
   3. Specify the following dependency in your application's Maven POM:
   
      [source,xml]
      ----
      <dependency>
         <groupId>io.helidon.integrations.cdi</groupId>
         <artifactId>helidon-integrations-cdi-oci-objectstorage</artifactId>
         <version>1.0.0</version>
         <scope>runtime</scope>
      </dependency>
      ----

== Injecting an object using a CDI extension

The following are examples of field injection and constructor injection for each of the Helicon CDI extensions:
 
=== Injecting a HikariCP data source

The following examples show how to create a `DataSource` named `orders` in your application.

* Field-injection example:

[source,java]
----
@Inject
@Named("orders")
private DataSource ordersDataSource;
----

* Constructor-injection example:

[source,java]
----
private final DataSource ds;
  
@Inject
public YourConstructor(@Named("orders") DataSource ds) {
  super();
  this.ds = ds;
}
----

The extension implements this injection point by creating an https://static.javadoc.io/com.zaxxer/HikariCP/2.7.8/com/zaxxer/hikari/HikariDataSource.html[HikariDataSource] object in the http://docs.jboss.org/cdi/api/2.0/javax/enterprise/context/ApplicationScoped.html[application scope].

To locate the configuration of the object, the extension uses the https://static.javadoc.io/org.eclipse.microprofile.config/microprofile-config-api/1.3/index.html?overview-summary.html[MicroProfile
Config API].

https://static.javadoc.io/org.eclipse.microprofile.config/microprofile-config-api/1.3/org/eclipse/microprofile/config/Config.html#getPropertyNames--[Property
names] that start with `javax.sql.DataSource.`_dataSourceName_`.` are parsed, and the remaining portion of each name is treated
as a https://github.com/brettwooldridge/HikariCP/blob/dev/README.md#configuration-knobs-baby[Hikari
connection pool property].

For example, a property with the name `javax.sql.DataSource.orders.dataSourceClassName` and value `org.h2.jdbcx.JdbcDataSource` together together with other similarly-named properties results in a Hikari connection pool with the `dataSourceClassName` property set to `org.h2.jdbcx.JdbcDataSource`.
  
=== Injecting a Jedis client

The following examples show how to create and inject a Jedis pool named `orders` in your application code.

* Field-injection example:

[source,java]
----
@Inject
@Named("orders")
private JedisPool ordersPool;
----

* Constructor-injection example:

[source,java]
----
private final JedisPool ordersPool;

@Inject
public YourConstructor(@Named("orders") JedisPool pool) {
  super();
  this.ordersPool = pool;
}
----

The extension implements this injection point by creating an https://static.javadoc.io/redis.clients/jedis/2.9.0/redis/clients/jedis/JedisPool.html[JedisPool] object in the http://docs.jboss.org/cdi/api/2.0/javax/enterprise/context/ApplicationScoped.html[application scope].

To locate the configuration of the object, the extension uses the https://static.javadoc.io/org.eclipse.microprofile.config/microprofile-config-api/1.3/index.html?overview-summary.html[MicroProfile
Config API].

https://static.javadoc.io/org.eclipse.microprofile.config/microprofile-config-api/1.3/org/eclipse/microprofile/config/Config.html#getPropertyNames--[Property
names] that start with `redis.clients.jedis.JedisPool.`_dataSourceName_`.` are parsed, and the remaining portion of each name is treated as a Java been property of `JedisPool`.

For example, a property with the name `redis.clients.jedis.JedisPool.orders.port` and value `6379` together with other similarly-named properties results in a `JedisPool` object with the `port` property set to `6379`.

=== Injecting an Oracle Cloud Infrastructure Object Storage client

* Field-injection example:

[source,java]
----
@Inject
private ObjectStorage client;
----

* Constructor-injection example:

[source,java]
----
private final ObjectStorage client;

@Inject
public YourConstructor(@Named("orders") ObjectStorage client) {
  super();
  this.client = client;
}
----

The extension implements this injection point by creating an Object Storage client object in the http://docs.jboss.org/cdi/api/2.0/javax/enterprise/context/ApplicationScoped.html[application scope].

To locate the configuration of the object, the extension uses the https://static.javadoc.io/org.eclipse.microprofile.config/microprofile-config-api/1.3/index.html?overview-summary.html[MicroProfile
Config API]. The following https://static.javadoc.io/org.eclipse.microprofile.config/microprofile-config-api/1.3/org/eclipse/microprofile/config/Config.html#getPropertyNames--[property
names] are used to establish a connection to Oracle Cloud Infrastructure Object
Storage:

* `oci.auth.fingerprint`
* `oci.auth.keyFile`
* `oci.auth.passphraseCharacters`
* `oci.auth.user`
* `oci.auth.tenancy`
* `oci.objectstorage.region`

These properties are described in the https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/javasdk.htm#Configur[Oracle Cloud Infrastructure Object Storage Java SDK documentation].
