///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////
//Contains content that is shared between multiple guides.
:common-page-prefix-inc:


=== Prerequisites 

// tag::common-prereqs[]


[role="flex, sm7"]
|=======

// tag::common-prereqs-table-contents[]

|A Helidon MP Application | You can use your own application or use the https://helidon.io/docs/v2/#/mp/guides/02_quickstart[Helidon MP Quickstart] to create a sample application.
|https://www.oracle.com/technetwork/java/javase/downloads[Java{nbsp}SE{nbsp}11] (http://jdk.java.net[Open{nbsp}JDK{nbsp}11]) |Helidon requires Java 11+.
|https://maven.apache.org/download.cgi[Maven 3.6.1+]|Helidon requires Maven 3.6.1+.
|https://docs.docker.com/install/[Docker 18.09+]|You need Docker if you
want to build and deploy Docker containers.
|https://kubernetes.io/docs/tasks/tools/install-kubectl/[Kubectl 1.16.5+]|If you want to
deploy to Kubernetes, you need `kubectl` and a Kubernetes cluster (you can
<<about/05_kubernetes.adoc,install one on your desktop>>).
// end::common-prereqs-table-contents[]

|=======



[source,bash]
.Verify Prerequisites
----
java -version
mvn --version
docker --version
kubectl version --short
----


[source,bash]
.Setting JAVA_HOME
----
# On Mac
export JAVA_HOME=`/usr/libexec/java_home -v 11`

# On Linux
# Use the appropriate path to your JDK
export JAVA_HOME=/usr/lib/jvm/jdk-11
----
// end::common-prereqs[]


// tag::common-prereqs-helm[]

[role="flex, sm7"]
|=======
include::common_prereqs.adoc[tag=common-prereqs-table-contents]

|https://github.com/helm/helm[Helm] | To manage Kubernetes applications.
|=======



[source,bash]
.Verify Prerequisites
----
java -version
mvn --version
docker --version
kubectl version --short
----


[source,bash]
.Setting JAVA_HOME
----
# On Mac
export JAVA_HOME=`/usr/libexec/java_home -v 11`

# On Linux
# Use the appropriate path to your JDK
export JAVA_HOME=/usr/lib/jvm/jdk-11
----

// end::common-prereqs-helm[]

// tag::common-prereqs-curl[]

[role="flex, sm7"]
|=======
include::common_prereqs.adoc[tag=common-prereqs-table-contents]
|https://curl.se/download.html[curl] 
|(Optional) for testing
|=======



[source,bash]
.Verify Prerequisites
----
java -version
mvn --version
docker --version
kubectl version --short
----


[source,bash]
.Setting JAVA_HOME
----
# On Mac
export JAVA_HOME=`/usr/libexec/java_home -v 11`

# On Linux
# Use the appropriate path to your JDK
export JAVA_HOME=/usr/lib/jvm/jdk-11
----
// end::common-prereqs-curl[]


// tag::common-prereqs-graal[]


[role="flex, sm7"]
|=======
include::common_prereqs.adoc[tag=common-prereqs-table-contents]
| https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.0.0[GraalVM CE 21.0.0]|
|=======



[source,bash]
.Verify Prerequisites
----
java -version
mvn --version
docker --version
kubectl version --short
----


[source,bash]
.Setting JAVA_HOME
----
# On Mac
export JAVA_HOME=`/usr/libexec/java_home -v 11`

# On Linux
# Use the appropriate path to your JDK
export JAVA_HOME=/usr/lib/jvm/jdk-11
----
// end::common-prereqs-graal[]
