///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Persistence
:description: Persistence-related support in Helidon MP
:keywords: datasource, helidon, jpa, jta, microprofile, mp
:rootdir: {docdir}/..

include::{rootdir}/includes/mp.adoc[]

== Contents

* <<Overview, Overview>>
* <<DS, Named Data Source Integration>>
** <<DS-CP-Project-Setup, Setting Up a Connection Pool>>
*** <<DS-HikariCP-Project-Setup, Setting Up the Hikari CP Connection Pool>>
*** <<DS-UCP-Project-Setup, Setting Up the Oracle Universal Connection Pool>>
** <<DS-Driver-Project-Setup, Setting Up a Database Driver>>
*** <<DS-H2-Driver-Project-Setup, Setting Up H2>>
*** <<DS-Oracle-Driver-Project-Setup, Setting Up Oracle JDBC>>
** <<DS-Configuration, Configuration>>
** <<DS-Usage, Usage>>

== Overview [[Overview]]

Helidon MP comes with deep integration for three broad,
specification-defined, persistence-related technologies that can be
used together or separately:

* Named https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/javax/sql/DataSource.html[data sources]
* https://jakarta.ee/specifications/transactions/2.0/[Jakarta Transactions] (JTA)
* https://jakarta.ee/specifications/persistence/3.0/[Jakarta Persistence] (JPA)

The integrations supported for each technology are described below.

== Named Data Source Integration [[DS]]

=== Overview

Helidon MP's named data source integration allows you to safely inject
managed
https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/javax/sql/DataSource.html[`javax.sql.DataSource`]
instances that are annotated with
https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/named[`jakarta.inject.Named`
annotations] into your Helidon MP application.
https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/Connection.html[`java.sql.Connection`
objects]
https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/javax/sql/DataSource.html#getConnection()[acquired]
from these data sources will be pooled by one of two possible
connection pool implementations:

1. https://github.com/brettwooldridge/HikariCP[HikariCP]

2. https://docs.oracle.com/en/database/oracle/oracle-database/21/jjucp/index.html[Oracle
   Universal Connection Pool]

The connections managed by the connection pool will be supplied by
your relational database vendor's JDBC driver.

How you set up Helidon MP's named data source integration differs
depending on which of these two connection pools, which JDBC driver,
and which relational database product you use.  Example setups are
described below.

==== Setting Up a Connection Pool [[DS-CP-Project-Setup]]

Helidon MP's named data source integration requires a connection pool.
Helidon MP comes with support for two connection pools:

1. https://github.com/brettwooldridge/HikariCP[HikariCP]

2. https://docs.oracle.com/en/database/oracle/oracle-database/21/jjucp/index.html[Oracle
   Universal Connection Pool]

You can choose to use either, but not both.  Details concerning each
connection pool's setup are described below.

===== Setting Up the HikariCP Connection Pool [[DS-HikariCP-Project-Setup]]

====== Maven Coordinates (HikariCP) [[DS-HikariCP-Maven-Coordinates]]

To include the HikariCP connection pool in your Helidon MP
application, xref:../about/managing-dependencies.adoc[ensure your
dependencies are managed], and then ensure the following
`<dependency>` element is present as a child element of your project's
`pom.xml` file's `<dependencies>` element:

[source,xml]
----
<dependency>
    <groupId>io.helidon.integrations.cdi</groupId>
    <artifactId>helidon-integrations-cdi-datasource-hikaricp</artifactId>
    <scope>runtime</scope> <!--1-->
</dependency>
----
<1> Note that the `scope` is `runtime`, indicating that the HikariCP
    integration will be available on the runtime classpath.

===== Setting up the Oracle Universal Connection Pool [[DS-UCP-Project-Setup]]

====== Maven Coordinates (Oracle Universal Connection Pool) [[DS-UCP-Maven-Coordinates]]

To include the Oracle Universal Connection Pool in your Helidon MP
application, xref:../about/managing-dependencies.adoc[ensure your
dependencies are managed], and then ensure the following
`<dependency>` element is present as a child element of your project's
`pom.xml` file's `<dependencies>` element:

[source,xml]
----
<dependency>
  <groupId>io.helidon.integrations.cdi</groupId>
  <artifactId>helidon-integrations-cdi-datasource-ucp</artifactId>
  <scope>runtime</scope> <!--1-->
</dependency>
----
<1> Note that the `scope` is `runtime`, indicating that the Oracle
    Universal Connection Pool integration will be available on the
    runtime classpath.

==== Setting Up a Database Driver [[DS-Driver-Project-Setup]]

===== Overview

Regardless of which connection pool you use, at the lowest level a
JDBC database driver is responsible for making any connections to a
relational database.  JDBC database drivers are
database-product-specific.

Once you have decided upon a relational database product to use, and a
JDBC driver to use to connect to it,
xref:../about/managing-dependencies.adoc[ensure your dependencies are
managed], and then ensure that a `runtime`-scoped `<dependency>`
element describing your JDBC driver is present as a child element of
your project's `pom.xml` file's `<dependencies>` element.

A couple of examples are described below for some common database
products.  They are not exhaustive.

See the
https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/package-summary.html[JDBC
4.3 Specification] for more information about JDBC.

===== Setting Up H2 [[DS-H2-Driver-Project-Setup]]

====== Maven Coordinates (H2) [[DS-H2-Driver-Maven-Coordinates]]

To include the http://www.h2database.com/html/main.html[H2 JDBC
driver] in your Helidon MP application so your application can connect
to an H2 database (whether in-memory or persistent):

* xref:../about/managing-dependencies.adoc[Ensure your dependencies are
managed]

Ensure the following
`<dependency>` element is present as a child element of your project's
`pom.xml` file's `<dependencies>` element:

[source,xml]
----
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <!--
         It's best to manage this with Maven's <dependencyManagement> feature,
         which is why the <version> element is commented out below.
         If nevertheless you opt for the explicit version here, check
         https://search.maven.org/search?q=g:com.h2database%20a:h2
         for up-to-date available versions.
    -->
    <!-- <version>2.1.212</version> -->
    <scope>runtime</scope> <!--1-->
</dependency>
----
<1> Note that the `scope` is `runtime`, indicating that the H2
    JDBC driver will be available on the runtime classpath.

===== Setting Up Oracle JDBC [[DS-Oracle-Driver-Project-Setup]]

====== Maven Coordinates (Oracle JDBC) [[DS-Oracle-Driver-Maven-Coordinates]]

To include the Oracle JDBC driver in your Helidon MP application so
your application can connect to an Oracle database:

* xref:../about/managing-dependencies.adoc[Ensure your dependencies are
managed]

* Read and understand
  https://www.oracle.com/database/technologies/maven-central-guide.html[Developer's
  Guide For Oracle JDBC 21c on Maven Central]

Ensure the following
`<dependency>` element is present as a child element of your project's
`pom.xml` file's `<dependencies>` element:

[source,xml]
----
<dependency>
    <!--
         See
         https://www.oracle.com/database/technologies/maven-central-guide.html
         for more details.
     -->
    <groupId>com.oracle.database.jdbc</groupId>
    <!--
         Why ojdbc*11*? Because:
         (a) Helidon 3 targets Java 17
         (b) Java 17 includes JDBC 4.3
         (c) ojdbc11 implements relevant parts of JDBC 4.3
         Please see
         https://www.oracle.com/database/technologies/maven-central-guide.html
         for more details.
    -->
    <artifactId>ojdbc11</artifactId>
    <!--
         It's best to manage this with Maven's <dependencyManagement> feature,
         which is why the <version> element is commented out below.
         If nevertheless you opt for the explicit version here, check
         https://search.maven.org/search?q=g:com.oracle.database.jdbc
         for up-to-date available versions, and see
         https://www.oracle.com/database/technologies/maven-central-guide.html
         for extremely important information.
    -->
    <!-- <version>21.3.0.0</version> -->
    <scope>runtime</scope> <!--1-->
</dependency>
----
<1> Note that the `scope` is `runtime`, indicating that the Oracle
    JDBC driver will be available on the runtime classpath.

==== Configuration [[DS-Configuration]]

To configure Helidon MP's named data source integration support:

1. Decide where the configuration will reside.

2. Create configuration suitable for the combination of your selected
   connection pool and database driver in that location.

Helidon MP's named data source integration support relies on
xref:config/introduction.adoc[Helidon MP's usage of MicroProfile
Config], so you have many choices when deciding on your
configuration's location in (1) above.

The configuration values themselves are necessarily specific to the
connection pool you selected and the database driver responsible for
actually connecting to your relational database.  In general, at a
minimum, you supply:

* a JDBC URL describing where the database is located

* information required to authenticate to the database

Some examples for common combinations follow.  They are not
exhaustive.

===== Configuration Prefixes

All MicroProfile Config-compatible property names for Helidon MP's
named data source integration support follow a common pattern:

> _objecttype_._datasourcename_._propertyname_

* The name of a given configuration property always begins with the
  fully-qualified Java class name of the object being configured.
  Most configuration for Helidon MP's named data source integration
  concerns the behavior of `javax.sql.DataSource` objects, so most
  configuration property names begin with `javax.sql.DataSource`.

* A period (`.`) separates the _objecttype_ portion from the rest of
  the property name.

* The name of the data source being configured comes next.  It cannot
  contain a period (`.`).

* A period (`.`) separates the _datasourcename_ portion from the rest
  of the property name.

* The connection pool- or driver-specific property name comes next.

As an example, configuration to set an imaginary `foo` property on the
`test` data source to `bar` looks like this:

[source]
----
javax.sql.DataSource.test.foo=bar
----

==== Usage [[DS-Usage]]

You use Helidon MP's named data source integration support in the same
way, regardless of your choices of database driver and connection pool.

To use Helidon MP's named data source integration support in your
application, create a
https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/javax/sql/DataSource.html[`DataSource`]-typed
injection point in a Java class representing a CDI bean somewhere in
your application,
https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/named[annotated
with the name] of the data source you wish to use.

Here is how to define a field-backed injection point:

[source,java]
----
import javax.sql.DataSource;

import jakarta.inject.Inject;
import jakarta.inject.Named;

// ...

@Inject // <1>
@Named("test") // <2>
private DataSource ds; // <3>
----
<1> https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/inject[`@Inject`]
    marks the field as an injection point.  Its behavior is defined by
    the
    https://jakarta.ee/specifications/dependency-injection/2.0/[Jakarta
    Dependency Injection specification].
<2> https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/named[`@Named("test")`]
    says to use the data source named `test`.
<3> The field injection point has a type of
    https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/javax/sql/DataSource.html[`javax.sql.DataSource`],
    and may be named anything you like.

Here is how to define a constructor parameter injection point:

[source,java]
----
import javax.sql.DataSource;

import jakarta.inject.Inject;
import jakarta.inject.Named;

// ...

private final DataSource ds; // <1>

@Inject // <2>
public SomeObject(@Named("test") DataSource ds) { // <3>
    this.ds = ds; // <4>
}
----
<1> This is the field whose value will be set in the constructor.
<2> https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/inject[`@Inject`]
    marks the constructor as one containing parameter injection
    points.  Its behavior is defined by the
    https://jakarta.ee/specifications/dependency-injection/2.0/[Jakarta
    Dependency Injection specification].
<3> https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/named[`@Named("test")`]
    says to use the data source named `test`.  The parameter injection
    point has a type of
    https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/javax/sql/DataSource.html[`javax.sql.DataSource`],
    and may be named anything you like.
<4> The injected argument will never be `null`.
