///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Persistence
:description: Persistence-related support in Helidon MP
:keywords: datasource, helidon, jpa, jta, microprofile, mp
:rootdir: {docdir}/..

include::{rootdir}/includes/mp.adoc[]

== Contents

* <<Overview, Overview>>
* <<DS, Named Data Source Integration>>
** <<DS-HikariCP-Setup, Setting Up the Hikari CP Connection Pool>>
** <<DS-Usage, Common Usage>>

== Overview [[Overview]]

Helidon MP comes with deep integration for three broad,
specification-defined, persistence-related technologies that can be
used together or separately:

* Named https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/javax/sql/DataSource.html[data sources]
* https://jakarta.ee/specifications/transactions/2.0/[Jakarta Transactions] (JTA)
* https://jakarta.ee/specifications/persistence/3.0/[Jakarta Persistence] (JPA)

The supported integration for each technology is detailed below.

== Named Data Source Integration [[DS]]

=== Overview

Helidon MP's named data source integration allows you to safely inject
managed
https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/javax/sql/DataSource.html[`javax.sql.DataSource`]
instances that are annotated with
https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/named[`jakarta.inject.Named`
annotations] into your Helidon MP application.
https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/Connection.html[`java.sql.Connection`
objects]
https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/javax/sql/DataSource.html#getConnection()[acquired]
from these data sources will be pooled by one of two possible
connection pool implementations:

1. https://github.com/brettwooldridge/HikariCP[HikariCP]

2. https://docs.oracle.com/en/database/oracle/oracle-database/21/jjucp/index.html[Oracle
   Universal Connection Pool]

How you set up named data source integration differs depending on
which of these two connection pools you use.  Each setup is described
below.

==== Setting Up the HikariCP Connection Pool [[DS-HikariCP-Setup]]

===== Maven Coordinates [[DS-HikariCP-Maven-Coordinates]]

To include the HikariCP connection pool in your Helidon MP
application, xref:../about/managing-dependencies.adoc[ensure your
dependencies are managed], and then ensure the following
`<dependency>` element is present as a child element of your project's
`pom.xml` file's `<dependencies>` element:

[source,xml]
----
<dependency>
    <groupId>io.helidon.integrations.cdi</groupId>
    <artifactId>helidon-integrations-cdi-datasource-hikaricp</artifactId>
    <scope>runtime</scope>
</dependency>
----

==== Common Usage [[DS-Usage]]

To use Helidon MP's named data source integration support in your
application, create a
https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/javax/sql/DataSource.html[`DataSource`]-typed
injection point somewhere in your application,
https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/jakarta/inject/named[annotated
with the name] of the data source you wish to use.

Here is how to define a field-backed injection point:

[source,java]
----
import javax.sql.DataSource;

import jakarta.inject.Inject;
import jakarta.inject.Named;

// ...

@Inject // <1>
@Named("test") // <2>
private DataSource ds; // <3>
----
<1> `@Inject` marks the field as an injection point.
<2> `@Named("test")` says to use the data source named `test`.
<3> The injection point has a type of `javax.sql.DataSource` and may
    be named anything you like.

