///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Telemetry
:description: Helidon MP Telemetry Support
:feature-name: MicroProfile Telemetry
:keywords: helidon, telemetry, microprofile, micro-profile
:microprofile-bundle: true
:rootdir: {docdir}/..

include::{rootdir}/includes/mp.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
- <<Configuration, Configuration>>
- <<Examples, Examples>>
- <<Additional Information, Additional Information>>
- <<Reference, Reference>>

== Overview



include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.telemetry</groupId>
    <artifactId>helidon-microprofile-telemetry</artifactId>
</dependency>
----

== Usage

OpenTelemetry comprises a collection of APIs, SDKs, integration tools, and other software components intended to facilitate the generation and control of telemetry data, including traces, metrics, and logs. In an environment where distributed tracing is enabled via OpenTelemetry (which combines OpenTracing and OpenCensus), this specification establishes the necessary behaviors for MicroProfile applications to participate seamlessly.

There are two ways to work with Telemetry, using:

- Automatic Instrumentation
- Manual Instrumentation

For Automatic Instrumentation, OpenTelemetry provides a JavaAgent. The Tracing API allows for the automatic participation in distributed tracing of Jakarta RESTful Web Services (both server and client) as well as MicroProfile REST Clients, without requiring any modifications to the code. This is achieved through automatic instrumentation.

For Manual Instrumentation there is a set of annotations and access to OpenTelemetry API.

`@WithSpan` - By adding this annotation to a method in any Jakarta CDI aware bean, a new Span will be created and any necessary connections to the current Trace context will be established. Additionally, the `SpanAttribute` annotation can be used to mark method parameters that should be included in the Trace.

Helidon provides full access to OpenTelemetry Tracing API:

* `io.opentelemetry.api.OpenTelemetry`
* `io.opentelemetry.api.trace.Tracer`
* `io.opentelemetry.api.trace.Span`
* `io.opentelemetry.api.baggage.Baggage`

Accessing and using these objects can be done as follows. For span:

.Span sample
[source, java]
----
@ApplicationScoped
class HelidonBean {

    @WithSpan   <1>
    void doSomethingWithinSpan() {
        // do something here
    }

    @WithSpan("name", kind = SpanKind.SERVER, @SpanAttribute(value = "arg") String arg) <2>
    void complexSpan() {
        // do something here
    }
}
----
<1> Simple `@WithSpan` annotation usage;
<2> Additional attributes can be set to the annotation.

You can also inject OpenTelemetry `Tracer` using the regular `@Inject` annotation and use `SpanBuilder` to manually create, star, and stop Spans.

.SpanBuilder usage
[source, java]
----
@Path("/")
public class HelidonEndpoint {

    @Inject
    Tracer tracer;  <1>

    @GET
    @Path("/span")
    public Response span() {
        Span span = tracer.spanBuilder("new")   <2>
                .setSpanKind(SpanKind.CLIENT)
                .setAttribute("someAttribute", "someValue")
                .startSpan();

        span.end();

        return Response.ok().build();
    }
}
----
<1> Inject `Tracer`;
<2> Use `Tracer.spanBuilder` to create and start new `Span`;

To obtain the current span, it can be injected with CDI. The current span can also be obtained using the static method `Span.current()`.

.Inject the current span
[source, java]
----
@Path("/")
public class HelidonEndpoint {
    @Inject
    Span span;  <1>

    @GET
    @Path("/current")
    public Response currentSpan() {
        return Response.ok(span.getAttribute("someAttribute")).build(); <2>
    }


    @GET
    @Path("/current/static")
    public Response currentSpanStatic() {
        return Response.ok(Span.current().getAttribute("someAttribute")).build(); <3>
    }
}
----
<1> Inject the current span;
<2> Use the injected span;
<3> Use `Span.current()` to access the current span;

The same functionality is available for the `Baggage` API:

.Inject the current baggage
[source, java]
----
@Path("/")
public class HelidonEndpoint {
    @Inject
    Baggage baggage;  <1>

    @GET
    @Path("/current")
    public Response currentBaggage() {
        return Response.ok(baggage.get("baggageKey")).build(); <2>
    }


    @GET
    @Path("/current/static")
    public Response currentBaggageStatic() {
        return Response.ok(Baggage.current().get("baggageKey")).build(); <3>
    }
}
----
<1> Inject the current baggage;
<2> Use the injected baggage;
<3> Use `Baggage.current()` to access the current baggage;


== Configuration

IMPORTANT: MicroProfile Telemetry is not activated by default. To activate this feature, you need to specify the configuration `otel.sdk.disabled=false` in one of the MicroProfile Config or other config sources.

To configure OpenTelemetry, MicroProfile Config must be used, and the configuration properties outlined in the following sections must be followed:

- OpenTelemetry SDK Autoconfigure (excluding properties related to Metrics and Logging)
- Manual Instrumentation


=== OpenTelemetry Java Agent

The OpenTelemetry Java Agent may influence the work of MicroProfile Telemetry, on how the objects are created and configured. Helidon will do "best effort" detect the use of the agent. But, if there is a decision to run the Helidon app with the agent, a configuration property should be set:

`otel.agent.present=true`

This way, Helidon will explicitly get all the configuration and objects from the Agent, thus allowing correct Span hierarchy settings.

== Examples

This guide showcases how to incorporate MicroProfile Telemetry into Helidon and provides illustrations of how to view traces. Jaeger is employed in all the examples, and the Jaeger UI is used to view the traces.

=== Setup Jaeger

For the examples Jaeger will be used for gathering of the tracing information.

.Run Jeager in a docker container.
[source, bash]
----
docker run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HOST_PORT=:9411 \
  -e COLLECTOR_OTLP_ENABLED=true \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 4317:4317 \
  -p 4318:4318 \
  -p 14250:14250 \
  -p 14268:14268 \
  -p 14269:14269 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.41
----

=== Enable MicroProfile Telemetry in Helidon Application

[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.telemetry</groupId>
    <artifactId>helidon-microprofile-telemetry</artifactId>
</dependency>
----

Add these lines to `META-INF/microprofile-config.properties`:

.MicroProfile Telemetry properties
[source,properties]
----
otel.sdk.disabled=false     <1>
otel.traces.exporter=jaeger <2>
----
<1> Enable MicroProfile Telemetry
<2> Set exporter to Jaeger

[source,properties]
---
tracing.service=helidon-greeting
---

=== Tracing at Method Level

[source, java]
----
@Path("/greet")
public class GreetResource {
    /**
     * Return a worldly greeting message.
     *
     * @return {@link String}
     */
    @GET
    @WithSpan("default")
    public String getDefaultMessage() {
        return "Hello World";
    }
}
----

[source,java]
----
@GET
@Path("custom")
@Produces(MediaType.APPLICATION_JSON)
@WithSpan
public JsonObject useCustomSpan(){
    Span span = tracer.spanBuilder("custom")
            .setSpanKind(SpanKind.INTERNAL)
            .setAttribute("attribute", "value")
            .startSpan();
    span.end();

    return JSON.createObjectBuilder()
            .add("Custom Span", span.toString())
            .build();
}
----

[source,java]
----
@Uri("http://localhost:8081/secondary")
private WebTarget target;

@GET
@Path("/outbound")
@WithSpan("outbound")
public String outbound() {
    return target.request().accept(MediaType.TEXT_PLAIN).get(String.class);
}
----


== Additional Information


== Reference

* link:https://download.eclipse.org/microprofile/microprofile-telemetry-1.0/tracing/microprofile-telemetry-tracing-spec-1.0.pdf[MicroProfile Telemetry Specification]
* link:https://opentelemetry.io/docs/[OpenTelemetry Documentation]