///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= WebSocket Introduction
:pagename: websocket-introduction
:description: Helidon WebSocket Introduction
:keywords: helidon, webserver, websocket

Helidon integrates with Tyrus [1] to provide support for the Jakarta WebSocket API [2].
The WebSocket API enables Java applications to participate in WebSocket interactions
as servers as well as clients. The server API supports two flavors: annotated and
programmatic endpoints.

Annotated endpoints, as suggested by their name, use Java annotations to provide
the necessary meta-data to define WebSocket handlers; programmatic endpoints
implement API interfaces and are annotation free. Annotated endpoints tend to be
more flexible since they allow different method signatures depending on the
application needs, whereas programmatic endpoints must implement an interface
and are, therefore, bounded to its definition. This will become more clear as
we dive into some examples in the next few sections.

Helidon has support for WebSockets both in SE and in MP. Helidon SE support
is based on the `TyrusSupport` class which is akin to `JerseySupport`.
Helidon MP support is focused on bean discovery using CDI and extensive use
of annotations, yet it is still possible to configure applications
programmatically with bean discovery disabled if so desired.

As stated above, the Jakarta WebSocket API supports both annotated and
programmatic endpoints. Even though most Helidon MP applications rely
on the use of annotations, and conversely Helidon SE applications do
not, it is worth mentioning that annotated and programmatic endpoints
are supported in both SE and MP.

== Running Example

In the next few sections we shall show the implementation of a simple application
that uses a REST resource to push messages into a shared queue and a
WebSocket endpoint to download all messages, one at a time, over a connection.
This example will show how REST and WebSocket connections can
be seamlessly combined into a Helidon application.

== Helidon SE

The complete Helidon SE example is available here [3]. Let us start by
looking at `MessageQueueService`:

[source,java]
----
public class MessageQueueService implements Service {

    private final MessageQueue messageQueue = MessageQueue.instance();

    @Override
    public void update(Routing.Rules routingRules) {
        routingRules.post("/board", this::handlePost);
    }

    private void handlePost(ServerRequest request, ServerResponse response) {
        request.content().as(String.class).thenAccept(messageQueue::push);
        response.status(204).send();
    }
}
----

This class exposes a REST resource where messages can be posted. Upon
receiving a message, it simply pushes it onto a shared queue and
returns 204 (No Content).

Messages pushed onto the queue can be obtained by opening a WebSocket
connection served by `MessageBoardEndpoint`:

[source,java]
----
public class MessageBoardEndpoint extends Endpoint {

    private final MessageQueue messageQueue = MessageQueue.instance();

    @Override
    public void onOpen(Session session, EndpointConfig endpointConfig) {
        session.addMessageHandler(new MessageHandler.Whole<String>() {
            @Override
            public void onMessage(String message) {
                try {
                    if (message.equals("SEND")) {
                        while (!messageQueue.isEmpty()) {
                            session.getBasicRemote().sendObject(messageQueue.pop());
                        }
                    }
                } catch (Exception e) {
                    // ...
                }
            }
        });
    }
}
----

This is an example of a programmatic endpoint that extends `Endpoint`. The method
`onOpen` will be invoked for every new connection. In this example, the application
registers a message handler for strings, and when the special `SEND` message
is received, it empties the shared queue sending messages one at a time over
the WebSocket connection.

In Helidon SE, REST and WebSocket classes need to be manually registered into
the web server. This is accomplished via a `Routing` builder:

[source,java]
----
    List<Class<? extends Encoder>> encoders =
           Collections.singletonList(UppercaseEncoder.class);

    Routing.builder()
           .register("/rest", new MessageQueueService())
           .register("/websocket",
                TyrusSupport.builder().register(
                        ServerEndpointConfig.Builder.create(
                                MessageBoardEndpoint.class, "/board").encoders(
                                        encoders).build()).build())
                .build();
[source,java]
----

This code snippet uses multiple builders for `Routing`, `TyrusSupport` and `ServerEndpointConfig`.
In particular, it registers `MessageBoardEndpoint.class` at `"/websocket/board"` and associates
with it a _message encoder_. For more information on message encoders and decoders the
reader is referred to [2]; in this example, `UppercaseEncoder.class` simply uppercases every
message sent from the server [3].


== Helidon MP

The equivalent Helidon MP application shown here takes full advantage of
CDI and class scanning and does not require startup code to initialize
the routes given that the necessary information is available from the
code annotations.

The REST endpoint is implemented as a JAX-RS resource, and the shared
queue (in application scope) is directly injected:

[source,java]
----
@Path("rest")
public class MessageQueueResource {

    @Inject
    private MessageQueue messageQueue;

    @POST
    @Path("board")
    @Consumes("text/plain")
    public void push(String s) {
        messageQueue.push(s);
    }
}
----

In this case, we opt for the use of an annotated WebSocket endpoint decorated
by `@ServerEndpoint` that provides all the meta-data which in the SE example
was part of `ServerEndpointConfig`.

[source,java]
----
@ServerEndpoint(
        value = "/board",
        encoders = { UppercaseEncoder.class })
public class MessageBoardEndpoint {

    @Inject
    private MessageQueue messageQueue;

    @OnMessage
    public void onMessage(Session session, String message) {
        if (message.equals("SEND")) {
            while (!messageQueue.isEmpty()) {
                session.getBasicRemote().sendObject(messageQueue.pop());
            }
        }
    }
}
----

Since `MessageBoardEndpoint` is just a POJO, it uses additional
annotations for event handlers such as `@OnMessage`. One advantage of
this approach, much like in the JAX-RS API, is that method
signatures are not fixed. In the snipped above, the parameters
(which could be specified in any order!) include the WebSocket
session and the message received that triggered the call.

So what else is needed to run this Helidon MP app? Nothing else
other than the supporting classes `MessageQueue` and `UppercaseEncoder`.
Helidon MP declares both `@Path` and `@ServerEndpoint` as
bean-defining annotation, so all that is needed is for CDI
discovery to be enabled.

By default, all JAX-RS resources will be placed under the
application path `"/"` and all WebSocket endpoints under
`"/websocket"` for separation. These values can be overridden
by providing subclasses/implementations for `jakarta.ws.rs.Application`
and `jakarta.websocket.server.ServerApplicationConfig`, respectively.
JAX-RS uses `@ApplicationPath` on application subclasses to provide
this root path, but since there is no equivalent in the WebSocket
API, Helidon MP also supports `@ApplicationPath` as an annotation
on `jakarta.websocket.server.ServerApplicationConfig` implementations.

For instance, if in our example we include the following class:

[source,java]
----
@ApplicationPath("/web")
public class MessageBoardApplication implements ServerApplicationConfig {
    @Override
    public Set<ServerEndpointConfig> getEndpointConfigs(
            Set<Class<? extends Endpoint>> endpoints) {
        assert endpoints.isEmpty();
        return Collections.emptySet();      // No programmatic endpoints
    }

    @Override
    public Set<Class<?>> getAnnotatedEndpointClasses(Set<Class<?>> endpoints) {
        return endpoints;       // Returned scanned endpoints
    }
}
----

the root path for WebSocket endpoints will be  `"/web"` instead of the default
`"/websocket"`.

Helidon MP provides developers the option to control the application's `main`,
including the server bootstrap steps. For this reason, the builder for
`io.helidon.microprofile.server.Server` also accepts a class of type
`Class<? extends ServerApplicationConfig>` as a way to configure a
server manually. Using this builder would be required for those applications
for which CDI discovery is disabled.

For more information on the MP version of this example, the reader is
referred to [4].


- [1] https://projects.eclipse.org/projects/ee4j.tyrus
- [2] https://projects.eclipse.org/projects/ee4j.websocket
- [3] (Helidon SE Example)
- [4] (Helidon MP Example)