///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Metrics-Capable Modules
:description: Helidon SE metrics-capable components
:keywords: helidon, metrics, metrics-capable, microprofile, guide
:intro-project-name: {h1-prefix}
:chk: icon:check[]
:x: icon:times[]
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

include::{rootdir}/includes/metrics/metrics-capable-components.adoc[tags=preamble;all-beginning-text;writing-code-intro]

[[writing_SE,SE Application Techniques]]
==== Writing and Packaging a Metrics-capable _Helidon SE Application_
Write your _SE application_ similarly, but do not use the `ComponentMetricsSettings`.
Instead, build a `MetricsSettings` object from the configuration.

.Example code to support disabling metrics usage in a component
[source,java]
----
import io.helidon.config.Config;
import io.helidon.metrics.api.MetricsSettings;
import io.helidon.metrics.api.RegistryFactory;
import io.helidon.webserver.WebServer;


import org.eclipse.microprofile.metrics.MetricRegistry;

public class MyApp {

    private static MetricsSettings metricsSettings;
    static MetricRegistry metricRegistry;

    public static void main(final String[] args) {
        startServer();
    }

    static Single<WebServer> startServer() {
        Config config = Config.create();

        metricsSettings = MetricsSettings.builder() // <1>
                .config(config)
                .build();

        metricRegistry = RegistryFactory.getInstance(metricsSettings) // <2>
                .getRegistry(MetricRegistry.Type.APPLICATION);

        WebServer server = WebServer.builder(createRouting(config)) // <3>
                .config(config.get("server"))
                .addMediaSupport(JsonpSupport.create())
                .build();

        return server.start();
    }

    private static Routing createRouting(Config config) {

        RestServiceSettings restServiceSettings = RestServiceSettings.create(config); // <4>

        MetricsSupport metricsSupport = MetricsSupport.create(metricsSettings, restServiceSettings); // <5>
        GreetService greetService = new GreetService(config);

        return Routing.builder()
                .register(metricsSupport)                  // <6>
                .register("/greet", greetService)
                .build();
    }

}
----
<1> Create and save `MetricsSettings` from config.
<2> Use `MetricsSettings` to get a suitable `RegistryFactory`, and use that to get the application registry.
<3> Pass `config` to `createRouting` which returns the `Routing` to initialize the web server.
<4> Use the `config` to create `RestServiceSettings` which controls the routing name, web context, and CORS set-up for the
metrics endpoint.
<5> Create the `MetricsSupport` instance using the metrics and REST service settings.
<6> Add the properly initialized `MetricsSupport` instance as a service to the routing, along with the app's own service.

Helidon uses the `enabled` value from `MetricsSettings` in providing the correct implementations of both the `RegistryFactory` and the `MetricsSupport`.

include::{rootdir}/includes/metrics/metrics-capable-components.adoc[tags=writing-code-ending]

include::{rootdir}/includes/metrics/metrics-capable-components.adoc[tags=wrap-up]