///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Micrometer Metrics
:description: Helidon Micrometer integration
:keywords: micrometer, helidon, metrics, integration
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

== Contents
- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
** <<Registering and Updating Meters, Registering and Updating Meters>>
** <<Accessing the Helidon Metrics Endpoint, Accessing the Helidon Metrics Endpoint>>
 - <<API, API>>
** <<Using Micrometer with the Helidon Metrics API, Using Micrometer with the Helidon Metrics API>>
 - <<Configuration, Configuration>>
- <<Examples, Examples>>
** <<Register a MeterRegistry-backed Service with the Web Server, Register a MeterRegistry-backed Service with the Web Server>>
** <<Create and Update Meters in Your Application Service, Create and Update Meters in Your Application Service>>
 - <<Additional Information, Additional Information>>
include::{rootdir}/includes/metrics/micrometer-shared.adoc[tags=intro]
include::{rootdir}/includes/dependencies.adoc[tag=maven-dependency]

[source,xml]
.`pom.xml`
----
<dependency>
    <groupId>io.helidon.webserver.observe</groupId>
    <artifactId>helidon-webserver-observe-metrics</artifactId>
</dependency>
<dependency>
    <groupId>io.helidon.metrics.providers</groupId>
    <artifactId>helidon-metrics-providers-micrometer</artifactId>
</dependency>
----
The first dependency adds the metrics observer and the `/observe/metrics` endpoint. It includes Helidon's
Micrometer-based metrics implementation at runtime. The second dependency makes the Micrometer API available when
compiling application code which uses Micrometer types directly, as the examples on this page do.

== Usage
Your application registers and updates Micrometer meters using annotations or direct use of the Micrometer API.

Your users retrieve Micrometer meters using an endpoint which Helidon creates automatically.

=== Registering and Updating Meters
Your code
include::{rootdir}/includes/metrics/micrometer-shared.adoc[tag=use-micrometer-api]

include::{rootdir}/includes/metrics/micrometer-shared.adoc[tag=accessing-endpoint-intro]

== API

=== Using Micrometer with the Helidon Metrics API

Helidon's Micrometer provider backs the neutral Helidon metrics API and the configured metrics publishers.
Application code which needs direct access to the Micrometer API can obtain Helidon's service-owned meter registry and
unwrap its Micrometer registry as described above.

The metrics observer exposes the service-owned registry through the standard `/observe/metrics` endpoint.
See the xref:{rootdir}/se/metrics/metrics.adoc[Helidon Metrics documentation] for information about configuring the observer.

// Configuration
include::{rootdir}/includes/metrics/micrometer-shared.adoc[tag=configuring-endpoint]

== Examples

include::{rootdir}/includes/metrics/micrometer-shared.adoc[tag=example-apps]

The rest of this section takes you through the process of using Micrometer meters from a Helidon SE application:

. Register a service that uses a Micrometer meter registry with the web server.
. Create meters using that meter registry and then update and query those meters.

=== Register a MeterRegistry-backed Service with the Web Server

[source,java]
.Register a service that uses Micrometer
----
include::{sourcedir}/se/metrics/MicrometerSnippets.java[tag=snippet_1, indent=0]
----
<1> Acquire Helidon's service-owned meter registry and unwrap the Micrometer registry which backs it.
<2> Create the service using that registry.
<3> Register the service with the web server.

=== Create and Update Meters in Your Application Service


[source,java]
.Define and use a `Counter`
----
include::{sourcedir}/se/metrics/MicrometerSnippets.java[tag=snippet_2, indent=0]
----
<1> Use the Micrometer meter registry to create the request counter.
<2> Add routing for any request to invoke the method which counts requests by updating the counter.
<3> Update the counter and then delegate the rest of the request processing to the next handler in the chain.

The example registers the counter in Helidon's service-owned registry, so the configured metrics publishers expose it.
If you do not configure any publishers explicitly, Helidon infers a Prometheus publisher.
See xref:{rootdir}/se/metrics/metrics.adoc#usage-publishing[publishing Helidon metrics] for publisher configuration.


== Additional Information

The link:https://micrometer.io[Micrometer website] describes the project as a whole and has links to more information.
