///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Micrometer Metrics
:description: Helidon Micrometer integration
:keywords: micrometer, helidon, metrics, integration
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

== Contents
- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
** <<Registering and Updating Meters, Registering and Updating Meters>>
** <<Accessing the Helidon Micrometer Endpoint, Accessing the Helidon Micrometer Endpoint>>
 - <<API, API>>
** <<The Helidon Micrometer API, The Helidon Micrometer API>>
 - <<Configuration, Configuration>>
- <<Examples, Examples>>
** <<Register a MeterRegistry-backed Service with the Web Server, Register a MeterRegistry-backed Service with the Web Server>>
** <<Create and Update Meters in Your Application Service, Create and Update Meters in Your Application Service>>
 - <<Additional Information, Additional Information>>
include::{rootdir}/includes/metrics/micrometer-shared.adoc[tags=intro]
include::{rootdir}/includes/dependencies.adoc[tag=maven-dependency]

[source,xml]
.`pom.xml`
----
<dependency>
    <groupId>io.helidon.metrics.providers</groupId>
    <artifactId>helidon-metrics-providers-micrometer</artifactId>
</dependency>
----

== Usage
Your application registers and updates Micrometer meters using annotations or direct use of the Micrometer API.

Your users retrieve Micrometer meters using an endpoint which Helidon creates automatically.

=== Registering and Updating Meters
Your code
include::{rootdir}/includes/metrics/micrometer-shared.adoc[tag=use-micrometer-api]

include::{rootdir}/includes/metrics/micrometer-shared.adoc[tag=accessing-endpoint-intro]

== API

=== The Helidon Micrometer API

Helidon provides no special API for dealing with Micrometer meters and meter registries beyond what Micrometer offers itself.

Helidon _does_ give you an easy way to expose a REST endpoint to report the meters stored in the Micrometer meter registry. The link:{micrometer-javadoc-base-url}/io/helidon/integrations/micrometer/MicrometerSupport.html[`MicrometerSupport`] interface
exposes static methods to directly create an instance of `MicrometerSupport` and to return a link:{micrometer-javadoc-base-url}/io/helidon/integrations/micrometer/MicrometerSupport.Builder.html[`Builder`] instance so your
code can fine-tune how the REST service behaves.

// Configuration
include::{rootdir}/includes/metrics/micrometer-shared.adoc[tag=configuring-endpoint]

== Examples

include::{rootdir}/includes/metrics/micrometer-shared.adoc[tag=example-apps]

The rest of this section takes you through the process of using Micrometer meters from a Helidon SE application:

. Register a service that uses a Micrometer meter registry with the web server.
. Create meters using that meter registry and then update and query those meters.

=== Register a MeterRegistry-backed Service with the Web Server

[source,java]
.Register a service that uses Micrometer
----
include::{sourcedir}/se/metrics/MicrometerSnippets.java[tag=snippet_1, indent=0]
----
<1> Acquire the Micrometer meter registry your application will use.
<2> Create the service using that registry.
<3> Register the service with the web server.

=== Create and Update Meters in Your Application Service


[source,java]
.Define and use a `Counter`
----
include::{sourcedir}/se/metrics/MicrometerSnippets.java[tag=snippet_2, indent=0]
----
<1> Use the Micrometer meter registry to create the request counter.
<2> Add routing for any request to invoke the method which counts requests by updating the counter.
<3> Update the counter and then delegate the rest of the request processing to the next handler in the chain.

The example above enrolls the built-in Prometheus meter registry with the default Prometheus registry configuration.
You can change the default setup for built-in registries, and you can enroll other meter registries your application
creates itself.

include::{rootdir}/includes/metrics/micrometer-shared.adoc[tag=overriding-intro]

You can override these defaults using configuration.


==== Using Configuration

include::{rootdir}/includes/metrics/micrometer-shared.adoc[tag=overriding-using-config]


== Additional Information

The link:https://micrometer.io[Micrometer website] describes the project as a whole and has links to more information.
