///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Tracing
:h1Prefix: MP
:description: Helidon MP Tracing Support
:feature-name: MicroProfile Tracing
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc
:microprofile-bundle: true
= :keywords: helidon, tracing, microprofile, micro-profile

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.tracing</groupId>
    <artifactId>helidon-microprofile-tracing</artifactId>
</dependency>
----

== Configuring Tracing with Helidon MP
Tracing support is implemented for both for Helidon MP Server and for Jersey client.
In addition, you need to add one of the tracer implementations:

- <<tracing/02_zipkin.adoc,Zipkin>>
- <<tracing/03_jaeger.adoc,Jaeger>>

You can configure a custom service name using the `tracing.service` configuration property. If this
property is undefined, name is created from JAX-RS Application name, or `Helidon MP` is used if no application
is defined.

All tracer specific configuration is expected in configuration under key `tracing`.

[source,properties]
.Example `microprofile-config.properties` with customized service name.
----
tracing.service=event-service
----

include::../../shared/tracing/common-config.adoc[]

To disable Helidon tracing for web server and security:
[source,properties]
----
tracing.components.web-server.enabled=false
tracing.components.security.enabled=false
----

To disables MP Tracing as by specification:
[source,properties]
----
mp.opentracing.server.skip-pattern=.*
----

== Creating custom spans

Helidon MP fully supports MicroProfile OpenTracing.
You can add custom spans using `@Traced` annotation on methods of CDI beans.

*Note for invoking methods on same class:*
_If you invoke a method on the same class, `@Traced` annotation would be ignored, as it is not
invoked through a CDI proxy and as such cannot be intercepted.
To make sure `@Traced` is honored, use it on JAX-RS resource methods and on CDI bean methods used from other beans._

== Trace propagation across services
Automated trace propagation is supported currently only with Jersey client.

Tracing propagation works automatically as long as you run within the scope of
Helidon MP and use Helidon components to invoke external services.

=== Manual handling of traces in Jersey Client

There is an option to provide `SpanContext` programmatically (such as when writing a command line
application that starts the span manually).

You can either configure the span context as the active span, or explicitly define it as client property.

[source,java]
.Tracing propagation with Jersey client
----
import static io.helidon.tracing.jersey.client.ClientTracingFilter.CURRENT_SPAN_CONTEXT_PROPERTY_NAME;
import static io.helidon.tracing.jersey.client.ClientTracingFilter.TRACER_PROPERTY_NAME;

// ...

Response response = client.target(serviceEndpoint)
    .request()
    // tracer should be provided unless available as GlobalTracer
    .property(TRACER_PROPERTY_NAME, tracer)
    .property(CURRENT_SPAN_CONTEXT_PROPERTY_NAME, spanContext)
    .get();
----

include::../../shared/tracing/common-config.adoc[]

==== Configuration using MP Config

Tracing configuration can be defined in `microprofile-config.properties` file.

[source, properties]
.Tracing configuration
----
tracing.components.web-server.spans.0.name="HTTP Request"
tracing.components.web-server.spans.0.logs.0.name="content-write"
tracing.components.web-server.spans.0.logs.0.enabled=false
----

==== Path based configuration in Helidon Web Server

For Web Server we have a path based support for configuring tracing, in addition
to the configuration described above.

Configuration of path can use any path string supported by the
Web Server. The configuration itself has the same possibilities
as traced configuration described above. The path specific configuration
will be merged with global configuration (path is the "newer" configuration, global is the "older")

[source,properties]
.Configuration properties
----
tracing.paths.0.path="/favicon.ico"
tracing.paths.0.enabled=false
tracing.paths.1.path="/metrics"
tracing.paths.1.enabled=false
tracing.paths.2.path="/health"
tracing.paths.2.enabled=false
tracing.paths.3.path="/greet"
tracing.paths.4.components.web-server.spans.0.name="content-read"
tracing.paths.4.components.web-server.spans.0.new-name="read"
tracing.paths.4.components.web-server.spans.0.enabled=false
----

==== Renaming top level span using request properties

To have a nicer overview in search pane of a tracer, you can customize the top-level span name using configuration.

Example:
[source,properties]
.Configuration properties
----
tracing.components.web-server.spans.0.name="HTTP Request"
tracing.components.web-server.spans.0.new-name: "HTTP %1$s %2$s"
----

This is supported ONLY for the span named "HTTP Request" on component "web-server".

Parameters provided:

1. Method - HTTP method
2. Path - path of the request (such as '/greet')
3. Query - query of the request (may be null)
