--
-- Copyright (c) 2026 Oracle and/or its affiliates.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS SCALAR_VALUE;
DROP TABLE IF EXISTS TX_MATRIX;
CREATE TABLE CONTACT (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(160) UNIQUE
);
INSERT INTO CONTACT (NAME, EMAIL) VALUES ('alpha', 'alpha@example.test');
INSERT INTO CONTACT (NAME, EMAIL) VALUES ('beta', NULL);

CREATE TABLE SCALAR_VALUE (
    ID INTEGER PRIMARY KEY,
    BOOLEAN_VALUE BOOLEAN,
    BYTE_VALUE SMALLINT,
    SHORT_VALUE SMALLINT,
    INTEGER_VALUE INTEGER,
    LONG_VALUE BIGINT,
    FLOAT_VALUE REAL,
    DOUBLE_VALUE DOUBLE PRECISION,
    DECIMAL_VALUE DECIMAL(20, 2),
    STRING_VALUE VARCHAR(160),
    SECOND_STRING_VALUE VARCHAR(160),
    BYTES_VALUE BYTEA,
    LOCAL_DATE_VALUE DATE,
    LOCAL_TIME_VALUE TIME,
    LOCAL_DATE_TIME_VALUE TIMESTAMP,
    OFFSET_TIME_VALUE TIME WITH TIME ZONE,
    OFFSET_DATE_TIME_VALUE TIMESTAMP WITH TIME ZONE,
    DATE_VALUE DATE,
    TIME_VALUE TIME,
    TIMESTAMP_VALUE TIMESTAMP
);
INSERT INTO SCALAR_VALUE (ID) VALUES (1);

CREATE TABLE TX_MATRIX (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DATA_VALUE VARCHAR(40) NOT NULL
);
INSERT INTO TX_MATRIX (DATA_VALUE) VALUES ('baseline');
