///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon Injection
:description: about Helidon Injection
:keywords: helidon, inject, injection, java, microservices, virtual threads
:feature-name: Helidon Injection
:rootdir: {docdir}/..




== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
- <<API, API>>
- <<Configuration, Configuration>>
- <<Examples, Examples>>
- <<Additional Information, Additional Information>>

== Overview

Helidon Injection is an optional feature in Helidon that provides service registry, a lifecycle engine and extensibility for customized code generation.

NOTE: Helidon Injection provides a way to develop non Helidon-specific declarative code using standard Javax/Jakarta annotation types.

The Helidon Injection Framework provides a mix of declarative and programmatic ways to build your application.
Helidon Injection's minimalist, compile-time generated dependency injection (DI) framework and compile-time source code generation has a number of advantages, including:

* enables declarative, Inversion of Control-style programming
* offers visibility into your application by providing "less magic" - understandability and debug-ability of your application
* provides deterministic behavior (instead of depending on reflection and classpath ordering, etc.)
* optimizes performance improvements since binding the model at compile-time is more efficient than computing it at runtime.

== Maven Coordinates


.Injection dependencies
[source,java]

----
<dependency>
    <groupId>io.helidon.inject</groupId>
    <artifactId>helidon-inject-api</artifactId>
    <version>${helidon.version}</version>
</dependency>
<dependency>
    <groupId>io.helidon.inject</groupId>
    <artifactId>helidon-inject-types</artifactId>
    <version>${helidon.version}</version>
</dependency>
----

== Usage

Once you have planned how each of your resources should support Injection, you specify the behavior in one of two ways:



== API

Adding Injection behavior to your Helidon WebServer application involves just a few simple steps.

=== Maven Coordinates

.Injection API pom.xml
[source, java]
----
 <artifactId>helidon-inject-inject</artifactId>
 <name>Helidon Injection API</name>
----


=== Types

The Injection API provides types that are generally useful at compile time to assign special meaning to the type. In this way it also helps with readability and intentions of the code itself.

.Injection types pom.xml
[source, java]
----
 <artifactId>helidon-inject-types</artifactId>
 <name>Helidon Injection Types</name>
----


 * {@link io.helidon.inject.api.Contract} - signifies that the type can be used for lookup in the service registry.
 * {@link io.helidon.inject.api.ExternalContracts} - same as Contract, but applied to the implementation class instead.
 * {@link io.helidon.inject.api.RunLevel} - ascribes meaning for when the service should start.






== Configuration

Injection Config builder



== Examples

//optional

== Additional Information
