///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon SE OIDC Security Provider Guide
:h1Prefix: SE
:description: Helidon OIDC Security Provider
:keywords: helidon, security, guide, oidc, provider

This guide describes how to set up Keycloak and Helidon
to secure your application with OIDC security provider.

== What you need

[width=50%,role="flex, sm7"]
|===
|About 20 minutes
|<<about/03_prerequisites.adoc,Helidon Prerequisites>>
|===

* <<Keycloak Installation,Keycloak Installation>>
* <<Set up Keycloak,Set up Keycloak>>
* <<Set up Helidon,Set up Helidon>>
* <<Restrict access to a specific role,Restrict access to a specific role>>

=== Keycloak Installation

==== On Docker

To install Keycloak with Docker, open a terminal and make sure the port 8080 is free.

[source,bash]
.Enter the following command
----
docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:11.0.2
----

This will start Keycloak on local port 8080. It will create the admin user with username `admin` and password `admin`
Feel free to modify 11.0.2 by any keycloak version of your wish.
If you are running docker behind a proxy server, make sure it is either configured into docker or
disable it. Otherwise, you might face a connection timeout because docker cannot download the required data.

To verify that Keycloak is running correctly, go to the admin console : http://localhost:8080/auth/admin
Log in using the username and password mentioned above: `admin`.

You should be logged in successfully, and it prompts the admin console.

==== On JDK

Download the last version of Keycloak from Keycloak website : https://www.keycloak.org/downloads
In the table Server choose Standalone server distribution. ZIP or Tar format are available, click on either
to download Keycloak.

After extracting the archive file, you should have a directory named keycloak followed by the version. For example,
if you chose version 11.0.2, the folder must be named keycloak-11.0.2.

Open keycloak folder to make it your current directory.
[source,bash]
.Run this command from command prompt to open the directory:
----
cd keycloak-11.0.2
----

===== Start Keycloak

To start keycloak and have it ready for further steps, run the following command.

[source,bash]
.On Linux run:
----
bin/standalone.sh
----

[source,bash]
.On Windows run:
----
bin/standalone.bat
----

Keycloak runs on localhost:8080 by default.

===== Create an admin user

You need to create an admin user because it does not come by default when installing Keycloak.
To do this, open  http://localhost:8080/auth in your favorite browser.

A window `Welcome to Keycloak` should be prompted. If not, check if any error appear in the terminal.

Fill the form by adding Username and Password. Click on `Create` to create the admin user.

Above Administration Console should be printed "User created" in a green rectangle.

To check that the admin user was created correctly, click on Administration user which should redirect you
to a Login form. Enter the Username and Password created earlier to log in.

After successfully logged in, the admin console is prompted.

=== Set up Keycloak

To set up Keycloak properly, go to the admin console: http://localhost:8080/auth/admin

If you are using Docker, use Username `admin` and password `admin` as it is the default admin user.
Otherwise, use the username and password you used to create the admin user.

==== Create a realm

A realm is the place where groups of applications, and their environment, can be created. It gathers :

- One or several applications
- One or several users
- Sessions
- Events
- Clients and their scopes

By default, there is a realm called `Master`. It is used to manage Keycloak. It is not recommended to associate your
application with this realm as it could disturb Keycloak functioning.

To create a new realm to manage your application:

. Open Keycloak admin console http://localhost:8080/auth/admin.
. Hover the mouse over the dropdown in the top-left corner where it says `Master`, and press `Add realm`.
. Fill the form by adding the realm name, `myRealm` for example.
. Click on `Create` to create the new realm.

To verify that your realm is created, on the top-left corner where it said `Master` previously
should be now your realm name or `myRealm` is you followed the example.

To switch from a realm to another, hover the realm name, and the other realm created appear in the dropdown.
Click on any realm name to change the current realm. Make sure all configuration or modification are saved before changing
the current realm or be subject to lose your configuration.

==== Create a user

Initially there are no users in a new realm. An unlimited number of user can be created per realm.
A realm contains resources such as client which can be accessed by users.

To create a new user:

. Open the Keycloak admin console: http://localhost:8080/auth/admin
. Click on `Users` in the left menu
. Press `Add user`
. Fill the form (Username is the only mendatory field) with this value Username: `myUser`
. Click `Save`

A new user is just created but it needs a password to be able to login. To initialize it, do this:

. Click on `Credentials` at the top of the page, under `Myuser`.
. Fill `Password` and `Password confirmation` with the user password of your choice.
. If the `Temporary` field is set to `ON`, the user has to  update password on next login. Click `ON`
to make it `OFF` and prevent it.
. Press `Set Password`.
. A pop-up window is popping off. Click on `Set Password` to confirm the new password.

To verify that the new user is created correctly:

. Open the Keycloak account console: `http://localhost:8080/auth/realms/myRealm/account`.
. Login with `myuser` and password chosen earlier.

You should now be logged-in to the account console where users can manage their accounts.

==== Create a Client

To create your first client:

. Navigate to the left menu, into configure section, click on `Clients`. This window displays a table with every client
from the realm.
. Click on `Create`
. Fill the following:
.. `Client ID` : `myClientID`.
.. `Client Protocol` : `openid-connect`
. Press `Save`
.. Modify `Access type` : `confidential`
.. Update `Valid Redirect URIs` : http://localhost:7987/*
. Click on `Save`

A new tab named `Credentials` is created. Click on it to access this new tab.

- `Client Authenticator` : `Client ID and Secret`
- Click on `generate secret` to generate client secret.

Keycloak is now configured and ready. Keep keycloak running on your terminal and open a new tab to
set up Helidon.

=== Set up Helidon

Use the Helidon SE Maven archetype to create a simple project. It will be used as an example
to show how to set up Helidon. Replace `{helidon-version}` by the latest helidon version.

[source,bash,subs="attributes+"]
.Run the Maven archetype
----
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-se \
    -DarchetypeVersion={helidon-version} \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-se \
    -Dpackage=io.helidon.examples.quickstart.se
----

[source,bash]
.The project will be built and run from the helidon-quickstart-se directory:
----
cd helidon-quickstart-se
----

==== Update project dependencies

Update the pom.xml file and add the following Helidon dependency to the `<dependencies>` section.

[source,xml]
.Add the following dependency to `pom.xml`:
----
<dependency>
    <groupId>io.helidon.security.providers</groupId>
    <artifactId>helidon-security-providers-oidc</artifactId>
</dependency>
----

==== Add OIDC security properties

The OIDC security provider configuration can be joined to helidon configuration file.
This file is located here: `src/main/resources/application.yaml`. It can be easily used to configure the web server
without modifying application code.

[source,yaml]
.Add the following line to application.yaml
----
security:
  providers:
  - abac:
      # Adds ABAC Provider - it does not require any configuration
  - oidc:
      client-id: "myClientID" // <1>
      client-secret: "Client secret generated into Keycloak client credential" // <2>
      identity-uri: "http://localhost:8080/auth/realms/myRealm" // <3>
      audience: "account"
      # proxy-host should be defined if you operate behind a proxy, can be removed otherwise
      proxy-host: ""
      frontend-uri: "http://localhost:7987" // <4>
      server-type: "oidc"
  web-server:
    # protected paths on the web server
    paths:  // <5>
      - path: "/greet"
        methods: ["get"]
        authenticate: true
----
<1> `client-id` must be the same as the one configure in keycloak.
<2> The client secret generate by Keycloak during `Create a client` section.
<3> `identity-uri` is used to redirect the user to keycloak.
<4> `frontend-uri` will direct you back to the application.
<5> `paths` section defines the protected application's path.

Make sure keycloak and the application are not running on the same port.
The application port value can be changed into application.yaml.

[source,yaml]
.Change these properties to configure the server host and port
----
server:
  port: 7987
  host: localhost
----

If the port 7987 is already used, check what port is free on your machine.

[source,yaml]
.Replace the old port into application.yaml
----
server:
  port: "{Your-new-port}"

...

frontend-uri: "http://localhost:{Your-new-port}"
----

==== Configure web server

Once the properties are added, the web server must be set up.
The `Main.createRouting` method gather all configuration properties.

[source,java]
.Add the following to `Main.createRouting` method
----
import io.helidon.security.Security;
import io.helidon.security.integration.webserver.WebSecurity;
import io.helidon.security.providers.oidc.OidcSupport;
...
Security security = Security.create(config.get("security"));    // <1>

return Routing.builder()
                .register(WebSecurity.create(security,config.get("security"))) // <2>
                .register(OidcSupport.create(config))   // <3>
                ...
----
<1> Create the Helidon `Security` instance using configuration.
<2> Register Helidon `WebSecurity` instance using security instance and configuration.
<3> Register Helidon `OidcSupport` instance.

That code is extracting security properties from application.yaml into two steps.
First the Security instance is used to bootstrap security, so the WebSecurity instance
can integrate security into Web Server.
Then, OidcSupport instance registers the endpoint to which OIDC redirects browser after a successful login.

Helidon sample is now set up and ready.

==== Try it !

[source,bash]
.Build the application, skipping unit tests, then run it:
----
mvn package -DskipTests=true
java -jar target/helidon-quickstart-se.jar
----

The tests must be skipped, otherwise it produces test failure. As the `/greet` endpoint for GET request is
now protected, its access is limited, and the tests are not built to take oidc security in account.

. Open your favourite browser and try to access `http://localhost:7987/greet/Michael`.
. You should not be redirected and receive greeting from the application.
. Enter the following into URL : `http://localhost:7987/greet`.
. Keycloak redirect you to its login page.
. Enter the username and associated password:
.. `Username` : `myUser`
.. `Password`: `password`
. After successful log in, keycloak redirect you to the `http://localhost:7987/greet` endpoint and print Hello word.

From the actual settings, the user needs to log in only once, then Keycloak saves all the connection data.

==== Update tests to the secure environment

At this stage of the application, tests cannot pass because of OIDC security. The only way to authenticate a user is
through the front end of that server which can be accessed with the browser for example.

In order to keep security and test the application locally, a new security provider must be set up. By adding specific
configuration to the tests, it is possible to override the application configuration.

The following explains how to set a basic authentication instead of oidc security provider only for the tests. Which means,
at the end of this guide, the application will be secured by oidc security provider, and the tests will use basic authentication.

[source,xml]
.Add the following dependency to `pom.xml`:
----
<dependency>
    <groupId>io.helidon.security.providers</groupId>
    <artifactId>helidon-security-providers-http-auth</artifactId>
    <scope>test</scope>
</dependency>
----

In the test folder `helidon-quickstart-se/src/test`:

[source,bash]
.Create a new directory and another one inside
----
mkdir resources
cd resources
touch application.yaml
----

Open the application.yaml file

[source,yaml]
.Copy these properties into application.yaml
----
app:
  greeting: "Hello"

server:
  port: 7987
  host: localhost

security:
  providers:
    - abac:
      # Adds ABAC Provider - it does not require any configuration
    - http-basic-auth:
        users:
          - login: "jack"
            password: "jackIsGreat"
    - oidc:
        client-id: "Your client ID"
        client-secret: "Your client secret"
        identity-uri: "http://localhost:8080/auth/realms/myrealm"
        audience: "account"
        frontend-uri: "http://localhost:7987"
        server-type: "oidc"
  web-server:
    # protected paths on the web server - do not include paths served by Jersey, as those are protected directly
    paths:
      - path: "/greet"
        methods: ["get"]
        authenticate: true
----

Add the `http-basic-auth` properties in the security -> providers property section. This configuration will be used
by the tests instead of the `java/resources/application.yaml`.

In the `MainTest.java` file, tests need to be modified to check the application security when accessing `/greet` path with a
`GET` method.

[source,java]
.Replace the first webclient call by this one:
----
webClient.get()
                .path("/greet")
                .request()
                .thenAccept(response -> Assertions.assertEquals(401,response.status().code()))
                .toCompletableFuture()
                .get();
----

This piece of code uses the webclient to access the application on `/greet` path with a `GET` method. The http basic
authentication security protects this path, so the client should receive an HTTP 401 code for unauthorized.

Only `jack` user has access to this part of the application.

[source,java]
.Add new check to the testHelloWorld method:
----
webClient.get()
                .path("/greet")
                .headers(headers ->  {
                    String encoding = Base64.getEncoder().encodeToString("jack:jackIsGreat".getBytes());
                    headers.add(Http.Header.AUTHORIZATION, "Basic " + encoding);
                    return headers;
                })
                .request(JsonObject.class)
                .thenAccept(jsonObject -> Assertions.assertEquals("Hello World!", jsonObject.getString("message")))
                .toCompletableFuture()
                .get();
----

The username and password are encoded and placed inside the header in order to authenticate as jack to access the application.
If the authentication is successful, the application send the `Hello World` back as a `JsonObject`.

Now, the project can be build without skipping test.

[source,bash]
.Build the project
----
mvn build install
----

==== Restrict access to a specific role

To give less access to an endpoint, it is possible to configure user role. So the application will only grant access
to the user with the required role.

Add a user and roles to the `helidon-quickstart-se/src/test/resources/application.yaml` and
`helidon-quickstart-se/src/java/resources/application.yaml` file.

[source,yaml]
.Add jack role and create a new user named john:
----
- http-basic-auth:
        users:
          - login: "jack"
            password: "jackIsGreat"
            roles: ["user"]
          - login: "john"
            password: "johnPassword"
            roles: ["admin", "user"]
----

Into the `web-server` section, the `roles-allowed` parameter defines which roles have access to the protected path and method.

[source,yaml]
.Add `admin` role
----
web-server:
    # protected paths on the web server - do not include paths served by Jersey, as those are protected directly
    paths:
      - path: "/greet"
        methods: ["get"]
        roles-allowed: "admin"
        authenticate: true
----

Once it is done, go to the tests to check the application behavior.

[source,java]
.Check that jack does not have access
----
webClient.get()
                .path("/greet")
                .headers(headers -> {
                    String encoding = Base64.getEncoder().encodeToString("jack:jackIsGreat".getBytes());
                    headers.add(Http.Header.AUTHORIZATION,"Basic " + encoding);
                    return headers;
                })
                .request()
                .thenAccept(response -> Assertions.assertEquals(403, response.status().code()))
                .toCompletableFuture()
                .get();
----

The user `jack` has only the `user` role so when accessing protected endpoint, a 401 (unauthorized) http code is returned.

[source,java]
.Check that john has access
----
webClient.get()
                .path("/greet")
                .headers(headers ->  {
                    String encoding = Base64.getEncoder().encodeToString("john:johnPassword".getBytes());
                    headers.add(Http.Header.AUTHORIZATION,"Basic " + encoding);
                    return headers;
                })
                .request(JsonObject.class)
                .thenAccept(jsonObject -> Assertions.assertEquals("Hello World!", jsonObject.getString("message")))
                .toCompletableFuture()
                .get();
----

The user `john` has `user` and `admin` roles, so he is allowed and receives `"Hello World"` as a `JsonObject`.
