///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon SE Health Check Guide
:description: Helidon health checks
:keywords: helidon, health check, health check, health, check
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

This guide describes how to create a sample Helidon SE project
that can be used to run some basic examples using both built-in and custom health checks.

== What You Need

For this 15 minute tutorial, you will need the following:

include::{rootdir}/includes/prerequisites.adoc[tag=prerequisites]

=== Create a Sample SE Project

Generate the project sources using the Helidon SE Maven archetype.
The result is a simple project that can be used for the examples in this guide.

[source,bash,subs="attributes+"]
.Run the Maven archetype:
----
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-se \
    -DarchetypeVersion={helidon-version} \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-se \
    -Dpackage=io.helidon.examples.quickstart.se
----

=== Using the Built-In Health Checks

Helidon has a set of built-in health checks:

* deadlock detection
* available disk space
* available heap memory

The following example will demonstrate how to use the built-in health checks.  These examples are all executed
from the root directory of your project (helidon-quickstart-se).

[source,xml]
.Notice that the built-in health check dependency is already in the project's pom.xml file:
----
<dependency>
    <groupId>io.helidon.health</groupId>
    <artifactId>helidon-health-checks</artifactId>
</dependency>
----

Handling health checks is part of Helidon's observability support.
By default, when you add the dependency for the built-in health checks, Helidon automatically registers the built-in checks.
But the generated project explicitly suppresses the build-in health checks, thereby highlighting the custom health checks it adds.

[source,java]
.Excerpt from `Main.main`:
----
ObserveFeature observe = ObserveFeature.builder()
     .config(config.get("server.features.observe")) // <1>
     .addObserver(HealthObserver.builder() // <2>
         .details(true) // <3>
         .useSystemServices(false) // <4>
         .addCheck(() -> HealthCheckResponse.builder() // <5>
                  .status(HealthCheckResponse.Status.UP)
                  .detail("time", System.currentTimeMillis())
                  .build(), HealthCheckType.READINESS)
         .addCheck(() -> HealthCheckResponse.builder() // <6>
                  .status(isStarted())
                  .detail("time", System.currentTimeMillis())
                  .build(), HealthCheckType.STARTUP)
         .build()) // <7>
     .build();

----
<1> Finds and applies configuration for observability.
<2> Begins preparing the `HealthObserver` according to this app's specific needs.
<3> Turns on detailed output in HTTP responses to the health endpoint.
<4> Suppresses automatic registration of built-in health checks.
<5> Adds a custom readiness health check which always reports `UP`'.
<6> Adds a custom start-up health check.
<7> Builds the `HealthObserver` for addition to the `ObserveFeature`.

To see the built-in health checks, temporarily change `useSystemServices` to `true`:
[source,java]
.Temporarily enable all built-in health checks
----
         .useSystemServices(true)
----

[source,bash]
.Build the application then run it:
----
mvn package
java -jar target/helidon-quickstart-se.jar
----

[source,bash]
.Verify the health endpoint in a new terminal window:
----
curl http://localhost:8080/observe/health
----

[source,json]
.Built-in health checks in the JSON response:
----
{
  "status": "DOWN",
  "checks": [
    ...
    {
      "name": "diskSpace",
      "status": "UP",
      "data": {
        "total": "465.63 GB",
        "percentFree": "15.77%",
        "totalBytes": 499963174912,
        "free": "73.42 GB",
        "freeBytes": 78837497856
      }
    },
    {
      "name": "heapMemory",
      "status": "UP",
      "data": {
        "total": "516.00 MB",
        "percentFree": "99.81%",
        "max": "8.00 GB",
        "totalBytes": 541065216,
        "maxBytes": 8589934592,
        "free": "500.80 MB",
        "freeBytes": 525126760
      }
    },
    {
      "name": "deadlock",
      "status": "UP"
    }
  ]
}

----



=== Adding Custom Health Checks

As illustrated above, the generated `Main` class in the QuickStart project adds two custom health checks.
Your own checks typically assess the conditions in and around your application and report whether the service should be considered started, live, and/or ready.

As a trivial but illustrative example, the custom start-up health check in the generated `Main` class reports that the app is _not_ started until eight seconds after the server has started. After that, the start-up check reports that the app _is_ started.

To see this start-up check in action, stop your running server (press ^C), then rerun it.

[source,bash]
.Stop the application:
----
^C
----
and note the output from the server
[listing]
----
Shutdown requested by JVM shutting down
[0x4fdb2ff3] @default socket closed.
Shutdown finished
----
then restart the server
[source,bash]
----
java -jar target/helidon-quickstart-se.jar
----

In another terminal window, within eight seconds access the health endpoint [source,bash]
.Verify the health endpoint in a new terminal window:
----
curl http://localhost:8080/observe/health
----
and notice the output.
[source,json]
----
{
  "status": "DOWN",                              // <1>
  "checks": [
    {
      "name": "Main$$Lambda/0x00000001310a8dc8", // <2>
      "status": "UP",
      "data": {
        "time": 1697584867358
      }
    },
    {
      "name": "Main$$Lambda/0x00000001310a9a78", // <3>
      "status": "DOWN",
      "data": {
        "time": 1697584867358
      }
    },
...
}
----
<1> Overall health (`DOWN` because at least one check reports `DOWN`).
<2> The custom readiness check (hard-coded as `UP`).
<3> The custom start-up check (`DOWN` because the server has not been up for at least eight seconds yet).

Now wait eight seconds and access the endpoint again.

[source,json]
----
{
  "status": "UP",                                // <1>
  "checks": [
    {
      "name": "Main$$Lambda/0x00000001310a8dc8",
      "status": "UP",
      "data": {
        "time": 1697584869478
      }
    },
    {
      "name": "Main$$Lambda/0x00000001310a9a78", // <2>
      "status": "UP",
      "data": {
        "time": 1697584869478
      }
    },
...
}
----
<1> Overall status (now `UP` because all checks report `UP`).
<2> The custom start-up check (now `UP` because the server has been up at least eight seconds).

=== Accessing Specific Health Check Types
You can choose which category of health check to retrieve when you access the health endpoint by adding the health check type as an additional part of the resource path:

* liveness only - http://localhost:8080/observe/health/live
* readiness only -  http://localhost:8080/observe/health/ready
* startup only - http://localhost:8080/observe/health/started
* all -  http://localhost:8080/observe/health


[source,bash]
.Get only start-up health checks
----
curl http://localhost:8080/observe/started
----

[source,json]
.JSON response:
----
{
  "status": "UP",
  "checks": [
    {
      "name": "Main$$Lambda/0x00000001360a9a78",
      "status": "UP",
      "data": {
        "time": 1697585727515
      }
    }
  ]
}
----

=== Custom Health Check URL Path

You can use a custom URL path for heath checks by setting the `endpoint` for the `HealthObserver`.

[source,java]
.Set a custom endpoint path:
----
ObserveFeature observe = ObserveFeature.builder()
     .config(config.get("server.features.observe"))
     .addObserver(HealthObserver.builder()
     .endpoint("/myhealth") // <1>
     .details(true)
...
----
<1> Changes the health endpoint path to `/myhealth`.

[source,bash]
.Build and run the application, then verify that the health check endpoint responds at `/myhealth`:
----
curl http://localhost:8080/myhealth
----


=== Using Liveness, Readiness, and Startup Health Checks with Kubernetes

The following example shows how to integrate the Helidon health API in an application that implements
health endpoints for the Kubernetes liveness, readiness, and startup probes.

[source,java]
.Add a `readyTime` variable to the `Main` class:
----
private static AtomicLong readyTime = new AtomicLong(0);
----

[source,java]
.Change the `HealthObserver` builder in the `Main.main` method to use new built-in liveness checks and custom liveness, readiness, and startup checks:
----
ObserveFeature observe = ObserveFeature.builder()
    .config(config.get("server.features.observe"))
    .addObserver(HealthObserver.builder()
    .useSystemServices(true)                      // <1>
    .addCheck(() -> HealthCheckResponse.builder()
             .status(readyTime.get() != 0)
             .detail("time", readyTime.get())
             .build(), HealthCheckType.READINESS) // <2>
    .addCheck(() -> HealthCheckResponse.builder()
             .status(readyTime.get() != 0
                     && Duration.ofMillis(System.currentTimeMillis()
                                             - readyTime.get())
                                 .getSeconds() >= 3)
             .detail("time", readyTime.get())
             .build(), HealthCheckType.STARTUP)   // <3>
    .addCheck(() -> HealthCheckResponse.builder()
            .status(HealthCheckResponse.Status.UP)
            .detail("time", System.currentTimeMillis())
            .build(), HealthCheckType.LIVENESS)   // <4>
    .build())
.build();

----
<1> Add built-in health checks.
<2> Add a custom readiness check.
<3> Add a custom start-up check.
<4> Add a custom liveness check.


[source,bash]
.Build and run the application, then verify the liveness, readiness, and started endpoints:
----
curl http://localhost:8080/health/live
curl http://localhost:8080/health/ready
curl http://localhost:8080/health/started
----


[source,bash]
.Stop the application and build the docker image:
----
docker build -t helidon-quickstart-se .
----

[source,yaml]
.Create the Kubernetes YAML specification, named `health.yaml`, with the following content:
----
kind: Service
apiVersion: v1
metadata:
  name: helidon-health // <1>
  labels:
    app: helidon-health
spec:
  type: NodePort
  selector:
    app: helidon-health
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: helidon-health // <2>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helidon-health
  template:
    metadata:
      labels:
        app: helidon-health
        version: v1
    spec:
      containers:
        - name: helidon-health
          image: helidon-quickstart-se
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live // <3>
              port: 8080
            initialDelaySeconds: 5 // <4>
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready // <5>
              port: 8080
            initialDelaySeconds: 5 // <6>
            periodSeconds: 2
            timeoutSeconds: 3
          startupProbe:
            httpGet:
              path: /health/started // <7>
              port: 8080
            initialDelaySeconds: 8 // <8>
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
----
<1> A service of type `NodePort` that serves the default routes on port `8080`.
<2> A deployment with one replica of a pod.
<3> The HTTP endpoint for the liveness probe.
<4> The liveness probe configuration.
<5> The HTTP endpoint for the readiness probe.
<6> The readiness probe configuration.
<7> The HTTP endpoint for the startup probe.
<8> The startup probe configuration.


[source,bash]
.Create and deploy the application into Kubernetes:
----
kubectl apply -f ./health.yaml
----

[source,bash]
.Get the service information:
----
kubectl get service/helidon-health
----

[source,bash]
----
NAME             TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
helidon-health   NodePort   10.107.226.62   <none>        8080:30116/TCP   4s // <1>
----
<1> A service of type `NodePort` that serves the default routes on port `30116`.

[source,bash]
.Verify the health endpoints using port '30116', your port may be different:
----
curl http://localhost:30116/health
----

[source,bash]
.Delete the application, cleaning up Kubernetes resources:
----
kubectl delete -f ./health.yaml
----

=== Summary
This guide demonstrates how to use health checks in a Helidon SE application as follows:

* Access the default health checks
* Create and use custom readiness, liveness, and startup checks
* Customize the health check root path
* Integrate Helidon health check with Kubernetes

Refer to the following reference for additional information:

* link:{javadoc-base-url}/index.html?overview-summary.html[Helidon Javadoc]

