///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:javadoc-base-url-api: {javadoc-base-url}io.helidon.integrations.oci.sdk.cdi/io/helidon/integrations/oci/sdk/cdi

= Oracle Cloud Infrastructure Integration
:h1Prefix: MP
:description: Helidon OCI Integration
:keywords: oci, cdi
:cdi-extension-api-url: https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#spi
:jsr330-singleton-api-url: https://jakarta.ee/specifications/dependency-injection/1.0/apidocs/javax/inject/singleton
:oci-objstore-url: https://docs.cloud.oracle.com/iaas/Content/Object/Concepts/objectstorageoverview.htm
:oci-javasdk-url: https://docs.cloud.oracle.com/iaas/Content/API/SDKDocs/javasdk.htm
:oci-cli-url: https://docs.oracle.com/en-us/iaas/tools/oci-cli/latest/
:oci-objstore-javadoc: https://docs.oracle.com/en-us/iaas/tools/java/latest/com/oracle/bmc/objectstorage/package-summary.html
:feature-name: OCI Integration
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc

Helidon MP OCI Integration provides easy access to
Oracle Cloud Infrastructure using the OCI Java SDK.

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source,xml]
----
<dependency>
     <groupId>io.helidon.integrations.oci.sdk</groupId>
     <artifactId>helidon-integrations-oci-sdk-cdi</artifactId>
</dependency>
----

== The Helidon OCI SDK Extension

When added to your application this link:{cdi-extension-api-url}[CDI portable extension]
provides support for injecting
link:{oci-javasdk-url}[Oracle Cloud Infrastructure SDK Clients]
in your Helidon MicroProfile application.
The extension also handles authenticating with OCI by automatically picking up OCI
credentials from your environment.

== Configuring the Helidon OCI SDK Extension

When you inject an OCI SDK Client object, the Helidon OCI SDK extension
configures and constructs the object for you. The configuration primarily
consists of initializing an OCI `AuthenticationDetailsProvider`. By default
the extension will examine your environment and select the best
`AuthenticationDetailsProvider` and configure it for you.

This means if your environment is already set up to work with the OCI SDK or
the OCI command line, then it is very likely you do not need to do any additional
configuration of the extension. Just add it as a dependency and it will self-configure.

If for some reason you require full control over the OCI configuration you have
that as well. For more information concerning the extension and its configuration
and authentication options see the link:{javadoc-base-url-api}/OciExtension.html[OciExtension]
javadocs. In particular the `oci.auth-strategies` property lets you control which
`AuthenticationDetailsProvider` will be used.

== Accessing OCI Services

Since the Helidion OCI SDK extension supports injecting any OCI client
from the OCI SDK, you can use it to access any OCI service supported by the
OCI SDK. In addition to adding the Helidon OCI SDK Extension dependency
(as described above) you will need to add dependencies for the specific
ODI SDK clients you will use.

You will also need to configure your environment to authenticate with OCI.
It is recommended that you do this first, and verify your configuration
by using the link:{oci-javasdk-url}[OCI CLI] to access the service.

The following documentation will help you get started with some
common OCI Services:

- <<mp/oci/02_object-storage.adoc,OCI Object Storage>>
- <<mp/oci/03_vault.adoc,OCI Vault>>
- <<mp/oci/04_atp.adoc,OCI ATP>>
