///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:javadoc-base-url-api: {javadoc-base-url}io.helidon.integrations.oci.sdk.cdi/io/helidon/integrations/oci/sdk/cdi/

= OCI Object Storage
:h1Prefix: MP
:description: Helidon OCI Object Storage integration
:keywords: oci, objectstorage
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc
:feature-name: OCI Object Storage
:oci-objstore-javadoc: https://docs.oracle.com/en-us/iaas/tools/java/latest/com/oracle/bmc/objectstorage/package-summary.html
:oci-objstore-url: https://docs.oracle.com/en-us/iaas/Content/Object/home.htm

You can use Helidon's <<mp/oci/01_oci.adoc,OCI SDK Extension>>
to access OCI Services. This document describes how to use it to access
OCI Object Storage.

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source,xml]
----
<dependency>
     <groupId>io.helidon.integrations.oci.sdk</groupId>
     <artifactId>helidon-integrations-oci-sdk-cdi</artifactId>
</dependency>
----

Then add a dependency on the OCI SDK's Object Storage API:

[source,xml]
----
<dependency>
    <groupId>com.oracle.oci.sdk</groupId>
    <artifactId>oci-java-sdk-objectstorage</artifactId>
</dependency>
----

== Injecting an Object Storage client

Once you have Helidon's OCI extension added to your application you can inject OCI SDK Clients.

[source,java]
.Field-injection example
----
 @Inject
 private ObjectStorage client;
----

[source,java]
.Constructor-injection example
----
 private final ObjectStorage client;
 @Inject
 public YourConstructor(@Named("orders") ObjectStorage client) {
   super();
   this.client = client;
 }
----

The extension implements this injection point by creating an Object Storage client
object in the link:{jsr330-singleton-api-url}[singleton scope].

== Configuring the Helidon OCI SDK Extension

By default the extension will select and configure an appropriate
OCI Authentication Details Provider for you based on your environment.
For this reason it is recommended that you configure your environment
first and get it working with the link:{oci-javasdk-url}[OCI CLI] before
using the Helidon OCI SDK Extension.

For more information see <<mp/oci/01_oci.adoc, Helidon OCI Extension>>.

== Using the Object Storage client

Once you have injected an ObjectStorage client you can use it as described in:

* link:{oci-objstore-javadoc}[OCI SDK Object Storage Javadocs]
* link:{oci-objstore-url}[OCI Object Storage Overview]
