///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////
:javadoc-base-url-api: {javadoc-base-url}io.helidon.integrations.oci.sdk.cdi/io/helidon/integrations/oci/sdk/cdi/

= OCI ATP
:h1Prefix: MP
:description: Helidon OCI ATP integration
:keywords: oci, atp
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc
:feature-name: OCI atp
:oci-atp-javadoc: https://docs.oracle.com/en-us/iaas/tools/java/latest/com/oracle/bmc/database/package-summary.html
:oci-atp-url: https://docs.oracle.com/en-us/iaas/Content/Database/home.htm

You can use Helidon's <<mp/oci/01_oci.adoc,OCI SDK Extension>>
to access OCI Services. This document describes how to use it to access the
OCI Database Service.

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source,xml]
----
<dependency>
     <groupId>io.helidon.integrations.oci.sdk</groupId>
     <artifactId>helidon-integrations-oci-sdk-cdi</artifactId>
</dependency>
----

Then add dependencies on the OCI SDK's Database API. Your specific
dependencies may differ depending on the OCI SDK features you use.

[source,xml]
----
<dependency>
    <groupId>com.oracle.oci.sdk</groupId>
    <artifactId>oci-java-sdk-database</artifactId>
</dependency>
----

== Injecting a Database client

Once you have Helidon's OCI extension added to your application you can inject
OCI SDK Clients.

[source,java]
.Field-injection example
----
 @Inject
 private Database database;
----

The extension implements these injection points by creating
objects in the link:{jsr330-singleton-api-url}[singleton scope].

== Configuring the Helidon OCI SDK Extension

By default the extension will select and configure an appropriate
OCI Authentication Details Provider for you based on your environment.
For this reason it is recommended that you configure your environment
first and get it working with the link:{oci-javasdk-url}[OCI CLI] before
using the Helidon OCI SDK Extension.

For more information see <<mp/oci/01_oci.adoc, Helidon OCI Extension>>.

== Using the Database client

Once you have injected OCI Database objects you can use them as described in:

* link:{oci-atp-javadoc}[OCI SDK Database Javadocs]
* link:{oci-atp-url}[OCI Database Overview]
