///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= OCI Vault
:description: Helidon OCI Vault integration
:keywords: oci, vault
:feature-name: OCI Vault
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

You can use Helidon's xref:oci.adoc[OCI SDK Extension] to access OCI Services.
This document describes how to use it to access OCI Vault.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
     <groupId>io.helidon.integrations.oci.sdk</groupId>
     <artifactId>helidon-integrations-oci-sdk-cdi</artifactId>
</dependency>
----

Then add dependencies on the OCI SDK's Vault API.
Your specific dependencies may differ depending on the OCI SDK features you use.

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>com.oracle.oci.sdk</groupId>
        <artifactId>oci-java-sdk-vault</artifactId>
    </dependency>
    <dependency>
        <groupId>com.oracle.oci.sdk</groupId>
        <artifactId>oci-java-sdk-keymanagement</artifactId>
    </dependency>
    <dependency>
        <groupId>com.oracle.oci.sdk</groupId>
        <artifactId>oci-java-sdk-secrets</artifactId>
    </dependency>
</dependencies>
----

== Injecting a Vault client

Once you have Helidon's OCI extension added to your application you can inject OCI SDK Clients.

[source,java]
.Field-injection example
----
@Inject
private Vaults vaults;
----

[source,java]
.Constructor-injection example
----
class VaultResource {
    @Inject
    VaultResource(Secrets secrets, KmsCrypto crypto, Vaults vaults) {
        this.secrets = secrets;
        this.crypto = crypto;
        this.vaults = vaults;
    }
}
----

The extension implements these injection points by creating objects in the
 link:{jakarta-inject-javadoc-url}/jakarta/inject/Singleton.html[singleton scope].

== Configuring the Helidon OCI SDK Extension

By default the extension will select and configure an appropriate OCI Authentication Details Provider for you based
 on your environment.

For this reason it is recommended that you configure your environment first and get it working with the
 link:{oci-javasdk-url}[OCI CLI] before using the Helidon OCI SDK Extension.

For more information see xref:oci.adoc[Helidon OCI Extension].

== Using the Vault client

Once you have injected OCI Vault objects you can use them as described in:

* link:{oci-javasdk-vault-javadoc-base-url}/package-summary.html[OCI SDK Vault Javadocs]
* link:{oci-vault-url}[OCI Vault Overview]
