///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Tracing
:description: Helidon Tracing Support
= :keywords: helidon, tracing

== Tracing Support
Helidon includes support for tracing through the `https://opentracing.io/[OpenTracing]` APIs.
Tracing is integrated with WebServer and Security.

Support for specific tracers is abstracted. Your application can depend on
the abstraction layer and provide a specific tracer implementation as a Java
`ServiceLoader` service.


=== Maven Coordinates

Declare the following dependency in your project to use the tracer abstraction:

[source,xml,subs="verbatim,attributes"]
.Tracer Abstraction
----
<dependency>
    <groupId>io.helidon.tracing</groupId>
    <artifactId>helidon-tracing</artifactId>
</dependency>
----

=== Configuring Tracing

To configure tracer with WebServer:

[source,java]
.Configuring OpenTracing `Tracer`
----
ServerConfiguration.builder()
                   .tracer(TracerBuilder.create("my-application")                    // <1>
                                 .collectorUri(URI.create("http://10.0.0.18:9411"))  // <2>
                                 .build())
                   .build()
----
<1> The name of the application (service) to associate with the tracing events
<2> The endpoint for tracing events, specific to the tracer used, usually loaded from Config

=== Configuring Tracing with Helidon MP
There is an additional dependency that adds Tracing support to MP server and Jersey client:

[source,xml,subs="verbatim,attributes"]
.MP Tracing
----
<dependency>
    <groupId>io.helidon.microprofile.tracing</groupId>
    <artifactId>helidon-microprofile-tracing</artifactId>
</dependency>
----

The minimal required configuration is `tracing.service` that contains
the service name to be associated with tracing spans sent by this instance.

All tracer specific configuration is expected in config under `tracing`.

Example `microprofile-config.properties` with tracer configuration:

----
tracing.service=helidon-mp
tracing.protocol=https
tracing.host=tracer.example.com
tracing.port=9411
----

== Trace propagation across services
Tracing propagation is supported currently only with Jersey client.

Tracing propagation works automatically in Helidon MP as long as you execute
the client call in the same thread as the Jersey server side.

_Exceptions that require manual handling_:

- When the resource method is annotated with Fault Tolerance annotations (e.g. `@Fallback`)
- When you use `async()` on the Jersey client request
- When you are not in a Jersey Server scope (e.g. when using Jersey client from Helidon SE)

In such cases, you must provide the SpanContext by hand:
[source,java]
.Tracing propagation with Jersey client (on a different thread)
----
import static io.helidon.tracing.jersey.client.ClientTracingFilter.CURRENT_SPAN_CONTEXT_PROPERTY_NAME;
import static io.helidon.tracing.jersey.client.ClientTracingFilter.TRACER_PROPERTY_NAME;

...

Response response = client.target(serviceEndpoint)
    .request()
    // tracer should be provided unless available as GlobalTracer
    .property(TRACER_PROPERTY_NAME, tracer)
    .property(CURRENT_SPAN_CONTEXT_PROPERTY_NAME, spanContext)
    .get();
----

Tracer and SpanContext can be obtained from `ServerRequest` - in Helidon SE
this is available as part of rouing, in Helidon MP you can inject it into Resource classes:

----
@Context
io.helidon.webserver.ServerRequest serverRequest;

...

SpanContext spanContext = serverRequest.spanContext();
// optional, you could also use GlobalTracer.get() if it is configured
Tracer tracer = req.webServer().configuration().tracer();
----