///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Security Providers
:h1Prefix: SE
:description: Helidon Security providers
:keywords: helidon, security

== Implemented Security Providers

Helidon provides the following security providers for endpoint protection:

[cols="3,2,^1,6"]
|===
^|Provider ^|Type ^|Outbound supported ^|Description

|<<OIDC Provider,OIDC Provider>> |Authentication |✅ |Open ID Connect supporting JWT, Scopes, Groups and OIDC code flow
|<<HTTP Basic Authentication Provider,HTTP Basic Authentication>> |Authentication |✅ |HTTP Basic Authentication support
|<<HTTP Digest Authentication Provider,HTTP Digest Authentication>> |Authentication |🚫 |HTTP Digest Authentication support
|<<Header Authentication Provider,Header Assertion>> |Authentication |✅ |Asserting a user based on a header value
|<<HTTP Signatures Provider,HTTP Signatures>> |Authentication |✅ |Protecting service to service communication through signatures
|<<IDCS Role Mapper,IDCS Roles>> |Role Mapping |🚫 |Retrieves roles from IDCS provider for authenticated user
|<<ABAC Provider,ABAC Authorization>> |Authorization |🚫 |Attribute based access control authorization policies
|===

The following providers are no longer evolved:
[cols="3,2,^1,6"]
|===
^|Provider ^|Type ^|Outbound supported ^|Description

|<<Google Login Provider,Google Login>> |Authentication |✅ |Authenticates a token from request against Google servers
|<<JWT Provider,JWT Provider>> |Authentication |✅ |JWT tokens passed from frontend
|===

=== OIDC Provider
Open ID Connect security provider.

==== Setup
[source,xml]
.Maven dependency
----
<dependency>
    <groupId>io.helidon.security.providers</groupId>
    <artifactId>helidon-security-providers-oidc</artifactId>
</dependency>
----

In Helidon SE, we need to register the redirection support with
routing (in addition to `WebSecurity` that integrates with `WebServer`).
This is not required when `redirect` is set to false.

[source,java]
.Adding support for OIDC redirects
----
Routing routing = Routing.builder()
        .register(WebSecurity.create(config.get("security")))
        .register(OidcSupport.create(config))
        ...
        .build();
----

include::../../shared/security/providers/oidc.adoc[]

include::../../shared/security/providers/http-basic-auth.adoc[]

include::../../shared/security/providers/http-digest-auth.adoc[]

include::../../shared/security/providers/header-assertion.adoc[]

include::../../shared/security/providers/http-signatures.adoc[]

include::../../shared/security/providers/idcs-role-mapper.adoc[]

include::../../shared/security/providers/abac.adoc[]

include::../../shared/security/providers/google-login.adoc[]

include::../../shared/security/providers/jwt.adoc[]

