///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Security Tools
:h1Prefix: SE
:description: Helidon Security Tools
:keywords: helidon, security

== Tools

=== Secure configuration

Support for encrypting secrets in configuration files.
[source,xml]
.Maven Dependency
----
<dependency>
    <groupId>io.helidon.config</groupId>
    <artifactId>helidon-config-encryption</artifactId>
</dependency>
----

=== Key and certificate configuration

Configuration support for accessing private keys, public keys, certificates and
 certificate chains including runtime access to instances of such.
[source,xml]
.Maven Dependency
----
<dependency>
    <groupId>io.helidon.common</groupId>
    <artifactId>helidon-common-key-util</artifactId>
</dependency>
----

