///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= WebServer Integration
:description: Helidon Security WebServer integration
:keywords: helidon, security
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

== WebServer

To integrate xref:../webserver.adoc[web server], add the following dependency to your project's pom.xml file:

[source,xml]
.Maven Dependency
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver-security</artifactId>
</dependency>
----

===  Configure Security with WebServer


There are two steps to configure security with WebServer:

1. Create a security instance and register it with the server.
2. Protect server routes with optional security features.

[source,java]
.Example using builders
----
// web server's Routing
HttpRouting.builder()
    // This is step 1 - register security instance with web server processing
    // security - instance of security either from config or from a builder
    // securityDefaults - default enforcement for each route that has a security definition
    .addFeature(SecurityFeature.create(security).securityDefaults(SecurityFeature.authenticate()))
    // this is step 2 - protect a route
    // protect this route with authentication (from defaults) and role "user"
    .get("/service1", SecurityFeature.rolesAllowed("user"), (req, res) -> {
        processService1Request(req, res);
    })
    .build();
----

[source,java]
.Example using configuration
----
HttpRouting.builder()
    // helper method to load both security and web server security from configuration
    .addFeature(SecurityFeature.create(config))
    // continue with web server route configuration
    .build();
----

[source,yaml]
.Example using configuration (YAML)
----
# This may change in the future - to align with web server configuration, once it is supported
security.web-server:
  # Configuration of integration with web server
  defaults:
    authenticate: true
  paths:
    - path: "/service1/[/{*}]"
      methods: ["get"]
      roles-allowed: ["user"]
----

include::{rootdir}/includes/security/helidon-endpoints.adoc[]

== Reference
* link:{security-integration-webserver-base-url}/module-summary.html[Helidon WebServer Security Integration]
