///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Cloud Security Container Integrations
:description: Helidon Security containers integration
:keywords: helidon, security
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]



The following cloud security containers are integrated with Helidon Security:

- <<WebServer, WebServer>>
- <<Jersey, Jersey >>

== WebServer

To integrate xref:../webserver.adoc[reactive web server], add the following dependency to your project's pom.xml file:

[source,xml]
.Maven Dependency
----
<dependency>
    <groupId>io.helidon.security.integration</groupId>
    <artifactId>helidon-security-integration-webserver</artifactId>
</dependency>
----

=== Configure Security with WebServer

There are two steps to configure security with WebServer:

1. Create a security instance and register it with the server.
2. Protect server routes with optional security features.

[source,java]
.Example using builders
----
// web server's Routing
Routing.builder()
    // This is step 1 - register security instance with web server processing
    // security - instance of security either from config or from a builder
    // securityDefaults - default enforcement for each route that has a security definition
    .register(WebSecurity.create(security).securityDefaults(WebSecurity.authenticate()))
    // this is step 2 - protect a route
    // protect this route with authentication (from defaults) and role "user"
    .get("/service1", WebSecurity.rolesAllowed("user"), (req, res) -> {
        processService1Request(req, res);
    })
    .build();
----

[source,java]
.Example using configuration
----
Routing.builder()
    // helper method to load both security and web server security from configuration
    .register(WebSecurity.create(config))
    // continue with web server route configuration
    .build();
----

[source,yaml]
.Example using configuration (YAML)
----
# This may change in the future - to align with web server configuration, once it is supported
security.web-server:
  # Configuration of integration with web server
  defaults:
    authenticate: true
  paths:
    - path: "/service1[/{*}]"
      methods: ["get"]
      roles-allowed: ["user"]
----

include::{rootdir}/includes/security/helidon-endpoints.adoc[]

== Jersey

Jersey (JAX-RS implementation) can be configured for both inbound and outbound security.

[source,xml]
.Maven Dependency
----
<dependency>
    <groupId>io.helidon.security.integration</groupId>
    <artifactId>helidon-security-integration-jersey</artifactId>
</dependency>
----

=== Inbound security

[source,java]
.Integrate with Jersey
----
ResourceConfig resourceConfig = new ResourceConfig()
    // register JAX-RS resource
    .register(JaxRsResource.class)
    // integrate security
    .register(new io.helidon.security.jersey.SecurityFeature(security));
----

=== Secure a Resource Method

The current approach does not have a configuration option so security must be
 configured through annotations.
Security currently supports @Authenticated and @Authorized. When a resource is annotated with one of these
 annotations (application class, resource class, or resource method), security will
 be triggered.

[source,java]
.Securing a resource method
----
// this is sufficient for security to be triggered, see javadoc for further details
@Authenticated
@Path("/{name}")
@GET
@Produces(MediaType.TEXT_PLAIN)
// due to Jersey approach to path matching, we need two methods to match both the "root" and "root" + subpaths
public String getHelloName(@PathParam("name") String name) {
    return "Hello " + name + ", your current subject: " + securityContext.getSubject();
}
----

=== Access Context

[source,java]
.Support in a JAX-RS resource
----
// inject io.helidon.security.SecurityContext
@Context
private SecurityContext securityContext;

----


=== Outbound Security
Outbound security is automatically registered with Jersey client.
The provider must have outbound security configured for identity to be propagated.

[source,xml]
.Maven Dependency
----
<dependency>
    <groupId>io.helidon.security.integration</groupId>
    <artifactId>helidon-security-integration-jersey-client</artifactId>
</dependency>
----

[source,java]
.Call remote target with outbound security
----
Client client = ClientBuilder.newClient();

try {
    // call the resource, will propagate identity as configured in Security
    String response = client.target("https://www.google.com")
        .request()
        // configure the security context for this request (as client and targets may be re-used)
        .property(ClientSecurity.PROPERTY_CONTEXT, securityContext)
        .get(String.class);
} finally {
    client.close();
}
----

== Reference
* link:{security-integration-jersey-base-url}/module-summary.html[Helidon Jersey Security Integration]
* link:{security-integration-webserver-base-url}/module-summary.html[Helidon WebServer Security Integration]