/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc.tests.database;

import java.util.Map;

import io.helidon.config.Config;
import io.helidon.config.ConfigSources;
import io.helidon.data.jdbc.JdbcClient;

/**
 * H2 fixture shared by imperative and declarative JDBC matrix tests.
 */
public final class H2Database {
    /**
     * JDBC URL used by H2 matrix tests and direct JDBC assertions.
     */
    public static final String URL = "jdbc:h2:mem:jdbc_data_jdbc_matrix;DB_CLOSE_DELAY=-1";

    private static final String GENERATED_KEY_COLUMN_PROPERTY = "helidon.data.jdbc.tests.generated-key-column";

    private H2Database() {
    }

    /**
     * Creates Helidon config for the H2 matrix database.
     *
     * @return config
     */
    public static Config config() {
        System.clearProperty(GENERATED_KEY_COLUMN_PROPERTY);
        JdbcClient client = JdbcClient.builder()
                .connection(connection -> connection
                        .url(URL)
                        .jdbcDriverClassName("org.h2.Driver"))
                .build();
        client.create("DROP TABLE IF EXISTS CONTACT").execute();
        client.create("DROP TABLE IF EXISTS OFFSET_DATE_TIME_VALUE").execute();
        client.create("DROP TABLE IF EXISTS SCALAR_VALUE").execute();
        client.create("DROP TABLE IF EXISTS TX_MATRIX").execute();
        client.create("""
                CREATE TABLE CONTACT (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    NAME VARCHAR(80) NOT NULL,
                    EMAIL VARCHAR(160) UNIQUE
                )
                """).execute();
        client.create("INSERT INTO CONTACT (NAME, EMAIL) VALUES ('alpha', 'alpha@example.test')").execute();
        client.create("INSERT INTO CONTACT (NAME, EMAIL) VALUES ('beta', NULL)").execute();
        client.create("""
                CREATE TABLE SCALAR_VALUE (
                    ID INTEGER PRIMARY KEY,
                    BOOLEAN_VALUE BOOLEAN,
                    BYTE_VALUE TINYINT,
                    SHORT_VALUE SMALLINT,
                    INTEGER_VALUE INTEGER,
                    LONG_VALUE BIGINT,
                    FLOAT_VALUE REAL,
                    DOUBLE_VALUE DOUBLE PRECISION,
                    DECIMAL_VALUE DECIMAL(20, 2),
                    STRING_VALUE VARCHAR(160),
                    SECOND_STRING_VALUE VARCHAR(160),
                    BYTES_VALUE VARBINARY(160),
                    LOCAL_DATE_VALUE DATE,
                    LOCAL_TIME_VALUE TIME,
                    LOCAL_DATE_TIME_VALUE TIMESTAMP,
                    DATE_VALUE DATE,
                    TIME_VALUE TIME,
                    TIMESTAMP_VALUE TIMESTAMP
                )
                """).execute();
        client.create("INSERT INTO SCALAR_VALUE (ID) VALUES (1)").execute();
        client.create("""
                CREATE TABLE OFFSET_DATE_TIME_VALUE (
                    ID INTEGER PRIMARY KEY,
                    LOCAL_DATE_TIME TIMESTAMP,
                    OFFSET_SECONDS INTEGER
                )
                """).execute();
        client.create("INSERT INTO OFFSET_DATE_TIME_VALUE (ID) VALUES (1)").execute();
        client.create("""
                CREATE TABLE TX_MATRIX (
                    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    DATA_VALUE VARCHAR(40) NOT NULL
                )
                """).execute();
        client.create("INSERT INTO TX_MATRIX (DATA_VALUE) VALUES ('baseline')").execute();
        return Config.just(ConfigSources.create(Map.of(
                "data.clients.jdbc.0.name", "@default",
                "data.clients.jdbc.0.connection.url", URL,
                "data.clients.jdbc.0.connection.jdbc-driver-class-name", "org.h2.Driver")));
    }
}
