///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Testing with TestNG
:description: Helidon Testing with TestNG
:keywords: helidon, mp, test, testing, testng
:feature-name: Testing with TestNG
:rootdir: {docdir}/../..
include::{rootdir}/includes/mp.adoc[]

:mp-testing-javadoc-url: {mp-testing-javadoc-base-url}/io/helidon/microprofile/testing
:mp-mocking-javadoc-url: {mp-mocking-javadoc-base-url}/io/helidon/microprofile/testing/mocking
:mp-server-javadoc-url: {mp-server-javadoc-base-url}/io/helidon/microprofile/server
:mp-config-javadoc-url: {mp-config-javadoc-base-url}/io/helidon/microprofile/config
:jakarta-jaxrs-javadoc-url: {jakarta-jaxrs-base-url}/apidocs/jakarta/ws/rs
:jakarta-cdi-javadoc-url: {jakarta-cdi-base-url}/apidocs/jakarta.cdi/jakarta/enterprise
:microprofile-config-javadoc-url: {microprofile-config-base-url}/apidocs/org/eclipse/microprofile/config

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
- <<Examples, Examples>>
- <<Mock Support, Mock Support>>
- <<Virtual Threads, Virtual Threads>>
- <<Reference, Reference>>

== Overview

Helidon provides a TestNG listener that integrates CDI to support testing with Helidon MP.

The test class is added as a CDI bean to support injection and the CDI container is started lazily during test execution.

include::{rootdir}/includes/dependencies.adoc[]
[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.testing</groupId>
    <artifactId>helidon-microprofile-testing-testng</artifactId>
    <scope>test</scope>
</dependency>
----

== Usage

include::{rootdir}/mp/testing/testing-common.adoc[tag=usage]

=== Test Instance Lifecyle

The test instance lifecycle is a pseudo singleton that follows the lifecycle of the CDI container.

I.e. By default, the test instance is re-used between test methods.

NOTE: The test instance is not re-used between CDI container, using a dedicated CDI container implies a new test instance

=== Using meta-annotations
Meta-annotations are supported on both test classes and test methods and can be used as a composition mechanism.

[source,java]
.Class-level meta-annotation
----
include::{sourcedir}/mp/testing/TestingNgSnippets.java[tag=snippet_2, indent=0]
----

[source,java]
.Method-level meta-annotation
----
include::{sourcedir}/mp/testing/TestingNgSnippets.java[tag=snippet_3, indent=0]
----
1. `org.testng.annotations.Test` is not inheritable and should be placed on methods

== API

include::{rootdir}/mp/testing/testing-common.adoc[tag=api]

== Examples

include::{rootdir}/mp/testing/testing-common.adoc[tag=examples]

== Mock Support

include::{rootdir}/mp/testing/testing-common.adoc[tag=mock-support]

=== Using CDI Alternative

link:{jakarta-cdi-javadoc-url}/inject/Alternative.html[`@Alternative`] can be used to replace a CDI bean with an instrumented
instance.

[source,java]
.Mocking using CDI Alternative
----
include::{sourcedir}/mp/testing/TestingNgSnippets.java[tag=snippet_1, indent=0]
----
<1> Create the mock instance in the test class
<2> Create a CDI producer method annotated with `@Alternative`
<3> Set priority to 1 (required by `@Alternative`)
<4> Customize the behavior

== Virtual Threads

include::{rootdir}/mp/testing/testing-common.adoc[tag=virtual-threads]

== Reference

* https://testng.org[TestNG Documentation]
