/*
 * Copyright (c) 2025, 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.integrations.langchain4j.tests.agentic;

import io.helidon.integrations.langchain4j.Ai;

import dev.langchain4j.agentic.declarative.SequenceAgent;
import dev.langchain4j.service.V;

/**
 * AI agent that acts as a router between request categories and expert agents.
 * <p>
 * The {@code ExpertRouterAgent} delegates incoming requests to a {@link CategoryRouter}
 * to determine the appropriate category, and then forwards the request to an
 * {@link ExpertsAgent} for handling by a specific expert. The routing logic is
 * defined by the {@code @SequenceAgent} annotation on the {@code ask} method.
 */
@Ai.Agent("expert-router")
public interface ExpertRouterAgent {

    /**
     * Processes the given user request by first classifying it with {@link CategoryRouter}
     * and then delegating it to the appropriate expert via {@link ExpertsAgent}.
     *
     * @param request the raw user request to be processed
     * @return the textual response generated by the selected expert agent
     */
    @SequenceAgent(outputKey = "response", subAgents = {
            CategoryRouter.class,
            ExpertsAgent.class
    })
    String ask(@V("request") String request);
}
