/*
 * Copyright (c) 2025 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.integrations.langchain4j.tests.agentic;

import io.helidon.integrations.langchain4j.Ai;

import dev.langchain4j.agentic.Agent;
import dev.langchain4j.service.UserMessage;
import dev.langchain4j.service.V;

/**
 * LegalExpert defines an AI‑driven legal analysis capability.
 *
 * @see Ai.Agent
 * @see Ai.ChatModel
 */
@Ai.Agent("legal-expert")
@Ai.ChatModel("google-gemini")
public interface LegalExpert {

    /**
     * Performs a legal analysis of the provided user request using an AI‑driven legal expert.
     *
     * @param request the user request to be examined; may contain any text describing a legal issue or question
     * @return a textual response generated by the AI legal expert that contains the legal analysis and answer
     */
    @UserMessage("""
            You are a legal expert.
            Analyze the following user request under a legal point of view and provide the best possible answer.
            The user request is {{request}}.
            Always start your response with introducing yourself as AI medical expert.
            """)
    @Agent(value = "A legal expert", outputKey = "response")
    String legal(@V("request") String request);
}
