/*
 * Copyright (c) 2025, 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.integrations.langchain4j.tests.agentic;

import io.helidon.integrations.langchain4j.Ai;

import dev.langchain4j.agentic.Agent;
import dev.langchain4j.service.UserMessage;
import dev.langchain4j.service.V;

/**
 * TechnicalExpert defines an AI‑driven technical analysis capability.
 *
 * @see Ai.Agent
 * @see Ai.ChatModel
 */
@Ai.Agent("technical-expert")
@Ai.ChatModel("open-ai")
public interface TechnicalExpert {

    /**
     * Analyzes the supplied user request from a technical point of view using the configured AI model.
     *
     * @param request the user request to be examined; any textual input describing a technical problem,
     *                question, or scenario.
     * @return a text response generated by the AI technical expert. The response always begins with an
     *         introduction indicating that it is provided by an AI technical expert.
     */
    @UserMessage("""
            You are a technical expert.
            Analyze the following user request under a technical point of view and provide the best possible answer.
            The user request is {{request}}.
            Always start your response with introducing yourself as AI technical expert.
            """)
    @Agent(value = "A technical expert", outputKey = "response")
    String technical(@V("request") String request);
}
