/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc.tests.database;

import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.Duration;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

import io.helidon.config.Config;
import io.helidon.config.ConfigSources;
import io.helidon.data.jdbc.JdbcClient;

import org.testcontainers.containers.GenericContainer;
import org.testcontainers.containers.wait.strategy.Wait;
import org.testcontainers.utility.DockerImageName;

/**
 * Oracle Database Free Testcontainers fixture shared by imperative and declarative JDBC tests.
 */
public final class OracleDatabase {
    /**
     * Test-only system property used by common imperative adapters to request Oracle identity columns explicitly.
     */
    public static final String GENERATED_KEY_COLUMN_PROPERTY = "helidon.data.jdbc.tests.generated-key-column";

    private static final DockerImageName IMAGE = DockerImageName.parse(
            "container-registry.oracle.com/database/free:latest-lite");
    private static final Map<String, Config> CONFIG_BY_CONTAINER = new ConcurrentHashMap<>();
    private static final AtomicInteger SCHEMA_COUNTER = new AtomicInteger();
    private static final String PASSWORD = "oracle123";

    private OracleDatabase() {
    }

    /**
     * Creates an Oracle container using the approved image.
     *
     * @return container
     */
    public static GenericContainer<?> container() {
        return new GenericContainer<>(IMAGE)
                .withEnv("ORACLE_PWD", PASSWORD)
                .withExposedPorts(1521)
                .withStartupAttempts(3)
                .waitingFor(Wait.forLogMessage(".*DATABASE IS READY TO USE.*", 1)
                        .withStartupTimeout(Duration.ofMinutes(5)));
    }

    /**
     * Returns Helidon config for a started Oracle container, creating and initializing one schema for each container
     * instance.
     *
     * @param container started container
     * @return config
     */
    public static Config config(GenericContainer<?> container) {
        Objects.requireNonNull(container, "The Oracle test container must not be null.");
        if (!container.isRunning()) {
            throw new IllegalStateException("The Oracle test container must be running.");
        }
        String containerId = Objects.requireNonNull(container.getContainerId(),
                                                    "The running Oracle test container must have an identifier.");
        return CONFIG_BY_CONTAINER.computeIfAbsent(containerId, ignored -> createConfig(container));
    }

    private static Config createConfig(GenericContainer<?> container) {
        String username = "JDBC_IT_" + SCHEMA_COUNTER.incrementAndGet();
        createSchema(container, username);
        JdbcClient client = JdbcClient.builder()
                .connection(connection -> connection
                        .url(jdbcUrl(container))
                        .username(username)
                        .password(PASSWORD.toCharArray())
                        .jdbcDriverClassName("oracle.jdbc.OracleDriver"))
                .build();
        client.create("""
                CREATE TABLE CONTACT (
                    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    NAME VARCHAR2(80) NOT NULL,
                    EMAIL VARCHAR2(160) UNIQUE
                )
                """).execute();
        client.create("INSERT INTO CONTACT (NAME, EMAIL) VALUES ('alpha', 'alpha@example.test')").execute();
        client.create("INSERT INTO CONTACT (NAME, EMAIL) VALUES ('beta', NULL)").execute();
        client.create("""
                CREATE TABLE SCALAR_VALUE (
                    ID NUMBER(10) PRIMARY KEY,
                    BOOLEAN_VALUE NUMBER(1),
                    BYTE_VALUE NUMBER(3),
                    SHORT_VALUE NUMBER(5),
                    INTEGER_VALUE NUMBER(10),
                    LONG_VALUE NUMBER(19),
                    FLOAT_VALUE BINARY_FLOAT,
                    DOUBLE_VALUE BINARY_DOUBLE,
                    DECIMAL_VALUE NUMBER(20, 2),
                    STRING_VALUE VARCHAR2(160),
                    SECOND_STRING_VALUE VARCHAR2(160),
                    BYTES_VALUE RAW(160),
                    LOCAL_DATE_VALUE DATE,
                    LOCAL_TIME_VALUE TIMESTAMP,
                    LOCAL_DATE_TIME_VALUE TIMESTAMP,
                    OFFSET_TIME_VALUE TIMESTAMP WITH TIME ZONE,
                    OFFSET_DATE_TIME_VALUE TIMESTAMP WITH TIME ZONE,
                    DATE_VALUE DATE,
                    TIME_VALUE TIMESTAMP,
                    TIMESTAMP_VALUE TIMESTAMP
                )
                """).execute();
        client.create("INSERT INTO SCALAR_VALUE (ID) VALUES (1)").execute();
        client.create("""
                CREATE TABLE TX_MATRIX (
                    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    DATA_VALUE VARCHAR2(40) NOT NULL
                )
                """).execute();
        client.create("INSERT INTO TX_MATRIX (DATA_VALUE) VALUES ('baseline')").execute();
        System.setProperty(GENERATED_KEY_COLUMN_PROPERTY, "ID");
        return Config.just(ConfigSources.create(Map.of(
                "data.clients.jdbc.0.name", "@default",
                "data.clients.jdbc.0.connection.url", jdbcUrl(container),
                "data.clients.jdbc.0.connection.username", username,
                "data.clients.jdbc.0.connection.password", PASSWORD,
                "data.clients.jdbc.0.connection.jdbc-driver-class-name", "oracle.jdbc.OracleDriver")));
    }

    private static void createSchema(GenericContainer<?> container, String username) {
        try (var connection = DriverManager.getConnection(jdbcUrl(container), "system", PASSWORD);
             var statement = connection.createStatement()) {
            statement.executeUpdate("CREATE USER " + username + " IDENTIFIED BY \"" + PASSWORD + "\"");
            statement.executeUpdate("GRANT CONNECT, RESOURCE TO " + username);
            statement.executeUpdate("GRANT UNLIMITED TABLESPACE TO " + username);
        } catch (SQLException e) {
            throw new IllegalStateException("Could not create the Oracle integration test schema.", e);
        }
    }

    private static String jdbcUrl(GenericContainer<?> container) {
        return "jdbc:oracle:thin:@localhost:%s/FREEPDB1".formatted(container.getMappedPort(1521));
    }
}
