///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= LangChain4J Coherence Provider
:description: LangChain4J Coherence
:keywords: helidon, AI, LangChain4J, LC4J, Coherence
:feature-name: LangChain4J Integration
:rootdir: {docdir}/../../..

include::{rootdir}/includes/se.adoc[]

== Contents

* <<Overview, Overview>>
* <<Maven Coordinates, Maven Coordinates>>
* <<Components, Components>>
** <<CoherenceEmbeddingModel, CoherenceEmbeddingModel>>
* <<Additional Information, Additional Information>>

== Overview

This module adds support for the Coherence embedding store.

== Maven Coordinates

In addition to the xref:langchain4j.adoc#maven-coordinates[Helidon integration with LangChain4J core dependencies], you must add the following:

[source,xml]
----
<dependency>
    <groupId>io.helidon.integrations.langchain4j.providers</groupId>
    <artifactId>helidon-integrations-langchain4j-providers-coherence</artifactId>
</dependency>
----

== Components

=== CoherenceEmbeddingModel

To automatically create and add `CoherenceEmbeddingModel` to the service registry add the following lines to `application.yaml`:

[source,yaml]
----
langchain4j:
  coherence:
    embedding-store:
      enabled: true
      session: "session"
      name: "namedMap"
      normalize-embeddings: false
      index: "hnsw"
      dimension: 768
      embedding-model:
        service-registry.named: beanName
----

If `enabled` is set to `false`, the configuration is ignored, and the component is not created.

Full list of configuration properties:

[cols="3,3a,5a"]

|===
|Key |Type |Description

|`embedding-model`|string | Allows to configure embedding model by specifying named bean using `embeddingModel.service-registry.named: beanName`. Default embedding model is used otherwise, if exists.
|`dimension` |integer |The number of dimensions in the embeddings that will be stored in vector store.
|`enabled` |boolean |If set to `true`, Coherence embedding store will be enabled.
|`index` |string |Specifies vector index type use to create a vector index used to query embeddings. Only `hnsw` is supported.
|`name` |string |Specifies name of the Coherence `com.tangosol.net.NamedMap` use to store embeddings.
|`normalize-embeddings` |boolean |A flag that when true, forces normalization of embeddings on adding and searching.
|`session` |string |The name of the `com.tangosol.net.Session` use to obtain the `com.tangosol.net.NamedMap` as specified with `name`.

|===


== Additional Information

* xref:langchain4j.adoc[LangChain4J Integration]
* https://docs.langchain4j.dev/integrations/embedding-stores/coherence[langChain4J Coherence Embedding Store Documentation]