///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= LangChain4J Core Components
:description: LangChain4J Core Components
:keywords: helidon, AI, LangChain4J, LC4J
:feature-name: LangChain4J Integration
:rootdir: {docdir}/../../..

include::{rootdir}/includes/se.adoc[]

== Contents

* <<Overview, Overview>>
* <<Maven Coordinates, Maven Coordinates>>
* <<Components, Components>>
** <<EmbeddingStoreContentRetriever, EmbeddingStoreContentRetriever>>
* <<Additional Information, Additional Information>>

== Overview

This module adds support for selected LangChain4J core components.

== Maven Coordinates

No additional dependencies are required beyond the xref:langchain4j.adoc#maven-coordinates[LangChain4J integration core dependencies].

== Components

=== EmbeddingStoreContentRetriever

To automatically create and add `EmbeddingStoreContentRetriever` to the service registry add the following lines to `application.yaml`:

[source,yaml]
----
langchain4j:
  rag:
    embedding-store-content-retriever:
      enabled: true
      embedding-model: "@default"
      embedding-store: "@default"
----

If `enabled` is set to `false`, the configuration is ignored, and the component is not created.

Full list of configuration properties:

[cols="3,3a,5a"]

|===
|Key |Type |Description

|`display-name` |string |Display name.
|`enabled` |boolean |If set to `false`, embedding store content retriever will be disabled even if configured.
|`max-results` |int |Maximum number of results.
|`min-score` |double |Minimum score threshold.
|`embedding-model` |string |Name of the service in the service registry that implements `dev.langchain4j.model.embedding.EmbeddingModel`. Use `@default` (the default option) to refer to the unnamed service.
|`embedding-store` |string |Name of the service in the service registry that implements `dev.langchain4j.model.embedding.EmbeddingStore<TextSegment>`. Use `@default` (the default option) to refer to the unnamed service.

|===

== Additional Information

* xref:langchain4j.adoc[LangChain4J Integration]
