///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Helidon guides
:keywords: helidon, java, microservices, microprofile, guides

== Getting Started

[PILLARS]
====
[CARD]
.Quickstart SE
[link=guides/02_quickstart-se.adoc]
--
Quickly create your first Helidon SE application in under 5 minutes.
--

[CARD]
.Quickstart MP
[link=guides/03_quickstart-mp.adoc]
--
Quickly create your first Helidon MP application in under 5 minutes.
--
====

== More Guides

[PILLARS]
====
[CARD]
.Create Docker Images
[link=guides/04_dockerfile.adoc]
--
Learn how to package your application and the necessary runtime dependencies as
 a Docker image.
--

[CARD]
.Build Container Images with Jib
[link=guides/05_jib.adoc]
--
Learn how to use Jib to create a container image without Docker.
--

[CARD]
.Deploying to OKE
[link=guides/06_Oracle_Kubernetes.adoc]
--
Learn how to deploy your application to Oracle Cloud Infrastructure Container
 Engine for Kubernetes (OKE).
--

====