///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Helidon guides
:keywords: helidon, java, microservices, microprofile, guides

== Getting Started

[PILLARS]
====
[CARD]
.Quickstart SE
[link=guides/02_quickstart-se.adoc]
--
Quickly create your first Helidon SE application in under 5 minutes.
--

[CARD]
.Quickstart MP
[link=guides/03_quickstart-mp.adoc]
--
Quickly create your first Helidon MP application in under 5 minutes.
--
====

== More Guides

[PILLARS]
====
[CARD]
.Create Docker Images
[link=guides/04_dockerfile.adoc]
--
Learn how to package your application and the necessary runtime dependencies as
 a Docker image.
--

[CARD]
.Build Container Images with Jib
[link=guides/05_jib.adoc]
--
Learn how to use Jib to create a container image without Docker.
--

[CARD]
.Deploying to OKE
[link=guides/06_Oracle_Kubernetes.adoc]
--
Learn how to deploy your application to Oracle Cloud Infrastructure Container
 Engine for Kubernetes (OKE).
--

.Setting Up Data Sources
[link=guides/07_datasource.adoc]
--
Learn how to configure and use data sources from your Helidon MP application.
--

[CARD]
.JPA Guide
[link=guides/09_jpa.adoc]
--
Learn how to use JPA from your Helidon MP application.

[CARD]
.MP Metrics Guide
[link=guides/09_metrics_mp_guide.adoc]
--
Learn how to use Helidon MP built-in and application metrics.
--

[CARD]
.SE Metrics Guide
[link=guides/09_metrics_se_guide.adoc]
--
Learn how to use Helidon SE built-in and application metrics.
--

[CARD]
.MP Health Check Guide
[link=guides/07_health_mp_guide.adoc]
--
Learn how to use Helidon MP built-in and custom health checks.
--

[CARD]
.SE Health Check Guide
[link=guides/07_health_se_guide.adoc]
--
Learn how to use Helidon SE built-in and custom health checks.
--

[CARD]
.MP Config Guide
[link=guides/11_config_mp_guide.adoc]
--
Learn how to configure a Helidon MP application.
--

[CARD]
.SE Config Guide
[link=guides/11_config_se_guide.adoc]
--
Learn how to configure a Helidon SE application.
--

[CARD]
.Build Native Images with GraalVM
[link=guides/15_graalnative.adoc]
--
Learn how to use GraalVM to build a native executable for your Helidon SE application.
--
====

== Tutorials

[PILLARS]
====

[CARD]
.Helidion MP Tutorial
[link=guides/91_mp-tutorial.adoc]
--
Learn how to build an Helidon MicroProfile (MP) application from scratch.
--
====
