///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Guides Overview
:description: Helidon guides
:keywords: helidon, java, microservices, microprofile, guides

== Getting Started

[PILLARS]
====
[CARD]
.Quickstart SE
[link=guides/02_quickstart-se.adoc]
--
Quickly create your first Helidon SE application in under 2 minutes.
--

[CARD]
.Quickstart MP
[link=guides/03_quickstart-mp.adoc]
--
Quickly create your first Helidon MP application in under 2 minutes.
--
====

== More Guides

[PILLARS]
====
[CARD]
.Create Docker Images
[link=guides/05_Dockerfile.adoc]
--
Package your application and the necessary runtime dependencies as a Docker image that also contains the Java runtime.
--
====