///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Guides Overview
:description: Helidon guides
:keywords: helidon, java, microservices, microprofile, guides

== Basics

[PILLARS]
====
[CARD]
.SE REST Web Service
[link=guides/02_SE_REST_web-service.adoc]
--
Use Helidon SE to create a RESTful web service that accepts HTTP requests.
--

[CARD]
.MP REST Web Service
[link=guides/03_MP_REST_web-service.adoc]
--
Use Helidon MP to create a JAX-RS RESTful web service.
--
====

== More Guides

[PILLARS]
====
[CARD]
.Create Docker Images
[link=guides/05_Dockerfile.adoc]
--
Package your application and the necessary runtime dependencies as a Docker image that also contains the Java runtime.
--
====