
///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:example-src-url: https://github.com/oracle/helidon/tree/master/examples/guides/se-rest-web-service/src/main/java


= Creating a ReSTful Web Service using Helidon SE
:description: Helidon SE ReSTful Web Service Guide
:keywords: helidon, guide, rest, web, service

This guide takes you through creating, building, and running a simple ReSTful web service using Helidon SE.

image:guides/baseline-schedule-24px.svg["Duration", title="Duration"] 15 minutes

== What You'll Learn
You will learn how to write a simple ReSTful web service using Helidon SE and its
reactive web server and how to build and run it using Maven.

== What You'll Need

* A text editor or an IDE
* JDK 1.8 or later
* Maven 3.5 or later

== Creating the Application
You have two choices:

* <<do-it-yourself,Do-it-yourself>> - Create a new maven project and add the code to it yourself.
* <<outsource-it,Outsource it>> - Clone a github repository or download a zip containing the finished example.

Either way you'll follow the same steps to build and run the application.

=== Do-it-yourself [[do-it-yourself]]

[source,java]
----
include::https://github.com/oracle/helidon/blob/master/examples/helidon-quickstart-se/src/main/java/io/helidon/examples/quickstart/se/Main.java
----

=== Outsource It [[outsource-it]]

== Building the Project

== Running the Application

 
