///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2019, Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////
:adoc-dir: {guides-dir}

= Deploying to OKE
:description: Helidon Oracle Container Engine for Kubernetes (OKE) Guide
:keywords: helidon, guide, oracle, kubernetes

Push a Docker image of your Helidon application to Oracle Cloud Infrastructure Registry (OCIR), and deploy the image from the registry to Oracle Cloud Infrastructure Container Engine for Kubernetes (OKE). 

== What You Need

|===
|About 10 minutes
| <<getting-started/01_prerequisites.adoc,Helidon prerequisites>>
|An OKE cluster. See http://www.oracle.com/webfolder/technetwork/tutorials/obe/oci/oke-full/index.html[Creating a Cluster with Oracle Cloud Infrastructure Container Engine for Kubernetes].
|A docker image of your application. See link:05_Dockerfile.adoc[Creating Docker Images].
|===

== Push Your Image to OCIR

1. Sign in to the Oracle Cloud Infrastructure (OCI) web console. 

   * You must be either a local user created by an administrator in OCI Identity and Access Management or a synchronized user created automatically by a federated identity provider. 

   * You must in the `Administrators` group or another group that has the `REPOSITORY_CREATE` permission. 
   
2. Generate an authentication token.
+
See https://docs.cloud.oracle.com/iaas/Content/Registry/Tasks/registrygettingauthtoken.htm[Getting an Auth Token].
+
NOTE: Remember to copy the generated token. You won't be able to access it again.

3. Log in to the OCIR Docker CLI:
+
a. In a terminal window, enter:
   `docker login <region-code>.ocir.io`
+
* `<region-code>` is the code for the OCI region that you're using. 
+
For example, the region code for Phoenix is `phx`. See https://docs.cloud.oracle.com/iaas/Content/General/Concepts/regions.htm[Regions and Availability Domains].

* `ocir.io` is the OCI registry name.
+
b. At the `username` prompt, enter your user name in the format `<tenancy_name>/<username>`. 
+
c. At the `password` prompt, enter the auth token that you generated earlier.

4. Tag the image that you want to push to the registry:
+
```
docker tag quickstart-se:latest <region-code>.ocir.io/<tenancy-name>/<repo-name>/<image-name>:<tag>
```

5. Push the image to the Registry:
+
```
docker push <region-code>.ocir.io/<tenancy-name>/<repo-name>/<image-name>:<tag>
```
+
* `<region-code>` is the code for the OCI region that you're using. See https://docs.cloud.oracle.com/iaas/Content/General/Concepts/regions.htm[Regions and Availability Domains].

* `ocir.io` is the OCI registry name.

* `<tenancy-name>` is the name of the tenancy that owns the repository to which you want to push the image.

* `<repo-name>` is optional. It is the name of a repository to which you want to push the image (for example, `project01`). If you don't specify a repository name, the name of the image is used as the repository name in OCIR.

* `<image-name>` is the name you want to give the image in OCIR (for example, `helloworld`).

* `<tag>` is an image tag you want to assign the image in OCIR (for example, `latest`).

6. Get the full path of the image in OCIR:
+
a. In the OCI web console, navigate to *Developer Services*, and select *Registry (OCIR)*.

b. Select the repository and image that you created.

c. Copy the value displayed in the *Full Path* field.
+
The path is in the format `<tenancy>/<repository>/<image>:<tag>`
+
Example: `oracle-cloudnative/example/quickstart-se:latest`

6. Create a namespace (for example, `helidon`) for the project:
+
```
kubectl create namespace helidon
```

7. (Optional) Create an image-pull secret.
+
NOTE: By default, the repository that you created is private. To allow Kubernetes to authenticate with the container registry and pull the private image, you must create and use an image-pull secret. If you choose to make your repository public, then skip this step.
+
```
kubectl create secret docker-registry ocirsecret --docker-server=<region-code>.ocir.io --docker-username='<tenancy-name>/<oci-username>' --docker-password='<oci-auth-token>' --docker-email='<email-address> --namespace helidon
```

8. In the application's `/target/app.yaml` file (created with Maven), add the following fields under `spec` in the `deployment` section:
+
a. (Optional) Add the image-pull secret that you created in the previous step:
+
This step is necessary only if you created an image-pull secret and want to keep the repository private.
+
[source, yaml]
----
imagePullSecrets: 
        - name: ocirsecret
----
b. In the `image` field under `containers`, specify the image path that you copied earlier from the OCI console, in the following format:
+
`<region-code>.ocir.io/<tenancy>/<repository>/<image>:<tag>`
+
Here's an example of an updated yaml file after adding the image-pull secret and the image path:
+
[source, yaml]
----
    spec:
      imagePullSecrets: 
      - name: ocirsecret
      containers:
      - name: helidon-se
        image: phx.ocir.io/oracle-cloudnative/example/quickstart-se:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
----

=== Deploy the Image to Kubernetes

1. Change to the `quickstart-se directory`.

2. Deploy the application to the `helidon` namespace within your Kubernetes cluster:
+
```
kubectl create -f target/app.yaml -n helidon
```

3. Get the `NodePort` number for your new pod:
+
```
kubectl get svc -n helidon
```
4. Get the IP address for your cluster nodes:
+
```
kubectl get nodes
```
5. Construct the URL of the deployed pod as follows:
```
http://<NodeIpAddress>:<NodePort>
```

Browse to (or cURL) the `http://<NodeIpAddress>:<NodePort>/greet` endpoint. It returns the same JSON response as when the application was deployed locally.
