///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Setting Up Data Sources
:description: Helidon MP Data Source Guide
:keywords: helidon, guide, datasource, microprofile

This guide shows how to configure and use named
https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`DataSource`]s
in your Helidon MP application.

== What You Need

|===
|About 20 minutes
|<<about/03_prerequisites.adoc,Helidon Prerequisites>>
|The Maven coordinates for your database vendor's JDBC-compliant database driver library
|===

== Add Your Database Driver to Your Helidon MP Application's Runtime Classpath

Make sure your database vendor's driver library is present on your
application's runtime classpath.  In a Maven project, add an
appropriate
https://maven.apache.org/ref/3.6.1/maven-model/maven.html#class_dependency[`<dependency>`]
element as a child element of the `<dependencies>` element in your
`pom.xml`, referencing the driver library.  Here's an example that
includes the
https://search.maven.org/classic/#artifactdetails%7Ccom.h2database%7Ch2%7C1.4.199%7Cjar[H2
database driver library]:

[source,xml]
----
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>1.4.199</version>
    <scope>runtime</scope> <!--1-->
</dependency>
----
<1> Note the `<scope>` is `runtime`.

== Add a Helidon Connection Pool Extension to Your Helidon MP Application's Runtime Classpath

Helidon contains two <<extensions/01_overview.adoc,extensions>> that
supply _connection pools_, infrastructure that allows efficient use of
database connections:

1. <<extensions/02_cdi_datasource-hikaricp.adoc,HikariCP extension>>:
   an extension that integrates the
   https://github.com/brettwooldridge/HikariCP[Hikari connection pool]
   into Helidon MP applications

2. <<extensions/02_cdi_datasource-ucp.adoc,Oracle Universal Connection
   Pool extension>>: an extension that integrates
   https://docs.oracle.com/en/database/oracle/oracle-database/19/jjucp/index.html[Oracle's
   Universal Connection Pool] into Helidon MP applications

Each connection pool offers tradeoffs in terms of size, efficiency and
features.

=== Add the Hikari Connection Pool to the Runtime Classpath

If you choose to integrate the Hikari connection pool into your
Helidon MP application, then add an appropriate
https://maven.apache.org/ref/3.6.1/maven-model/maven.html#class_dependency[`<dependency>`]
element as a child element of the `<dependencies>` element in your
`pom.xml`, referencing the HikariCP extension:

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>io.helidon.integrations.cdi</groupId>
    <artifactId>helidon-integrations-cdi-datasource-hikaricp</artifactId>
    <version>{helidon-version}</version>
    <scope>runtime</scope> <!--1-->
</dependency>
----
<1> Note the `<scope>` is `runtime`.

=== Add the Oracle Universal Connection Pool to the Runtime Classpath

If, instead, you shoose to integrate the Oracle Universal Connection Pool into your Helidon MP application, then add an appropriate
https://maven.apache.org/ref/3.6.1/maven-model/maven.html#class_dependency[`<dependency>`]
element as a child element of the `<dependencies>` element in your
`pom.xml`, referencing the Oracle Universal Connection Pool extension:

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>io.helidon.integrations.cdi</groupId>
    <artifactId>helidon-integrations-cdi-datasource-ucp</artifactId>
    <version>{helidon-version}</version>
    <scope>runtime</scope> <!--1-->
</dependency>
----
<1> Note the `<scope>` is `runtime`.

== Configure the Connection Pool

Regardless of which connection pool you integrate into your Helidon MP
application via the mechanisms described above, you will need to tell
that connection pool's machinery how many pools to set up, what to
name each of them so you can refer to them inside your code, and how
each of them should connect to a database.

Helidon MP, because it is a conformant MicroProfile specification
implementation, uses <<microprofile/06_configuration.adoc,an
implementation>> of the
https://github.com/eclipse/microprofile-config[MicroProfile Config
specification] to acquire configuration, so is subject to that
specification's rules.  Some of those rules are that, out of the box,
any MicroProfile Config implementation (such as
<<microprofile/06_configuration.adoc,Helidon's>>) must automatically
consider system properties, environment variables and a classpath
resource named `META-INF/microprofile-config.properties`.
<<microprofile/02_server-configuration.adoc,Helidon MP additionally
considers a runtime classpath resource named `application.yaml`>>.

In this guide, we'll set up configuration in an `application.yaml`
classpath resource.  Different syntax may apply if you use a different
MicroProfile Config
https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#configsources[`ConfigSource`
implementation], but the principles described below are the same.

=== Configure the Hikari Connection Pool

If you have chosen to integrate the Hikari connection pool into your
Helidon MP application, then ensure the following YAML is present in
your `application.yaml`, and that your `application.yaml` is present
on the runtime classpath of your Helidon MP application:

[source,yaml]
----
javax:
  sql:
    DataSource: <1>
      test: <2>
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource <3>
        dataSource: <4>
          password: ""
          url: jdbc:h2:mem:test
          user: sa
----

<1> The YAML consisting of a top level `javax`
https://yaml.org/spec/1.1/current.html#key/information%20model[mapping]
whose sole element is a `sql` mapping whose sole mapping is a
`DataSource` mapping corresponds to the Java type of
https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`javax.sql.DataSource`].
This preamble specifies the type of Java object that will supply
database connections in your code.  Its sole element is a mapping
whose key is the name of the data source in question.  This preamble
is required.

<2> This mapping's key is the name of your data source, and will be
referenced in your application code.  Its elements are
https://github.com/brettwooldridge/HikariCP/blob/dev/README.md#configuration-knobs-baby[Hikari
connection pool properties].  The data source name may be anything you
like.  By convention, data source names are usually single words
consisting of alphanumeric characters only.

<3> This is the class name of the actual
https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`javax.sql.DataSource`]
implementation provided by your database vendor.  In this example,
which uses the https://www.h2database.com/html/main.html[H2 database],
the class name in question is
https://www.h2database.com/javadoc/org/h2/jdbcx/JdbcDataSource.html[`org.h2.jdbcx.JdbcDataSource`].

<4> The Hikari connection pool reserves the keyword `dataSource` as an
indicator that the property names that follow are
https://docs.oracle.com/javase/tutorial/javabeans/writing/properties.html[Java
Bean properties] of the class denoted by the value of the
`dataSourceClassName` property.  In this example, the
https://www.h2database.com/javadoc/org/h2/jdbcx/JdbcDataSource.html#setUrl_String[`url`
Java Bean property] of the
https://www.h2database.com/javadoc/org/h2/jdbcx/JdbcDataSource.html[`org.h2.jdbcx.JdbcDataSource`
class] will be set to `jdbc:h2:mem:test`.  See the
https://github.com/brettwooldridge/HikariCP/blob/dev/README.md#initialization[HikariCP
documentation for more details].

=== Configure the Oracle Universal Connection Pool

If instead you have chosen to integrate the Oracle Universal
Connection Pool into your Helidon MP application, then ensure the
following YAML is present in your `application.yaml`, and that your
`application.yaml` is present on the runtime classpath of your Helidon
MP application:

[source,yaml]
----
javax:
  sql:
    DataSource: <1>
      test: <2>
        connectionFactoryClassName: org.h2.jdbcx.JdbcDataSource <3>
        URL: jdbc:h2:mem:test
        user: sa
        password: ""
----

<1> The YAML consisting of a top level `javax` mapping whose sole
element is a `sql` mapping whose sole mapping is a `DataSource`
mapping corresponds to the Java type of
https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`javax.sql.DataSource`].
This preamble specifies the type of Java object that will supply
database connections in your code.  Its sole element is a mapping
whose key is the name of the data source in question.  This preamble
is required.

<2> This mapping's key will be the name of your data source, and will
be referenced in your application code.  Each of its elements' keys
are
https://docs.oracle.com/javase/tutorial/javabeans/writing/properties.html[Java
Bean properties] of the
https://docs.oracle.com/en/database/oracle/oracle-database/19/jjuar/oracle/ucp/jdbc/PoolDataSource.html[`oracle.ucp.jdbc.PoolDataSource`]
class.  By convention, data source names are usually single words
consisting of alphanumeric characters only.

<3> If your database vendor provides a
https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`DataSource`]
implementation class, then specify its name as the value of the
https://docs.oracle.com/en/database/oracle/oracle-database/19/jjuar/oracle/ucp/jdbc/PoolDataSource.html#setConnectionFactoryClassName_java_lang_String_[`connectionFactoryClassName`
Java Bean property].  In this example, which uses the
https://www.h2database.com/html/main.html[H2 database], the class name
in question is
https://www.h2database.com/javadoc/org/h2/jdbcx/JdbcDataSource.html[`org.h2.jdbcx.JdbcDataSource`].

== Inject a https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`DataSource`] in Your Application Code

Now that you've included the relevant libraries and configured them
appropriately you can use the features they enable.

The Helidon connection pool extensions provide support for injecting
https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`DataSource`]
implementations into your code.  The `DataSource` instances so
injected will be in
https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#application_context_se[application
scope], so, loosely speaking, they are effectively singletons.

To inject the `test` data source configured in the examples above,
do the following:

[source,java]
----
@Inject <1>
@Named("test") <2>
private DataSource testDataSource; <3>
----

<1> The
http://javax-inject.github.io/javax-inject/api/javax/inject/Inject.html[`@Inject`
annotation] is used to indicate that the CDI container should set the
annotated field automatically.

<2> The
http://javax-inject.github.io/javax-inject/api/javax/inject/Named.html[`@Named`
annotation] is used, in this case, to select which of several
potentially configured data sources should be injected.  Here, the
`test` data source is requested.

<3> The `testDataSource` field here, whose name is arbitrary, is typed
with
https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`DataSource`].
Its protection level, `private` in this case, is immaterial, following
CDI rules.  Helidon MP's CDI container will use the configuration
described elsewhere in this document to create a new or retrieve an
existing `DataSource` implementation instance whose name is specified
by the `@Named` annotation, and will set this field's value to it.

=== Coupling Your Application Code to a Particular Connection Pool

If for some reason you wish to couple your application tightly to a
particular connection pool implementation, you can choose a different
data type for the field receiving an injected `DataSource`.

You might choose to do this to take advantage of additional methods
offered by either the Hikari connection pool classes or the Oracle
Universal Connection Pool classes.

In general, if you have no need for methods that are not present in
the
https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`javax.sql.DataSource`
interface], tight coupling to a connection pool implementation is
discouraged.

==== Coupling Your Application Code to the Hikari Connection Pool

For example, if you wish to couple your application tightly to the
Hikari connection pool implementation of the
https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html[`javax.sql.DataSource`
interface], you can do this:

[source,java]
----
import com.zaxxer.hikari.HikariDataSource; <1>

@Inject
@Named("test")
private HikariDataSource testDataSource; <2>
----

<1> Your application will now require the Hikari connection pool
classes on its compile and runtime classpaths.

<2> The CDI container will use the Hikari connection pool
configuration described elsewhere in this document to create a new or
retrieve an existing `HikariDataSource` implementation instance whose
name is specified by the `@Named` annotation, and will set this
field's value to it.

==== Coupling Your Application Code to the Oracle Universal Connection Pool

If, instead, you wish to couple your application tightly to Oracle
Universal Connection Pool classes and interfaces, you can do this:

[source,java]
----
import oracle.ucp.jdbc.PoolDataSource; <1>

@Inject
@Named("test")
private PoolDataSource testDataSource; <2>
----

<1> Your application will now require the Oracle Universal Connection
Pool classes on its compile and runtime classpaths.

<2> The CDI container will use the Oracle Universal Connection Pool
configuration described elsewhere in this document to create a new or
retrieve an existing
https://docs.oracle.com/en/database/oracle/oracle-database/19/jjuar/oracle/ucp/jdbc/PoolDataSource.html[`PoolDataSource`]
implementation instance whose name is specified by the `@Named`
annotation, and will set this field's value to it.

== Examples

Helidon features a few examples of projects that use data sources.

* https://github.com/oracle/helidon/tree/master/examples/integrations/cdi/datasource-hikaricp-h2[An
  example showing a Hikari connection pool data source connected to an
  H2 database]

* https://github.com/oracle/helidon/tree/master/examples/integrations/cdi/datasource-hikaricp-mysql[An
  example showing a Hikari connection pool data source connected to a
  MySQL database]

Some examples' configurations can be found in their
`META-INF/microprofile-config.properties` resources instead of in an
`application.yaml` file as described above.  Though the syntax is
different, the same principles as those described above still apply.
