///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Using OpenAPI with Helidon
:toc:
:toc-placement: preamble
:description: Helidon OpenAPI Guide
:keywords: helidon, guide, openapi
:helidon-tag: https://github.com/oracle/helidon/tree/{helidon-version}
:quickstart-example: {helidon-tag}/examples/quickstarts/helidon-quickstart-se
:mp-openapi-spec: https://github.com/eclipse/microprofile-open-api/blob/master/spec/src/main/asciidoc/microprofile-openapi-spec.adoc#static-openapi-files
:openapi-spec: https://github.com/OAI/OpenAPI-Specification
:helidon-mp-openapi-example: {helidon-tag}/examples/microprofile/openapi-basic
:smallrye-mp-openapi: https://github.com/smallrye/smallrye-open-api

Easily allow your Helidon SE or MP application to serve an OpenAPI document
that describes your application's endpoints.

== What you need

|===
|About 15 minutes
| <<about/03_prerequisites.adoc,Helidon Prerequisites>>
|===

== OpenAPI for Helidon MP
Helidon MP conforms to the link:{mp-openapi-spec}[MicroProfile OpenAPI specification],
which was inspired by the link:{openapi-spec}[OpenAPI spec] itself.

You can follow two general approaches with OpenAPI in your Helidon MP app:

1. add MicroProfile OpenAPI annotations to the endpoints in your source code, allowing
the Helidon MP runtime to discover those endpoints via CDI at app start-up; and
2. create a static OpenAPI document describing your app's endpoints, for example
using a separate tool such as Swagger, and packaging it with your app.

You can use either or both in the same application. Helidon MP support for OpenAPI
will combine these and other sources of endpoint information in serving the
OpenAPI document for your app. (See 
<<Advanced OpenAPI support in Helidon SE and MP,the advanced section>> below.)

Typically you add automatic OpenAPI support to your application by:

1. adding annotations to your endpoints and/or packaging a static OpenAPI document
with your app, and
2. updating your `pom.xml` to:
    a. add a dependency for the Helidon MP OpenAPI artifact, and
    b. invoke a maven plug-in to build a Jandex index and include it in your 
application JAR (optional but strongly advised).

Helidon includes a link:{helidon-mp-openapi-example}[complete example maven project] showing
Helidon MP OpenAPI support.

=== Annotating endpoints
The added OpenAPI-related annotations allow the system to build the OpenAPI document 
describing your endpoints. 

Here is one of the endpoints from the example mentioned earlier:

[source,java]
----
@GET
@Operation(summary = "Returns a generic greeting", // <1>
        description = "Greets the user generically")
@APIResponse(description = "Simple JSON containing the greeting", // <2>
        content = @Content(mediaType = "application/json",
                           schema = @Schema(implementation = GreetingMessage.class)))
@Produces(MediaType.APPLICATION_JSON)
public JsonObject getDefaultMessage() {...}
----
<1> `@Operation` gives information about this operation.
<2> `@APIResponse` describes the HTTP response and declares its media type and contents.

You can also define any request parameters the endpoint expects, although this
endpoint uses none.

This guide shows only a few annotations for illustration. The Helidon MP OpenAPI example linked above
illustrates more, and the MicroProfile OpenAPI spec describes them all.

=== Building the Jandex index
The Jandex index speeds up annotation processing by CDI during your application's
start-up.

If your build _does not_ create 
the index then the Helidon MP OpenAPI runtime automatically creates one in memory during 
app start-up. But this slows down your app start-up and, depending on how CDI is 
configured, might inadvertently miss information. 

NOTE: We _strongly recommend_ building the index into your app.

Add this to the `<build><plugins>` section of your `pom.xml`:

[source,xml]
----
<plugin>
    <groupId>org.jboss.jandex</groupId>
    <artifactId>jandex-maven-plugin</artifactId>
    <executions>
      <execution>
        <id>make-index</id>
        <goals>
          <goal>jandex</goal>
        </goals>
      </execution>
    </executions>
</plugin>
----

=== Adding Helidon MP OpenAPI support to your app
Add these two sections to the `<dependencies>` portion of your `pom.xml`:

[source,xml]
----
<dependency> <!--1-->
    <groupId>org.eclipse.microprofile.openapi</groupId>
    <artifactId>microprofile-openapi-api</artifactId>
    <version>${version.lib.microprofile-openapi-api}</version>
</dependency>

<dependency> <!--2-->
    <groupId>io.helidon.microprofile.openapi</groupId>
    <artifactId>helidon-microprofile-openapi</artifactId>
    <version>${project.version}</version>
    <scope>runtime</scope>
</dependency>
----
<1> Defines the MicroProfile OpenAPI annotations so you can use them in your code.
<2> Adds the Helidon MP OpenAPI runtime support.

== OpenAPI for Helidon SE
Helidon SE does not process annotations. You can still use OpenAPI with your
Helidon SE app by using a static OpenAPI document, a model reader,
and a filter.

To use OpenAPI from your Helidon SE app:

1. in your `pom` add a dependency for Helidon SE support,
2. in your application add a registration of `OpenAPISupport`,
3. add a static OpenAPI document at `META-INF/openapi.yml` (optional)
4. add a model reader class and/or a filter class to your app and configure them
in `application.yaml` (see <<se_config, the SE config table>> below).

Here is the additional dependency for Helidon SE OpenAPI runtime support:

[source,xml]
----
<dependency>
    <groupId>io.helidon.openapi</groupId>
    <artifactId>helidon-openapi</artifactId>
</dependency>
----
Note that this is a compile-time dependency, because your code registers
`OpenAPISupport` (a class in that artifact) like this:

[source,java]
----
Config config = Config.create();
...
return Routing.builder()
        .register(JsonSupport.create())
        .register(OpenAPISupport.create(config)) // <1>
        .register(health)                   // Health at "/health"
        .register(metrics)                  // Metrics at "/metrics"
        .register("/greet", greetService)
        .build();
----
<1> Adds the `OpenAPISupport` service to your server.  

Helidon SE support for OpenAPI supports a handful of config properties similar
to those described in the MicroProfile OpenAPI spec.

[[se_config]]
.Helidon SE OpenAPI Config Properties
|===
|Property |Use

|`openapi.model.reader` |Fully-qualified class name for the model reader
(see <<Advanced OpenAPI support, Advanced OpenAPI support>> below)
|`openapi.filter` |Fully-qualified class name for the filter
(see <<Advanced OpenAPI support, Advanced OpenAPI support>> below)
|`openapi.servers` |Prefix for servers to be included in the OpenAPI document
|`openapi.servers.path` |Prefix for path servers to be included in the OpenAPI document
|`openapi.servers.operation` |Prefix for operation servers to be included in the OpenAPI document
|`openapi.schema-references.enable` |Whether OpenAPI schema references should be used
|===

For more information on what these settings do consult the MicroProfile OpenAPI and the 
OpenAPI specs.

== Accessing the OpenAPI document
Now your Helidon SE or MP application will automatially respond to an additional endpoint --
 `/openapi` -- and it will return the OpenAPI document describing the endpoints
in your application.

By default, per the MicroProfile OpenAPI spec, the default format of the OpenAPI document is YAML. 
There is not yet an adopted IANA YAML media type, but a proposed one specifically
for OpenAPI documents that has some support is `application/vnd.oai.openapi`.
That is what Helidon returns, by default.

A client can specify `Accept:` as either `application/vnd.oai.openapi+json` or `application/json`
to request JSON.

== Advanced OpenAPI support
As described in the MicroProfile OpenAPI spec, in addition to annotations there 
are three other ways you can influence how Helidon SE and MP prepare the OpenAPI 
document that describes your app:

1. placing a static OpenAPI document in your application JAR at `META-INF/openapi.yml`,
2. implementing the `OASModelReader` interface in your application, and
3. implementing the `OASFilter` interface in your application.

The model reader provide endpoint information programmatically as the OpenAPI 
runtime assembles the document. The filter can selectively modify or even
remove parts of the endpoint information gathered by the OpenAPI implementation.

The MicroProfile OpenAPI spec describes numerous MicroProfile config properties, 
and you use two of them to identify your model reader and filter.
