///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Using JPA in Helidon MP
:description: Helidon JPA Guide
:keywords: helidon, guide, transaction, jpa, microprofile

This guide shows how to configure and use the
https://jcp.org/en/jsr/detail?id=338[Java Persistence API (JPA)] from
within a Helidon MP application.

== What You Need

|===
|About 30 minutes
|<<about/03_prerequisites.adoc,Helidon Prerequisites>>
|<<07_datasources.adoc,An understanding of named data source support in Helidon MP>>
|<<08_jta.adoc,An understanding of transaction support in Helidon MP>>
|===

== What You'll Do

By following this guide, you’ll enhance a bare-bones Helidon MP
application to use JPA, backed by
https://www.eclipse.org/eclipselink/#jpa[EclipseLink]EclipseLink, to
access an in-memory https://www.h2database.com/html/main.html[H2
database]. You’ll see how to install the relevant dependencies and add
JPA-related code to your application.

== Use the Maven Archetype to Generate a Helidon MP Application

#Archetype instructions go here#

== Add the H2 Database Driver to the Runtime Classpath

Add the following dependency in your `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>
    <version>1.4.199</version>
    <scope>runtime</scope>
</dependency>
----

In a production application, you may use a different database, so you
may add a different database driver dependency here instead.

== Add the Hikari Connection Pool Extension to the Runtime Classpath

Add the following dependency in your `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.helidon.integrations.cdi</groupId>
    <artifactId>helidon-integrations-cdi-datasource-hikaricp</artifactId>
    <scope>runtime</scope>
</dependency>
----

== Add the Provider-Independent Helidon JPA Integration to the Runtime Classpath

Add the following dependency in your `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.helidon.integrations.cdi</groupId>
    <artifactId>helidon-integrations-cdi-jpa</artifactId>
    <version>{helidon-version}</version>
    <scope>runtime</scope>
</dependency>
----

== Add the EclipseLink JPA Integration to the Runtime Classpath

Add the following dependency in your `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.helidon.integrations.cdi</groupId>
    <artifactId>helidon-integrations-cdi-eclipselink</artifactId>
    <version>{helidon-version}</version>
    <scope>runtime</scope>
</dependency>
----

