///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:h1Prefix: SE
:javadoc-base-url-api: {javadoc-base-url}io.helidon.webserver/io/helidon/webserver
:description: Helidon WebServer TLS configuration
:keywords: helidon, reactive, reactive streams, reactive java, reactive webserver, tls

= WebServer TLS configuration

Configure the TLS either programmatically, or by the Helidon configuration framework.

== Configuring the TLS in your code

The easiest way to configure the TLS in WebServer is in your application code.

[source,java]
----
KeyConfig keyConfig = KeyConfig.keystoreBuilder()
                //Whether this keystore is also trust store
                .trustStore()
                //Keystore location/name
                .keystore(Resource.create("keystore.p12"))
                //Password to the keystore
                .keystorePassphrase("password")
                .build();

WebServer.builder()
         .tls(WebServerTls.builder()
               .trust(keyConfig)
               .privateKey(keyConfig)
               .build())
         .build();
----

== Configuring the TLS in the config file

It is also possible to configure TLS via the config file.

[source,yaml]
.WebServer TLS configuration file `application.yaml`
----
server:
  tls:
    #Truststore setup
    trust:
      keystore:
        passphrase: "password"
        trust-store: true
        resource:
          resource-path: "keystore.p12"
    #Keystore with private key and server certificate
    private-key:
      keystore:
        passphrase: "password"
        resource:
          resource-path: "keystore.p12"
----
Then, in your application code, load the configuration from that file.

[source,java]
.WebServer initialization using the `application.yaml` file located on the classpath
----
Config config = Config.create();
WebServer webClient = WebServer.create(routing, config.get("server"));
----
Or you can only create WebServerTls instance base on the config file.

[source,java]
.WebServerTls instance based on `application.yaml` file located on the classpath
----
Config config = Config.create();
WebServerTls.builder()
    .config(config.get("server.tls"))
    .build();
----

== Configuration options

See all configuration options
link:{javadoc-base-url-api}/WebServerTls.html[here].

Available server certificate configuration options:

[cols="^2s,<2,<2,<6"]
|===
|Configuration key |Default value ^|Java type  ^|Description

|`client-auth` |NONE |Enum |See link:{javadoc-base-url-api}/ClientAuthentication.html[here] for all possible values.
Whether to require client certificate authentication
|`protocols` |{nbsp} |String |TLS protocols to enable with the server socket
|`session-cache-size` |{nbsp} |int |The size of the cache used for storing SSL session objects
|`session-timeout-seconds` |{nbsp} |int |The timeout for the cached SSL session objects, in seconds
|`private-key` |{nbsp} |Object |Keystore configuration, please follow the example above
|`trust` |{nbsp} |Object |Keystore configuration, please follow the example above
|===
