///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= OpenAPI-based Code Generation
:rootdir: {docdir}/../..
:incdir: {rootdir}/includes/openapi
:gen-inc: {incdir}/openapi-generator.adoc

include::{rootdir}/includes/se.adoc[]

:helidon-client-xref: {webclient-page}
include::{gen-inc}[tag=preamble]

include::{gen-inc}[tags=intro;coords;config;usage;using-generated-code-intro;using-generated-code-server-intro]


The Helidon SE server generator also creates, for each API, a separate class containing handler methods for each endpoint.
Along with the `PetService` interface or abstract class which has methods such as `addPet` and `getPetById`, the tool generates `PetServiceImpl` with methods such as `handleAddPet` and `handleGetPetById`.

[source,java]
.Generated `PetService` abstract class
----
public abstract class PetService implements Service {
    void addPet(ServerRequest request, ServerResponse response, Pet pet) {
        // ...
    }
    abstract void handleAddPet(ServerRequest request, ServerResponse response, Pet pet);

    void getPetById(ServerRequest request, ServerResponse response) {
        // ...
    }
    abstract void handleGetPetById(ServerRequest request, ServerResponse response, Long petId);
}
----

[source,java]
.Generated skeleton `PetServiceImpl` class (which you extend)
----
public class PetServiceImpl extends PetService {
    public void handleAddPet(ServerRequest request, ServerResponse response, Pet pet) {
        response.status(HTTP_CODE_NOT_IMPLEMENTED.send());
    }

    public void handleGetPetById(ServerRequest request, ServerResponse response, Long petId) {
        response.status(HTTP_CODE_NOT_IMPLEMENTED).send();
    }
}
----
You write your own classes which extend `PetServiceImpl` and the other generated `xxxImpl` classes, overriding the `handle...` methods.

You have control over--and therefore responsibility for--preparing the response to be sent to the client, including the status, any response headers, and any returned entity.
Your overriding implementation of `handleGetPetById` might look like the following example.

[source,java]
.Example override of `handleGetPetById`
----
public void handleGetPetById(ServerRequest request, ServerResponse response, Long petId) {
    Pet pet = locatePetInDatabase(petId);
    if (pet == null) {
        response.status(404).send();
    }
    response.send(pet); // Respnose status is 200 by default.
    }
}
----

include::{gen-inc}[tag=using-generated-code-client-intro]

The generated Helidon SE client includes the class `ApiClient`. This class corresponds to
the Helidon link:{webclient-javadoc-base-url}/io/helidon/webclient/WebClient.html[`WebClient`] and represents the connection between your code and the remote server. The generator also creates one or more `Api` interfaces and corresponding implementation classes. The examples below use the `PetApi` interface and the `PetApiImpl` class.

To invoke the remote service your code must:

. Create an instance of `ApiClient` using an `ApiClient.Builder`.
. Use that `ApiClient` instance to instantiate a `PetApi` object.
. Invoke the methods on the `PetApi` object to access the remote services and then retrieve the returned result value.

The following sections explain these steps.

==== Creating an `ApiClient` Instance
The Helidon SE client generator gives you as much flexibility as you need in connecting to the remote service.

Internally, the `ApiClient` uses a Helidon `WebClient` object to contact the remote system.
The `ApiClient.Builder` automatically prepares a Helidon
link:{webclient-javadoc-base-url}/io/helidon/webclient/WebClient.Builder.html[`WebClient.Builder`] object using information from the OpenAPI document.

The next sections describe, from simplest to most complicated, the ways your code can create an `ApiClient` instance, each involving increased involvement with the `WebClient.Builder` object.

===== Accepting the Automatic `WebClient.Builder`
In the simplest case, your code can get an `ApiClient` instance directly.

[source,java]
.Creating an `ApiClient` instance - simple case
----
ApiClient apiClient = ApiClient.builder().build();
----

Your code relies fully on the automatic `WebClient.Builder`.
In many cases, this approach works very well, especially if the OpenAPI document correctly declares the servers and their URIs.

===== Influencing the Automatic `WebClient.Builder`
Your code can use the `ApiClient.Builder` to fine-tune the settings for the internal `WebClient.Builder`.
For instance, your code can set an object mapper to be used for Jackson processing or the `JsonbConfig` object to be used for JSON-B processing, depending on which serialization library you chose when you ran the generator.

Your code does not need to know how the object mapper setting is conveyed to the internal `WebClient.Builder`. The `ApiClient.Builder` knows how to do that.

[source,java]
.Creating an `ApiClient` instance - influencing the `ApiClient.Builder`
----
ApiClient apiClient = apiClient.builder()
                            .objectMapper(yourCustomMapper)
                            .build();
----

===== Adjusting the Automatic `WebClient.Builder`
In more complicated situations, your code can adjust the settings of the `WebClient.Builder` the `ApiClient.Builder` creates.

[source,java]
.Creating an `ApiClient` instance - adjusting the `WebClient.Builder`
----
ApiClient.Builder apiClientBuilder = ApiClient.builder();

apiClientBuilder.webClientBuilder() // <1>
                .connectTimeout(4, TimeUnit.SECONDS); // <2>

ApiClient apiClient = apiClientBuilder.build(); // <3>
----
<1> Access the `ApiClient.Builder`'s automatic `WebClient.Builder` instance.
<2> Adjust a setting of the `WebClient.Builder` directly.
<3> Build the `ApiClient` which implicitly builds the `WebClient` from the now-adjusted internal `WebClient.Builder`.

The automatic `WebClient.Builder` retains information derived from the OpenAPI document unless your code overrides those specific settings.

===== Providing a Custom `WebClient.Builder`
Lastly, you can construct the `WebClient.Builder` entirely yourself and have the `ApiClient.Builder` use it instead of its own internal builder.

[source,java]
.Creating an `ApiClient` instance - using a custom `WebClient.Builder`
----
WebClient.Builder customWebClientBuilder = WebClient.builder()
                .connectTimeout(3, TimeUnit.SECONDS)
                .baseUri("https://myservice.mycompany.com");

ApiClient apiClient = ApiClient.builder()
                        .webClientBuilder(customWebClientBuilder)
                        .build();
----
Note that this approach entirely replaces the internal, automatically-prepared `WebClient.Builder` with yours; it _does not_ merge the new builder with the internal one. In particular, any information from the OpenAPI document the generator used to prepare the internal  `WebClient.Builder` is lost.


==== Creating a `PetApi` Instance
The `ApiClient` represents the connection to the remote server but not the individual RESTful operations.
Each generated `xxxApi` interface exposes a method for each operation declared in the OpenAPI document associated with that API via its `tags` value.
By example, the `PetApi` interface exposes a method for each operation in the OpenAPI document that pertains to pets.

To invoke an operation defined on the `PetApi` interface, your code instantiates a `PetApi` using an `ApiClient` object:

[source,java]
.Preparing the PetStore Client API
----
ApiClient apiClient = ApiClient.builder().build();
PetApi petApi = PetApiImpl.create(apiClient);
----

==== Invoking Remote Endpoints
With the `petApi` object, your code can invoke any of the methods on the `PetApi` interface to contact the remote service.

The Helidon WebClient follows a reactive programming model, and the Helidon SE client generator creates an `ApiResponse` interface, also reactive.
Each generated `PetApi` method returns an `ApiResponse<returnType>` where the `returnType` is the return type declared in the OpenAPI document for the corresponding operation.

The `ApiResponse` interface exposes two methods your code can use to work with the response from the remote service invocation:

* `Single<T> result()`
+
Provides reactive access to the value returned by the remote service in the response.
This method lets your code fetch the return value directly.
* `Single<WebClientResponse> webClientResponse()`
+
Provides reactive access to the Helidon `WebClientResponse` object.
Your code can find out the HTTP return status, read headers in the response, and process the content (if any) in the response however it needs to.

In the reactive Helidon WebClient model, the first part of the response message can  arrive (the status and headers are available) before the entity in the body of the response is readable.
So there are two reactive events associated with an incoming HTTP response:

. when the response _excluding_ the entity content has arrived, and
. when your code can begin consuming the entity content.

You can adopt different styles of retrieving the results, depending on the specific needs of the code you are writing.

===== Synchronous access to the result
This example shows the simplest way to invoke the remote service and work with the result.

[source,java]
.Synchronous access to the return value
----
// Assumes the petApi field is initialized as above.
List<Pet> availablePets = petApi.findPetsByStatus(List.of(Pet.StatusEnum.AVAILABLE.value())) // <1>
                .result() // <2>
                .await(4, TimeUnit.SECONDS); // <3>
----
<1> Start the remote service invocation.
<2> Access the reactive result.
<3> Wait for the result to arrive subject to a four-second timeout.

This code blocks the current thread, waiting up to four seconds for the response to arrive.
This approach might be adequate if you are developing a command-line client where the thread has no other meaningful work to do until it has the result.
This is _not_ an appropriate style for server code that uses the generated client to invoke another service.

Note that this approach offers no access to the HTTP status for the response or any headers that might have been returned.

===== Synchronous access with status checking
The Helidon WebClient programming model includes a `WebClientResponse` interface which exposes all aspects of the HTTP response returned from the remote service.

The next example shows how your code can use the `WebClientResponse`.

[source,java]
.Synchronous access with status checking
----
ApiResponse<List<Pet>> apiResponse = petApi.findPetsByStatus(List.of(Pet.StatusEnum.AVAILABLE.value())); // <1>

WebClientResponse webClientResponse = apiResponse.webClientResponse()
            .await(4, TimeUnit.SECONDS); // <2>

if (webClientResponse.status().code() != 200) { // <3>
    // Handle a non-successful status.
}

List<Pet>> availablePets = apiResponse.result()
            .await(4, TimeUnit.SECONDS); // <4>
----
<1> Start the remote service invocation.
<2> Wait for the HTTP response status and headers to arrive.
<3> Check the status in the HTTP response.
<4> Wait for the content to arrive subject to a four-second timeout.

This code also blocks the current thread, first to wait for the initial response and then to wait for the result content.

===== Fully-reactive access
The following example shows how your code might invoke the remote service and process the response using the reactive programming model.

.Fully-reactive access with status checking
[source,java]
----
// Assumes the petApi field is initialized as above.
ApiResponse<List<Pet>> availablePetsResponse =
    petApi.findPetsByStatus(List.of(Pet.StatusEnum.AVAILABLE.value())); // <1>

availablePetsResponse.webClientResponse()
    .thenAccept(resp -> { // <2>
        if (resp.status().code() == 200) {
            try {
                availablePetsResponse.result() // <3>
                    .thenAccept(availablePets -> {
                        // Process the List<Pet> of available pets. // <4>

                    })
                    .exceptionally(throwable -> {
                        // Handle whatever problem occurred in retrieving the results. // <5>
                        return null;
                    });
            } catch (ExecutionException | InterruptedException e) {
                // Handle errors while waiting for the response content to arrive. // <6>
            }
        } else {
            // Handle non-200 HTTP status. // <7>
        })
    .exceptionally(throwable -> {
        // Handle whatever problem occurred in receiving the response. // <8>
        return null;
    });
----
<1> Starts the remote service invocation.
<2> Reactively processes the first portion of the HTTP response.
<3> Reactively processes a successfully-received HTTP response.
<4> Reactively processes the successfully-returned list of available pets.
<5> Reactively handles any errors in retrieving the list of available pets.
<6> Handle problems that occurred while waiting for the response content to arrive.
<7> Handle a non-200 response status.
<8> Reactively handles any errors in receiving the HTTP response.

The fully-reactive approach brings with it some complexity, but it lets your code completely avoid blocking the thread that initiates the outbound remote service access.
Avoiding blocking is especially important if the code which uses the generated client runs in a server.

Some of this complexity enters because there are several ways this processing can fail.
Your code should handle each of them in whatever ways make sense for your application, and that might mean dealing with each different error scenario in a different way.

include::{gen-inc}[tag=common-references]
* xref:{helidon-client-xref}[Helidon WebClient documentation]