///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= OpenAPI UI
:description: Helidon SE OpenAPI UI Support
:keywords: helidon, se, openapi ui
:rootdir: {docdir}/../..
:ui-inc: {rootdir}/includes/openapi/openapi-ui.adoc

include::{rootdir}/includes/se.adoc[]

:javadoc-path: {openapi-ui-javadoc-base-url}/io/helidon/integrations/openapi/ui
:openapi-javadoc-path: {openapi-javadoc-base-url}/io/helidon/openapi

include::{ui-inc}[tag=preamble]

include::{ui-inc}[tags=intro;overview]

include::{ui-inc}[tag=dependencies]

Also, make sure your project has the following dependency.

include::{docdir}/openapi.adoc[tag=depc]

This dependency allows your application to create, configure, and register the `OpenAPISupport` service.

include::{ui-inc}[tag=usage]

== API
=== Creating `OpenAPISupport` with Automatic UI Behavior
With the Helidon OpenAPI UI dependency in your `pom.xml` file, any `OpenAPISupport` object your application builds prepares the default OpenAPI UI behavior, possibly modified by any UI settings you have in your configuration.

[source,java]
.Create `OpenAPISupport` with automatic UI
----
Config config = Config.create(); // <1>
Config openApiConfig = config.get(OpenAPISupport.Builder.CONFIG_KEY)); // <2>

OpenAPISupport openApiSupport =
    OpenAPISupport.builder()
        .config(openApiConfig) // <3>
        .build();
----
<1> Load the configuration.
<2> Extract the `OpenAPISupport` configuration.
<3> Build the `OpenAPISupport` instance using the configuration.

If your code invokes the `OpenAPISupport.Builder` `config` method, Helidon automatically applies the `ui` section of the `openapi` configuration to the UI.

=== Customizing the UI Behavior
You can control some of the behavior of the UI programmatically in two steps:

. Create an link:{javadoc-path}/OpenApiUi.Builder.html[`OpenApiUi.Builder`] and invoke methods on it to set the UI behavior.
. Invoke the `ui` method on link:{openapi-javadoc-base-url}/io.helidon.openapi.OpenAPISupport.Builder.html[`OpenAPISupport.Builder`], passing the `OpenApiUi.Builder` you prepared above.

The following example illustrates these steps, combining configuration with explicit programmatic settings.

[source,java]
.Create `OpenApiUi` and `OpenAPISupport` instances
----
Config config = Config.create(); // <1>
Config openApiConfig = config.get(OpenAPISupport.Builder.CONFIG_KEY)); // <2>

OpenApiUi.Builder uiBuilder =
    OpenApiUi.builder() // <3>
        .webContext("/my-openapi-ui"); // <4>

OpenAPISupport openApiSupport =
    OpenAPISupport.builder() // <5>
        .ui(uiBuilder)
        .config(openApiConfig) // <6>
        .build();


----
<1> Load the configuration.
<2> Extract the `OpenAPISupport` configuration.
<3> Create the `OpenApiUi.Builder` instance.
<4> Explicitly set the web context where the UI should respond.
<5> Create the `OpenAPISupport` instance using the `OpenApiUi.Builder` just created.
You can refine the behavior of the `OpenAPISupport` object by invoking additional methods on its builder before invoking its `build` method.
<6> Apply the `openapi` configuration to the `OpenAPISupport` builder. This also automatically applies any `openapi.ui` configuration to the UI.

The order in which your code invokes the methods on `OpenApiUi.Builder` and `OpenAPISupport.Builder` determines the outcome.
For instance, the example above sets the UI on the `OpenAPISupport.Builder` _before_ applying configuration.
If the configuration contains a setting for the UI's `web-context` value then the UI uses the configured value, not the programmatic value, because your code applied the configuration later.
Your code should typically apply configuration _after_ setting any values programmatically.
Doing so allows users or deployers of your service to set the behavior using configuration according to their particular needs which your code might not be able to anticipate.

[NOTE]
====
The `webContext(String)` method on `OpenApiUi.Builder`  sets the web context where the UI should respond instead of the default `/openapi/ui`.
Helidon uses the provided string to set the _entire_ web context for the UI, not as a suffix appended to the web context for the `OpenAPISupport` service.
====

=== Registering `OpenAPISupport`
Whether or not your code tailors the UI or `OpenAPISupport` behavior, it must register the resulting `OpenAPISupport` instance so that the OpenAPI and UI endpoints can respond correctly.

[source,java]
.Register services for routing
----
Routing.builder()
        .register(openApiSupport)
        // Add registrations of your service(s) and other Helidon services you need.
        .build();
----

The UI is implemented as part of the `OpenAPISupport` service which registers the UI automatically.
Your code does not register the UI explicitly.

include::{ui-inc}[tag=config-intro]

include::{ui-inc}[tag=config-details]

include::{ui-inc}[tag=additional-info]