///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= OpenAPI in Helidon
:description: Helidon SE OpenAPI Support
:keywords: helidon, se, openapi
:feature-name: OpenAPI
:rootdir: {docdir}/../..
:incdir: {rootdir}/includes/openapi

include::{rootdir}/includes/se.adoc[]
:javadoc-path: {openapi-javadoc-base-url}/io.helidon.openapi

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
- <<API, API>>
- <<Configuration, Configuration>>
- <<Examples, Examples>>
- <<Additional Information, Additional Information>>

== Overview

include::{incdir}/openapi.adoc[tag=overview]

include::{rootdir}/includes/dependencies.adoc[]

// tag::depc[]
[source,xml]
----
<dependency>
    <groupId>io.helidon.openapi</groupId>
    <artifactId>helidon-openapi</artifactId>
</dependency>
----
// end::depc[]

== Usage

You can very simply add support for OpenAPI to your Helidon SE application. This
document shows what changes you need to make to your application and how to access
the OpenAPI document for your application at runtime.

=== Changing your application

==== Register `OpenAPISupport` in your application routing

Helidon SE provides the link:{javadoc-path}/OpenAPISupport.html[`OpenAPISupport`] class which your application uses to assemble the in-memory model and expose the `/openapi` endpoint to clients. You can create an instance either using a static `create` method or by instantiating its link:{javadoc-path}/OpenAPISupport.Builder.html[`Builder`]. The xref:#register_openapisupport[example below]  illustrates one way to do this.

include::{incdir}/openapi.adoc[tag=furnish-openapi-info]

==== Add OpenAPI dependency
If you implement either a model reader or a filter, add this dependency to your
`pom.xml`:

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>org.eclipse.microprofile.openapi</groupId>
    <artifactId>microprofile-openapi-api</artifactId>
    <version>{microprofile-openapi-version}</version>
</dependency>
----

include::{incdir}/openapi.adoc[tag=usage-access-endpoint]

== API

include::{incdir}/openapi.adoc[tag=api]

Helidon {flavor-uc} provides an API for creating and setting up the REST endpoint which serves OpenAPI documents to clients at the `/openapi` path. Use either static methods on link:{javadoc-path}/OpenAPISupport.html[`OpenAPISupport`]  or use its link:{javadoc-base}/OpenAPISupport.Builder.html[`Builder`] to create an instance of `OpenAPISupport`. Then add that instance to your application's routing. The <<#register_openapisupport,example>> below shows how to do this.

[[config]]
== Configuration

Helidon SE OpenAPI configuration supports the following settings:

include::{rootdir}/config/io_helidon_openapi_SEOpenAPISupport.adoc[leveloffset=+1,tag=config]



== Examples

Helidon SE provides a link:{helidon-github-tree-url}/examples/openapi[complete OpenAPI example]
based on the SE QuickStart sample app which includes a model reader and a filter.

Most Helidon {flavor-uc} applications need only to create and register `OpenAPISupport`.

[#register_openapisupport]
=== Register `OpenAPISupport`

.Java Code to Register `OpenAPISupport` for Routing
[source,java]
----
Config config = Config.create();
return Routing.builder()
        .register(JsonSupport.create())
        .register(OpenAPISupport.create(config)) // <1>
        .register(health)                   // Health at "/health"
        .register(metrics)                  // Metrics at "/metrics"
        .register("/greet", greetService)
        .build();
----
<1> Adds the `OpenAPISupport` service to your server.

If you need more control over the `OpenAPISupport` instance, invoke `OpenAPISupport.builder()` to get an `OpenAPISupport.Builder` object and work with it.

== Additional Information
include::{incdir}/openapi.adoc[tag=additional-building-jandex]