///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= OpenAPI U/I
:toc:
:toc-placement: preamble
:description: Helidon SE OpenAPI U/I Support
:keywords: helidon, se, openapi u/i
:rootdir: {docdir}/../..
:incdir: {rootdir}/includes/openapi
:ui-inc: {incdir}/openapi-ui.adoc

include::{rootdir}/includes/se.adoc[]
include::{rootdir}/includes/pages.adoc[]
:javadoc-path: {openapi-ui-javadoc-base-url}/io/helidon/integrations/openapi/ui
:openapi-javadoc-path: {openapi-javadoc-base-url}/io/helidon/openapi

include::{ui-inc}[tag=preamble]

include::{ui-inc}[tags=intro;overview]

include::{ui-inc}[tag=dependencies]

Also, make sure your project has the following dependency.

include::{openapi-page}[tag=depc]

This dependency allows your application to create, configure, and register the `OpenAPISupport` service.

include::{ui-inc}[tag=usage]

== API
=== Creating `OpenAPISupport` with Automatic U/I Behavior
With the Helidon OpenAPI U/I dependency in your `pom.xml` file, any `OpenAPISupport` object your application builds prepares the default OpenAPI U/I behavior, possibly modified by any U/I settings you have in your configuration.

[source,java]
.Create `OpenAPISupport` with automatic U/I
----
Config config = Config.create(); // <1>
Config openApiConfig = config.get(OpenAPISupport.Builder.CONFIG_KEY)); // <2>

OpenAPISupport openApiSupport =
    OpenAPISupport.builder()
        .config(openApiConfig) // <3>
        .build();
----
<1> Load the configuration.
<2> Extract the `OpenAPISupport` configuration.
<3> Build the `OpenAPISupport` instance using the configuration.

If your code invokes the `OpenAPISupport.Builder` `config` method, Helidon automatically applies the `ui` section of the `openapi` configuration to the U/I.

=== Customizing the U/I Behavior
You can control some of the behavior of the U/I programmatically in two steps:

. Create an link:{javadoc-path}/OpenApiUi.Builder.html[`OpenApiUi.Builder`] and invoke methods on it to set the U/I behavior.
. Invoke the `ui` method on link:{openapi-javadoc-base-url}/io.helidon.openapi.OpenAPISupport.Builder.html[`OpenAPISupport.Builder`], passing the `OpenApiUi.Builder` you prepared above.

The following example illustrates these steps, combining configuration with explicit programmatic settings.

[source,java]
.Create `OpenApiUi` and `OpenAPISupport` instances
----
Config config = Config.create(); // <1>
Config openApiConfig = config.get(OpenAPISupport.Builder.CONFIG_KEY)); // <2>

OpenApiUi.Builder uiBuilder =
    OpenApiUi.builder() // <3>
        .webContext("/my-openapi-ui"); // <4>

OpenAPISupport openApiSupport =
    OpenAPISupport.builder() // <5>
        .ui(uiBuilder)
        .config(openApiConfig) // <6>
        .build();


----
<1> Load the configuration.
<2> Extract the `OpenAPISupport` configuration.
<3> Create the `OpenApiUi.Builder` instance.
<4> Explicitly set the web context where the U/I should respond.
<5> Create the `OpenAPISupport` instance using the `OpenApiUi.Builder` just created.
You can refine the behavior of the `OpenAPISupport` object by invoking additional methods on its builder before invoking its `build` method.
<6> Apply the `openapi` configuration to the `OpenAPISupport` builder. This also automatically applies any `openapi.ui` configuration to the U/I.

The order in which your code invokes the methods on `OpenApiUi.Builder` and `OpenAPISupport.Builder` determines the outcome.
For instance, the example above sets the U/I on the `OpenAPISupport.Builder` _before_ applying configuration.
If the configuration contains a setting for the U/I's `web-context` value then the U/I uses the configured value, not the programmatic value, because your code applied the configuration later.
Your code should typically apply configuration _after_ setting any values programmatically.
Doing so allows users or deployers of your service to set the behavior using configuration according to their particular needs which your code might not be able to anticipate.

[NOTE]
====
The `webContext(String)` method on `OpenApiUi.Builder`  sets the web context where the U/I should respond instead of the default `/openapi/ui`.
Helidon uses the provided string to set the _entire_ web context for the U/I, not as a suffix appended to the web context for the `OpenAPISupport` service.
====

=== Registering `OpenAPISupport`
Whether or not your code tailors the U/I or `OpenAPISupport` behavior, it must register the resulting `OpenAPISupport` instance so that the OpenAPI and U/I endpoints can respond correctly.

[source,java]
.Register services for routing
----
Routing.builder()
        .register(openApiSupport)
        // Add registrations of your service(s) and other Helidon services you need.
        .build();
----

The U/I is implemented as part of the `OpenAPISupport` service which registers the U/I automatically.
Your code does not register the U/I explicitly.

include::{ui-inc}[tag=config-intro]

include::{ui-inc}[tag=config-details]

include::{ui-inc}[tag=additional-info]