///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= OpenAPI U/I
:toc:
:toc-placement: preamble
:description: Helidon SE OpenAPI U/I Support
:keywords: helidon, se, openapi u/i
:rootdir: {docdir}/../..
:incdir: {rootdir}/includes/openapi
:ui-inc: {incdir}/openapi-ui.adoc

include::{rootdir}/includes/se.adoc[]
include::{rootdir}/includes/pages.adoc[]
:javadoc-path: {openapi-ui-javadoc-base-url}/io/helidon/integrations/openapi/ui
:openapi-javadoc-path: {openapi-javadoc-base-url}/io/helidon/openapi

include::{ui-inc}[tag=preamble]

include::{ui-inc}[tags=intro;overview]

include::{ui-inc}[tag=dependencies]

Also, make sure your project has the following dependency.

include::{openapi-page}[tag=depc]

This dependency allows your application to create, configure, and register the `OpenAPISupport` service.

include::{ui-inc}[tag=usage]

== API
You can control some of the behavior of the U/I programmatically in two steps:

. Create an link:{javadoc-path}/OpenApiUi.Builder.html[`OpenApiUi.Builder`] and invoke methods on it to set the U/I behavior.
. Invoke the `ui` method on link:{openapi-javadoc-base-url}/io.helidon.openapi.OpenAPISupport.Builder.html[`OpenAPISupport.Builder`], passing the `OpenApiUi.Builder` you prepared above.

The following example illustrates these steps.

[source,java]
.Create `OpenApiUiSupport` and `OpenAPISupport` instances
----
Config config = Config.create(); // <1>
Config openApiConfig = config.get(OpenAPISupport.Builder.CONFIG_KEY)); // <2>

OpenApiUi.Builder uiBuilder =
    OpenApiUi.builder() // <3>
        .config(openApiConfig.get(OpenApiUi.Builder.OPENAPI_UI_CONFIG_KEY); // <4>

OpenAPISupport openApiSupport =
    OpenAPISupport.builder()
        .config.get()
        .ui(uiBuilder) // <5>
        .build();


----
<1> Load the configuration.
<2> Extract the `OpenAPISupport` config.
<3> Create the `OpenApiUi.Builder` instance.
<4> Use the `ui` configuration (which is contained within the `OpenAPISupport` config) to assign the behavior of the U/I as set in the configuration. You could also invoke other methods on the U/I builder to further tailor the U/I behavior.
<5> Create the `OpenAPISupport` instance using the `OpenApiUi.Builder` just created. You can refine the behavior of the `OpenAPISupport` object by invoking additional methods on its builder before invoking its `build` method.

Register the `OpenAPISupport` service, as well as your own services and others from Helidon.

[source,java]
.Register services for routing
----
Routing.builder()
        .register(openApiSupport)
        // Add registrations of your service(s) and other Helidon services you need.
        .build();
----

[NOTE]
====
The `webContext(String)` method on `OpenApiUi.Builder`  sets the web context where the U/I should respond instead of the default `/openapi/ui`.
Helidon uses the provided string to set the _entire_ web context for the U/I, not as a suffix appended to the web context for the `OpenAPISupport` service.
====
include::{ui-inc}[tag=config-intro]

For example, the following configuration changes the path where you access the U/I.

[source,yaml]
.Example `application.yaml` configuration changing the U/I URL
----
openapi:
  ui:
    web-context: /my-openapi-ui
----

include::{ui-inc}[tag=config-details]
