--
-- Copyright (c) 2026 Oracle and/or its affiliates.
--
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
--

CREATE TABLE CHAOS_CONTACT (
    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(80) NOT NULL
);
CREATE TABLE CHAOS_GENERATED (
    ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(80) NOT NULL
);
INSERT INTO CHAOS_CONTACT (ID, NAME) VALUES (1, 'alpha');
INSERT INTO CHAOS_CONTACT (ID, NAME) VALUES (2, 'beta');
