#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Security requires Helidon config

server:
  port: 7987
  # location on classpath (e.g. src/main/resources/WEB in maven)
  static.classpath:
    location: "/WEB"
    # this is optional, defaults to "/"
    context: "/web"
security:
  config.require-encryption: false
  properties:
    # This is a nice way to be able to override this with local properties or env-vars
    idcs-uri: "https://idcs-d424f4f986044976bdc027f7ffa3f085.identity.c9dev1.oc9qadev.com"
    idcs-client-id: "bfce84c76f8d4fe6b14c8e9123db4600"
    idcs-client-secret: "${CLEAR=fb9596d4-fea7-4578-a15f-4f46b9d8b478}"
    # Used as a base for redirects back to us
    frontend-uri: "http://localhost:7987"
    proxy-host: "www-proxy.uk.oracle.com"
  providers:
  - abac:
  - oidc:
      client-id: "${ALIAS=security.properties.idcs-client-id}"
      client-secret: "${ALIAS=security.properties.idcs-client-secret}"
      identity-uri: "${ALIAS=security.properties.idcs-uri}"
      # A prefix used for custom scopes
      scope-audience: "http://localhost:7987/test-application"
      proxy-host: "${ALIAS=security.properties.proxy-host}"
      frontend-uri: "${ALIAS=security.properties.frontend-uri}"
      # Retrieve roles
      idcs-roles: true
  web-server:
    paths:
    - path: "/web[/{*}]"
      authenticate: true
