///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon Documentation
:description: Helidon
:keywords: helidon, java, microservices, microprofile, documentation
:rootdir: {docdir}/..



include::{rootdir}/includes/attributes.adoc[]



[PILLARS]
====
//Introduction to Helidon
[CARD]
.Introduction to Helidon
[icon=lightbulb]
--
Start here to learn how Helidon's open-source set of Java libraries can help you write cloud-native Java microservices.

xref:{rootdir}/about/introduction.adoc[What is Helidon?]

xref:{rootdir}/about/intro.adoc[What's New in Helidon 4]

xref:{rootdir}/about/archetype.adoc[Helidon Archetypes]

xref:{rootdir}/about/additional_info.adoc[Helidon Community and Support]




--
//Getting Started
[CARD]
.Getting Started
[icon=rocket_launch]
--
There are several ways to generate your first Helidon project. In a hurry? Try the Helidon CLI or Project Starter which provide a set of predefined archetypes to choose from.

xref:{rootdir}/about/prerequisites.adoc[Prerequisites and System Requirements]

xref:{rootdir}/about/cli.adoc[Using the Helidon CLI]

xref:{rootdir}/mp/guides/quickstart.adoc[Using the MP Quickstart Guide]

xref:{rootdir}/se/guides/quickstart.adoc[Using the SE Quick Start Guide]


--

//Upgrade Guides
[CARD]
.Upgrading Helidon
[icon=storage]
--
Use the upgrade guides to help you upgrade your existing Helidon applications to the latest version of Helidon.

xref:{rootdir}/mp/guides/upgrade_4x.adoc[Upgrade From Helidon MP 3.x]

xref:{rootdir}/se/guides/upgrade_4x.adoc[Upgrade From Helidon SE 3.x]

--



//Developing Your First Application
[CARD]
.Developing Your First Application From Scratch
[icon=terminal]
--
Use these hands-on development tutorials to learn how to generate a small "Hello World!" greeting service that demonstrates some of Helidon's core features.

xref:{rootdir}/mp/guides/mp-tutorial.adoc[Helidon MP Tutorial]

// We do not have an SE application tutorial. So for now point at quickstart.
xref:{rootdir}/se/guides/quickstart.adoc[Helidon SE Quickstart]

--

//How-To Guides
[CARD]
.How-To Guides
[icon=library_books]
--
Ready for more hands-on learning? Explore the features of Helidon with these quick step-by-step guides.

xref:{rootdir}/se/guides/overview.adoc[SE Guides]

xref:{rootdir}/mp/guides/overview.adoc[MP Guides]

--
//Advanced SE Features
[CARD]
.Advanced SE Features
[icon=hotel_class]
--
xref:{rootdir}/se/webserver.adoc[Helidon WebServer]

xref:{rootdir}/se/metrics/metrics.adoc[Helidon Metrics]

xref:{rootdir}/se/config/introduction.adoc[Helidon Config]
--


//Training and Certification
[CARD]
.Training and Certification
[icon=model_training]
--


Training:
 https://learn.oracle.com/ols/learning-path/become-a-helidon-microservices-developer-professional/88258/114512[Become a Helidon Microservices Developer Professional]

Certification:
  https://learn.oracle.com/ols/learning-path/become-a-helidon-microservices-developer-professional/88258/114512[Helidon Microservices Developer Professional (1Z0-1113)]

New to Helidon? Check out https://a.co/d/0niQnwC[Beginning Helidon] to learn more about building cloud-native microservices with Helidon.



--

//Get Involved
[CARD]
.Get Involved
[icon=groups]
--
Here are some additional resources you can use to get started, get help, and to follow the evolution of Helidon.

Project website: https://helidon.io

Medium publication: https://medium.com/helidon

GitHub repository: https://github.com/helidon-io/helidon

Public Slack workspace: https://slack.helidon.io/

Twitter account: https://twitter.com/helidon_project

YouTube channel: https://youtube.helidon.io

Stack Overflow tag: https://stackoverflow.com/tags/helidon
--
====




