///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Introducing Helidon
:description: Helidon
:keywords: helidon, java, microservices
:rootdir: {docdir}/..

include::{rootdir}/includes/attributes.adoc[]

== Introducing Helidon 

Helidon is a framework for developing Java applications using a microservices architecture. It simplifies and streamlines the development, deployment, and management of cloud-native applications.

At its core, Helidon provides a set of Java APIs that allow you to develop new Java applications (or migrate existing applications) that can run in more places, scale easily, and adjust swiftly as requirements change, leading to more efficient and effective applications.

Helidon applications are standalone Java applications running in their own JVM and powered by the Helidon WebServer. Helidon is compatible with Java SE and many Jakarta EE specifications. It includes a full observability stack with dedicated components for health checks, metrics, tracing, and logging. It also integrates well with several other popular tools and technologies so you can feel confident that you won't lose any functionality moving to the Helidon framework.

Helidon SE is Helidon's foundational set of APIs. It offers a lightweight and flexible approach to developing Java applications while still providing a full framework for configuration, observability, security, integrations, and deployment.

You should use Helidon SE if:

* You want full transparency into and greater control over your development process.
* You plan to rely heavily on concurrency APIs and want support for virtual threads.
* You want to limit the number of third-party dependencies.
* You prefer a microframework with a tiny footprint.

Learn more at xref:{rootdir}/se/introduction.adoc[Helidon SE].

The following code example shows a simple RESTful service implemented using Helidon SE.

.Helidon SE sample
[source,java]
----
include::{sourcedir}/about/IntroductionSnippets.java[tag=snippet_1, indent=0]
----

== Next Steps

* Read xref:{rootdir}/about/prerequisites.adoc[Get Started] and learn how to set up your environment.
* Try out Helidon with the xref:{rootdir}/se/guides/quickstart.adoc[Helidon SE Quick Start].
* If you're using an earlier version of Helidon, read the xref:{rootdir}/se/guides/upgrade_4x.adoc[Helidon SE 4.x Upgrade Guide].

Helidon is an open source framework (developed by Oracle) licensed under Apache License 2.0. You can follow its development at the https://github.com/helidon-io/helidon[Helidon GitHub repository].
