///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Run Kubernetes Locally for Development
:description: Running Kubernetes locally
:keywords: kubernetes, local development, docker desktop, minikube
:rootdir: {docdir}/..

include::{rootdir}/includes/attributes.adoc[]

For development, it can be convenient to run Kubernetes locally. A popular option that is used throughout Helidon documentation is https://docs.docker.com/desktop/[Docker Desktop], which includes support for Kubernetes.

You can also use https://minikube.sigs.k8s.io/docs/[minikube] for local development, though you will have to adapt any Docker Desktop-specific instructions for minikube.

For instructions on how to install and configure Docker Desktop for your platform, see the following Docker documentation: 

* https://docs.docker.com/desktop/setup/install/linux/[Docker Desktop on Linux]
* https://docs.docker.com/desktop/setup/install/mac-install/[Docker Desktop on macOS]
* https://docs.docker.com/desktop/setup/install/windows-install/[Docker Desktop on Windows].

After you install Docker Desktop, see https://docs.docker.com/desktop/use-desktop/kubernetes/[Explore the Kubernetes view] in the Docker documentation for guidance on enabling and using Kubernetes in Docker Desktop.

NOTE: Docker Desktop for Linux does not include `kubectl` by default. See https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/[Install and Set Up kubectl on Linux] in the Kubernetes documentation.

If you get errors when running `kubectl` commands, make sure the Kubernetes context is set to `docker-desktop`.

[source,bash]
.Make sure Kubernetes context is set to docker-desktop
----
kubectl config get-contexts
kubectl config use-context docker-desktop
kubectl cluster-info
kubectl version
kubectl get nodes
----
