///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Get Started
:description: Helidon prerequisites and getting started
:keywords: helidon
:rootdir: {docdir}/..

include::{rootdir}/includes/attributes.adoc[]

Helidon is a collection of Java libraries for writing microservices. As such, you don't install Helidon itself. Instead, you install the tools necessary to create an environment suitable for developing Helidon projects and applications.

== System Requirements

You must have Java and Maven installed on your system to use Helidon. Depending on how you plan to deploy your services, you may need to install Docker and kubectl as well.

.Requirements
[%autowidth]
|====
include::{rootdir}/includes/prerequisites.adoc[tag=prerequisites-table-rows]
|====

If you use Windows, see xref:windows.adoc[Helidon on Windows] for additional prerequisites.

[source,bash]
.Verify System Requirements
----
java -version
mvn --version
docker --version
kubectl version
----

=== Set the `JAVA_HOME` Environment Variable

Make sure you set the `JAVA_HOME` environment variable.

[source,bash]
.Set `JAVA_HOME` on Linux
----
# Enter the appropriate path to your JDK
export JAVA_HOME=/usr/lib/jvm/jdk-21
----

[source,bash]
.Set `JAVA_HOME` on macOS
----
# Enter the appropriate path to your JDK
export JAVA_HOME=`/usr/libexec/java_home -v 21`
----

[source,cmd]
.Set `JAVA_HOME` on Windows
----
# Enter the appropriate path to your JDK
setx JAVA_HOME=C:\\PROGRA~1\\Java\\jdk-21
----

== Next Steps

Now that your environment is set up, you can get started with Helidon. Try out the Helidon MP and Helidon SE Quick Start tutorials to build your first Helidon project and application.

* xref:../mp/guides/quickstart.adoc[Helidon MP Quick Start]
* xref:../se/guides/quickstart.adoc[Helidon SE Quick Start]

TIP: Read xref:introduction.adoc[About Helidon] to help you understand the differences between Helidon MP and Helidon SE.
