///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon on Windows
:description: Helidon on Windows
:keywords: windows, microsoft
:rootdir: {docdir}/..

include::{rootdir}/includes/attributes.adoc[]


Generally, the Helidon documentation assumes that you're using a Unix-like operating system such as Linux or macOS. If you want to use Helidon on Windows, then review the following document for tips on the differences that you should be aware of.

== System Requirements

If you plan to develop Helidon projects and applications on Windows, make sure your environment meets the following requirements:

* All of the requirements listed in xref:prerequisites.adoc[Getting Started]
* _If using the xref:cli.adoc[Helidon CLI] (which is recommended)_, Visual C\+\+ Redistributable Runtime. Download at https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-c-redistributable-v14[Microsoft Visual C++ Redistributable latest supported downloads]

The following are recommended but not required:

* curl
* PowerShell (_not_ Windows PowerShell)
* Windows Terminal

TIP: If you do not have `curl` installed, in PowerShell, you can use `Invoke-WebRequest` instead.