///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:description: Configuration of io.helidon.metrics.api.RegistrySettings
:keywords: helidon, config, io.helidon.metrics.api.RegistrySettings
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.metrics.api.RegistrySettings

[source,text]
.Type
----
io.helidon.metrics.api.RegistrySettings
----



==== Configuration options




Optional configuration options:
[cols="3,3,2,5"]

|===
|key |type |default value |description

|`enabled` |boolean |`true` |Sets whether the metric type should be enabled.
|`filter` |link:../../includes/config/io.helidon.metrics.api.RegistryFilterSettings.adoc[RegistryFilterSettings] |{nbsp} |Name filtering, featuring optional exclude and include settings

|===
