///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.media.common.MediaContext
:keywords: helidon, config, io.helidon.media.common.MediaContext
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.media.common.MediaContext
include::{rootdir}/includes/attributes.adoc[]

= MediaContext (media.common) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.media.common/io.helidon.media.common.MediaContext[io.helidon.media.common.MediaContext]




== Configuration options



Optional configuration options:
[cols="3,3,2,5a"]

|===
|key |type |default value |description

|`discover-services` |boolean |{nbsp} |Whether Java Service Loader should be used to load MediaSupportProvider.
|`filter-services` |boolean |{nbsp} |Whether services loaded by Java Service Loader should be filtered.
 All of the services which should pass the filter, have to be present under `services` section of configuration.
|`register-defaults` |boolean |{nbsp} |Whether default readers and writers should be registered
|`services` |Object[&#93; |{nbsp} |Configuration section for each service. Each entry has to have "name" parameter. It is also used for filtering of loaded services

|===

// end::config[]