///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= MicroProfile Health
:spec-name: MicroProfile Health
:description: {spec-name} support in Helidon MP
:keywords: helidon, mp, microprofile, health
:h1Prefix: MP
:health-release: {version.lib.microprofile-health}
:feature-name: MicroProfile Health
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc
:microprofile-bundle: true

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source,xml]
----
        <dependency>
            <groupId>io.helidon.microprofile.health</groupId>
            <artifactId>helidon-microprofile-health</artifactId>
        </dependency>
----

To enable built-in health checks add the following dependency
(or use the <<mp/introduction/02_microprofile.adoc, helidon-microprofile bundle>> )

[source,xml]
----
        <dependency>
            <groupId>io.helidon.health</groupId>
            <artifactId>helidon-health-checks</artifactId>
        </dependency>
----

== Overview
Microservices expose their health status primarily so external tools (for example, an orchestrator such as Kubernetes)
can monitor each service and take action, such as restarting a service instance if it has failed
or temporarily shunting traffic away from the instance if the service is unable to process
incoming requests normally.

== About the MicroProfile Health Specification
Helidon MP implements the MicroProfile Health
link:http://download.eclipse.org/microprofile/microprofile-health-{health-release}/microprofile-health-spec.html[spec].
The spec prescribes how external tools probe a service's health checks and how you
implement health checks as part of your microservice that are specific to your service's needs.

== Concepts

=== Liveness, Readiness, and Startup Checks

MicroProfile Health supports three types of health checks:

_Liveness_ checks report whether the runtime environment in which the service is running
is sufficient to support the work the service performs.
The environment is beyond the control of
the service itself and typically cannot improve without outside intervention.
If a microservice instance reports a `DOWN`
liveness check, it should never report `UP` later.
It will need to be stopped and a replacement instance created.

_Readiness_ checks report whether the service is _currently_ capable of performing its work.
A service that reports `DOWN` for its readiness cannot _at the moment_ do its job, but at
some future point it might become able to do so without requiring a restart.

_Startup_ checks indicate whether the service has started to the point where liveness and readiness checks even make sense.
 A service reporting `DOWN` for a startup check is still initializing itself and normally will report `UP`, assuming it has started successfully.

The following table describes more about these types of health checks, including how an orchestrator
such as Kubernetes might react.

=== Known Health Check Endpoints
A MicroProfile-compliant service reports its health via known REST endpoints. Helidon MP
provides these endpoints automatically as part of every MP microservice.

External management tools (or `curl` or browsers) retrieve health checks using the REST endpoints in the following table which summarizes the types of health checks in MicroProfile Health.
Responses from the health endpoints report `200` (OK), `204` (no content), or `503` (service unavailable) depending on the outcome of running the health checks.
HTTP `GET` responses include JSON content showing the detailed results of all the health checks which the server executed after receiving the request.
HTTP `HEAD` requests return only the status with no payload.


.Types of Health Checks
|===
|Type | Meaning | REST endpoint | Kubernetes response on failure

|liveness
|whether the runtime environment is suitable
|`/health/live`
|Restarts container.

|readiness
|whether the microservice is currently capable of doing its work
|`/health/ready`
|Diverts requests away from the instance; periodically rechecks readiness and resumes traffic once the
microservice reports itself as ready.

|startup
|whether the microservice has initialized to the point where liveness and readiness checks might pass
|`/health/started`
|Treats the instance as still starting up; does not check liveness or readiness until the startup probe reports success or times out according to its configuration.
|===

=== Built-in and Custom Health Checks

==== Built-in Health Checks
Helidon provides built-in, default checks for each endpoint.
The built-in liveness checks include various environmental values, such as whether the JVM has detected deadlocks
or whether there is sufficient heap space. The built-in readiness and startup checks always report `UP`.

You can see all the defaults by accessing any Helidon MP microservice's `/health/live` endpoint
and viewing the response.

==== Custom Health Checks
Add your own liveness, readiness, or startup checks by adding a Java class for each check.
Each custom check must implement the `HealthCheck` interface, and you add either the `@Liveness`,
 `@Readiness`, or `@Startup` annotation to the class.

=== Next Steps
Add custom health checks to your own microservices.

The
<<mp/guides/04_health.adoc, Helidon MP Health Check Guide>> shows how to create a
sample project and add custom health checks.