///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2020, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
ifndef::flavor-lc[:flavor-lc: se]
ifndef::flavor-uc[:flavor-lc: SE]
ifndef::se-flavor[:se-flavor: true]
ifndef::h1-prefix[:h1-prefix: SE]

//Contains content that is shared between multiple CORS pages.
:keywords: helidon, java, cors, se
:basic-table-intro:
:config-table-methods-column-header: builder method
:cors-config-key-explanation:

:ws-cors-javadoc: {webserver-cors-javadoc-base-url}/io/helidon/webserver/cors
:cors-javadoc: {cors-javadoc-base-url}/io/helidon/cors

= CORS Shared content

// tag::cors-intro[]
ifdef::se-flavor[:built-in-service-prefix: /observe]
ifndef::se-flavor[:built-in-service-prefix: ]

The link:https://www.w3.org/TR/cors[cross-origin resource sharing (CORS) protocol] helps developers control if and how REST resources served by their applications can be shared across origins.
Helidon {flavor-uc} includes an implementation of CORS that you can use to add CORS behavior
to the services you develop. You can define your application's CORS behavior programmatically using the Helidon CORS API alone or together with configuration.

== Before You Begin
ifdef::se-flavor[=== Planning Your Resource Sharing]
Before you revise your application to add CORS support, you need to decide what type of cross-origin sharing you want
to allow for each resource your application exposes.
For example, suppose for a given resource you want to allow unrestricted sharing for GET, HEAD, and POST requests
(what CORS refers to as "simple" requests), but permit other types of requests only from the two
origins `foo.com` and `there.com`.
Your application would implement two types of CORS sharing: more relaxed for the
simple requests and stricter for others.

Once you know the type of sharing you want to allow for each of your resources--including any from built-in
services--you can change your application accordingly.
// end::cors-intro[]

// The add-cors-dependency tag's contents is reused from other SE and MP pages.
// The actual dependency is different for SE and MP, so we tag it separately from the intro text so the
// MP pages can reuse this intro text but use their own "actual" dependency. We could have parameterized
// the groupID and artifactID but this approach allows the actual dependencies themselves to be
// in the source literally rather than parameterized.
// tag::add-cors-dependency[]
The xref:{rootdir}/about/managing-dependencies.adoc[Managing Dependencies] page describes how you
should declare dependency management for Helidon applications.
For CORS support in Helidon {flavor-uc}, you must include
the following dependency in your project:
// end::add-cors-dependency[]

//tag::cors-configuration-formats-intro[]
=== Understanding the CORS Configuration Formats [[cors-configuration-formats]]

CORS configuration is done through link:{ws-cors-javadoc}/CorsFeature.html[`CorsFeature`], a `WebServer` feature that configures CORS for the whole application.
This configuration contains a list of protected `paths`, which use the Cross-Origin options and are mapped to the link:{ws-cors-javadoc}/CorsPathConfig.html[`CorsPathConfig`].
//end::cors-configuration-formats-intro[]

//tag::cors-feature-config[]
[[cross-origin-feature-config]]
=== Cross-Origin Server Feature Configuration

include::{rootdir}/config/io_helidon_webserver_cors_CorsFeature.adoc[leveloffset=+1,tag=config]
//end::cors-feature-config[]

The following example only adds defaults (allow all origins and all methods):

[source,yaml]
----
cors:
  enabled: true <1>
----
<1> To only use defaults, enabled must be set to `true`, as otherwise the feature is enabled only if at least one path is configured under `paths`

The following example limits cross-origin resource sharing for `PUT` and
`DELETE` operations to only `foo.com` and `there.com`, and allows all other methods and origins

[source,yaml]
----
cors:
  paths:
    path-pattern: "/*" <1>
    allow-origins: ["https://foo.com", "https://there.com"]
    allow-methods: ["PUT", "DELETE"]
----
<1> A path pattern that matches all paths on the server

=== Cross-Origin Path Configuration

All configuration options that can be used for each `path` when configuring CORS.

include::{rootdir}/config/io_helidon_webserver_cors_CorsPathConfig.adoc[leveloffset=+1,tag=config]

// tag::accessing-shared-resources-intro[]
=== Accessing the Shared Resources
If you have edited the Helidon {flavor-uc} QuickStart application as described in the previous topics and saved your changes,
you can build and run the application. Once you do so you can execute `curl` commands to demonstrate the behavior changes
in the metric and health services with the addition of the CORS functionality. Note the addition of the
`Origin` header value in the `curl` commands, and the `Access-Control-Allow-Origin` in the successful responses.

==== Build and Run the Application
Build and run the QuickStart application as usual.
// end::accessing-shared-resources-intro[]

// tag::cors-and-requested-uri-intro[]
== CORS and the Requested URI Feature
The decisions the Helidon CORS feature makes depend on accurate information about each incoming request,
particularly the host to which the request is sent.
Conveyed as headers in the request, this information can be changed or overwritten by intermediate nodes--such as load
balancers--between the origin of the request and your service.

Well-behaved intermediate nodes preserve this important data in other headers, such as `Forwarded`.
// end::cors-and-requested-uri-intro[]

// tag::cors-and-requested-uri-wrapup[]
The CORS support in Helidon uses the requested URI feature to discover the correct information about each request,
according to your configuration, so it can make accurate decisions about whether to permit cross-origin accesses.
// end::cors-and-requested-uri-wrapup[]

// tag::configuring-cors-for-builtin-services[]
== Configuring CORS for Built-in Services
Use configuration to control whether and how each of the built-in services works with CORS.

In the `cors` configuration section add a block for each built-in service using its path as described in the
CORS configuration section.
// Tag the following example so we can exclude it from MP which supplies its own complete example.
// tag::se-config-example[]
The following example restricts sharing of the
`{built-in-service-prefix}/health` resource, provided by the health built-in service, to only the origin `\https://there.com`.
[source,yaml,subs="attributes+"]
----
cors:
  paths:
    - "path-pattern": "{built-in-service-prefix}/health"
      "allow-origins": ["https://there.com"]
    - "path-pattern": "{built-in-service-prefix}/metrics"
      "allow-origins": ["https://foo.com"]
----

// end::se-config-example[]

// end::configuring-cors-for-builtin-services[]


// tag::accessing-shared-resources-main[]
=== Retrieve Metrics
The metrics service rejects attempts to access metrics on behalf of a disallowed origin.
[source,bash,subs="attributes+"]
----
curl -i -H "Origin: https://other.com" http://localhost:8080{built-in-service-prefix}/metrics
----

[source, listing]
.Curl output
----
HTTP/1.1 403 Forbidden
Date: Mon, 11 May 2020 11:08:09 -0500
transfer-encoding: chunked
connection: keep-alive
----

But accesses from `foo.com` succeed.
[source,bash,subs="attributes+"]
----
curl -i -H "Origin: https://foo.com" http://localhost:8080{built-in-service-prefix}/metrics
----

[source, listing]
.Curl output
----
HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://foo.com
Content-Type: text/plain
Date: Mon, 11 May 2020 11:08:16 -0500
Vary: Origin
connection: keep-alive
content-length: 6065

# TYPE base_classloader_loadedClasses_count gauge
# HELP base_classloader_loadedClasses_count Displays the number of classes that are currently loaded in the Java virtual machine.
base_classloader_loadedClasses_count 3568
----

==== Retrieve Health
The health service rejects requests from origins not specifically approved.

[source,bash,subs="attributes+"]
----
curl -i -H "Origin: https://foo.com" http://localhost:8080{built-in-service-prefix}/health
----

[source, listing]
----
HTTP/1.1 403 Forbidden
Date: Mon, 11 May 2020 12:06:55 -0500
transfer-encoding: chunked
connection: keep-alive
----

And responds successfully only to cross-origin requests from `\https://there.com`.

[source,bash,subs="attributes+"]
----
curl -i -H "Origin: https://there.com" http://localhost:8080{built-in-service-prefix}/health
----

[source, listing]
----
HTTP/1.1 200 OK
Access-Control-Allow-Origin: https://there.com
Content-Type: application/json
Date: Mon, 11 May 2020 12:07:32 -0500
Vary: Origin
connection: keep-alive
content-length: 461

{"outcome":"UP",...}
----
// end::accessing-shared-resources-main[]
