///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2021, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]

// tag::maven-dependency[]
== Maven Coordinates [[maven-coordinates]]

To enable {feature-name}
ifeval::["{microprofile-bundle}" == "true"]
either add a dependency on the xref:{rootdir}/mp/introduction/microprofile.adoc[helidon-microprofile bundle] or
endif::[]
add the following dependency to your project's `pom.xml` (see
 xref:{rootdir}/about/managing-dependencies.adoc[Managing Dependencies]).
// end::maven-dependency[]
