///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////


= Oracle Cloud Infrastructure Tutorial
:description: Helidon OCI Integration
:keywords: oci, cdi, Oracle Cloud Infrastructure
:feature-name: OCI Integration
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

This guide describes the basic process of deploying a Helidon MP application on Oracle Cloud Infrastructure (OCI).

== Overview

Oracle Cloud Infrastructure (OCI) is a set of complementary cloud services that enable you to build and run a range of applications and services in a highly available hosted environment. See link:{oci-doc-url}/Content/GSG/Concepts/baremetalintro.htm[OCI documentation].

By deploying Helidon applications on OCI, you can take advantage of OCI services and features. Helidon integration with OCI includes support for the link:{oci-doc-url}/Content/API/SDKDocs/javasdk.htm[OCI SDK for Java] - allowing you to write custom code to extend features. Helidon also provides a link:{jakarta-cdi-spec-url}#spi[Helidon OCI SDK CDI portable extension] to support
injecting link:{oci-javasdk-url}[Oracle Cloud Infrastructure SDK Clients] in your Helidon MicroProfile application.

This guide and the Helidon Quick Start for OCI are currently only available with Helidon MP. However, you can write Helidon SE applications directly with the link:{oci-doc-url}/Content/API/SDKDocs/javasdk.htm[OCI SDK for Java APIs] and use this guide as a guideline for setting up your OCI environment.

== What You Need

For this tutorial, you will need the following:

include::{rootdir}/includes/prerequisites.adoc[tag=prerequisites-cli]

== Generating the Project

You can generate Helidon MP project files for OCI using the Helidon Project Starter.

A Helidon Project Starter allows you to choose from a set of archetypes with pre-defined feature sets and lets you customize it by providing a host of options.

. Go to the https://helidon.io/starter[Helidon Project Starter] page on the Helidon website.
. Under *Helidon Flavor*, select *Helidon MP* and click *Next*.
. Under *Application Type*, select *OCI* and click *Next*.
. If you are using this application for testing or development purposes, then under *Customize Project*, leave the values as default and go to the next step. If you want to use the generated project as the basis for a production application, then replace `groupId`, `artifactId` and `package` with values appropriate for your application.
. Click *Download* to save the project zip archive to your computer.
. Extract the project files.

.Click to view the structure of the Helidon MP OCI project starter.
[%collapsible]
====
----
├── README.md
├── client
│   ├── README.md
│   ├── pom.xml
│   └── src
│       └── main
│           └── resources
│               └── META-INF
│                   └── beans.xml
├── pom.xml
├── server
│   ├── Dockerfile
│   ├── README.md
│   ├── app.yaml
│   ├── distribution.xml
│   ├── pom.xml
│   └── src
│       ├── main
│       │   ├── java
│       │   │   └── me
│       │   │       └── username
│       │   │           └── mp
│       │   │               └── oci
│       │   │                   └── server
│       │   │                       ├── GreetLivenessCheck.java
│       │   │                       ├── GreetReadinessCheck.java
│       │   │                       ├── GreetResource.java
│       │   │                       ├── GreetingProvider.java
│       │   │                       └── package-info.java
│       │   └── resources
│       │       ├── META-INF
│       │       │   ├── beans.xml
│       │       │   ├── microprofile-config-prod.properties
│       │       │   ├── microprofile-config-test.properties
│       │       │   └── microprofile-config.properties
│       │       ├── application.yaml
│       │       └── logging.properties
│       └── test
│           └── java
│               └── me
│                   └── username
│                       └── mp
│                           └── oci
│                               └── server
│                                   ├── Common.java
│                                   ├── GreetResourceConfigFileTest.java
│                                   ├── GreetResourceInstancePrincipalTest.java
│                                   └── GreetResourceMockedTest.java
└── spec
    ├── README.md
    └── api.yaml
----
====

Alternatively, you can also use the Helidon CLI to generate the Helidon MP OCI project instead.

== Running the Application Locally

Use the project to build an application jar for the example. It saves all runtime dependencies in the `/target/libs` directory, allowing you to easily start the application by running the application jar file.

. Change to the directory containing the project files and run:

[source,bash]
.Build the Application
----
mvn package
----

. Then, to run the application, run:

[source,bash]
.Run the application
----
java -jar server/target/myproject-server.jar
----

The example is a very simple "Hello World" greeting service. It supports GET requests for generating a greeting message, and a PUT request for changing the greeting itself. The response is encoded using JSON.

For example:

[source,bash]
.Try the Application
----
curl -X GET http://localhost:8080/greet
{"message":"Hello World!"}

curl -X GET http://localhost:8080/greet/Joe
{"message":"Hello Joe!"}

curl -X PUT -H "Content-Type: application/json" -d '{"greeting" : "Hola"}' http://localhost:8080/greet/greeting

curl -X GET http://localhost:8080/greet/Jose
{"message":"Hola Jose!"}
----

== Deploying a Helidon Application on OCI

You can deploy a Helidon application to an Oracle Cloud Infrastructure (OCI) environment, using either OCI Compute or OCI Kubernetes Engine (OKE). Depending on your requirements, one option might be better suited to your needs than the other.

* **OCI Compute** lets you provision and manage Compute hosts, known as instances, to run your applications. Instances can be either bare metal or virtual machines (VM). See link:{oci-doc-url}/Content/Compute/home.htm[Compute] in OCI documentation for more information.

* **OKE** is a fully-managed, scalable, and highly available service that you can use to deploy your containerized applications to the cloud. See link:{oci-doc-url}/Content/ContEng/home.htm[Kubernetes Engine] in OCI documentation for more information.

After you have selected your OCI environment, you can get started with deploying your Helidon applications.

* To learn how to deploy a Helidon MP application on OCI Compute, follow the instructions outlined at https://github.com/helidon-io/helidon-labs/blob/main/hols/oci-basic-setup/README.md[Deploying a Helidon OCI MP Application on a Basic OCI Setup] in the Helidon Labs GitHub repository.
* To learn how to deploy a Helidon MP application on OCI OKE, follow the instructions outlined at link:{oci-doc-url}/developer-tutorials/tutorials/helidon-k8s/01oci-helidon-k8s-summary.htm[Kubernetes: Deploy a Java Helidon Application] in OCI documentation. Make sure you select *OCI* as the Application Type, and _not_ Quickstart.

=== Integrating with OCI Services

Before you can use OCI services, you must properly configure your application to run on OCI. The Helidon MP OCI Project Starter is already partially configured to integrate with several common OCI services but you must update its configuration with values specific to your application and OCI environment. 

See xref:../integrations/oci.adoc[OCI Integration] for more information on how to configure your Helidon application to integrate with Helidon services.

The Helidon OCI SDK extension also supports injecting clients for any link:{oci-javasdk-url}#Services_Supported[OCI services supported by the OCI SDK for Java].


NOTE: Whenever you integrate a new OCI service in your application, you must build and redeploy the application to enable the OCI service's features.
