///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Helidon MP Guides
:keywords: helidon, java, microservices, microprofile, guides
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

== Getting Started

[PILLARS]
====
[CARD]
.Quickstart MP
[link=quickstart.adoc]
--
Create your first Helidon MP application in under 5 minutes.
--
====

== Helidon MP Guides

[PILLARS]
====
[CARD]
.MP Config Guide
[link=config.adoc]
--
Learn how to configure a Helidon MP application.
--

[CARD]
.MP Health Check Guide
[link=health.adoc]
--
Learn how to use Helidon MP built-in and custom health checks.
--

[CARD]
.MP Metrics Guide
[link=metrics.adoc]
--
Learn how to use Helidon MP built-in and application metrics.
--

[CARD]
.MP Tracing Guide
[link=tracing.adoc]
--
Learn how to trace a Helidon MP application.
--

[CARD]
.Helidon MP Tutorial
[link=mp-tutorial.adoc]
--
Learn how to build a Helidon MicroProfile (MP) application from scratch.
--

[CARD]
.Helidon MP Upgrade guide
[link=upgrade.adoc]
--
Learn how to upgrade your Helidon MP application from 1.x to 2.x.
--

[CARD]
.OIDC Tutorial
[link=security-oidc.adoc]
--
Learn how to set up OIDC security in your Helidon MP application.
--

[CARD]
.Helidon MP Tracing
[link=tracing.adoc]
--
Learn how to use tracing in your Helidon MP application.
--

[CARD]
.Testing with JUnit 5
[link=testing-junit5.adoc]
--
Learn how to use JUnit5 for testing your applications.
--

[CARD]
.Helidon MP and JBatch
[link=jbatch.adoc]
--
Learn how to use JBatch with Helidon MP.
--

[CARD]
.Performance tuning in Helidon MP
[link=performance-tuning.adoc]
--
Learn how to improve performance of your application.
--
====

== Build and Deploy

[PILLARS]
====
[CARD]
.Maven Guide
[link=maven-build.adoc]
--
Using Helidon in your Maven project.
--

[CARD]
.Gradle Guide
[link=gradle-build.adoc]
--
Using Helidon in your Gradle project.
--

[CARD]
.GraalVM Native Images
[link=graalnative.adoc]
--
Learn how to build a GraalVM native image for your Helidon application
both on your desktop and as part of a Docker image.
--

[CARD]
.Custom Runtime Images using jlink
[link=jlink-image.adoc]
--
Learn how to build a custom runtime Java image for your Helidon application
both on your desktop and as part of a Docker image.
--

[CARD]
.Building Container Images with Jib
[link=../../guides/jib.adoc]
--
Learn how to use Jib to create a container image without Docker.
--

[CARD]
.Deploying to OKE
[link=../../guides/oke.adoc]
--
Learn how to deploy your application to Oracle Cloud Infrastructure Container Engine for Kubernetes (OKE).
--
====
