///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon MP Quick Start
:description: Helidon MP Quick Start guide
:keywords: Helidon, MicroProfile, MP
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

This quick start describes how to create and run a basic Helidon MP application and optionally, how to build a Docker image and use Kubernetes to deploy it.

== Generate the Project

The Helidon *Project Starter* allows you to quickly generate a project with basic functionality that lets you explore the features of Helidon and that's also customizable enough to use as a starting point for your own projects and applications.

. Make sure your environment is properly set up for Helidon development. See xref:prerequisites.adoc[Getting Started].
. Go to the https://helidon.io/starter[Helidon Project Starter] page on the Helidon website.
. Under *Helidon Flavor*, select *Helidon MP* and click *Next*.
. Under *Application Type*, select *Quickstart* and click *Next*.
. Under *Media Support*, select a JSON library and click *Next*.
. Under *Customize Project*, leave the values set to their default values since this is a tutorial. If you were planning on using this project as a base for a real application, you would update the values accordingly.
. Click *Download* to save the project zip archive to your computer. This is the Maven project that's the basis for your Helidon Quick Start application.

TIP: You can also generate the Quick Start project using the xref:../../about/cli.adoc[Helidon CLI]. Run the following command to create a Maven project in your current directory: `helidon init --batch -Dflavor=mp -Dapp-type=quickstart`

Now that you've generated the project, you can build a Helidon application and start experimenting.

. Extract the project files and navigate to the expanded directory. You should have the following files and folders:
    * `.idea/`: Project-specific settings files for a JetBrains IntelliJ project.
    * `src/`: Application source code
    * `.gitignore`: A basic gitignore file designed for Maven projects.
    * `.helidon`: Helidon project metadata.
    * `app.yaml`: A Kubernetes Deployment and Service definition.
    * `pom.xml`: The Maven project file.
    * `README.md`: An overview of the capabilities of this project.
    * Various Docker related files
. Build the application by running `mvn package`. The project builds an application jar and saves all runtime dependencies in the `target/libs` directory, making it easy to start the application.
. Start the application by running `java -jar target/myproject.jar`. The name of your application .jar file matches the `artifactId` specified when you built the Project Starter. If you changed the default `artifactId`, make sure you update the .jar file name in the command accordingly.

The example application generated by the Project Starter is a simple `"Hello, World!"` greeting service. It supports GET requests for generating a greeting message, and a PUT request for changing the greeting itself. The response is encoded using JSON. For example:

[source,bash]
----
curl -X GET http://localhost:8080/greet
{"message":"Hello World!"}

curl -X GET http://localhost:8080/greet/Joe
{"message":"Hello Joe!"}

curl -X PUT -H "Content-Type: application/json" -d '{"greeting" : "Hola"}' http://localhost:8080/greet/greeting

curl -X GET http://localhost:8080/greet/Jose
{"message":"Hola Jose!"}
----

Congratulations! You now have a working Helidon MP application. You can use it to:

* Experiment with Helidon MP features and services
** Try out the <<health-metrics,Health service and the Metrics service>>
* <<build-docker-image,Build a Docker Image>>
* <<deploy-k8s,Deploy it to Kubernetes>>
* <<build-graalvmni-customjava,Build GraalVM Native and Custom Java Runtime Images>>

and much more!

[#health-metrics]
== Track Health and Metrics

Helidon provides built-in support for monitoring the Health and Metrics endpoints in your application.

Use the Health component to monitor the health of your microservice to make sure it is available and performing correctly. For more information on how to retrieve and monitor Health data about your application, see xref:../health.adoc[Health].

[source,bash]
.To see general Health endpoint data, run:
----
curl -s -X GET http://localhost:8080/health
----

Use the Metrics component to export telemetry to management agents and to register and update metrics to expose telemetry data from their services. For more information on how to generate and send Metrics data from your application, see xref:../metrics/metrics.adoc[Metrics].

[source,bash]
.To see Metrics data rendered in Prometheus format, run:
----
curl -s -X GET http://localhost:8080/metrics
----

[source,bash]
.To see Metrics data rendered in JSON format, run:
----
curl -H 'Accept: application/json' -X GET http://localhost:8080/metrics
----

[#build-docker-image]
== Build a Docker Image

The project includes a Dockerfile so that you can easily build and run a Docker image.

NOTE: To build the Docker image, you must have Docker installed and running on your system.

. Build the Docker image by running `docker build -t myproject .`.
. Run the Docker image by running `docker run --rm -p 8080:8080 myproject:latest`.
. As you did earlier, you can test the `"Hello, World!"` application as a Docker image using GET and PUT requests. For example,

[source,bash]
----
curl -X GET http://localhost:8080/greet
{"message":"Hello World!"}

curl -X GET http://localhost:8080/greet/Joe
{"message":"Hello Joe!"}

curl -X PUT -H "Content-Type: application/json" -d '{"greeting" : "Hola"}' http://localhost:8080/greet/greeting

curl -X GET http://localhost:8080/greet/Jose
{"message":"Hola Jose!"}
----

[#deploy-k8s]
== Deploy Application to Kubernetes

To deploy the application to Kubernetes, you must have access to a Kubernetes cluster. Some lightweight options for running Kubernetes include Docker Desktop or minikube. This quick start assumes you're using Docker Desktop. See https://docs.docker.com/desktop/[Docker Desktop] in the Docker documentation. 

If you haven't already, install `kubectl`, the Kubernetes command line tool. See https://kubernetes.io/docs/tasks/tools/#kubectl[Install kubectl] in the Kubernetes documentation.

. Set up a Kubernetes cluster.
. Verify that you can connect to the cluster by running `kubectl cluster-info` and then running `kubectl get nodes`.
. Navigate to the Quick Start project folder, `myproject/`.
. Deploy the application to Kubernetes by running `kubectl create -f app.yaml` and then `kubectl get pods`. Wait for the quick start pod to be `RUNNING`.
+
This will create a service that is exposed to any node port.
. Look up the new service to find the port by running `kubectl get service myproject`.
+
Make a note of the port numbers. If you want to access the Health and Metrics endpoints, make sure you use the NodePort number (the second port number) instead of `8080`. For example, `curl -X GET http://localhost:31431/greet`.

To remove the application from Kubernetes, run `kubectl delete -f app.yaml`.

[#build-graalvmni-customjava]
== Build GraalVM Native and Custom Java Runtime Images

Helidon also includes support for GraalVM Native Images and custom Java Runtime Images. For more information, see:

* xref:graalnative.adoc[GraalVM Native Images]
* xref:jlink-image.adoc[Custom Java Runtime Images using `jlink`]
