///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon MP 4.x Upgrade Guide
:description: Helidon MP 4.x Upgrade Guide
:keywords: helidon, porting, migration, upgrade, incompatibilities, 3.x
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

Helidon 4.x introduces significant changes to APIs and runtime behavior. Use this guide to help you understand the changes required to transition a Helidon MP 3.x application to Helidon 4.x.

== Significant Changes

The following sections describe the changes between Helidon 3.x and Helidon 4.x that can significantly impact your development process. Review them carefully.

You can also review the https://github.com/helidon-io/helidon/blob/main/CHANGELOG.md[Helidon repository CHANGELOG] to see a detailed history of changes made to the project.

NOTE: Helidon adheres to https://semver.org/spec/v2.0.0.html[Semantic Versioning]. As such, Helidon 4.x includes changes that are not backward compatible with Helidon 3.x.

=== Java SE Support

Helidon 4.x removes support for Java SE 17. You must use Java SE 21 or later. If you are using Helidon 4.3.0 or later, using Java SE 25 or later is recommended.

=== New Web Server Implementation

Helidon 4.x introduces Helidon WebServer, a virtual threads-based web server implementation based on the JDK Project Loom. Helidon WebServer replaces Netty, the server implementation used by previous versions of Helidon.

Helidon provides a MicroProfile server implementation (`io.helidon.microprofile.server.Server`) that encapsulates the Helidon WebServer.

=== MicroProfile Support

Helidon 4.0.0 adds support for https://download.eclipse.org/microprofile/microprofile-6.0/microprofile-spec-6.0.html#microprofile6.0[MicroProfile 6.0]. Key changes include:

* Significant updates to the https://download.eclipse.org/microprofile/microprofile-metrics-5.0.0/microprofile-metrics-spec-5.0.0.html[MicroProfile Metrics specification].
* Addition of the MicroProfile Telemetry specification which replaces the MicroProfile OpenTracing specification.
* Support for the https://jakarta.ee/specifications/coreprofile/10/jakarta-coreprofile-spec-10.0#introduction[Jakarta EE 10 Core Profile] (instead of individual Jakarta EE specifications).
* Various minor updates to other MicroProfile specifications. Review the individual MicroProfile specifications for details.

Helidon 4.1.0 adds support for https://download.eclipse.org/microprofile/microprofile-6.1/microprofile-spec-6.1.html#microprofile6.1[MicroProfile 6.1].

NOTE: Read each specification carefully to check for incompatible changes.

== Other Changes

The following sections describe changes between Helidon 3.x and Helidon 4.x that may impact your development process.

=== Jandex

The Jandex groupId changed from `org.jboss.jandex` to `io.smallrye`. You should update all references accordingly.

=== Testing

Testing support moved to a new Maven artifact and Java package.

In Helidon 3.x, it was:

[source, xml]
----
<dependency>
    <groupId>io.helidon.microprofile.tests</groupId>
    <artifactId>helidon-microprofile-tests-junit5</artifactId>
    <scope>test</scope>
</dependency>
----

In Helidon 4.x, it is now:

[source, xml]
----
<dependency>
    <groupId>io.helidon.microprofile.testing</groupId>
    <artifactId>helidon-microprofile-testing-junit5</artifactId>
    <scope>test</scope>
</dependency>
----

Additionally, the Java package changed from `io.helidon.microprofile.tests.junit5` to `io.helidon.microprofile.testing.junit5`.

Update all references accordingly.

=== Logging

The Helidon console handler changed from `io.helidon.common.HelidonConsoleHandler` to `io.helidon.logging.jul.HelidonConsoleHandler`.

If you use this handler in your `logging.properties` file, you must update it and add the following dependency:

[source, xml]
----
<dependency>
    <groupId>io.helidon.logging</groupId>
    <artifactId>helidon-logging-jul</artifactId>
    <scope>runtime</scope>
</dependency>
----
