///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2025, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Declarative

:description: Helidon SE Declarative
:keywords: helidon, se, injection, declarative
:h1Prefix: SE
:feature-name: Declarative
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

== Contents

- <<Overview, Overview>>
- <<Usage, Usage>>
- <<Features, Features>>

== Overview

Helidon declarative programming model allows inversion of control style programming with all the performance benefits of Helidon SE.

Our declarative approach has the following advantages:

- Uses Helidon SE imperative code to implement features (i.e. performance is same as "pure" imperative application)
- Generates all the necessary code at build-time, to avoid reflection and bytecode manipulation at runtime
- It is based on xref:injection.adoc#Overview[Helidon Injection]
- Declarative features are in the same modules as Helidon SE features (i.e. does not require additional dependencies)

[NOTE]
Helidon Declarative is an incubating feature. The APIs shown here are subject to change. These APIs will be finalized in a future release of Helidon.

== Usage

To create a declarative application, use the annotations provided in our Helidon SE modules (details under <<Features, Features>>), and the maven plugin
described in xref:injection.adoc#generate-binding[Injection: Startup] to generate the binding.

In addition, the following section must be added to the `build` of the Maven `pom.xml` to enable annotation processors that generate the necessary code:

[source,xml]
----
<plugins>
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
            <annotationProcessorPaths>
                <path>
                    <groupId>io.helidon.bundles</groupId>
                    <artifactId>helidon-bundles-apt</artifactId>
                    <version>${helidon.version}</version>
                </path>
            </annotationProcessorPaths>
        </configuration>
    </plugin>
</plugins>
----


== Features

The following features are currently implemented:

- <<Dec-Config, Configuration>>
- <<Dec-HTTP-Server, HTTP Server Endpoint>>
- <<Dec-HTTP-Client, Typed HTTP Client>>
- <<Dec-GRPC-Server, gRPC Server Endpoint>>
- <<Dec-GRPC-Client, Typed gRPC Client>>
- <<Dec-FT, Fault Tolerance>>
- <<Dec-Scheduling, Scheduling>>
- <<Dec-Validation, Validation>>
- <<Dec-Security, Security>>
- <<Dec-Metrics, Metrics>>
- <<Dec-Tracing, Tracing>>
- <<Dec-WebSocket-Server, WebSocket Server>>
- <<Dec-WebSocket-Client, WebSocket Client>>
- <<Dec-CORS, WebServer CORS>>
- <<Dec-Health, Health Checks>>

A Helidon Declarative application should be started using the generated application binding, to ensure no lookup and no reflection.
The call to `ServiceRegistryManager.start` ensures that all services with a defined `RunLevel` are started, including Helidon WebServer, Scheduled services etc.

[source,java]
.Example of a declarative main class
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_1, indent=0]
----

=== Configuration [[Dec-Config]]

Configuration can be injected as a whole into any service, or a specific configuration option can be injected using `@Configuration.Value`. Default values can be defined using annotations in `@Default`

Services available for injection:

- link:{config-javadoc-base-url}/io/helidon/config/Config.html[`io.helidon.config.Config`]

Annotations:

- link:{config-javadoc-base-url}/io/helidon/config/Configuration.html[`io.helidon.config.Configuration.Value`] - define the configuration key to inject, on constructor parameter
- Annotations defined in link:{common-javadoc-base-url}/io/helidon/common/Default.html[`io.helidon.common.Default`] - define a default typed value, on the same constructor parameter

Example of usage can be seen below in HTTP Server Endpoint example.

=== HTTP Server Endpoint [[Dec-HTTP-Server]]

To create an HTTP endpoint, simply annotate a class with `@RestServer.Endpoint`, and
add at least one method annotated with one of the HTTP method annotations, such as `@Http.GET`.

Services available for injection:

N/A

Supported method parameters (no annotation required):

- link:{webserver-javadoc-base-url}/io/helidon/webserver/http/ServerRequest.html[`io.helidon.webserver.http.ServerRequest`]
- link:{webserver-javadoc-base-url}/io/helidon/webserver/http/ServerResponse.html[`io.helidon.webserver.http.ServerResponse`]
- link:{context-javadoc-base-url}/io/helidon/common/context/Context.html[`io.helidon.common.context.Context`]
- `io.helidon.common.security.SecurityContext`
- link:{security-javadoc-base-url}/io/helidon/security/SecurityContext.html`[`io.helidon.security.SecurityContext] - in case `helidon-security` module is on the classpath

Annotations on endpoint type:

- link:{webserver-javadoc-base-url}/io/helidon/webserver/http/RestServer.Endpoint.html[`io.helidon.webserver.http.RestServer.Endpoint`] - required annotation
- link:{webserver-javadoc-base-url}/io/helidon/webserver/http/RestServer.Listener.html[`io.helidon.webserver.http.RestServer.Listener`] - to define the named listener this should be served on (named port/socket)
- link:{webserver-javadoc-base-url}/io/helidon/webserver/http/RestServer.Header.html[`io.helidon.webserver.http.RestServer.Header`] - header to return with each response from this endpoint
- link:{webserver-javadoc-base-url}/io/helidon/webserver/http/RestServer.ComputedHeader.html[`io.helidon.webserver.http.RestServer.ComputedHeader`] - computed header to return with each response from this endpoint
- link:{http-javadoc-base-url}/io/helidon/http/Http.Path.html[`io.helidon.http.Http.Path`] - path (context) this endpoint will be available on

Annotations on endpoint methods:

- link:{webserver-javadoc-base-url}/io/helidon/webserver/http/RestServer.Header.html[`io.helidon.webserver.http.RestServer.Header`] - header to return with each response from this method
- link:{webserver-javadoc-base-url}/io/helidon/webserver/http/RestServer.ComputedHeader.html[`io.helidon.webserver.http.RestServer.ComputedHeader`] - computed header to return with each response from this method
- link:{webserver-javadoc-base-url}/io/helidon/webserver/http/RestServer.Status.html[`io.helidon.webserver.http.RestServer.Status`] - status to return (if a custom one is required)
- link:{http-javadoc-base-url}/io/helidon/http/Http.Path.html[`io.helidon.http.Http.Path`] - path (context) this method will be available on (subpath of the endpoint path)
- link:{http-javadoc-base-url}/io/helidon/http/Http.GET.html[`io.helidon.http.Http.GET`] (and other methods) - definition of HTTP method this method will serve
- link:{http-javadoc-base-url}/io/helidon/http/Http.HttpMethod.html[`io.helidon.http.Http.HttpMethod`] - for custom HTTP method names (mutually exclusive with above)
- link:{http-javadoc-base-url}/io/helidon/http/Http.Produces.html[`io.helidon.http.Http.Produces`] - what media type this method produces (return entity content type)
- link:{http-javadoc-base-url}/io/helidon/http/Http.Consumes.html[`io.helidon.http.Http.Consumes`] - what media type this method accepts (request entity content type)

Annotations on method parameters:

- link:{http-javadoc-base-url}/io/helidon/http/Http.Entity.html[`io.helidon.http.Http.Entity`] - Request entity, a typed parameter is expected, will use HTTP media type modules to coerce into the correct type
- link:{http-javadoc-base-url}/io/helidon/http/Http.HeaderParam.html[`io.helidon.http.Http.HeaderParam`] - Typed HTTP request header value
- link:{http-javadoc-base-url}/io/helidon/http/Http.CookieParam.html[`io.helidon.http.Http.CookieParam`] - Typed HTTP request cookie value
- link:{http-javadoc-base-url}/io/helidon/http/Http.QueryParam.html[`io.helidon.http.Http.QueryParam`] - Typed HTTP query value
- link:{http-javadoc-base-url}/io/helidon/http/Http.FormParam.html[`io.helidon.http.Http.FormParam`] - Typed URL encoded form value from the request entity
- link:{http-javadoc-base-url}/io/helidon/http/Http.PathParam.html[`io.helidon.http.Http.PathParam`] - Typed parameter from path template
- link:{http-javadoc-base-url}/io/helidon/http/Http.RequestParams.html[`io.helidon.http.Http.RequestParams`] - Grouped request parameters in a record type

`Http.FormParam` is backed by the request entity and should be used with
`@Http.Consumes(MediaTypes.APPLICATION_FORM_URLENCODED_VALUE)`. It cannot be combined with `Http.Entity` on the same
declarative method. Each endpoint method parameter may have at most one supported request parameter annotation.

`Http.RequestParams` is supported only for record parameter types. This is a restriction on the parameter types supported
by declarative code generation. Each record component must either be a supported typed parameter that does not require an
annotation, such as `ServerRequest`, or have one of these component annotations: `Http.HeaderParam`, `Http.CookieParam`,
`Http.QueryParam`, `Http.FormParam`, `Http.PathParam`, or `Http.Entity`. Components must not combine supported request
parameter annotations. At most one `Http.Entity` component is supported, and `Http.Entity` cannot be combined with
`Http.FormParam` components.

The named value annotations, such as `Http.HeaderParam`, `Http.CookieParam`, `Http.QueryParam`, `Http.FormParam`, and
`Http.PathParam`, support scalar values, `Optional<T>`, `List<T>`, and `Optional<List<T>>`. For server endpoints,
`List<T>` is mandatory and the request fails if the named value is missing.
`Optional<List<T>>` is optional and is empty when the named value is missing. If the named value is present but has no
values, the injected list is empty. Cookies are an exception: cookies are not represented as `Parameters`, so a named
cookie cannot be present with no values. Cookie parameter names are validated during declarative code generation.
Server path parameters are obtained from the routed request path.

[source,java]
.Example of an HTTP Server Endpoint
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_2, indent=0]
----

[source,java]
.Example of Grouped HTTP Server Parameters
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_19, indent=0]
----

=== Typed HTTP Client [[Dec-HTTP-Client]]

To create a typed HTTP client, create an interface annotated with `RestClient.Endpoint`, and at least one method annotated
with one fo the HTTP method annotations, such as `@Http.GET`. Methods can only have parameters annotated with one of the
`Http` qualifiers.

Annotations on endpoint type:

- link:{webclient-api-javadoc-base-url}/io/helidon/webclient/api/RestClient.Endpoint.html[`io.helidon.webclient.api.RestClient.Endpoint`] - required annotation
- link:{http-javadoc-base-url}/io/helidon/http/Http.Path.html[`io.helidon.http.Http.Path`] - path (context) the server listens on
- link:{webclient-api-javadoc-base-url}/io/helidon/webclient/api/RestClient.Header.html[`io.helidon.webclient.api.RestClient.Header`] - header to include in every request to the server
- link:{webclient-api-javadoc-base-url}/io/helidon/webclient/api/RestClient.ComputedHeader.html[`io.helidon.webclient.api.RestClient.ComputedHeader`] - header to compute and include in every request to the server

Annotations on endpoint methods:

- link:{webclient-api-javadoc-base-url}/io/helidon/webclient/api/RestClient.Header.html[`io.helidon.webclient.api.RestClient.Header`] - header to include in every request to the server
- link:{webclient-api-javadoc-base-url}/io/helidon/webclient/api/RestClient.ComputedHeader.html[`io.helidon.webclient.api.RestClient.ComputedHeader`] - header to compute and include in every request to the server
- link:{http-javadoc-base-url}/io/helidon/http/Http.Path.html[`io.helidon.http.Http.Path`] - path (context) the server serves this endpoint method on
- link:{http-javadoc-base-url}/io/helidon/http/Http.GET.html[`io.helidon.http.Http.GET`] (and other methods) - definition of HTTP method this method will invoke
- link:{http-javadoc-base-url}/io/helidon/http/Http.HttpMethod.html[`io.helidon.http.Http.HttpMethod`] - for custom HTTP method names (mutually exclusive with above)
- link:{http-javadoc-base-url}/io/helidon/http/Http.Produces.html[`io.helidon.http.Http.Produces`] - what media type this method produces (content type of entity from the server)
- link:{http-javadoc-base-url}/io/helidon/http/Http.Consumes.html[`io.helidon.http.Http.Consumes`] - what media type this method accepts (request entity content type)

Annotations on method parameters:

- link:{http-javadoc-base-url}/io/helidon/http/Http.Entity.html[`io.helidon.http.Http.Entity`] - Request entity, a typed parameter is expected, will use HTTP media type modules to write to the request
- link:{http-javadoc-base-url}/io/helidon/http/Http.HeaderParam.html[`io.helidon.http.Http.HeaderParam`] - Typed HTTP header value to send
- link:{http-javadoc-base-url}/io/helidon/http/Http.CookieParam.html[`io.helidon.http.Http.CookieParam`] - Typed HTTP cookie value to send
- link:{http-javadoc-base-url}/io/helidon/http/Http.QueryParam.html[`io.helidon.http.Http.QueryParam`] - Typed HTTP query value to send
- link:{http-javadoc-base-url}/io/helidon/http/Http.FormParam.html[`io.helidon.http.Http.FormParam`] - Typed URL encoded form value to send in the request entity
- link:{http-javadoc-base-url}/io/helidon/http/Http.PathParam.html[`io.helidon.http.Http.PathParam`] - Typed parameter from path template to construct the request URI
- link:{http-javadoc-base-url}/io/helidon/http/Http.RequestParams.html[`io.helidon.http.Http.RequestParams`] - Grouped request parameters in a record type

`Http.FormParam` is backed by the request entity and should be used with
`@Http.Consumes(MediaTypes.APPLICATION_FORM_URLENCODED_VALUE)`. It cannot be combined with `Http.Entity` on the same
declarative method. Each client method parameter may have at most one supported request parameter annotation.

`Http.RequestParams` is supported only for record parameter types. This is a restriction on the parameter types supported
by declarative code generation. Each client record component must use one of these component annotations:
`Http.HeaderParam`, `Http.CookieParam`, `Http.QueryParam`, `Http.FormParam`, `Http.PathParam`, or `Http.Entity`.
Components must not combine supported request parameter annotations. At most one `Http.Entity` component is supported,
and `Http.Entity` cannot be combined with `Http.FormParam` components.

The `Http.HeaderParam`, `Http.CookieParam`, `Http.QueryParam`, and `Http.FormParam` annotations support scalar values,
`Optional<T>`, `List<T>`, and `Optional<List<T>>`. Declarative clients send every value from `List<T>`, and send
`Optional<List<T>>` only when the optional is present.
Declarative client named-value parameters must not be `null`; use `Optional.empty()` to omit optional values. List values
must not contain `null` elements. The same nullability rule applies to named-value components of `Http.RequestParams`
records, and the request-params argument itself must not be `null`.
Cookie parameter names are validated during declarative code generation. Declarative clients send cookie parameters as a
single `Cookie` header and do not escape cookie values; each cookie parameter value must already be a valid cookie-octet
value. Cookies are not represented as `Parameters`, so a named cookie cannot be present with no values. A mandatory
client `List<T>` cookie parameter must contain at least one value.

Declarative clients use `Http.PathParam` values as URI path text when constructing the request URI. They do not encode
each value as a single path segment, so reserved path characters such as `/` keep their WebClient URI meaning. Path
parameter values must not be `null`.

[source,java]
.Example of a Typed HTTP Client
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_3, indent=0]
----

[source,java]
.Example of Grouped HTTP Client Parameters
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_20, indent=0]
----

=== gRPC Server Endpoint [[Dec-GRPC-Server]]

Declarative gRPC server endpoints are service registry services annotated with
`io.helidon.webserver.grpc.RpcServer.Endpoint` and
link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.GrpcService.html[`io.helidon.grpc.api.Grpc.GrpcService`].
The generated binding contributes a `GrpcRouteRegistration` service that registers the endpoint with the gRPC server
feature.

Annotations on endpoint type:

- `io.helidon.webserver.grpc.RpcServer.Endpoint` - required annotation to generate a declarative gRPC server endpoint
- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.GrpcService.html[`io.helidon.grpc.api.Grpc.GrpcService`] - gRPC service name; use the fully-qualified service name when the proto declares a package.
  If not set, the service class simple name is used.
- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.ProtoDescriptor.html[`io.helidon.grpc.api.Grpc.ProtoDescriptor`] - generated protocol buffer class with a static `getDescriptor()` method returning `com.google.protobuf.Descriptors.FileDescriptor`
- `io.helidon.service.registry.Service.Singleton` - normal service registry scope for the endpoint implementation

The endpoint must declare exactly one proto descriptor source: either `@Grpc.ProtoDescriptor` on the type or one
`@Grpc.Proto` method. The method must have no parameters and return
`com.google.protobuf.Descriptors.FileDescriptor`.

Annotations on endpoint methods:

- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.Unary.html[`io.helidon.grpc.api.Grpc.Unary`] - unary gRPC method
- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.ServerStreaming.html[`io.helidon.grpc.api.Grpc.ServerStreaming`] - server-streaming gRPC method
- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.ClientStreaming.html[`io.helidon.grpc.api.Grpc.ClientStreaming`] - client-streaming gRPC method
- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.Bidirectional.html[`io.helidon.grpc.api.Grpc.Bidirectional`] - bidirectional streaming gRPC method

Each endpoint method must declare exactly one gRPC method annotation and must not declare checked exceptions. The Java
annotation type must match the streaming cardinality declared by the proto method.

Supported server method signatures:

- Unary: `Res method(Req)` or `void method(Req, StreamObserver<Res>)`
- Server streaming: `Iterable<Res> method(Req)`, `Stream<Res> method(Req)`, or
  `void method(Req, StreamObserver<Res>)`
- Client streaming: `Res method(Iterable<Req>)` or `Res method(Stream<Req>)`
- Bidirectional streaming: `Iterable<Res> method(Iterable<Req>)`, `Stream<Res> method(Stream<Req>)`, or
  `StreamObserver<Req> method(StreamObserver<Res>)`

Server endpoint methods using an `Iterable<Req>` request-stream shape first collect all inbound messages before invoking
the method. Use `Stream<Req>` or `StreamObserver<Req>` request shapes for non-collecting request processing.

Generated registrations use the fully-qualified gRPC service name, including the proto package when present. Route
registration is enabled by default and can be disabled with `server.features.grpc-route-registration.enabled=false`.
Custom `GrpcRouteRegistration` implementations can return a named socket. If that socket is not configured and
`socketRequired()` returns `false`, the registration falls back to the default socket. Return `true` from
`socketRequired()` to fail startup when the named socket is missing.

Validation annotations on declarative gRPC server methods are enforced by generated entry point interceptors. To map a
`ValidationException` to gRPC `INVALID_ARGUMENT`, add `helidon-webserver-grpc-validation` to the server runtime. The
validation gRPC server service is enabled by default under `grpc.grpc-services.validation`; set
`grpc.grpc-services.validation.enabled=false` to disable the status mapping.

Security annotations on declarative gRPC server methods require the gRPC security module and runtime service. Add
`helidon-webserver-grpc-security`, configure normal Helidon security, and enable the gRPC security service with
`grpc.grpc-services.security.enabled=true`.

=== Typed gRPC Client [[Dec-GRPC-Client]]

To create a typed gRPC client, create an interface annotated with `RpcClient.Endpoint` and `Grpc.GrpcService`, and at
least one method annotated with one of the gRPC method annotations.

Annotations on endpoint type:

- link:{grpc-client-javadoc-base-url}/io/helidon/webclient/grpc/RpcClient.Endpoint.html[`io.helidon.webclient.grpc.RpcClient.Endpoint`] - required annotation
- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.GrpcService.html[`io.helidon.grpc.api.Grpc.GrpcService`] - gRPC service name; use the fully-qualified service name when the proto declares a package
- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.ProtoDescriptor.html[`io.helidon.grpc.api.Grpc.ProtoDescriptor`] - generated protocol buffer class with a static `getDescriptor()` method returning `com.google.protobuf.Descriptors.FileDescriptor`

The endpoint must declare exactly one proto descriptor source: either `@Grpc.ProtoDescriptor` on the type or one
`@Grpc.Proto` static method. The method must have no parameters and return
`com.google.protobuf.Descriptors.FileDescriptor`.

Annotations on endpoint methods:

- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.Unary.html[`io.helidon.grpc.api.Grpc.Unary`] - unary gRPC method
- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.ServerStreaming.html[`io.helidon.grpc.api.Grpc.ServerStreaming`] - server-streaming gRPC method
- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.ClientStreaming.html[`io.helidon.grpc.api.Grpc.ClientStreaming`] - client-streaming gRPC method
- link:{grpc-api-javadoc-base-url}/io/helidon/grpc/api/Grpc.Bidirectional.html[`io.helidon.grpc.api.Grpc.Bidirectional`] - bidirectional streaming gRPC method

Each abstract non-default client method must declare exactly one gRPC method annotation and must not declare checked
exceptions.

Supported client method signatures:

- Unary: `Res method(Req)` or `void method(Req, StreamObserver<Res>)`
- Server streaming: `Iterable<Res> method(Req)`, `Stream<Res> method(Req)`, or
  `void method(Req, StreamObserver<Res>)`
- Client streaming: `Res method(Iterable<Req>)`, `Res method(Stream<Req>)`, or
  `StreamObserver<Req> method(StreamObserver<Res>)`
- Bidirectional streaming: `Iterable<Res> method(Iterable<Req>)`, `Stream<Res> method(Stream<Req>)`, or
  `StreamObserver<Req> method(StreamObserver<Res>)`

To inject a typed gRPC client, use the annotated interface with the `@RpcClient.Client` qualifier.

[source,java]
----
@Service.Inject
MyService(@RpcClient.Client GreetingClient client) {
}
----

The `RpcClient.Endpoint.value()` defines the target URI for generated backing clients and supports configuration
expressions, such as `${grpc.service.uri:http://localhost:8080}`. When declarative code generation creates a new
backing `GrpcClient`, it applies this URI after any client configuration. Registry-provided clients keep their own
base URI.

The base of configuration for a declarative gRPC client is the fully qualified name of the annotated interface. This key
can be modified using the `configKey` property of the `@RpcClient.Endpoint` annotation.

Configuration options under this key:

[cols="1,1,3"]
|===
|Key |Default |Description

|`client`
|none
|Configuration options of Helidon `GrpcClient`. If this node exists, the generated client creates a dedicated
`GrpcClient` instance and does not use a registry-provided client.
|===

Client resolution order:

1. If `<configKey>.client` exists, create a dedicated `GrpcClient` from that configuration and apply
   `RpcClient.Endpoint.value()` as its base URI.
2. Otherwise, if `RpcClient.Endpoint.clientName()` is set and a matching named `GrpcClient` exists in the service
   registry, use that registry client.
3. Otherwise, if `RpcClient.Endpoint.clientName()` is set and no matching named `GrpcClient` exists, create a new
   `GrpcClient` using the endpoint URI from `RpcClient.Endpoint.value()`.
4. Otherwise, if an unnamed `GrpcClient` exists in the service registry, use that registry client.
5. Otherwise, create a new `GrpcClient` using the endpoint URI from `RpcClient.Endpoint.value()`.

=== Fault Tolerance [[Dec-FT]]

Fault tolerance annotations allow adding features to methods on services.
The annotations can be added to any method that supports interception (i.e. methods that are not private).
Method-level fault tolerance annotations can also be declared on methods inherited from service contracts and typed
HTTP client interfaces. Type-level fault tolerance annotations on interfaces are not inherited by service methods.
Contracts provided by registry-managed service factories are not included.

Method Annotations:

- link:{faulttolerance-javadoc-base-url}/io/helidon/faulttolerance/Ft.Retry.html[`io.helidon.faulttolerance.Ft.Retry`] - allow retries
- link:{faulttolerance-javadoc-base-url}/io/helidon/faulttolerance/Ft.Fallback.html[`io.helidon.faulttolerance.Ft.Fallback`] - fallback to another method that provides
- link:{faulttolerance-javadoc-base-url}/io/helidon/faulttolerance/Ft.Async.html[`io.helidon.faulttolerance.Ft.Async`] - invoke method asynchronously
- link:{faulttolerance-javadoc-base-url}/io/helidon/faulttolerance/Ft.Timeout.html[`io.helidon.faulttolerance.Ft.Timeout`] - invoke method with a timeout
- link:{faulttolerance-javadoc-base-url}/io/helidon/faulttolerance/Ft.Bulkhead.html[`io.helidon.faulttolerance.Ft.Bulkhead`] - use bulkhead
- link:{faulttolerance-javadoc-base-url}/io/helidon/faulttolerance/Ft.CircuitBreaker.html[`io.helidon.faulttolerance.Ft.CircuitBreaker`] - use circuit breaker

[source,java]
.Example of Fault Tolerance Fallback
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_4, indent=0]
----

=== Scheduling [[Dec-Scheduling]]

Scheduling allows service methods to be invoked periodically.

Method annotations:

- link:{scheduling-javadoc-base-url}/io/helidon/scheduling/Scheduling.Cron.html[`io.helidon.scheduling.Scheduling.Cron`] - execute with schedule defined by a CRON expression
- link:{scheduling-javadoc-base-url}/io/helidon/scheduling/Scheduling.FixedRate.html[`io.helidon.scheduling.Scheduling.FixedRate`] - execute with a fixed interval

[source,java]
.Example of a fixed rate scheduled method
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_5, indent=0]
----

The following annotation values can use configuration expressions:

- `Scheduling.Cron#value()`
- `Scheduling.Fixed#delayBy()`
- `Scheduling.FixedRate#value()`

Configuration expressions is a reference to a configuration key, with optional default value:

`${config.key:default-value}`


=== Validation [[Dec-Validation]]

Validation provides an ability to validate service method parameters and return types.
This is achieved through constraint annotations and type validation.

To use validation, the proper dependency must be added to your `pom.xml`, and an annotation processor must be configured to
code generate the required classes. The annotation processor is part of the bundle mentioned in Helidon Declarative introduction
above.

Helidon validation module:
[source, xml]
----
<dependency>
    <groupId>io.helidon.validation</groupId>
    <artifactId>helidon-validation</artifactId>
</dependency>
----

For declarative gRPC server endpoints, add the gRPC validation runtime module when validation failures should be returned
as gRPC `INVALID_ARGUMENT` status responses:

[source,xml]
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver-grpc-validation</artifactId>
</dependency>
----

The gRPC validation status mapper is enabled by default under `grpc.grpc-services.validation`; set
`grpc.grpc-services.validation.enabled=false` to disable it.

==== Constraint Annotations

A "Constraint Annotation" is any annotation directly annotated with `io.helidon.validation.Validation.Constraint`.
Helidon Validation provides a set of built-in validation constraints, though custom constraints can be created, or existing constraints can be combined.

Existing constraints:

Constraints for any type:

- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.NotNull.html[`io.helidon.validation.Validation.NotNull`] - must not be null
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Null.html[`io.helidon.validation.Validation.Null`] - must be null

Constraints for `String` and `CharSequence`:

- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.String.Email.html[`io.helidon.validation.Validation.Email`] - matches an e-mail structure (basic check only)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.String.NotBlank.html[`io.helidon.validation.Validation.String.NotBlank`] - must not be blank (empty or only white-space characters)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.String.NotEmpty.html[`io.helidon.validation.Validation.String.NotEmpty`] - must not be empty (i.e. length is `0`)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.String.Length.html[`io.helidon.validation.Validation.String.Length`] - check for maximal (and optionally minimal) length
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.String.Pattern.html[`io.helidon.validation.Validation.String.Pattern`] - check against a regular expression

Constraints for types that extend `java.lang.Number`. These constraints accept any such type, though all types are eventually converted to a `BigDecimal` and the checks are done against the result.
`Byte` is always converted as an unsigned number, i.e. its values are from `0` to `255` inclusive.

- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Number.Negative.html[`io.helidon.validation.Validation.Number.Negative`] - the value must be negative (`< 0`)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Number.NegativeOrZero.html[`io.helidon.validation.Validation.Number.NegativeOrZero`] - the value must be negative or zero (`&lt;= 0`)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Number.Positive.html[`io.helidon.validation.Validation.Number.Positive`] - the value must be positive (`> 0`)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Number.PositiveOrZero.html[`io.helidon.validation.Validation.Number.PositiveOrZero`] - the value must be positive or zero (`>= 0`)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Number.Min.html[`io.helidon.validation.Validation.Number.Min`] - the value must be at least the specified minimal value (`>= min`), value is defined as a `String`
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Number.Max.html[`io.helidon.validation.Validation.Number.Max`] - the value must be at most the specified maximal value (`&lt;= max`), value is defined as a `String`
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Number.Digits.html[`io.helidon.validation.Validation.Number.Digits`] - the number must have at most the specified number of integer and fractional digits
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Number.MultipleOf.html[`io.helidon.validation.Validation.Number.MultipleOf`] - the value must be evenly divisible by the specified positive factor, which is defined as a `String`

Constraints for `Integer` data types. These constraints accept `int, long, byte, char, short` and their boxed counterparts.
`byte` is always converted as an unsigned number, i.e. its values are from `0` to `255` inclusive.
These are convenience annotation that use `int` data type:

- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Integer.Min.html[`io.helidon.validation.Validation.Integer.Min`] - the value must be at least the specified minimal value (`>= min`)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Integer.Max.html[`io.helidon.validation.Validation.Integer.Max`] - the value must be at most the specified maximal value (`&lt;= max`)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Integer.MultipleOf.html[`io.helidon.validation.Validation.Integer.MultipleOf`] - the value must be evenly divisible by the specified positive integer factor

Constraints for `Long` and `long` data types. No other type is supported:

- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Long.Min.html[`io.helidon.validation.Validation.Long.Min`] - the value must be at least the specified minimal value (`>= min`)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Long.Max.html[`io.helidon.validation.Validation.Long.Max`] - the value must be at most the specified maximal value (`&lt;= max`)
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Long.MultipleOf.html[`io.helidon.validation.Validation.Long.MultipleOf`] - the value must be evenly divisible by the specified positive long factor

Constraints for `Boolean` and `boolean` data type. No other type is supported:

- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Boolean.True.html[`io.helidon.validation.Validation.Boolean.True`] - the value must be `true`
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Boolean.False.html[`io.helidon.validation.Validation.Boolean.False`] - the value must be `false`

Constraints for collection and map data types:

- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Collection.Size.html[`io.helidon.validation.Validation.Collection.Size`] - the size of the collection or map must be between the minimal and maximal sizes

Constraints for calendar/time data types. Behavior depends on the specific type - for example for `Year` data type, past is previous year,
future is the next year, and present is the current year, regardless of which month it is. When using `Instant`, past is already the last millisecond.

- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Calendar.Future.html[`io.helidon.validation.Validation.Calendar.Future`] - the value must be in the future
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Calendar.FutureOrPresent.html[`io.helidon.validation.Validation.Calendar.FutureOrPresent`] - the value must be in the future or now
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Calendar.Past.html[`io.helidon.validation.Validation.Calendar.Past`] - the value must be in the past
- link:{validation-javadoc-base-url}/io/helidon/validation/Validation.Calendar.PastOrPresent.html[`io.helidon.validation.Validation.Calendar.PastOrPresent`] - the value must be in the past or now

Supported types for calendar/time validations:

- `java.util.Date`
- `java.util.Calendar`
- `java.time.Instant`
- `java.time.LocalDate`
- `java.time.LocalDateTime`
- `java.time.LocalTime`
- `java.time.MonthDay`
- `java.time.OffsetDateTime`
- `java.time.OffsetTime`
- `java.time.Year`
- `java.time.YearMonth`
- `java.time.ZonedDateTime`
- `java.time.chrono.HijrahDate`
- `java.time.chrono.JapaneseDate`
- `java.time.chrono.MinguoDate`
- `java.time.chrono.ThaiBuddhistDate`


==== Type Validation

A type annotated with `@Validation.Validated` will have validation code generated. Usage of that type can be marked with
`@Validation.Valid` - if such an annotation is present, and it is on a field of another validated type, or it is a parameter,
return type, or a type argument of a parameter/return type of a service method, the object instance will be validated using
a generated interceptor.
Type-use validation is supported on nested `Optional`, `Collection`, `List`, `Set`, `Map` key/value types, array component
types, and wildcard bounds.

==== Usage

[source,java]
.Example of a validated type
----
include::{sourcedir}/se/ValidationSnippets.java[tag=snippet_1, indent=0]
----

[source,java]
.Example of a validated method call using a validated type
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_7, indent=0]
----

Constraint annotations and `@Validation.Valid` can also be declared on non-private instance methods of service interfaces.
They are applied when the service instance is obtained from the service registry.
Constraints declared on matching service interface and implementation methods are combined. Implementation constraints do not
replace or loosen constraints declared by the service interface, even when both methods use the same constraint type with
different values.
Service interfaces are discovered using the service registry contract rules, including `@Service.Contract`,
implicit contracts when enabled, and `@Service.ExternalContracts`.
The same applies to instances returned by registry-managed service factories, including `Supplier`,
`Service.ServicesFactory`, `Service.InjectionPointFactory`, and `Service.QualifiedFactory` services.
This can change runtime behavior for services that already declared interface validation: invalid calls through
registry-obtained services may now fail with a `ValidationException`, while directly constructed objects are not intercepted.

[source,java]
.Example of a validated service contract
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_7b, indent=0]
----

A custom "compound" annotation can be created to simplify usage.

[source,java]
.Example of a compound annotation
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_8, indent=0]
----

A custom constraint annotation can be created (and act as a compound annotation as well).

[source,java]
.Example of a custom constraint annotation
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_9, indent=0]
----

For each constraint annotation, there MUST be a service that validates it.

[source,java]
.Example of constraint validation provider
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_10, indent=0]
----

=== Security [[Dec-Security]]

Security provides protection of WebServer endpoints.

Identity propagation (when using a WebClient) depends on configuration of the client and configuration of security.
We currently do not have a declarative way of modifying client behavior.

Declarative gRPC server security annotations require `helidon-webserver-grpc-security` on the server runtime classpath and
an enabled gRPC security service, for example `grpc.grpc-services.security.enabled=true`, in addition to normal Helidon
security configuration.

Supported annotations:

- `io.helidon.security.annotations.Authenticated` - mark an endpoint or a method as requiring authentication
- `io.helidon.security.annotations.Authorized` - mark an endpoint or a method as requiring authorization;
  `explicit = true` is not supported for declarative gRPC
- `io.helidon.security.annotations.Audited` - mark an endpoint or a method as requiring audit logging
- `io.helidon.security.abac.role.RoleValidator.PermitAll` - annotated method does not require any authentication or authorization (even if endpoint does)
- `jakarta.annotation.security.PermitAll` - same as `RoleValidator.PermitAll`
- `jakarta.annotation.security.DenyAll` - annotated method will not be callable with any kind of authentication or authorization
- link:{security-javadoc-base-url}/io/helidon/security/abac/role/RoleValidator.Roles.html[`io.helidon.security.abac.role.RoleValidator.Roles`] - provide a set of roles that can access a resource, implies authentication is required
- `jakarta.annotation.security.RolesAllowed` - same as above (`RoleValidator.Roles`)

=== Metrics [[Dec-Metrics]]

Add support for the following meters:

- Counter
- Timer
- Gauge

Method annotations:

- link:{metrics-javadoc-base-url}/io/helidon/metrics/api/Metrics.Counted.html[`io.helidon.metrics.api.Metrics.Counted`] - adds a counter metric to the metric registry for method executions
- link:{metrics-javadoc-base-url}/io/helidon/metrics/api/Metrics.Timed.html[`io.helidon.metrics.api.Metrics.Timed`] - adds a timer metric to the metric registry for method executions
- link:{metrics-javadoc-base-url}/io/helidon/metrics/api/Metrics.Gauge.html[`io.helidon.metrics.api.Metrics.Gauge`] - marks a method that returns a number as a gauge

Metrics method annotations can also be declared on methods inherited from service contracts and typed HTTP client interfaces.
Contracts provided by registry-managed service factories are not included.

In addition, we can use link:{metrics-javadoc-base-url}/io/helidon/metrics/api/Metrics.Tag.html[`io.helidon.metrics.api.Metrics.Tag`] annotation on a type, method, or as a `tags` property of an annotation to add tags to the metric. Tags from type definition will be added to all metrics on the type, tags on methods on all metrics on the method, and tags in the metric annotation will only be used by that metric.

The example below shows additional tags. The counter on method `counted` will have the following tags: `service=Metered;method=counted` (and of course the scope tag that is always added).

[source,java]
.Example of a counted method with type tags and counter tags
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_11, indent=0]
----

A gauge is a method that returns a `Number`, and is invoked by the metrics implementation to obtain a value. Example below shows a definition of a `Gauge`. Note that a `unit` is mandatory for gauges.

[source,java]
.Example of a gauge
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_12, indent=0]
----

=== Tracing [[Dec-Tracing]]

Add support for tracing of methods.
This feature will add a new span for each annotated method (or all methods on an annotated type).
Tracing annotations can also be declared on methods inherited from service contracts and typed HTTP client interfaces.
A type-level tracing annotation on a contract interface applies only to methods declared by that contract.
Contracts provided by registry-managed service factories are not included.

Annotations:

- link:{tracing-javadoc}/io/helidon/tracing/Tracing.Traced.html[`io.helidon.tracing.Tracing.Traced`] - all methods on the annotated type are will be traced, or the annotated method will be traced
- link:{tracing-javadoc}/io/helidon/tracing/Tracing.ParamTag.html[`io.helidon.tracing.Tracing.ParamTag`] - the annotated method parameter will be added as a tag to the span


Notes on defaults:

- if a `kind` is defined to other value than `INTERNAL`, it will be used unless a `kind` other than `INTERNAL` is defined on a method annotation (i.e. it is not possible to have `SERVER` on type, and `INTERNAL` on method)
- span name defaults to `fully-qualified-class-name.method-name`

The following example shows annotation on a type. This would make all methods traced with span kind of `SERVER`, and with a tag `service` with value `TracedService`.

[source,java]
.Example of traced type
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_13, indent=0]
----

A traced method with an explicit span name, adding a tag with a constant value, and a tag with a value from annotated parameter. The tag name defaults to parameter name (`userAgent` in this case).

[source,java]
.Annotated traced method
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_14, indent=0]
----

=== WebSocket Server [[Dec-WebSocket-Server]]

To create a WebSocket endpoint, simply annotate a class with `@WebSocketServer.Endpoint`, and
add at least one method annotated with one of the WebSocket method annotations, such as `@WebSocket.OnMessage`.

Services available for injection:

N/A

Supported method parameters (no annotation required):

- link:{websocket-javadoc-base-url}/io/helidon/websocket/WsSession.html[`io.helidon.websocket.WsSession`]
- `boolean` in a method annotated with `@WebSocket.OnMessage` - indicator of "last" message (if not present, the message will be combined before delivery)
- `java.lang.String` (`@WebSocket.OnMessage`) - the message delivered (text)
- `java.io.Reader` (`@WebSocket.OnMessage`) - the message delivered (text)
- link:{buffers-javadoc-base-url}/io/helidon/common/buffers/BufferData.html[`io.helidon.common.buffers.BufferData`] (`@WebSocket.OnMessage`) - the message delivered (binary)
- `java.nio.ByteBuffer` (`@WebSocket.OnMessage`) - the message delivered (binary)
- `java.io.InputStream` (`@WebSocket.OnMessage`) - the message delivered (binary)
- `io.helidon.http.HttpPrologue` (`@WebSocket.OnHttpUpgrade) - the HTTP prologue (method, path, protocol version)
- `io.helidon.http.Headers` (`@WebSocket.OnHttpUpgrade) - the request headers
- `int` (`@WebSocket.OnClose`) - the close code
- `java.lang.String` (`@WebSocket.OnClose`) - the close reason
- `java.lang.Throwable` (`@WebSocket.OnError`) - the throwable thrown


Annotations on endpoint type:

- link:{websocket-server-javadoc-base-url}/io/helidon/webserver/websocket/WebSocketServer.Endpoint.html[`io.helidon.webserver.websocket.WebSocketServer.Endpoint`] - required annotation
- link:{websocket-server-javadoc-base-url}/io/helidon/webserver/websocket/WebSocketServer.Listener.html[`io.helidon.webserver.websocket.WebSocketServer.Listener`] - to define the named listener this should be served on (named port/socket)
- link:{http-javadoc-base-url}/io/helidon/http/Http.Path.html[`io.helidon.http.Http.Path`] - path (context) this endpoint will be available on

Annotations on endpoint methods:

- link:{websocket-javadoc-base-url}/io/helidon/websocket/WebSocket.OnMessage.html[`io.helidon.websocket.WebSocket.OnMessage`] - receives either a binary or a text message
- link:{websocket-javadoc-base-url}/io/helidon/websocket/WebSocket.OnHttpUpgrade.html[`io.helidon.websocket.WebSocket.OnHttpUpgrade`] - invoked during HTTP upgrade, the method may return `Headers` to be sent during the upgrade response
- link:{websocket-javadoc-base-url}/io/helidon/websocket/WebSocket.OnOpen.html[`io.helidon.websocket.WebSocket.OnOpen`] - invoked when the WebSocket connection is established (after upgrade)
- link:{websocket-javadoc-base-url}/io/helidon/websocket/WebSocket.OnClose.html[`io.helidon.websocket.WebSocket.OnClose`] - invoked when the WebSocket connection is closed
- link:{websocket-javadoc-base-url}/io/helidon/websocket/WebSocket.OnError.html[`io.helidon.websocket.WebSocket.OnError`] - invoked when an error occurs when invoking other methods

Annotations on method parameters:

- link:{http-javadoc-base-url}/io/helidon/http/Http.PathParam.html[`io.helidon.http.Http.PathParam`] - Typed parameter from path template

[source,java]
.Example of a WebSocket Server Endpoint
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_15, indent=0]
----

=== WebSocket Client [[Dec-WebSocket-Client]]

To create a WebSocket client endpoint, simply annotate a class with `@WebSocketClient.Endpoint`, and
add at least one method annotated with one of the WebSocket method annotations, such as `@WebSocket.OnMessage`.

Services available for injection:

- a factory for the endpoint (generated), if endpoint is named `EchoEndpoint`, an `EchoEndpointFactory` will be generated with methods to connect to remote server

Supported method parameters (no annotation required):

- link:{websocket-javadoc-base-url}/io/helidon/websocket/WsSession.html[`io.helidon.websocket.WsSession`]
- `boolean` in a method annotated with `@WebSocket.OnMessage` - indicator of "last" message (if not present, the message will be combined before delivery)
- `java.lang.String` (`@WebSocket.OnMessage`) - the message delivered (text)
- `java.io.Reader` (`@WebSocket.OnMessage`) - the message delivered (text)
- link:{buffers-javadoc-base-url}/io/helidon/common/buffers/BufferData.html[`io.helidon.common.buffers.BufferData`] (`@WebSocket.OnMessage`) - the message delivered (binary)
- `java.nio.ByteBuffer` (`@WebSocket.OnMessage`) - the message delivered (binary)
- `java.io.InputStream` (`@WebSocket.OnMessage`) - the message delivered (binary)
- `int` (`@WebSocket.OnClose`) - the close code
- `java.lang.String` (`@WebSocket.OnClose`) - the close reason
- `java.lang.Throwable` (`@WebSocket.OnError`) - the throwable thrown


Annotations on endpoint type:

- link:{websocket-client-javadoc-base-url}/io/helidon/webclient/websocket/WebSocketClient.Endpoint.html[`io.helidon.webclient.websocket.WebSocketClient`] - required annotation
- link:{http-javadoc-base-url}/io/helidon/http/Http.Path.html[`io.helidon.http.Http.Path`] - path (context) this endpoint will be available on

Annotations on endpoint methods:

- link:{websocket-javadoc-base-url}/io/helidon/websocket/WebSocket.OnMessage.html[`io.helidon.websocket.WebSocket.OnMessage`] - receives either a binary or a text message
- link:{websocket-javadoc-base-url}/io/helidon/websocket/WebSocket.OnHttpUpgrade.html[`io.helidon.websocket.WebSocket.OnHttpUpgrade`] - invoked during HTTP upgrade, the method may return `Headers` to be sent during the upgrade response
- link:{websocket-javadoc-base-url}/io/helidon/websocket/WebSocket.OnOpen.html[`io.helidon.websocket.WebSocket.OnOpen`] - invoked when the WebSocket connection is established (after upgrade)
- link:{websocket-javadoc-base-url}/io/helidon/websocket/WebSocket.OnClose.html[`io.helidon.websocket.WebSocket.OnClose`] - invoked when the WebSocket connection is closed
- link:{websocket-javadoc-base-url}/io/helidon/websocket/WebSocket.OnError.html[`io.helidon.websocket.WebSocket.OnError`] - invoked when an error occurs when invoking other methods

Annotations on method parameters:

- link:{http-javadoc-base-url}/io/helidon/http/Http.PathParam.html[`io.helidon.http.Http.PathParam`] - Typed parameter from path template defined by `@Http.Path` on the class

[source,java]
.Example of a WebSocket Client Endpoint
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_16, indent=0]
----

[source,java]
.Example of a component connecting the websocket
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_17, indent=0]
----

=== WebServer CORS [[Dec-CORS]]

CORS can be configured through Helidon Config, the root key is `cors`.

To add an explicit CORS (Cross-origin resource sharing) configuration to an endpoint method, you may annotate it
with one of the annotations in the `Cors` class, such as `@Cors.Defaults`.

Annotations on endpoint method (must be an `OPTIONS` method):

- link:{ws-cors-javadoc}/Cors.Defaults.html[`io.helidon.webserver.cors.Cors.Defaults`] - support all methods, all origins, do not combine with other annotations from `Cors` class
- link:{ws-cors-javadoc}/Cors.AllowOrigins.html[`io.helidon.webserver.cors.Cors.AllowOrigins`] - configure allowed origins, either as a exact string, or regular expression (if the value contains `\`, `*` or `{`, it is considered a regular expression)
- link:{ws-cors-javadoc}/Cors.AllowMethods.html[`io.helidon.webserver.cors.Cors.AllowMethods`] - set of allowed methods that the different origin script can use
- link:{ws-cors-javadoc}/Cors.AllowHeaders.html[`io.helidon.webserver.cors.Cors.AllowHeaders`] - set of allowed headers sent from the different origin script
- link:{ws-cors-javadoc}/Cors.ExposeHeaders.html[`io.helidon.webserver.cors.Cors.ExposeHeaders`] - set of headers from response exposed to the different origin script
- link:{ws-cors-javadoc}/Cors.AllowCredentials.html[`io.helidon.webserver.cors.Cors.AllowCredentials`] - whether to add credentials (such as Cookie) to requests from the different origin script
- link:{ws-cors-javadoc}/Cors.MaxAgeSeconds.html[`io.helidon.webserver.cors.Cors.MaxAgeSeconds`] - maximal number of seconds the pre-flight is considered valid


[source,java]
.Example of a CORS protected endpoint
----
include::{sourcedir}/se/inject/DeclarativeExample.java[tag=snippet_18, indent=0]
----
<1> Configure origins that can be overridden using config key `app.cors.allow-origins` with the provided default values (comma separated)
<2> Configure headers the script can send to this host
<3> Configure allowed methods for CORS requests
<4> Configure max age to be 3 minutes

=== Health Checks [[Dec-Health]]

To add a declarative health check, create a service that implements io.helidon.health.HealthCheck or produces an instance of it.
The WebServer health observer discovers all such services and uses them to contribute to the health response. Because the lookup is performed only once, you must not use the @Service.PerRequest scope. The recommended scope is @Service.Singleton.
