/**
 * OpenAPI Helidon Quickstart
 * This is a sample for Helidon Quickstart project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.Message;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import org.eclipse.microprofile.rest.client.RestClientBuilder;

import java.net.URL;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * OpenAPI Helidon Quickstart Test
 *
 * API tests for MessageApi
 */
public class MessageApiTest {

    private static MessageApi client;
    private static final String baseUrl = "http://localhost:8080";

    @BeforeAll
    public static void setup() throws MalformedURLException {
        client = RestClientBuilder.newBuilder()
                        .baseUrl(new URL(baseUrl))
                        .register(ApiException.class)
                        .build(MessageApi.class);
    }

    
    /**
     * Return a worldly greeting message.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDefaultMessageTest() throws Exception {
        //Message response = client.getDefaultMessage();
        //assertNotNull(response);
    }
    
    /**
     * Return a greeting message using the name that was provided.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessageTest() throws Exception {
        //Message response = client.getMessage(name);
        //assertNotNull(response);
    }
    
    /**
     * Set the greeting to use in future messages.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateGreetingTest() throws Exception {
        //void response = client.updateGreeting(message);
        //assertNotNull(response);
    }
    
}
