/**
 * OpenAPI Helidon Quickstart
 * This is a sample for Helidon Quickstart project.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import java.util.Set;

import jakarta.ws.rs.*;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.MediaType;

import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import org.openapitools.client.model.Message;

/**
 * OpenAPI Helidon Quickstart
 *
 * <p>This is a sample for Helidon Quickstart project.
 */
@RegisterRestClient(baseUri="http://localhost:8080")
@RegisterProvider(ApiExceptionMapper.class)
@Path("/greet")
public interface MessageApi  {

    /**
     * Return a worldly greeting message.
     */
    @GET
    
    @Produces({ "application/json" })
    Message getDefaultMessage() throws ApiException, ProcessingException;

    /**
     * Return a greeting message using the name that was provided.
     */
    @GET
    @Path("/{name}")
    @Produces({ "application/json" })
    Message getMessage(@PathParam("name") String name) throws ApiException, ProcessingException;

    /**
     * Set the greeting to use in future messages.
     */
    @PUT
    @Path("/greeting")
    @Consumes({ "application/json" })
    void updateGreeting(Message message) throws ApiException, ProcessingException;
}
