///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Additional Supported Formats and Sources
:description: Helidon config supported formats and sources
:keywords: helidon, config
:feature-name: Config
:rootdir: {docdir}/../..

include::{rootdir}/includes/se.adoc[]

== Contents

- <<Overview, Overview>>
- <<Additional Config Formats and Parsers, Additional Config Formats and Parsers>>

== Overview
Helidon Config provides several extension modules that support other configuration
formats (parsers) and sources. This document describes how to include them and use them in your project. In each case you need to add module dependencies to your project and, in some cases, write your application accordingly.

== Additional Config Formats and Parsers

=== Automatic Media Type and File Type Handling
With each of the parsers described here, your application can either

1. explicitly add a parser of the correct implementation to the `Config.Builder`, or
2. rely on Java service loading and the config system's matching of file types and
media types to parsers.

If your application creates a `Config.Builder` with parser services _disabled_
(see link:{config-javadoc-base-url}/io/helidon/config/Config.Builder.html#disableParserServices--[`disableParserServices`]
then that builder will not find the Java services for the various parsers and so
will be unable to match the file type or media type of sources with the corresponding
parser automatically. So if you want to use automatic type
matching with a given builder, do not invoke `Config.Builder.disableParserServices()`.

=== YAML [[Config-ModuleYaml]]

==== Maven Coordinates

Add the following dependency in your project:

[source,xml]
.Config YAML Dependency in `pom.xml`
----
<dependency>
    <groupId>io.helidon.config</groupId>
    <artifactId>helidon-config-yaml</artifactId>
</dependency>
----

==== Using the YAML Parser
The YAML parser handles the following media type:

- `application/x-yaml` - YAML format (file type `.yaml`)

[source,java]
.Automatic selection
----
include::{sourcedir}/se/config/SupportedFormatsSnippets.java[tag=snippet_1, indent=0]
----

<1> The config system automatically maps the file type `.yaml` to the media type `application/x-yaml`
which the Helidon YAML parser matches.

[source,java]
.YAML parser specified - no file type on source
----
include::{sourcedir}/se/config/SupportedFormatsSnippets.java[tag=snippet_2, indent=0]
----

<1> The media type of the source `my-config` is unknown, so the config system
cannot choose a parser automatically.
<2> The config system will parse the resource `my-config` on the runtime classpath
using the YAML parser instance created by the
link:{config-javadoc-base-url}.yaml/io/helidon/config/yaml/YamlConfigParser.html[`YamlConfigParser`].
The `create()` method creates a config parser with default behavior.

[source,java]
.Media type specified
----
include::{sourcedir}/se/config/SupportedFormatsSnippets.java[tag=snippet_3, indent=0]
----

<1> The media type of the source `my-config` is unknown, so the config system
cannot choose a parser automatically.
<2> Specifying the media type for the config source allows the config system to
use its matching algorithm with the available parsers to choose a parser for that type.

[source,java]
.YAML parser specified because parser services disabled
----
include::{sourcedir}/se/config/SupportedFormatsSnippets.java[tag=snippet_4, indent=0]
----

<1> Disables automatic parser lookup and registration.
<2> Explicit registration of the YAML parser is therefore required.

=== HOCON/JSON [[Config-ModuleHocon]]
The Helidon HOCON config module handles sources in the
HOCON and JSON formats.

==== Maven Coordinates
Add the following dependency in your project:

[source,xml]
.Config HOCON Dependency in `pom.xml`
----
<dependency>
    <groupId>io.helidon.config</groupId>
    <artifactId>helidon-config-hocon</artifactId>
</dependency>
----

==== Using the HOCON/JSON Parser

The parser handles the following media types:

- `application/hocon` - HOCON format (file type `.conf`)
- `application/json` - JSON format (file type `.json`)

[source,java]
.Automatic selection
----
include::{sourcedir}/se/config/SupportedFormatsSnippets.java[tag=snippet_5, indent=0]
----

<1> The config system automatically maps the file type `.conf` to the media type `application/hocon
which the Helidon HOCON parser matches.

The same module and parser supports file type `.json` and the media type
 `application/json`.

[source,java]
.HOCON parser specified - no file type on source
----
include::{sourcedir}/se/config/SupportedFormatsSnippets.java[tag=snippet_6, indent=0]
----

<1> the media type of the source `my-config` is unknown, so the config system cannot
choose a parser automatically.
<2> The config system will parse the resource `my-config` using the HOCON parser created
by the link:{config-javadoc-base-url}.hocon/io/helidon/config/hocon/HoconConfigParser.html[HoconConfigParser].
The `create()` method creates a config parser with default behavior.

[source,java]
.Media type specified
----
include::{sourcedir}/se/config/SupportedFormatsSnippets.java[tag=snippet_7, indent=0]
----

<1> The media type of the source `my-config` is unknown, so the config system
cannot choose a parser automatically.
<2> Specifying the media type for the config source allows the config system to
use its matching algorithm with the available parsers to choose a parser for that
type.

[source,java]
.HOCON parser specified because parser services disabled
----
include::{sourcedir}/se/config/SupportedFormatsSnippets.java[tag=snippet_8, indent=0]
----

<1> Disables automatic parser lookup and registration.
<2> Explicit registration of the HOCON parser is therefore required.

[source,java]
.Customized HOCON parser
----
include::{sourcedir}/se/config/SupportedFormatsSnippets.java[tag=snippet_9, indent=0]
----

<1> Creates new instance of the parser builder.
<2> Disables resolution of substitutions.
(See the link:https://github.com/lightbend/config/blob/master/HOCON.md#substitutions[HOCON documentation].)
<3> Builds a new instance of the HOCON config parser.

You can also specify
link:https://github.com/lightbend/config/blob/master/config/src/main/java/com/typesafe/config/ConfigResolveOptions.java[`ConfigResolveOptions`]
using the `HoconConfigParser.builder().resolveOptions` method.
