///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= CORS in Helidon SE

:description: Helidon SE CORS Support
:keywords: helidon, java, cors, se, configuration, services
:feature-name: CORS
:cors-config-key-explanation: , identified by a configuration key of your choosing,
:mapped-config-top-key: my-cors
:config-table-methods-column-header: builder method
:!cors-config-table-exclude-keys:
:basic-table-intro: The table below lists the configuration keys that identify the CORS characteristics.
:rootdir: {docdir}/..

include::{rootdir}/includes/se.adoc[]
:ws-cors-javadoc: {webserver-cors-javadoc-base-url}/io/helidon/webserver/cors
:cors-javadoc: {cors-javadoc-base-url}/io/helidon/cors
:ws-cors-artifact: io.helidon.webserver:helidon-webserver-cors

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<API, API>>
- <<Configuration, Configuration>>
- <<Examples, Examples>>
- <<Additional Information, Additional Information>>

== Overview

include::{rootdir}/includes/cors.adoc[tag=cors-intro]
// Still in the Before You Begin section...

==== Choosing How To Implement CORS
You can add CORS support to your application in either or both of the following ways, depending on your specific requirements:

* Use configuration and automatic feature detection: *recommended*.
+
If you add the Helidon CORS Maven artifact to your project, at runtime Helidon automatically discovers it and activates it according to configuration. You do not need to change your Java code. Instead, you control your application's CORS behavior entirely using configuration linked to the resource paths your application exposes.
+
This is the simplest way to set up CORS for your service, and we recommend you use this approach.
* Use the Helidon CORS WebServer Feature to add CORS support programmatically
+
Your code creates an instance of `io.helidon.webserver.cors.CorsFeature` with custom `CorsPathConfig`s, and adds it to the server builder.

The following sections briefly illustrate each approach.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml,subs="attributes+"]
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver-cors</artifactId>
</dependency>
----

== API

=== Using the Config-only Approach
If you add the `{ws-cors-artifact}` Maven artifact to your project you do not have to add any CORS-specific code to your application to implement CORS. Express the CORS behavior you want in configuration, associating path patterns with the CORS settings you want to apply to the matching paths.

See the xref:_configuration[configuration] section below for more information.

=== Adding Code to Include CORS in WebServer

The Helidon SE CORS API provides two key classes that you use in your application:

*  link:{ws-cors-javadoc}/CorsFeature.html[`CorsFeature`] - `WebServer` feature that contains per-path CORS configurations (`CorsPathConfig`) to enforce at runtime; there will be exactly one instance of this class, and it can be configured using a builder

* link:{ws-cors-javadoc}/CorsPathConfig.html[`CorsPathConfig`] - Represents the details for a specific path and  a particular type of sharing, such as which origins are allowed to have access using which HTTP methods, etc.
Create one instance of `CorsPathConfig` for each path you want covered by CORS

The CORS feature works as follows:

- it registers a filter that handles both pre-flight `OPTIONS` requests and regular requests, the ordering is handled through its weight - by default it is always executed before routing and filters registered in routing
- it registers a low weight route for `OPTIONS` method, to ensure we return a non-`404` response for pre-flight requests
- if a pre-flight request comes to the webserver, the filter will check CORS against the configured path configurations, and configure the correct response headers
- if a request comes to the webserver that is not pre-flight, and it is a CORS request, the filter will validate the request can be executed, and adds appropriate headers to the response, OR it terminates the request as forbidden

[[se-api-routing-example]]
=== Sample Routing Setup Using the `CrossOriginConfig` API

The link:{helidon-github-examples-url}/quickstarts/helidon-quickstart-se[Helidon SE Quickstart application]
 lets you change the greeting by sending a `PUT` request to the `/greet/greeting` resource.

This example, based on the QuickStart greeting app, uses the CORS API to influence the xref:{rootdir}/se/webserver/webserver.adoc#routing[routing],
thereby determining how that resource is shared. (If desired, you can use <<Configuration, configuration>> instead
of the low-level API.)

The following code shows one way to prepare your application's routing to support CORS.

[[intro-quick-start-code-example]]
[source,java]
----
include::{sourcedir}/se/CorsSnippets.java[tag=snippet_3, indent=0]
----
<1> Create a builder for `CorsFeature`
<2> Add a `CorsPathConfig` using a builder (can be added multiple times with different configuration), this builder allows configuration of all available CORS options
<3> Configure the path pattern of this CORS config (uses the same pattern as WebServer routing)
<4> Add allow origin
<5> Add allow method
<6> Build the `CorsFeature` instance
<7> Register the new `CorsFeature` instance with WebServer builder

The ordering of `.addPath(...)` methods when configuring the `CorsFeature` is significant, as they are checked in order, and the first `CorsPathConfig` that matches the requested path and method will be used.

If you configure `/greet/*` first, and then `/greet/admin` with the same methods, but different allowed origins (or other options), the `/greet/*` path will be used as it also matches `/greet/admin` and is first.

By adding the few additional lines described above you allow the greeting application to participate in CORS.

[[_configuration]]
== Configuration

You can use configuration instead of or in combination with the Helidon CORS SE API to add CORS support to your resources by
replacing some Java code with declarative configuration.

=== Configuration for Automatic CORS Processing
Recall that simply by adding the `{ws-cors-artifact}` artifact to your project you allow Helidon to automatically use configuration to set up CORS behavior throughout your application.

To use this automatic support, make sure your configuration contains a `cors` section which contains CORS path configuration as described below and as shown in the following example.
[source,yaml,subs="attributes+"]
----
cors:
  paths:
    - "path-pattern": "/greeting"
      "allow-origins": ["https://foo.com", "https://there.com", "https://other.com"]
      "allow-methods": ["PUT", "DELETE"]
    - "path-pattern": "/"
      "allow-methods": ["GET", "HEAD", "OPTIONS", "POST"]
----

include::{rootdir}/includes/cors.adoc[tag=cors-configuration-formats-intro]
include::{rootdir}/includes/cors.adoc[tag=cors-feature-config]


== Examples

For a complete example, see {helidon-github-examples-url}/cors[Helidon SE CORS Example].

== Additional Information

include::{rootdir}/includes/cors.adoc[tag=cors-and-requested-uri-intro]
You can configure how the Helidon server handles these headers as described in the documentation for
xref:{rootdir}/se/webserver/webserver.adoc#_requested_uri_discovery[requested URI discovery].

include::{rootdir}/includes/cors.adoc[tag=cors-and-requested-uri-wrapup]

include::{rootdir}/includes/cors.adoc[tag=configuring-cors-for-builtin-services,leveloffset=+1]
include::{rootdir}/includes/cors.adoc[tag=accessing-shared-resources-intro]

[source,bash]
----
mvn package
java -jar target/helidon-quickstart-se.jar
----

[source, listing]
----
WEB server is up! http://localhost:8080/greet
----

include::{rootdir}/includes/cors.adoc[tag=accessing-shared-resources-main]
