///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2025, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Discovery
:description: Helidon SE Discovery Support
:feature-name: Helidon Discovery
:keywords: helidon, discovery
:rootdir: {docdir}/..

include::{rootdir}/includes/se.adoc[]

== Contents

* <<Overview, Overview>>
* <<Maven Coordinates, Maven Coordinates>>
* <<API Usage, API Usage>>
* <<Providers, Providers>>
* <<Integrations, Integrations>>
** <<Web Client Discovery Integration, Web Client>>
* <<References, References>>

== Overview

In Helidon, _discovery_ is the general process of finding named sets of advertised resources at a moment of an
application's runtime. The advertised resources are often URIs representing microservice endpoints. In some
environments, those endpoints might frequently come and go at unpredictable intervals, as microservices are started,
stopped, and redeployed. The named applications they represent, however, are relatively static. Discovery helps link
such a named application to its transient resources, so that clients can more easily contact it, knowing only its name.

Helidon Discovery is a feature with a vendor- and implementation-independent API backed by vendor-specific
implementations of that API known as _providers_. A developer programs against the Discovery API, and packages a
(normally Helidon-supplied) conformant Discovery implementation (a provider) with her application at deployment
time. See <<Providers,Providers>> below.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
.`pom.xml`
----
<dependencies>
    <dependency>
        <groupId>io.helidon.discovery</groupId>
        <artifactId>helidon-discovery</artifactId> <!--1-->
    </dependency>
</dependencies>
----
<1> Helidon Discovery API dependency.

Discovery is implemented by one or more _<<Providers,discovery providers_>>. Generally you will choose a single provider
and include its relevant dependencies on your runtime classpath as well. See the <<Providers, Providers>> section for
more details.

== API Usage

To use Helidon Discovery, you acquire an
link:{discovery-javadoc-base-url}/io/helidon/discovery/Discovery.html[`io.helidon.discovery.Discovery` object] and call
its
link:{discovery-javadoc-base-url}/io/helidon/discovery/Discovery.html#uris(java.lang.String,java.net.URI)[`uris(String,
URI)` method] to find resources represented as
link:{discovery-javadoc-base-url}/io/helidon/discovery/DiscoveredUri.html[`io.helidon.discovery.DiscoveredUri`
instances].  You supply a _discovery name_, which is the name under which you expect to find advertised resources, and a
_default value_, which is a link:{jdk-javadoc-url}/java.base/java/net/URI.html[`URI`] to use in case the provider does
not supply any resources. In general,
link:{discovery-javadoc-base-url}/io/helidon/discovery/DiscoveredUri.html[`DiscoveredUri`]s you receive are ordered from
more suitable to less suitable, where the definition of _suitable_ is up to the provider. Some providers will consider
aspects like the health or uptime of an advertised resource when returning results. Others may not. Finally, a
link:{discovery-javadoc-base-url}/io/helidon/discovery/DiscoveredUri.html[`DiscoveredUri`] representing the default
value you supply will always be present as the last element in the set of resources you receive.

=== `Discovery` Acquisition

==== `Discovery` Acquisition Using xref:injection/injection.adoc#_injection_points[Helidon Inject]

You can acquire a
link:{discovery-javadoc-base-url}/io/helidon/discovery/Discovery.html[`io.helidon.discovery.Discovery` object] by
xref:injection/injection.adoc#_injection_points[injecting] it into your Helidon SE application:

[source,java]
.Acquiring a `Discovery` object using Helidon Inject
----
include::{sourcedir}/se/DiscoverySnippets.java[tag=snippet_0_imports,indent=0]

include::{sourcedir}/se/DiscoverySnippets.java[tag=snippet_0,indent=0]
----
<1> Use the
    link:{service-registry-base-url}/io/helidon/service/registry/Service.Inject.html[`io.helidon.service.registry.Service.Inject`
    annotation] to indicate that this constructor has an xref:injection/injection.adoc#_injection_points[injection point].
<2> Here, the `discovery` constructor parameter is the injection point and will receive a non-`null`
    link:{discovery-javadoc-base-url}/io/helidon/discovery/Discovery.html[instance of `io.helidon.discovery.Discovery`].
<3> The constructor explicitly assigns the injected reference to the `discovery` instance field.

==== `Discovery` Acquisition Using the Helidon xref:injection/injection.adoc#_programmatic_lookup[Service Registry]

You can acquire a
link:{discovery-javadoc-base-url}/io/helidon/discovery/Discovery.html[`io.helidon.discovery.Discovery` object] by
xref:injection/injection.adoc#_programmatic_lookup[using the Helidon Service Registry] via the
link:{service-registry-base-url}/io/helidon/service/registry/Services.html[`io.helidon.service.registry.Services`
fa&ccedil;ade]:

[source,java]
.Acquiring a `Discovery` object using the Helidon Service Registry
----
include::{sourcedir}/se/DiscoverySnippets.java[tag=snippet_1_imports,indent=0]

include::{sourcedir}/se/DiscoverySnippets.java[tag=snippet_1,indent=0]
----
<1> Use the
    link:{service-registry-base-url}/io/helidon/service/registry/Services.html#get(java.lang.Class)[`io.helidon.service.registry.Services#get(Class)`
    method] to acquire an instance of the
    link:{discovery-javadoc-base-url}/io/helidon/discovery/Discovery.html[`io.helidon.discovery.Discovery` class], and
    assign it to an instance field.

=== Discovering URIs

Discovery uses a _discovery name_ to identify and discover URIs notionally belonging to an application. An application
may have several URIs. The discovery name is the name that identifies the application for discovery purposes.

To discover a named application's URIs, call the
link:{discovery-javadoc-base-url}/io/helidon/discovery/Discovery.html#uris(java.lang.String,java.net.URI)[`Discovery#uris(String,
URI)` method], passing it the discovery name and a `URI` to use as a default value. Both values must be non-`null`. You
will receive an immutable link:{jdk-javadoc-url}/java.base/java/util/SequencedSet.html[`SequencedSet`] of
link:{discovery-javadoc-base-url}/io/helidon/discovery/DiscoveredUri.html[`io.helidon.discovery.DiscoveredUri`
instances] representing the URIs, ordered from the most to the least _suitable_, according to the provider. A
link:{discovery-javadoc-base-url}/io/helidon/discovery/DiscoveredUri.html[`DiscoveredUri`] representing the default
value will appear last in the set:

[source,java]
.Discovering URIs
----
include::{sourcedir}/se/DiscoverySnippets.java[tag=snippet_2_imports,indent=0]

include::{sourcedir}/se/DiscoverySnippets.java[tag=snippet_2,indent=0]
----

<1> URIs that are discovered are represented as a
    link:{jdk-javadoc-url}/java.base/java/util/SequencedSet.html[`SequencedSet`] of
    link:{discovery-javadoc-base-url}/io/helidon/discovery/DiscoveredUri.html[`io.helidon.discovery.DiscoveredUri` instances].
    This is the _discovered set_. In general, the first element in the set is the
    link:{discovery-javadoc-base-url}/io/helidon/discovery/DiscoveredUri.html[discovered URI] that is the most
    _suitable_, as determined by the Discovery provider. (The last element is a
    link:{discovery-javadoc-base-url}/io/helidon/discovery/DiscoveredUri.html[`DiscoveredUri`] whose
    link:{discovery-javadoc-base-url}/io/helidon/discovery/DiscoveredUri.html#uri()[`uri()` method] yields a
    link:{jdk-javadoc-url}/java.base/java/net/URI.html[`URI`] that is identical or equal to the
    link:{jdk-javadoc-url}/java.base/java/net/URI.html[`URI`] that was supplied as the default value.)
<2> `EXAMPLE` is the discovery name for which URIs are being sought.
<3> This link:{jdk-javadoc-url}/java.base/java/net/URI.html[`URI`] is a default value in case the Discovery provider
    finds no URIs, or encounters an error. A
    link:{discovery-javadoc-base-url}/io/helidon/discovery/DiscoveredUri.html[`DiscoveredUri`] representing it will
    appear last in the discovered set.
<4> This link:{jdk-javadoc-url}/java.base/java/net/URI.html[`URI`] is the most suitable one for use, and may or may not
    be equal to the supplied default value.

== Providers

The Discovery API is implemented at runtime by a _Discovery provider_.

To use a Discovery provider, include it on your runtime classpath. See the provider's documentation for details about
installing, configuring, and using the provider.

== Integrations

Helidon integrates a <<Providers,Discovery provider>> with other Helidon modules as described below.

=== Web Client Discovery Integration

Helidon integrates a <<Providers,Discovery provider>> with xref:webclient.adoc[Web Client].

==== Maven Coordinates

To include the Helidon Web Client Discovery integration in your project, add the Web Client Discovery integration
dependency (see xref:{rootdir}/about/managing-dependencies.adoc[Managing Dependencies]). Any Discovery provider you use
must also be present on the runtime classpath.

[source,xml]
.`pom.xml`
----
<dependencies>
    <dependency>
        <groupId>io.helidon.webclient</groupId>
        <artifactId>helidon-webclient-discovery</artifactId>
        <scope>runtime</scope>
    </dependency>
</dependencies>
----

The behavior of the Web Client Discovery integration is
link:{webclient-discovery-javadoc-base-url}/io/helidon/webclient/discovery/WebClientDiscovery.html#handle(io.helidon.webclient.spi.WebClientService.Chain,io.helidon.webclient.api.WebClientServiceRequest)[fully
specified and documented].

==== Configuration

The Helidon Web Client Discovery integration can be configured using xref:config/introduction.adoc[Helidon
Config]. Examples shown below are in YAML, but are expressible in any format and any location that Helidon Config
supports.

Because the Helidon Web Client Discovery integration is fundamentally a
xref:webclient.adoc#_adding_service_to_webclient[Web Client Service], you configure it under a Web Client's `services`
configuration node:

[source,yaml]
.`application.yaml`
----
webclient:
  services:
    discovery: # <1>
----
<1> Indicates that the Web Client Discovery integration should apply to this Web Client configuration. More configuration
    is required; see below.

==== Configuring URIs

To mark URIs requested by a Web Client as subject to discovery, and to use discovery names appropriate for them, you
need to configure _prefix URIs_. URIs that match no prefix will not be subject to discovery:

[source,yaml]
.`application.yaml`
----
webclient:
  services:
    discovery:
      prefix-uris:
        EXAMPLE: "https://example.com:443/" # <1>
        TEST: "https://test.example.com:443/" # <2> <3>
----
<1> Indicates that URIs starting with `https://example.com:443/` will be subject to discovery, using the discovery name
    of `EXAMPLE`
<2> Indicates that URIs starting with `https://test.example.com:443/` will be subject to discovery, using the discovery
    name of `TEST`
<3> URIs that begin with text other than `https://example.com:443/` or `https://test.example.com:443/` will not be
    subject to discovery

== References

* link:{discovery-javadoc-base-url}/module-summary.html[Discovery Javadoc]
* link:{webclient-discovery-javadoc-base-url}/module-summary.html[Web Client Discovery Integration Javadoc]
* xref:webclient.adoc[Helidon Web Client]
