///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= GraphQL Server Introduction
:description: Helidon GraphQL Server Introduction
:keywords: helidon, graphql, java
:feature-name: GraphQL
:rootdir: {docdir}/..

include::{rootdir}/includes/se.adoc[]


== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<API, API>>
- <<Declarative API, Declarative API>>
- <<Configuration, Configuration>>
- <<Examples, Examples>>
- <<Additional Information, Additional Information>>

== Overview

The Helidon GraphQL Server provides a framework for creating link:https://github.com/graphql-java/graphql-java[GraphQL]
applications that integrate with the Helidon WebServer. GraphQL is a query language to access server data.
The Helidon GraphQL integration enables HTTP clients to issue queries over the network and retrieve data;
it is an alternative to other protocols such as REST or GRPC.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
  <groupId>io.helidon.webserver</groupId>
  <artifactId>helidon-webserver-graphql</artifactId>
</dependency>
----

== API

An instance of `GraphQlService` must be registered in the Helidon WebServer routes to enable
GraphQL support in your application. In addition, a GraphQL schema needs to be specified
to verify and execute queries.

The following code fragment creates an instance of `GraphQlService`, disables authentication for
the public example endpoint, and registers it in the Helidon WebServer.

[source,java]
----
include::{sourcedir}/se/GraphQlSnippets.java[tag=snippet_1, indent=0]
----

By default, `GraphQlService` will reserve `/graphql` as the URI path to process queries and
require requests to be authenticated. Set `permitAll` to `true` only for endpoints intended to
be public.
The `buildSchema` method creates the schema and defines 2 types of queries for this
application:

[source,java]
----
include::{sourcedir}/se/GraphQlSnippets.java[tag=snippet_2, indent=0]
----

The following is a description of each of these steps:

<1> Define the GraphQL schema.
<2> Create a `DataFetcher` to return a list of hellos in different languages.
<3> Wire up the `DataFetcher` s.
<4> Generate the GraphQL schema.

== Declarative API

Helidon Declarative can generate the GraphQL schema, GraphQL Java runtime wiring, and WebServer registration from annotated
Service Registry classes. Use declarative GraphQL when the schema should be derived from Java resolver methods and Java schema
types at build time.

Declarative GraphQL applications use the normal declarative application startup described in
xref:injection/declarative.adoc#Overview[Helidon Declarative]. Add the GraphQL modules, WebServer, and Service Registry to
your application:

[source,xml]
----
<dependency>
  <groupId>io.helidon.graphql</groupId>
  <artifactId>helidon-graphql</artifactId>
</dependency>
<dependency>
  <groupId>io.helidon.graphql</groupId>
  <artifactId>helidon-graphql-server</artifactId>
</dependency>
<dependency>
  <groupId>io.helidon.webserver</groupId>
  <artifactId>helidon-webserver</artifactId>
</dependency>
<dependency>
  <groupId>io.helidon.webserver</groupId>
  <artifactId>helidon-webserver-graphql</artifactId>
</dependency>
<dependency>
  <groupId>io.helidon.service</groupId>
  <artifactId>helidon-service-registry</artifactId>
</dependency>
----

Configure the Helidon annotation processors as described in xref:injection/declarative.adoc#Usage[Declarative Usage], then
start the generated application binding:

[source,java]
----
include::{sourcedir}/se/GraphQlSnippets.java[tag=snippet_3, indent=0]
----

Annotate a Service Registry singleton with `@GraphQlServer.Endpoint`. Resolver methods annotated with `@GraphQl.Query` and
`@GraphQl.Mutation` become top-level GraphQL fields. Methods annotated with `@GraphQlServer.Field` become child field
resolvers on generated object types.

[source,java]
----
include::{sourcedir}/se/GraphQlSnippets.java[tag=snippet_4, indent=0]
----

Java classes, records, interfaces, and enums must be annotated with `@GraphQl.Entity` before they contribute SDL object, input,
or enum definitions. Built-in GraphQL scalar types do not need this marker. Use `@GraphQl.Scalar` with a matching
`GraphQlScalar` service for custom scalar Java types.

Declarative resolver parameters can bind:

- GraphQL arguments, using `@GraphQl.Argument` when the Java parameter name should not be used.
- Child resolver source objects, using `@GraphQlServer.Source` when the source parameter cannot be inferred.
- `graphql.schema.DataFetchingEnvironment`.
- Helidon `Context`, GraphQL `ExecutionContext`, and `SecurityContext` propagated from the current request.
- Custom resolver-only parameters through the GraphQL parameter codegen SPI.

By default, generated GraphQL endpoints use `/graphql`, and the generated schema is available under
`/graphql/schema.graphql`. You can override the listener, web context, and schema URI with `@GraphQlServer.Listener`,
`@GraphQlServer.Context`, and `@GraphQlServer.SchemaUri`.

== Configuration

include::{rootdir}/includes/graphql.adoc[]

== Examples

Using the schema defined in Section <<API>>, you can probe the following endpoints:

1. Hello world endpoint
+
[source,bash]
----
curl -X POST http://127.0.0.1:PORT/graphql -d '{"query":"query { hello }"}'

"data":{"hello":"world"}}
----

2. Hello in different languages
+
[source,bash]
----
curl -X POST http://127.0.0.1:PORT/graphql -d '{"query":"query { helloInDifferentLanguages }"}'

{"data":{"helloInDifferentLanguages":["Bonjour","Hola","Zdravstvuyte","Nǐn hǎo","Salve","Gudday","Konnichiwa","Guten Tag"]}}
----

== Additional Information

 * link:{graphql-javadoc-base-url}/module-summary.html[GraphQL Javadocs]
