///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview

:description: Scheduling in Helidon SE
:keywords: helidon, se, scheduling
:h1Prefix: SE
:feature-name: Scheduling
:rootdir: {docdir}/..

include::{rootdir}/includes/se.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
- <<Configuration, Configuration>>
- <<Cron, Cron>>
- <<Fixed rate, Fixed Rate>>
- <<Examples, Examples>>
- <<Reference, Reference>>

== Overview

Scheduling is an essential feature for the Enterprise. Helidon has its own implementation of Scheduling functionality
based on https://github.com/jmrozanec/cron-utils[Cron-utils].

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.scheduling</groupId>
    <artifactId>helidon-scheduling</artifactId>
</dependency>
----

== Usage
For scheduling periodic tasks, it is possible to choose a fixed rate or a Cron expression.

=== Fixed rate

[source,java]
.Scheduling with fixed rate use `Scheduling.fixedRate()` builder.
----
include::{sourcedir}/se/SchedulingSnippets.java[tag=snippet_1, indent=0]
----

Metadata like human-readable interval description or configured values are available through
FixedRateInvocation provided as task parameter.

[source,java]
.Invocation metadata
----
include::{sourcedir}/se/SchedulingSnippets.java[tag=snippet_2, indent=0]
----

include::{rootdir}/config/io_helidon_scheduling_FixedRate.adoc[tag=config,leveloffset=+2]

=== Cron

For more complicated interval definition, Cron expression can be leveraged with
`Scheduling.cron()` builder.

[source,java]
.Scheduling with Cron expression
----
include::{sourcedir}/se/SchedulingSnippets.java[tag=snippet_3, indent=0]
----

include::{rootdir}/config/io_helidon_scheduling_Cron.adoc[tag=config,leveloffset=+2]

=== Cron expression syntax

Cron expressions should be configured as follows.

include::{rootdir}/includes/cron.adoc[lines=19..]

Metadata like human-readable interval description or configured values are available through
CronInvocation provided as task parameter.

== Configuration
Scheduling is configurable with xref:../se/config/introduction.adoc[Helidon Config].

[source,java]
.Example of configuring
----
include::{sourcedir}/se/SchedulingSnippets.java[tag=snippet_4, indent=0]
----


== Examples

=== Fixed rate
For simple fixed rate invocation use .

[source,java]
.Example of scheduling with fixed rate use `Scheduling.fixedRate()` builder.
----
include::{sourcedir}/se/SchedulingSnippets.java[tag=snippet_5, indent=0]
----

Metadata like human-readable interval description or configured values are available through
`FixedRateInvocation` provided as task parameter.


[source,java]
.Example with invocation metadata
----
include::{sourcedir}/se/SchedulingSnippets.java[tag=snippet_6, indent=0]
----

== Reference

* https://github.com/jmrozanec/cron-utils[Cron-utils GitHub page]
* link:{scheduling-javadoc-base-url}/io/helidon/microprofile/scheduling/package-summary.html[Helidon Scheduling JavaDoc]
