///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= WebSocket in Helidon Nima
:toc:
:toc-placement: preamble
:description: WebSocket in Helidon Nima
:keywords: helidon, java, websocket, web, socket, nima
:feature-name: WebSocket
:rootdir: {docdir}/..

include::{rootdir}/includes/nima.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<API, API>>
- <<Examples, Examples>>
- <<Additional Information, Additional Information>>

== Overview

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.nima.websocket</groupId>
    <artifactId>helidon-nima-websocket</artifactId>
</dependency>
----

To enable WebSocket client support add the following dependency:

[source,xml]
----
<dependency>
    <groupId>io.helidon.nima.websocket</groupId>
    <artifactId>helidon-nima-websocket-client</artifactId>
</dependency>
----

== API

Helidon Nima provides a WebSocket API that includes support for both
client and server endpoints. The two APIs share a common interface called `WsListener`
to handle WebSocket events --these connections are _symmetric_ in that both
client and server can send messages, ping each other, etc. The client API
is an alternative to the built-in client in the JDK library.

The `WsListener` interface defines default (empty) methods for each of the
events that occur during the lifetime of a WebSocket connection. These include:
open, close, message, ping, pong

// Server and Client API
// Both share the WsListener interface
// The client API provides an alternative to the native support in the JDK
// WsClient

== Examples

See <<API>> section for examples.

== Additional Information

For additional information, see the
link:{nima-faulttolerance-javadoc-base-url}/module-summary.html[Fault Tolerance Nima API Javadocs].
