///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.faulttolerance.Retry
:keywords: helidon, config, io.helidon.faulttolerance.Retry
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.faulttolerance.Retry
include::{rootdir}/includes/attributes.adoc[]

= Retry (faulttolerance) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.faulttolerance/io/helidon/faulttolerance/Retry.html[io.helidon.faulttolerance.Retry]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cancel-source` |boolean |`true` |Policy to cancel any source stage if the value return by Retry#invoke
 is cancelled. Default is `true`; mostly used by FT MP to change default.
|`name` |string |`Retry-` |A name assigned for debugging, error reporting or configuration purposes.
|`overall-timeout` |Duration |`PT1S` |Overall timeout.
 When overall timeout is reached, execution terminates (even if the retry policy
 was not exhausted).
|`retry-policy` |io.helidon.faulttolerance.Retry.RetryPolicy (service provider interface)

Such as:

 - xref:{rootdir}/config/io_helidon_faulttolerance_Retry_DelayingRetryPolicy.adoc[DelayingRetryPolicy]
 - xref:{rootdir}/config/io_helidon_faulttolerance_Retry_JitterRetryPolicy.adoc[JitterRetryPolicy]

 |{nbsp} |Configure a retry policy to use to calculate delays between retries.
 Defaults to a io.helidon.faulttolerance.Retry.JitterRetryPolicy
 with 4 calls (initial call + 3 retries), delay of 200 millis and a jitter of 50 millis.

|===

// end::config[]