///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.security.providers.idcs.mapper.IdcsRoleMapperProvider
:keywords: helidon, config, io.helidon.security.providers.idcs.mapper.IdcsRoleMapperProvider
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.security.providers.idcs.mapper.IdcsRoleMapperProvider
include::{rootdir}/includes/attributes.adoc[]

= IdcsRoleMapperRxProvider (security.providers.idcs.mapper) Configuration

// tag::config[]

IDCS role mapping provider


Type: link:{javadoc-base-url}/io.helidon.security.providers.idcs.mapper/io/helidon/security/providers/idcs/mapper/IdcsRoleMapperRxProvider.html[io.helidon.security.providers.idcs.mapper.IdcsRoleMapperProvider]


[source,text]
.Config key
----
idcs-role-mapper
----


This type provides the following service implementations:

- `io.helidon.security.spi.SecurityProvider`
- `io.helidon.security.spi.SubjectMappingProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cache-config` |xref:{rootdir}/config/io_helidon_security_providers_common_EvictableCache.adoc[EvictableCache] |{nbsp} |Use explicit io.helidon.security.providers.common.EvictableCache for role caching.
|`default-idcs-subject-type` |string |`user` |Configure subject type to use when requesting roles from IDCS.
 Can be either #IDCS_SUBJECT_TYPE_USER or #IDCS_SUBJECT_TYPE_CLIENT.
 Defaults to #IDCS_SUBJECT_TYPE_USER.
|`oidc-config` |xref:{rootdir}/config/io_helidon_security_providers_oidc_common_OidcConfig.adoc[OidcConfig] |{nbsp} |Use explicit io.helidon.security.providers.oidc.common.OidcConfig instance, e.g. when using it also for OIDC
 provider.
|`subject-types` |SubjectType[&#93; (USER, SERVICE) |`USER` |Add a supported subject type.
 If none added, io.helidon.security.SubjectType#USER is used.
 If any added, only the ones added will be used (e.g. if you want to use
 both io.helidon.security.SubjectType#USER and io.helidon.security.SubjectType#SERVICE,
 both need to be added.

|===

// end::config[]