///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.observe.log.LogStreamConfig
:keywords: helidon, config, io.helidon.webserver.observe.log.LogStreamConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.observe.log.LogStreamConfig
include::{rootdir}/includes/attributes.adoc[]

= LogStreamConfig (webserver.observe.log) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.observe.log/io/helidon/webserver/observe/log/LogStreamConfig.html[io.helidon.webserver.observe.log.LogStreamConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`content-type` |HttpMediaType |`@io.helidon.http.HttpMediaTypes@.PLAINTEXT_UTF_8` |
|`enabled` |boolean |`true` |Whether stream is enabled.

 @return whether to allow streaming of log statements
|`idle-message-timeout` |Duration |`PT5S` |How long to wait before we send the idle message, to make sure we keep the stream alive.

 @return if no messages appear within this duration, and idle message will be sent
 @see #idleString()
|`idle-string` |string |`%
` |String sent when there are no log messages within the #idleMessageTimeout().

 @return string to write over the network when no log messages are received
|`queue-size` |int |`100` |Length of the in-memory queue that buffers log messages from loggers before sending them over the network.
 If the messages are produced faster than we can send them to client, excess messages are DISCARDED, and will not
 be sent.

 @return size of the in-memory queue for log messages

|===

// end::config[]