///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.media.common.MediaContext
:keywords: helidon, config, io.helidon.media.common.MediaContext
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.media.common.MediaContext
include::{rootdir}/includes/attributes.adoc[]

= MediaContext (media.common) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.media.common/io/helidon/media/common/MediaContext.html[io.helidon.media.common.MediaContext]




== Configuration options

.Required configuration options
[cols="3,3a,2,5a"]
|===
|key |type |default value |description

|`services` |io.helidon.media.common.spi.MediaSupportProvider[&#93; (service provider interface) |{nbsp} |Configures this Builder from the supplied Config.
 <table class="config">
 <caption>Optional configuration parameters</caption>
 <tr>
     <th>key</th>
     <th>description</th>
 </tr>
 <tr>
     <td>register-defaults</td>
     <td>Whether to register default reader and writers</td>
 </tr>
 <tr>
     <td>discover-services</td>
     <td>Whether to discover services via service loader</td>
 </tr>
 <tr>
     <td>filter-services</td>
     <td>Whether to filter discovered services by service names in services section</td>
 </tr>
 <tr>
     <td>services</td>
     <td>Configuration section for each service. Each entry has to have "name" parameter.
     It is also used for filtering of loaded services.</td>
 </tr>
 </table>

|===



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`discover-services` |boolean |`false` |Whether Java Service Loader should be used to load MediaSupportProvider.
|`filter-services` |boolean |`false` |Whether services loaded by Java Service Loader should be filtered.
 All of the services which should pass the filter, have to be present under `services` section of configuration.
|`register-defaults` |boolean |`true` |Whether default readers and writers should be registered.

|===

// end::config[]