///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webclient.api.HttpConfigBase
:keywords: helidon, config, io.helidon.webclient.api.HttpConfigBase
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webclient.api.HttpConfigBase
include::{rootdir}/includes/attributes.adoc[]

= HttpConfigBase (webclient.api) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webclient.api/io/helidon/webclient/api/HttpConfigBase.html[io.helidon.webclient.api.HttpConfigBase]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`connect-timeout` |Duration |{nbsp} |Connect timeout.

 @return connect timeout
 @see io.helidon.common.socket.SocketOptions#connectTimeout()
|`follow-redirects` |boolean |`true` |Whether to follow redirects.

 @return whether to follow redirects
|`keep-alive` |boolean |`true` |Determines if connection keep alive is enabled (NOT socket keep alive, but HTTP connection keep alive, to re-use
 the same connection for multiple requests).

 @return keep alive for this connection
 @see io.helidon.common.socket.SocketOptions#socketKeepAlive()
|`max-redirects` |int |`10` |Max number of followed redirects.
 This is ignored if #followRedirects() option is `false`.

 @return max number of followed redirects
|`properties` |Map&lt;string, string&gt; |{nbsp} |Properties configured for this client. These properties are propagated through client request, to be used by
 services (and possibly for other purposes).

 @return map of client properties
|`proxy` |xref:{rootdir}/config/io_helidon_webclient_api_Proxy.adoc[Proxy] |{nbsp} |Proxy configuration to be used for requests.

 @return proxy to use, defaults to Proxy#noProxy()
|`read-timeout` |Duration |{nbsp} |Read timeout.

 @return read timeout
 @see io.helidon.common.socket.SocketOptions#readTimeout()
|`tls` |xref:{rootdir}/config/io_helidon_common_tls_Tls.adoc[Tls] |{nbsp} |TLS configuration for any TLS request from this client.
 TLS can also be configured per request.
 TLS is used when the protocol is set to `https`.

 @return TLS configuration to use

|===

// end::config[]