///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.microprofile.server.Server
:keywords: helidon, config, io.helidon.microprofile.server.Server
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.microprofile.server.Server
include::{rootdir}/includes/attributes.adoc[]

= Server (microprofile.server) Configuration

// tag::config[]

Configuration of Helidon Microprofile Server


Type: link:{javadoc-base-url}/io.helidon.microprofile.server/io/helidon/microprofile/server/Server.html[io.helidon.microprofile.server.Server]


This is a standalone configuration type, prefix from configuration root: `server`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`host` |string |{nbsp} |Configure listen host.
|`port` |int |{nbsp} |Configure listen port.

|===

// end::config[]