///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.openapi.OpenApiUi
:keywords: helidon, config, io.helidon.openapi.OpenApiUi
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.openapi.OpenApiUi
include::{rootdir}/includes/attributes.adoc[]

= OpenApiUi (openapi) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.openapi/io/helidon/openapi/OpenApiUi.html[io.helidon.openapi.OpenApiUi]


[source,text]
.Config key
----
ui
----



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`enabled` |boolean |`true` |Sets whether the UI should be enabled.
|`options` |Map&lt;string, string&gt; |{nbsp} |Sets implementation-specific UI options.
|`web-context` |string |{nbsp} |web context (path) where the UI will respond

|===

// end::config[]