///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.reactive.webserver.SocketConfiguration
:keywords: helidon, config, io.helidon.reactive.webserver.SocketConfiguration
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.reactive.webserver.SocketConfiguration
include::{rootdir}/includes/attributes.adoc[]

= SocketConfiguration (reactive.webserver) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.reactive.webserver/io/helidon/reactive/webserver/SocketConfiguration.html[io.helidon.reactive.webserver.SocketConfiguration]




== Configuration options

.Required configuration options
[cols="3,3a,2,5a"]
|===
|key |type |default value |description

|`name` |string |{nbsp} |Configure a socket name, to bind named routings to.

|===



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`backlog` |int |`1024` |Configures a maximum length of the queue of incoming connections on the server
 socket.

 Default value is #DEFAULT_BACKLOG_SIZE.
|`backpressure-buffer-size` |long |{nbsp} |Maximum length of the response data sending buffer can keep without flushing.
 Depends on `backpressure-policy` what happens if max buffer size is reached.
|`backpressure-strategy` |BackpressureStrategy (LINEAR, AUTO_FLUSH, PREFETCH, UNBOUNDED) |`LINEAR` |Sets a backpressure strategy for the server to apply against user provided response upstream.

- LINEAR - Data are requested one-by-one, in case buffer reaches watermark, no other data is requested.
- AUTO_FLUSH - Data are requested one-by-one, in case buffer reaches watermark, no other data is requested.
- PREFETCH - After first data chunk arrives, probable number of chunks needed to fill the buffer up to watermark is calculated and requested.
- NONE - No backpressure is applied, Long.MAX_VALUE(unbounded) is requested from upstream.


|[.line-through]#`bind-address`# |string |{nbsp} |*Deprecated* Configures local address where the server listens on with the server socket.
 If not configured, then listens an all local addresses.
|`continue-immediately` |boolean |`false` |When true WebServer answers to expect continue with 100 continue immediately,
 not waiting for user to actually request the data.

 Default is `false`
|`enable-compression` |boolean |`false` |Enable negotiation for gzip/deflate content encodings. Clients can
 request compression using the "Accept-Encoding" header.

 Default is `false`
|`host` |string |{nbsp} |A helper method that just calls #bindAddress(String).
|`max-header-size` |int |`16384` |Maximal number of bytes of all header values combined. When a bigger value is received, a
 io.helidon.common.http.Http.Status#BAD_REQUEST_400
 is returned.

 Default is `16384`
|`max-initial-line-length` |int |`4096` |Maximal number of characters in the initial HTTP line.

 Default is `4096`
|`max-payload-size` |long |{nbsp} |Set a maximum payload size for a client request. Can prevent DoS
 attacks.
|`max-upgrade-content-length` |int |`65536` |Set a maximum length of the content of an upgrade request.

 Default is `64*1024`
|`port` |int |`0` |Configures a server port to listen on with the server socket. If port is
 `0` then any available ephemeral port will be used.
|`receive-buffer-size` |int |{nbsp} |Configures proposed value of the TCP receive window that is advertised to the remote peer on the
 server socket.

 If `0` then use implementation default.
|`timeout-millis` |long |`0` |Socket timeout in milliseconds
|`tls` |xref:{rootdir}/config/io_helidon_reactive_webserver_WebServerTls.adoc[WebServerTls] |{nbsp} |Configures SSL for this socket. When configured, the server enforces SSL
 configuration.
 If this method is called, any other method except for #tls(java.util.function.Supplier)¨
 and repeated invocation of this method would be ignored.

 If this method is called again, the previous configuration would be ignored.

|===

// end::config[]