///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.WebServer
:keywords: helidon, config, io.helidon.webserver.WebServer
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.WebServer
include::{rootdir}/includes/attributes.adoc[]

= WebServer (webserver) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver/io/helidon/webserver/WebServer.html[io.helidon.webserver.WebServer]


This is a standalone configuration type, prefix from configuration root: `server`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`features` |io.helidon.webserver.spi.ServerFeature[&#93; (service provider interface)

Such as:

 - xref:{rootdir}/config/io_helidon_webserver_observe_ObserveFeature.adoc[ObserveFeature]
 - xref:{rootdir}/config/io_helidon_webserver_context_ContextFeature.adoc[ContextFeature]
 - xref:{rootdir}/config/io_helidon_webserver_cors_CorsFeature.adoc[CorsFeature]
 - xref:{rootdir}/config/io_helidon_webserver_security_SecurityFeature.adoc[SecurityFeature]
 - xref:{rootdir}/config/io_helidon_webserver_accesslog_AccessLogFeature.adoc[AccessLogFeature]

 |{nbsp} |Server features allow customization of the server, listeners, or routings.

 @return server features
|`shutdown-hook` |boolean |`true` |When true the webserver registers a shutdown hook with the JVM Runtime.

 Defaults to true. Set this to false such that a shutdown hook is not registered.

 @return whether to register a shutdown hook
|`sockets` |xref:{rootdir}/config/io_helidon_webserver_ListenerConfig.adoc[Map&lt;string, ListenerConfig&gt;] |{nbsp} |Socket configurations.
 Note that socket named `WebServer#DEFAULT_SOCKET_NAME` cannot be used,
 configure the values on the server directly.

 @return map of listener configurations, except for the default one

|===

// end::config[]