///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.common.configurable.LruCache
:keywords: helidon, config, io.helidon.common.configurable.LruCache
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.common.configurable.LruCache
include::{rootdir}/includes/attributes.adoc[]

= LruCache (common.configurable) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.common.configurable/io/helidon/common/configurable/LruCache.html[io.helidon.common.configurable.LruCache]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`capacity` |int |`10000` |Configure capacity of the cache. Defaults to `LruCache#DEFAULT_CAPACITY`.

 @return maximal number of records in the cache before the oldest one is removed

|===

// end::config[]