///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.common.configurable.ScheduledThreadPoolSupplier
:keywords: helidon, config, io.helidon.common.configurable.ScheduledThreadPoolSupplier
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.common.configurable.ScheduledThreadPoolSupplier
include::{rootdir}/includes/attributes.adoc[]

= ScheduledThreadPoolSupplier (common.configurable) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.common.configurable/io/helidon/common/configurable/ScheduledThreadPoolSupplier.html[io.helidon.common.configurable.ScheduledThreadPoolSupplier]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`core-pool-size` |int |`16` |Core pool size of the thread pool executor.
 Defaults to `DEFAULT_CORE_POOL_SIZE`.

 @return corePoolSize see java.util.concurrent.ThreadPoolExecutor#getCorePoolSize()
|`is-daemon` |boolean |`true` |Is daemon of the thread pool executor.
 Defaults to `DEFAULT_IS_DAEMON`.

 @return whether the threads are daemon threads
|`prestart` |boolean |`false` |Whether to prestart core threads in this thread pool executor.
 Defaults to `DEFAULT_PRESTART`.

 @return whether to prestart the threads
|`thread-name-prefix` |string |`helidon-` |Name prefix for threads in this thread pool executor.
 Defaults to `DEFAULT_THREAD_NAME_PREFIX`.

 @return prefix of a thread name
|`virtual-threads` |boolean |{nbsp} |When configured to `true`, an unbounded virtual executor service (project Loom) will be used.

 If enabled, all other configuration options of this executor service are ignored!

 @return whether to use virtual threads or not, defaults to `false`

|===

// end::config[]