///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.faulttolerance.Retry.JitterRetryPolicy
:keywords: helidon, config, io.helidon.faulttolerance.Retry.JitterRetryPolicy
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.faulttolerance.Retry.JitterRetryPolicy
include::{rootdir}/includes/attributes.adoc[]

= JitterRetryPolicy (faulttolerance.Retry) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.faulttolerance.Retry/io/helidon/faulttolerance/Retry/JitterRetryPolicy.html[io.helidon.faulttolerance.Retry.JitterRetryPolicy]



This type provides the following service implementations:

- `io.helidon.faulttolerance.Retry.RetryPolicy`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`calls` |int |`3` |Total number of calls (first + retries).
|`delay` |Duration |`PT0.2S` |Base delay between the invocations.
|`jitter` |Duration |`PT0.05S` |Random part of the delay.
 A number between `[-jitter,+jitter]` is applied to delay each time
 delay is calculated.

|===

// end::config[]