///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.faulttolerance.CircuitBreaker
:keywords: helidon, config, io.helidon.faulttolerance.CircuitBreaker
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.faulttolerance.CircuitBreaker
include::{rootdir}/includes/attributes.adoc[]

= CircuitBreaker (faulttolerance) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.faulttolerance/io/helidon/faulttolerance/CircuitBreaker.html[io.helidon.faulttolerance.CircuitBreaker]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cancel-source` |boolean |`true` |Policy to cancel any source stage if the value return by CircuitBreaker#invoke
 is cancelled. Default is `true`; mostly used by FT MP to change default.
|`delay` |Duration |`PT5S` |How long to wait before transitioning from open to half-open state.
|`error-ratio` |int |`60` |How many failures out of 100 will trigger the circuit to open.
 This is adapted to the #volume(int) used to handle the window of requests.
If errorRatio is 40, and volume is 10, 4 failed requests will open the circuit.
|`name` |string |`CircuitBreaker-` |A name assigned for debugging, error reporting or configuration purposes.
|`success-threshold` |int |`1` |How many successful calls will close a half-open circuit.
 Nevertheless the first failed call will open the circuit again.
|`volume` |int |`10` |Rolling window size used to calculate ratio of failed requests.

|===

// end::config[]