///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.security.SecurityFeature
:keywords: helidon, config, io.helidon.webserver.security.SecurityFeature
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.security.SecurityFeature
include::{rootdir}/includes/attributes.adoc[]

= SecurityFeature (webserver.security) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.security/io/helidon/webserver/security/SecurityFeature.html[io.helidon.webserver.security.SecurityFeature]


[source,text]
.Config key
----
security
----


This type provides the following service implementations:

- `io.helidon.webserver.spi.ServerFeatureProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`defaults` |xref:{rootdir}/config/io_helidon_webserver_security_SecurityHandler.adoc[SecurityHandler] |`SecurityHandler.create()` |The default security handler.

 @return security handler defaults
|`paths` |xref:{rootdir}/config/io_helidon_webserver_security_PathsConfig.adoc[PathsConfig[&#93;] |{nbsp} |Configuration for webserver paths.

 @return path configuration
|`security` |xref:{rootdir}/config/io_helidon_security_Security.adoc[Security] |{nbsp} |Security associated with this feature.
 If not specified here, the feature uses security registered with
 io.helidon.common.context.Contexts#globalContext(), if not found, it creates a new
 instance from root of configuration (using `security` key).

 This configuration allows usage of a different security instance for a specific security feature setup.

 @return security instance to be used to handle security in this feature configuration
|`weight` |double |`800.0` |Weight of the security feature. Value is:
 `io.helidon.webserver.security.SecurityFeature#WEIGHT`.

 @return weight of the feature

|===

// end::config[]