///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.WebServer
:keywords: helidon, config, io.helidon.webserver.WebServer
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.WebServer
include::{rootdir}/includes/attributes.adoc[]

= WebServer (webserver) Configuration

// tag::config[]

Configuration of the HTTP server.


Type: link:{javadoc-base-url}/io.helidon.webserver/io/helidon/webserver/WebServer.html[io.helidon.webserver.WebServer]


This is a standalone configuration type, prefix from configuration root: `server`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`backlog` |int |`1024` |Configures a maximum length of the queue of incoming connections on the server
 socket.

 Default value is #DEFAULT_BACKLOG_SIZE.
|[.line-through]#`bind-address`# |string |{nbsp} |*Deprecated* Configures local address where the server listens on with the server socket.
 If not configured, then listens an all local addresses.
|`enable-compression` |boolean |`false` |Enable negotiation for gzip/deflate content encodings. Clients can
 request compression using the "Accept-Encoding" header.

 Default is `false`
|`features.print-details` |boolean |`false` |Set to `true` to print detailed feature information on startup.
|`host` |string |{nbsp} |A helper method that just calls #bindAddress(String).
|`max-header-size` |int |`16384` |Maximal number of bytes of all header values combined. When a bigger value is received, a
 io.helidon.common.http.Http.Status#BAD_REQUEST_400
 is returned.

 Default is `8192`
|`max-initial-line-length` |int |`4096` |Maximal number of characters in the initial HTTP line.

 Default is `4096`
|`max-payload-size` |long |{nbsp} |Set a maximum payload size for a client request. Can prevent DoS
 attacks.
|`max-upgrade-content-length` |int |`65536` |Set a maximum length of the content of an upgrade request.

 Default is `64*1024`
|`backpressure-buffer-size` |long |`5242880` |Set a maximum length of the unflushed response data sending buffer can keep without applying backpressure.
Depends on `backpressure-policy` what happens if max buffer size is reached.

 Default is `5*1024*1024` - 5Mb
|`backpressure-policy` | String | `LINEAR` |Sets the strategy for applying backpressure to the reactive stream
of response data.

* LINEAR - Data chunks are requested one-by-one after previous data chunk has been written to Netty's buffer, when
`backpressure-buffer-size` watermark is reached, new chunks are not requested until buffer size decrease under
the watermark value.
* PREFETCH - After first data chunk arrives, expected number of chunks needed to fill the buffer up
to watermark is calculated and requested.
* AUTO_FLUSH - Data are requested one-by-one, in case buffer reaches watermark, no other data is requested and extra flush is initiated.
* UNBOUNDED - No backpressure is applied, Long.MAX_VALUE(unbounded) is requested from upstream.

 Default is `LINEAR`
|`port` |int |`0` |Configures a server port to listen on with the server socket. If port is
 `0` then any available ephemeral port will be used.
|`receive-buffer-size` |int |{nbsp} |Configures proposed value of the TCP receive window that is advertised to the remote peer on the
 server socket.

 If `0` then use implementation default.
|`sockets` |xref:{rootdir}/config/io_helidon_webserver_SocketConfiguration.adoc[SocketConfiguration[&#93;] |{nbsp} |Adds an additional named server socket configuration. As a result, the server will listen
 on multiple ports.

 An additional named server socket may have a dedicated Routing configured
 through io.helidon.webserver.WebServer.Builder#addNamedRouting(String, Routing).
|`timeout-millis` |long |`0` |Socket timeout in milliseconds
|`tls` |xref:{rootdir}/config/io_helidon_webserver_WebServerTls.adoc[WebServerTls] |{nbsp} |Configures SSL for this socket. When configured, the server enforces SSL
 configuration.
 If this method is called, any other method except for #tls(java.util.function.Supplier)¨
 and repeated invocation of this method would be ignored.

 If this method is called again, the previous configuration would be ignored.
|`worker-count` |int |{nbsp} |Sets a count of threads in pool used to process HTTP requests.
 Default value is `CPU_COUNT * 2`.

 Configuration key: `workers`

|===

// end::config[]