///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.faulttolerance.Retry.DelayingRetryPolicy
:keywords: helidon, config, io.helidon.faulttolerance.Retry.DelayingRetryPolicy
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.faulttolerance.Retry.DelayingRetryPolicy
include::{rootdir}/includes/attributes.adoc[]

= DelayingRetryPolicy (faulttolerance.Retry) Configuration

// tag::config[]

A retry policy that prolongs the delays between retries by a defined factor.


Type: link:{javadoc-base-url}/io.helidon.faulttolerance.Retry/io/helidon/faulttolerance/Retry/DelayingRetryPolicy.html[io.helidon.faulttolerance.Retry.DelayingRetryPolicy]



This type provides the following service implementations:

- `io.helidon.faulttolerance.Retry.RetryPolicy`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`calls` |int |`3` |Total number of calls (first + retries).
|`delay` |Duration |`PT0.2S` |Base delay between the invocations.
|`delay-factor` |double |`2` |A delay multiplication factor.

|===

// end::config[]