///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.observe.health.HealthFeature
:keywords: helidon, config, io.helidon.webserver.observe.health.HealthFeature
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.observe.health.HealthFeature
include::{rootdir}/includes/attributes.adoc[]

= HealthFeature (webserver.observe.health) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver.observe.health/io/helidon/webserver/observe/health/HealthFeature.html[io.helidon.webserver.observe.health.HealthFeature]


This is a standalone configuration type, prefix from configuration root: `health`



== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`cross-origin-config` |xref:{rootdir}/config/io_helidon_cors_CrossOriginConfig.adoc[CrossOriginConfig] |{nbsp} |Set the CORS config from the specified `CrossOriginConfig` object.
|`details` |boolean |`false` |Whether details should be printed.
 By default, health only returns a io.helidon.http.Status#NO_CONTENT_204 for success,
 io.helidon.http.Status#SERVICE_UNAVAILABLE_503 for health down,
 and io.helidon.http.Status#INTERNAL_SERVER_ERROR_500 in case of error with no entity.
 When details are enabled, health returns io.helidon.http.Status#OK_200 for success, same codes
 otherwise
 and a JSON entity with detailed information about each health check executed.
|`enabled` |boolean |`true` |Whether "observe health" should be enabled.
|`web-context` |string |{nbsp} |Set the root context for the REST API of the service.

|===

// end::config[]