///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.grpc.client.GrpcChannelDescriptor
:keywords: helidon, config, io.helidon.grpc.client.GrpcChannelDescriptor
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.grpc.client.GrpcChannelDescriptor
include::{rootdir}/includes/attributes.adoc[]

= GrpcChannelDescriptor (grpc.client) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.grpc.client/io/helidon/grpc/client/GrpcChannelDescriptor.html[io.helidon.grpc.client.GrpcChannelDescriptor]




== Configuration Options



.Optional Configuration Options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`host` |string |`localhost` |Set the host name to connect.
|`port` |int |`1408` |Set the port that will be used to connect to the server.
|`target` |string |{nbsp} |Set the target string, which can be either a valid io.grpc.NameResolver
 compliant URI, or an authority string.
|`tls` |xref:{rootdir}/config/io_helidon_grpc_core_GrpcTlsDescriptor.adoc[GrpcTlsDescriptor] |{nbsp} |Set the GrpcTlsDescriptor. If `tlsDescriptor` is null or if the `tlsDescriptor.isEnabled()` is false,
 then no TLS will be used.

|===

// end::config[]