///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.common.configurable.AllowList
:keywords: helidon, config, io.helidon.common.configurable.AllowList
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.common.configurable.AllowList
include::{rootdir}/includes/attributes.adoc[]

= AllowList (common.configurable) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.common.configurable/io/helidon/common/configurable/AllowList.html[io.helidon.common.configurable.AllowList]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`allow.all` |boolean |`false` |Allows all strings to match (subject to "deny" conditions). An `allow.all` setting of `false` does
 not deny all strings but rather represents the absence of a universal match, meaning that other allow and deny settings
 determine the matching outcomes.

 @return whether to allow all strings to match (subject to "deny" conditions)
|`allow.exact` |string[&#93; |{nbsp} |Exact strings to allow.

 @return exact strings to allow
|`allow.pattern` |Pattern[&#93; |{nbsp} |Patterns specifying strings to allow.

 @return patterns which allow matching
|`allow.prefix` |string[&#93; |{nbsp} |Prefixes specifying strings to allow.

 @return prefixes which allow matching
|`allow.suffix` |string[&#93; |{nbsp} |Suffixes specifying strings to allow.

 @return suffixes which allow matching
|`deny.exact` |string[&#93; |{nbsp} |Exact strings to deny.

 @return exact strings to allow
|`deny.pattern` |Pattern[&#93; |{nbsp} |Patterns specifying strings to deny.

 @return patterns which deny matching
|`deny.prefix` |string[&#93; |{nbsp} |Prefixes specifying strings to deny.

 @return prefixes which deny matching
|`deny.suffix` |string[&#93; |{nbsp} |Suffixes specifying strings to deny.

 @return suffixes which deny matching

|===

// end::config[]