///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.security.providers.httpauth.HttpBasicAuthProvider
:keywords: helidon, config, io.helidon.security.providers.httpauth.HttpBasicAuthProvider
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.security.providers.httpauth.HttpBasicAuthProvider
include::{rootdir}/includes/attributes.adoc[]

= HttpBasicAuthProvider (security.providers.httpauth) Configuration

// tag::config[]

HTTP Basic Authentication provider


Type: link:{javadoc-base-url}/io.helidon.security.providers.httpauth/io/helidon/security/providers/httpauth/HttpBasicAuthProvider.html[io.helidon.security.providers.httpauth.HttpBasicAuthProvider]


[source,text]
.Config key
----
http-basic-auth
----


This type provides the following service implementations:

- `io.helidon.security.spi.SecurityProvider`
- `io.helidon.security.spi.AuthenticationProvider`


== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`optional` |boolean |`false` |Whether authentication is required.
 By default, request will fail if the authentication cannot be verified.
 If set to false, request will process and this provider will abstain.
|`outbound` |xref:{rootdir}/config/io_helidon_security_providers_common_OutboundTarget.adoc[OutboundTarget[&#93;] |{nbsp} |Add a new outbound target to configure identity propagation or explicit username/password.
|`principal-type` |SubjectType (USER, SERVICE) |`USER` |Principal type this provider extracts (and also propagates).
|`realm` |string |`helidon` |Set the realm to use when challenging users.
|`users` |xref:{rootdir}/config/io_helidon_security_providers_httpauth_ConfigUserStore_ConfigUser.adoc[ConfigUser[&#93;] |{nbsp} |Set user store to validate users.
 Removes any other stores added through #addUserStore(SecureUserStore).

|===

// end::config[]