///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.security.providers.httpauth.HttpDigestAuthProvider
:keywords: helidon, config, io.helidon.security.providers.httpauth.HttpDigestAuthProvider
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.security.providers.httpauth.HttpDigestAuthProvider
include::{rootdir}/includes/attributes.adoc[]

= HttpDigestAuthProvider (security.providers.httpauth) Configuration

// tag::config[]

Http digest authentication security provider


Type: link:{javadoc-base-url}/io.helidon.security.providers.httpauth/io/helidon/security/providers/httpauth/HttpDigestAuthProvider.html[io.helidon.security.providers.httpauth.HttpDigestAuthProvider]


[source,text]
.Config key
----
http-digest-auth
----


This type provides the following service implementations:

- `io.helidon.security.spi.SecurityProvider`
- `io.helidon.security.spi.AuthenticationProvider`


== Configuration options



Optional configuration options:
[cols="3,3,2,5a"]

|===
|key |type |default value |description

|`algorithm` |Algorithm (MD5) |`MD5` |Digest algorithm to use.
|`nonce-timeout-millis` |long |`1 day` |How long will the nonce value be valid. When timed-out, browser will re-request username/password.
|`optional` |boolean |`false` |Whether authentication is required.
 By default, request will fail if the authentication cannot be verified.
 If set to false, request will process and this provider will abstain.
|`principal-type` |SubjectType (USER, SERVICE) |`USER` |Type of authenticated entity, can be used in combination with other authentication mechanism to authenticate both the user (as in person sitting in front of a computer) and a service (as in the application requesting this service on user's behalf)
|`qop` |Qop (NONE, AUTH) |`NONE` |Only `AUTH` supported. If left empty, uses the legacy approach (older RFC version). `AUTH-INT` is not supported.
|`realm` |string |`Helidon` |Set the realm to use when challenging users.
|`server-secret` |string |{nbsp} |The nonce is encrypted using this secret - to make sure the nonce we get back was generated by us and to
 make sure we can safely time-out nonce values.
 This secret must be the same for all service instances (or all services that want to share the same authentication).
 Defaults to a random password - e.g. if deployed to multiple servers, the authentication WILL NOT WORK. You MUST
 provide your own password to work in a distributed environment with non-sticky load balancing.
|`users` |string[&#93; |{nbsp} |List of users when using configuration based approach. As an alternative, you can implement a java service (see below).

|===

// end::config[]