///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.grpc.server.GrpcServerConfiguration
:keywords: helidon, config, io.helidon.grpc.server.GrpcServerConfiguration
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.grpc.server.GrpcServerConfiguration
include::{rootdir}/includes/attributes.adoc[]

= GrpcServerConfiguration (grpc.server) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.grpc.server/io/helidon/grpc/server/GrpcServerConfiguration.html[io.helidon.grpc.server.GrpcServerConfiguration]




== Configuration Options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`name` |string |`grpc.server` |Set the name of the gRPC server.

 Configuration key: `name`
|`native` |boolean |`false` |Specify if native transport should be used.
|`port` |int |`1408` |Sets server port. If port is `0` or less then any available ephemeral port will be used.

 Configuration key: `port`
|`workers` |int |`Number of processors available to the JVM` |Sets a count of threads in pool used to process HTTP requests.
 Default value is `CPU_COUNT * 2`.

 Configuration key: `workers`

|===

// end::config[]