///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/..]
:description: Configuration of io.helidon.webserver.ConnectionConfig
:keywords: helidon, config, io.helidon.webserver.ConnectionConfig
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.webserver.ConnectionConfig
include::{rootdir}/includes/attributes.adoc[]

= ConnectionConfig (webserver) Configuration

// tag::config[]


Type: link:{javadoc-base-url}/io.helidon.webserver/io/helidon/webserver/ConnectionConfig.html[io.helidon.webserver.ConnectionConfig]




== Configuration options



.Optional configuration options
[cols="3,3a,2,5a"]

|===
|key |type |default value |description

|`connect-timeout` |Duration |`PT10S` |Connect timeout.
 Default is `DEFAULT_CONNECT_TIMEOUT_DURATION`.

 @return connect timeout
|`keep-alive` |boolean |`true` |Configure socket keep alive.
 Default is `true`.

 @return keep alive
 @see java.net.StandardSocketOptions#SO_KEEPALIVE
|`read-timeout` |Duration |`PT30S` |Read timeout.
 Default is `DEFAULT_READ_TIMEOUT_DURATION`

 @return read timeout
|`receive-buffer-size` |int |`32768` |Socket receive buffer size.
 Default is `DEFAULT_SO_BUFFER_SIZE`.

 @return buffer size, in bytes
 @see java.net.StandardSocketOptions#SO_RCVBUF
|`reuse-address` |boolean |`true` |Socket reuse address.
 Default is `true`.

 @return whether to reuse address
 @see java.net.StandardSocketOptions#SO_REUSEADDR
|`send-buffer-size` |int |`32768` |Socket send buffer size.
 Default is `DEFAULT_SO_BUFFER_SIZE`.

 @return buffer size, in bytes
 @see java.net.StandardSocketOptions#SO_SNDBUF
|`tcp-no-delay` |boolean |`false` |This option may improve performance on some systems.
 Default is `false`.

 @return whether to use TCP_NODELAY, defaults to `false`
 @see java.net.StandardSocketOptions#TCP_NODELAY

|===

// end::config[]