///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////
:java-base: src/main/java/io/helidon/guides/mp/restfulwebservice
:greet-app: {java-base}/GreetApplication.java
:main-class: {java-base}/Main.java
:greet-resource-class: {java-base}/GreetResource.java
:greet-application-class: {java-base}/GreetApplication.java
:health-resource-class: {java-base}/CheckLiveness.java
:greeting-provider-class: {java-base}/GreetingProvider.java
:pom: pom.xml
:src-main-resources: src/main/resources
:meta-inf-dir: {src-main-resources}/META-INF
:beans-xml: {meta-inf-dir}/beans.xml
:config-file: {meta-inf-dir}/microprofile-config.properties
:logging-properties-file: {src-main-resources}/logging.properties
:se-guide-adoc: ../se-restful-webservice/README.adoc
:artifact-id: mp-restful-webservice


= The MP RESTful Web Service Guide
:description: Helidon MP guide restful web service
:keywords: helidon, guide, example, mp
:toc: preamble
:toclevels: 3

Create and build a JAX-RS RESTful web service as your first Helidon MP application.

== What you will learn
You'll learn how to use Helidon MP quickly to create a JAX-RS RESTful web service that accepts these HTTP requests:

|===
|Method and URL | Result

|`GET localhost:8080/greet` |Returns a generic but friendly greeting
|`GET localhost:8080/greet/Joe` |Returns a personalized greeting for the specified person
|`PUT localhost:8080/greet/greeting/Hola` |Changes the greeting used in subsequent responses
|===

We create the app in these main steps:

. Write a basic Helidon MP app to respond to the HTTP requests.

. Add code to perform a simple app-speciric health check.

. Add code to record a simple app-specific metric.

This guide walks you through the code and helps you understand what each part of the
code does. But if you prefer, you can get the finished code for this example.
See the <<downloading,downloading>> section for instructions.

== What you need

|===
|About 15 minutes
|An IDE or text editor
|JDK 8 or later
|Maven 3.5 or later
|===

//Optional:
//|===
//|Docker 18.02 (use the Edge channel to run Kubernetes on your desktop)
//|`kubectl` 1.7.4
//|===

== Develop your application

=== Generate the Maven project using the Helidon archetype
Helidon provides a Maven archetype you can use to create a new Helidon project that
includes sample code.

1. `cd` to a directory that is not already a Maven project.
2. Run this command:
+
--
[source,bash,subs="attributes+"]
.Creating a new Helidon MP project
----
mvn archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-mp \
    -DarchetypeVersion={helidon-version} \
    -DgroupId=io.helidon.guides \
    -DartifactId={artifact-id} \
    -Dpackage=io.helidon.guides.mp.restfulwebservice
----

Running the archetype this way creates a subdirectory `{artifact-id}`
(using the `artifactId` setting from the archetype invocation) that contains a new
Maven project for a Helidon service.
--

=== Browse the generated source

==== `pom.xml`
The input you provided to the archetype determines the project's Maven
coordinates:
[source,xml,indent=0]
----
include::{pom}[tag=coordinates]
----

Also in the `<dependency-management>` section notice the dependency on the Helidon bom pom:
[source,xml,subs="verbatim,attributes"]
----
include::{pom}[tag=bom,indent=0]
----

Lower, in the `<dependencies>` section, you will see a declaration for the Helidon
MicroProfile bundle.

==== `src/main/resources/META-INF/microprofile-config.properties`
This file contains settings for the Helidon web server and the
application. Note that the MicroProfile Config specification says that
configuration data is read, by default, from this file;
the application does not have to do anything in code to load it.
[source]
.src/main/resources/META-INF/microprofile-config.properties
----
include::{config-file}[tag=configContent]
----
<1> Initial application greeting.
<2> Web server configuration.

==== `src/main/resources/logging.properties`
This file controls logging within the application.
[source,java]
.src/main/resources/logging.properties
----
include::{logging-properties-file}[tag=loggingProps]
----

==== `src/main/resources/META-INF/beans.xml` -- "empty" `beans.xml`
This "empty" `beans.xml` file makes sure JAX-RS searches for beans.
[source,java]
.src/main/resources/META-INF/beans.xml
----
<?xml version="1.0" encoding="UTF-8"?>
include::{beans-xml}[tag=beans]
----

==== `GreetingProvider.java` - a bean to hold the greeting message
The app contains a default greeting loaded from configuration which the user
can set via HTTP.
The app stores the current greeting message in this JAX-RS bean for injection where needed.

[source,java]
----
include::{greeting-provider-class}[tag=class]
----
<1> Makes sure the system allocates one instance of `GreetingProvider` and uses
that one wherever `GreetingProvider` is injected.
<2> An `AtomicReference<String>` can handle potential concurrent attempts to update it,
so one holds the greeting message. Your application might receive multiple concurrent HTTP requests that
try to modify the message.
<3> The constructor is annotated with `javax.inject.Inject` and
accepts the initial message value as a `String` argument. The `ConfigProperty` annotation
on that argument triggers automatic MicroProfile config processing to look up the
`app.greeting` config value from (in our case) the default
MicroProfile config source: `META-INF/microprofile-config.properties`.
<4> Returns the greeting.
<5> Sets the greeting.

==== `GreetResource.java` - the JAX-RS root resource for the application
This class defines the endpoints for the application.

Note several points:

. The resource is request-scoped and declares the common path prefix that
all endpoints in the resource share.
+
--
[source,java]
----
include::{greet-resource-class}[tag=classDecl,indent=0]
}
----
--
. JAX-RS injects the single instance of the `GreetingProvider` bean so the
resource can access the greeting message.
+
--
[source,java]
----
include::{greet-resource-class}[tag=ctor,indent=0]
----
--
. A private method formats the messages the endpoints
return to the clients.
+
--
[source,java]
----
include::{greet-resource-class}[tag=createResponse,indent=0]
----
<1> `who` is the name of the end-user we want to greet
<2> Retrieves the greeting message from the `GreetingProvider` bean and embeds the end-user name
in it.
<3> Prepares the response as JSON.
--

. Three methods implement the resource's three endpoints.
.. Returning the default message
+
--
[source,java]
----
include::{greet-resource-class}[tag=getDefaultMessage,indent=0]
----
<1> Indicates the HTTP method: `GET`.
<2> Tells JAX-RS that this method returns JSON.
--
.. Returning the personalized greeting
+
--
[source,java]
----
include::{greet-resource-class}[tag=getMessageWithName,indent=0]
----
<1> Declares the path parameter which is the name to use for personalizing
the returned message.
<2> Indicates the HTTP method: `GET`.
<3> Tells JAX-RS that this method returns JSON.
<4> Triggers injection of the path parameter `name` as an argument to the method.
--
.. Setting a new greeting message
+
--
[source,java]
----
include::{greet-resource-class}[tag=setGreeting,indent=0]
----
<1> Identifies the path parameter for the new greeting text.
<2> It's an HTTP `PUT`.
<3> Tells JAX-RS that this method both consumes and produces JSON.
<4> JAX-RS injects the new greeting from the path parameter as the method argument.
--

==== `GreetApplication.java` - the `Application` class
JAX-RS looks for an `Application` and will find `GreetApplication`.

[source,java]
----
include::{greet-application-class}[tag=greetAppBody,indent=0]
----
<1> JAX-RS creates only one instance of this class.
<2> No path prefix for this application.
<3> Class must extend `javax.ws.rs.core.Application`.
<4> Reports the resource classes in the application.

==== `Main.java`
The main class is quite short.

. `startServer`
+
--
[source,java]
----
include::{main-class}[tag=startServer,indent=0]
----
<1> Automatically reads server configuration from `microprofile-config.properties`
and then starts the reactive web server.
--
. `setupLogging`
+
--
[source,java]
----
include::{main-class}[tag=setupLogging,indent=0]
----
<1> Loads logging config from `logging.properties`
--
. `main`
+
--
The `main` method simply sets up logging, starts the server, and announces
a successful start-up.
[source,java]
----
include::{main-class}[tag=main]
----
--

== Build and run
include::{se-guide-adoc}[tag=buildAndRun]

== Add an app-specific health check
include::{se-guide-adoc}[tag=addHealthChecksIntro]

Helidon MicroProfile provides a built-in health framework. We can tap into that
easily to add our app-specific liveness check.

=== Add a new class for the health check
Create `CheckLiveness.java` to define the endpoints for checking if the service is
active and if it is ready.

. Add these imports:
+
--
[source,java]
----
include::{health-resource-class}[tag=imports]
----
--

. Declare the class this way:
+
--
[source,java]
----
include::{health-resource-class}[tag=classDecl,indent=0]
}
----
<1> Mark the class as `@ApplicationScoped`; we need only one instance in the app.
<2> Identify this as a health resource.
<3> The class must implement `HealthCheck`.
--

. Declare an injected instance field to refer to the greeting message provider. This
is the only input to the active check in our simple implementation.
+
--
[source,java]
----
include::{health-resource-class}[tag=greetingDecl,indent=0]
----
<1> Indicates that JAX-RS should inject the field.
<2> JAX-RS will inject a reference to the single `GreetingProvider` instance.
--

. Add the `call` method.
+
--
The health framework invokes `call` to retrieve the health information associated
with this health resource.

[source,java]
----
include::{health-resource-class}[tag=callMethod,indent=0]
----
<1> Create the health check with the name `greetingAlive`.
<2> The service is alive as long as the greeting message (trimmed) is not empty.
<3> If not, report that this liveness check is `down` and add an explanatory
message.
<4> If so, report that this liveness check is `up`.
<5> Either way, build the response and return it.
--

include::{se-guide-adoc}[tags=rebuildAndRerunService;tryReadiness;!se-HealthChecks-notes]

== Add metrics support
include::{se-guide-adoc}[tag=metricsIntro]

=== Update the code

. Add the metrics dependency to `pom.xml`.
+
--
[source,xml]
----
include::{pom}[tag=metricsDependency,indent=0]
----
--

. In `GreetResource` annotate each method that is to be measured, in our case `getDefaultMessage`,
`getMessage`, and `updateGreeting`. (We annotate `updateGreeting` for simplicity
and so the metrics
reported here have the same values as for the Helidon SE RESTful web
service example. In a real application we might measure the `update` method separately
from the `get` methods.)
.. Add these imports:
+
--
[source,java]
----
include::{greet-resource-class}[tag=metricsImports,indent=0]
----
--

.. Annotate `getDefaultMessage`, `getMessage`, and `updateGreeting` so they are
instrumented
+
--
[source,java]
----
include::{greet-resource-class}[tag=countedAnno,indent=0]
----
<1> Marks this method as measured by a `Counter` metric.
<2> Declares the unique name for this counter among all metrics.
<3> Allows the same counter to accumulate uses of multiple methods.
<4> Indicates that the metrics system should increment the counter on each invocation but
_not_ decrement it when the method returns.
--

=== Stop, rebuild and rerun your application

. Stop any running instance of your app.
. Rebuild the app and then run it.

=== Send some requests
Use the same `curl` commands as before to send requests to
the server:

|====
|Command
a|[source,bash]
curl -X GET http://localhost:8080/greet
a|[source,bash]
curl -X GET http://localhost:8080/greet/Joe
a|[source,bash]
curl -X PUT http://localhost:8080/greet/greeting/Hola
a|[source,bash]
curl -X GET http://localhost:8080/greet/Jose
|====

=== Retrieve metrics
Run this `curl` command to retrieve the collected metrics:
[source,bash]
----
curl -X GET http://localhost:8080/metrics/application <1>
----
<1> Requests all application-scoped metrics (we only have one).
You should see this output (in Prometheus format):
[listing]
----
# TYPE application:io_helidon_guides_mp_restfulwebservice_greet_resource_accessctr counter
# HELP application:io_helidon_guides_mp_restfulwebservice_greet_resource_accessctr Total greetings accesses
application:io_helidon_guides_mp_restfulwebservice_greet_resource_accessctr 4
----
Note that:

. The name of the counter is automatically qualified with the package and class name of the JAX-RS
resource that records the metric (`io_helidon_guides_mp_restfulwebservice_greet_resource_accessctr`). If we
had added `absolute=true` to the `@Counted` annotation attributes then the name would be
simply `accessctr`.

. The first two lines are gathered from the metadata we included in the `@Counted`
annotation.

. As expected, the value for the counter is 4.

A `curl` to `http://localhost:8080/metrics` lists not only our application-scoped
metric but all the _base_ and _vendor_ metrics as defined in the MicroProfile metrics spec.
For example, you will see a `vendor:requests_count`
counter. This will be larger than our counter because that counter also tracks
requests to the `/metrics` path itself; our `accessctr` counter tracks only requests to
our application endpoints.

== (Optional) Download the example source [[downloading]]
Instead of building the application using the code snippets in this guide,
you can download it.

. Clone the link:https://github.com/oracle/helidon[`git` workspace
for Helidon]
. `cd` to the `examples/guides/mp-restful-webservice` directory.
. Run:
+
--
[source,bash]
----
mvn package
java -jar target/mp-restful-webservice.jar
----
--
