///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////
:java-base: src/main/java/io/helidon/guides/mp/restfulwebservice
:greet-app: {java-base}/GreetApplication.java
:main-class: {java-base}/Main.java
:greet-resource-class: {java-base}/GreetResource.java
:greet-application-class: {java-base}/GreetApplication.java
:health-resource-class: {java-base}/CheckLiveness.java
:greeting-provider-class: {java-base}/GreetingProvider.java
:pom: pom.xml
:src-main-resources: src/main/resources
:meta-inf-dir: {src-main-resources}/META-INF
:beans-xml: {meta-inf-dir}/beans.xml
:config-file: {meta-inf-dir}/microprofile-config.properties
:logging-properties-file: {src-main-resources}/logging.properties
:se-guide-adoc: ../se-restful-webservice/README.adoc
:artifact-id: mp-restful-webservice


= The MicroProfile RESTful Web Service Guide
:description: Helidon MicroProfile guide restful web service
:keywords: helidon, guide, example, mp, microprofile
:toc: preamble
:toclevels: 2

Create and build a JAX-RS RESTful web service as your first Helidon MicroProfile application.

== What you will learn
You'll learn how to use Helidon MicroProfile quickly to create a JAX-RS RESTful web service that accepts these HTTP requests:

[width=75%]
|===
|Method and URL | Result

|`GET localhost:8080/greet` |Returns a generic but friendly greeting
|`GET localhost:8080/greet/Joe` |Returns a personalized greeting for the specified person
|`PUT -H "Content-Type: application/json" -d '{"greeting" : "Hola"}' localhost:8080/greet/greeting` |Changes the greeting used in subsequent responses
|===

You'll create the app in three main steps:

. Write a basic Helidon MP app to respond to the HTTP requests.

. Add code to perform a simple app-specific health check.

. Add code to record a simple app-specific metric.

As you develop the app, this guide helps you understand what each part of the code
does. If you prefer to download the finished code for this example, follow the
instructions at <<downloading,Download the example source>>.

== What you need

[width=50%]
|===
|About 15 minutes
|An IDE or text editor
|JDK 8 or later
|Maven 3.5 or later
|===

//Optional:
//|===
//|Docker 18.02 (use the Edge channel to run Kubernetes on your desktop)
//|`kubectl` 1.7.4
//|===

== Develop your application

=== Generate the Maven project using the Helidon archetype
Helidon provides a Maven archetype you can use to create a new Helidon project that
includes sample code.

1. `cd` to a directory that is not already a Maven project.
2. Run this command:
+
--
[source,bash,subs="attributes+"]
.Creating a new Helidon MP project
----
mvn archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-mp \
    -DarchetypeVersion={helidon-version} \
    -DgroupId=io.helidon.guides \
    -DartifactId={artifact-id} \
    -Dpackage=io.helidon.guides.mp.restfulwebservice
----

Running the archetype this way creates a subdirectory `{artifact-id}`
(using the `artifactId` setting from the archetype invocation) that contains a new
Maven project for a Helidon service.
--

=== Browse the generated source
==== `pom.xml`
The input you provided to the archetype determines the project's Maven
coordinates:
[source,xml,indent=0]
// _include::0-0:{pom}[tag=coordinates]
----
    <artifactId>mp-restful-webservice</artifactId>
----

In the `<dependency-management>` section, note the dependency on the `helidon-bom` POM:
[source,xml,subs="verbatim,attributes"]
// _include::0-6:{pom}[tag=bom,indent=0]
----
<dependency>
    <groupId>io.helidon</groupId>
    <artifactId>helidon-bom</artifactId>
    <version>${helidon.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----

Later, in the `<dependencies>` section, you will see a declaration for the Helidon
MicroProfile bundle.

==== `src/main/resources/META-INF/microprofile-config.properties`
This file contains settings for the Helidon web server and the
application. Note that the MicroProfile Config specification stipulates that
configuration data is read, by default, from this file;
the application does not have to do anything in code to load it.
[source]
// _include::0-7:{config-file}[tag=configContent]
----
# Application properties. This is the default greeting
# <1>
app.greeting=Hello

# Microprofile server properties
# <2>
server.port=8080
server.host=0.0.0.0
----
<1> Initial application greeting.
<2> Web server configuration.

==== `src/main/resources/logging.properties`
This file controls logging within the application.
[source,java]
// _include::0-10:{logging-properties-file}[tag=loggingProps]
----
# Send messages to the console
handlers=java.util.logging.ConsoleHandler

# Global default logging level. Can be overriden by specific handlers and loggers
.level=INFO

# Helidon Web Server has a custom log formatter that extends SimpleFormatter.
# It replaces "!thread!" with the current thread name
java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=io.helidon.webserver.WebServerLogFormatter
java.util.logging.SimpleFormatter.format=%1$tY.%1$tm.%1$td %1$tH:%1$tM:%1$tS %4$s %3$s !thread!: %5$s%6$s%n
----

==== `src/main/resources/META-INF/beans.xml` -- "empty" `beans.xml`
This "empty" `beans.xml` file makes sure JAX-RS searches for beans.
[source,java]
// _include::1-7:{beans-xml}[tag=beans]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee
                           http://xmlns.jcp.org/xml/ns/javaee/beans_2_0.xsd"
       version="2.0"
       bean-discovery-mode="annotated">
</beans>
----

==== `GreetingProvider.java` - a bean to hold the greeting message
The app contains a default greeting loaded from configuration which the user
can set via HTTP.
The app stores the current greeting message in this JAX-RS bean for injection where needed.

[source,java]
// _include::0-21:{greeting-provider-class}[tag=class]
----
@ApplicationScoped // <1>
public class GreetingProvider {
    private final AtomicReference<String> message = new AtomicReference<>(); // <2>

    /**
     * Create a new greeting provider, reading the message from configuration.
     *
     * @param message greeting to use
     */
    @Inject
    public GreetingProvider(@ConfigProperty(name = "app.greeting") String message) { // <3>
        this.message.set(message);
    }

    String getMessage() { // <4>
        return message.get();
    }

    void setMessage(String message) { // <5>
        this.message.set(message);
    }
}
----
<1> Makes sure the system allocates one instance of `GreetingProvider` and uses
that instance wherever `GreetingProvider` is injected.
<2> An `AtomicReference<String>`, which will handle concurrent updates correctly,
holds the greeting message. Your application might receive multiple concurrent HTTP requests that
try to modify the message.
<3> The constructor is annotated with `javax.inject.Inject` and
accepts the initial message value as a `String` argument. The `ConfigProperty` annotation
on that argument triggers automatic MicroProfile config processing to look up the
`app.greeting` config value from (in our case) the default
MicroProfile config source: `META-INF/microprofile-config.properties`.
<4> Returns the greeting.
<5> Sets the greeting.

==== `GreetResource.java` - the JAX-RS root resource for the application
This class defines the endpoints for the application.

Note the following:

. The resource is request-scoped and declares the common path prefix that
all endpoints in the resource share.
+
--
[source,java]
// _include::0-2:{greet-resource-class}[tag=classDecl,indent=0]
----
@Path("/greet")
@RequestScoped
public class GreetResource {
}
----
--
. JAX-RS injects the single instance of the `GreetingProvider` bean so the
resource can access the greeting message.
+
--
[source,java]
// _include::0-3:{greet-resource-class}[tag=ctor,indent=0]
----
@Inject
public GreetResource(GreetingProvider greetingConfig) {
    this.greetingProvider = greetingConfig;
}
----
--
. A private method formats the messages that the endpoints
return to the clients.
+
--
[source,java]
// _include::0-6:{greet-resource-class}[tag=createResponse,indent=0]
----
private JsonObject createResponse(String who) { // <1>
    String msg = String.format("%s %s!", greetingProvider.getMessage(), who); // <2>

    return JSON.createObjectBuilder() // <3>
            .add("message", msg)
            .build();
}
----
<1> `who` is the name of the end-user we want to greet
<2> Retrieves the greeting message from the `GreetingProvider` bean and embeds the end-user name
in it.
<3> Prepares the response as JSON.
--

. The following methods implement the resource's three endpoints.
.. Returning the default message
+
--
[source,java]
// _include::0-5:{greet-resource-class}[tag=getDefaultMessage,indent=0]
----
@SuppressWarnings("checkstyle:designforextension")
@GET // <1>
@Produces(MediaType.APPLICATION_JSON) // <2>
public JsonObject getDefaultMessage() {
    return createResponse("World");
}
----
<1> Indicates the HTTP method: `GET`.
<2> Tells JAX-RS that this method returns JSON.
--
.. Returning the personalized greeting
+
--
[source,java]
// _include::0-6:{greet-resource-class}[tag=getMessageWithName,indent=0]
----
@SuppressWarnings("checkstyle:designforextension")
@Path("/{name}") // <1>
@GET // <2>
@Produces(MediaType.APPLICATION_JSON) // <3>
public JsonObject getMessage(@PathParam("name") String name) { // <4>
    return createResponse(name);
}
----
<1> Declares the path parameter which is the name to use for personalizing
the returned message.
<2> Indicates the HTTP method: `GET`.
<3> Tells JAX-RS that this method returns JSON.
<4> Triggers injection of the path parameter `name` as an argument to the method.
--
.. Setting a new greeting message
+
--
[source,java]
// _include::0-20:{greet-resource-class}[tag=setGreeting,indent=0]
----
@SuppressWarnings("checkstyle:designforextension")
@Path("/greeting") // <1>
@PUT // <2>
@Consumes(MediaType.APPLICATION_JSON) // <3>
@Produces(MediaType.APPLICATION_JSON) // <3>
public Response updateGreeting(JsonObject jsonObject) {
    if (!jsonObject.containsKey("greeting")) {
        JsonObject entity = JSON.createObjectBuilder()
                .add("error", "No greeting provided")
                .build();
        return Response.status(Response.Status.BAD_REQUEST)
                .entity(entity)
                .build();
    }

    String newGreeting = jsonObject.getString("greeting"); // <4>

    greetingProvider.setMessage(newGreeting); // <5>
    return Response.status(Response.Status.NO_CONTENT) // <6>
            .build();
}
----
<1> Identifies the path for this endpoint.
<2> It's an HTTP `PUT`.
<3> Tells JAX-RS that this method both consumes and produces JSON.
<4> Retrieve the new greeting from the JSON payload.
<5> Save the new greeting for later use.
<6> Prepare the response.
--

==== `GreetApplication.java` - the `Application` class
JAX-RS looks for an `Application` and will find `GreetApplication`.

[source,java]
// _include::0-8:{greet-application-class}[tag=greetAppBody,indent=0]
----
@ApplicationScoped // <1>
@ApplicationPath("/") // <2>
public class GreetApplication extends Application { // <3>

    @Override
    public Set<Class<?>> getClasses() {
        return CollectionsHelper.setOf(GreetResource.class); // <4>
    }
}
----
<1> JAX-RS creates only one instance of this class.
<2> No path prefix for this application.
<3> Class must extend `javax.ws.rs.core.Application`.
<4> Reports the resource classes in the application.

==== `Main.java`
The main class is quite short.

. `startServer`
+
--
[source,java]
// _include::0-5:{main-class}[tag=startServer,indent=0]
----
static Server startServer() {
    // Server will automatically pick up configuration from
    // microprofile-config.properties
    // and Application classes annotated as @ApplicationScoped
    return Server.create().start(); // <1>
}
----
<1> Automatically reads server configuration from `microprofile-config.properties`
and then starts the reactive web server.
--
. `setupLogging`
+
--
[source,java]
// _include::0-4:{main-class}[tag=setupLogging,indent=0]
----
private static void setupLogging() throws IOException {
    // load logging configuration
    LogManager.getLogManager().readConfiguration(
            Main.class.getResourceAsStream("/logging.properties")); // <1>
}
----
<1> Loads logging config from `logging.properties`
--
. `main`
+
--
The `main` method simply sets up logging, starts the server, and announces
a successful start-up.
[source,java]
// _include::0-6:{main-class}[tag=main]
----
    public static void main(final String[] args) throws IOException {
        setupLogging();

        Server server = startServer();

        System.out.println("http://localhost:" + server.port() + "/greet");
    }
----
--

== Build and run
// _include::0-39:{se-guide-adoc}[tag=buildAndRun]
You can use your IDE's features to build and run the project directly.

Or, to use Maven outside the IDE, build your app this way:
[source,bash]
mvn package

and run it like this:
[source,bash,subs="attributes+"]
java -jar target/{artifact-id}.jar

Once you have started your app, from another command window run these commands
to access its functions:
[[curl-command-table]]
|====
|Command |Result |Function

a|[source,bash]
curl -X GET http://localhost:8080/greet
a|[listing]
{"message":"Hello World!"}
|Returns a greeting with no personalization

a|[source,bash]
curl -X GET http://localhost:8080/greet/Joe
a|[listing]
{"message":"Hello Joe!"}
|Returns the personalized greeting

a|[source,bash]
curl -X PUT -H "Content-Type: application/json" -d '{"greeting" : "Hola"}' http://localhost:8080/greet/greeting/Hola
a|
(no response payload)
|Changes the greeting

a|[source,bash]
curl -X GET http://localhost:8080/greet/Jose
a|[listing]
{"message":"Hola Jose!"}
|Shows that the greeting change took effect
|====

== Add an app-specific health check
// _include::0-37:{se-guide-adoc}[tag=addHealthChecksIntro]
A well-behaved microservice reports on its own health.
Two common approaches for checking health, often used together, are:

- readiness - a simple verification that the service has been started, has initialized itself,
and is ready to respond to requests; and
- liveness - often a more thorough assessment of whether
and how well the service can do its job.

For example, Kubernetes can ping your service's
readiness endpoint after it starts the pod containing the service to determine
when the service is ready to accept requests, withholding traffic until the readiness
endpoint reports success. Kubernetes can use the liveness endpoint to find out if
the service considers itself able to function, attempting a pod restart if the
endpoint reports a problem.

In general a liveness check might assess:

- service health - whether the service itself can do its job correctly
- host health - if the host has sufficient resources (for example, disk space)
for the service to operate
- health of other, dependent services - if other services on which this service
depends are themselves OK.

We will add an app-specific liveness check.
Our greeting service does not depend on any
host resources (like disk space) or any other services. So for this
example we define our service as "alive" in a very trivial way:
if the greeting text has been assigned
_and is not empty_ when trimmed of leading or trailing white space. Otherwise we
consider the service to be unhealthy, in which case the service will
still respond but its answers might not be what we want.

Normally we would
write our service to make
sure that a newly-assigned greeting is non-empty _before_
accepting it. But omitting that validation lets us create an easy health check
that we can use by simply setting the greeting to blank from
a `curl` command.

Helidon MicroProfile provides a built-in health framework. We can use that
framework easily to add our app-specific liveness check.

=== Add a new class for the health check
Create `CheckLiveness.java` to define the endpoints for checking whether the service is
active and whether it is ready.

. Add these imports:
+
--
[source,java]
// _include::0-6:{health-resource-class}[tag=imports]
----
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

import org.eclipse.microprofile.health.Health;
import org.eclipse.microprofile.health.HealthCheck;
import org.eclipse.microprofile.health.HealthCheckResponse;
import org.eclipse.microprofile.health.HealthCheckResponseBuilder;
----
--

. Declare the class:
+
--
[source,java]
// _include::0-2:{health-resource-class}[tag=classDecl,indent=0]
----
@ApplicationScoped // <1>
@Health // <2>
public class CheckLiveness implements HealthCheck { // <3>
}
----
<1> Mark the class as `@ApplicationScoped`; we need only one instance in the app.
<2> Identify this as a health resource.
<3> The class must implement `HealthCheck`.
--

. Declare an injected instance field to refer to the greeting message provider. This
is the only input to the active check in our simple implementation.
+
--
[source,java]
// _include::0-1:{health-resource-class}[tag=greetingDecl,indent=0]
----
@Inject // <1>
private GreetingProvider greeting; // <2>
----
<1> Indicates that JAX-RS should inject the field.
<2> JAX-RS will inject a reference to the single `GreetingProvider` instance.
--

. Add the `call` method.
+
--
The health framework invokes `call` to retrieve the health information associated
with this health check.

[source,java]
// _include::0-10:{health-resource-class}[tag=callMethod,indent=0]
----
public HealthCheckResponse call() {
    HealthCheckResponseBuilder builder = HealthCheckResponse.builder()
            .name("greetingAlive"); //<1>
    if (greeting == null || greeting.getMessage().trim().length() == 0) { //<2>
        builder.down() //<3>
               .withData("greeting", "not set or is empty");
    } else {
        builder.up(); //<4>
    }
    return builder.build(); //<5>
}
----
<1> Create the health check with the name `greetingAlive`.
<2> The service is alive as long as the greeting message (trimmed) is not empty.
<3> If the message is empty, then report that this liveness check is `down` and add an explanatory
message.
<4> If the message is non-empty, then report that this liveness check is `up`.
<5> In either case, build the response and return it.
--

// _include::0-120:{se-guide-adoc}[tags=rebuildAndRerunService;tryReadiness;!se-HealthChecks-notes]
=== Stop, rebuild and rerun your service

. Stop any running instance of your app.
. Rebuild the app and then run it.


=== Check the server's health
Run this command:
[source,bash]
curl -X GET http://localhost:8080/health | json_pp

You should see output as shown in this example:
[listing,subs=+quotes]
----
{
    "checks": [
        {
            "name": "deadlock",
            "state": "UP"
        },
        {
            "data": {
                "free": "179.37 GB",
                "freeBytes": 192597303296,
                "percentFree": "38.51%",
                "total": "465.72 GB",
                "totalBytes": 500068036608
            },
            "name": "diskSpace",
            "state": "UP"
        },
        *{
            "name": "greetingAlive",
            "state": "UP"
        }*,
        {
            "data": {
                "free": "255.99 MB",
                "freeBytes": 268422144,
                "max": "4.00 GB",
                "maxBytes": 4294967296,
                "percentFree": "98.73%",
                "total": "308.00 MB",
                "totalBytes": 322961408
            },
            "name": "heapMemory",
            "state": "UP"
        }
    ],
    "outcome": "UP"
}
----
The item labeled `outcome` describes the overall health of the
server based on all the other indicators. The state of all the indicators is UP.
So the `outcome` field shows UP. You should also see our app-specific liveness check in the output
(bolded above).

=== Arrange for an unhealthy report
Recall that our simple rule for liveness is that the greeting be non-null and
non-empty. We can easily force our server to report an unhealthy state.

. Set the greeting to a blank.
+
--
[source,bash]
curl -X PUT -H "Content-Type: application/json" -d '{"greeting" : " "}' http://localhost:8080/greet/greeting

Our code to update the greeting accepts this and saves it as the new greeting.
--

. Ping the health check endpoint again with the same command as before.
+
--
[source,bash]
curl -X GET http://localhost:8080/health | python -m json.tool

This time you should see these two parts of the output indicating that something is
wrong:
[listing]
----
        {
            "data": {
                "greeting": "not set or is empty"
            },
            "name": "greetingAlive",
            "state": "DOWN"
        }
...
    "outcome": "DOWN"
----
If you add `-i` to the `curl` command and remove the pipe, the output includes the status 503 "Service Unavailable" report:
[source,bash]
curl -i -X GET http://localhost:8080/health

[listing]
----
HTTP/1.1 503 Service Unavailable
Content-Type: application/json
Date: Tue, 5 Feb 2019 08:09:22 -0600
transfer-encoding: chunked
connection: keep-alive
...
----
--

. Set the greeting back to "Hello", so that the service is healthy again.
+
--
[source,bash]
curl -X PUT -H "Content-Type: application/json" -d '{"greeting" : "Hello"}' http://localhost:8080/greet/greeting
--

. Check the health again.
+
--
[source,bash]
curl -X GET http://localhost:8080/health | python -m json.tool

This time the `outcome` and `greetingAlive` values will be back to `UP`.
--



== Add metrics support
// _include::0-1:{se-guide-adoc}[tag=metricsIntro]
As a simple illustration of using metrics, we revise our greeting service to count how many times
a client sends a request to the app.

=== Update the code

. Add the metrics dependency to `pom.xml`.
+
--
[source,xml]
// _include::0-4:{pom}[tag=metricsDependency,indent=0]
----
<dependency>
    <groupId>io.helidon.microprofile.metrics</groupId>
    <artifactId>helidon-microprofile-metrics</artifactId>
    <scope>runtime</scope>
</dependency>
----
--

. In `GreetResource` annotate each method that is to be measured, in our case `getDefaultMessage`,
`getMessage`, and `updateGreeting`. (We annotate `updateGreeting` for simplicity
and so the metrics
reported here have the same values as for the Helidon SE RESTful web
service example. In a real application we might measure the `update` method separately
from the `get` methods.)
.. Add these imports:
+
--
[source,java]
// _include::0-1:{greet-resource-class}[tag=metricsImports,indent=0]
----
import org.eclipse.microprofile.metrics.MetricUnits;
import org.eclipse.microprofile.metrics.annotation.Counted;
----
--

.. Annotate `getDefaultMessage`, `getMessage`, and `updateGreeting` so they are
instrumented.
+
--
[source,java]
// _include::0-6:{greet-resource-class}[tag=countedAnno,indent=0]
----
@Counted(// <1>
        name = "accessctr", // <2>
        reusable = true,    // <3>
        description = "Total greetings accesses",
        displayName = "Access Counter",
        monotonic = true,   // <4>
        unit = MetricUnits.NONE)
----
<1> Marks this method as measured by a `Counter` metric.
<2> Declares the unique name for this counter among all metrics.
<3> Allows the same counter to accumulate uses of multiple methods.
<4> Indicates that the metrics system should increment the counter on each invocation but
_not_ decrement it when the method returns.
--

=== Stop, rebuild and rerun your application

. Stop any running instance of your app.
. Rebuild the app and then run it.

=== Send some requests
Use the same `curl` commands as before to send requests to
the server:

|====
|Command
a|[source,bash]
curl -X GET http://localhost:8080/greet
a|[source,bash]
curl -X GET http://localhost:8080/greet/Joe
a|[source,bash]
curl -X PUT -H "Content-Type: application/json" -d '{"greeting" : "Hola"}' http://localhost:8080/greet/greeting
a|[source,bash]
curl -X GET http://localhost:8080/greet/Jose
|====

=== Retrieve metrics
Run this `curl` command to retrieve the collected metrics:
[source,bash]
----
curl -X GET http://localhost:8080/metrics/application <1>
----
<1> Requests all application-scoped metrics (we only have one).
You should see this output (in Prometheus format):
[listing]
----
# TYPE application:io_helidon_guides_mp_restfulwebservice_greet_resource_accessctr counter
# HELP application:io_helidon_guides_mp_restfulwebservice_greet_resource_accessctr Total greetings accesses
application:io_helidon_guides_mp_restfulwebservice_greet_resource_accessctr 4
----
Note that:

. The name of the counter is automatically qualified with the package and class name of the JAX-RS
resource that records the metric (`io_helidon_guides_mp_restfulwebservice_greet_resource_accessctr`). If we
had added `absolute=true` to the `@Counted` annotation attributes then the name would be
simply `accessctr`.

. The first two lines are gathered from the metadata we included in the `@Counted`
annotation.

. As expected, the value for the counter is 4.

A `curl` to `http://localhost:8080/metrics` lists not only our application-scoped
metric but all the _base_ and _vendor_ metrics as defined in the MicroProfile metrics
specification.
For example, you will see a `vendor:requests_count`
counter. This will be larger than our counter because that counter also tracks
requests to the `/metrics` path itself; our `accessctr` counter tracks only requests to
our application endpoints.

[[downloading,Download the example source]]
== (Optional) Download the example source
// _include::0-24:{se-guide-adoc}[tag=downloading]
Instead of generating and then enhancing the application as described in this guide,
you can download it.

. Clone the Helidon repository:
+
--
[source,bash]
.Using ssh
git clone git@github.com:oracle/helidon.git

or
[source,bash]
.Using HTTPS
git clone https://github.com/oracle/helidon.git
--
. `cd` to the `helidon/examples/guides/{artifact-id}` directory.
. Run:
+
--
[source,bash,subs="attributes+"]
----
mvn package
java -jar target/{artifact-id}.jar
----
--
