///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Rest Client
:description: Helidon MP Rest Client
= :keywords: helidon, rest, client, microprofile, micro-profile

== Configuring Rest Client with Helidon MP
Declare the following dependency in your project:

[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.restclient</groupId>
    <artifactId>helidon-microprofile-rest-client</artifactId>
</dependency>
----

== Creating new client - Interface
MicroProfile Rest Client can be created by using RestClientBuilder class
and calling method newBuilder. Then you need to specify the baseUri you want to
target on and then just call method build. This method accepts only one
parameter and it is an interface you want to create client from.

Example:
[source,java]
----
SomeInterface someInterface =
                RestClientBuilder.newBuilder()
                                 .baseUri(URI.create("http://localhost:8080/baseUri"))
                                 .build(SomeInterface.class);
someInterface.someMethod(apiModel);
----

== Creating new client - CDI
It is also possible to create rest client via CDI. Interface
which you want to create new client from has to be annotated with
`@RegisterRestClient` annotation. This particular annotation has optional
parameter `baseUri` which does the same thing as baseUri method on builder.

Example:
[source,java]
----
@RegisterRestClient(baseUri="http://localhost:8080/baseUri")
public interface SomeResource {

// ...

}
----

Another step which you need to specify is to create actual injection point
for this resource to be injected in.

Example:
[source,java]
----
@Inject
@RestClient
SomeResource client;

// ...

client.sampleMethod();

----

== Rest client configuration
Rest client implementation allows you to configure its parameters by builder,
annotations and configuration. By using each of these, it is possible to register
new providers and their priorities, specify base uri/url and others.

To further investigation of how to do that, please take a look at the spec:
`https://download.eclipse.org/microprofile/microprofile-rest-client-1.2.1/microprofile-rest-client-1.2.1.html`

== Runnable example
To be able to run and test this example, please head to the Helidon examples/quickstarts
and start helidon-quickstart-mp example by its Main.main method. Then create project with
the dependency on the Helidon rest client implementation and create following rest client
interface.

Rest client interface:
[source,java]
----
@Path("/greet")
interface GreetRestClient {

     @GET
     JsonObject getDefaultMessage();

     @Path("/{name}")
     @GET
     JsonObject getMessage(@PathParam("name") String name);

}
----
Then create runnable method the same way as it is described in
`Creating new client - Interface`,but with baseUri `http://localhost:8080/greet`
and different interface name.

When you try to run the methods on your new instance, you should be getting output
as expected.