///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Rest Client
:description: Helidon MP Rest Client
= :keywords: helidon, rest, client, microprofile, micro-profile

== Configuring Rest Client with Helidon MP
Declare the following dependency in your project:

[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.restclient</groupId>
    <artifactId>helidon-microprofile-rest-client</artifactId>
</dependency>
----

== Creating new client - Interface
MicroProfile Rest Client can be created by using RestClientBuilder class
and calling method newBuilder. Then you need to specify the baseUri you want to
target on and then just call method build. This method accepts only one
parameter and it is an interface you want to create client from.

Example:
[source,java]
----
SomeInterface someInterface =
                RestClientBuilder.newBuilder()
                                 .baseUri("localhost:8080")
                                 .build(SomeInterface.class);
remoteApi.someMethod(apiModel);
----

== Creating new client - Annotation
It is also possible to create rest client via annotations.


MicroProfile Rest Client can be created by using RestClientBuilder class
and calling method newBuilder. Then you need to specify the baseUri you want to
target on and then just call method build. This method accepts only one
parameter and it is an interface you want to create client from.

Example:
[source,java]
----
SomeInterface someInterface =
                RestClientBuilder.newBuilder()
                                 .baseUri("localhost:8080")
                                 .build(SomeInterface.class);
remoteApi.someMethod(apiModel);
----

== Trace propagation across services
Automated trace propagation is supported currently only with Jersey client.

Tracing propagation works automatically as long as you execute
the client call in the same thread as the Jersey server side.

_Exceptions that require manual handling_:

- When the resource method is annotated with Fault Tolerance annotations (e.g. `@Fallback`)
- When you use `async()` on the Jersey client request

In such cases, you must provide the SpanContext by hand:
[source,java]
.Tracing propagation with Jersey client (on a different thread)
----
import static io.helidon.tracing.jersey.client.ClientTracingFilter.CURRENT_SPAN_CONTEXT_PROPERTY_NAME;
import static io.helidon.tracing.jersey.client.ClientTracingFilter.TRACER_PROPERTY_NAME;

// ...

Response response = client.target(serviceEndpoint)
    .request()
    // tracer should be provided unless available as GlobalTracer
    .property(TRACER_PROPERTY_NAME, tracer)
    .property(CURRENT_SPAN_CONTEXT_PROPERTY_NAME, spanContext)
    .get();
----

Tracer and SpanContext can be obtained from `ServerRequest` that can be injected into Resource classes:

----
@Context
io.helidon.webserver.ServerRequest serverRequest;

//...

SpanContext spanContext = serverRequest.spanContext();
// optional, you could also use GlobalTracer.get() if it is configured
Tracer tracer = req.webServer().configuration().tracer();
----
