///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/../../..]

:basic-table-intro: The table below lists the configuration keys that identify the CORS characteristics.
:cors-config-key-explanation: , identified with the configuration key 'cors',
:cors-config-table-exclude-methods: true
:feature-name: OIDC Security Provider

include::{rootdir}/config/io_helidon_security_providers_oidc_OidcProvider.adoc[leveloffset=+2,tag=config]

=== Example code
See the link:{helidon-github-tree-url}/examples/security/idcs-login[example] on GitHub.

[source,yaml]
.Configuration example
----
security:
  providers:
  - oidc:
      client-id: "client-id-of-this-service"
      client-secret: "${CLEAR=client-secret-of-this-service}"
      identity-uri: "http://your-tenant.identity-server.com"
      frontend-uri: "http://my-service:8080"
      audience: "http://my-service"
      cors:
        allow-origins: ["http://foo.com", "http://there.com"]
        allow-methods: ["PUT", "DELETE"]
      outbound:
        - name: "internal-services"
          hosts: ["*.example.org"]
          outbound-token:
            header: "X-Internal-Auth"
----

=== How does it work? [[oidc-workflow]]
At Helidon startup, if OIDC provider is configured, the following will happen:

1. `client-id`, `client-secret`, and `identityUri` are validated - these must provide values
2. Unless all resources are configured as local resources, the provider attempts
to contact the `oidc-metadata.resource` endpoint to retrieve all endpoints

At runtime, depending on configuration...

If a request comes without a token or with insufficient scopes:

1. If `redirect` is set to `true` (default), request is redirected to the authorization
endpoint of the identity server. If set to false, `401` is returned
2. User authenticates against the identity server
3. The identity server redirects back to Helidon service with a code
4. Helidon service contacts the identity server's token endpoint, to exchange the code
for a JWT
5. The JWT is stored in a cookie (if cookie support is enabled, which it is by default)
6. Helidon service redirects to original endpoint (on itself)

Helidon obtains a token from request (from cookie, header, or query parameter):

1. Token is parsed as a singed JWT
2. We validate the JWT signature either against local JWK or against the identity server's
introspection endpoint depending on configuration
3. We validate the issuer and audience of the token if it matches the configured values
4. A subject is created from the JWT, including scopes from the token
5. We validate that we have sufficient scopes to proceed, and return `403` if not
6. Handling is returned to security to process other security providers

=== OIDC Multitenancy
Helidon OIDC provider offers also multitenancy support. It is possible to set different OIDC configuration for
each tenant. It is important to note, that it is not needed to add any other dependency.

==== Configuration example
include::{rootdir}/config/io_helidon_security_providers_oidc_common_TenantConfig.adoc[leveloffset=+3,tag=config]

[source,yaml]
.Configuration example
----
security:
  providers:
  - oidc:
      multi-tenant: true
      tenant-id-style: "token-handler"
      tenant-id-handler:
        header: "tenant-name-header"
      client-id: "client-id-of-this-service"
      client-secret: "${CLEAR=client-secret-of-this-service}"
      identity-uri: "http://your-default-tenant.identity-server.com"
      frontend-uri: "http://my-service:8080"
      audience: "http://my-service"
      tenants:
        - name: "your-tenant-name"
          client-id: "tenant-client-id-this-service"
          client-secret: "${CLEAR=tenant-client-secret-of-this-service}"
          identity-uri: "http://your-tenant.identity-server.com"
----

==== How to enable [[tenant-enable]]
. To enable this support, one does need to add `multi-tenant: true` to the root
OIDC configuration
. Set `tenant-id-style` property to either one of the values from the table below
. Add `tenants` config list. Each list entry is required to have unique `name`

.Tenant ID styles
[cols="3,3,5a"]

|===
|style name |Description |Additional configuration
|`host-header` | Tenant name will be matched to the value obtained from the `Host` header |
|`token-handler` | Custom header, which will contain tenant name information. |
We need to also set additional config option named `tenant-id-handler`. This option specifies desired header name.
[source,yaml]
----
tenant-id-handler:
  header: "<HEADER-CONTAINING-TENANT-NAME>"
----
|`domain` | This will obtain the tenant name from the domain |
We need to also set addition config option named `tenant-id-domain-level`
[source,yaml]
----
tenant-id-domain-level: 1
----
Specified number helps determine which part of the domain should be used as tenant name.

Example: +
tenant.oracle.com +
domain level (1) = com +
domain level (2) = oracle +
domain level (3) = tenant
|`none` | This setting will always use default tenant name "@default" |
|===

==== How does that work?
Multitenant support requires to obtain tenant name from the incoming request. OIDC configuration is selected
based on the received tenant name. The way this tenant name has to be provided is configured via `tenant-id-style`
configuration. See <<tenant-enable, How to enable tenants>> for more information. After matching tenant configuration
with the received name, the rest of the OIDC flow if exactly the same as in <<oidc-workflow, How does OIDC work>>.

Base OIDC configuration is treated as a default tenant, which is used, if no tenant name is provided. This default
tenant is having `@default` name specified.

It is also important to note, that each tenant configuration is based on the default tenant configuration (base OIDC configuration),
and therefore its configuration do not need to change all the properties, if they do not differ from the base OIDC
configuration.

[[cors]]
== CORS Settings
As an experimental feature, you can set up cross-origin handling for the redirect and logout endpoints in an optional `cors` block inside the `oidc` configuration.

include::{rootdir}/includes/cors.adoc[tag=basic-cross-origin-config-no-heading-or-intro]
