/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.declarative.tests.compatibility.v4;

import io.helidon.service.registry.Service;
import io.helidon.validation.Validation;

/**
 * Service with parameter and return validation generated by Helidon 4.
 */
@Service.Singleton
public class LegacyValidationService {
    /**
     * Read a validated object parameter.
     *
     * @param value validated value
     * @return property value
     */
    public String objectParameter(@Validation.Valid LegacyValidatedValue value) {
        return value.value();
    }

    /**
     * Return a string subject to a return-value constraint.
     *
     * @param value result to validate
     * @return validated result
     */
    @Validation.String.NotBlank
    public String scalarResult(String value) {
        return value;
    }

    /**
     * Return an object subject to cascaded return-value validation.
     *
     * @param value property value to validate
     * @return validated object
     */
    @Validation.Valid
    public LegacyValidatedValue objectResult(String value) {
        return LegacyValidatedValue.create(value);
    }
}
