/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.declarative.tests.compatibility.v4;

import java.util.Optional;

import io.helidon.builder.api.Prototype;

/**
 * Person whose builder and JSON converter are generated by Helidon 4.
 */
@Prototype.Blueprint
@Prototype.Annotated("io.helidon.json.binding.Json.Entity")
interface LegacyPersonBlueprint {
    /**
     * Person's name.
     *
     * @return name
     */
    String name();

    /**
     * Person's age.
     *
     * @return age
     */
    int age();

    /**
     * Optional nickname.
     *
     * @return nickname
     */
    Optional<String> nickname();
}
