/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.declarative.tests.compatibility.v4;

import io.helidon.service.registry.Event;
import io.helidon.service.registry.Service;

/**
 * Event emitter injection generated by Helidon 4.
 */
@Service.Singleton
public class LegacyEventService {
    private final Event.Emitter<Message> emitter;

    @Service.Inject
    LegacyEventService(Event.Emitter<Message> emitter) {
        this.emitter = emitter;
    }

    /**
     * Publish a synchronous event.
     *
     * @param value event payload
     */
    public void emit(String value) {
        emitter.emit(new Message(value));
    }

    record Message(String value) {
    }
}
