/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.declarative.tests.compatibility.v4;

import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicInteger;

import io.helidon.common.media.type.MediaTypes;
import io.helidon.http.Http;
import io.helidon.http.Status;
import io.helidon.service.registry.Service;
import io.helidon.webserver.http.RestServer;

/**
 * Exercises additional HTTP routes generated by Helidon 4.
 */
@SuppressWarnings("deprecation")
@RestServer.Endpoint
@Service.Singleton
@Http.Path("/legacy/additional")
public class LegacyAdditionalHttpEndpoint {
    private final AtomicInteger emptyCalls = new AtomicInteger();

    private volatile String submittedEntity = "";

    /**
     * Number of completed empty-response requests.
     *
     * @return invocation count
     */
    public int emptyCalls() {
        return emptyCalls.get();
    }

    /**
     * Entity received by the void submission route.
     *
     * @return submitted entity
     */
    public String submittedEntity() {
        return submittedEntity;
    }

    @Http.GET
    @Http.Path("/query")
    @Http.Produces(MediaTypes.TEXT_PLAIN_VALUE)
    String query(@Http.QueryParam("value") Optional<Integer> value) {
        return value.map(it -> "present:" + it).orElse("absent");
    }

    @Http.GET
    @Http.Path("/computed-header")
    @Http.Produces(MediaTypes.TEXT_PLAIN_VALUE)
    String computedHeader(@Http.HeaderParam(LegacyHeaderFunction.HEADER_NAME) String value) {
        return value;
    }

    @Http.GET
    @Http.Path("/empty")
    @RestServer.Status(Status.NO_CONTENT_204_CODE)
    void empty() {
        emptyCalls.incrementAndGet();
    }

    @Http.POST
    @Http.Path("/entity")
    @Http.Consumes(MediaTypes.TEXT_PLAIN_VALUE)
    @RestServer.Status(Status.NO_CONTENT_204_CODE)
    void submit(@Http.Entity String entity) {
        submittedEntity = entity;
    }

    @Http.GET
    @Http.Path("/values")
    @Http.Produces(MediaTypes.APPLICATION_JSON_VALUE)
    List<String> values() {
        return List.of("legacy", "generic");
    }
}
