/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.declarative.tests.compatibility.v4;

import io.helidon.validation.Validation;

/**
 * Value with a type validator generated by Helidon 4.
 */
@Validation.Validated
public class LegacyValidatedValue {
    private final String value;

    private LegacyValidatedValue(String value) {
        this.value = value;
    }

    /**
     * Create a value to validate at an intercepted service boundary.
     *
     * @param value property value
     * @return value instance
     */
    public static LegacyValidatedValue create(String value) {
        return new LegacyValidatedValue(value);
    }

    /**
     * Property validated by the generated type validator.
     *
     * @return property value
     */
    @Validation.String.NotBlank
    public String value() {
        return value;
    }
}
