/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.declarative.tests.compatibility.v4;

import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

import io.helidon.service.registry.Event;
import io.helidon.service.registry.Service;

/**
 * Observer dispatch generated by Helidon 4.
 */
@Service.Singleton
public class LegacyEventObserver {
    private final List<String> received = new CopyOnWriteArrayList<>();

    /**
     * Received event payloads in delivery order.
     *
     * @return received payloads
     */
    public List<String> received() {
        return List.copyOf(received);
    }

    @Event.Observer
    void receive(LegacyEventService.Message message) {
        received.add(message.value());
    }
}
