///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= About CORS in Helidon SE
:toc:
:toc-placement: preamble
:h1Prefix: SE
:description: Helidon SE CORS Support
:keywords: helidon, java, cors, se
:flavor-uc: SE
:flavor-lc: se
:rootdir: {docdir}/../..

include::{rootdir}/includes/attributes.adoc[]

link:https://www.w3.org/TR/cors[Cross-origin resource sharing] (CORS) support in Helidon SE provides a flexible
mechanism that allows a Helidon SE application to control how another web application can access its resources,
even if that web application is served from a different domain.

== Overview

include::{rootdir}/includes/cors/cors-common.adoc[tag=cors-intro]

== Next Steps

To introduce CORS into your Helidon SE application, do any or all of the following:

* Modify your code using the Helidon SE CORS API. xref:02_using-the-api.adoc[Learn more].
* Use configuration in combination with the Helidon SE CORS API to add CORS to your application. xref:03_using-configuration.adoc[Learn more].
* Update your application to include any of the built-in Helidon services that automatically
support CORS. xref:04_support-in-builtin-services.adoc[Learn more].
