///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= About CORS in Helidon SE
:toc:
:toc-placement: preamble
:pagename: cors-introduction
:description: Helidon SE CORS Support
:keywords: helidon, java, cors, se
:helidon-tag: https://github.com/oracle/helidon/tree/{helidon-version}
:quickstart-example: {helidon-tag}/examples/quickstarts/helidon-quickstart-se
:cors-spec: https://www.w3.org/TR/cors/
:helidon-se-cors-example: {helidon-tag}/examples/cors
:helidon-tag: https://github.com/oracle/helidon/tree/{helidon-version}
:quickstart-example: {helidon-tag}/examples/quickstarts/helidon-quickstart-se
:javadoc-base-url-api: {javadoc-base-url}io.helidon.webserver.cors/io/helidon/webserver/cors
:javadoc-base-url-webserver: {javadoc-base-url}io.helidon.webserver/io/helidon/webserver
:helidon-variant: SE

link:{cors-spec}[Cross-origin resource sharing] (CORS) support in Helidon SE provides a flexible
mechanism that allows a Helidon SE application to control how other web applications can access its resources, even if that web application is not served from the same domain.

== Overview
// tag::cors-intro[]
The CORS protocol helps developers control if and how REST resources served by their applications can be shared across origins.
Helidon {helidon-variant} includes an implementation of CORS that you can use to add CORS behavior
to the services you develop. You can define your application's CORS behavior programmatically using the Helidon CORS API alone, or
together with configuration. Helidon also provides three built-in services that add their
own endpoints to your application - health, metrics, and OpenAPI - that have integrated CORS support.
By adding very little code to your application, you control how all the resources in
your application -- the ones you write and the ones provided by the Helidon built-in services -- can be shared across origins.

== Before You Begin
Before you revise your application to add CORS support, you need to decide what type of cross-origin sharing you want
to allow for each resource your application exposes.
For example, suppose for a given resource you want to allow unrestricted sharing for GET, HEAD, and POST requests
(what CORS refers to as "simple" requests), but permit other types of requests only from the two
origins `foo.com` and `there.com`.
Your application would implement two types of CORS sharing: relaxed for the
simple requests and stricter for others.

Once you know the type of sharing you want to allow for each of your resources -- including any from built-in
services -- you can change your application accordingly.

== Next Steps
For details about changing your application to include CORS support, see:

* <<se/cors/02_using-the-api.adoc,Using the Helidon SE CORS API>>
* <<se/cors/03_using-configuration.adoc,Using Configuration for CORS>>
* <<se/cors/04_support-in-builtin-services.adoc, Using CORS in Built-in Services>>
// end::cors-intro[]
