///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= About CORS in Helidon SE
:toc:
:toc-placement: preamble
:pagename: cors-introduction
:description: Helidon SE CORS Support
:keywords: helidon, java, cors, se
:helidon-tag: https://github.com/oracle/helidon/tree/{helidon-version}
:quickstart-example: {helidon-tag}/examples/quickstarts/helidon-quickstart-se
:cors-spec: https://www.w3.org/TR/cors/
:helidon-se-cors-example: {helidon-tag}/examples/cors
:helidon-tag: https://github.com/oracle/helidon/tree/{helidon-version}
:quickstart-example: {helidon-tag}/examples/quickstarts/helidon-quickstart-se
:javadoc-base-url-api: {javadoc-base-url}io.helidon.webserver.cors/io/helidon/webserver/cors
:javadoc-base-url-webserver: {javadoc-base-url}io.helidon.webserver/io/helidon/webserver
:helidon-variant: SE

link:{cors-spec}[Cross-origin resource sharing] (CORS) support in Helidon SE provides a flexible
mechanism that allows a Helidon SE application to control how other web applications can access its resources, even if that web application is not served from the same domain.

== Overview
// tag::cors-intro[]
The CORS protocol helps developers control if and how REST resources are shared across origins.
Helidon {helidon-variant} includes an implementation of CORS which you can use to add CORS behavior
to the services you develop.
Further, three services which are built into Helidon and which add endpoints to your
application -- health, metrics, and OpenAPI -- have integrated CORS support.
By adding a little code to your application and using configuration, you can manage how all resources in
your application -- the ones you write and the ones provided by Helidon -- can be shared across origins.


Before you revise your application, you need to decide what type of cross-origin sharing you want
to allow for each resource your application exposes.
For example, suppose for a given resource you want to allow unrestricted access for GET, HEAD, and POST requests
(what CORS refers to as "simple" requests), but permit other types of requests only from the two
origins `foo.com` and `there.com`.
This means that you have two types of CORS sharing: relaxed for the
simple requests and stricter for others.

Once you know the type of sharing you want to allow for each of your resources -- including any built-in
ones -- you can make the changes required.
// end::cors-intro[]

== Using the Helidon CORS API
Recall that every Helidon SE application explicitly sets up routing rules which govern how Helidon delivers incoming
requests to the code that should respond to those requests.
You do this for both your own endpoints as well as those from built-in services.

To add CORS behavior to endpoints, you augment how you set up the routing, through minimal
coding changes, for those endpoints.
Those coding changes involve using a simple API, provided by the Helidon SE CORS module,
to define the CORS behavior you want and then include that behavior as you build the routing rules for the services
in your application.

The <<se/cors/02_using-the-api.adoc,Using the API>> section explores in detail how to incorporate
CORS into the routing for the endpoints in your application.

== Using Configuration
The API gives you everything you need to add CORS support to your resources, but you can use the API in combination with
configuration. Doing so simplifies your application code a bit by moving some of the CORS-related routing set-up out of
procedural Java code into declarative configuration.

This approach -- combining configuration and the API -- also lets you add a powerful feature
to your app, whereby those who deploy your application can override the CORS behavior which the application
sets up with what _they_ want.
Deployers can modify the configuration to alter the CORS behavior of your endpoints,
without requiring any changes to the application code.

The <<se/cors/03_using-configuration.adoc,Using Configuration>> section explains how to use configuration
with the Helidon CORS API.

== Using CORS with the Built-in Services
The CORS-enabled built-in services have this override feature automatically. Remember that your application sets up
routing for the built-in services as well as your own endpoints. If you write you application to use configuration
in setting up the routing for those services, instead of calling the API alone, you let your users
configure the CORS behavior of the built-in services as well.

You can take advantage of this feature of the built-in services even if you do not add CORS behavior
to your own endpoints.

The <<se/cors/04_support-in-builtin-services.adoc,Using Built-in Services>> section describes how your application can
use configuration in defining the routing for built-in services to implement this override feature.

