///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= About CORS in Helidon SE
:toc:
:toc-placement: preamble
:pagename: cors-introduction
:description: Helidon SE CORS Support
:keywords: helidon, java, cors, se
:helidon-tag: https://github.com/oracle/helidon/tree/{helidon-version}
:quickstart-example: {helidon-tag}/examples/quickstarts/helidon-quickstart-se
:cors-spec: https://www.w3.org/TR/cors/
:helidon-se-cors-example: {helidon-tag}/examples/cors
:helidon-tag: https://github.com/oracle/helidon/tree/{helidon-version}
:quickstart-example: {helidon-tag}/examples/quickstarts/helidon-quickstart-se
:javadoc-base-url-api: {javadoc-base-url}io.helidon.webserver.cors/io/helidon/webserver/cors
:javadoc-base-url-webserver: {javadoc-base-url}io.helidon.webserver/io/helidon/webserver
:helidon-variant: SE

link:{cors-spec}[Cross-origin resource sharing] (CORS) support in Helidon SE provides a flexible
mechanism that allows a Helidon SE application to control how other web applications can access its resources, even if that web application is not served from the same domain.

== Overview
// tag::cors-intro[]
The CORS protocol helps developers control if and how REST resources which their applications serve are shared across origins.
Helidon {helidon-variant} includes an implementation of CORS which you can use to add CORS behavior
to the services you develop.
Further, three services which are built into Helidon and which add their own endpoints to your
application -- health, metrics, and OpenAPI -- have integrated CORS support.
By adding very little code to your application, you control how all resources in
your application -- the ones you write and the ones provided by the Helidon built-in services -- can be shared across origins.

Before you revise your application to add CORS support, you need to decide what type of cross-origin sharing you want
to allow for each resource your application exposes.
For example, suppose for a given resource you want to allow unrestricted sharing for GET, HEAD, and POST requests
(what CORS refers to as "simple" requests), but permit other types of requests only from the two
origins `foo.com` and `there.com`.
Your application would implement two types of CORS sharing: relaxed for the
simple requests and stricter for others.

Once you know the type of sharing you want to allow for each of your resources -- including any from built-in
services -- you can change your application accordingly.
// end::cors-intro[]

== Using the Helidon CORS API
Recall that every Helidon SE application explicitly creates routing rules which govern how Helidon delivers incoming
each request to the code that should respond.
You do this for both your own endpoints as well as those from built-in services.

To add CORS behavior to endpoints, you make minimal changes in how you set up the routing for those endpoints.
Using a simple API, provided by the Helidon SE CORS module,
you define the CORS behavior you want and then include that behavior as you build the routing rules for the services
in your application.

The <<se/cors/02_using-the-api.adoc,Using the API>> section explores in detail how to incorporate
CORS into the routing for the endpoints in your application.

== Adding Configuration
The API gives you everything you need to add CORS support to your resources, but you can use the API in combination with
configuration. Doing so simplifies your application code by moving some of the CORS-related routing set-up out of
procedural Java code into declarative configuration.

Incorporating configuration in this way also lets you add a powerful feature
to your app, whereby those who deploy your application can override the CORS behavior which the application
code sets up.
Deployers can modify the configuration to alter the CORS behavior of your the endpoints in your application
without requiring any changes to the application code.

The <<se/cors/03_using-configuration.adoc,Using Configuration>> section explains how to use configuration
with the Helidon CORS API.

== Controlling CORS for Built-in Services
The health, metrics, and OpenAPI built-in services have integrated CORS support.
If you include these services in your application's routing rules and do nothing else, then
those services will share their resources across all origins.

These services have the override feature described above.
By writing your application to use configuration as it prepares the routing for those
services, you let your users
control the CORS behavior of the built-in services through configuration.

You can take advantage of this feature of the built-in services even if you do not add CORS behavior
to your own endpoints.

The <<se/cors/04_support-in-builtin-services.adoc,Using Built-in Services>> section describes how your application can
use configuration in defining the routing for built-in services, and it shows how to implement this override feature.

