///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Using CORS in Built-in Services
:toc:
:toc-placement: preamble
:h1Prefix: SE
:description: Helidon SE CORS Support in Built-in Services
:keywords: helidon, java, cors, se, services
:flavor-uc: SE
:flavor-lc: se
:rootdir: {docdir}/../..

include::{rootdir}/includes/attributes.adoc[]

Several built-in Helidon services -- health, metrics, and OpenAPI -- have integrated CORS support.
You can include these services in your application and control their CORS behavior.

include::{rootdir}/includes/cors/cors-common.adoc[tag=understanding-cors-support-in-services]
include::{rootdir}/includes/cors/cors-common.adoc[tag=builtin-getting-started]

== Controlling CORS for Built-in Services Using the API
Although services such as health, metrics, and OpenAPI are built into Helidon, to use them your application must create
instances of the services and then use those instances in building your application's routing rules.

Recall that each
service type has a `Builder` class. To control the CORS behavior of a built-in service using the API, follow these steps:

. Create a `Builder` for the type of service of interest.

. Build an instance of `CrossOriginConfig` with the settings you want.

. Invoke the `builder.crossOriginConfig` method, passing that `CrossOriginConfig` instance.

. Invoke the builder's `build` method to initialize the service instance.

. Use the service instance in preparing the routing rules.

The following excerpt shows changes to the
link:{helidon-github-tree-url}/examples/quickstarts/helidon-quickstart-se[Helidon SE QuickStart example] which limit
sharing of the `/metrics` endpoint to `\http://foo.com`.
[source,java]
----
private static Routing createRouting(Config config) {

        CrossOriginConfig.Builder metricsCrossOriginConfigBuilder = CrossOriginConfig.builder() // <1>
                .allowOrigins("http://foo.com");
        RestServiceSettings.Builder restServiceSettingsBuilder = RestServiceSettings.builder()
                 .crossOriginConfig(metricsCrossOriginConfigBuilder); // <2>
        MetricsSupport metrics = MetricsSupport.builder()
                .restServiceSettings(restServiceSettingsBuilder) // <3>
                .build();
        GreetService greetService = new GreetService(config);
        HealthSupport health = HealthSupport.builder()
                .addLiveness(HealthChecks.healthChecks())   // Adds a convenient set of checks
                .build();

        return Routing.builder()
                .register(health)                   // Health at "/health"
                .register(metrics)                  // Metrics at "/metrics" // <4>
                .register("/greet", greetService)
                .build();
    }
----
<1> Create the `CrossOriginConfig.Builder` for metrics, limiting sharing to `\http://foo.com`.
<2> Use the `CrossOriginConfig.Builder` instance in constructing
the `RestServiceSetting.Builder` (which assigns common settings such as the CORS configuration and the web context for the service endpoint).
<3> Use the `RestServiceSetting.Builder` in preparing the `MetricsSupport` service.
<4> Use the `MetricsSupport` object in creating the routing rules.

include::{rootdir}/includes/cors/cors-common.adoc[tag=configuring-cors-for-builtin-services]

include::{rootdir}/includes/cors/cors-common.adoc[tag=accessing-shared-resources-intro]

[source,bash]
----
mvn package
java -jar target/helidon-quickstart-se.jar
----

[source, listing]
----
WEB server is up! http://localhost:8080/greet
----

include::{rootdir}/includes/cors/cors-common.adoc[tag=accessing-shared-resources-main]
