///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////


= Oracle WebLogic Server 
:description: Helidon Oracle WebLogic Server Integration
:keywords: wls, jms, rest, single sign-on, sso, microtx, web services
:feature-name: Oracle WebLogic Server Integration Integration
:rootdir: {docdir}/../..

:wls-version: 14.1.1.0
// TODO: Change the link! This is UAT!
:wls-root-url: https://docs-uat.us.oracle.com/en/middleware/standalone/weblogic-server/{wls-version}

:wls-jaxrs-url: {wls-root-url}/restf/develop-restful-service.html#GUID-8C2E2918-B157-49BE-8BCA-125C87E4B3E3
:wls-jaxrs-link: {wls-jaxrs-url}[Developing and Securing RESTful Web Services for Oracle WebLogic Server]

:wls-jaxrs-client-url: {wls-root-url}/restf/develop-restful-client.html#GUID-F50F4FB3-8A25-439F-8554-484F1C58315C
:wls-jaxrs-client-link: {wls-jaxrs-url}[Developing RESTful Web Service Clients for Oracle WebLogic Server]

:wls-jms-url: {wls-root-url}/wlshe/integrating-oracle-weblogic-server-jms-helidon.html#GUID-431439D4-F2F0-4D89-8A65-287A822BA83D
:wls-jms-link: {wls-jms-url}[Integrating WebLogic JMS with Helidon]

:wls-soap-url: {wls-root-url}/wlshe/integrating-oracle-weblogic-server-web-services-helidon.html#GUID-DA893D15-13CB-49AF-AD5B-43FD716618BB
:wls-soap-link: {wls-jms-url}[Integrating Oracle WebLogic Server Web Services with Helidon]

:wls-sso-url: {wls-root-url}/wlshe/integrating-oracle-weblogic-and-helidon-sso-oci.html#GUID-D54EE368-0D7F-4DBB-9279-CC5BDDB76725
:wls-sso-link: {wls-sso-url}[Integrating Oracle WebLogic Cluster and Helidon Applications for SSO on OCI Using IDCS]

:osdc-url: https://edelivery.oracle.com/osdc/faces/Home.jspx
:osdc-link: {osdc-url}[Oracle Software Delivery Cloud]

:jersey-url: https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest
:jersey-link: {jersey-url}[Eclipse Jersey]

include::{rootdir}/includes/mp.adoc[]

== Contents

- <<Overview, Overview>>
- <<REST Services Integration, REST Services Integration>>
- <<JMS Integration, JMS Integration>>
- <<Web Services Integration, Web Services Integration>>
- <<Single Sign-On on OCI Integration, Single Sign-On on OCI Integration>>

== Overview

Integration between Helidon and Oracle Weblogic Server is possible over numerous protocols, most notably RESTful web services,
SOAP web services and JMS. Both Helidon and Oracle Weblogic Server supports Single Sign-on (SSO) authentication using Oracle Identity Cloud Service (IDCS).

== REST Services Integration [[REST-Services]]

- <<REST-Services-Overview, Overview>>
- <<REST-Server, JAX-RS Server>>
- <<REST-Client, JAX-RS Client>>
- <<REST-Services-References, References>>

=== Overview [[REST-Services-Overview]]
RESTful integration between Oracle Weblogic Server and Helidon MP is easy to develop and maintain because
both runtimes supports JAX-RS for serving and calling RESTful resources.
Thanks to the Jakarata EE compliance you can create same RESTful resource or client which will work in both environments.

Main difference in usage of JAX-RS between Helidon and Oracle Weblogic Server is caused by the version of the supported Jakarta specification.
While Oracle Weblogic Server supports Jakarta EE 8, Helidon supports JAX-RS or newly Jakarta RESTful Web Services from Jakarta EE 9.1.
Most notable difference between those two versions of Jakarta EE is the package name change, where `javax` has been replaced with `jakarta`.

[source, java]
.Helidon JAX-RS imports
----
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.Context;
import jakarta.ws.rs.core.MediaType;
----

While imports from `jakarta` namespace needs to be used in Helidon,
for Oracle Weblogic Server `javax` needs to be used for the same JAX-RS code.

[source, java]
.Oracle Weblogic Server JAX-RS imports
----
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
----

=== JAX-RS Server [[REST-Server]]
JAX-RS resource is a simple bean with annotated methods representing routes, HTTP methods under specific path.
Annotated methods are invoked when particular REST endpoint is called. All the mapping and routing is done by
actual implementation of JAX-RS standard according the JAX-RS annotations.

[source,java]
.JAX-RS example resource
----
@Path("/greet")//<1>
public class GreetResource {

    @Path("/hello")
    @GET //<2>
    @Produces(MediaType.TEXT_PLAIN) //<3>
    public Response getHello() {
        return Response.ok("Hello World!") //<4>
                       .build();
    }
}
----
<1> Path of the resource
<2> HTTP method
<3> Expected response content type
<4> Returning text payload with status 200

JAX-RS is very powerful tool where you can register your own message body writers, readers, filters or exception mappers.
In both, Helidon and Oracle Weblogic Server, is {jersey-link} used as an JAX-RS implementation.

For further reading on how to create and deploy JAX-RS RESTful resources in Helidon continue to xref:../../mp/jaxrs/jaxrs-applications.adoc[JAX-RS applications.]
For developing and deploying JAX-RS resources on Oracle Weblogic Server follow {wls-jaxrs-link} documentation.

=== JAX-RS Client [[REST-Client]]

JAX-RS provides convenient client API for calling RESTful resources.
Client allows you to prepare and execute RESTful request call with a simple builder pattern API.

[source,java]
.JAX-RS client example
----
Client client = ClientBuilder.newClient();
String res = client
    .target("http://localhost:8080") //<1>
    .path("/greet") //<2>
    .request("text/plain") // <3>
    .get(String.class); // <4> <5>
----
<1> Creates new WebTarget with default root url
<2> Prepare request to particular context path
<3> Set expected response content type
<4> Execute GET request and block until response is received
<5> Parameter sets expected response payload type, available body readers are used for parsing to the correct type

Again you can register your own message body writers, readers, filters or exception mappers.

For further reading on how to create JAX-RS clients in Helidon continue to xref:../../mp/jaxrs/jaxrs-client.adoc[JAX-RS client.]
For developing and deploying JAX-RS clients on Oracle Weblogic Server follow {wls-jaxrs-client-link} documentation.

=== References [[REST-Services-References]]
* xref:../../mp/introduction/microprofile.adoc[Helidon MP Tutorial]
* xref:../../mp/guides/quickstart.adoc[Helidon MP Quickstart]
* {wls-jaxrs-link}
* {wls-jaxrs-client-link}
* {jersey-link}

== JMS Integration [[JMS-Integration]]

- <<JMS-Integration-Overview, Overview>>
- <<JMS-Integration-Maven-Coordinates, Maven Coordinates>>
- <<JMS-Integration-Usage, Usage>>
- <<JMS-Integration-Examples, Examples>>
- <<JMS-Integration-References, References>>

=== Overview [[JMS-Integration-Overview]]

The integration of the Oracle WebLogic Server Java Message Service (JMS) with Helidon enables Oracle WebLogic Server applications and Helidon microservices to communicate through messaging, in one or both directions.

=== Maven Coordinates [[JMS-Integration-Maven-Coordinates]]

To enable Oracle WebLogic Server JMS  with Helidon, add the following dependencies to your project’s `pom.xml` file:

*Dependency for Reactive Messaging*
[source,xml]
----
<dependency>
   <groupId>io.helidon.microprofile.messaging</groupId>
   <artifactId>helidon-microprofile-messaging</artifactId>
</dependency>
----
*Dependency for JMS connector*
[source,xml]
----
<dependency>
    <groupId>io.helidon.messaging.jms</groupId>
    <artifactId>helidon-messaging-jms</artifactId>
</dependency>
----

*Dependencies for the WLS thin client JAR file*
Download the jakarta thin client JAR (`wlthint3client.jakarta`) file from https://edelivery.oracle.com/osdc/faces/Home.jspx[Oracle Software Delivery Cloud], and add it as part of the Maven dependencies:
[source,xml]
----
<dependency>
    <groupId>wlthint3client.jakarta</groupId>
    <artifactId>wlthint3client-jakarta</artifactId>
    <version>1.0</version>
</dependency>
----

=== Usage [[JMS-Integration-Usage]]

After adding the Maven dependencies, configure the Helidon JMS connector including the JMS environment properties and the JMS resources such as the connection factory, destination, and destination type.

After you have configured the Helidon JMS connector, add the Java code to send and receive messages to and from Oracle WebLogic Server.

Sample method to consume a message from the JMS channel:
[source, java]
----
@Incoming("from-wls-q")
public void receive(String msg) {
    System.out.println("Process JMS message as per business logic" + msg);
}
----

Sample method to produce messages to the JMS channel:
[source, java]
----
@Outgoing("to-wls-q")
public PublisherBuilder<String> produceToJms() {
    return ReactiveStreams.of("test1", "test2");
}
----

For more information about this integration, see {wls-jms-link}

=== Examples [[JMS-Integration-Examples]]
The following example shows the helidon-jms connector configurations added to the `application.yaml` file.

[source, yaml]
----
# User-defined properties
wls-username: weblogic
wls-password: welcome1
# WLS Admin server t3 connection URL
wls-admin-url: t3://localhost:7001
# WLS Cluster t3 connection URL
wls-cluster-url: t3://localhost:7003,localhost:7005,localhost:7007
 
mp:
  messaging:
    connector:
      helidon-jms:
        jndi:
           #Default connection factory name. This can be overridden in individual resource configurations
           jms-factory: qcf
           #JMS environment properties to lookup resources
           env-properties:
              java.naming.factory.initial: weblogic.jndi.WLInitialContextFactory
              java.naming.provider.url: ${wls-admin-url}
              java.naming.security.principal: ${wls-username}
              java.naming.security.credentials: ${wls-password}
 
    # Add all consumer resources-related configurations below incoming 
    incoming:
      #Identifier "from-wls-q" is used with @Incoming annotation
      from-wls-q:
        #Connector Name as specific in connector section. It is predefined
        connector: helidon-jms
        #JMS Destination Name in JNDI format
        jndi.destination: queuejndi
        #JMS Destination Type
        type: queue
        #JMS Connection Factory 
        jndi.jms-factory: qcf
 
    # Add all producer resources-related configurations below outgoing 
    outgoing:
      #Identifier "to-wls-q" is used with @Outgoing annotation
      to-wls-q:
        connector: helidon-jms
        jndi.destination: queuejndi
        type: queue
        jndi.jms-factory: qcf
----


=== References [[JMS-Integration-References]]

* xref:../../mp/reactivemessaging/jms.adoc[JMS Connector]
* {wls-jms-link}

== Web Services Integration [[Web-Services-Integration]]

- <<Web-Services-Integration-Overview, Overview>>
- <<Web-Services-Integration-Maven-Coordinates, Maven Coordinates>>
- <<Web-Services-Integration-Usage, Usage>>
- <<Web-Services-Integration-Example, Example>>
- <<Web-Services-Integration-References, References>>

=== Overview [[Web-Services-Integration-Overview]]

Helion MP and WebLogic Server Web Services integration enables the Helidon microservice application to communicate with the WebLogic Web Service deployed in Oracle WebLogic Server.

=== Maven Coordinates [[Web-Services-Integration-Maven-Coordinates]]

Add the `com.oracle.webservices.wls.jaxws-wlswss-client.jar` client file downloaded from {osdc-link}, as part of the Maven dependencies:
[source, xml]
----
<dependency>
    <groupId>com.oracle.webservices.wls.jaxws-wlswss-client</groupId>
    <artifactId>com.oracle.webservices.wls.jaxws-wlswss-client</artifactId>
    <version>1.0</version>
</dependency>
----

=== Usage [[Web-Services-Integration-Usage]]

Use the `clientgen` WebLogic web services Ant task by using the `com.oracle.webservices.wls.jaxws-wlswss-client.jar` file, installed earlier, to generate the *jakarta* based client artifacts that client applications use to invoke the WebLogic web services. Add a call to the `clientgen` Ant task, as shown in the following example:
[source, xml]
----
<target>
    <path id="lib.clientgen.id">  
        <pathelement path="${jaxws.client.jar}"/>  
    </path> 
 
    <taskdef name="clientgen" classname="weblogic.wsee.tools.anttasks.ClientGenTask" classpathref="lib.clientgen.id"/>
    <clientgen wsdl="${remote.wsdl.location}" wsdlLocation="${remote.wsdl.location}"
       destDir="${project.basedir}/target/classes" packageName="examples.webservices.simple_client"
       type="JAXWS" copyWsdl="true" />
</target>
----

=== Example [[Web-Services-Integration-Example]]

You can create the RESTful web service to invoke the WebLogic Web Service, as shown in the example below:
[source, java]
----
@Path("/helidonclient")
@ApplicationScoped
public class HelidonWSEEClient {
 
    private JsonBuilderFactory JSON = Json.createBuilderFactory(Collections.emptyMap());
 
    @GET
    @Path("/getWLSWebserviceResult/subtract/{y}/from/{x}")
    @Produces(MediaType.APPLICATION_JSON)
    public JsonObject invokeWLSWebservice(@PathParam("x") int x, @PathParam("y") int y) {
 
        String wsdlLocation = System.getProperty("remote.wsdl.location");
        DynamicWSImplService testService = new DynamicWSImplService();
        DynamicWSImpl testPort = testService.getDynamicWSImplPort();
        BindingProvider binding = (BindingProvider) testPort;
        binding.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, wsdlLocation);
        int response = testPort.subtract(x,y);
 
        return JSON.createObjectBuilder().add("wsresponse", response).build();
   }
}
----

=== References [[Web-Services-Integration-References]]

* {wls-soap-link}

== Single Sign-On on OCI Integration [[SSO-Integration]]

- <<SSO-Integration-Overview, Overview>>
- <<SSO-Integration-Maven-Coordinates, Maven Coordinates>>
- <<SSO-Integration-Usage, Usage>>
- <<SSO-Integration-References, References>>

=== Overview [[SSO-Integration-Overview]]

The Oracle WebLogic Server and Helidon integration on OKE enables SSO authentication to: 

* Access the IDCS configured client application deployed on Oracle WebLogic cluster.
* Access the Helidon REST endpoints configured with IDCS.
* Access the WebLogic application endpoints from the Helidon REST endpoints.

=== Maven Coordinates [[SSO-Integration-Maven-Coordinates]]

To enable this integration, add the Maven dependency to the `pom.xml` file, as shown in the following example:
[source, xml]
----
<dependency>
  <groupId>io.helidon.microprofile</groupId>
   <artifactId>helidon-microprofile-security</artifactId>
</dependency>
<dependency>
  <groupId>io.helidon.microprofile</groupId>
  <artifactId>helidon-microprofile-oidc</artifactId>
</dependency>
----

=== Usage [[SSO-Integration-Usage]]

To set up the integration, you should integrate the WebLogic cluster applications and the Helidon 3.x application with Oracle Identity Cloud Service (IDCS). For more information about these integrations, see https://docs-uat.us.oracle.com/en/middleware/standalone/weblogic-server/14.1.1.0/wlshe/integrating-oracle-weblogic-and-helidon-sso-oci.html#GUID-94C760CC-9874-48A7-AD59-DA3108FB36C8[Integrating Oracle WebLogic Cluster and Helidon 3.x for SSO].

Then, access the WebLogic cluster application endpoint from the Helidon REST endpoints by adding the following snippet in the Helidon source code:
[source, java]
----
@Authenticated
@GET
@Produces (MediaType.APPLICATION_JSON)
public JsonObject getDefaultMessage() {
  // Get access token using WebLogic application registered at IDCS client id and secret.
  // Use token to access to WebLogic application SSO endpoints
}
----
Use the IDCS *Client ID* and *Client Secret* of the WebLogic cluster application to obtain the access token to access the WebLogic cluster application SSO points.

[source, java]
----
Client client = ClientBuilder.newClient();
WebTarget target = client.target(WLS_TOKEN_SERVICE_URL);
String scope = new StringJoiner(" ")
        .add(WLS_QUOTE_APP_SCOPE)
        .add(WLS_PIPELINE_APP_SCOPE)
        .add(WLS_INSIGHT_APP_SCOPE)
        .add(WLS_REPORT_APP_SCOPE)
        .toString();
Form form = new Form()
        .param("grant_type", "client_credentials")
        .param("client_id", WLS_IDCS_CLIENT_ID)
        .param("client_secret", WLS_IDCS_CLIENT_SECRET)
        .param("scope", scope);
String token = target
        .request(MediaType.APPLICATION_JSON_TYPE)
        .post(Entity.entity(form, MediaType.APPLICATION_FORM_URLENCODED_TYPE), JsonObject.class)
        .getString("access_token");
----

Access the Helidon SSO REST endpoint to verify the integration between Helidon 3.x application and the WebLogic cluster application. After a successful SSO authentication at the Helidon REST endpoint, you will be able to access the WebLogic cluster application.

=== References [[SSO-Integration-References]]

* xref:../../mp/security/providers.adoc[Security Providers]
* xref:../../mp/security/providers.adoc#OIDC-Provider[OIDC Provider]
* {wls-soap-link}





