caching:
  providers:
  - type: "coherence"
    properties:
      cluster-name: "Helidon"
  caches:
  - name: "simple-cache"
    type: "memory"
    properties:
      capacity: 2
  - name: "loader-cache"
    type: "memory"
    properties:
      capacity: 2
  - name: "sample"
    type: "coherence"

server:
  port: 8080