/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.webserver.observe.telemetry.metrics;

import java.util.List;

/**
 * Mostly generated by Oracle generative chat.
 */
public final class MetricsExportImpl implements MetricsExport {
    private final List<MetricsEnvelope> resourceMetrics;

    public MetricsExportImpl(List<MetricsEnvelope> resourceMetrics) {
        this.resourceMetrics = resourceMetrics == null ? List.of() : List.copyOf(resourceMetrics);
    }

    @Override
    public List<MetricsEnvelope> resourceMetrics() {
        return resourceMetrics;
    }
}