/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.webserver.observe.telemetry.metrics;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Models either:
 *  - a single ResourceMetrics JSON object (your log line), OR
 *  - items inside the wrapped ExportMetricsServiceRequest.resourceMetrics[].
 *  <p>
 *  Mostly generated by Oracle generative chat.
 *
 */
public interface MetricsEnvelope {
    Resource resource();
    List<ScopeMetrics> scopeMetrics();

    interface Resource {
        Map<String, AnyValue> attributes();
    }

    interface ScopeMetrics {
        InstrumentationScope scope();
        List<Metric> metrics();
    }

    interface InstrumentationScope {
        String name();
        Map<String, AnyValue> attributes();
    }

    interface Metric {
        String name();
        String description();
        String unit();
        Histogram histogram(); // nullable if absent
    }

    interface Histogram {
        Integer aggregationTemporality(); // e.g., 2
        List<HistogramDataPoint> dataPoints();
    }

    interface HistogramDataPoint {
        String startTimeUnixNano();
        String timeUnixNano();
        Integer count();
        Double sum();
        Double min();
        Double max();
        List<String> bucketCounts();
        List<Double> explicitBounds();
        Map<String, AnyValue> attributes();
    }


    interface AnyValue {
        Optional<String> asString();
        Optional<Long> asLong();
        Optional<Double> asDouble();
        Optional<Boolean> asBoolean();
        Map<String, Object> raw();
    }
}

