///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:toc:
:toc-placement: preamble
:description: Scheduling in Helidon MP
:keywords: helidon, mp, scheduling
:h1Prefix: MP

== Scheduling
For scheduling tasks in Helidon you can choose from @Scheduled or @FixedRate annotations by required complexity of invocation interval. All you need is define method with one of the annotations in application scoped bean.

[source,xml]
.Dependency for Scheduling feature
----
<dependency>
    <groupId>io.helidon.microprofile.scheduling</groupId>
    <artifactId>helidon-microprofile-scheduling</artifactId>
</dependency>
----


=== Fixed rate
For simple fixed rate invocation interval is @FixedRate the easiest way for scheduling
task invocation.

[source,java]
.Example of scheduling with fixed rate
----
@FixedRate(initialDelay = 5, value = 10, timeUnit = TimeUnit.MINUTES)
public void methodName() {
    System.out.println("Every 10 minutes, first invocation 5 minutes after start");
}
----

All values defined with the annotation can be overridden from the config.

[source,yaml]
.Overiding annotated values from config
----
fully.quallified.ClassName.methodName:
  schedule:
    initial-delay: 5
    delay: 15
    time-unit: HOURS
----

Metadata like human-readable interval description or configured values are available through
FixedRateInvocation injected as method parameter.

[source,java]
.Example with ivocation metadata
----
@FixedRate(initialDelay = 5, value = 10, timeUnit = TimeUnit.MINUTES)
public void methodName(FixedRateInvocation inv) {
    System.out.println("Method invoked " + inv.description());
}
----

=== Cron expression

For more complicated interval definition, cron expression can be leveraged with
@Schedule annotation.

[source,java]
.Example of scheduling with cron expression
----
@Scheduled("0 15 8 ? * *")
public void methodName() {
    System.out.println("Executer every day at 8:15");
}
----

include::../../shared/scheduling/01_cron.adoc[lines=19..]

Metadata like human-readable interval description or configured values are available through
CronInvocation injected as method parameter.

[source,java]
.Example with ivocation metadata
----
@Scheduled("0 15 8 ? * *")
public void methodName(CronInvocation inv) {
    System.out.println("Method invoked " + inv.description());
}
----