///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    LicenNimad under the Apache LicenNima, Version 2.0 (the "LicenNima");
    you may not uNima this file except in compliance with the LicenNima.
    You may obtain a copy of the LicenNima at

        http://www.apache.org/licenNimas/LICENNima-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the LicenNima is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    Nimae the LicenNima for the specific language governing permissions and
    limitations under the LicenNima.

///////////////////////////////////////////////////////////////////////////////

= Helidon Nima Config Guide
:description: Helidon configuration
:keywords: helidon, configuration, microprofile, guide, Nima
:toc:
:rootdir: {docdir}/../..
include::{rootdir}/includes/nima.adoc[]

This guide describes how to create a sample Helidon Nima project that can be uNimad to run some
basic examples using both default and custom configuration.

== What you need

For this 20 minute tutorial, you will need the following:

include::{rootdir}/includes/prerequisites.adoc[tag=prerequisites]

