///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Health Checks
:h1Prefix: SE
:description: Helidon health checks
:keywords: helidon, health checks, health, check
:javadoc-base-url-api: {javadoc-base-url}io.helidon.health.checks/io/helidon/health/checks
:feature-name: Health Checks
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc

== ToC

- Overview
- Maven
- Usage
- API
- Configuration
- Reference
- Examples
- Additional Information

== Overview

TODO: extend
This document describes the health check API available with Helidon SE.

include::{common-deps-page-prefix-inc}[tag=maven-dependency]

[source,xml]
----
<dependency>
    <groupId>io.helidon.health</groupId>
    <artifactId>helidon-health</artifactId>
</dependency>
----

Optional dependency to use built-in health checks:

[source,xml]
----
<dependency>
    <groupId>io.helidon.health</groupId>
    <artifactId>helidon-health-checks</artifactId>
</dependency>
----

== Usage

=== About health checks

It’s a good practice to monitor your microservice’s health, to ensure that it is
 available and performs correctly.

Applications implement health checks to expose health status that is collected
 at regular intervals by external tooling, such as orchestrators like
 Kubernetes. The orchestrator may then take action, such as restarting your
 application if the health check fails.

A typical health check combines the statuses of all the dependencies that
 affect availability and the ability to perform correctly:

* network latency
* storage
* database
* other services used by your application


== API

[cols="4,6"]
.Health check API classes
|=======
| `org.eclipse.microprofile.health.HealthCheck`
| Java functional interface representing the logic of a single health check

| `org.eclipse.microprofile.health.HealthCheckResponse`
| Result of a health check invocation that contains a status and a description.

| `org.eclipse.microprofile.health.HealthCheckResponseBuilder`
| Builder class to create `HealthCheckResponse` instances

| `io.helidon.health.HealthSupport`
| WebServer service that exposes `/health` and invokes the registered health
 checks

| `io.helidon.health.HealthSupport.Builder`
| Builder class to create `HealthSupport` instances
|=======

A health check is a Java functional interface that returns a
 `HealthCheckResponse` object. You can choose to implement a health check
 inline with a lambda expression or you can reference a method with the double
 colon operator `::`.

[source,java]
.Health check with a lambda expression:
----
HealthCheck hc = () -> HealthCheckResponse
        .named("exampleHealthCheck")
        .up()
        .build();
----

[source,java]
.Health check with method reference:
----
HealthCheckResponse exampleHealthCheck(){
    return HealthCheckResponse
        .named("exampleHealthCheck")
        .up()
        .build();
}
HealthCheck hc = this::exampleHealthCheck;
----

`HealthSupport` is a WebServer service that contains a collection of
 registered `HealthCheck` instances. When queried, it invokes the registered
 health check and returns a response with a status code representing the overall
 status of the application.

[cols="1,5",role="flex, sm7"]
.Health status codes
|=======
| `200` | The application is healthy (with health check details in the response).
| `204` | The application is healthy (with _no_ health check details in the response).
| `503` | The application is not healthy.
| `500` | An error occurred while reporting the health.
|=======

HTTP `GET` responses include JSON content showing the detailed results of all the health checks which the server executed after receiving the request.
HTTP `HEAD` requests return only the status with no payload.


== Configuration

TODO:

== Reference

TODO:

== Examples


[source,java]
.Create the health support service:
----
HealthSupport health = HealthSupport.builder()
    .addLiveness(hc)
    .build();
----

[source,java]
.Register a custom health check:
----
HealthSupport health = HealthSupport.builder()
    .addLiveness(() -> HealthCheckResponse.named("exampleHealthCheck")
                 .up()
                 .withData("time", System.currentTimeMillis())
                 .build()) // <.>
    .build();

Routing.builder()
        .register(health) // <.>
        .build();
----
<.> Add a custom health check. This example returns `UP` and current time.
<.> Register health support with web server routing (adds the `/health`
endpoint).

TIP: Balance collecting a lot of information with the need to avoid overloading
the application and overwhelming users.

[source,json]
.JSON response:
----
{
    "status": "UP",
    "checks": [
        {
            "name": "exampleHealthCheck",
            "status": "UP",
            "data": {
                "time": 1546958376613
            }
        }
    ]
}
----

== Additional Information

=== Built-in health checks

You can use Helidon-provided health checks to report various
 common health check statuses:

[[built-in-health-checks-table]]
[cols="1,1,3,15,3"]
|=======
|Built-in health check |Health check name |JavaDoc |Config properties |Default config value

|deadlock detection
|`deadlock`
| link:{javadoc-base-url-api}/DeadlockHealthCheck.html[`DeadlockHealthCheck`]
| n/a
| n/a

|available disk space
|`diskSpace`
| link:{javadoc-base-url-api}/DiskSpaceHealthCheck.html[`DiskSpaceHealthCheck`]
|`helidon.healthCheck.diskSpace.thresholdPercent` +
 +
`helidon.healthCheck.diskSpace.path`
| `99.999` +
 +
`/`
|available heap memory
| `heapMemory`
| link:{javadoc-base-url-api}/HeapMemoryHealthCheck.html[`HeapMemoryHealthCheck`]
|`helidon.healthCheck.heapMemory.thresholdPercent`
|`98`
|=======

The following code adds the default built-in health checks to your application:

[source,java]
----
HealthSupport health = HealthSupport.builder()
    .addLiveness(HealthChecks.healthChecks()) // <.>
    .build();

Routing.builder()
        .register(health) // <.>
        .build();
----
<.> Add built-in health checks using defaults (requires the `helidon-health-checks`
 dependency).
<.> Register the created health support with web server routing (adds the 
`/health` endpoint).

You can control the thresholds for built-in health checks in either of two ways:

* Create the health checks individually
using their builders instead of using the `HealthChecks` convenience class.
Follow the JavaDoc links in the <<built-in-health-checks-table,table>> above.

* Configure the behavior of the built-in health checks using the config property keys in the
<<built-in-health-checks-table,table>>.

Further, you can suppress one or more of the built-in health checks by setting the configuration item
`helidon.health.exclude` to a comma-separated list of the health check names
(from the <<built-in-health-checks-table,table>>) you want to exclude.

== Health report
Accessing the Helidon-provided `/health` endpoint reports the health of your application:
[source,json]
.JSON response.
----
{
    "status": "UP",
    "checks": [
        {
            "name": "deadlock",
            "status": "UP"
        },
        {
            "name": "diskSpace",
            "status": "UP",
            "data": {
                "free": "211.00 GB",
                "freeBytes": 226563444736,
                "percentFree": "45.31%",
                "total": "465.72 GB",
                "totalBytes": 500068036608
            }
        },
        {
            "name": "heapMemory",
            "status": "UP",
            "data": {
                "free": "215.15 MB",
                "freeBytes": 225600496,
                "max": "3.56 GB",
                "maxBytes": 3817865216,
                "percentFree": "99.17%",
                "total": "245.50 MB",
                "totalBytes": 257425408
            }
        }
    ]
}
----


=== About Kubernetes probes

Probes is the term used by Kubernetes to describe health checks for containers
(link:{kubernetes-probes-url}[Kubernetes documentation]).

There are three types of probes:

* _liveness_: Indicates whether the container is running
* _readiness_: Indicates whether the container is ready to service requests
* _startup_: Indicates whether the application in the container has started

You can implement probes using the following mechanisms:

. Running a command inside a container
. Sending an `HTTP` request to a container
. Opening a `TCP` socket to a container

A microservice exposed to HTTP traffic will typically implement both the
liveness probe and the readiness probe using HTTP requests.
If the microservice takes a significant time to initialize itself, you can also define a startup probe, in which case
Kubernetes does not check liveness or readiness probes until the startup probe returns success.

You can configure several parameters for probes. The following are the most
relevant parameters:

[cols="2,5",role="flex, sm7"]
|=======
| `initialDelaySeconds`
| Number of seconds after the container has started before liveness or readiness
probes are initiated.

| `periodSeconds`
| Probe interval. Default to 10 seconds. Minimum value is 1.

| `timeoutSeconds`
| Number of seconds after which the probe times out. Defaults to 1 second.
Minimum value is 1

| `failureThreshold`
| Number of consecutive failures after which the probe should stop. Default: 3.
Minimum: 1.
|=======

==== Liveness probe

The liveness probe is used to verify the container has become unresponsive.
For example, it can be used to detect deadlocks or analyze heap usage. When
Kubernetes gives up on a liveness probe, the corresponding pod is restarted.

NOTE: The liveness probe can result in repeated restarts in certain cases.
For example, if the probe is implemented to check all the dependencies
strictly, then it can fail repeatedly for temporary issues. Repeated restarts
can also occur if `timeoutSeconds` or `periodSeconds` is too low.

We recommend the following:

* Avoid checking dependencies in a liveness probe.
* Set `timeoutSeconds` to avoid excessive probe failures.
* Acknowledge startup times with `initialDelaySeconds`.

==== Readiness probe

The readiness probe is used to avoid routing requests to the pod until it is
ready to accept traffic. When Kubernetes gives up on a readiness probe, the
pod is not restarted, traffic is not routed to the pod anymore.

NOTE: In certain cases, the readiness probe can cause all the pods to be removed
from service routing. For example, if the probe is implemented to check all the
dependencies strictly, then it can fail repeatedly for temporary issues. This
issue can also occur if `timeoutSeconds` or `periodSeconds` is too low.

We recommend the following:

* Be conservative when checking shared dependencies.
* Be aggressive when checking local dependencies.
* Set `failureThreshold` according to `periodSeconds` in order to accommodate
temporary errors.

==== Startup probe

The startup probe prevents Kubernetes from prematurely checking the other probes if the application takes a long time to start.
Otherwise, Kubernetes might misinterpret a failed liveness or readiness probe and shut down the container when, in fact, the application is still coming up.


=== Troubleshooting probes

Failed probes are recorded as events associated with their corresponding pods.
The event message contains only the status code.

[source,bash]
.Get the events of a single pod:
----
POD_NAME=$(kubectl get pod -l app=acme -o jsonpath='{.items[0].metadata.name}') # <1>
kubectl get event --field-selector involvedObject.name=${POD_NAME} # <2>
----
<1> Get the effective pod name by filtering pods with the label `app=acme`.
<2> Filter the events for the pod.

TIP: Create log messages in your health check implementation when setting a
`DOWN` status. This will allow you to correlate the cause of a failed probe.

== Example

This example shows the usage of the Helidon health API in an application that
implements health endpoints for the liveness and readiness probes. Note that
the application code dissociates the health endpoints from the default routes,
so that the health endpoints are not exposed by the service. An example YAML
specification is also provided for the Kubernetes service and deployment.

[source,java]
.Application code:
----
Routing healthRouting = Routing.builder()
        .register(JsonSupport.create())
        .register(HealthSupport.builder()
                .webContext("/live") // <1>
                .addLiveness(HealthChecks.healthChecks()) // <2>
                .build())
        .register(HealthSupport.builder()
                .webContext("/ready") // <3>
                .addReadiness(() -> HealthCheckResponse.named("database").up().build()) // <4>
                .build())
        .build();

Routing defaultRouting = Routing.builder()
        .any((req, res) -> res.send("It works!")) // <5>
        .build();

WebServer server = WebServer.builder(defaultRouting)
        .config(ServerConfiguration.builder()
                .port(8080) // <6>
                .addSocket("health", SocketConfiguration.builder() // <7>
                        .port(8081)
                        .build())
                .build())
        .addNamedRouting("health", healthRouting) // <8>
        .build();

server.start();
----
<1> The health service for the `liveness` probe is exposed at `/live`.
<2> Using the built-in health checks for the `liveness` probe.
<3> The health service for the `readiness` probe is exposed at `/ready`.
<4> Using a custom health check for a pseudo database that is always `UP`.
<5> The default route: returns It works! for any request.
<6> The server uses port 8080 for the default routes.
<7> A socket configuration named `health` using port `8081`.
<8> Route the health services exclusively on the `health` socket.

[source,yaml]
.Kubernetes descriptor:
----
kind: Service
apiVersion: v1
metadata:
  name: acme # <1>
  labels:
    app: acme
spec:
  type: NodePort
  selector:
    app: acme
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: acme # <2>
spec:
  replicas: 1
  template:
    metadata:
      name: acme
      labels:
        name: acme
    spec:
      containers:
      - name: acme
        image: acme
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /live # <3>
            port: 8081
          initialDelaySeconds: 3 # <4>
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready # <5>
            port: 8081
          initialDelaySeconds: 10 # <6>
          periodSeconds: 30
          timeoutSeconds: 10
---
----
<1> A service of type `NodePort` that serves the default routes on port `8080`.
<2> A deployment with one replica of a pod.
<3> The HTTP endpoint for the liveness probe.
<4> The liveness probe configuration.
<5> The HTTP endpoint for the readiness probe.
<6> The readiness probe configuration.
