#
# Copyright (c) 2026 Oracle and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM container-registry.oracle.com/java/openjdk:27-oraclelinux9@sha256:7477f4f5b0deebce818b5c918c9f0aa6eafb1342eb2ed54628ebbcd0a1dd7ada

WORKDIR /opt/helidon

COPY target/libs/ /opt/helidon/libs/

RUN mkdir -p /certs /www

ENTRYPOINT ["java", "-cp", "/opt/helidon/libs/*", "io.helidon.tests.integration.quic.interop.Main"]
