///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:description: Helidon documentation
:keywords: helidon, java, microservices, microprofile, documentation

== Get going

[PILLARS]
====
[CARD]
.Guides
[icon=explore,link=guides/01_overview.adoc]
--
Follow step-by-step guides to build your applications.
--

[CARD]
.Javadocs
[icon=library_books,link=apidocs/index.html?overview-summary.html,link-type=url]
--
Browse the Helidon Javadocs.
--
====

== Components

[PILLARS]
====
[CARD]
.WebServer
[icon=settings_ethernet,link=webserver/01_introduction.adoc]
--
A programmatic HTTP API with reactive features, powered by Netty.
--

[CARD]
.Config
[icon=settings,link=config/01_introduction.adoc]
--
A flexible configuration framework with support for multiple sources and
 formats.
--

[CARD]
.Security
[icon=security,link=security/01_introduction.adoc]
--
A tool-chain to handle authentication, authorization and context propagation.
--

[CARD]
.MicroProfile
[icon=widgets,link=microprofile/01_introduction.adoc]
--
A platform definition that is familiar to enterprise Java developers.
--

[CARD]
.Extensions
[icon=extension,link=extensions/01_overview.adoc]
--
A set of add-ons for your Helidon-based applications.
--

[CARD]
.Metrics
[icon=av_timer,link=metrics/01_metrics.adoc]
--
Instrumentation to expose metrics of your applications.
--

[CARD]
.Tracing
[icon=timeline,link=tracing/01_tracing.adoc]
--
Profile and monitor your applications across multiple services.
--

[CARD]
.Health Checks
[icon=favorite_outline,link=health/01_health.adoc]
--
Expose health statuses of your applications.
--

[CARD]
.OpenAPI
[icon=donut_large,link=openapi/01_openapi.adoc]
--
Support OpenAPI from your application.
--
====
