///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/../..]
ifndef::flavor-lc[:flavor-lc: se]
ifndef::flavor-uc[:flavor-lc: SE]
ifndef::se-flavor[:se-flavor: true]
ifndef::h1-prefix[:h1-prefix: SE]
:feature-name: metrics-capable components
:intro-project-name: {h1-prefix}
:chk: icon:check[]
:x: icon:times[]

// tag::preamble[]
== Contents

- <<Overview, Overview>>
- <<Usage, Usage>>
- <<Examples, Examples>>

== Overview
This document explains Helidon {h1-prefix} metrics-capable components and applications and describes how to create and control them.
// end::preamble[]

// tag::all-beginning-text[]

Think of Helidon metrics in several related but different parts:

=== APIs
* The Helidon metrics API
+
This API allows your code to register, look-up, remove, and update metrics using
the `RegistryFactory`, `MetricRegistry`, and individual metrics interfaces.
* The Helidon metrics REST service API
+
This API allows your code to set up and respond to the `/metrics` endpoint so clients can retreive metrics information.

=== Implementations of the APIs
* Implementations of the Helidon metrics API.
+
Helidon provides two--minimal and full-featured--and selects which one to use at runtime,
based on what components are present on the runtime path and whether metrics is configured to be enabled or disabled.
+
ifdef::mp-flavor[By default, Helidon MP services use the full-featured implementation.]
ifdef::se-flavor[You control which implementation your Helidon SE service uses by which dependency you add to your project.]
* Implementations of the Helidon metrics REST service API.
+
Helidon provides two--minimal and full-featured--and selects which one to use at runtime.
+
ifdef::mp-flavor[]
By default, Helidon MP apps which use metrics use the full-featured metrics REST service by default.
endif::[]
ifdef::se-flavor[]
Your Helidon SE app provides this feature (if at all) by explicitly using the `MetricsSupport` interface.
+
Most Helidon SE applications are web-based and their developers choose to expose the built-in metrics web service.
But by separating the parts of metrics this way,
Helidon allows non-web apps to work with metrics as well, just without the web service support.
endif::[]


As you plan and write Helidon components and applications,
you make some choices about exactly how your code will use metrics.
This document gives some background information,
describes each option and its effect, and provides some code examples.

== Usage
This section helps you decide how incorporate metrics into your software by describing the categories of metrics usage, explaining generally how Helidon implements metrics, and illustrating how to write the metrics-related code accordingly.

=== Categorizing Metrics Usage
We can place each Helidon component and Helidon application into one of three categories based on how it relies on metrics.
The type of module dictates the compile-time dependency you declare in the project `pom.xml`.

.Types of Metrics Usage
[cols="1,1,6"]
|===
|Registers, updates, removes metrics? |Refers to metrics values? |Category

|{x}
|{x}
|metrics-independent

|{chk}
|{x}
|metrics-capable

|{chk}
|{chk}
|metrics-dependent
|===

Whenever possible, if your component or application uses metrics, then write it as metrics-capable code.

=== Understanding the Two Metrics Implementations
Helidon provides two metrics implementations:

* _Full-featured_ metrics allows registering, removing, and updating metrics and observing metrics' changing values.
The `helidon-metrics` component contains full-featured metrics.
* _Minimal_ metrics supports registering, removing, and updating metrics.
The metrics objects provided by the minimal implementation are no-ops: their values never change.
The minimal implementation is part of the `helidon-metrics-api` component.

Any code compiled with `helidon-metrics-api` can assume that the runtime path will include the minimal implementation.

Both implementations support all the operations of the `RegistryFactory` and the `MetricRegistry`.
The full implementation provides fully-functional metrics instances (counters, timers, etc.).
In the minimal implementations, metrics do not update their values.

For Helidon to use the full implementation, two conditions must hold:

* The `helidon-metrics` component must be on the runtime path.
* Metrics must be enabled, using either a builder or configuration. (Enabled is the default.)

Otherwise, provided that the runtime path includes `helidon-metrics-api`, Helidon activates the minimal implementation.

=== Understanding the Two Metrics Service Implementations
Helidon includes two implementations of support for the metrics web service endpoint `/metrics`
(or whatever context value is configured).

The full-service implementation sends responses which describe the metadata and current values for the metrics registered in
metric registries. The `helidon-metrics` component contains this implementation.

The `helidon-metrics-service-api` component contains the API for the metrics web service support (the `MetricsSupport` interface) and also
a minimal implementation. This implementation simply responds with `404` and an explanatory message that metrics are disabled.

Any code compiled with `helidon-metrics-service-api` can assume that the runtime path will contain the minimal implementation.

Helidon activates the full implementation if the runtime path includes the full implementation _and_ metrics is configured as enabled;
Helidon uses the minimal implementation otherwise.

=== Enabling and Disabling Metrics
Using
ifeval::["{h1-prefix}" == "SE"]
either builder-style settings or
endif::[]
configuration, your component
ifeval::["{h1-prefix}" == "SE"]
or Helidon SE application
endif::[]
can let end users control
at runtime whether Helidon should use full-featured metrics.
If an end user sets `metrics.enabled` to `false`, then Helidon activates the minimal metrics and metrics service implementations
provided they are in the runtime path.

Further, users can set `component-name.metrics.enabled` to `false` which disables metrics for just that component
so long as the component was written to check that setting and act on it accordingly.

=== Designing and Writing Metrics-capable Applications and Components
Whoever packages and deploys your application or component can control what code will be on the runtime path and whether metrics
is enabled or not.
As a result, wherever possible, construct your modules which use metrics so that they do not make decisions based on the values of metrics;
that is, design them to be metrics-capable, _not_ metrics-dependent.
Doing so allows your code to operate regardless of whether the full-featured metrics implementation is active at runtime.

==== Declaring Dependencies
. Include this dependency:
+
[source,xml]
.Dependency for Helidon metrics API
----
<dependency>
    <groupId>io.helidon.metrics</groupId>
    <artifactId>helidon-metrics-api</artifactId>
</dependency>
----
This module defines the metrics API: `RegistryFactory`, `MetricRegistry`, and the various metrics themselves.

ifdef::se-flavor[]
. To permit the use of the built-in metrics web service support for the `/metrics` endpoint, add this dependency:
+
[source,xml]
.Dependency for metrics web service support
----
<dependency>
    <groupId>io.helidon.metrics</groupId>
    <artifactId>helidon-metrics-service-api</artifactId>
</dependency>
----
This module defines the metrics web service API: `MetricsSupport`.
+
Use the `MetricsSupport` interface from `helidon-metrics-service-api` in your SE app initialization code to create a service you can register with the web server. (See the example <<writing_SE,below>>.)
endif::[]
. Declare an explicit runtime dependency on the full-featured metrics
implementation:
+
[source,xml]
.Dependency for full metrics and metrics service implementations
----
<dependency>
    <groupId>io.helidon.metrics</groupId>
    <artifactId>helidon-metrics</artifactId>
    <scope>runtime</scope>
</dependency>
----

// end::all-beginning-text[]

// tag::writing-code-beginning[]

// tag::writing-code-intro[]
=== Writing Metrics-capable Code
The way you write a metrics-capable module depends on whether it is a _component_
(that is, _not_ an application) or an _application_.

// end::writing-code-intro[]

// tag::writing-component[]

==== Writing a _Non-application Component_
Write your _non-application_ component to accept component-specific configuration that includes an optional `metrics` section
which can include an optional `enabled` setting. Helidon defaults the value to `true`.
The following example shows one way to accomplish this:

.Example code to support disabling metrics usage in a component
[source,java]
----
import io.helidon.config.Config;
import io.helidon.metrics.api.ComponentMetricsSettings;
import io.helidon.metrics.api.MetricsSettings;
import io.helidon.metrics.api.RegistryFactory;

import org.eclipse.microprofile.metrics.MetricRegistry;

public class UtilComponent {

    private final MetricRegistry metricRegistry; // <1>

    public static class Builder implements io.helidon.common.Builder<UtilComponent> { // <2>
        private ComponentMetricsSettings.Builder componentMetricsSettingsBuilder = ComponentMetricsSettings.builder();

        public Builder componentMetricsSettings(ComponentMetricsSettings.Builder componentMetricsSettingsBuilder) { // <3>
            this.componentMetricsSettingsBuilder = componentMetricsSettingsBuilder;
            return this;
        }

        public Builder config(Config componentConfig) { // <4>
            componentConfig
                .get(ComponentMetricsSettings.Builder.METRICS_CONFIG_KEY)
                .as(ComponentMetricsSettings::create)
                .ifPresent(this::componentMetricsSettings);
            return this;
        }

        public UtilComponent build() {
            return new UtilComponent(this);
        }
    }

    private UtilComponent(Builder builder) {
        metricRegistry = RegistryFactory
                .getInstance(builder.componentMetricsSettingsBuilder.build())
                .getRegistry(MetricRegistry.Type.VENDOR); // <5>
    }

    MetricRegistry metricRegistry() { // <6>
        return metricRegistry;
    }
}
----
<1> Other code in the component uses this metric registry for registering, looking up, and removing metrics.
<2> Applications which use instances of `MyComponent` use this `Builder` to set up and create those instances.
<3> Applications which layer on your component invoke this method to set up the component-level metrics behavior they want your component to use.
<4> If an application supports configuration, it passes the util config to this method.
<5> The constructor for your component obtains the `MetricRegistry` which the rest of your component will use.
<6> Provides easy access to the `MetricRegistry` which the component's metrics code should use.

Helidon returns either a full-featured `RegistryFactory` or a minimal one, depending on:

* whether the full-featured metrics implementation is on the runtime path,
* whether metrics overall is enabled or disabled, and
* whether the component metrics settings requests enabled or disabled metrics.

// end::writing-component[]

// end::writing-code-beginning[]


// tag::writing-code-ending[]

== Examples

The following example shows how useful metrics-capable code can be in the context of building Docker images.

You (or others) could assemble a Docker image with your metrics-capable app as its top layer or your metrics-capable component in a middle layer, built on a lower  layer containing several Helidon modules including the full metrics implementation.
When that Docker image runs, your app will run with full-featured metrics support.

Separately, someone could build a similar Docker image which _does not_ include the Helidon metrics implementation.
In this Docker image, your app or component will run successfully but will not incur the overhead of actually updating the metrics it uses.

Users can create different Docker images, some with full metrics support and some without,
which all use a single version of your metrics-capable app or component which runs properly in either environment without change.
// end::writing-code-ending[]

// tag::wrap-up[]
== Additional Information

=== Advantages of Writing Metrics-capable Modules
By writing a metrics-capable app or component, you give packagers and deployers of your code the flexibility to include or exclude
the full metrics implementation at runtime as they see fit.

Because your one module works correctly in either environment:

* The consumers of your app benefit by not needing to understand and choose between two different implementations of your module, or having to add both your main module and an  optional add-on which adds metrics support to your module.
* You benefit by writing and maintaining a single module, not two: one that is metrics-independent and one that is metrics-dependent.
// end::wrap-up[]
