///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/../..]
ifndef::flavor-lc[:flavor-lc: se]
:description: Helidon metrics
:keywords: helidon, metrics, configuration


// tag::config-intro[]
== Configuration

To control how the Helidon metrics subsystem behaves, add a `metrics` section to
ifdef::mp-flavor[your `META-INF/microprofile-config.properties` file.]
ifdef::se-flavor[your configuration file, such as `application.yaml`.]

Certain default configuration values depend on the fact that you are using Helidon {flavor-uc} as described in the <<flavor-specific-defaults,second table below>>.

include::{rootdir}/config/io_helidon_webserver_observe_metrics_MetricsObserver.adoc[tag=config,leveloffset=+1]

// It seems we need an explicit open block for the website rendering to create the anchor properly. I tried adding the anchor to the table (without the block) but that didn't work on the live site.
[#flavor-specific-defaults]
--
.Default Values Specific to Helidon {flavor-uc}
[%autowidth]
|====
|Key | Default Value

| `app-tag-name`
a| ifdef::se-flavor[`app`]
ifdef::mp-flavor[`mp_app`]

| `scoping.tag-name`
a| ifdef::se-flavor[`scope`]
ifdef::mp-flavor[`mp_scope`]

| `scoping.default`
// Use two ifdefs even though the value is the same because without that the resulting formatting can look different vs. the preceding cells.
a| ifdef::se-flavor[`application`]
ifdef::mp-flavor[`application`]

|====
--

[[controlling-gc-time]]
=== Controlling the {metric_uc} Type for `gc.time`
To date Helidon 4 releases have implemented the system-provided {metric} `gc.time` as a counter.
In fact, a gauge is more suitable for the approximate time the JVM has spent doing garbage
ifdef::se-flavor[collection.]
ifdef::mp-flavor[]
collection, and beginning with MicroProfile Metrics 5.1 the TCK relies on `gc.time` being a gauge.
endif::mp-flavor[]

Helidon {helidon-version} continues to use a counter by default to preserve backward compatibility, but you can choose to use a gauge by setting the configuration property `metrics.gc-time-type` to `gauge`.
You can also set the config property to `counter` which is the default.

Why should you care?
In fact, this distinction might not make a difference for many users.
But for others the differences between the programmatic APIs for `Counter` and `Gauge` would affect application code that works directly with the `gc-time`
{metric}. Further, the difference in output--particularly in the OpenMetrics/Prometheus format--might affect their application or downstream monitoring tools.

The ability to choose the {metric} type for `gc.time` is deprecated and is planned for removal in a future major release of Helidon at which time Helidon will always use a gauge.

// end::config-intro[]

// tag::config-examples[]
[#example-configuration]
=== Example Configuration

Metrics configuration is quite extensive and powerful and, therefore, a bit complicated.
The rest of this section illustrates some of the most common scenarios:

* <<config-disable,Disable metrics entirely.>>
* <<config-kpi,Choose whether to collect extended key performance indicator metrics.>>
ifdef::mp-flavor[]
* <<config-rest-request,Control `REST.request` metrics collection.>>

endif::[]

[#config-disable]
==== Disable Metrics Subsystem

.Disabling metrics entirely
ifdef::mp-flavor[]
[source,properties]
----
metrics.enabled=false
----
endif::[]
ifdef::se-flavor[]
[source,yaml]
----
server:
  features:
    observe:
      observers:
        metrics:
          enabled: false
----
endif::[]
Helidon does not update metrics, and the `{metrics-endpoint}` endpoints respond with `404`..

[#config-kpi]
==== Collecting Basic and Extended Key Performance Indicator (KPI) {metrics_uc}

Any time you include the Helidon metrics module in your application, Helidon tracks a basic performance indicator {metric}: a `Counter` of all requests received (`requests.count`)

Helidon {h1-prefix} also includes additional, extended KPI {metrics} which are disabled by default:

* current number of requests in-flight - a `Gauge` (`requests.inFlight`) of requests currently being processed
* long-running requests - a `Counter` (`requests.longRunning`) measuring the total number of requests which take at least a given amount of time to complete; configurable, defaults to 10000 milliseconds (10 seconds)
* load - a `Counter` (`requests.load`) measuring the number of requests worked on (as opposed to received)
* deferred - a `Gauge` (`requests.deferred`) measuring delayed request processing (work on a request was delayed after Helidon received the request)

You can enable and control these {metrics} using configuration:

.Controlling extended KPI {metrics}
ifdef::mp-flavor[]
[source,properties]
----
metrics.key-performance-indicators.extended = true
metrics.key-performance-indicators.long-running.threshold-ms = 2000
----
endif::[]
ifdef::se-flavor[]
[source,yaml]
----
server:
  features:
    observe:
      observers:
        metrics:
          key-performance-indicators:
            extended: true
            long-running:
              threshold-ms: 2000
----
endif::[]

[#config-rest-request]
ifdef::mp-flavor[]
==== Enable `REST.request` {metrics_uc}

.Controlling REST request {metrics}
[source,properties]
----
metrics.rest-request-enabled=true
----
Helidon automatically registers and updates `Timer` {metrics} for every REST endpoint in your service.
endif::[]

// end::config-examples[]
