restrictive-cors:
  allow-origins: ["http://foo.com", "http://there.com"]
  allow-methods: ["PUT", "DELETE"]

# The example app uses the following for overriding other settings.
#cors:
#  paths:
#    - path-pattern: /greeting
#      allow-origins: ["http://foo.com", "http://there.com", "http://other.com"]
#      allow-methods: ["PUT", "DELETE"]
