///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Metrics and Health Support
:description: Helidon Reactive WebServer metrics and health support
:keywords: helidon, reactive, reactive streams, reactive java, reactive webserver, metrics

== Metrics Support
The WebServer includes Prometheus support for metrics.

=== Prerequisites

Declare the following dependency in your project:

[source,xml,subs="verbatim,attributes"]
.Webserver Prometheus Support Dependency
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver-prometheus</artifactId>
</dependency>
----

=== Configuring Prometheus
To enable Prometheus integration, register Prometheus support
with the WebServer:

[source,java]
.Configuring Prometheus
----
Routing.builder()
                .register(PrometheusSupport.create())
                .register("/myapp", new MyService())
                .build();
----

Then you can interact with Prometheus collectors in your service. Metrics are available at `/metrics`

[source,java]
.Define a Prometheus Counter
----
public class MyService implements Service {
    static final Counter accessCtr = Counter.build()
        .name("requests_total").help("Total requests.").register();  //<1>

    @Override
    public void update(Routing.Rules rules) {
            rules
                 .any(this::countAccess)
                 .get("/", this::myGet);
        }

    private void countAccess(ServerRequest request, ServerResponse response) {
            accessCtr.inc(); //<2>
            request.next();
    }
}
----

<1> Register a Prometheus `Counter` with the default Collector
<2> Use the `Counter` in a request handler

== Implementing a Health Check

The WebServer does not include a dedicated health check feature, but you
can implement a health check by defining an appropriate endpoint. 

To create a health check that runs on a separate port from your main web application:

1. Define a second socket in the WebServer's configuration.
2. Create a health service to handle requests on the socket.
3. Add a route to the health service.

[source,yaml]
.Define a health check socket in application.yaml
----
server:
  port: 8080
  sockets:
    health:  // <1>
        port: 9090
----

<1> Name this socket "health"

[source,java]
.Create a health service
----
public class HealthCheckService implements Service {

    HealthCheckService() {
    }

    @Override
    public void update(Routing.Rules rules) {
        rules.get("/health", this::get);
    }

    public void get(ServerRequest req, ServerResponse res) {
        res.status(200).send();
    }
}
----

[source,java]
.Define a route to the HealthCheckService service on the socket
----
        // By default this picks up application.yaml from the classpath
        Config config = Config.create();

        // Get WebServer config from the "server" section of application.yaml
        ServerConfiguration serverConfig = ServerConfiguration.
            fromConfig(config.get("server"));

        WebServer server = WebServer.builder(createRouting())  //<1>
                        .configuration(serverConfig)
                        .addNamedRouting("health",  //<2>
                                Routing.builder()
                                .register(new HealthCheckService())  // <3>
                                .build())
                        .build();
----

<1> `createRouting()` creates a `Routing` object for your main application.
    See the <<getting-started/02_base-example.adoc#Quickstart Examples,Quickstart examples>>.
<2> Add routing for a named socket. This name must match the name of the socket
    used in the WebServer configuration.
<3> Register the health check service on that socket.

You can access your health check at `host:9090/health`
