///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/../..]
ifndef::flavor-lc[:flavor-lc: se]
:description: Helidon metrics
:keywords: helidon, metrics, configuration


// tag::config-intro[]
== Configuration

To control how the Helidon metrics subsystem behaves, add a `metrics` section to
ifdef::mp-flavor[your `META-INF/microprofile-config.properties` file.]
ifdef::se-flavor[your configuration file, such as `application.yaml`.]

include::{rootdir}/config/io_helidon_metrics_serviceapi_MetricsSupport.adoc[tag=config,leveloffset=+1]

// end::config-intro[]

// tag::config-examples[]
[#example-configuration]
=== Example Configuration
- <<Disable Metrics Subsystem, Disable Metrics Subsystem>>
- <<Disable Selected Metrics, Disable Selected Metrics>>
- <<Collecting Basic and Extended Key Performance Indicator (KPI) Metrics, Collecting Basic and Extended Key Performance Indicator (KPI) Metrics>>

Metrics configuration is quite extensive and powerful and, therefore, a bit complicated.
The rest of this section illustrates some of the most common scenarios.

[#config-disable]
==== Disable Metrics Subsystem

.Disabling metrics entirely
ifdef::mp-flavor[]
[source,properties]
----
metrics.enabled=false
----
endif::[]
ifdef::se-flavor[]
[source,yaml]
----
metrics:
  enabled: false
----
endif::[]
Helidon does not update metrics, and the `/metrics` endpoints respond with `404` plus a message that the metrics subsystem is disabled.

[#config-selective]
==== Disable Selected Metrics

You can be even more selective. Within a registry type you can configure up to two regular expression patterns:

* one matching metric names to _exclude_, and
* one matching metric names to _include_.

Helidon updates and reports a metric only if two conditions hold:

* the metric name _does not_ match the `exclude` regex pattern (if you define one), and
* either
** there is no `include` regex pattern, or
** the metric name matches the `include` pattern.

[NOTE]
====
Make sure any `include` regex pattern you specify matches _all_ the metric names you want to capture.
====
Suppose your application creates and updates a group of metrics with names such as `myapp.xxx.queries`, `myapp.xxx.creates`, `myapp.xxx.updates`, and `myapp.xxx.deletes` where `xxx` can be either `supplier` or `customer`.

The following example gathers all metrics _except_ those from your application regarding suppliers _although_ supplier updates are _included_:

.Disabling and enabling metrics by name
ifdef::mp-flavor[]
[source,properties]
----
metrics.registries.0.type=application
metrics.registries.0.application.filter.exclude=myapp\.supplier\..*
metrics.registries.0.application.filter.include=myapp\.supplier\.updates
----
endif::[]
ifdef::se-flavor[]
[source,yaml]
----
metrics:
  registries:
    - type: application
      filter:
        exclude: "myapp\.supplier\..*"
        include: "myapp\.supplier\.updates"
----
endif::[]

This setting excludes metrics with names starting with `myapp.supplier` _except_ for the metric `myapp.supplier.updates`. The `exclude` and `include` values are regular expressions.

[#config-kpi]
==== Collecting Basic and Extended Key Performance Indicator (KPI) Metrics

Any time you include the Helidon metrics module in your application, Helidon tracks two basic performance indicator metrics:

* a `Counter` of all requests received (`requests.count`), and
* a `Meter` of all requests received (`requests.meter`).

Helidon {h1-prefix} also includes additional, extended KPI metrics which are disabled by default:

* current number of requests in-flight - a `ConcurrentGauge` (`requests.inFlight`) of requests currently being processed
* long-running requests - a `Meter` (`requests.longRunning`) measuring the rate at which Helidon processes requests which take at least a given amount of time to complete; configurable, defaults to 10000 milliseconds (10 seconds)
* load - a `Meter` (`requests.load`) measuring the rate at which requests are worked on (as opposed to received)
* deferred - a `Meter` (`requests.deferred`) measuring the rate at which a request's processing is delayed after Helidon receives the request

You can enable and control these metrics using configuration:

.Controlling extended KPI metrics
ifdef::mp-flavor[]
[source,properties]
----
metrics.key-performance-indicators.extended = true
metrics.key-performance-indicators.long-running.threshold-ms = 2000
----
endif::[]
ifdef::se-flavor[]
[source,yaml]
----
metrics:
  key-performance-indicators:
    extended: true
    long-running:
      threshold-ms: 2000
----
endif::[]

[#config-rest-request]
ifdef::mp-flavor[]
==== Enable REST.request Metrics

.Controlling REST request metrics
[source,properties]
----
metrics.rest-request.enabled=true
----
Helidon automatically registers and updates `SimpleTimer` metrics for every REST endpoint in your service.
endif::[]

// end::config-examples[]