///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

ifndef::rootdir[:rootdir: {docdir}/../..]
ifndef::flavor-lc[:flavor-lc: se]

:description: Helidon metrics
:keywords: helidon, metrics, exemplar, prometheus, OpenMetrics
:feature-name: OpenMetrics exemplar support

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
** <<Interpreting Exemplars, Interpreting Exemplars>>
** <<Output Format, Output Format>>
** <<Controlling Exemplar Output, Controlling Exemplar Output>>
- <<Examples, Examples>>
- <<Additional Information, Additional Information>>

== Overview

A metric typically reflects the usage of a _single_ point in your service processing _multiple_ requests over time.
A value such as the total time consumed by a given REST endpoint underscores the aggregate nature of metric values; Helidon accumulates the time from all requests in the total duration.

Tracing, on the other hand, captures the usage of _multiple_ parts of your code as your service responds to a _single_ request.

Metrics and tracing come together in Helidon's support for examplars.

[NOTE]
--
link:https://www.merriam-webster.com/dictionary/exemplar[_exemplar_] - one that serves as a model or example
[.text-right]
-- Merriam-Webster Dictionary
--

In the context of metrics, an _exemplar_ for a given metric is a specific sample which, in some sense, made a typical contribution to the metric's value. For example, an exemplar for a `SimpleTimer` might be a sample in which the duration it contributed to the value of a `SimpleTimer` is near the mean of the durations over all samples. The metrics output identifies the exemplar sample using the trace ID of the trace which triggered that sample.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>io.helidon.metrics</groupId>
    <artifactId>helidon-metrics-trace-exemplar</artifactId>
    <scope>runtime</scope>
</dependency>
----

Also, include the Helidon integration module for a tracing implementation (such as
ifdef::se-flavor[]
xref:{rootdir}/se/tracing.adoc#zipkin-tracing[Helidon Zipkin])
endif::[]
ifdef::mp-flavor[]
xref:{rootdir}/mp/tracing.adoc#zipkin-tracing[Helidon Zipkin])
endif::[]
include::{rootdir}/includes/tracing/tracer-zipkin.adoc[tag=zipkin-dependency]

Add the Helidon tracing component itself:
ifdef::se-flavor[]
include::{rootdir}/se/tracing.adoc[tag=tracing-dependency]
endif::[]
ifdef::mp-flavor[]
include::{rootdir}/mp/tracing.adoc[tag=tracing-dependency]
endif::[]

== Usage
Once you add the appropriate dependencies to your project, exemplar support runs automatically as part of Helidon metrics. You do not need to change your application or configuration.

=== Interpreting Exemplars

Helidon automatically records a sample (label, value, and timestamp) with each update to certain metrics. When a client accesses the `/metrics` endpoint, Helidon adds the label, value, and timestamp to the OpenMetrics response for those metrics.

By default, Helidon adds exemplars only to counters and the counter portion of simple timers.
The OpenMetrics specification allows exemplars only on counters and buckets.
(Helidon's histogram output, consistent with the MicroProfile Metrics spec, includes the quantiles but not the buckets.)

[NOTE]
Earlier releases of Helidon included exemplars on other metric types as well. If you must keep the prior behavior for compatibility reasons, see the xref:controlling-exemplar-output[Controlling Exemplar Output] section below.

=== Output Format
In the OpenMetrics output, an exemplar actually appears as a comment appended to the normal OpenMetrics output.

.OpenMetrics format with exemplars
[source,subs="quotes"]
----
_metric-identifier_ _metric-value_ # _exemplar-label_ _sample-timestamp_
----
Even downstream consumers of OpenMetrics output that do not recognize the exemplar format should continue to work correctly (as long as they _do_ recognize comments).

But some consumers, such as trace collectors and their U/Is, understand the exemplar format, and they allow you to browse metrics and then navigate directly to the trace for the metric's exemplar.

[[controlling-exemplar-output]]
=== Controlling Exemplar Output
Once you add dependencies on `helidon-metrics-trace-exemplar` and one of the Helidon tracing integration libraries to your project, Helidon automatically adds exemplars to those metrics which the OpenMetrics specification permits to have exemplars.

Earlier releases of Helidon added exemplars to other, non-standard metric types. If you require the former behavior for compatibility reasons,  you can enable exemplars on non-standard metric types.
In this context, with _strict_ exemplar behavior Helidon adds exemplars only to those metrics allowed by the OpenMetrics spec.  With _lax_ behavior Helidon also adds exemplars to simple timer and meter output.

[NOTE]
The lax exemplar behavior is non-standard. Some downstream consumers of the resulting OpenMetrics output might reject it because it contains non-standard content.

You control strict vs. lax exemplar support separately for each registry type.

ifdef::se-flavor[]
=== Using Configuration
endif::[]
ifdef::se-flavor[]
[source,yaml]
.Enabling non-standard exemplar behavior in `application.yaml`
----
metrics:
  registries:
    - type: application
      exemplars:
        strict: false
----
endif::[]
ifdef::mp-flavor[]
[source,properties]
.Enabling non-standard exemplar behavior in `META-INF/microprofile-config.properties`
----
metrics.registries.0.type=application
metrics.registries.0.exemplars.strict = false
----
endif::[]
The `exemplars.strict` setting defaults to `true` for all registry types.

ifdef::se-flavor[]

=== Using `RegistrySettings` Programmatically
The `MetricsSettings.Builder` interface exposes `registrySettings(MetricRegistry.Type, RegistrySettings)` with which your code can assign registry settings for each registry type separately. The `RegistrySettings.Builder` interface has the `strictExemplars(boolean)` method with which you can programmatically choose whether to use strict or lax exemplar support. The default is `true`.
endif::[]

== Examples

ifdef::se-flavor[]
Helidon includes an link:{helidon-github-examples-url}/metrics/exemplar[example application], based on the QuickStart application, which illustrates exemplar support.
endif::[]

Once you enable exemplar support you can see the exemplars in the metrics output.

.Exemplar output - `Counter`
[listing,subs="+quotes"]
----
# TYPE application_globalRequestTracker_total counter
# HELP application_globalRequestTracker_total
application_globalRequestTracker_total 4 *# {trace_id="daf26fe35fee9917"} 0.001183992 1617725180.234000*
----
This exemplar in this case is the most recent sample.

== Additional Information

Brief discussion of link:{openmetrics-exemplar-spec-url}[exemplars in the OpenMetrics spec]