///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:description: Configuration of io.helidon.openapi.OpenAPISupport
:keywords: helidon, config, io.helidon.openapi.OpenAPISupport
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.openapi.OpenAPISupport

[source,text]
.Type
----
io.helidon.openapi.OpenAPISupport
----

OpenAPI support configuration



==== Configuration options




Optional configuration options:
[cols="3,3,2,5"]

|===
|key |type |default value |description

|`web-context` |string |`/openapi` |Sets the web context path for the OpenAPI endpoint.
|`cors` |link:../../shared/config/io.helidon.webserver.cors.CrossOriginConfig.adoc[CrossOriginConfig] |{nbsp} |Assigns the CORS settings for the OpenAPI endpoint.
|`static-file` |string |`META-INF/openapi.{json,yaml,yml}` |Sets the file system path of the static OpenAPI document file.

|===
