///////////////////////////////////////////////////////////////////////////////

Copyright (c) 2022 Oracle and/or its affiliates.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:description: Configuration of io.helidon.health.HealthSupport.Builder
:keywords: helidon, config, io.helidon.health.HealthSupport.Builder
:basic-table-intro: The table below lists the configuration keys that configure io.helidon.health.HealthSupport.Builder

[source,text]
.Type
----
io.helidon.health.HealthSupport.Builder
----



==== Configuration options




Optional configuration options:
[cols="3,3,2,5"]

|===
|key |type |default value |description

|`exclude-classes` |Class<?>[&#93; |{nbsp} |A class may be excluded from invoking health checks on it.
 This allows configurable approach to disabling broken health-checks.
|`timeout-millis` |long |{nbsp} |health endpoint timeout (ms)
|`exclude` |String> |{nbsp} |Add health checks to a black list.
 Health check results that match by name with a blacklisted records will not be
 part of the result.
|`include` |String> |{nbsp} |Add health checks to a white list (in case #includeAll is set to `false`.
|`enabled` |boolean |{nbsp} |HealthSupport can be disabled by invoking this method.

|===
