= Hikari Connection Pool Integration Example

== Overview

This example shows a trivial Helidon MicroProfile application that
uses the Hikari connection pool CDI integration.  It also shows how to
run the Oracle database in a Docker container and connect the
application to it.

== Notes

To log in to the Oracle Container Registry (which you will need to do
in order to pull Oracle database images from it):

```sh
$ docker login -u your.name@yourdomain.com -p yourpasswordhere container-registry.oracle.com
```

For more information on the Oracle Container Registry, please visit
https://container-registry.oracle.com[its website].

To run Oracle's `database/standard` Docker image in a Docker container
named `oracle` that publishes ports 1521 and 5500 to
the host:

```sh
$ docker container run --name oracle --detach -it --publish 1521:1521 --publish 5500:5500 --shm-size=3g container-registry.oracle.com/database/standard:latest
```

It will take about ten minutes before the database is ready.

To ensure that the sample application is configured to talk to the
Oracle database running in this Docker container, verify that the
following lines (among others) are present in
`src/main/resources/META-INF/microprofile-config.properties`:

```
javax.sql.DataSource.example.dataSourceClassName=oracle.jdbc.pool.OracleDataSource
javax.sql.DataSource.example.dataSource.url = jdbc:oracle:thin:@localhost:1521:ORCL
javax.sql.DataSource.example.dataSource.user = sys as sysoper
javax.sql.DataSource.example.dataSource.password = Oracle
```

To compile and package the sample application:

```sh
$ mvn clean package
```

To run the application:

```sh
$ java -jar target/helidon-examples-integrations-datasource-hikaricp-*.jar
```

To see the results of running the sample application:

```sh
$ curl http://localhost:8080/tables
```

To stop the `oracle` Docker container:

```sh
$ docker container stop oracle
```

To remove the `oracle` Docker container:

```sh
$ docker container rm oracle
```

== References

Running the Oracle database in a Docker container:

https://technology.amis.nl/2017/12/30/oracle-database-in-a-docker-container-from-oracle-container-registry/

Another guide:

https://technology.amis.nl/2017/11/18/run-oracle-database-in-docker-using-prebaked-image-from-oracle-container-registry-a-two-minute-guide/

