///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Health Checks
:description: Helidon health checks
:keywords: helidon, health checks, health, check, readiness, liveness, probes, kubernetes
:feature-name: Health Checks
:rootdir: {docdir}/..

include::{rootdir}/includes/se.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<API, API>>
** <<Built-In Health Checks, Built-In Health Checks>>
** <<Kubernetes Probes, Kubernetes Probes>>
** <<Troubleshooting Probes, Troubleshooting Probes>>
- <<Configuration, Configuration>>
- <<Examples, Examples>>
** <<JSON Response Example,JSON Response Example>>
** <<Kubernetes Example, Kubernetes Example>>
- <<Additional Information, Additional Information>>

== Overview

It’s a good practice to monitor your microservice’s health, to ensure that it is
available and performs correctly.
Applications implement health checks to expose health status that is collected
at regular intervals by external tooling, such as orchestrators like
Kubernetes. The orchestrator may then take action, such as restarting your
application if the health check fails.

A typical health check combines the statuses of all the dependencies that
affect availability and the ability to perform correctly:

* Network Latency
* Storage
* Database
* Other Services (used by your application)

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.health</groupId>
    <artifactId>helidon-health</artifactId>
</dependency>
----

Optional dependency to use built-in health checks:

[source,xml]
----
<dependency>
    <groupId>io.helidon.health</groupId>
    <artifactId>helidon-health-checks</artifactId>
</dependency>
----

== API
To add custom health checks to your application, you need to

* write the code which performs the health checks, and
* make those custom health checks known to Helidon.

=== Writing Custom Health Checks

A health check is a Java functional interface that returns a
`HealthCheckResponse` instance. You can create custom health checks in several ways, among them:

* write a class which implements the `HealthCheck` interface,
* write an in-line lambda expression, or
* use a method reference a method with the double colon operator `::`.

[source,java]
.Health check with a lambda expression:
----
Supplier<HealthCheckResponse> hcr = () -> HealthCheckResponse
                .builder()
                .detail("exampleValue", "looking-good")
                .status(HealthCheckResponse.Status.UP) // always "up"
                .build();
----

[source,java]
.Health check with method reference (in class `Main`):
----
static HealthCheckResponse exampleHealthCheck() {
        return HealthCheckResponse
                .builder()
                .detail("exampleValue", "looking-good")
                .status(HealthCheckResponse.Status.UP) // always "up"
                .build();
    }

Supplier<HealthCheckResponse> hcr = Main::exampleHealthCheck;
----
A real health check would compute its status dynamically based on the conditions in the server rather than hard-coding a fixed value.

=== Adding Custom Health Checks to Helidon

Health support in Helidon is part of Helidon's observability feature.
`HealthObserver` is a Helidon-provided observability implementation that contains a collection of
registered `HealthCheck` instances and, when queried, invokes the registered
health checks and returns a response with a status code representing the overall
status of the application.

[cols="1,5",role="flex, sm7"]
.Health status codes
|=======
| `200` | The application is healthy (with health check details in the response).
| `204` | The application is healthy (with _no_ health check details in the response).
| `503` | The application is not healthy.
| `500` | An error occurred while reporting the health.
|=======

You control, either using configuration or adding code to your application, whether the HTTP responses to `GET` requests contain detailed information about each health check.
With details enabled, HTTP `GET` responses include JSON content showing the detailed results of all the health checks which the server executed after receiving the request.
With details disabled, HTTP `GET` responses have no payload.
HTTP `HEAD` requests always return only the status with no payload.

If you add the Helidon health dependency to your `pom.xml` file, Helidon automatically registers the `HelidonObserver` service and responds to the default `/observe/health` endpoint.
Further, if you add the built-in health checks dependency, Helidon automatically finds them and adds those checks to the `HealthObserver`.

The following example shows how to register your own custom health checks while building and registering an
instance of `HealthObserver`:

[source,java]
.Create and register the health observer feature with a custom health check
----
WebServer server = WebServer.builder()
        .config(config.get("server"))
        .addFeature(ObserveFeature.create(HealthObserver.builder()                     // <1>
                                                  .addCheck(hcr,                       // <2>
                                                            HealthCheckType.READINESS, // <3>
                                                            "exampleCheck")            // <4>
                                                  .details(true)                       // <5>
                                                  .build()))                           // <6>
        .routing(Main::routing)
        .build()
        .start();
----
<1> Create a builder for the `HealthObserver`.
<2> Create and add a custom health check to the builder, passing the supplier of the health check response (the `hcr` variable in this example).
<3> Set the type of health check.
<4> Set the name of the health check.
<5> Set the health observer to include details in the output. (optional)
<6> Build the `HealthObserver` so it can be added to the observability feature that is registered with the webserver.

Invoke `addCheck` multiple times to add multiple custom health checks.

Here is a sample response to the custom health check registered above:

[source,json]
.JSON response:
----
{
  "status": "UP",
  "checks": [
        {
      "name": "exampleCheck",
      "status": "UP",
      "data": {
        "exampleValue": "looking-good"
      }
    },
...
}
----

TIP: Balance collecting a lot of information with the need to avoid overloading
the application and overwhelming users.

The following table provides a summary of the Health Check API classes.

[cols="4,6"]
.Health check API classes
|=======
| `io.helidon.health.HealthCheck`
| Java functional interface representing the logic of a single health check

| `io.helidon.health.HealthCheckResponse`
| Result of a health check invocation that contains a status

| `io.helidon.webserver.observe.health.HealthObserver`
| WebServer service that exposes `/observe/health` and invokes the registered health
checks
|=======

=== Built-In Health Checks

You can use Helidon-provided health checks to report various
common health check statuses:

[[built-in-health-checks-table]]
[cols="1,1,3,15,3"]
|=======
|Built-in health check |Health check name |JavaDoc |Config properties |Default config value

|deadlock detection
|`deadlock`
| link:{health-javadoc-base-url}/io/helidon/health/checks/DeadlockHealthCheck.html[`DeadlockHealthCheck`]
| n/a
| n/a

|available disk space
|`diskSpace`
| link:{health-javadoc-base-url}/io/helidon/health/checks/DiskSpaceHealthCheck.html[`DiskSpaceHealthCheck`]
|`helidon.healthCheck.diskSpace.thresholdPercent` +
+
`helidon.healthCheck.diskSpace.path`
| `99.999` +
+
`/`
|available heap memory
| `heapMemory`
| link:{health-javadoc-base-url}/io/helidon/health/checks/HeapMemoryHealthCheck.html[`HeapMemoryHealthCheck`]
|`helidon.healthCheck.heapMemory.thresholdPercent`
|`98`
|=======

Simply adding the built-in health check dependency is sufficient to register all the built-in health checks automatically.
If you want to use only some of the built-in checks in your application, you can disable automatic discovery of the built-in health checks and register only the ones you want.

The following code adds only selected built-in health checks to your application:

[source,java]
.Adding selected built-in health checks
----
WebServer server = WebServer.builder()
        .config(config.get("server"))
        .addFeature(ObserveFeature.create(HealthObserver.builder()
                                                  .useSystemServices(false) // <1>
                                                  .addCheck(HealthChecks.deadlockCheck()) // <2>
                                                  .addCheck(hc) // <3>
                                                  .details(true)
                                                  .build()))
        .routing(Main::routing)
        .build()
        .start();
----
<1> Disables automatic registration of the built-in health checks.
<2> Adds the specific built-in check(s) you want.
<3> Adds a custom check.

You can control the thresholds for built-in health checks in either of two ways:

* Create the health checks individually
using their builders instead of using the `HealthChecks` convenience class.
Follow the JavaDoc links in the <<built-in-health-checks-table,table>> above.

* Using configuration as explained in <<Configuration>>.

=== Kubernetes Probes
* <<Liveness Probe, Liveness Probe>>
* <<Readiness Probe, Readiness Probe>>
* <<Startup Probe, Startup Probe>>


Probes is the term used by Kubernetes to describe health checks for containers
(link:https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes[Kubernetes documentation]).

There are three types of probes:

* _liveness_: Indicates whether the container is running
* _readiness_: Indicates whether the container is ready to service requests
* _startup_: Indicates whether the application in the container has started

You can implement probes using the following mechanisms:

. Running a command inside a container
. Sending an `HTTP` request to a container
. Opening a `TCP` socket to a container

A microservice exposed to HTTP traffic will typically implement both the
liveness probe and the readiness probe using HTTP requests.
If the microservice takes a significant time to initialize itself, you can also define a startup probe, in which case
Kubernetes does not check liveness or readiness probes until the startup probe returns success.

You can configure several parameters for probes. The following are the most
relevant parameters:

[cols="2,5",role="flex, sm7"]
|=======
| `initialDelaySeconds`
| Number of seconds after the container has started before liveness or readiness
probes are initiated.

| `periodSeconds`
| Probe interval. Default to 10 seconds. Minimum value is 1.

| `timeoutSeconds`
| Number of seconds after which the probe times out. Defaults to 1 second.
Minimum value is 1

| `failureThreshold`
| Number of consecutive failures after which the probe should stop. Default: 3.
Minimum: 1.
|=======

==== Liveness Probe

The liveness probe is used to verify the container has become unresponsive.
For example, it can be used to detect deadlocks or analyze heap usage. When
Kubernetes gives up on a liveness probe, the corresponding pod is restarted.

NOTE: The liveness probe can result in repeated restarts in certain cases.
For example, if the probe is implemented to check all the dependencies
strictly, then it can fail repeatedly for temporary issues. Repeated restarts
can also occur if `timeoutSeconds` or `periodSeconds` is too low.

We recommend the following:

* Avoid checking dependencies in a liveness probe.
* Set `timeoutSeconds` to avoid excessive probe failures.
* Acknowledge startup times with `initialDelaySeconds`.

==== Readiness Probe

The readiness probe is used to avoid routing requests to the pod until it is
ready to accept traffic. When Kubernetes gives up on a readiness probe, the
pod is not restarted, traffic is not routed to the pod anymore.

NOTE: In certain cases, the readiness probe can cause all the pods to be removed
from service routing. For example, if the probe is implemented to check all the
dependencies strictly, then it can fail repeatedly for temporary issues. This
issue can also occur if `timeoutSeconds` or `periodSeconds` is too low.

We recommend the following:

* Be conservative when checking shared dependencies.
* Be aggressive when checking local dependencies.
* Set `failureThreshold` according to `periodSeconds` in order to accommodate
temporary errors.

==== Startup Probe

The startup probe prevents Kubernetes from prematurely checking the other probes if the application takes a long time to start.
Otherwise, Kubernetes might misinterpret a failed liveness or readiness probe and shut down the container when, in fact, the application is still coming up.


=== Troubleshooting Probes

Failed probes are recorded as events associated with their corresponding pods.
The event message contains only the status code.

[source,bash]
.Get the events of a single pod:
----
POD_NAME=$(kubectl get pod -l app=acme -o jsonpath='{.items[0].metadata.name}') # <1>
kubectl get event --field-selector involvedObject.name=${POD_NAME} # <2>
----
<1> Get the effective pod name by filtering pods with the label `app=acme`.
<2> Filter the events for the pod.

TIP: Create log messages in your health check implementation when setting a
`DOWN` status. This will allow you to correlate the cause of a failed probe.

== Configuration

Built-in health checks can be configured using the config property keys
described in this
<<built-in-health-checks-table,table>>. Further, you can suppress one or more of the built-in
health checks by setting the configuration item
`helidon.health.exclude` to a comma-separated list of the health check names
(from this <<built-in-health-checks-table,table>>) you want to exclude.

== Examples

=== JSON Response Example

Accessing the Helidon-provided `/health` endpoint reports the health of your application
as shown below:

[source,json]
.JSON response.
----
{
    "status": "UP",
    "checks": [
        {
            "name": "deadlock",
            "status": "UP"
        },
        {
            "name": "diskSpace",
            "status": "UP",
            "data": {
                "free": "211.00 GB",
                "freeBytes": 226563444736,
                "percentFree": "45.31%",
                "total": "465.72 GB",
                "totalBytes": 500068036608
            }
        },
        {
            "name": "heapMemory",
            "status": "UP",
            "data": {
                "free": "215.15 MB",
                "freeBytes": 225600496,
                "max": "3.56 GB",
                "maxBytes": 3817865216,
                "percentFree": "99.17%",
                "total": "245.50 MB",
                "totalBytes": 257425408
            }
        }
    ]
}
----

=== Kubernetes Example

This example shows the usage of the Helidon health API in an application that
implements health endpoints for the liveness and readiness probes. Note that
the application code dissociates the health endpoints from the default routes,
so that the health endpoints are not exposed by the service. An example YAML
specification is also provided for the Kubernetes service and deployment.

[source,java]
.Application code:
----
ObserveFeature observeFeature = ObserveFeature.builder()
    .addObserver(HealthObserver.builder()
                         .useSystemServices(false)
                         .endpoint("/health/live") // <1>
                         .addChecks(HealthChecks.healthChecks()) // <2>
                         .build())
    .addObserver(HealthObserver.builder()
        .useSystemServices(false)
        .endpoint("/health/ready") // <3>
        .addCheck(new HealthCheck() { // <4>
            @Override
            public String name() {
                return "database";
            }

            @Override
            public HealthCheckResponse call() {
            return HealthCheckResponse.builder()
                .status(true)
                .build();
            }

            @Override
            public HealthCheckType type() {
                return HealthCheckType.READINESS;
            }
        })
        .build())
    .build();
WebServer server = WebServer.builder()
    .putSocket("@default", socket -> socket
        .port(8080) // <5>
        .routing(r -> r.any((req, res) -> res.send("It works!")))) // <6>
    .putSocket("observe", socket -> socket
        .port(8081) // <7>
        .routing(r -> r.addFeature(observeFeature))) // <8>
    .build()
    .start();
----
<1> The health service for the `liveness` probe is exposed at `/observe/health/live`.
<2> Using the built-in health checks for the `liveness` probe.
<3> The health service for the `readiness` probe is exposed at `/observe/health/ready`.
<4> Using a custom health check for a pseudo database that is always `UP`.
<5> The default socket uses port 8080 for the default routes.
<6> The default route: returns It works! for any request.
<7> The `observe` socket uses port 8081 for the "/observe" routes.
<8> Route the `observe` feature exclusively on the `observe` socket.

[source,yaml]
.Kubernetes descriptor:
----
kind: Service
apiVersion: v1
metadata:
  name: acme # <1>
  labels:
    app: acme
spec:
  type: NodePort
  selector:
    app: acme
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: acme # <2>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme
  template:
    metadata:
      name: acme
      labels:
        name: acme
    spec:
      containers:
      - name: acme
        image: acme
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /observe/health/live # <3>
            port: 8081
          initialDelaySeconds: 3 # <4>
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /observe/health/ready # <5>
            port: 8081
          initialDelaySeconds: 10 # <6>
          periodSeconds: 30
          timeoutSeconds: 10
---
----
<1> A service of type `NodePort` that serves the default routes on port `8080`.
<2> A deployment with one replica of a pod.
<3> The HTTP endpoint for the liveness probe.
<4> The liveness probe configuration.
<5> The HTTP endpoint for the readiness probe.
<6> The readiness probe configuration.

== Additional Information

* link:{health-javadoc-base-url}/module-summary.html[Health Checks SE API JavaDocs].