///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= OpenAPI Generator
:toc:
:toc-placement: preamble
:description: Helidon SE OpenAPI Generator
:keywords: helidon, se, openapi, generator
:feature-name: Helidon SE OpenAPI Generator
:rootdir: {docdir}/..

include::{rootdir}/includes/se.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Configuration, Configuration>>
- <<Usage, Usage>>
- <<Reference, Reference>>

== Overview

The OpenAPI Specification (OAS) defines a standard, language-agnostic interface to RESTful APIs which allows both humans and computers to discover and understand the capabilities of the service without access to source code, documentation, or through network traffic inspection.
When properly defined, a consumer can understand and interact with the remote service with a minimal amount of implementation logic.
OpenAPI documents allow you to convert the metadata about your API into some other format and OpenAPI Generator helps with that. It allows generating of API client or server stubs.
With OpenAPI client generator for Helidon SE, user can easily generate Rest Client to interact with any server which exposes an OpenAPI document.
With OpenAPI server generator for Helidon SE server stubs can be generated where user has to implement business logic for exposed endpoints.

== Maven Coordinates [[Maven-Coordinates]]

Core:

[source,xml]
----
<dependency>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator</artifactId>
    <version>${openapi-generator-version}</version>
</dependency>
----

See the different versions of the openapi-generator artifact available on maven central.

Cli:

[source,xml]
----
<dependency>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-cli</artifactId>
    <version>${openapi-generator-version}</version>
</dependency>
----

See the different versions of the openapi-generator-cli artifact available on maven central.

Maven plugin:

[source,xml]
----
<dependency>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>${openapi-generator-version}</version>
</dependency>
----

== Configuration

To customize generated project different options can be used.
Options for OpenAPI Generator are the same whether you're using the Maven/Gradle Plugins, CLI, or Online generation.

General Configuration parameters

At a minimum generation of the new Helidon MP project requires:

[cols="1,1"]
|===
|Option | Description

|inputSpec
|OpenAPI Spec file path
|generatorName
|target generator name
|library
|library template (sub-template)
|===

The whole list of the general configuration parameters for OpenAPI Generator is available on link:https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin[openapi-generator-maven-plugin] page.

Predefined values for required options for Helidon SE Generators :

[cols="1,1,1"]
|===
|Option |Value |Description

|generatorName
|java-helidon-server
|generator name for Helidon SE Server

|generatorName
|java-helidon-client
|generator name for Helidon SE Client

|library
|se
|used library for Helidon SE Server/Client
|===

OpenAPI Generators for Helidon SE support such specific options :

[cols="1,1,1,1,1"]
|===
|Option |Description |Values |Default |Notes

|helidonVersion
|Version of Helidon
|
|2.5.2
|

|fullProject
|Generate API files only
|true/false
|false
| API files : API Interfaces or abstract classes, models (files we do not expect the end user to modify)

|serializationLibrary
|Library to use for serializing JSON
|jsonb, jackson
|jackson
|
|===

== Usage

CLI, Maven/Gradle Plugins, or Online generation can be used to generate Helidon SE project.

To generate a project using CLI at first `openapi-generator-cli.jar` or `Launcher Script` should be downloaded (details can be found in link:https://github.com/OpenAPITools/openapi-generator#1---installation[OpenAPI Generator GitHub Repository])

To generate Helidon SE server stubs for petstore.yaml (OpenApi Document) using `openapi-generator-cli.jar`, please run the following :

[source,bash]
----
java -jar openapi-generator-cli.jar \
  generate \
  -i petstore.yaml \
  -g java-helidon-server \
  --library se \
  -p groupId=test.se.helidon \
  -p artifactId=test-helidon-se-server \
  -p artifactVersion=1.0.0-SNAPSHOT
----

This command will generate maven project for Helidon SE Server with groupId, artifactId and version as described above.

To generate SE REST client for petstore.yaml (OpenApi Document) using `openapi-generator-cli.jar`, please run the following :

[source,bash]
----
java -jar openapi-generator-cli.jar \
  generate \
  -i petstore.yaml \
  -g java-helidon-client \
  --library se
----

This command will generate maven project for Helidon SE Rest Client that can interact with server which exposes API that described in the OpenAPI document (petstore.yaml).

Maven plugin `openapi-generator-maven-plugin` can be used to generate files according to an OpenAPI document.
Default phase is `generate-sources` phase.

For example, this Maven plugin can be used to generate/regenerate files (API interfaces or abstract classes that represent REST endpoints, models and other files that the end user does not modify) :

[source,xml]
----
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>${openapi-generator-version}</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/petstore.yaml</inputSpec>
                <generatorName>java-helidon-server</generatorName>
                <library>se</library>
                <configOptions>
                   <fullProject>false</fullProject>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
----

== Reference
* link:https://openapi-generator.tech[OpenAPI Generator Official Website]
* link:https://github.com/OpenAPITools/openapi-generator[OpenAPI Generator GitHub Repository]
