///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2025 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= WebServer Introduction
:description: Helidon Reactive WebServer Introduction
:keywords: helidon, reactive, reactive streams, reactive java, reactive webserver, tls
:feature-name: WebServer
:rootdir: {docdir}/..
:requested-uri-discovery-inc: {rootdir}/includes/server/requested-uri-discovery.adoc

include::{rootdir}/includes/se.adoc[]

== Contents

- <<Overview,Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
- <<Configuration, Configuration>>
** <<Configuring the WebServer in Your Code, Configuring the WebServer in Your Code>>
** <<Configuring the WebServer in a Configuration File, Configuring the WebServer in a Configuration File>>
** <<Configuration Options, Configuration Options>>
*** <<Routing, Routing>>
*** <<Request Handling, Request Handling>>
*** <<Error Handling, Error Handling>>
- <<Supported Technologies, Supported Technologies>>
** <<HTTP/2 Support, HTTP/2 Support>>
** <<Static Content Support, Static Content Support>>
** <<Jersey (JAX-RS) Support, Jersey (JAX-RS) Support>>
** <<JSON Support, JSON Support>>
- <<Reference, Reference>>
- <<Additional Information, Additional Information>>


== Overview

WebServer provides an asynchronous and reactive API for creating web applications.
The API is inspired by popular NodeJS and Java frameworks.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver</artifactId>
</dependency>
----

== Usage
The following sections describe how to use WebServer. 

== Configuration

Configure the WebServer either programmatically, or by the Helidon configuration framework.

=== Configuring the WebServer in Your Code

The easiest way to configure the WebServer is in your
application code.

[source,java]
----
WebServer webServer = WebServer.builder()
      .bindAddress(InetAddress.getLocalHost())
      .port(8080)
      .build();
----

=== Configuring the WebServer in a Configuration File

You can also define the configuration in a file.

[source,yaml]
.WebServer configuration file `application.yaml`
----
server:
  port: 8080
  bind-address: "0.0.0.0"
----

Then, in your application code, load the configuration from that file.

[source,java]
.WebServer initialization using the `application.yaml` file located on the classpath
----
Config config = Config.create(); // <1>
WebServer webServer = WebServer.create(routing, config.get("server")); // <2>
----

<1> `application.yaml` is a default configuration source loaded when YAML support is on classpath, so we can
just use `Config.create()`
<2> Server expects the configuration tree located on the node of `server`

=== Configuration Options

include::{rootdir}/config/io_helidon_webserver_WebServer.adoc[leveloffset=+2,tag=config]

== Routing 
Routing lets you use request matching criteria to bind requests to a `handler` that implements
your custom business logic. Matching criteria include one or more *HTTP Method(s)* and, optionally,
a request *path matcher*. Use the `RequestPredicate` class to specify more routing
criteria.

=== Basics

Routing also supports _Error Routing_ which binds Java `Throwable` to the
handling logic.

Configure HTTP request routing using `Routing.Builder`.

[source,java]
.Using Routing.Builder to specify how HTTP requests are handled
----
Routing routing = Routing.builder()
                         .get("/hello", (req, res) -> res.send("Hello World!")) // <1>
                         .build();

WebServer webServer = WebServer.create(routing); // <2>
----
<1> Handle all GETs to `/hello` path. Send the `Hello World!` string.
<2> Add the `routing` to the WebServer.

=== HTTP Method Routing

`Routing.Builder` lets you specify how to handle each HTTP method. For example:

[cols="1,5", role="flex, sm7"]
|===
|HTTP Method|Routing.Builder example

|*GET*|`+.get((req, res) -> { /* handler */ })+`
|*PUT*| `+.put((req, res) -> { /* handler */ })+`
|*POST*| `+.post((req, res) -> { /* handler */ })+`
|*HEAD*| `+.head((req, res) -> { /* handler */ })+`
|*DELETE*| `+.delete((req, res) -> { /* handler */ })+`
|*TRACE*| `+.trace((req, res) -> { /* handler */ })+`
|*OPTIONS*| `+.options((req, res) -> { /* handler */ })+`
|_any method_|`+.any((req, res) -> { /* handler */ })+`
|_multiple methods_|`+.anyOf(List.of(Http.Method.GET, Http.Method.POST), (req, res) -> { /* handler */ })+`
|_custom method_|`+.anyOf(Set.of(Http.RequestMethod.create("CUSTOM")), (req, res) -> { /* handler */ })+`
|===

=== Path Matcher Routing
You can combine HTTP method routing with request path matching.

[source,java]
----
Routing.builder()
       .post("/some/path", (req, res) -> { /* handler */ })
----

You can use *path pattern* instead of _path_ with the following syntax:

* `/foo/bar/baz` - Exact path match against resolved path even with non-usual characters
* `/foo/{}/baz` - `{}` Unnamed regular expression segment `([^/]+)`
* `/foo/{var}/baz` - Named regular expression segment `([^/]+)`
* `/foo/{var:\d+}` - Named regular expression segment with a specified expression
* `/foo/{:\d+}` - Unnamed regular expression segment with a specified expression
* `/foo/{\+var}` - Convenience shortcut for `{var:.+}`. A matcher is not a true URI template (as defined by RFC) but this convenience is in sync with the Apiary templates
* `/foo/{\+}` - Convenience shortcut for unnamed segment with regular expression `{:.+}`
* `/foo/{\*}` - Convenience shortcut for unnamed segment with regular expression `{:.*}`
* `/foo[/bar]` - An optional block, which translates to the `/foo(/bar)?` regular expression
* `/*` or `/foo*` - `*` Wildcard character can be matched with any number of characters.


IMPORTANT: Path (matcher) routing is *exact*. For example, a `/foo/bar` request is *not* routed to `.post('/foo', ...)`.

TIP: Always start _path_ and _path patterns_ with the `/` character.

[[anchor-requestpredicate]]
=== Request Predicate

Use the `RequestPredicate` utility class to identify more
criteria. You can construct (build) a predicate based on typical request criteria such as
content type, or the existence of a header
or cookie. You can also construct a handler that only processes
requests accepted by the predicate. All other requests are _nexted_, meaning that they are routed to the next valid handler.

[source,java]
----
.post("/foo",
      RequestPredicate.create()
                      .containsHeader("my-gr8-header")
                      .accepts(MediaType.TEXT_PLAIN)
                      .and(this::isUserAuthenticated)
                      .thenApply((req, resp) -> {
                           // Some logic
                      })
                      .otherwise((req, resp) -> { /* Otherwise logic */ }); // Optional. Default logic is req.next()
----

=== Organizing Code into Services

By implementing the `Service` interface you can organize your code into one
or more services, each with its own path prefix and set of handlers.

[source,java]
.Use `Routing.Builder.register` to register your service
----
.register("/hello", new HelloService())
----

[source,java]
.Service implementation
----
public class HelloService implements Service {
    @Override
    public void update(Routing.Rules rules) {
        rules.get("/subpath", this::getHandler);
    }

    private void getHandler(ServerRequest request,
                            ServerResponse response) {
        // Some logic
    }
}
----
In this example, the `GET` handler matches requests to `/hello/subpath`.

== Request Handling

Implement the logic to handle requests to WebServer in a `Handler`, which is a `FunctionalInterface`.
Handlers:

* Process the request and <<anchor-sending-response,send>> a response.
* Act as a filter and forward requests to downstream handlers using the `request.next()`
method.
* Throw an exception or call `request.next(exception)` to begin
<<Error Handling,error handling>>.

=== Process Request and Produce Response
Each `Handler` has two parameters. `ServerRequest` and `ServerResponse`.

* Request provides access to the request method, URI, path, query parameters,
headers and entity.
* Response provides an ability to set response code, headers, and entity.

[[anchor-filtering]]
=== Handler as a Filter
The handler forwards the request to the downstream handlers by
_nexting_. There are two options:

* call `req.next()`
+
[source,java]
----
.any("/hello", (req, res) -> { // <1>
    // filtering logic  // <2>
    req.next(); // <3>
})
----
<1> handler for any HTTP method using the `/hello` path
<2> business logic implementation
<3> forward the current request to the downstream handler

* call `req.next(throwable)` to forward the handling to the
<<Error Handling,error handling>>
+
[source,java]
----
.any("/hello", (req, res) -> { // <1>
    // filtering logic (e.g., validating parameters) // <2>
    if (userParametersOk()) {
        req.next(); // <3>
    } else {
        req.next(new IllegalArgumentException("Invalid parameters."); // <4>
    }
})
----
<1> handler for any HTTP method using the `/hello` path
<2> custom logic
<3> forward the current request to the downstream handler
<4> forward the request to the error handler

The handling logic can explicitly forward the execution to a different thread.
This is the reason why returning from the handler can't automatically
trigger calling the next handler.

[[anchor-sending-response]]
=== Sending a response
To complete the request handling, you must send a response by calling the `res.send()` method.

[source,java]
----
.get("/hello", (req, res) -> { // <1>
    // terminating logic
    res.status(Http.Status.ACCEPTED_201);
    res.send("Saved!"); // <2>
})
----
<1> handler that terminates the request handling for any HTTP method using the `/hello` path
<2> send the response

=== Protocol Specific Routing
Handling routes based on the protocol version is possible by registering specific routes
on routing builder.

[source,java]
.Routing based on HTTP version
----
.routing(r -> r
        .get("/any-version", (req, res) -> res.send("HTTP Version " + req.version()))
        .route(Http1Route.route(GET, "/version-specific", (req, res) -> res.send("HTTP/1.1 route")))
        .route(Http2Route.route(GET, "/version-specific", (req, res) -> res.send("HTTP/2 route")))
)
----

While `Http1Route` for Http/1 is always available with Helidon webserver,
other routes like `Http2Route` for <<HTTP/2 Support, HTTP/2>> needs to be added as additional dependency.

== Requested URI Discovery
include::{requested-uri-discovery-inc}[tag=intro]

=== Setting Up Requested URI Discovery Programmatically
To set up requested URI discovery on the default socket for your server, use the link:{webserver-javadoc-base-url}/io/helidon/webserver/WebServer.Builder.html[`WebServer.Builder`]:
[source,java]
.Requested URI set-up for the default server socket
----
import io.helidon.common.configurable.AllowList;
import static io.helidon.webserver.SocketConfiguration.RequestedUriDiscoveryType.FORWARDED;
import static io.helidon.webserver.SocketConfiguration.RequestedUriDiscoveryType.X_FORWARDED;

AllowList trustedProxies = AllowList.builder()
        .addAllowedPattern(Pattern.compile("lb.+\\.mycorp\\.com"))
        .addDenied("lbtest.mycorp.com")
        .build(); // <1>

WebServer.Builder builder = WebServer.builder()
        .defaultSocket(s -> s
                .host("localhost")
                .port(0)
                .requestedUriDiscoveryTypes(List.of(FORWARDED, X_FORWARDED)) // <2>
                .trustedProxies(trustedProxies)) // <3>
        .addRouting(yourRouting)
        .config(serverConfig);
----
<1> Create the `AllowList` describing the intermediate networks nodes to trust and not trust. Presumably the `lbxxx.mycorp.com` nodes are trusted load balancers except for the test load balancer `lbtest`, and no other nodes are trusted.
`AllowList` accepts prefixes, suffixes, predicates, regex patterns, and exact matches.
See the link:{configurable-javadoc-base-url}/io/helidon/common/configurable/AllowList.html[`AllowList`] JavaDoc for complete information.
<2> Use `Forwarded` first, then try `X-Forwarded-*` on each request.
<3> Set the `AllowList` for trusted intermediaries.

If you build your server with additional sockets, you can control requested URI discovery separately for each.

=== Setting Up Requested URI Discovery using Configuration
include::{requested-uri-discovery-inc}[tag=config-example-intro]

[source,yaml]
.Configuring requested URI behavior
----
server:
  port: 0
  requested-uri-discovery:
    types: FORWARDED,X_FORWARDED
    trusted-proxies:
      allow:
        pattern: "lb.*\\.mycorp\\.com"
      deny:
        exact: "lbtest.mycorp.com""
----

=== Obtaining the Requested URI Information
Your code obtains the requested URI information from the Helidon server request object:

[source,java]
.Retrieving Requested URI Information
----
import io.helidon.common.http.UriInfo;

public class MyHandler implements Handler {

    @Override
    public void accept(ServerRequest req, ServerResponse res) {
        UriInfo uriInfo = req.requestedUri();
        // ...
    }
}
----
See the link:{common-http-javadoc-base-url}/io/helidon/common/http/UriInfo.html[`UriInfo`] JavaDoc for more information.

== Error Handling

=== Error Routing

You may register an error handler for a specific `Throwable` in the
`Routing.Builder` method.
[source,java]
----
Routing routing = Routing.builder()
                        .error(MyException.class, (req, res, ex) -> { // <1>
                            // handle the error, set the HTTP status code
                            res.send(errorDescriptionObject); // <2>
                        })
                        .build
----
<1> Registers an error handler that handles `MyException` that are thrown from the
upstream handlers
<2> Finishes the request handling by sending a response

Error handlers are called when

* an exception is thrown from a handler
* `req.next(ex)` is called, where `ex` is an instance of `Throwable`

As with the standard handlers, the error handler must either

* send a response
+
[source,java]
----
.error(MyException.class, (req, res, ex) -> {
    res.status(Http.Status.BAD_REQUEST_400);
    res.send("Unable to parse request. Message: " + ex.getMessage());
})
----
* or, forward the error handling to the downstream error handlers
+
[source,java]
----
.error(Throwable.class, (req, res, ex) -> {
    // some logic
    req.next(ex);
})
----

Error handling can't be forwarded to the standard
handlers. In fact, invoking `req.next(ex)` or `req.next()` in an error handler
are equivalent.

[source,java]
----
.error(Throwable.class, (req, res, ex) -> {
    if (condition) {
        req.next(ex); // <1>
    } else {
        req.next(); // <2>
    }
})
----
<1> Call a downstream error handler with the `Throwable` instance.
<2> Here, `req.next()` is the same as `req.next(ex)`. In both cases, the downstream error handler is called.

=== Default Error Handling
If no user-defined error handler is matched, or if the last error handler of the
exception called `req.next()`, then the exception is translated to an HTTP response as follows:

* Subtypes of `HttpException` are translated to their associated HTTP error codes.
+
[source,java]
.Reply with the `406` HTTP error code by throwing an exception
----
(req, res) -> throw new HttpException("Amount of money must be greater than 0.", Http.Status.NOT_ACCEPTABLE_406) // <1>
----

* Otherwise, the exceptions are translated to an Internal Server Error HTTP
error code `500`.

== Supported Technologies
== HTTP/2 Support

Helidon supports HTTP/2 upgrade from HTTP/1, HTTP/2 without prior knowledge
and HTTP/2 with ALPN over TLS.
HTTP/2 support is enabled in webserver by default when it's artifact is available on classpath.

=== Maven Coordinates
To enable HTTP/2 support add the following dependency to your project's `pom.xml`.

[source,xml]
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver-http2</artifactId>
</dependency>
----

== Static Content Support

Use the `io.helidon.webserver.staticcontent.StaticContentSupport` class to serve files and classpath resources.
`StaticContentSupport` can be created for any readable directory or classpath
context root and registered on a path in `Routing`.

You can combine dynamic handlers with `StaticContentSupport` objects: if no file matches the request path, then the request is forwarded to
the next handler.

=== Maven Coordinates

To enable Static Content Support add the following dependency to your project's `pom.xml`.

[source,xml]
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver-static-content</artifactId>
</dependency>
----

=== Registering Static Content

To register static content based on a file system (`/pictures`), and classpath (`/`):

[source,java]
----
Routing.builder()
       .register("/pictures", StaticContentSupport.create(Paths.get("/some/WEB/pics"))) // <1>
       .register("/", StaticContentSupport.builder("/static-content") // <2>
                                   .welcomeFileName("index.html") // <3>
                                   .build());
----
<1> Create a new `StaticContentSupport` object to serve data from the file system,
and associate it with the `"/pictures"` context path.
<2> Create a `StaticContentSupport` object to serve resources from the contextual
`ClassLoader`. The specific classloader can be also
defined. A builder lets you provide more configuration values.
<3> `index.html` is the file that is returned if a directory is requested.

A `StaticContentSupport` object can be created using `create(...)` factory methods or a
`builder`. The `builder` lets you provide more configuration values, including _welcome file-name_
and mappings of filename extensions to media types.

== Jersey (JAX-RS) Support

=== Maven Coordinates

To enable Jersey (JAX-RS) Support add the following dependency to your project's `pom.xml`.

[source,xml]
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver-jersey</artifactId>
</dependency>
----

=== JAX-RS Support
You can register a Jersey (JAX-RS) application at a _context root_ using the
`JerseySupport` class.

==== Registering a Jersey Application
To register a *Jersey* application at a context root, use the
`JerseySupport` class and its `JerseySupport.Builder` builder.

`JerseySupport` can register the JAX-RS resources directly.
[source,java]
.Jersey (JAX-RS) `HelloWorld` resource
----
@Path("/")
public class HelloWorld {

    @GET
    @Path("hello")
    public Response hello() {
        return Response.ok("Hello World!").build();
    }
}
----

[source,java]
.Registering the `HelloWorld` resource
----
Routing.builder()
       .register("/jersey", // <1>
                 JerseySupport.builder()
                              .register(HelloWorld.class) // <2>
                              .build())
       .build();
----
<1> Register the Jersey application at `/jersey` context root
<2> The Jersey `Application` stays hidden and consists of a single `HelloWorld`
resource class

As a result, an HTTP GET request to `/jersey/hello` would yield a `Hello World!`
response string.

===== Registering a JAX-RS Application
You can also register the JAX-RS `Application` object.
[source,java]
.Register the `HelloWorld` resource
----
Routing.builder()
       .register("/jersey", // <1>
                 JerseySupport.builder(new MyApplication()) // <2>
                              .build())
       .build();
----
<1> Register the Jersey application at `/jersey` context root
<2> `MyApplication` handles requests made to /jersey context root.

===== Accessing WebServer Internals from a JAX-RS Application

You can inject WebServer request and response objects into your
JAX-RS application using `@Context`.

[source,java]
.Injection of WebServer internal objects
----
@Path("/")
@RequestScoped
public class HelloWorld {
    @Context
    private ServerRequest request;

    @Context
    private ServerResponse response;
}
----

== JSON Support
The WebServer supports JSON-P. When enabled, you can send and
receive JSON-P objects transparently.

=== Maven Coordinates

To enable JSON Support add the following dependency to your project's `pom.xml`.

[source,xml]
----
<dependency>
    <groupId>io.helidon.media</groupId>
    <artifactId>helidon-media-jsonp</artifactId>
</dependency>
----

=== Usage

To enable JSON-P support, first register it with the web server.
Then you can add routes that handle and return JSON.

[source,java]
.Configure JsonpSupport and use it for reading and writing of entities
----
JsonpSupport jsonbSupport = JsonpSupport.create(); // <1>
WebServer webServer = WebServer.builder()
    .addMediaSupport(jsonpSupport) // <2>
    .build();
----
<1> Register JsonpSupport to enable transformation from and to `JsonObject` objects
<2> Register that JsonpSupport instance to enable automatic
deserialization of Java objects from and serialization of Java objects
to JSON.

[source,java]
.Handler that receives and returns JSON objects
----
private static final JsonBuilderFactory JSON_FACTORY = Json.createBuilderFactory(Collections.emptyMap()); // <1>

private void sayHello(ServerRequest req, ServerResponse res, JsonObject json) { // <2>
        JsonObject msg = JSON_FACTORY.createObjectBuilder()   // <3>
          .add("message", "Hello " + json.getString("name"))
          .build();
        res.send(msg);                            // <4>
}
----
<1> Using a `JsonBuilderFactory` is more efficient than `Json.createObjectBuilder()`
<2> JsonObject is passed to handler
<3> Create a JsonObject using JSON-P to hold return data
<4> Send JsonObject in response

[source,bash]
.Example of posting JSON to sayHello endpoint
----
curl --noproxy '*' -X POST -H "Content-Type: application/json" \
    http://localhost:8080/sayhello -d '{"name":"Joe"}'
----

[source, json]
.Response body
----
{"message":"Hello Joe"}
----

=== Configuring Json Reader/Writer factories
To configure JSON-P `JsonReaderFactory` and `JsonWriterFactory` that are used by
the `JsonpSupport` instance, create the `JsonpSupport` object:

[source,java]
.Create `JsonpSupport` with the provided configuration
----
JsonpSupport.create(Map.of(JsonGenerator.PRETTY_PRINTING, false));
----

== JSON-B Support
The WebServer supports the http://json-b.net/[JSON-B
specification]. When this support is enabled, Java objects will be
serialized to and deserialized from JSON automatically using
https://github.com/eclipse-ee4j/yasson[Yasson], an implementation of
the link:{jakarta-jsonb-spec-url}[JSON-B specification].

=== Maven Coordinates

To enable JSON-B Support add the following dependency to your project's `pom.xml`.

[source,xml]
----
<dependency>
    <groupId>io.helidon.media</groupId>
    <artifactId>helidon-media-jsonp</artifactId>
</dependency>
----

=== Usage
To enable JSON-B support, first create and register a
link:{media-jsonb-javadoc-base-url}/io/helidon/media/jsonb/JsonbSupport.html[`JsonbSupport`] instance with a
link:{webserver-javadoc-base-url}/io/helidon/webserver/WebServer.Builder.html[`WebServer.Builder`].

[source,java]
.Registration of the `JsonbSupport` via `WebServer`
----
JsonbSupport jsonbSupport = JsonbSupport.create(); // <1>
WebServer webServer = WebServer.builder()
    .addMediaSupport(jsonbSupport) // <2>
    .build();
----
<1> Create a `JsonbSupport` instance.  This instance may be
reused freely.
<2> Register that `JsonbSupport` instance to enable automatic
deserialization of Java objects from and serialization of Java objects
to JSON.

Now that automatic JSON serialization and deserialization facilities
have been set up, you can register a `Handler` that works with Java
objects instead of raw JSON.  Deserialization from and serialization
to JSON will be handled according to the
https://jcp.org/en/jsr/detail?id=367[JSON-B specification].

Suppose you have a `Person` class that looks like this:

[source,java]
.Hypothetical `Person` class
----
public class Person {

    private String name;

    public Person() {
        super();
    }

    public String getName() {
        return this.name;
    }

    public void setName(final String name) {
        this.name = name;
    }
}
----

Then you can set up a `Handler` like this:

[source,java]
.A `Handler` that works with Java objects instead of raw JSON
----
final Routing routing =
    routingBuilder.post("/echo", // <1>
                        Handler.create(Person.class, // <2>
                                       (req, res, person) -> res.send(person)))) // <3>
    .build();
----
<1> Set up a route for `POST` requests using the
link:{webserver-javadoc-base-url}/io/helidon/webserver/Routing.Builder.html#post-java.lang.String-io.helidon.webserver.Handler...-[`Routing.Builder#post(String, Handler...)` method]
<2> Use the
link:{webserver-javadoc-base-url}/io/helidon/webserver/Handler.html#create-java.lang.Class-io.helidon.webserver.Handler.EntityHandler-[`Handler#create(Class, Handler.EntityHandler)` method]
to install a `Handler.EntityHandler` that works with `Person` instances.
<3> This `Handler.EntityHandler` consumes a `Person` instance
(`person`) and simply echoes it back.  Note that there is no working
with raw JSON here.

[source,bash]
.Example of posting JSON to the `/echo` endpoint
----
curl --noproxy '*' -X POST -H "Content-Type: application/json" \
    http://localhost:8080/echo -d '{"name":"Joe"}'
{"name":"Joe"}
----

== Jackson Support
The WebServer supports
https://github.com/FasterXML/jackson#jackson-project-home-github[Jackson].
When this support is enabled, Java objects will be serialized to and
deserialized from JSON automatically using Jackson.

=== Maven Coordinates

To enable Jackson Support add the following dependency to your project's `pom.xml`.

[source,xml]
----
<dependency>
    <groupId>io.helidon.media</groupId>
    <artifactId>helidon-media-jackson</artifactId>
</dependency>
----

=== Usage
To enable Jackson support, first create and register a
link:{media-jackson-javadoc-base-url}/io/helidon/media/jackson/JacksonSupport.html[`JacksonSupport`]
instance with a
link:{webserver-javadoc-base-url}/io/helidon/webserver/WebServer.Builder.html[`WebServer.Builder`].

[source,java]
.Registration of the `JacksonSupport` via `WebServer`
----
JacksonSupport jacksonSupport = JacksonSupport.create(); // <1>
WebServer webServer = WebServer.builder()
    .addMediaSupport(jacksonSupport) // <2>
    .build();
----
<1> Create a `JacksonSupport` instance.  This instance may be
reused freely.
<2> Register that `JacksonSupport` instance to enable automatic
deserialization of Java objects from and serialization of Java objects
to JSON.

Now that automatic JSON serialization and deserialization facilities
have been set up, you can register a `Handler` that works with Java
objects instead of raw JSON.  Deserialization from and serialization
to JSON will be handled by
https://github.com/FasterXML/jackson#jackson-project-home-github[Jackson].

Suppose you have a `Person` class that looks like this:

[source,java]
.Hypothetical `Person` class
----
public class Person {

    private String name;

    public Person() {
        super();
    }

    public String getName() {
        return this.name;
    }

    public void setName(final String name) {
        this.name = name;
    }
}
----

Then you can set up a `Handler` like this:

[source,java]
.A `Handler` that works with Java objects instead of raw JSON
----
final Routing routing =
    routingBuilder.post("/echo", // <1>
                        Handler.create(Person.class, // <2>
                                       (req, res, person) -> res.send(person)))) // <3>
    .build();
----
<1> Set up a route for `POST` requests using the
link:{webserver-javadoc-base-url}/io/helidon/webserver/Routing.Builder.html#post-java.lang.String-io.helidon.webserver.Handler...-[`Routing.Builder#post(String, Handler...)` method]
<2> Use the
link:{webserver-javadoc-base-url}/io/helidon/webserver/Handler.html#create-java.lang.Class-io.helidon.webserver.Handler.EntityHandler-[`Handler#create(Class, Handler.EntityHandler)` method]
to install a `Handler.EntityHandler` that works with `Person` instances.
<3> This `Handler.EntityHandler` consumes a `Person` instance
(`person`) and simply echoes it back.  Note that there is no working
with raw JSON here.

[source,bash]
.Example of posting JSON to the `/echo` endpoint
----
curl --noproxy '*' -X POST -H "Content-Type: application/json" \
    http://localhost:8080/echo -d '{"name":"Joe"}'
----

[source, json]
.Response body
----
{"name":"Joe"}
----

== Access Log

Access logging in Helidon is done by a dedicated module that can be
added to WebServer and configured.

Access logging is a Helidon WebServer `Service` and as such is executed
in the order it is registered with WebServer routing.
This implies that if you register it last and another `Service` or
`Handler` finishes the request, the service will not be invoked.

To enable Access logging add the following dependency to project's `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.helidon.webserver</groupId>
    <artifactId>helidon-webserver-access-log</artifactId>
</dependency>
----


=== Configuring Access Log in your code

Access log is configured in your code by registering it as a service with `Routing`

[source,java]
----
Routing.builder()
    .register(AccessLogSupport.create(config.get("server.access-log")))
    .get("/greet", myService)
----

The order of registration is significant - make sure `AccessLogSupport` is registered first (even before security, tracing etc.).

=== Configuring Access Log in a configuration file

Access log can be configured as follows:

[source, yaml]
.Access Log configuration file
----
server:
  port: 8080
  access-log:
    format: "%h %l %u %t %r %s %b %{Referer}i"
----

All options shown above are also available programmatically when using builder.


include::{rootdir}/includes/server/access-log-config-common.adoc[leveloffset=+1]

== TLS Configuration

Configure TLS either programmatically, or by the Helidon configuration framework.

=== Configuring TLS in your code

To configure TLS in WebServer programmatically create your keystore configuration and pass it to the WebServer builder.

[source,java]
----
KeyConfig keyConfig = KeyConfig.keystoreBuilder()
                //Whether this keystore is also trust store
                .trustStore()
                //Keystore location/name
                .keystore(Resource.create("keystore.p12"))
                //Password to the keystore
                .keystorePassphrase("password")
                .build();

WebServer.builder()
         .tls(WebServerTls.builder()
               .trust(keyConfig)
               .privateKey(keyConfig)
               .build())
         .build();
----

=== Configuring TLS in the config file

It is also possible to configure TLS via the config file.

[source,yaml]
.WebServer TLS configuration file `application.yaml`
----
server:
  tls:
    #Truststore setup
    trust:
      keystore:
        passphrase: "password"
        trust-store: true
        resource:
          resource-path: "keystore.p12"
    #Keystore with private key and server certificate
    private-key:
      keystore:
        passphrase: "password"
        resource:
          resource-path: "keystore.p12"
----
Then, in your application code, load the configuration from that file.

[source,java]
.WebServer initialization using the `application.yaml` file located on the classpath
----
Config config = Config.create();
WebServer webClient = WebServer.create(routing, config.get("server"));
----
Or you can only create WebServerTls instance based on the config file.

[source,java]
.WebServerTls instance based on `application.yaml` file located on the classpath
----
Config config = Config.create();
WebServerTls.builder()
    .config(config.get("server.tls"))
    .build();
----

This can alternatively be configured with paths to PKCS#8 PEM files rather than KeyStores:

[source,yaml]
.WebServer TLS configuration file `application.yaml`
----
server:
  tls:
    #Truststore setup
    trust:
      pem:
        certificates:
          resource:
            resource-path: "ca-bundle.pem"
    private-key:
      pem:
        key:
          resource:
            resource-path: "key.pem"
        cert-chain:
          resource:
            resource-path: "chain.pem"
----

=== Configuration options

include::{rootdir}/config/io_helidon_webserver_WebServerTls.adoc[leveloffset=+2,tag=config]


== HTTP Compression

HTTP compression can improve bandwidth utilization and transfer speeds in certain scenarios. It
requires a few extra CPU cycles for compressing and uncompressing, but these can be offset
if data is transferred over low-bandwidth network links.

A client advertises the compression encodings it supports at request time, and the
WebServer responds by selecting an encoding it supports and setting it in a header,
effectively _negotiating_ the content encoding of the response. If none of the
advertised encodings is supported by the WebServer, the response is returned
uncompressed.

=== Configuring HTTP Compression

HTTP compression in the Helidon WebServer is _disabled_ by default. It can sometimes interfere
with certain applications that use streaming, even if a compression encoding has not been
negotiated with the client.

It can be enabled either programmatically or via configuration,
and it can also be enabled on a per-socket basis. When configured at the server level, it
applies only to the _default_ socket.

Programmatically, simply use the `enableCompression` method during server creation:

[source,java]
----
WebServer.builder()
         .port(8080)
         .routing(...)
         .enableCompression(true)        // compression enabled
         .build()
----

Or use a config file as follows and make sure the WebServer is created using it:

[source,yaml]
.WebServer HTTP Compression configuration file `application.yaml`
----
server:
  port: 8080
  enable-compression: true
----

=== HTTP Compression Negotiation

HTTP compression negotiation is controlled by clients using the `Accept-Encoding` header.
The value of this header is a comma-separated list of encodings. The WebServer
will select one of these encodings for compression purposes; it currently supports `gzip`
and `deflate`.

For example, if the request includes `Accept-Encoding: gzip, deflate`, and HTTP compression
has been enabled as shown above, the response shall include the header `Content-Encoding: gzip`
and a compressed payload.

== Additional Information

Here is the code for a minimalist web application that runs on a random free port:

[source,java]
----
public static void main(String[] args) {
    WebServer webServer = WebServer
            .create(Routing.builder()
                            .any((req, res) -> res.send("It works!"))) // <1>
            .start() // <2>
            .await(10, TimeUnit.SECONDS); // <3>

    System.out.println("Server started at: http://localhost:" + webServer.port()); // <4>
}
----

<1> For any kind of request, at any path, respond with `It works!`.
<2> Start the server.
<3> Wait for the server to start while throwing possible errors as runtime exceptions.
<4> The server is bound to a random free port.

== Reference

* link:{webserver-javadoc-base-url}/module-summary.html[Helidon WebServer JavaDoc]
* link:{webserver-staticcontent-javadoc-base-url}/module-summary.html[Helidon WebServer Static Content JavaDoc]
* link:{webserver-jersey-javadoc-base-url}/module-summary.html[Helidon WebServer Jersey JavaDoc]
* link:{media-jsonp-javadoc-base-url}/module-summary.html[Helidon JSON-B Support JavaDoc]
* link:{media-jsonb-javadoc-base-url}/module-summary.html[Helidon JSON-P Support JavaDoc]
* link:{media-jackson-javadoc-base-url}/module-summary.html[Helidon Jackson Support JavaDoc]
