///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

=== Configuration using Helidon Config [[Tracing-config]]

There is a set of common configuration options that this section describes. In addition each tracer implementation
may have additional configuration options - please see the documentation of each of them.

Each implementation may provide defaults for these options.

All common configuration options:
|===
|key |description

|service |Name of the service sending the tracing information. This is usually visible in the trace data to
distinguish actors in a conversation (e.g. when multiple microservices are connected together)
|protocol |Protocol of the tracing collector (e.g. `http`, `https`)
|host |Host of the tracing collector (e.g. `localhost`)
|port |Port of the tracing collector (e.g. `9411`)
|path |Path of the tracing collector service that is used to send spans to
|enabled |If set to false, tracing would be disabled
|tags |String tags that are to be added to each span reported (object node of string-string pairs)
|boolean-tags |Boolean tags that are to be added to each span reported (object node of string-boolean pairs)
|int-tags |Int tags that are to be added to each span reported (object node of string-int pairs)

|===