///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:description: Helidon metrics
:keywords: helidon, metrics, jaeger, tracing
:jaeger-doc-link: https://www.jaegertracing.io/docs/{jaeger-doc-version}/client-libraries
Integrate the metrics from Jaeger tracing into your Helidon {helidon-variant} application simply by adding a dependency.

== Overview
As the <<{helidon-jaeger-doc-link}, Helidon Jaeger Tracing>> document describes, you can use Jaeger tracing in your Helidon {helidon-variant} application.

Jaeger maintains several metrics about its own activity (briefly outlined in the link:{jaeger-doc-link}/#metrics[Jaeger client documentation]). This document explains how you can integrate those Jaeger tracing metrics with Helidon's metrics.

== Prerequisites
Your `pom.xml` file should already contain the dependency for Helidon-Jaeger tracing integration.

To enable integration with Jaeger's metrics, add the following dependency:

[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>io.helidon.metrics</groupId>
    <artifactId>helidon-metrics-jaeger</artifactId>
    <scope>runtime</scope>
</dependency>
----

You can leave your application's Java code unchanged.
By adding this dependency, you instruct Helidon to monitor the Jaeger tracing metrics internally and to publish them using the Helidon metrics system.

Rebuild and start your application.

== Accessing Jaeger Tracing Metrics
Submit a few requests to your application's endpoints.
This causes Jaeger to update its internal metrics.

Then, when you access your application's metrics endpoint (`/metrics` by default), Helidon displays the updated Jaeger tracing metrics as part of the `vendor` metrics section.

[source,bash]
----
curl -H "Accept: application/json" -X GET http://localhost:8080/metrics/vendor
----
[source,json]
.Partial Helidon Metrics `vendor` Output Showing Jaeger Metrics
----
 ... "jaeger_tracer_baggage_restrictions_updates;result=err": 0,
  "jaeger_tracer_baggage_restrictions_updates;result=ok": 0,
  "jaeger_tracer_baggage_truncations": 0,
  "jaeger_tracer_baggage_updates;result=err": 0,
  "jaeger_tracer_baggage_updates;result=ok": 0,
  "jaeger_tracer_finished_spans": 0,
  "jaeger_tracer_reporter_queue_length": 0,
  "jaeger_tracer_reporter_spans;result=dropped": 0,
  "jaeger_tracer_reporter_spans;result=err": 0,
  "jaeger_tracer_reporter_spans;result=ok": 0,
  "jaeger_tracer_sampler_queries;result=err": 1,
  "jaeger_tracer_sampler_queries;result=ok": 0,
  "jaeger_tracer_sampler_updates;result=err": 0,
  "jaeger_tracer_sampler_updates;result=ok": 0,
  "jaeger_tracer_span_context_decoding_errors": 0,
  "jaeger_tracer_started_spans;sampled=n": 15,
  "jaeger_tracer_started_spans;sampled=y": 0,
  "jaeger_tracer_traces;sampled=n;state=joined": 2,
  "jaeger_tracer_traces;sampled=n;state=started": 3,
  "jaeger_tracer_traces;sampled=y;state=joined": 0,
  "jaeger_tracer_traces;sampled=y;state=started": 0,
...
----
Helidon publishes whatever metrics Jaeger creates.
