///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2024 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= gRPC MP Server
:description: Helidon gRPC MicroProfile Server-Side Services
:keywords: helidon, java, grpc, microprofile, micro-profile, mp
:feature-name: gRPC MicroProfile Server
:rootdir: {docdir}/../..
:microprofile-bundle: false

include::{rootdir}/includes/mp.adoc[]

== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<API, API>>
- <<Usage, Usage>>
** <<Defining a Service, Defining a Service>>
** <<Using Custom Marshalers, Using Custom Marshalers>>
- <<Implementing a gRPC Extension, Implementing a gRPC Extension>>
- <<gRPC Reflection Service, gRPC Reflection Service>>
- <<Configuration, Configuration>>
- <<Examples, Examples>>

== Overview
The gRPC Microprofile API is an extension to xref:{rootdir}/mp/introduction.adoc[Helidon MP] to allow building
gRPC services that integrate with the Microprofile APIs. Using Helidon MP makes building gRPC services
easier when compared to the traditional approach. Services
can be built using POJOs that are then discovered and deployed at runtime in the same way Helidon MP
discovers and deploys other Web services.

Building gRPC services using Helidon gRPC MP is simple and allows developers to concentrate on their
application logic without the need to write a lot of boilerplate code.

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.grpc</groupId>
    <artifactId>helidon-microprofile-grpc-server</artifactId>
</dependency>
----

== API
All Helidon gRPC MP annotations are defined in the `Grpc` interface. The following annotations are
used to implement Helidon MP gRPC services:

* `@Grpc.GrpcService`: an annotation that marks a class as a gRPC service.

* `@Grpc.GrpcMarshaller`: an annotation on a type or method that specifies a named marshaller
supplier. This annotation is required when not using Protobuf serialization.

* `@Grpc.Proto`: an annotation for an optional method returning the Protobuf descriptor. For
more information see the <<gRPC Reflection Service, gRPC Reflection Service>>.

The following gRPC method types are supported:

* `@Grpc.Unary`: a method that takes a single value (or void) and returns a single value
(or void).

* `@Grpc.ServerStreaming`: a method that takes a single value (or void) and returns a
stream of values.

* `@Grpc.ClientStreaming`: a method that takes a stream of values and returns a single value (or void).

* `@Grpc.Bidirectional`: a method that takes a stream of values and returns a stream of values.

== Usage
=== Defining a Service

The traditional approach to building Java gRPC services is to write Protobuf files describing a
service, use these files to generate service stubs, and then implement the service methods
from stub classes. In Helidon MP, you have a simpler option of just writing normal POJOs that
refer to the Protobuf message types without the need to extend any generated stubs.

For example:

[source,java]
----
include::{sourcedir}/mp/grpc/GrpcSnippets.java[tag=snippet_1, indent=0]
----

Note that the message types in `Strings` are generated from a Protobuf file, but the class
itself is just a POJO that uses the Helidon MP annotations described above. In addition,
`@Grpc.Unary` overrides the Java method name to match that in the Protobuf file,
as shown next:

[source,protobuf]
----
syntax = "proto3";

service StringService {
  rpc Upper (StringMessage) returns (StringMessage) {}
}

message StringMessage {
  string text = 1;
}
----

=== Using Custom Marshalers

Even though it is recommended to use Protobuf message types, it is not mandatory. Traditional
Java types can be used as long as custom marshalers are provided. For instance, in the example
above we can use a `String` type instead of the generated type `StringMessage`, if we create
a marshaler for it. For example,

[source,java]
----
include::{sourcedir}/mp/grpc/GrpcSnippets.java[tag=snippet_2, indent=0]
----

In this example, the marshaler is provided using the name `"string"` and its supplier must
be discoverable via CDI. The following is an example of a marshaler and its supplier for the
`String` type:

[source,java]
----
include::{sourcedir}/mp/grpc/GrpcSnippets.java[tag=snippet_3_5, indent=0]
include::{sourcedir}/mp/grpc/GrpcSnippets.java[tag=snippet_3, indent=0]
----

Annotating the supplier with `@Dependent` ensures discoverability provided CDI is configured
to find all annotated beans in the corresponding `beans.xml` file.

== Implementing a gRPC Extension

When unable to annotate a service class &mdash;for example when the code is built by a third party&mdash;
another way to deploy non-CDI bean services is to implement a gRPC MP server extension.
Such an extension will be called when the MP server is starting and be given the chance to provide
additional services for deployment.
An extension must implement the `io.helidon.microprofile.grpc.server.spi.GrpcMpExtension` interface.

For example, assuming that there is a gRPC service class called `StringService` that needs to
be deployed, a gRPC server extension class might look like this:

[source,java]
----
include::{sourcedir}/mp/grpc/GrpcSnippets.java[tag=snippet_4, indent=0]
----

<1> The `configure` method of the extension will be called to allow the extension to add extra configuration to
the server.
<2> In this example, an instance of the `StringService` is registered with the routing, as
described in the xref:{rootdir}/se/grpc/server.adoc#_grpc_server_routing[gRPC Server Routing] documentation.

The `GrpcMpExtension` instances are discovered and loaded using the service loader, so for
this example above to work, a file
`META-INF/services/io.helidon.microprofile.grpc.server.spi.GrpcMpExtension`
would need to be created with the name of the extension shown above.

== gRPC Reflection Service

When a gRPC client interacts with a server, it needs to have access to the
Protobuf file to learn about the available services, methods and
message types in use. For many applications, this information is simply
_common knowledge_ between the two parties. However, in some cases, especially
while developing a new service, it is convenient to use tools such as `grpcurl`
or `Postman` to test a service.

Helidon includes a gRPC reflection service that can be queried by client tools
to learn about the available services &mdash;similar to
OpenAPI for REST services. The reflection service is implemented as a
_feature_ and can be enabled programmatically by adding the feature, or
via config as follows:

[source,yaml]
----
  features:
    grpc-reflection:
      enabled: true
----

For more information see xref:{rootdir}/se/grpc/server.adoc#_configuration[gRPC
Server Configuration].


In Helidon MP, annotated services must provide access to the underlying
Protobuf description to use the reflection service. Here is a modified
version of `StringService` that adds an annotated method returning the
descriptor:

[source,java]
----
include::{sourcedir}/mp/grpc/GrpcSnippets.java[tag=snippet_1_5, indent=0]
----

A method annotated by `@Grpc.Proto` must return type `Descriptors.FileDescriptor`;
such a descriptor is available from the Protobuf generated code, in this example,
the `Strings.getDescription()` method. The reflection service shall call this
method to provide service introspection to any clients that support the protocol.

== Configuration

At the time of writing, there is no configuration that is specific to
Helidon MP. For more information about gRPC configuration in SE, see
xref:{rootdir}/se/grpc/server.adoc#_configuration[gRPC Server Configuration].

== Examples

Please refer to the link:{helidon-github-examples-url}/microprofile/grpc[Helidon gRPC MP Example].
