/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

import javax.sql.DataSource;

import io.helidon.data.DataException;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import org.junit.jupiter.api.Test;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

class JdbcResourceOwnershipTest {

    @Test
    void returnsEveryConnectionAfterMaterializationAndMapperFailure() {
        try (HikariDataSource dataSource = dataSource()) {
            JdbcClient client = new JdbcClientImpl(dataSource);
            client.create("CREATE TABLE TEST_VALUE (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                  + "DATA_VALUE VARCHAR(40))")
                    .execute();
            JdbcClient.Rows<Long> generatedKeys = client.create("INSERT INTO TEST_VALUE(DATA_VALUE) VALUES (?)")
                    .bind(1, "value")
                    .generatedKeys()
                    .addColumn("ID")
                    .map(row -> row.required(1, Long.class));

            assertThat(dataSource.getHikariPoolMXBean().getActiveConnections(), is(0));
            assertThat(generatedKeys.one(), is(1L));
            assertThat(dataSource.getHikariPoolMXBean().getActiveConnections(), is(0));

            for (int count = 0; count < 20; count++) {
                assertThat(client.create("UPDATE TEST_VALUE SET DATA_VALUE = ? WHERE ID = ?")
                                   .bind(1, "value")
                                   .bind(2, 1L)
                                   .execute(),
                           is(1L));
                assertThat(client.create("SELECT DATA_VALUE FROM TEST_VALUE").map(String.class).list(),
                           is(List.of("value")));
                long key = client.create("INSERT INTO TEST_VALUE(DATA_VALUE) VALUES (?)")
                        .bind(1, "temporary")
                        .generatedKeys()
                        .addColumn("ID")
                        .map(row -> row.required(1, Long.class))
                        .one();
                assertThat(client.create("DELETE FROM TEST_VALUE WHERE ID = ?")
                                   .bind(1, key)
                                   .execute(),
                           is(1L));
                assertThat(dataSource.getHikariPoolMXBean().getActiveConnections(), is(0));
            }
            assertThrows(IllegalStateException.class,
                         () -> client.create("SELECT DATA_VALUE FROM TEST_VALUE")
                                 .map(row -> {
                                     throw new IllegalStateException("mapper failed");
                                 })
                                 .list());
            assertThrows(DataException.class,
                         () -> client.create("SELECT VALUE FROM TABLE_THAT_DOES_NOT_EXIST")
                                 .map(String.class)
                                 .list());

            assertThat(client.create("SELECT COUNT(*) FROM TEST_VALUE").map(Long.class).one(), is(1L));
            assertThat(dataSource.getHikariPoolMXBean().getActiveConnections(), is(0));
        }
    }

    @Test
    void oneConnectionPoolRemainsReusableAfterConnectionCleanupFailure() throws Exception {
        try (HikariDataSource pool = dataSource()) {
            JdbcClient setup = new JdbcClientImpl(pool);
            setup.create("DROP TABLE IF EXISTS TEST_VALUE").execute();
            setup.create("CREATE TABLE TEST_VALUE (ID BIGINT PRIMARY KEY, DATA_VALUE VARCHAR(40))").execute();
            setup.create("INSERT INTO TEST_VALUE VALUES (1, 'value')").execute();

            Connection pooledConnection = pool.getConnection();
            Connection failingConnection = new DelegatingConnection(pooledConnection) {
                @Override
                public void close() throws SQLException {
                    super.close();
                    throw new SQLException("connection close failed");
                }
            };
            AtomicBoolean firstBorrow = new AtomicBoolean(true);
            DataSource dataSource = mock(DataSource.class);
            when(dataSource.getConnection()).thenAnswer(invocation ->
                    firstBorrow.getAndSet(false) ? failingConnection : pool.getConnection());
            JdbcClient client = new JdbcClientImpl(dataSource);

            DataException failure = assertThrows(DataException.class,
                                                 () -> client.create("SELECT DATA_VALUE FROM TEST_VALUE")
                                                         .map(String.class)
                                                         .one());

            assertThat(failure.getCause().getMessage(), is("connection close failed"));
            assertThat(client.create("SELECT COUNT(*) FROM TEST_VALUE").map(Long.class).one(), is(1L));
            assertThat(pool.getHikariPoolMXBean().getActiveConnections(), is(0));
            assertThat(pool.getHikariPoolMXBean().getTotalConnections(), is(1));
        }
    }

    /**
     * Creates a one-connection pool so a leaked result cannot be hidden by a
     * second connection.
     *
     * @return test datasource
     */
    private static HikariDataSource dataSource() {
        HikariConfig config = new HikariConfig();
        config.setJdbcUrl("jdbc:h2:mem:jdbc_resource_ownership;DB_CLOSE_DELAY=-1");
        config.setMaximumPoolSize(1);
        config.setConnectionTimeout(1_000);
        return new HikariDataSource(config);
    }
}
