/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.math.BigDecimal;
import java.sql.JDBCType;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.OffsetTime;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicReference;

import io.helidon.data.DataException;
import io.helidon.data.NoResultException;
import io.helidon.data.NonUniqueResultException;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.hamcrest.CoreMatchers.instanceOf;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.not;
import static org.hamcrest.CoreMatchers.sameInstance;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;

class JdbcRunnerTest {
    private JdbcClient client;

    @BeforeEach
    void setUp() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:jdbc_runner;DB_CLOSE_DELAY=-1");
        try (var connection = dataSource.getConnection();
             var statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS POKEMON");
            statement.execute("CREATE TABLE POKEMON (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                      + "NAME VARCHAR(80))");
        }
        client = new JdbcClientImpl(dataSource);
    }

    @Test
    void executesUpdatesQueriesAndGeneratedKeys() {
        long first = client.create("INSERT INTO POKEMON(NAME) VALUES (?)")
                .bind(1, "Pikachu")
                .generatedKeys()
                .addColumn("ID")
                .map(row -> row.required(1, Long.class))
                .one();
        long second = client.create("INSERT INTO POKEMON(NAME) VALUES (?)")
                .bind(1, "Raichu")
                .generatedKeys()
                .map(row -> row.required("ID", Long.class))
                .one();

        assertThat(first, is(1L));
        assertThat(second, is(2L));
        assertThat(client.create("SELECT NAME FROM POKEMON ORDER BY ID").map(String.class).list(),
                   is(List.of("Pikachu", "Raichu")));
        assertThat(client.create("UPDATE POKEMON SET NAME = ? WHERE ID = ?")
                           .bind(1, "Pichu")
                           .bind(2, first)
                           .execute(),
                   is(1L));
        assertThat(client.create("SELECT NAME FROM POKEMON WHERE ID = ?")
                           .bind(1, first)
                           .map(String.class)
                           .optional(),
                   is(Optional.of("Pichu")));
    }

    @Test
    void validatesAndFinalizesGeneratedKeyConfiguration() {
        JdbcClient.GeneratedKeys keys = client.create("INSERT INTO POKEMON(NAME) VALUES ('Pichu')")
                .generatedKeys();

        assertThrows(NullPointerException.class, () -> keys.addColumn(null));
        assertThrows(IllegalArgumentException.class, () -> keys.addColumn(" "));
        keys.addColumn("ID");
        assertThrows(IllegalArgumentException.class, () -> keys.addColumn("id"));
        assertThrows(NullPointerException.class, () -> keys.map(null));

        JdbcClient.Rows<Long> rows = keys.map(row -> row.required(1, Long.class));

        assertThrows(IllegalStateException.class, () -> keys.addColumn("NAME"));
        assertThrows(IllegalStateException.class, () -> keys.map(row -> row.required(1, Long.class)));
        assertThat(rows.one(), is(1L));
    }

    @Test
    void bindsNullWithTheDeclaredJdbcType() {
        client.create("INSERT INTO POKEMON(NAME) VALUES (?)")
                .bindNull(1, JDBCType.VARCHAR)
                .execute();

        assertThat(client.create("SELECT COUNT(*) FROM POKEMON WHERE NAME IS NULL")
                           .map(Long.class)
                           .one(),
                   is(1L));
        assertThrows(NullPointerException.class,
                     () -> client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, null));
        assertThrows(IllegalArgumentException.class,
                     () -> client.create("INSERT INTO POKEMON(NAME) VALUES (?)")
                             .bindNull(1, JDBCType.NULL));
    }

    @Test
    void enforcesCardinalityAndSingleUseStages() {
        JdbcClient.Rows<String> empty = client.create("SELECT NAME FROM POKEMON").map(String.class);
        assertThrows(NoResultException.class, empty::one);

        client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, "one").execute();
        client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, "two").execute();
        assertThrows(NonUniqueResultException.class,
                     () -> client.create("SELECT NAME FROM POKEMON").map(String.class).one());
        assertThrows(NonUniqueResultException.class,
                     () -> client.create("SELECT NAME FROM POKEMON").map(String.class).optional());

        JdbcClient.Statement statement = client.create("DELETE FROM POKEMON WHERE ID = ?");
        statement.bind(1, 1L);
        statement.execute();
        assertThrows(IllegalStateException.class, statement::execute);
    }

    @Test
    void returnsAnImmutableMaterializedList() {
        client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, "one").execute();
        List<String> result = client.create("SELECT NAME FROM POKEMON").map(String.class).list();

        assertThat(result, is(List.of("one")));
        assertThrows(UnsupportedOperationException.class, () -> result.add("two"));
    }

    @Test
    void mapsEverySupportedScalarFamily() {
        assertScalar(Boolean.TRUE, Boolean.class);
        assertScalar((byte) 7, Byte.class);
        assertScalar((short) 8, Short.class);
        assertScalar(9, Integer.class);
        assertScalar(10L, Long.class);
        assertScalar(11.5F, Float.class);
        assertScalar(12.5D, Double.class);
        assertScalar(new BigDecimal("13.50"), BigDecimal.class);
        assertScalar("text", String.class);
        assertScalar(LocalDate.of(2026, 7, 25), LocalDate.class);
        assertScalar(LocalTime.of(10, 11, 12), LocalTime.class);
        assertScalar(LocalDateTime.of(2026, 7, 25, 10, 11, 12), LocalDateTime.class);
        assertScalar(OffsetTime.parse("10:11:12+05:30"), OffsetTime.class);
        assertScalar(OffsetDateTime.parse("2026-07-25T10:11:12+05:30"), OffsetDateTime.class);
        assertScalar(java.sql.Date.valueOf("2026-07-25"), java.sql.Date.class);
        assertScalar(Time.valueOf("10:11:12"), Time.class);
        assertScalar(Timestamp.valueOf("2026-07-25 10:11:12"), Timestamp.class);

        byte[] bytes = {1, 2, 3, 4};
        byte[] result = client.create("SELECT ?").bind(1, bytes).map(byte[].class).one();
        assertThat(result, is(bytes));
    }

    @Test
    void mapsSqlNullToEmptyOnlyForOptionalScalarResults() {
        assertThat(client.create("SELECT CAST(NULL AS VARCHAR)").map(String.class).optional(),
                   is(Optional.empty()));
        assertThat(client.create("SELECT NAME FROM POKEMON WHERE 1 = 0").map(String.class).optional(),
                   is(Optional.empty()));
        assertThrows(DataException.class,
                     () -> client.create("SELECT CAST(NULL AS VARCHAR)").map(String.class).one());
        assertThrows(DataException.class,
                     () -> client.create("SELECT CAST(NULL AS VARCHAR)").map(String.class).list());
    }

    @Test
    void confinesRowsToMapperInvocationAndRejectsNullMapperResults() {
        AtomicReference<JdbcClient.Row> escaped = new AtomicReference<>();

        assertThat(client.create("SELECT 'value'")
                           .map(row -> {
                               escaped.set(row);
                               return row.required(1, String.class);
                           })
                           .one(),
                   is("value"));
        assertThrows(IllegalStateException.class, () -> escaped.get().required(1, String.class));
        assertThrows(DataException.class,
                     () -> client.create("SELECT 'value'").map(row -> null).one());
    }

    @Test
    void permanentlyExpiresRowsBeforeAdvancingTheCursor() {
        client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, "one").execute();
        client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, "two").execute();
        AtomicReference<JdbcClient.Row> first = new AtomicReference<>();
        AtomicReference<JdbcClient.Row> second = new AtomicReference<>();

        try (var executor = Executors.newSingleThreadExecutor()) {
            List<String> names = client.create("SELECT NAME FROM POKEMON ORDER BY ID")
                    .map(row -> {
                        if (first.compareAndSet(null, row)) {
                            return row.required(1, String.class);
                        }
                        second.set(row);
                        assertThrows(IllegalStateException.class,
                                     () -> first.get().required(1, String.class));
                        CompletionException failure = assertThrows(
                                CompletionException.class,
                                () -> CompletableFuture.supplyAsync(
                                                () -> first.get().required(1, String.class),
                                                executor)
                                        .join());
                        assertThat(failure.getCause(), instanceOf(IllegalStateException.class));
                        return row.required(1, String.class);
                    })
                    .list();

            assertThat(names, is(List.of("one", "two")));
            assertThat(first.get(), not(sameInstance(second.get())));
            assertThrows(IllegalStateException.class, () -> first.get().required(1, String.class));
            assertThrows(IllegalStateException.class, () -> second.get().required(1, String.class));
        }
    }

    /**
     * Verifies one supported scalar through both value binding and column-one
     * result mapping.
     *
     * @param value scalar value
     * @param type scalar type
     * @param <T> scalar type
     */
    private <T> void assertScalar(T value, Class<T> type) {
        assertThat(client.create("SELECT ?").bind(1, value).map(type).one(), is(value));
    }
}
