///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= OpenAPI U/I
:toc:
:toc-placement: preamble
:description: Helidon MP OpenAPI U/I Support
:keywords: helidon, mp, openapi u/i
:rootdir: {docdir}/../..
:incdir: {rootdir}/includes/openapi
:openapi-inc: {incdir}/openapi.adoc
:ui-inc: {incdir}/openapi-ui.adoc
:feature-name: OpenAPI U/I support

include::{rootdir}/includes/mp.adoc[]
include::{rootdir}/includes/pages.adoc[]
:javadoc-path: {openapi-ui-javadoc-base-url}/io/helidon/integrations/openapi/ui
:openapi-javadoc-path: {openapi-javadoc-base-url}/io/helidon/openapi

include::{ui-inc}[tag=preamble]

include::{ui-inc}[tags=intro;overview]

include::{rootdir}/includes/dependencies.adoc[]

[source,xml]
----
    <dependency>
        <groupId>io.helidon.integrations.openapi-ui</groupId>
        <artifactId>helidon-integrations-openapi-ui-cdi</artifactId>
        <scope>runtime</scope>
    </dependency>
----

Also add the following dependency for OpenAPI support in your Helidon MP application.
[source,xml]
----
include::{openapi-inc}[tag=mp-depc]
----

include::{ui-inc}[tag=usage]

== API

Your Helidon MP application does not use any API to enable or control Helidon OpenAPI U/I support.
Adding the dependency as described earlier is sufficient, and you can control the U/I behavior using <<Configuration,configuration>>.

include::{ui-inc}[tag=config-intro]

For example, the following configuration changes the path where you access the U/I.

[source,properties]
.Example `META-INF/microprofile-config.properties` configuration changing the U/I URL
----
openapi.ui.web-context=/my-openapi-ui
----

include::{ui-inc}[tag=config-details]
