///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

=== Google Login Provider
:description: Helidon Security Google Login Provider
:keywords: helidon, security, google

Authenticates a token from request against Google identity provider

==== Setup

[source,xml]
.Maven dependency
----
<dependency>
    <groupId>io.helidon.security.providers</groupId>
    <artifactId>helidon-security-providers-google-login</artifactId>
</dependency>
----

[source,text]
.Provider class name
----
io.helidon.security.providers.google.login.GoogleTokenProvider
----

[source,text]
.Provider configuration key
----
google-login
----

==== Example code
https://github.com/oracle/helidon/tree/master/examples/security/google-login[]

[source,yaml]
.Configuration example
----
security:
  providers:
    - provider:
        client-id: "Google client id"
----

==== Configuration options
The following table shows all configuration options of the provider and their default values

[cols="2,2,5"]

|===
|key |default value |description

|`client-id` |{nbsp} |Client id of an application. To create an application, use
    the Google developer console (https://developers.google.com/identity/sign-in/web/sign-in)
|`optional` |`false` |If set to `true`, failure to authenticate will return `ABSTAIN` result instead of `FAILURE`. This is
    an important distinction when more than one provider is used
|`realm` |`helidon` |Realm used in the challenge when authentication is not provided and it is required
|`proxy-host` |none |Configuration of a proxy host to use when authenticating the user
|`proxy-port` |`80` |Proxy port
|`token` |`Authorization` header with `bearer` prefix |Configuration of the location of the token (see `TokenHandler`)
|`outbound` |{nbsp} |A list of outbound configurations
|`outbound.*.name` |{nbsp} |Required name of outbound configuration
|`outbound.*.username` |{nbsp} |Optional username used for outbound security; if not provided, current identity is propagated
|`outbound.*.password` |{nbsp} |Optional password used for outbound security
|`outbound.*.transports` |any transport |An array of transports this outbound configuration should be used for
|`outbound.*.hosts` |any host |An array of hosts this outbound configuration should be used for, can be a regular expression
|`outbound.*.paths` |any path |An array of paths this outbound configuration should be used for (such as `/greet`), can be a regular expression
|`outbound.*.methods` |any method |An array of HTTP methods this outbound configuration should be used for
|===

==== How does it work?
We expect to receive a token (with sufficient scopes) from the inbound request,
 such as when using the Google login button on a page.
The page has access to the token in javascript and can send it to backend with
every request in a header field (`Authorization` with `bearer ` prefix is assumed by default).

Once we receive the token in Helidon, we parse it and:

1. Validate if it timed out locally
2. Return a cached response (see `EvictableCache` with default values)
3. Otherwise verify using Google API - `GoogleIdTokenVerifier`

We build a subject from the Google token with the following attributes filled (if in token):

- userId
- email
- name
- emailVerified
- locale
- family_name
- given_name
- picture (URL)

*Outbound security*
The token will be propagated to outbound calls if an outbound target exists
that matches the invoked endpoint (see `outbound` configuration above).