///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

=== IDCS Role Mapper
:description: Helidon Security IDCS Role Mapper Provider
:keywords: helidon, security, idcs

A role mapper to retrieve roles from Oracle IDCS.

==== Setup

[source,xml]
.Maven dependency
----
<dependency>
    <groupId>io.helidon.security.providers</groupId>
    <artifactId>helidon-security-providers-idcs-mapper</artifactId>
</dependency>
----

[source,text]
.Provider class name
----
io.helidon.security.providers.idcs.mapper.IdcsRoleMapperProvider
----

[source,text]
.Provider configuration key
----
idcs-role-mapper
----

==== Example code
https://github.com/oracle/helidon/tree/master/examples/security/idcs-login/[]

[source,yaml]
.Configuration example
----
security:
  providers:
    - idcs-role-mapper:
        multitenant: false
        oidc-config:
            client-id: "client-id"
            client-secret: "client-secret"
            identity-uri: "IDCS identity server address"
----

==== Configuration options
The following table shows all configuration options of the provider and their default values

[cols="2,2,5"]

|===
|key |default value |description

|`multitenant` |`true` |Whether to support multi-tenancy with this provider
|`idcs-tenant-handler` |Header `X-USER-IDENTITY-SERVICE-GUID` |Multi-tenant specific `TokenHandler` configuration to retrieve the tenant id
|`idcs-app-name-handler` |Header `X-RESOURCE-SERVICE-INSTANCE-IDENTITY-APPNAME` |Multi-tenant specific `TokenHandler` configuration to retrieve the application name
|`cache-config` |{nbsp} |Configuration of cache of roles for subjects
|`cache-config.cache-enabled` |`true` |Possibility to disable the cache altogether
|`cache-config.max-size` |`100_000` |Maximal number of records in the cache
|`cache-config.cache-timeout-millis` |1 hour |Cache timeout in milliseconds
|`cache-config.cache-evict-delay-millis` |1 minute |How long to wait before starting the first eviction process
|`cache-config.cache-evict-period-millis` |5 minutes |Period of running the eviction process
|`cache-config.parallelism-threshold` |`10_000` |Threshold as used by `ConcurrentHashMap.forEachKey`
|`cache-config.evictor-class` |{nbsp} |Implementation of `BiFunction` that receives key and value, and returns `true` for records that should be removed
    from the cache. Eviction mechanism should be fast, as it is called within methods of `ConcurrentHashMap`
|`subject-types` |`USER` |Can use `USER` and/or `SERVICE`
|`default-idcs-subject-type` |`user` |Default subject type to use when requesting roles, can be `user` or `client`
|`oidc-config` |{nbsp} |`OidcConfig` configuration, except `validate-with-jwk` is set to `false`,
        and `server-type` is set to `idcs`
|===

==== How does it work?
The provider asks the IDCS server to provide list of roles for the currently
authenticated user.
The result is cached for a certain period of time (see `cache-config` above).

