///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

=== Provider
:description: Helidon Security ... Provider
:keywords: helidon, security

Short description

==== Setup

[source,xml]
.Maven dependency
----
<dependency>
    <groupId>io.helidon.security.providers</groupId>
    <artifactId>helidon-security-providers-</artifactId>
</dependency>
----

[source,text]
.Provider class name
----
io.helidon.security.providers.
----

[source,text]
.Provider configuration key
----
provider-config-key
----

==== Example code
https://github.com/oracle/helidon/tree/master/examples/security/[]

[source,yaml]
.Configuration example
----
security:
  providers:
    - provider:
        key: "value"
----

==== Configuration options
The following table shows all configuration options of the provider and their default values

[cols="2,2,5"]

|===
|key |default value |description

|`key` |{nbsp} |Description
|===

==== How does it work?
Detailed description

