///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= About Helidon MP
:description: about Helidon MP
:keywords: helidon, java, microservices, microprofile

== Helidon MP

Helidon is a collection of Java libraries for writing microservices. Helidon
offers two programming models: <<about/02_se-about.adoc,Helidon SE>>
and Helidon MP.

Helidon MP is an implementation of the
https://microprofile.io[MicroProfile]
https://github.com/eclipse/microprofile/releases[specification].
Helidon {helidon-version} supports MicroProfile {mp-version}. Since
MicroProfile has its roots in Java EE, you'll find that the MicroProfile
APIs follow a familiar, declarative approach with heavy use of annotations.
This makes it a good choice for Java EE developers.

== MicroProfile APIs

MicroProfile starts with a core of Java EE APIs, then defines a number
of new APIs to add capabilities you need for writing modern cloud native
applications:

* JAX-RS
* JSON-P
* JSON-B
* CDI
* MicroProfile Config
* MicroProfile Fault Tolerance
* MicroProfile Health
* MicroProfile JWT Authentication
* MicroProfile Metrics
* MicroProfile OpenAPI
* MicroProfile OpenTracing
* MicroProfile Rest Client

For more information see the Helidon MicroProfile <<microprofile/01_introduction,documentation>>
and <<guides/01_overview.adoc,guides>>.

== Helidon MP CDI Extensions

In addition to MicroProfile support, Helidon MP provides
<<extensions/01_overview.adoc,CDI extensions>> to address areas not
covered by MicroProfile. Examples include:

* DataSource for Oracle UCP and HikariCP
* JPA
* JTA

== No Application Server

Helidon is a collection of libraries that runs on top of Netty. It is not
derived from a Java EE application server. That means your cloud native
application is compact
and efficient without unnecessary overhead or bloat.

== Try it now

Try the <<guides/03_quickstart-mp.adoc,Helidon MP quickstart>> to get your
first Helidon MP application up and running in minutes.
