///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon on Windows
:description: Helidon on Windows
:keywords: windows

== Introduction

Most of the Helidon documentation is Linux/Mac/Unix centric. This document gives
some tips for Windows users.

== Prerequisites

Windows 10 is required.

For general pre-requisites like Java and Maven see <<about/03_prerequisites.adoc,Getting Started>>.
If you want to use the <<about/05_cli.adoc,Helidon CLI>> you'll also need to install the
Visual C++ Redistributable Runtime:

* https://aka.ms/vs/16/release/vc_redist.x64.exe[x64]
* https://aka.ms/vs/16/release/vc_redist.x86.exe[x86]

We also recommend installing the following from the Microsoft Store:

* PowerShell
* Windows Terminal

This document assumes you will be using PowerShell.

== Maven Quickstart Archetypes

=== Helidon SE

[source,bash,subs="attributes+"]
----
mvn "-U" "archetype:generate" "-DinteractiveMode=false" `
    "-DarchetypeGroupId=io.helidon.archetypes" `
    "-DarchetypeArtifactId=helidon-quickstart-se" `
    "-DarchetypeVersion={helidon-version}" `
    "-DgroupId=io.helidon.examples" `
    "-DartifactId=helidon-quickstart-se" `
    "-Dpackage=io.helidon.examples.quickstart.se"
----

You can then follow the instructions in the <<se/guides/02_quickstart.adoc,Helidon SE Quickstart>>. If
you do not have `curl` installed you can use `Invoke-WebRequest`:

[source,bash]
----
Invoke-WebRequest -Uri "http://localhost:8080/greet"
----


=== Helidon MP

[source,bash,subs="attributes+"]
----
mvn "-U" "archetype:generate" "-DinteractiveMode=false" `
    "-DarchetypeGroupId=io.helidon.archetypes" `
    "-DarchetypeArtifactId=helidon-quickstart-mp" `
    "-DarchetypeVersion={helidon-version}" `
    "-DgroupId=io.helidon.examples" `
    "-DartifactId=helidon-quickstart-mp" `
    "-Dpackage=io.helidon.examples.quickstart.mp"
----

You can then follow the instructions in the <<mp/guides/02_quickstart.adoc,Helidon MP Quickstart>>. If
you do not have `curl` installed you can use `Invoke-WebRequest`:

[source,bash]
----
Invoke-WebRequest -Uri "http://localhost:8080/greet"
----
