///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Kubernetes on your Desktop
:description: Running Kubernetes on your desktop.
:keywords: kubernetes

For development it's often convenient to run Kubernetes on your desktop.
Two popular ways to do this are with
https://kubernetes.io/docs/getting-started-guides/minikube/[Kubernetes Minikube]
or
https://docs.docker.com/docker-for-mac/kubernetes/[Kubernetes support in Docker
 for Desktop].

In this guide we'll use Docker for Desktop.

== Install

Install
https://docs.docker.com/docker-for-mac/install/[Docker for Mac] or
https://docs.docker.com/docker-for-windows/install/[Docker for Windows].

Starting with version 18.06 Docker for Desktop includes Kubernetes support.

== Enable Kubernetes Support

Enable
https://docs.docker.com/docker-for-mac/#kubernetes[Kubernetes Support for Mac]
or
https://docs.docker.com/docker-for-windows/#kubernetes[Kubernetes Support for
 Windows].

Once Kubernetes installation is complete, make sure you have your context
set correctly to use docker-for-desktop.

[source,bash]
.Make sure K8s context is set to docker-for-desktop
----
kubectl config get-contexts
kubectl config use-context docker-for-desktop
kubectl cluster-info
kubectl version --short
kubectl get nodes
----
