///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon Project Starter



https://helidon.io/starter[Helidon Project Starter] allows you to choose from a set of archetypes with pre-defined feature sets and lets you customize it by providing a host of options.

== Select a Flavor


=== Helidon SE

=== Helidon MP


== Choose an Application Type
Helidon provides the following set of archetypes to bootstrap your application development journey.

=== QuickStart 
This option creates a Helidon project that includes multiple REST operations along with default observability setup and a set of dependencies to enable ease of development e.g. in case of Helidon MP, it uses `helidon-microprofile` bundle instead of minimal `helidon-microprofile-core` bundle.

=== Database
This option builds on `QuickStart` to demonstrate how to integrate with database (in-memory H2, by default). In case of, Helidon SE that uses the DbClient API while for Helidon MP that uses JPA.

=== Custom
This option enables user to create Helidon project of their choice, suitable to start from scratch i.e. bare minimum, if default values are chosen Or choose from many options available.

=== OCI (MP Only)
This option builds on `QuickStart` to demonstrate integration with Oracle Cloud Infrastructure (OCI) services using the OCI SDK. Generated project showcases OpenApi-driven development approach where the practice of designing and building APIs is done first, then creating the rest of an application around them is implemented next. This is available for Helidon MP only.


== Media Support Options

=== Jackson JSON 

=== JSON-B
Default.

=== JSON-P (SE Only)

== Customize Project

* groupId
* artifactId
* Project Version
* Java package name

== Download the Project Files

Click *Download* and Project Starter generates the files in a directory named after the `artifactId` value. It mainly contains the following:

* Maven structure

* skeletal application code

* associated unit test code

* example Dockerfile files

* application configuration file(s)

* Readme file with instructions to build and run application/test





