///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Introducing Helidon 4
:description: Helidon
:keywords: helidon, java, microservices
:rootdir: {docdir}/..


== What's New in This Release

* We have removed the Netty-based Helidon __reactive__ WebServer and WebClient and replaced them with implementations based on virtual threads that have a _blocking_ style API.

NOTE: Virtual threads are lightweight threads that dramatically reduce the effort of writing, maintaining, and observing high-throughput concurrent applications. Learn more about using virtual threads https://openjdk.org/jeps/444[here]. 


* Helidon 4 now supports MicroProfile 5.0-based applications working on virtual threads. This is the first MicroProfile framework that supports virtual threads and uses JDK features on the new Helidon WebServer.




