///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018, 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Get Started
:description: Helidon pre-requisites and getting started
:keywords: helidon
:rootdir: {docdir}/..

include::{rootdir}/includes/attributes.adoc[]

Everything you need to get started with Helidon is listed here.

== Prerequisites

include::{rootdir}/about/introduction.adoc[tag=prereqs]

[source,bash]
.Verify Prerequisites
----
java -version
mvn --version
docker --version
kubectl version --short
----

== Setting `JAVA_HOME`

[source,bash]
.Setting `JAVA_HOME`
----
# On Mac
export JAVA_HOME=`/usr/libexec/java_home -v 21`

# On Linux
# Use the appropriate path to your JDK
export JAVA_HOME=/usr/lib/jvm/jdk-21
----

== Try the Quickstart Examples

Now you are ready to try the Quickstart Examples:

1. xref:../mp/guides/quickstart.adoc[Helidon MP Quickstart Example]
2. xref:../se/guides/quickstart.adoc[Helidon SE Quickstart Example]

TIP: See xref:introduction.adoc[About Helidon]
for more information on the differences between Helidon MP and SE.

TIP: See xref:windows.adoc[Helidon on Windows]
for some tips on using Helidon on Windows.
