///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= The ReSTful Web Service Guide
:description: Helidon guide restful web service
:keywords: helidon, guide, example

This guide describes how to create and build a ReSTful web service as your first Helidon application.

== What You Will Learn
You'll learn how to use Helidon quickly to create a ReSTful web service that accepts these HTTP requests:

|===
|Method and URL | Result

|`GET localhost:8080/greet` |Returns a friendly greeting
|`GET localhost:8080/greet/Joe` |Returns a personalized greeting for Joe
|`PUT localhost:8080/greet/greeting/Hola` |Changes the greeting used in subsequent responses
|===

== What You Need

|===
|About 10 minutes
|An IDE or text editor
|JDK 1.8 or later
|Maven 3.5 or later
|Docker 18.02 (use the Edge channel to run Kubernetes on your desktop)
|`kubectl` 1.7.4
|===

== Write Your Application
=== Create a new Maven Project
You can choose how to create your maven project and the app:

* use your IDE to create a new Java maven project,
* run the standard maven archetype to create a new Java project, or
* run the Helidon maven archetype (which also creates the completed example app).

==== Use your IDE
Use your IDE to create a new maven project for a Java SE application. 

==== Use the maven Java archetype

Run this command:
[source]
mvn archetype:generate -DarchetypeGroupId=org.apache.maven.archetypes -DarchetypeArtifactId=maven-archetype-quickstart -DarchetypeVersion=1.3
---

In either case make sure
the parent POM is set to the `io.helidon.guides:helidon-guides` artifact. That allows
you to take advantage of the parent's plug-in and dependency management settings
to simplify your own POM.

Make sure the Java version settings in the new `pom.xml` are set to `8`.

==== Run the Helidon maven archetype
Decide on the maven group and artifact ID you want for your new project and the
Java package you want to use for your code. Then run this command:

[source]
mvn archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-se \
    -DarchetypeVersion=0.10.1 \
    -DgroupId=your-group-ID \
    -DartifactId=your-artifact-ID \
    -Dpackage=your-package

---

== Build and Run


