///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon SE Introduction
:description: Helidon SE Introduction
:keywords: helidon, java, microservices, microprofile

== Helidon SE

Helidon is a collection of Java libraries for writing microservices. Helidon
offers two programming models: Helidion SE and <<mp/introduction/01_introduction.adoc,Helidon MP>>.

Helidon SE is a compact toolkit that embraces the latest Java SE features:
reactive streams, asynchrous and functional programming, and fluent style
APIs.

The REST framework for Helidon SE is the Helidon WebServer. It's built on top
of Netty and uses a straight forward request routing API and supports a
number of additional Helidon features:

* Config
* Security
* Health
* Metrics
* OpenAPI
* OpenTracing
* JSON-P
* JSON-B

For details see the Helidon <<about/01_overview.adoc,documentation>> and
<<se/guides/01_overview.adoc,guides>>.

== GraalVM Native Image support

Helidon SE supports https://www.graalvm.org[GraalVM]
https://www.graalvm.org/docs/reference-manual/native-image/[native images]
for small footprint and lightening fast startup. For more information see
the <<se/guides/36_graalnative.adoc,Graal native image guide>>.

== No Application Server

Helidon is a collection of libraries that runs on top of Netty.
It is not derived from a Java EE
application server. That means your cloud native application is compact
and efficient without unnecessary overhead or bloat.

== Try it now

Try the <<se/guides/02_quickstart.adoc,Helidon SE quickstart>> to get your
first Helidon SE application up and running in minutes.
