///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon SE
:description: Helidon SE Introduction
:keywords: helidon, java, microservices, microprofile
:pagename: about-helidon-SE
:description: Helidon SE introduction
:keywords: helidon, java, SE, microservices, Netty
:h1Prefix: SE

Helidon SE is a compact toolkit that embraces the latest Java SE features:
reactive streams, asynchrous and functional programming, and fluent-style
APIs.

== About Helidon SE Components

The REST framework for Helidon SE is the Helidon WebServer. It’s built on top of Netty and uses a straight forward request routing API and supports a number of additional Helidon features:


== Components

[PILLARS]
====
//aot
[CARD]
.Ahead-of-Time Compilation (AOT)
[icon=save,link=se/aot/01_introduction.adoc]
--
Use GraalVM native image to compile Helidon applications into a native executable. 
--
//config
[CARD]
.Config
[icon=settings,link=se/config/01_introduction.adoc]
--
A flexible configuration framework with support for multiple sources and
 formats.
--

//CORS
[CARD]
.CORS
[icon=share,link=se/cors/01_introduction.adoc]
--
Add support for CORS to your application using a Helidon module.
--
//DBClient
[CARD]
.DB Client
[icon=storage,link=se/dbclient/01_introduction.adoc]
--
Provides a unified, reactive API for working with databases in non-blocking way.
--

//gRPC
[CARD]
.gRPC
[icon=swap_horiz,link=se/grpc/01_introduction.adoc]
--
Build gRPC servers and clients.
--
//Health Checks
[CARD]
.Health Checks
[icon=favorite_outline,link=se/health/01_health.adoc]
--
Expose health statuses of your applications.
--
//Metrics
[CARD]
.Metrics
[icon=av_timer,link=metrics/01_metrics.adoc]
--
Instrumentation to expose metrics of your applications.
--
//Openapi
[CARD]
.OpenAPI
[icon=donut_large,link=se/openapi/01_openapi.adoc]
--
Support OpenAPI from your application.
--

//Reactive Messaging
[CARD]
.Reactive Messaging
[icon=message,link=se/se/reactivemessaging/01_introduction.adoc]
--
Use prepared tools for repetitive use case scenarios.
--

//Reactive Streams
[CARD]
.Reactive Streams
[icon=waves,link=se/se/reactivestreams/01_overview.adoc]
--
APIs to work with reactive streams in Helidon.
--
//Security
[CARD]
.Security
[icon=security,link=se/security/01_introduction.adoc]
--
A tool-chain to handle authentication, authorization and context propagation.
--
//Tracing
[CARD]
.Tracing
[icon=timeline,link=se/tracing/01_tracing.adoc]
--
Profile and monitor your applications across multiple services.
--
//WebClient
[CARD]
.WebClient
[icon=http,link=se/webclient/01_introduction.adoc]
--
HTTP client that handles responses to the HTTP requests in a reactive way.
--

//WebServer
[CARD]
.WebServer
[icon=settings_ethernet,link=se/webserver/01_introduction.adoc]
--
A programmatic HTTP API with reactive features, powered by Netty.
--
//WebSocket
[CARD]
.WebSocket
[icon=timeline,link=se/websocket/01_overview.adoc]
--
Enables Java applications to participate in WebSocket interactions as both servers and clients. 
--






====


== Next Steps

Try the Helidon SE quickstart guides to get your
first Helidon SE application up and running in minutes.

[PILLARS]
====
[CARD]
.Guides
[icon=explore,link=se/guides/01_overview.adoc]
--
Follow step-by-step guides to build your applications using Helidon SE.

--

[CARD]
.Javadocs
[icon=library_books,link=apidocs/index.html?overview-summary.html,link-type=url]
--
Browse the Helidon Javadocs.
--
====
