///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

:h1Prefix: SE
:javadoc-base-url-api: {javadoc-base-url}io.helidon.webclient/io/helidon/webclient
:description: Helidon WebClient TLS configuration
:keywords: helidon, se, rest, httpclient, webclient, reactive, tls

= WebClient TLS configuration

Configure the TLS either programmatically, or by the Helidon configuration framework.

== Configuring the TLS in your code

The one way to configure the TLS in WebClient is in your application code.

[source,java]
----
KeyConfig keyConfig = KeyConfig.keystoreBuilder()
                //Whether this keystore is also trust store
                .trustStore()
                //Keystore location/name
                .keystore(Resource.create("client.p12"))
                //Password to the keystore
                .keystorePassphrase("password")
                .build();

WebClient.builder()
         .tls(WebClientTls.builder()
               .certificateTrustStore(keyConfig)
               .clientKeyStore(keyConfig)
               .build())
         .build();
----

== Configuring the TLS in the config file

It is also possible to configure TLS via the config file.

[source,yaml]
.WebClient TLS configuration file `application.yaml`
----
webclient:
  tls:
    #Server part defines settings for server certificate validation and truststore
    server:
      keystore:
        passphrase: "password"
        trust-store: true
        resource:
          resource-path: "keystore.p12"
    #Client part defines access to the keystore with client private key or certificate
    client:
      keystore:
        passphrase: "password"
        resource:
          resource-path: "keystore.p12"
----
Then, in your application code, load the configuration from that file.

[source,java]
.WebClient initialization using the `application.yaml` file located on the classpath
----
Config config = Config.create();
WebClient webClient = WebClient.create(config.get("webclient"));
----
Or you can only create WebClientTls instance based on the config file.

[source,java]
.WebClientTls instance based on `application.yaml` file located on the classpath
----
Config config = Config.create();
WebClientTls.builder()
    .config(config.get("webclient.tls"))
    .build();
----

== Configuration options

See all configuration options
link:{javadoc-base-url-api}/WebClientTls.html[here].

Available server certificate configuration options:

[cols="^2s,<2,<2,<6"]
|===
|Configuration key |Default value ^|Java type  ^|Description

|`disable-hostname-verification` |false |boolean |Whether hostname verification should be performed
|`trust-all` |false |boolean |Whether all of the server certificates should be trusted
|`keystore` |{nbsp} |Object |Keystore configuration, please follow the example above
|===

Available client configuration options:

[cols="^2s,<2,<2,<6"]
|===
|Configuration key |Default value ^|Java type  ^|Description

|`keystore` |{nbsp} |Object |Keystore configuration, please follow the example above
|===