db:
  source: "mongoDb"
  connection:
    # docker run --rm --name mongo -p 27017:27017 mongo
    url: "mongodb://127.0.0.1:27017/pokemon"
  health-check:
    type: "query"
    statementName: "health-check"
  statements:
    create-types: "CREATE TABLE POKEMONTYPE (id INTEGER NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL)"
    create-pokemons: "CREATE TABLE POKEMON (id INTEGER NOT NULL PRIMARY KEY, name VARCHAR(64) NOT NULL, id_type INTEGER NOT NULL REFERENCES POKEMONTYPE(id))"
    # Select all types
    select-all-types: '{
            "collection": "POKEMONTYPE",
            "query": {}
        }'
    # Select all pokemons
    select-all-pokemons: '{
            "collection": "POKEMON",
            "query": {}
        }'
    # Select pokemon by id
    select-pokemon-by-id: '{
            "collection": "POKEMON",
            "query": {
              "id": $id
            }
        }'
    # Select pokemon by name
    select-pokemon-by-name: '{
            "collection": "POKEMON",
            "query": {
              "name": ?
            }
        }'
    # Insert records into database
    insert-type: '{
            "collection": "POKEMONTYPE",
            "value": {
                "id": ?,
                "name": ?
            }
        }'
    insert-pokemon: '{
            "collection": "POKEMON",
            "value": {
                "id": ?,
                "name": ?
                "id_type": ?
            }
        }'
    # Delete pokemon by id
    delete-pokemon-by-id: '{
            "collection": "POKEMON",
            "query": {
                "id": $id
            }
        }'
