db:
  source: jdbc
  connection:
    # docker run --rm --name xe -p 1521:1521 -p 8888:8080 -e ORACLE_PWD=oracle wnameless/oracle-xe-11g-r2
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: system
    password: oracle
    poolName: oracle
    initializationFailTimeout: -1
    connectionTimeout: 2000
    helidon:
      pool-metrics:
        enabled: true
        name-prefix: "hikari."
  services:
    metrics:
      - type: METER
  health-check:
    type: "dml"
    statementName: "ping"
  statements:
    # Ping statement
    ping: "SET @HELIDON_PING=0"
    create-table: "CREATE TABLE DOCUMENT (name VARCHAR(64) NOT NULL PRIMARY KEY, extension VARCHAR(64) NOT NULL)"
    select-all: "SELECT name, extension FROM DOCUMENT"
    insert: "INSERT INTO DOCUMENT(name, extension) VALUES(:name, :extension)"
    delete: "DELETE FROM DOCUMENT WHERE name = ?"
