db:
  source: "mongoDb"
  connection:
    url: "mongodb://127.0.0.1:27017/pokemon"
  health-check:
    type: "query"
    statementName: "health-check"
  statements:
    # Health check statement. HealthCheck statement type must be query.
    health-check: '{
            "operation": "command",
            "query": { ping: 1 }
        }'
    # Insert operation contains collection name, operation type and data to be inserted.
    # Name variable is stored as MongoDB primary key attribute _id
    insert2: '{
            "collection": "pokemons",
            "value": {
                "_id": $name,
                "type": $type
            }
        }'
    select-all: '{
            "collection": "pokemons",
            "query": {}
        }'
    select-one: '{
            "collection": "pokemons",
            "query": {
              "_id": ?
            }
        }'
    delete-all: '{
            "collection": "pokemons",
            "operation": "delete"
        }'
    update: '{
            "collection": "pokemons",
            "query": {
                "_id": $name
            },
            "value": {
                $set: { "type": $type }
            }
        }'
    delete: '{
            "collection": "pokemons",
            "query": {
                "_id": ?
            }
        }'
