db:
  source: "mongoDb"
  connection:
    url: "mongodb://127.0.0.1:27017/pokemon"
  health-check:
    type: "query"
    statementName: "health-check"
  statements:
    health-check: '{
            "operation": "command",
            "query": { ping: 1 }
        }'
    insert: '{
            "collection": "document",
            "value": {
                "_id": $name,
                "extension": $extension
            }
        }'
    select-all: '{
            "collection": "document",
            "query": {}
        }'
    delete: '{
            "collection": "document",
            "query": {
                "_id": ?
            }
        }'
