///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2023 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon Pico
:description: about Helidon Pico
:keywords: helidon, java, microservices, reactive, virtual threads





== Contents

- <<Overview, Overview>>
- <<Maven Coordinates, Maven Coordinates>>
- <<Usage, Usage>>
- <<API, API>>
- <<Configuration, Configuration>>
- <<Examples, Examples>>
- <<Additional Information, Additional Information>>

== Overview

Helidon Pico is an optional feature in Helidon that provides service registry, a lifecycle engine and extensibility for customized code generation. Foundationally, Pico provides a way to develop declarative code using standard Javax/Jakarta annotation types (not Helidon-specific). The Helidon Pico framework provides a mix of declarative and programmatic ways to build your application. 

Pico's minimalist, compile-time generated dependency injection (DI) framework and compile-time source code generation has a number of advantages, including:

* pre-runtime validation of the dependency injection model
* visibility into your application by providing "less magic" - understandability and debug-ability of your application
* deterministic behavior (instead of depending on reflection and classpath ordering, etc.)
* performance, since binding the model at compile-time is more efficient than computing it at runtime. 





== Maven Coordinates

To enable Pico add the following dependencies to your project's `pom.xml` (see Managing Dependencies).

.Pico dependencies
[source,java]

----
<dependency>
    <groupId>io.helidon.pico</groupId>
    <artifactId>helidon-pico-api</artifactId>
    <version>${helidon.version}</version>
</dependency>
<dependency>
    <groupId>io.helidon.pico</groupId>
    <artifactId>helidon-pico-types</artifactId>
    <version>${helidon.version}</version>
</dependency>
----

== Usage

Once you have planned how each of your resources should support Pico, you specify the Pico behavior in one of two ways:



== API

Adding Pico behavior to your Helidon application involves just a few simple steps.

=== Maven Coordinates

.Pico API pom.xml
[source, java]
----
 <artifactId>helidon-pico-api</artifactId>
 <name>Helidon Pico API</name>
----


=== Types

The Pico API provides types that are generally useful at compile time to assign special meaning to the type. In this way it also helps with readability and intentions of the code itself.

.Pico types pom.xml
[source, java]
----
 <artifactId>helidon-pico-types</artifactId>
 <name>Helidon Pico Types</name>
----


 * {@link io.helidon.pico.api.Contract} - signifies that the type can be used for lookup in the service registry.
 * {@link io.helidon.pico.api.ExternalContracts} - same as Contract, but applied to the implementation class instead.
 * {@link io.helidon.pico.api.RunLevel} - ascribes meaning for when the service should start.






== Configuration

Pico Config builder



== Examples

//optional 

== Additional Information




