/*
 * Copyright (c) 2024, 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.helidon.quic;

import java.nio.ByteBuffer;
import java.security.InvalidKeyException;
import java.security.Key;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;
import java.util.Arrays;
import java.util.Random;
import java.util.concurrent.atomic.AtomicLong;

import javax.crypto.KeyGenerator;
import javax.crypto.Mac;

import io.helidon.common.Api;

import static io.helidon.quic.QuicConnectionId.MAX_CONNECTION_ID_LENGTH;

/**
 * A class to generate connection ids bytes.
 * This algorithm is specific to our implementation - it's not defined
 * in any RFC (connection id bytes are free form).
 * For the purpose of validation we encode the length of
 * the connection id into the connection id bytes.
 * For the purpose of uniqueness we encode a unique id.
 * The rest of the connection id are random bytes.
 */
@Api.Internal
public class QuicConnectionIdFactory {
    private static final Random RANDOM = new SecureRandom();
    private static final String CLIENT_DESC = "QuicClientConnectionId";
    private static final String SERVER_DESC = "QuicServerConnectionId";

    private static final int MIN_CONNECTION_ID_LENGTH = 9;

    private final AtomicLong tokens = new AtomicLong();
    private final byte[] scrambler;
    private final Key statelessTokenKey;
    private final String simpleDesc;
    private final int connectionIdLength = RANDOM.nextInt(MIN_CONNECTION_ID_LENGTH, MAX_CONNECTION_ID_LENGTH + 1);
    private volatile boolean wrapped;

    private QuicConnectionIdFactory(String simpleDesc) {
        this.simpleDesc = simpleDesc;
        byte[] temp = new byte[MAX_CONNECTION_ID_LENGTH];
        RANDOM.nextBytes(temp);
        scrambler = temp;
        try {
            KeyGenerator kg = KeyGenerator.getInstance("HmacSHA256");
            statelessTokenKey = kg.generateKey();
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("HmacSHA256 key generator not available", e);
        }
    }

    /**
     * Create a factory configured for client-generated connection IDs.
     *
     * @return client connection-ID factory
     */
    public static QuicConnectionIdFactory client() {
        return new QuicConnectionIdFactory(CLIENT_DESC);
    }

    /**
     * Create a factory configured for server-generated connection IDs.
     *
     * @return server connection-ID factory
     */
    public static QuicConnectionIdFactory server() {
        return new QuicConnectionIdFactory(SERVER_DESC);
    }

    /**
     * The connection ID length used by this Quic instance.
     * This is the source connection id length for outgoing packets,
     * and the destination connection id length for incoming packets.
     *
     * @return the connection ID length used by this instance
     */
    public int connectionIdLength() {
        return connectionIdLength;
    }

    /**
     * Creates a new connection ID for a connection.
     *
     * @return a new connection ID
     */
    public QuicConnectionId newConnectionId() {
        long token = newToken();
        return new QuicLocalConnectionId(token, simpleDesc,
                                         newConnectionId(connectionIdLength, token));
    }

    /**
     * Returns a stateless reset token for the given connection ID.
     *
     * @param connectionId connection ID
     * @return stateless reset token for the given connection ID
     * @throws IllegalArgumentException if the connection ID was not generated by this factory
     */
    public byte[] statelessTokenFor(QuicConnectionId connectionId) {
        if (!(connectionId instanceof QuicLocalConnectionId)) {
            throw new IllegalArgumentException("Not a locally-generated connection ID");
        }
        Mac mac;
        try {
            mac = Mac.getInstance("HmacSHA256");
            mac.init(statelessTokenKey);
        } catch (NoSuchAlgorithmException | InvalidKeyException e) {
            throw new IllegalStateException("HmacSHA256 is not available", e);
        }
        byte[] result = mac.doFinal(connectionId.bytes());
        return Arrays.copyOf(result, 16);
    }

    /**
     * Allocate the next internal uniqueness token.
     *
     * @return next token value
     */
    public long newToken() {
        var token = tokens.incrementAndGet();
        if (token < 0) {
            token = -token - 1;
            wrapped = true;
        }
        return token;
    }

    /**
     * Create raw bytes for a new connection ID.
     *
     * @param length requested connection-ID length
     * @param token  uniqueness token to embed
     * @return encoded connection-ID bytes
     */
    public byte[] newConnectionId(int length, long token) {
        length = Math.clamp(length, MIN_CONNECTION_ID_LENGTH, MAX_CONNECTION_ID_LENGTH);
        byte[] bytes = new byte[length];
        RANDOM.nextBytes(bytes);

        if (token < 0) {
            token = -token - 1;
        }
        int len = variableLengthLength(token);

        bytes[0] = (byte) ((length << 3) & 0xF8);
        bytes[0] = (byte) (bytes[0] | len);
        int shift = 8 * len;
        for (int i = 0; i <= len; i++) {
            bytes[i + 1] = (byte) ((token >> shift) & 0xFF);
            shift -= 8;
        }
        for (int i = 0; i < length; i++) {
            bytes[i] = (byte) ((bytes[i] & 0xFF) ^ (scrambler[i] & 0xFF));
        }

        return bytes;
    }

    /**
     * Decode the connection-ID length encoded in the supplied bytes.
     *
     * @param bytes encoded connection-ID bytes
     * @return encoded connection-ID length
     */
    public int connectionIdLength(byte[] bytes) {
        var length = extractConnectionIdLength(bytes[0]);
        return length;
    }

    /**
     * Decode the uniqueness token encoded in the supplied connection-ID bytes.
     *
     * @param bytes encoded connection-ID bytes
     * @return embedded token value
     */
    public long connectionIdToken(byte[] bytes) {
        int len = extractTokenLength(bytes[0]);
        long token = 0;
        int shift = len * 8;
        for (int i = 0; i <= len; i++) {
            int j = i + 1;
            long l = ((bytes[j] & 0xFF) ^ (scrambler[j] & 0xFF)) & 0xFF;
            l = l << shift;
            token += l;
            shift -= 8;
        }
        return token;
    }

    QuicConnectionId unsafeConnectionIdFor(ByteBuffer buffer) {
        int expectedLength = connectionIdLength;

        int remaining = buffer.remaining();
        if (remaining < MIN_CONNECTION_ID_LENGTH) {
            return null;
        }
        if (remaining != expectedLength) {
            return null;
        }

        byte first = buffer.get(0);
        int len = extractConnectionIdLength(first);
        if (len < MIN_CONNECTION_ID_LENGTH) {
            return null;
        }
        if (len > MAX_CONNECTION_ID_LENGTH) {
            return null;
        }
        if (len != expectedLength) {
            return null;
        }

        long token = peekConnectionIdToken(buffer);
        if (!isValidToken(token)) {
            return null;
        }
        var cid = new QuicLocalConnectionId(buffer, token, simpleDesc);
        return cid;
    }

    ByteBuffer statelessReset(ByteBuffer connId, int length) {
        // 43 bytes max:
        //  first byte bits 01xx xxxx
        //  followed by random bytes
        //  terminated by 16 bytes reset token
        length = Math.min(length, 43);
        if (length < 21) { // minimum QUIC short datagram length
            return null;
        }

        var cid = (QuicLocalConnectionId) unsafeConnectionIdFor(connId);
        if (cid != null) {
            var localToken = statelessTokenFor(cid);
            ByteBuffer buf = ByteBuffer.allocate(length);
            buf.put((byte) (0x40 + RANDOM.nextInt(0x40)));
            byte[] random = new byte[length - 17];
            RANDOM.nextBytes(random);
            buf.put(random);
            buf.put(localToken);
            buf.flip();
            return buf;
        }
        return null;
    }

    private static int variableLengthLength(long token) {
        int len = 0;
        int shift = 0;
        for (int i = 1; i < 8; i++) {
            shift += 8;
            if ((token >> shift) == 0) {
                break;
            }
            len++;
        }
        return len;
    }

    private long peekConnectionIdToken(ByteBuffer bytes) {
        int len = extractTokenLength(bytes.get(0));
        long token = 0;
        int shift = len * 8;
        for (int i = 0; i <= len; i++) {
            int j = i + 1;
            long l = ((bytes.get(j) & 0xFF) ^ (scrambler[j] & 0xFF)) & 0xFF;
            l = l << shift;
            token += l;
            shift -= 8;
        }
        return token;
    }

    private boolean isValidToken(long token) {
        if (token < 0) {
            return false;
        }
        long prevToken = tokens.get();
        boolean wrapped = prevToken < 0 || this.wrapped;
        // if `tokens` has wrapped, we can say nothing...
        // otherwise, we can say it should not be coded on more bytes than
        // the previous token that was distributed
        if (!wrapped) {
            return token <= prevToken;
        }
        return true;
    }

    private int extractConnectionIdLength(byte b) {
        var bits = ((b & 0xFF) ^ (scrambler[0] & 0xFF)) & 0xFF;
        bits = bits >> 3;
        return bits;
    }

    private int extractTokenLength(byte b) {
        var bits = ((b & 0xFF) ^ (scrambler[0] & 0xFF)) & 0xFF;
        return bits & 0x07;
    }

    // A connection id generated by this instance.
    private static final class QuicLocalConnectionId extends QuicConnectionId {
        private final long token;
        private final String simpleDesc;

        // Connection Ids created with this constructor are safer
        // to use in maps as the buffer wraps a safe byte array in
        // this constructor.
        private QuicLocalConnectionId(long token, String simpleDesc, byte[] bytes) {
            super(ByteBuffer.wrap(bytes));
            this.token = token;
            this.simpleDesc = simpleDesc;
        }

        // Connection Ids created with this constructor are only
        // safe to use as long as the caller abstain from mutating
        // the provided byte buffer.
        // Typically, they will be transiently used to look up some
        // connection in a map indexed by a connection id.
        private QuicLocalConnectionId(ByteBuffer buffer, long token, String simpleDesc) {
            super(buffer);
            this.token = token;
            this.simpleDesc = simpleDesc;
        }

        @Override
        public String toString() {
            return "%s(length=%s, token=%s, hash=%s)"
                    .formatted(simpleDesc, length(), token, hashCode());
        }
    }
}
