#!/bin/bash
#
# Copyright (c) 2017, 2021 Oracle and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

export SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
export ETCD_DATA_DIRS=/tmp/etcd-data/config-gerrit-etcd-data-dirs
rm -rf $ETCD_DATA_DIRS
export CONTAINER_NAME="config-etcd"

docker rm -f $CONTAINER_NAME
export HOST_IP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`

docker run -d \
  -v $ETCD_DATA_DIRS:/var/data-dir \
  -p 2380:2380 \
  -p 2379:2379 \
  --name $CONTAINER_NAME \
  quay.io/coreos/etcd:v3.1.3 \
  etcd \
  -name etcd \
  -data-dir /var/data-dir \
  -advertise-client-urls http://$HOST_IP:2380 \
  -listen-client-urls http://0.0.0.0:2379 \
  -initial-advertise-peer-urls http://$HOST_IP:2380 \
  -listen-peer-urls http://0.0.0.0:2380

echo "Run with name $CONTAINER_NAME"

echo "Test:"
docker exec $CONTAINER_NAME /bin/sh -c "ETCDCTL_API=3 etcdctl put my-key my-value"
