#!/bin/bash
#
# Copyright (c) 2017, 2021 Oracle and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOST_IP=`ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'`
CONFIG_FILE="$SCRIPT_DIR/config.yaml"

if [ -f "$CONFIG_FILE" ]; then
    echo "Storing configuration into ETCD: $CONFIG_FILE"
    curl --noproxy $HOST_IP -vvv http://$HOST_IP:2379/v2/keys/comments-aas-config -XPUT --data-urlencode value@$CONFIG_FILE
else
    echo "Configuration file $CONFIG_FILE not found. DO NOT IMPORT INTO ETCD!"
fi
