/*
 * Copyright (c) 2026 Oracle and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.helidon.data.jdbc;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.OffsetDateTime;
import java.time.OffsetTime;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicReference;

import io.helidon.data.DataException;
import io.helidon.data.NoResultException;
import io.helidon.data.NonUniqueResultException;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.hamcrest.CoreMatchers.instanceOf;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.not;
import static org.hamcrest.CoreMatchers.sameInstance;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;

class JdbcRunnerTest {
    private JdbcClient client;

    @BeforeEach
    void setUp() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:jdbc_runner;DB_CLOSE_DELAY=-1");
        try (var connection = dataSource.getConnection();
             var statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS POKEMON");
            statement.execute("DROP TABLE IF EXISTS CASE_KEYS");
            statement.execute("CREATE TABLE POKEMON (ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                      + "NAME VARCHAR(80))");
            statement.execute("CREATE TABLE CASE_KEYS (\"ID\" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                                      + "\"id\" VARCHAR(80))");
        }
        client = new JdbcClientImpl(dataSource, JdbcConnectionLease.ownedProvider());
    }

    /**
     * Proves query, update, and generated-key terminals execute through the
     * same real-driver runner path.
     */
    @Test
    void executesUpdatesQueriesAndGeneratedKeys() {
        long first = client.create("INSERT INTO POKEMON(NAME) VALUES (?)")
                .bind(1, "Pikachu")
                .generatedKeys()
                .addColumn("ID")
                .map(row -> row.required(1, Long.class))
                .one();
        long second = client.create("INSERT INTO POKEMON(NAME) VALUES (?)")
                .bind(1, "Raichu")
                .generatedKeys()
                .map(row -> row.required("ID", Long.class))
                .one();

        assertThat(first, is(1L));
        assertThat(second, is(2L));
        assertThat(client.create("SELECT NAME FROM POKEMON ORDER BY ID").map(String.class).list(),
                   is(List.of("Pikachu", "Raichu")));
        assertThat(client.create("UPDATE POKEMON SET NAME = ? WHERE ID = ?")
                           .bind(1, "Pichu")
                           .bind(2, first)
                           .execute(),
                   is(1L));
        assertThat(client.create("SELECT NAME FROM POKEMON WHERE ID = ?")
                           .bind(1, first)
                           .map(String.class)
                           .optional(),
                   is(Optional.of("Pichu")));
    }

    /**
     * Proves generated-key column validation is immutable once mapping
     * finalizes the request.
     */
    @Test
    void validatesAndFinalizesGeneratedKeyConfiguration() {
        JdbcClient.GeneratedKeys keys = client.create("INSERT INTO POKEMON(NAME) VALUES ('Pichu')")
                .generatedKeys();

        NullPointerException nullColumn = assertThrows(NullPointerException.class, () -> keys.addColumn(null));
        assertThat(nullColumn.getMessage(), is("The generated column name must not be null."));
        IllegalArgumentException blankColumn = assertThrows(IllegalArgumentException.class,
                                                            () -> keys.addColumn(" "));
        assertThat(blankColumn.getMessage(), is("A generated column name must not be blank."));
        keys.addColumn("ID");
        keys.addColumn("id");
        IllegalArgumentException duplicateColumn = assertThrows(IllegalArgumentException.class,
                                                                () -> keys.addColumn("ID"));
        assertThat(duplicateColumn.getMessage(), is("The generated column name 'ID' is duplicated."));
        NullPointerException nullMapper = assertThrows(NullPointerException.class, () -> keys.map(null));
        assertThat(nullMapper.getMessage(), is("The generated key mapper must not be null."));

        JdbcClient.GeneratedKeys executableKeys = client.create("INSERT INTO POKEMON(NAME) VALUES ('Pichu')")
                .generatedKeys()
                .addColumn("ID");
        JdbcClient.Rows<Long> rows = executableKeys.map(row -> row.required(1, Long.class));

        IllegalStateException finalized = assertThrows(IllegalStateException.class,
                                                       () -> executableKeys.addColumn("NAME"));
        assertThat(finalized.getMessage(), is("Generated key mapping has already been selected."));
        IllegalStateException remapped = assertThrows(IllegalStateException.class,
                                                      () -> executableKeys.map(row -> row.required(1, Long.class)));
        assertThat(remapped.getMessage(), is("Generated key mapping has already been selected."));
        assertThat(rows.one(), is(1L));
    }

    /**
     * Proves quoted key columns that differ only by case remain distinct and
     * are returned in requested order by a supporting driver.
     */
    @Test
    void returnsCaseDistinctQuotedGeneratedColumns() {
        CaseDistinctKeys keys = client.create("INSERT INTO CASE_KEYS(\"id\") VALUES (?)")
                .bind(1, "lower-case value")
                .generatedKeys()
                .addColumn("ID")
                .addColumn("id")
                // JDBC name-based reads cannot distinguish these labels, but their ordinal positions remain exact.
                .map(row -> new CaseDistinctKeys(row.required(1, Long.class), row.required(2, String.class)))
                .one();

        assertThat(keys, is(new CaseDistinctKeys(1L, "lower-case value")));
    }

    /**
     * Proves singular cardinality and terminal-stage single-use rules against
     * actual result sets.
     */
    @Test
    void enforcesCardinalityAndSingleUseStages() {
        JdbcClient.Rows<String> empty = client.create("SELECT NAME FROM POKEMON").map(String.class);
        NoResultException emptyFailure = assertThrows(NoResultException.class, empty::one);
        assertThat(emptyFailure.getMessage(), is("The JDBC operation returned no rows."));

        client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, "one").execute();
        client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, "two").execute();
        NonUniqueResultException nonUnique = assertThrows(
                NonUniqueResultException.class,
                () -> client.create("SELECT NAME FROM POKEMON").map(String.class).one());
        assertThat(nonUnique.getMessage(), is("The JDBC operation returned more than one row."));
        assertThrows(NonUniqueResultException.class,
                     () -> client.create("SELECT NAME FROM POKEMON").map(String.class).optional());

        JdbcClient.Statement statement = client.create("DELETE FROM POKEMON WHERE ID = ?");
        statement.bind(1, 1L);
        statement.execute();
        IllegalStateException reused = assertThrows(IllegalStateException.class, statement::execute);
        assertThat(reused.getMessage(), is("A JDBC statement can perform only one terminal operation."));
    }

    /**
     * Proves list results are fully materialized and immutable after the JDBC
     * resources close.
     */
    @Test
    void returnsAnImmutableMaterializedList() {
        client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, "one").execute();
        List<String> result = client.create("SELECT NAME FROM POKEMON").map(String.class).list();

        assertThat(result, is(List.of("one")));
        assertThrows(UnsupportedOperationException.class, () -> result.add("two"));
    }

    /**
     * Proves every supported scalar family maps through a real H2 result set.
     */
    @Test
    void mapsEverySupportedScalarFamily() {
        assertScalar(Boolean.TRUE, Boolean.class);
        assertScalar((byte) 7, Byte.class);
        assertScalar((short) 8, Short.class);
        assertScalar(9, Integer.class);
        assertScalar(10L, Long.class);
        assertScalar(11.5F, Float.class);
        assertScalar(12.5D, Double.class);
        assertScalar(new BigDecimal("13.50"), BigDecimal.class);
        assertScalar("text", String.class);
        assertScalar(LocalDate.of(2026, 7, 25), LocalDate.class);
        assertScalar(LocalTime.of(10, 11, 12), LocalTime.class);
        assertScalar(LocalDateTime.of(2026, 7, 25, 10, 11, 12), LocalDateTime.class);
        assertScalar(OffsetTime.parse("10:11:12+05:30"), OffsetTime.class);
        assertScalar(OffsetDateTime.parse("2026-07-25T10:11:12+05:30"), OffsetDateTime.class);
        assertScalar(Date.valueOf("2026-07-25"), Date.class);
        assertScalar(Time.valueOf("10:11:12"), Time.class);
        assertScalar(Timestamp.valueOf("2026-07-25 10:11:12"), Timestamp.class);

        byte[] bytes = {1, 2, 3, 4};
        byte[] result = client.create("SELECT ?").bind(1, bytes).map(byte[].class).one();
        assertThat(result, is(bytes));
    }

    /**
     * Proves SQL NULL maps to empty only for optional scalar terminals and is
     * rejected for required scalar terminals.
     */
    @Test
    void mapsSqlNullToEmptyOnlyForOptionalScalarResults() {
        assertThat(client.create("SELECT CAST(NULL AS VARCHAR)").map(String.class).optional(),
                   is(Optional.empty()));
        assertThat(client.create("SELECT NAME FROM POKEMON WHERE 1 = 0").map(String.class).optional(),
                   is(Optional.empty()));
        assertThrows(DataException.class,
                     () -> client.create("SELECT CAST(NULL AS VARCHAR)").map(String.class).one());
        assertThrows(DataException.class,
                     () -> client.create("SELECT CAST(NULL AS VARCHAR)").map(String.class).list());
    }

    /**
     * Proves an explicit optional-valued mapper preserves row presence
     * separately from SQL nullability for imperative applications.
     */
    @Test
    void distinguishesNoRowSqlNullAndNonNullWithAnExplicitMapper() {
        Optional<Optional<String>> noRow = client.create("SELECT NAME FROM POKEMON WHERE 1 = 0")
                .map(row -> row.optional(1, String.class))
                .optional();
        Optional<Optional<String>> sqlNull = client.create("SELECT CAST(NULL AS VARCHAR)")
                .map(row -> row.optional(1, String.class))
                .optional();
        Optional<Optional<String>> value = client.create("SELECT 'Pikachu'")
                .map(row -> row.optional(1, String.class))
                .optional();

        assertThat(noRow, is(Optional.empty()));
        assertThat(sqlNull, is(Optional.of(Optional.empty())));
        assertThat(value, is(Optional.of(Optional.of("Pikachu"))));
    }

    /**
     * Proves row access is callback-scoped and a mapper returning null is
     * rejected without leaking its result set.
     */
    @Test
    void confinesRowsToMapperInvocationAndRejectsNullMapperResults() {
        AtomicReference<JdbcClient.Row> escaped = new AtomicReference<>();

        assertThat(client.create("SELECT 'value'")
                           .map(row -> {
                               escaped.set(row);
                               return row.required(1, String.class);
                           })
                           .one(),
                   is("value"));
        IllegalStateException expired = assertThrows(IllegalStateException.class,
                                                     () -> escaped.get().required(1, String.class));
        assertThat(expired.getMessage(), is("A JDBC row is valid only during its mapper callback."));
        DataException nullResult = assertThrows(DataException.class,
                                                () -> client.create("SELECT 'value'").map(row -> null).one());
        assertThat(nullResult.getMessage(), is("The JDBC row mapper returned null."));
    }

    /**
     * Proves a retained row facade expires before cursor advancement and can
     * never regain access to the underlying result set.
     */
    @Test
    void permanentlyExpiresRowsBeforeAdvancingTheCursor() {
        client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, "one").execute();
        client.create("INSERT INTO POKEMON(NAME) VALUES (?)").bind(1, "two").execute();
        AtomicReference<JdbcClient.Row> first = new AtomicReference<>();
        AtomicReference<JdbcClient.Row> second = new AtomicReference<>();

        try (var executor = Executors.newSingleThreadExecutor()) {
            List<String> names = client.create("SELECT NAME FROM POKEMON ORDER BY ID")
                    .map(row -> {
                        if (first.compareAndSet(null, row)) {
                            return row.required(1, String.class);
                        }
                        second.set(row);
                        assertThrows(IllegalStateException.class,
                                     () -> first.get().required(1, String.class));
                        CompletionException failure = assertThrows(
                                CompletionException.class,
                                () -> CompletableFuture.supplyAsync(
                                                () -> first.get().required(1, String.class),
                                                executor)
                                        .join());
                        assertThat(failure.getCause(), instanceOf(IllegalStateException.class));
                        return row.required(1, String.class);
                    })
                    .list();

            assertThat(names, is(List.of("one", "two")));
            assertThat(first.get(), not(sameInstance(second.get())));
            assertThrows(IllegalStateException.class, () -> first.get().required(1, String.class));
            assertThrows(IllegalStateException.class, () -> second.get().required(1, String.class));
        }
    }

    /**
     * Verifies one supported scalar through both value binding and column-one
     * result mapping.
     *
     * @param value scalar value
     * @param type scalar type
     * @param <T> scalar type
     */
    private <T> void assertScalar(T value, Class<T> type) {
        assertThat(client.create("SELECT ?").bind(1, value).map(type).one(), is(value));
    }

    private record CaseDistinctKeys(long upperCaseId, String lowerCaseId) {
    }
}
