///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020, 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon MP JPA
:toc:
:toc-placement: preamble
:spec-name: Jakarta Persistence
:description: {spec-name} support in Helidon MP
:keywords: helidon, mp, microprofile, persistence, database
:h1Prefix: MP

== Overview
Helidon MP supports JPA in much the same way that Java EE application
servers do, but with much less weight.  If you come from a Java EE
background, you'll feel right at home: you work with JPA in Helidon MP
in all the ways that you're familiar with.

For example, in Helidon MP's JPA integration, you can work with a
fully managed `EntityManager` by injecting it in the same way you
would in a Java EE application server:

[source,java]
----
@PersistenceContext
private EntityManager em;
----

The Jakarta Persistence API is a specification that governs how Java
objects map to relational databases, and has existed since 2006.
Hibernate and Eclipselink, two of the most popular JPA
implementations, are supported by Helidon MP JPA. 

== Next Steps
Learn more about the 
https://jcp.org/en/jsr/detail?id=338[Java Persistence API (JPA)]

Configure and use the Java Persistence API (JPA) from
within a Helidon MP application. <<mp/guides/09_jpa.adoc, Helidon MP JPA Guide>>.

