///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon MP JPA
:toc:
:toc-placement: preamble
:spec-name: Jakarta Persistence
:description: {spec-name} support in Helidon MP
:keywords: helidon, mp, microprofile, persistence, database
:h1Prefix: MP

== Overview
Helidon MicroProfile’s JPA support goes beyond the usual surface-level integration to give you the kind of managed support you are probably used to from the Java EE application server days. It does it transparently and using familiar tools. 




== Next Steps
Learn more about the 
https://jcp.org/en/jsr/detail?id=338[Java Persistence API (JPA)]

Configure and use the Java Persistence API (JPA) from
within a Helidon MP application. <<mp/guides/09_jpa.adoc, Helidon MP JPA Guide>>.

