///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2019, 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Overview
:h1Prefix: MP
:description: Helidon MP Guides
:keywords: helidon, java, microservices, microprofile, guides

== Getting Started

[PILLARS]
====
[CARD]
.Quickstart MP
[link=mp/guides/02_quickstart.adoc]
--
Create your first Helidon MP application in under 5 minutes.
--
====

== Helidon MP Guides

[PILLARS]
====
[CARD]
.MP Config Guide
[link=mp/guides/03_config.adoc]
--
Learn how to configure a Helidon MP application.
--

[CARD]
.MP Health Check Guide
[link=mp/guides/04_health.adoc]
--
Learn how to use Helidon MP built-in and custom health checks.
--

[CARD]
.MP Metrics Guide
[link=mp/guides/05_metrics.adoc]
--
Learn how to use Helidon MP built-in and application metrics.
--

[CARD]
.MP Tracing Guide
[link=mp/guides/06_tracing.adoc]
--
Learn how to trace a Helidon MP application.
--

[CARD]
.Using DataSources
[link=mp/guides/07_datasource.adoc]
--
Learn how to configure and use DataSources
in your Helidon MP application.
--

[CARD]
.Using Transactions
[link=mp/guides/08_jta.adoc]
--
Learn how to configure and use Java Transaction API (JTA)-compliant transactions
in your Helidon MP application.
--

[CARD]
.Using JPA
[link=mp/guides/09_jpa.adoc]
--
Learn how to configure and use the Java Persistence API (JPA)
in your Helidon MP application.
--

[CARD]
.Helidon MP Tutorial
[link=mp/guides/10_mp-tutorial.adoc]
--
Learn how to build a Helidon MicroProfile (MP) application from scratch.
--
====

== Build and Deploy

[PILLARS]
====
[CARD]
.Maven Guide
[link=mp/guides/25_maven_build.adoc]
--
Using Helidon in your Maven project.
--

[CARD]
.Gradle Guide
[link=mp/guides/26_gradle_build.adoc]
--
Using Helidon in your Gradle project.
--

[CARD]
.GraalVM Native Images
[link=mp/guides/36_graalnative.adoc]
--
Learn how to build a GraalVM native image for your Helidon application
both on your desktop and as part of a Docker image.
--

[CARD]
.Custom Runtime Images using jlink
[link=mp/guides/37_jlink_image.adoc]
--
Learn how to build a custom runtime Java image for your Helidon application
both on your desktop and as part of a Docker image.
--

[CARD]
.Building Container Images with Jib
[link=guides/32_jib.adoc]
--
Learn how to use Jib to create a container image without Docker.
--

[CARD]
.Deploying to OKE
[link=guides/34_Oracle_Kubernetes.adoc]
--
Learn how to deploy your application to Oracle Cloud Infrastructure Container
 Engine for Kubernetes (OKE).
--
====
