///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2020 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Helidon MP OIDC Security Provider
:h1Prefix: MP
:description: Helidon OIDC Security Provider guide
:keywords: helidon, security, guide, oidc, provider

This guide describes how to set up Keycloak and Helidon
to secure an application with OIDC security provider.

== What you need

[width=50%,role="flex, sm7"]
|===
|About 10 minutes
|<<about/03_prerequisites.adoc,Helidon Prerequisites>>
|===

=== Set up Keycloak

If Keycloak is not installed, please read its documentation. It is highly recommended following
the getting started guide.
This guide will describe the settings needed to secure your application
with Helidon OIDC security provider.

Once Keycloak is installed, navigate to the admin console. In the left column, click on `Clients`.
A table display all your clients. Push the `Create` button to create a new client.

Enter `myClientID` in the client ID field for testing purpose and make sure
the value of client protocol is `openid-connect`.
Choose `Valid Redirect URIs` according to your application settings.
If you do not have an application ready yet, enter `http://localhost:7987/*`. Press "+"
to add your choice and click on the `Save` button at the bottom of the page.

=== Set up Helidon

Use the Helidon MP Maven archetype to create a simple project. It will be used as an example
to show how to set up Helidon.

[source,bash,subs="attributes+"]
.Run the Maven archetype
----
mvn -U archetype:generate -DinteractiveMode=false \
    -DarchetypeGroupId=io.helidon.archetypes \
    -DarchetypeArtifactId=helidon-quickstart-mp \
    -DarchetypeVersion={helidon-version} \
    -DgroupId=io.helidon.examples \
    -DartifactId=helidon-quickstart-mp \
    -Dpackage=io.helidon.examples.quickstart.mp
----

[source,bash]
.The project will be built and run from the helidon-quickstart-mp directory:
----
cd helidon-quickstart-mp
----

==== Add OIDC security properties

The OIDC security provider properties can be joined to helidon property file.
So it can be easily used to configure the web server without modifying application code.

[source,yaml]
.Create application.yaml file and add the following line
----
security:
  providers:
  - abac:
      # Adds ABAC Provider - it does not require any configuration
  - oidc:
      client-id: "myClientID" // <1>
      client-secret: "secret"
      identity-uri: "http://localhost:8080/auth/realms/myrealm" // <2>
      audience: "account"
      # proxy-host should be defined if you operate behind a proxy, can be removed otherwise
      proxy-host: ""
      frontend-uri: "http://localhost:7987" // <3>
      server-type: "oidc"
  web-server:
    # protected paths on the web server
    paths:  // <4>
      - path: "/greet"
        methods: ["get"]
        authenticate: true
----
<1> `client-id` must be the same as the one configure in keycloak.
<2> `identity-uri` is used to redirect the user to keycloak.
<3> `frontend-uri` will direct you back to the application.
<4> `paths` section defines the protected application's path.

==== Try it !

[source,bash]
.Build the application, skipping unit tests, then run it:
----
mvn package -DskipTests=true
java -jar target/helidon-quickstart-mp.jar
----

The tests must be skipped, otherwise it produces test failure. As the `/greet` path is
now protected, its access is limited and the tests are not built to take oidc security in account.
