///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Performance Tuning
:description: Helidon MP Performance Tuning
:feature-name: Performance Tuning
:microprofile-bundle: true
:keywords: helidon, microprofile, micro-profile, performance, tuning
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

In this guide you fill find basic advice for performance tuning of your Helidon application. Most of them target Netty tuning, as Helidon is based on it.
You should also consider configuring/tuning Java heap size as per any Java application.


== Use `io.helidon.microprofile.bundles:helidon-microprofile-core`

Use `helidon-microprofile-core` dependency (and not the `helidon-microprofile` dependency) and add only what you use. For example:

[source,xml]
----
<dependency>
    <groupId>io.helidon.microprofile.bundles</groupId>
    <artifactId>helidon-microprofile-core</artifactId>
</dependency>
<dependency>
    <groupId>io.helidon.microprofile.metrics</groupId>
    <artifactId>helidon-microprofile-metrics</artifactId>
</dependency>
<dependency>
    <groupId>io.helidon.microprofile.health</groupId>
    <artifactId>helidon-microprofile-health</artifactId>
</dependency>
<dependency>
    <groupId>io.helidon.media</groupId>
    <artifactId>helidon-media-jsonp</artifactId>
</dependency>
----


== Configure Netty worker thread pool size

The Netty worker thread-pool is what handles your incoming requests. It defaults to 2*NCPU. To set it to something else you can set this property in `microprofile-config.properties`:

[source,properties]
----
server.worker-count=4
----


=== Configure Helidon server pool size

The Helidon server thread-pool takes requests from Netty and invokes your JAX-RS endpoints.  You can control lts configuration in `microprofile-config.properties`. This is Helidon MP specific only.

[source,properties]
----
server.executor-service.core-pool-size: 2
server.executor-service.max-pool-size: 4
----

To verify settings increase the log level for Helidon's executor service by adding this to your `logging.properties`:

[source,properties]
----
io.helidon.common.configurable.ThreadPool.level=FINE
----


=== Configure Netty's maxOrder (Helidon 2.4.1 or earlier)

In some situations Netty can aggressively allocate memory per request. This has been addressed in recent versions of Helidon and Netty, but if you are running an earlier version set this system property when you start your Helidon application:

```
-Dio.netty.allocator.maxOrder=6
```

You can try smaller numbers.
