///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= LRA
:toc:
:toc-placement: preamble
:description: Long Running Actions
:keywords: helidon, mp, lra
:h1Prefix: MP
:feature-name: Long Running Actions
:spec-version: 1.0-RC3
:spec-name: Micro Profile {feature-name} specification
:spec-link: https://download.eclipse.org/microprofile/microprofile-lra-{spec-version}/microprofile-lra-spec-{spec-version}.html
:common-deps-page-prefix-inc: ../../shared/dependencies/common_shared.adoc

include::{common-deps-page-prefix-inc}[tag=maven-dependency]
[source,xml]
----
<dependency>
  <groupId>io.helidon.microprofile.lra</groupId>
  <artifactId>helidon-microprofile-lra-client</artifactId>
</dependency>
<!-- Support for Narayana coordinator -->
<dependency>
  <groupId>io.helidon.microprofile.lra</groupId>
  <artifactId>helidon-microprofile-lra-client-narayana-adapter</artifactId>
</dependency>
----

== {feature-name} (LRA)
Distributed transactions for microservices are known as SAGA design patterns and are defined by the {spec-link}[{spec-name}]. 
Unlike well known XA protocol, LRA is asynchronous and therefore much more scalable. Every LRA JAX-RS resource (<<mp/lra/03_participant.adoc, participant>>) defines endpoints to be invoked when transaction needs to be <<mp/lra/03_participant.adoc#complete-participant-method, completed>> or <<mp/lra/03_participant.adoc#compensate-participant-method, compensated>>.

LRA transactions need to be coordinated over REST API by the LRA coordinator. <<mp/lra/02_coordinator.adoc, Coordinator>>
keeps track of all transactions and calls the @Compensate or @Complete endpoints for all participants involved in the particular 
transaction. LRA transaction is first started, then joined by <<mp/lra/03_participant.adoc, participant>>.
Participant reports the successful finish of transaction by calling complete. Coordinator then calls the JAX-RS 
<<mp/lra/03_participant.adoc#complete-participant-method, complete>> endpoint that was registered during the join of each 
<<mp/lra/03_participant.adoc, participant>>. As the completed or compensated participants don't have to be on same instance, 
the whole architecture is highly scalable.

image::lra/lra-complete-lb.svg[Complete]

In case of error during the LRA transaction, participant reports cancel of LRA to coordinator.
<<mp/lra/02_coordinator.adoc, Coordinator>> calls compensate on all the joined participants.

image::lra/lra-compensate-lb-error.svg[Cancel]

When participant joins the LRA with timeout defined `@LRA(value = LRA.Type.REQUIRES_NEW, timeLimit = 5, timeUnit = ChronoUnit.MINUTES)`, coordinator compensate if timeout occurs before close is reported by participants. 

image::lra/lra-compensate-lb-timeout.svg[Timeout]



=== Example
The following example shows how a simple LRA participant starts and joins a transaction after calling the '/start-example' resource.
When startExample method finishes successfully, close is reported to <<mp/lra/02_coordinator.adoc, coordinator>> 
and `/complete-example` endpoint is called by coordinator to confirm successful closure of the LRA.

If an exception occurs during startExample method execution, coordinator receives cancel call and `/compensate-example` 
is called by coordinator to compensate for cancelled LRA transaction. 

[source,java]
.Example of simple LRA participant
----
@PUT
@LRA(LRA.Type.REQUIRES_NEW) <1>
@Path("start-example")
public Response startExample(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId, <2>
                             String data) {
    if (data.contains("BOOM")) {
        throw new RuntimeException("BOOM 💥"); <3>
    }

    LOGGER.info("Data " + data + " processed 🏭");
    return Response.ok().build(); <4>
}

@PUT
@Complete <5>
@Path("complete-example")
public Response completeExample(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId) {
    LOGGER.log(Level.INFO, "LRA id: {0} completed 🎉", lraId);
    return LRAResponse.completed();
}

@PUT
@Compensate <6>
@Path("compensate-example")
public Response compensateExample(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId) {
    LOGGER.log(Level.SEVERE, "LRA id: {0} compensated 🦺", lraId);
    return LRAResponse.compensated();
}
----
<1> This JAX-RS PUT method will start new LRA transactions and join it before method body gets executed
<2> LRA id assigned by coordinator to this LRA transaction
<3> When method execution finishes exceptionally, cancel signal for this particular LRA is sent to coordinator 
<4> When method execution finishes successfully, complete signal for this particular LRA is sent to coordinator
<5> Method which will be called by coordinator when LRA is completed
<6> Method which will be called by coordinator when LRA is canceled

=== Configuration

[source,yaml]
.Example of lra configuration
----
mp.lra:
  coordinator.url: http://localhost:8070/lra-coordinator <1>
  propagation.active: true <2>
  participant.url: http://coordinator.visibe.host:80/awsomeapp <3>
----
<1> Url of coordinator
<2> Propagate LRA headers LRA_HTTP_CONTEXT_HEADER and LRA_HTTP_PARENT_CONTEXT_HEADER through non-LRA endpoints
<3> Url of the LRA enabled service overrides standard base uri,
so coordinator can call load-balancer instead of the service

For more information continue to {spec-link}[{spec-name}].