///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2021 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

///////////////////////////////////////////////////////////////////////////////

= Participant
:toc:
:toc-placement: preamble
:description: Long Running Actions
:keywords: helidon, mp, lra
:feature-name: Long Running Actions
:spec-version: 1.0-RC3
:javadoc-link: https://download.eclipse.org/microprofile/microprofile-lra-{spec-version}/apidocs/org/eclipse/microprofile/lra/annotation/
:rootdir: {docdir}/../..

include::{rootdir}/includes/mp.adoc[]

== Participant

The Participant, or Compensator, is an LRA resource with at least one of the JAX-RS(or non-JAX-RS) methods annotated with
link:{microprofile-lra-javadoc-url}Compensate.html[@Compensate] or link:{microprofile-lra-javadoc-url}AfterLRA.html[@AfterLRA].


=== @LRA [[lra-method]]

link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html[~javadoc~]

Marks JAX-RS method which should run in LRA context and needs to be accompanied by at least minimal set of mandatory
participant methods(<<compensate-participant-method,Compensate] or <<after-participant-method,AfterLRA]).

LRA options:

* link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#value--[value]
** link:{microprofile-lra-javadoc-url}/ws/rs/LRA.Type.html#REQUIRED[REQUIRED] join incoming LRA or create and join new
** link:{microprofile-lra-javadoc-url}/ws/rs/LRA.Type.html#REQUIRES_NEW[REQUIRES_NEW] create and join new LRA
** link:{microprofile-lra-javadoc-url}/ws/rs/LRA.Type.html#MANDATORY[MANDATORY] join incoming LRA or fail
** link:{microprofile-lra-javadoc-url}/ws/rs/LRA.Type.html#SUPPORTS[SUPPORTS] join incoming LRA or continue outside LRA context
** link:{microprofile-lra-javadoc-url}/ws/rs/LRA.Type.html#NOT_SUPPORTED[NOT_SUPPORTED] always continue outside LRA context
** link:{microprofile-lra-javadoc-url}/ws/rs/LRA.Type.html#NEVER[NEVER] Fail with 412 if executed in LRA context
** link:{microprofile-lra-javadoc-url}/ws/rs/LRA.Type.html#NESTED[NESTED] create and join new LRA nested in the incoming LRA context
* link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#timeLimit--[timeLimit] max time limit before LRA gets cancelled automatically by xref:coordinator.adoc[coordinator]
* link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#timeUnit--[timeUnit] time unit if the timeLimit value
* link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#end--[end] when false LRA is not closed after successful method execution
* link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#cancelOn--[cancelOn] which HTTP response codes of the method causes LRA to cancel
* link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#cancelOnFamily--[cancelOnFamily] which family of HTTP response codes causes LRA to cancel


Method parameters:

* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - id of the LRA transaction

[source,java]
----
@PUT
@LRA(LRA.Type.REQUIRES_NEW, timeLimit = 500, timeUnit = ChronoUnit.MILLIS)
@Path("start-example")
public Response startLra(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId, String data)
----

=== @Compensate [[compensate-participant-method]]

link:{microprofile-lra-javadoc-url}Compensate.html[~javadoc~]

WARNING: Expected to be called by LRA xref:coordinator.adoc[coordinator] only!

Compensate method is called by xref:coordinator.adoc[coordinator] when xref:introduction.adoc[LRA] is cancelled,
usually by error during execution of method body of <<lra-method,@LRA annotated method>>.
If the method responds with 500 or 202, coordinator will eventually try the call again.
If participant has <<status-participant-method,@Status annotated method>> xref:coordinator.adoc[coordinator]
retrieves the status to find out if retry should be done.


==== JAX-RS variant with supported LRA context values:

* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - id of the LRA transaction
* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_PARENT_CONTEXT_HEADER[LRA_HTTP_PARENT_CONTEXT_HEADER] - parent LRA id in case of nested LRA

[source,java]
----
@PUT
@Path("/compensate")
@Compensate
public Response compensateWork(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId,
                               @HeaderParam(LRA_HTTP_PARENT_CONTEXT_HEADER) URI parent){
    return LRAResponse.compensated();
}
----

==== Non JAX-RS variant with supported LRA context values:

* URI with LRA id

[source,java]
----
@Compensate
public void compensate(URI lraId)
----

=== @Complete [[complete-participant-method]]

{microprofile-lra-javadoc-url}Complete.html[~javadoc~]

WARNING: Expected to be called by LRA xref:coordinator.adoc[coordinator] only!

Complete method is called by xref:coordinator.adoc[coordinator] when LRA is successfully closed.
If the method responds with 500 or 202, coordinator will eventually try the call again.
If participant has <<status-participant-method,@Status annotated method>>, xref:coordinator.adoc[coordinator] retrieves the status to find out if retry should be done.

==== JAX-RS variant with supported LRA context values:

* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - id of the LRA transaction
* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_PARENT_CONTEXT_HEADER[LRA_HTTP_PARENT_CONTEXT_HEADER] - parent LRA id in case of nested LRA

[source,java]
----
@PUT
@Path("/complete")
@Complete
public Response complete(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId,
                         @HeaderParam(LRA_HTTP_PARENT_CONTEXT_HEADER) URI parentLraId)
----

==== Non JAX-RS variant with supported LRA context values:

* URI with LRA id

[source,java]
----
@Complete
public void complete(URI lraId)
----

=== @Forget

link:{microprofile-lra-javadoc-url}/Forget.html[~javadoc~]

WARNING: Expected to be called by LRA xref:coordinator.adoc[coordinator] only!

<<complete-participant-method,Complete] and <<complete-participant-method,compensate]
methods can fail(500) or report that compensation/completion is in progress(202).
In such case participant needs to be prepared to report its status over <<status-participant-method,@Status annotated method>> to xref:coordinator.adoc[coordinator].
When xref:coordinator.adoc[coordinator] decides all the participants have finished, method annotated with @Forget is called.

==== JAX-RS variant with supported LRA context values:

* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - id of the LRA transaction
* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_PARENT_CONTEXT_HEADER[LRA_HTTP_PARENT_CONTEXT_HEADER] - parent LRA id in case of nested LRA

[source,java]
----
@DELETE
@Path("/forget")
@Forget
public Response forget(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId,
                       @HeaderParam(LRA_HTTP_PARENT_CONTEXT_HEADER) URI parent)
----

==== Non JAX-RS variant with supported LRA context values:

* URI with LRA id

[source,java]
----
@Forget
public void forget(URI lraId)
}
----

=== @Leave

{microprofile-lra-javadoc-url}/ws/rs/Leave.html[~javadoc~]

Method annotated with @Leave called with LRA context(with header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER]) informs xref:coordinator.adoc[coordinator] that current participant is leaving the LRA.
Method body is executed after leave signal is sent.
As a result, participant methods complete and compensate won't be called when the particular LRA ends.

* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - id of the LRA transaction

[source,java]
----
@PUT
@Path("/leave")
@Leave
public Response leaveLRA(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraIdtoLeave)
----

=== @Status [[status-participant-method]]

link:{microprofile-lra-javadoc-url}Status.html[~javadoc~]

WARNING: Expected to be called by LRA xref:coordinator.adoc[coordinator] only!

If the coordinator's call to the participant's method fails, then it will retry the call.
If the participant is not idempotent, then it may need to report its state to coordinator by declaring method
annotated with @Status for reporting if previous call did change participant status.
xref:coordinator.adoc[Coordinator] can call it and decide if compensate or complete retry is needed.

==== JAX-RS variant with supported LRA context values:

* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_CONTEXT_HEADER[LRA_HTTP_CONTEXT_HEADER] - id of the LRA transaction
* link:{microprofile-lra-javadoc-url}ParticipantStatus.html[ParticipantStatus] - Status of the participant reported to xref:coordinator.adoc[coordinator]

[source,java]
----
@GET
@Path("/status")
@Status
public Response reportStatus(@HeaderParam(LRA_HTTP_CONTEXT_HEADER) URI lraId) {
    return Response.status(ParticipantStatus.FailedToCompensate).build();
}
----

==== Non JAX-RS variant with supported LRA context values:

* URI with LRA id
* link:{microprofile-lra-javadoc-url}ParticipantStatus.html[ParticipantStatus] - Status of the participant reported to xref:coordinator.adoc[coordinator]

[source,java]
----
@Status
public Response reportStatus(URI lraId){
    return Response.ok(ParticipantStatus.FailedToCompensate).build();
}
----

=== @AfterLRA [[after-participant-method]]

link:{microprofile-lra-javadoc-url}AfterLRA.html[~javadoc~]

WARNING: Expected to be called by LRA xref:coordinator.adoc[coordinator] only!

Method annotated with link:{microprofile-lra-javadoc-url}AfterLRA.html[@AfterLRA] in the same class as the one with @LRA annotation gets invoked after particular LRA finishes.

==== JAX-RS variant with supported LRA context values:

* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_ENDED_CONTEXT_HEADER[LRA_HTTP_ENDED_CONTEXT_HEADER] - id of the finished LRA transaction
* Header link:{microprofile-lra-javadoc-url}/ws/rs/LRA.html#LRA_HTTP_PARENT_CONTEXT_HEADER[LRA_HTTP_PARENT_CONTEXT_HEADER] - parent LRA id in case of nested LRA
* link:{microprofile-lra-javadoc-url}LRAStatus.html[LRAStatus] - Final status of the LRA (link:{microprofile-lra-javadoc-url}LRAStatus.html#Cancelled[Cancelled], link:{microprofile-lra-javadoc-url}LRAStatus.html#Closed[Closed], link:{microprofile-lra-javadoc-url}LRAStatus.html#FailedToCancel[FailedToCancel], {microprofile-lra-javadoc-url}LRAStatus.html#FailedToClose[FailedToClose])

[source,java]
----
@PUT
@Path("/finished")
@AfterLRA
public Response whenLRAFinishes(@HeaderParam(LRA_HTTP_ENDED_CONTEXT_HEADER) URI lraId,
                                @HeaderParam(LRA_HTTP_PARENT_CONTEXT_HEADER) URI parentLraId,
                                LRAStatus status)
----

==== Non JAX-RS variant with supported LRA context values:

* URI with finished LRA id
* link:{microprofile-lra-javadoc-url}LRAStatus.html[LRAStatus] - Final status of the LRA (link:{microprofile-lra-javadoc-url}LRAStatus.html#Cancelled[Cancelled], link:{microprofile-lra-javadoc-url}LRAStatus.html#Closed[Closed], link:{microprofile-lra-javadoc-url}LRAStatus.html#FailedToCancel[FailedToCancel], {microprofile-lra-javadoc-url}LRAStatus.html#FailedToClose[FailedToClose])

[source,java]
----
public void whenLRAFinishes(URI lraId, LRAStatus status)
----

