name: Assign Issue to Project

on:
  issues:
    types: [opened, reopened]
env:
  GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}


jobs:
  Assign-Issue-To-Backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: etc/scripts/actions/assign-issue-to-project.sh $GITHUB_REPOSITORY ${{ github.event.issue.number }} Backlog Triage
