name: Native image integration test

on: [push, pull_request]

#pull_request:
#  paths:
#    - 'native-image/*'
#    - 'webserver/*'
#    - 'security/*'
#    - 'common/*'
#    - 'config/*'
#    - 'health'
#    - 'integrations/graal/*'
#    - 'media/*'
#    - 'metrics/*'
#    - 'security/*'
#    - 'tests/integration/native-image'
#    - 'tracing/*'
#    - 'webserver/*'
#    - 'pom.xml'

jobs:
#  native_image_test_linux:
#    name: 'Test native image on Linux'
#    runs-on: ubuntu-latest
  native_image_test_mac:
    name: 'Test native image on Mac OS-X'
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build helidon
        run: mvn install -DskipTests
      - name: Install native image
        run: ./etc/scripts/native-image/install.sh https://github.com/oracle/graal/releases/download/vm-19.2.0/graalvm-ce-darwin-amd64-19.2.0.tar.gz graalvm-ce-darwin-amd64-19.2.0 graalvm-ce-19.2.0/Contents/Home/bin
      - name: Build native image
        run: ./etc/scripts/native-image/build-image.sh "examples/quickstarts/helidon-quickstart-se"
      - name: Test native image
        run: ./etc/scripts/native-image/test-quickstart-image.sh
