#
# Workflow that runs on any push to main.

name: "Post PR Merge"

on:
  push:
    branches:
      - 'main'
      - 'helidon-*.x'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  validate:
    uses: ./.github/workflows/validate.yml
  snapshot:
    needs: validate
    uses: ./.github/workflows/snapshotrelease.yaml
    secrets: inherit
