# Notes
# - cannot run on Windows, as we use shell scripts

name: "Release"

on:
  push:
    branches: [ 'release-*' ]

env:
  JAVA_VERSION: '11'
  JAVA_DISTRO: 'temurin'
  MVN_ARGS: |
    -B -fae -e -ntp
    -Dmaven.wagon.httpconnectionManager.ttlSeconds=60
    -Dmaven.wagon.http.retryHandler.count=3

concurrency:
  group: release-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  copyright:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v3.13.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Copyright
        run: etc/scripts/copyright.sh
  create-tag:
    runs-on: ubuntu-22.04
    environment: release
    outputs:
      version: ${{ steps.create-tag.outputs.version }}
      tag: ${{ steps.create-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
      - id: create-tag
        run: ./etc/scripts/release.sh create_tag >> "${GITHUB_OUTPUT}"
  release:
    needs: [ create-tag ]
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
          ref: ${{ needs.create-tag.outputs.tag }}
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - id: build
        env:
          GPG_PASSPHRASE: ${{ secrets.HELIDON_GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.HELIDON_GPG_PRIVATE_KEY }}
        shell: bash
        run: |
          etc/scripts/setup-gpg.sh
          mvn ${MVN_ARGS} \
            -Prelease,no-snapshots \
            -DskipTests \
            -DaltDeploymentRepository=":::file://${PWD}/staging" \
            deploy
      - id: upload
        shell: bash
        env:
          CENTRAL_USER: ${{ secrets.CENTRAL_USER }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        run: |
          etc/scripts/upload.sh upload_release \
            --dir="staging" \
            --description="Helidon v%{version}" >> ${GITHUB_OUTPUT}
      - uses: actions/upload-artifact@v4
        with:
          name: io-helidon-artifacts-${{ github.ref_name }}
          path: staging
          retention-days: 90
