# Notes
# - removed macos-latest from most jobs to speed up the process

name: "Validate"

on: [pull_request, push]

env:
  JAVA_VERSION: '21'
  JAVA_DISTRO: 'oracle'
  HELIDON_PIPELINES: 'true'
  MAVEN_HTTP_ARGS: '-Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Dmaven.wagon.http.retryHandler.count=3'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  copyright:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0
     - name: Set up JDK ${{ env.JAVA_VERSION }}
       uses: actions/setup-java@v4.1.0
       with:
         distribution: ${{ env.JAVA_DISTRO }}
         java-version: ${{ env.JAVA_VERSION }}
         cache: maven
     - name: Copyright
       run: etc/scripts/copyright.sh
  checkstyle:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Checkstyle
        run: etc/scripts/checkstyle.sh
  spotbugs:
    timeout-minutes: 45
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Spotbugs
        run: etc/scripts/spotbugs.sh
  docs:
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Docs
        run: etc/scripts/docs.sh
  build:
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2022 ]
        include:
          - os: ubuntu-20.04
            build_script: etc/scripts/github-build.sh
          - os: windows-2022
            build_script: etc/scripts/github-build.bat
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Maven Build
        run: ${{ matrix.build_script }}
      - name: Archive test results
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
         name: test-results
         path: |
           **/target/surefire-reports/*.txt
           **/target/it/**/*.log
  examples:
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-2022 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Maven build
        run: |
          mvn -B -e "-Dmaven.test.skip=true" $MAVEN_HTTP_ARGS -DskipTests -Ppipeline install 
          cd examples
          mvn -B verify
  mp-tck:
    timeout-minutes: 60
    name: "MicroProfile TCKs"
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Maven build
        run: etc/scripts/mp-tck.sh
  archetypes:
    timeout-minutes: 50
    strategy:
      matrix:
        os: [ ubuntu-20.04, windows-2022 ]
        include:
          - os: ubuntu-20.04
            test-archetypes: etc/scripts/test-archetypes.sh
          - os: windows-2022
            test-archetypes: etc/scripts/test-archetypes.bat
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4.1.0
        with:
          distribution: ${{ env.JAVA_DISTRO }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
      - name: Test archetypes
        run: ${{ matrix.test-archetypes }}
  packaging:
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-latest, windows-2022 ]
        include:
          - os: ubuntu-20.04
            compile: etc/scripts/github-compile.sh
            test-jar: etc/scripts/test-packaging-jar.sh
            test-jlink: etc/scripts/test-packaging-jlink.sh
            test-native: etc/scripts/test-packaging-native.sh
          - os: macos-latest
            compile: etc/scripts/github-compile.sh
            test-jar: etc/scripts/test-packaging-jar.sh
            test-jlink: etc/scripts/test-packaging-jlink.sh
            test-native: etc/scripts/test-packaging-native.sh
          - os: windows-2022
            compile: etc/scripts/github-compile.bat
            test-jar: etc/scripts/test-packaging-jar.bat
            test-jlink: etc/scripts/test-packaging-jlink.bat
            test-native: etc/scripts/test-packaging-native.bat
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: graalvm-community
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: true
          cache: maven
      - name: Build Helidon
        run: ${{ matrix.compile }}
      - name: JAR packaging
        run: ${{ matrix.test-jar }}
      - name: JLink packaging
        run: ${{ matrix.test-jlink }}
      - name: Native-Image packaging
        run: ${{ matrix.test-native }}
